/**
 * Hand-written concept MCQs. `ref` is a subtopic id (`${topicId}:${index}`) or
 * `pattern:<DSA pattern name>`. The correct option is listed first; the
 * generator shuffles options deterministically.
 */
export interface ConceptQuestion {
  ref: string;
  prompt: string;
  correct: string;
  wrong: [string, string, string];
  explanation: string;
}

export const CONCEPTS: ConceptQuestion[] = [
  // JavaScript
  { ref: "js-basics:0", prompt: "How do you run a file named app.js with Node?", correct: "node app.js", wrong: ["npm app.js", "run app.js", "npx app.js --node"], explanation: "The node binary takes a file path; running node with no arguments opens the REPL." },
  { ref: "js-basics:1", prompt: "Why default to const?", correct: "It prevents rebinding, which makes intent clear and avoids accidental reassignment", wrong: ["It makes objects deeply immutable", "It is always faster at runtime", "It hoists the value to the top of the scope"], explanation: "const stops reassignment of the binding; the object it points to can still be mutated." },
  { ref: "js-async:0", prompt: "What is the main problem with deeply nested callbacks?", correct: "Error handling and control flow get scattered and hard to follow", wrong: ["They always run synchronously", "They block the event loop", "They can't access outer variables"], explanation: "Promises and async/await flatten the flow and centralise error handling." },
  { ref: "js-async:4", prompt: "After the current synchronous code finishes, what runs next?", correct: "All queued microtasks, such as promise callbacks", wrong: ["The next setTimeout callback", "Pending I/O callbacks", "setImmediate callbacks"], explanation: "The microtask queue is drained completely before the event loop picks the next macrotask." },
  { ref: "js-async:8", prompt: "What does fetch do when its AbortSignal is aborted?", correct: "It rejects with an AbortError (DOMException)", wrong: ["It resolves with status 499", "It keeps running in the background and resolves later", "It throws synchronously at the call site"], explanation: "Pass AbortSignal.timeout(ms) or a controller's signal to cancel requests." },
  { ref: "js-async:9", prompt: "A promise pool with concurrency 3 processes 10 tasks. How many run at once, at most?", correct: "3", wrong: ["10", "1", "One per CPU core"], explanation: "A pool starts a new task only when one of the 3 in-flight tasks settles." },
  { ref: "js-async:9", prompt: "Exponential backoff with a 100 ms base waits how long before retries 1 to 4?", correct: "100, 200, 400, 800 ms (ideally plus random jitter)", wrong: ["100, 100, 100, 100 ms", "100, 200, 300, 400 ms", "800, 400, 200, 100 ms"], explanation: "Each retry doubles the delay; jitter spreads retries so clients don't stampede together." },
  { ref: "js-functions:4", prompt: "A memoize helper is a good fit for…", correct: "Pure functions called repeatedly with the same arguments", wrong: ["Functions that write to a database", "Functions that return random values", "Requests that must always fetch fresh data"], explanation: "Memoization caches results by arguments, which is only safe when the output depends only on the input." },
  { ref: "js-advanced:1", prompt: "What does an async generator give a for await...of loop?", correct: "One value per iteration, awaiting each next() promise", wrong: ["An array of all values at once", "Only the final return value", "A Node.js stream object"], explanation: "Async generators are ideal for paginated APIs and streaming data." },
  { ref: "js-advanced:2", prompt: "Which statement about ES modules vs CommonJS is true?", correct: "ESM imports are static and hoisted; require() is an ordinary runtime call", wrong: ["require() supports top-level await", "CommonJS exports are live bindings, ESM exports are copies", "Node can't run ESM without a bundler"], explanation: "Static imports enable tree-shaking and top-level await; ESM exports are live bindings." },
  { ref: "js-advanced:2", prompt: 'What does "type": "module" in package.json do?', correct: "Treats .js files in the package as ES modules", wrong: ["Bundles the package with esbuild", "Enables TypeScript compilation", "Forces .mjs files to be CommonJS"], explanation: "Without it, .js is CommonJS; .mjs and .cjs always force a format." },
  { ref: "js-advanced:5", prompt: "Which is a classic memory leak in a long-running Node server?", correct: "A module-level Map cache that grows without eviction", wrong: ["A local variable inside a request handler", "Using const instead of let", "Calling a function recursively 10 times"], explanation: "Anything reachable from module scope is never collected; bound caches with LRU/TTL." },
  { ref: "js-objects:7", prompt: "Why can a WeakMap help avoid memory leaks?", correct: "Its keys are held weakly, so entries disappear when the key object is garbage-collected", wrong: ["It compresses its values", "It caps itself at 100 entries", "It stores data on disk"], explanation: "WeakMap is perfect for per-object metadata that shouldn't keep the object alive." },
  { ref: "js-advanced:8", prompt: "What are V8 hidden classes (shapes) for?", correct: "Fast property access through inline caches when objects share a layout", wrong: ["Hiding private fields", "Garbage-collecting unused classes", "Compiling TypeScript types"], explanation: "Objects created with the same properties in the same order share a shape, so lookups stay monomorphic and fast." },
  { ref: "js-advanced:8", prompt: "Which habit keeps V8 objects fast?", correct: "Initialise all properties in the constructor, in the same order", wrong: ["Add and delete properties dynamically later", "Wrap every object in a Proxy", "Use arguments.callee"], explanation: "Changing shapes (adding/deleting properties) makes call sites polymorphic and slower." },
  { ref: "js-advanced:6", prompt: "In Node's EventEmitter, what happens when 'error' is emitted with no listener?", correct: "The error is thrown and can crash the process", wrong: ["It is silently ignored", "It is logged as a warning only", "It is queued until a listener is added"], explanation: "Always attach an 'error' listener to emitters and streams." },

  // TypeScript
  { ref: "ts:0", prompt: "When do you need a type alias rather than an interface?", correct: "For unions, e.g. type Id = string | number", wrong: ["For plain object shapes", "For classes to implement", "For declaration merging"], explanation: "Interfaces describe object shapes and can merge; unions, tuples and mapped types need type aliases." },
  { ref: "ts:1", prompt: "For type Shape = { kind: 'circle'; r: number } | { kind: 'square'; s: number }, what narrows it in a switch?", correct: "Checking shape.kind (a discriminated union)", wrong: ["typeof shape === 'object'", "shape instanceof Shape", "Casting with as Shape"], explanation: "A shared literal field lets TypeScript narrow each branch; add a never check for exhaustiveness." },
  { ref: "ts:2", prompt: "What does <T extends { id: string }> mean?", correct: "T can be any type that has at least an id: string property", wrong: ["T must be exactly { id: string }", "T must be a subclass of a class named id", "T is optional"], explanation: "Constraints set a lower bound on what T must have while keeping the caller's full type." },
  { ref: "ts:3", prompt: "Which utility type makes every property optional?", correct: "Partial<T>", wrong: ["Required<T>", "Pick<T, K>", "Readonly<T>"], explanation: "Partial is handy for PATCH payloads; Required does the opposite." },
  { ref: "ts:3", prompt: "Omit<User, 'password'> produces…", correct: "User without the password property", wrong: ["Only the password property", "User with password made optional", "A compile error unless password is optional"], explanation: "Omit removes keys; Pick keeps only the listed keys." },
  { ref: "ts:4", prompt: "Why use unknown instead of any for untrusted input?", correct: "unknown forces you to narrow or validate before using the value", wrong: ["unknown is faster at runtime", "any can't hold objects", "unknown validates JSON automatically"], explanation: "any switches off type checking; unknown keeps it on until you prove the type." },
  { ref: "ts:4", prompt: "What is the return type of a function that always throws?", correct: "never", wrong: ["void", "undefined", "unknown"], explanation: "never means the function never returns normally." },
  { ref: "ts:5", prompt: "What does `as const` do to ['a', 'b']?", correct: "Makes it a readonly tuple of literal types: readonly ['a', 'b']", wrong: ["Freezes the array at runtime", "Converts it into an enum", "Widens it to string[]"], explanation: "as const is compile-time only; it's a lightweight alternative to enums." },
  { ref: "ts:6", prompt: "What does strictNullChecks catch?", correct: "Using a value that might be null or undefined without checking it", wrong: ["Unused imports", "Missing semicolons", "Slow loops"], explanation: "It's part of strict mode and prevents the most common runtime TypeErrors." },
  { ref: "ts:7", prompt: "With useUnknownInCatchVariables, what is the type of e in catch (e)?", correct: "unknown", wrong: ["Error", "any", "never"], explanation: "Anything can be thrown, so narrow with e instanceof Error before reading e.message." },
  { ref: "ts:8", prompt: "Why validate with zod when you already have TypeScript types?", correct: "Types disappear at runtime; zod checks real data from requests, env vars and APIs", wrong: ["zod makes TypeScript compile faster", "TypeScript can't describe objects", "zod replaces unit tests"], explanation: "z.infer gives you the static type from the same schema, so they never drift." },

  // Node.js
  { ref: "node-internals:0", prompt: "What does libuv provide to Node?", correct: "The event loop, the thread pool and async I/O abstractions", wrong: ["The JavaScript JIT compiler", "The npm registry client", "TypeScript support"], explanation: "V8 runs JavaScript; libuv handles async I/O across operating systems." },
  { ref: "node-internals:1", prompt: "In which event-loop phase do setImmediate callbacks run?", correct: "Check", wrong: ["Timers", "Poll", "Close callbacks"], explanation: "The phases are timers → pending → poll → check → close; setImmediate runs in check." },
  { ref: "node-internals:2", prompt: "Which of these use the libuv thread pool?", correct: "fs.readFile and crypto.pbkdf2", wrong: ["setTimeout", "TCP socket reads on Linux", "Promise.then"], explanation: "File system calls, DNS lookup, zlib and some crypto use the pool; network sockets use OS async I/O." },
  { ref: "node-internals:2", prompt: "What is the default UV_THREADPOOL_SIZE?", correct: "4", wrong: ["1", "The number of CPU cores", "128"], explanation: "Raise it when many concurrent fs/crypto calls queue up." },
  { ref: "node-internals:3", prompt: "A request handler runs a 2-second synchronous loop. What happens?", correct: "Every other request waits: the event loop is blocked", wrong: ["Node moves it to another thread automatically", "Only that client waits", "The loop is paused and resumed later"], explanation: "Move CPU-heavy work to worker threads or a queue." },
  { ref: "node-internals:5", prompt: "What does stream.pipeline() add over .pipe()?", correct: "Error propagation and cleanup across all streams, plus a completion callback or promise", wrong: ["Faster throughput by default", "Automatic gzip", "Parallel processing on all cores"], explanation: ".pipe() doesn't forward errors or destroy streams on failure; pipeline does." },
  { ref: "node-internals:5", prompt: "What does back-pressure look like in Node streams?", correct: "write() returns false and the producer waits for 'drain'", wrong: ["The consumer reads faster than the producer", "The stream retries failed writes", "Data is buffered to disk automatically"], explanation: "Respecting back-pressure keeps memory flat when the consumer is slower than the producer." },
  { ref: "node-internals:6", prompt: "What does path.join('/a', '../b') return?", correct: "/b", wrong: ["/a/../b", "/a/b", "b"], explanation: "path.join normalises the result, resolving .. segments." },
  { ref: "node-internals:7", prompt: "Best fit for CPU-heavy work, like image resizing, inside one Node service?", correct: "worker_threads", wrong: ["cluster", "process.nextTick", "A bigger UV_THREADPOOL_SIZE only"], explanation: "Worker threads run JS in parallel without blocking the main event loop." },
  { ref: "node-internals:7", prompt: "What does the cluster module do?", correct: "Forks several processes that share one server port", wrong: ["Runs threads with shared memory", "Schedules cron jobs", "Balances database connections"], explanation: "cluster (or PM2 / containers) uses all CPU cores for a stateless server." },
  { ref: "node-internals:8", prompt: 'What does the "exports" field in package.json do?', correct: "Defines which entry points consumers may import, blocking deep imports", wrong: ["Lists dev dependencies", "Sets the required Node version", "Exports environment variables"], explanation: "It can also map different files for import vs require." },
  { ref: "node-backend:0", prompt: "With the bare http module, how do you send a JSON response?", correct: "res.writeHead(200, { 'Content-Type': 'application/json' }); res.end(JSON.stringify(data))", wrong: ["res.json(data)", "return data from the handler", "res.send(data)"], explanation: "res.json and res.send are Express helpers built on top of these calls." },
  { ref: "node-backend:1", prompt: "How does Express recognise error-handling middleware?", correct: "It takes four parameters: (err, req, res, next)", wrong: ["It is registered with app.error()", "It is named errorHandler", "It must be the first middleware"], explanation: "Register it last; call next(err) or throw in async handlers (Express 5) to reach it." },
  { ref: "node-backend:1", prompt: "A middleware neither sends a response nor calls next(). What happens?", correct: "The request hangs until it times out", wrong: ["Express calls next() automatically", "Express sends a 404", "The process crashes"], explanation: "Every middleware must end the response or pass control on." },
  { ref: "node-backend:2", prompt: "In NestJS, what are providers?", correct: "Injectable classes (services, repositories) resolved by the DI container", wrong: ["HTTP route handlers only", "Database drivers", "Frontend components"], explanation: "Controllers handle routes; providers hold business logic and are injected via constructors." },
  { ref: "node-backend:3", prompt: "Where should request validation happen?", correct: "At the boundary, before business logic, returning 400 on failure", wrong: ["Only in the database schema", "Only in the frontend", "After saving the record"], explanation: "Validate early with a schema (zod/joi) so the rest of the code can trust its input." },
  { ref: "node-backend:4", prompt: "What is the main drawback of long-lived stateless JWT access tokens?", correct: "They're hard to revoke before they expire", wrong: ["They need a database lookup on every request", "They can't carry claims", "They only work over HTTP/2"], explanation: "Use short-lived access tokens plus refresh tokens that can be revoked." },
  { ref: "node-backend:4", prompt: "Why hash passwords with bcrypt?", correct: "It's deliberately slow and salted, which resists brute force", wrong: ["It's reversible for password recovery", "It's the fastest hash available", "It encrypts with a server key"], explanation: "Never store plain or fast-hashed (MD5/SHA) passwords." },
  { ref: "node-backend:5", prompt: "Why use a database connection pool?", correct: "Reusing open connections avoids per-request connect cost and caps load on the DB", wrong: ["It caches query results", "It encrypts traffic", "It shards the database"], explanation: "On serverless, cache the client globally so warm invocations reuse the pool." },
  { ref: "node-backend:6", prompt: "What does supertest let you do?", correct: "Send HTTP requests to your app in tests without binding a real port", wrong: ["Mock the database", "Measure code coverage", "Run load tests"], explanation: "It's the standard for integration-testing Express/Nest routes." },
  { ref: "node-backend:7", prompt: "What does 12-factor config mean?", correct: "Config lives in environment variables, not in code", wrong: ["Config is committed in config.json", "Each environment has its own codebase", "Secrets are hard-coded but obfuscated"], explanation: "The same build runs everywhere; only the environment changes." },
  { ref: "node-backend:8", prompt: "Why add a request ID to every log line?", correct: "To correlate all logs from one request, even across services", wrong: ["To rate-limit clients", "To encrypt logs", "To make logging faster"], explanation: "Structured JSON logs (pino) with a request ID make tracing incidents practical." },
  { ref: "node-production:0", prompt: "What's a good first step when hunting event-loop blocking?", correct: "Measure event-loop lag and profile CPU (--cpu-prof, clinic)", wrong: ["Add more RAM", "Add more console.log calls", "Switch to HTTP/2"], explanation: "Flame graphs show which synchronous function hogs the thread." },
  { ref: "node-production:1", prompt: "How do you confirm a memory leak?", correct: "Compare heap snapshots over time and look for growing retained objects", wrong: ["Restart the server", "Watch CPU usage", "Count open files"], explanation: "Steady growth in the same object type between snapshots points at the leak." },
  { ref: "node-production:2", prompt: "What's a prerequisite for scaling Node horizontally behind a load balancer?", correct: "Stateless servers, with sessions in Redis or the DB rather than memory", wrong: ["CPU affinity for each request", "A single shared process", "Running on port 80"], explanation: "Any instance must be able to serve any request." },
  { ref: "node-production:3", prompt: "What should graceful shutdown on SIGTERM do?", correct: "Stop accepting requests, finish in-flight ones, close DB connections, then exit", wrong: ["Exit immediately", "Ignore the signal", "Restart the process in place"], explanation: "Orchestrators send SIGTERM before killing; handle it to avoid dropped requests." },
  { ref: "node-production:4", prompt: "What does a token-bucket rate limiter allow?", correct: "Short bursts up to the bucket size while enforcing an average rate", wrong: ["Exactly one request per second, no bursts", "Unlimited requests from known IPs", "Requests only when the bucket is empty"], explanation: "Tokens refill at a fixed rate; each request spends one." },
  { ref: "node-production:5", prompt: "Why send emails from a background queue (e.g. BullMQ)?", correct: "Responses stay fast and failed sends can be retried", wrong: ["Emails become free", "It removes the need for SMTP", "It guarantees exactly-once delivery"], explanation: "Queues give retries with backoff; jobs should still be idempotent (at-least-once)." },
  { ref: "node-production:6", prompt: "When does prototype pollution happen?", correct: "When untrusted keys like __proto__ get merged into objects, changing Object.prototype", wrong: ["When too many classes extend each other", "When prototypes are frozen", "Whenever JSON.parse is used"], explanation: "Validate keys, use Object.create(null) or Map, and avoid naive deep merges." },
  { ref: "node-production:7", prompt: "Why is single-threaded Node fast for I/O-heavy APIs?", correct: "Non-blocking I/O lets one thread juggle many concurrent connections", wrong: ["JavaScript runs on many threads", "Node caches every response", "V8 compiles to GPU code"], explanation: "Time is spent waiting on I/O, which the event loop overlaps." },
  { ref: "node-production:7", prompt: "When is Node a poor fit?", correct: "Long CPU-bound computation in the request path", wrong: ["Real-time chat", "JSON APIs", "Streaming file uploads"], explanation: "CPU-heavy work blocks the loop; use workers or another runtime for it." },

  // DSA concepts
  { ref: "dsa-complexity:0", prompt: "Two nested loops over n items with an O(1) body. What's the complexity?", correct: "O(n²)", wrong: ["O(n)", "O(n log n)", "O(2n)"], explanation: "n iterations of an inner loop that runs n times." },
  { ref: "dsa-complexity:1", prompt: "What does amortised O(1) push on a dynamic array mean?", correct: "Occasional O(n) resizes average out to O(1) per push", wrong: ["Every push is O(1) in the worst case", "Push is O(log n)", "Resizing never happens"], explanation: "Doubling capacity makes total resize cost O(n) over n pushes." },
  { ref: "dsa-complexity:2", prompt: "Which operation is O(n) on a JS array?", correct: "arr.shift()", wrong: ["arr.push(x)", "arr.pop()", "arr[i]"], explanation: "shift re-indexes every element; use a pointer or a deque for queues." },
  { ref: "dsa-complexity:4", prompt: "With prefix sums, a range sum query takes…", correct: "O(1) after O(n) preprocessing", wrong: ["O(log n) per query", "O(n) per query", "O(n²) preprocessing"], explanation: "sum(i..j) = prefix[j + 1] - prefix[i]." },
  { ref: "dsa-hashing-pointers:0", prompt: "Why use Map over a plain object as a hash table in JS?", correct: "Keys of any type, insertion order, and size in O(1)", wrong: ["Objects can't use strings as keys", "Map always uses less memory", "Map keeps keys sorted"], explanation: "Objects coerce keys to strings and inherit prototype keys." },
  { ref: "dsa-hashing-pointers:4", prompt: "What does every recursive function need?", correct: "A base case that stops the recursion", wrong: ["A global variable", "A loop", "An accumulator argument"], explanation: "Without a base case recursion never ends and overflows the call stack." },

  // Databases, design, systems, AI
  { ref: "dbms-relational:1", prompt: "What is a candidate key?", correct: "A minimal set of attributes that uniquely identifies a row", wrong: ["Any foreign key", "The first column of a table", "A key that may contain duplicates"], explanation: "One candidate key is chosen as the primary key; the rest are alternate keys." },
  { ref: "dbms-relational:2", prompt: "orders.user_id has ON DELETE CASCADE. Deleting a user…", correct: "Also deletes that user's orders", wrong: ["Is blocked while orders exist", "Sets orders.user_id to NULL", "Archives the orders"], explanation: "RESTRICT blocks, SET NULL nulls the column, CASCADE deletes dependants." },
  { ref: "dbms-intro:3", prompt: "A user has many orders; each order belongs to one user. What's the cardinality?", correct: "One-to-many", wrong: ["Many-to-many", "One-to-one", "Many-to-one from user to order"], explanation: "Put the foreign key (user_id) on the many side (orders)." },
  { ref: "oop-pillars:4", prompt: "Why 'favour composition over inheritance'?", correct: "Behaviour can be combined and swapped without rigid class hierarchies", wrong: ["Inheritance is slower in V8", "Composition always needs less code", "JavaScript doesn't support inheritance"], explanation: "Deep hierarchies couple subclasses to parent internals." },
  { ref: "solid:2", prompt: "What does the Liskov Substitution Principle say?", correct: "Subtypes must work anywhere their base type is expected without breaking behaviour", wrong: ["A class should have one reason to change", "Depend on abstractions", "Interfaces should be small"], explanation: "The classic violation is a Square subclass breaking Rectangle's setWidth." },
  { ref: "solid:4", prompt: "What does dependency inversion look like in a Node service?", correct: "High-level code depends on interfaces; concrete DB/HTTP clients are injected", wrong: ["Every module imports the DB directly", "Dependencies are installed globally", "Child classes call parent constructors"], explanation: "Injecting ports makes services easy to test with fakes." },
  { ref: "lld-cache-ratelimiter:0", prompt: "How does a JS Map help build an O(1) LRU cache?", correct: "It keeps insertion order: delete + set moves a key to the end, and keys().next() is the oldest", wrong: ["Map sorts keys by access time automatically", "Map has a built-in evict() method", "Map limits its own size"], explanation: "On get: delete and re-set; on overflow: delete the first key." },
  { ref: "net-basics:1", prompt: "When would you choose UDP over TCP?", correct: "When low latency matters and occasional loss is fine (video, games, DNS)", wrong: ["When you need guaranteed delivery", "When you need ordering", "When you need congestion control"], explanation: "TCP adds reliability and ordering at the cost of handshakes and head-of-line blocking." },
  { ref: "api-design:1", prompt: "Why prefer cursor pagination for large, changing feeds?", correct: "Stable pages and fast seeks via an indexed cursor instead of OFFSET scans", wrong: ["It lets you jump straight to page 500", "It needs no index", "It returns total counts cheaply"], explanation: "OFFSET scans and skips rows, and items shift when new rows arrive." },
  { ref: "api-design:2", prompt: "What does an idempotency key on POST /payments prevent?", correct: "Charging twice when the client retries the same request", wrong: ["SQL injection", "Slow responses", "Unauthorised access"], explanation: "The server stores the key with the result and replays it on retries." },
  { ref: "api-design:5", prompt: "How is the GraphQL N+1 problem usually fixed?", correct: "Batching per request with a DataLoader", wrong: ["Adding more resolvers", "Switching to REST", "Growing the DB pool to N+1"], explanation: "DataLoader collects keys in one tick and issues a single batched query." },
  { ref: "hld-scale-zero-to-million:2", prompt: "What's the main limit of vertical scaling?", correct: "A hard ceiling on one machine, and it stays a single point of failure", wrong: ["It requires sharding", "It needs a load balancer", "You can't add RAM"], explanation: "Horizontal scaling adds machines and redundancy." },
  { ref: "hld-scale-zero-to-million:4", prompt: "What do read replicas mainly help with?", correct: "Scaling reads; writes still go to the primary", wrong: ["Scaling writes linearly", "Removing replication lag", "Replacing backups"], explanation: "Replicas can lag, so read-your-writes may need the primary." },
  { ref: "hld-scale-zero-to-million:5", prompt: "What does cache-aside mean?", correct: "The app checks the cache first and, on a miss, loads from the DB and fills the cache", wrong: ["The DB writes to the cache automatically", "The cache is the source of truth", "Every write bypasses the DB"], explanation: "Pair it with TTLs or invalidation on writes." },
  { ref: "hld-scale-zero-to-million:11", prompt: "What's a key risk of sharding by user_id % N?", correct: "Changing N moves most keys to new shards (consistent hashing reduces this)", wrong: ["Reads become impossible", "It needs a single primary", "Joins get faster"], explanation: "Consistent hashing moves only about 1/N of keys when a shard is added." },
  { ref: "hld-framework:1", prompt: "10M daily users each make 10 requests a day. Roughly what's the average QPS?", correct: "About 1,200", wrong: ["About 12", "About 120,000", "About 10,000,000"], explanation: "100M requests ÷ 86,400 s ≈ 1,157 QPS; plan peak at 2–3× that." },
  { ref: "ai-ml-basics:4", prompt: "Training accuracy is 99% but validation accuracy is 70%. What does that suggest?", correct: "Overfitting", wrong: ["Underfitting", "Perfect generalisation", "The validation set is too easy"], explanation: "The model memorised training data; regularise, simplify or get more data." },
  { ref: "ai-ml-basics:5", prompt: "For fraud detection, where missing fraud is costly, which metric should you prioritise?", correct: "Recall", wrong: ["Accuracy", "Precision only", "Training loss"], explanation: "Recall measures how many real positives you catch; accuracy hides rare classes." },
  { ref: "ai-deep-learning:1", prompt: "How do embeddings represent text?", correct: "As dense vectors where similar meanings sit close together", wrong: ["As compressed ZIP files", "As one-hot vectors only", "As SQL rows"], explanation: "Vector similarity powers semantic search and RAG." },
  { ref: "ai-deep-learning:3", prompt: "What does self-attention let each token do?", correct: "Weigh every other token in the context when building its representation", wrong: ["See only the previous token", "Skip tokenisation", "Run on its own GPU"], explanation: "Attention is why transformers capture long-range context in parallel." },
  { ref: "ai-deep-learning:5", prompt: "At its core, what is an LLM trained to do?", correct: "Predict the next token given the previous tokens", wrong: ["Look answers up in a database", "Execute code", "Memorise the internet word for word"], explanation: "Instruction tuning and RLHF shape that next-token predictor into an assistant." },
  { ref: "behavioral-stories:0", prompt: "What does STAR stand for?", correct: "Situation, Task, Action, Result", wrong: ["Story, Team, Approach, Review", "Start, Think, Act, Reflect", "Situation, Target, Analysis, Risk"], explanation: "Spend most of the time on Action and quantify the Result." },

  // DSA patterns that have no recognition questions
  { ref: "pattern:SQL (Backend must-know)", prompt: "Which clause filters groups after aggregation?", correct: "HAVING", wrong: ["WHERE", "GROUP BY", "ORDER BY"], explanation: "WHERE filters rows before grouping; HAVING filters the aggregated groups." },
  { ref: "pattern:SQL (Backend must-know)", prompt: "Which join keeps every row from the left table, even without a match?", correct: "LEFT JOIN", wrong: ["INNER JOIN", "CROSS JOIN", "SELF JOIN"], explanation: "Unmatched right-side columns come back as NULL." },
  { ref: "pattern:SQL (Backend must-know)", prompt: "How do you get the second-highest salary per department in modern SQL?", correct: "DENSE_RANK() OVER (PARTITION BY dept ORDER BY salary DESC) and keep rank 2", wrong: ["MAX(salary) - 1", "GROUP BY salary LIMIT 2", "SELECT TOP 2 without ORDER BY"], explanation: "Window functions rank within partitions without collapsing rows." },
  { ref: "pattern:SQL (Backend must-know)", prompt: "Which index helps WHERE user_id = ? ORDER BY created_at DESC most?", correct: "A composite index on (user_id, created_at)", wrong: ["Separate indexes on every column", "An index on created_at only", "No index; ORDER BY is free"], explanation: "Equality columns first, then the sort column, so the index serves both." },
  { ref: "pattern:JavaScript (30 Days of JS)", prompt: "What makes a function a closure in JavaScript?", correct: "It keeps access to variables from the scope where it was created", wrong: ["It is declared with the closure keyword", "It runs immediately", "It takes no arguments"], explanation: "Closures power counters, memoize, once, debounce and module patterns." },
  { ref: "pattern:JavaScript (30 Days of JS)", prompt: "A function must resolve within t ms or reject with 'Time Limit Exceeded'. What's the idiomatic tool?", correct: "Promise.race between the work and a timer promise that rejects", wrong: ["Promise.all with a timer", "A while loop checking Date.now()", "setInterval polling the result"], explanation: "Clear the timer when the work finishes to avoid leaks." },
];
