import { define, type ProblemDef } from "../../dsa-extras/define";
import { arrayGen, gen } from "../../dsa-extras/gen";
import type { ProblemSpec } from "../types";

/** Judges for seeded LeetCode problems that the Array Ladder points at. LeetCode's own signatures. */
const DEFS: ProblemDef[] = [
  {
    slug: "remove-element",
    title: "Remove Element",
    difficulty: "Easy",
    pattern: "Two Pointers",
    fn: "removeElement",
    params: [["nums", "number[]"], ["val", "number"]],
    returns: "number",
    returnKind: "arg0Prefix",
    compare: "unordered",
    hints: [
      "You don't need to delete anything: you only need the kept values to sit at the front. Where does the next kept value go?",
      "Keep a write index k starting at 0. Scan every element; when it isn't val, copy it to nums[k] and advance k. At the end the first k slots hold the answer (any order is accepted).",
      "k = 0\nfor i from 0 to n - 1:\n  if nums[i] != val:\n    nums[k] = nums[i]\n    k += 1\nreturn k",
    ],
    reference: `function removeElement(nums, val) { let k = 0; for (let i = 0; i < nums.length; i++) if (nums[i] !== val) nums[k++] = nums[i]; return k; }`,
    brute: `function removeElement(nums, val) { const kept = nums.filter((v) => v !== val); kept.forEach((v, i) => { nums[i] = v; }); return kept.length; }`,
    fuzz: gen(`return [__arr(rand, __r(rand, 0, 12), 0, 4), __r(rand, 0, 4)];`),
    examples: [[[3, 2, 2, 3], 3], [[0, 1, 2, 2, 3, 0, 4, 2], 2]],
    edges: [
      ["empty", [[], 1]],
      ["all-equal", [[5, 5, 5], 5], "Everything is removed: return 0."],
      ["no-answer", [[1, 2, 3], 9], "Nothing matches: keep all n elements."],
    ],
  },
  {
    slug: "remove-duplicates-from-sorted-array",
    title: "Remove Duplicates from Sorted Array",
    difficulty: "Easy",
    pattern: "Two Pointers",
    fn: "removeDuplicates",
    params: [["nums", "number[]"]],
    returns: "number",
    returnKind: "arg0Prefix",
    hints: [
      "The array is sorted, so equal values sit next to each other. How do you know a value is new?",
      "Use a slow write pointer for the end of the unique prefix and a fast pointer to scan. When nums[fast] differs from the last kept value, write it at the slow pointer and advance.",
      "if n == 0: return 0\nk = 1\nfor i from 1 to n - 1:\n  if nums[i] != nums[k - 1]:\n    nums[k] = nums[i]\n    k += 1\nreturn k",
    ],
    reference: `function removeDuplicates(nums) { if (!nums.length) return 0; let k = 1; for (let i = 1; i < nums.length; i++) if (nums[i] !== nums[k - 1]) nums[k++] = nums[i]; return k; }`,
    brute: `function removeDuplicates(nums) { const u = [...new Set(nums)]; u.forEach((v, i) => { nums[i] = v; }); return u.length; }`,
    fuzz: gen(`return [__sorted(rand, __r(rand, 1, 12), -3, 3)];`),
    examples: [[[1, 1, 2]], [[0, 0, 1, 1, 1, 2, 2, 3, 3, 4]]],
    edges: [
      ["single", [[7]]],
      ["all-equal", [[2, 2, 2, 2]]],
      ["negatives", [[-3, -3, -1, 0, 0]]],
    ],
  },
  {
    slug: "maximum-average-subarray-i",
    title: "Maximum Average Subarray I",
    difficulty: "Easy",
    pattern: "Sliding Window",
    fn: "findMaxAverage",
    params: [["nums", "number[]"], ["k", "number"]],
    returns: "number",
    hints: [
      "The best average over windows of the same length k comes from the best sum. Can you avoid dividing until the very end?",
      "Slide a window sum of size k: add the entering element, subtract the leaving one, keep the maximum sum, then return it divided by k.",
      "window = sum of nums[0..k-1]\nbest = window\nfor i from k to n - 1:\n  window += nums[i] - nums[i - k]\n  best = max(best, window)\nreturn best / k",
    ],
    reference: `function findMaxAverage(nums, k) { let w = 0; for (let i = 0; i < k; i++) w += nums[i]; let best = w; for (let i = k; i < nums.length; i++) { w += nums[i] - nums[i - k]; best = Math.max(best, w); } return best / k; }`,
    brute: `function findMaxAverage(nums, k) { let best = -Infinity; for (let i = 0; i + k <= nums.length; i++) best = Math.max(best, nums.slice(i, i + k).reduce((a, b) => a + b, 0)); return best / k; }`,
    fuzz: gen(`const n = __r(rand, 1, 12); return [__arr(rand, n, -20, 20), __r(rand, 1, n)];`),
    examples: [[[1, 12, -5, -6, 50, 3], 4], [[5], 1]],
    edges: [
      ["negatives", [[-1, -12, -5], 2], "All negative: initialising the best to 0 is wrong."],
      ["boundary", [[4, 2, 1, 3], 4], "k = n: the whole array is the only window."],
      ["all-equal", [[3, 3, 3, 3], 2]],
    ],
  },
  {
    slug: "minimum-size-subarray-sum",
    title: "Minimum Size Subarray Sum",
    difficulty: "Medium",
    pattern: "Sliding Window",
    fn: "minSubArrayLen",
    params: [["target", "number"], ["nums", "number[]"]],
    returns: "number",
    hints: [
      "All numbers are positive, so a window's sum only grows when you extend it and only shrinks when you drop from the left.",
      "Expand the right end and add its value. While the sum is at least target, record the window length and shrink from the left. Return 0 if no window ever reached target.",
      "left = 0, sum = 0, best = infinity\nfor right from 0 to n - 1:\n  sum += nums[right]\n  while sum >= target:\n    best = min(best, right - left + 1)\n    sum -= nums[left]\n    left += 1\nreturn 0 if best is infinity else best",
    ],
    reference: `function minSubArrayLen(target, nums) { let l = 0, s = 0, best = Infinity; for (let r = 0; r < nums.length; r++) { s += nums[r]; while (s >= target) { best = Math.min(best, r - l + 1); s -= nums[l++]; } } return best === Infinity ? 0 : best; }`,
    brute: `function minSubArrayLen(target, nums) { let best = 0; for (let i = 0; i < nums.length; i++) { let s = 0; for (let j = i; j < nums.length; j++) { s += nums[j]; if (s >= target) { if (!best || j - i + 1 < best) best = j - i + 1; break; } } } return best; }`,
    fuzz: gen(`return [__r(rand, 1, 30), __arr(rand, __r(rand, 1, 12), 1, 9)];`),
    examples: [[7, [2, 3, 1, 2, 4, 3]], [4, [1, 4, 4]]],
    edges: [
      ["no-answer", [11, [1, 1, 1, 1, 1, 1, 1, 1]], "The whole array sums to less than target: return 0."],
      ["single", [3, [3]]],
      ["boundary", [15, [1, 2, 3, 4, 5]], "Only the whole array reaches the target."],
    ],
  },
  {
    slug: "max-consecutive-ones-iii",
    title: "Max Consecutive Ones III",
    difficulty: "Medium",
    pattern: "Sliding Window",
    fn: "longestOnes",
    params: [["nums", "number[]"], ["k", "number"]],
    returns: "number",
    hints: [
      "Flipping at most k zeros is the same as finding the longest window that contains at most k zeros.",
      "Grow the window to the right, counting zeros. When the count exceeds k, move the left end forward until a zero leaves. Track the largest valid window.",
      "left = 0, zeros = 0, best = 0\nfor right from 0 to n - 1:\n  if nums[right] == 0: zeros += 1\n  while zeros > k:\n    if nums[left] == 0: zeros -= 1\n    left += 1\n  best = max(best, right - left + 1)\nreturn best",
    ],
    reference: `function longestOnes(nums, k) { let l = 0, z = 0, best = 0; for (let r = 0; r < nums.length; r++) { if (nums[r] === 0) z++; while (z > k) { if (nums[l] === 0) z--; l++; } best = Math.max(best, r - l + 1); } return best; }`,
    brute: `function longestOnes(nums, k) { let best = 0; for (let i = 0; i < nums.length; i++) { let z = 0; for (let j = i; j < nums.length; j++) { if (nums[j] === 0) z++; if (z > k) break; best = Math.max(best, j - i + 1); } } return best; }`,
    fuzz: gen(`const n = __r(rand, 1, 16); return [__arr(rand, n, 0, 1), __r(rand, 0, 4)];`),
    examples: [[[1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0], 2], [[0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1], 3]],
    edges: [
      ["zeros", [[0, 0, 0], 0], "No flips and no ones: the answer is 0."],
      ["boundary", [[0, 0, 1], 5], "k is larger than the number of zeros: the whole array works."],
      ["all-equal", [[1, 1, 1, 1], 0]],
    ],
  },
  {
    slug: "find-pivot-index",
    title: "Find Pivot Index",
    difficulty: "Easy",
    pattern: "Prefix Sum",
    fn: "pivotIndex",
    params: [["nums", "number[]"]],
    returns: "number",
    hints: [
      "If you know the total and the sum to the left of i, what is the sum to the right of i?",
      "Compute the total once. Walk left to right with a running left sum; index i is a pivot when left == total - left - nums[i]. Return the first such index, or -1.",
      "total = sum of nums\nleft = 0\nfor i from 0 to n - 1:\n  if left == total - left - nums[i]: return i\n  left += nums[i]\nreturn -1",
    ],
    reference: `function pivotIndex(nums) { const total = nums.reduce((a, b) => a + b, 0); let left = 0; for (let i = 0; i < nums.length; i++) { if (left === total - left - nums[i]) return i; left += nums[i]; } return -1; }`,
    brute: `function pivotIndex(nums) { for (let i = 0; i < nums.length; i++) { const l = nums.slice(0, i).reduce((a, b) => a + b, 0); const r = nums.slice(i + 1).reduce((a, b) => a + b, 0); if (l === r) return i; } return -1; }`,
    fuzz: arrayGen(1, 10, -3, 3),
    examples: [[[1, 7, 3, 6, 5, 6]], [[1, 2, 3]]],
    edges: [
      ["boundary", [[2, 1, -1]], "Index 0 is the pivot: the left sum of an empty prefix is 0."],
      ["single", [[5]], "One element: both sides are empty, so index 0 is a pivot."],
      ["zeros", [[0, 0, 0]], "Every index works; return the first."],
    ],
  },
  {
    slug: "trapping-rain-water",
    title: "Trapping Rain Water",
    difficulty: "Hard",
    pattern: "Two Pointers",
    fn: "trap",
    params: [["height", "number[]"]],
    returns: "number",
    hints: [
      "Water above a bar is limited by the tallest bar to its left and the tallest bar to its right. Which of the two matters?",
      "Use two pointers with running left and right maxima. Always move the side with the smaller maximum: that side's water level is already decided by its own maximum.",
      "l = 0, r = n - 1, leftMax = 0, rightMax = 0, water = 0\nwhile l < r:\n  if height[l] < height[r]:\n    leftMax = max(leftMax, height[l]); water += leftMax - height[l]; l += 1\n  else:\n    rightMax = max(rightMax, height[r]); water += rightMax - height[r]; r -= 1\nreturn water",
    ],
    reference: `function trap(height) { let l = 0, r = height.length - 1, lm = 0, rm = 0, w = 0; while (l < r) { if (height[l] < height[r]) { lm = Math.max(lm, height[l]); w += lm - height[l]; l++; } else { rm = Math.max(rm, height[r]); w += rm - height[r]; r--; } } return w; }`,
    brute: `function trap(height) { let w = 0; for (let i = 0; i < height.length; i++) { const lm = Math.max(...height.slice(0, i + 1)); const rm = Math.max(...height.slice(i)); w += Math.min(lm, rm) - height[i]; } return w; }`,
    fuzz: arrayGen(0, 14, 0, 6),
    examples: [[[0, 1, 0, 2, 1, 0, 1, 3, 2, 1, 2, 1]], [[4, 2, 0, 3, 2, 5]]],
    edges: [
      ["empty", [[]]],
      ["sorted", [[1, 2, 3, 4]], "Rising bars hold no water."],
      ["two", [[5, 5]]],
    ],
  },
  {
    slug: "first-missing-positive",
    title: "First Missing Positive",
    difficulty: "Hard",
    pattern: "Arrays & Hashing",
    fn: "firstMissingPositive",
    params: [["nums", "number[]"]],
    returns: "number",
    hints: [
      "The answer is always between 1 and n + 1. How could the array itself record which of those values are present?",
      "Place every value v in 1..n at index v - 1 by swapping until each slot holds its own value or a value that can't be placed. Then the first index i with nums[i] != i + 1 gives the answer i + 1.",
      "for i from 0 to n - 1:\n  while 1 <= nums[i] <= n and nums[nums[i] - 1] != nums[i]:\n    swap nums[i] with nums[nums[i] - 1]\nfor i from 0 to n - 1:\n  if nums[i] != i + 1: return i + 1\nreturn n + 1",
    ],
    reference: `function firstMissingPositive(nums) { const a = nums.slice(); const n = a.length; for (let i = 0; i < n; i++) { while (a[i] >= 1 && a[i] <= n && a[a[i] - 1] !== a[i]) { const j = a[i] - 1; const t = a[j]; a[j] = a[i]; a[i] = t; } } for (let i = 0; i < n; i++) if (a[i] !== i + 1) return i + 1; return n + 1; }`,
    brute: `function firstMissingPositive(nums) { const s = new Set(nums); let x = 1; while (s.has(x)) x++; return x; }`,
    fuzz: arrayGen(0, 12, -3, 12),
    examples: [[[1, 2, 0]], [[3, 4, -1, 1]]],
    edges: [
      ["empty", [[]], "No values: 1 is missing."],
      ["sorted", [[1, 2, 3, 4]], "1..n all present: the answer is n + 1."],
      ["duplicates", [[1, 1, 1]], "Duplicates must not loop forever while swapping."],
      ["negatives", [[-5, -1, 0]]],
    ],
  },
];

export const LADDER_SEEDED: ProblemSpec[] = DEFS.map((d) => define(d).spec);
