import { define, type ProblemDef } from "../../dsa-extras/define";
import { gen } from "../../dsa-extras/gen";
import type { ProblemSpec } from "../types";

const IVS = (n: string, lo: number, hi: number, maxLen: number, minLen = 1) =>
  `Array.from({ length: ${n} }, () => { const s = __r(rand, ${lo}, ${hi}); return [s, s + __r(rand, ${minLen}, ${maxLen})]; })`;
const DISJOINT = `function __ivs(rand, n) { var out = [], at = __r(rand, 0, 3); for (var i = 0; i < n; i++) { var len = __r(rand, 0, 4); out.push([at, at + len]); at += len + __r(rand, 1, 3); } return out; }`;

/** Judges for seeded LeetCode problems that the Greedy Ladder points at. LeetCode's own signatures. */
const DEFS: ProblemDef[] = [
  {
    slug: "assign-cookies",
    title: "Assign Cookies",
    difficulty: "Easy",
    pattern: "Greedy",
    fn: "findContentChildren",
    params: [["g", "number[]"], ["s", "number[]"]],
    returns: "number",
    hints: [
      "Give the least greedy child the smallest cookie that satisfies them; a bigger cookie would be wasted.",
      "Sort both. Walk the cookies with a pointer on the children: when a cookie satisfies the current child, move to the next child.",
      "sort g, sort s\nchild = 0\nfor cookie in s:\n  if child < len(g) and cookie >= g[child]: child = child + 1\nreturn child",
    ],
    reference: `function findContentChildren(g, s) { const a = g.slice().sort((x, y) => x - y), b = s.slice().sort((x, y) => x - y); let i = 0; for (const c of b) if (i < a.length && c >= a[i]) i++; return i; }`,
    brute: `function findContentChildren(g, s) { const a = g.slice().sort((x, y) => x - y), b = s.slice().sort((x, y) => y - x); const ok = (k) => { if (k > b.length) return false; const top = b.slice(0, k).reverse(); for (let i = 0; i < k; i++) if (top[i] < a[i]) return false; return true; }; let k = 0; while (k < a.length && ok(k + 1)) k++; return k; }`,
    fuzz: gen(`return [__arr(rand, __r(rand, 1, 8), 1, 10), __arr(rand, __r(rand, 0, 8), 1, 10)];`),
    examples: [[[1, 2, 3], [1, 1]], [[1, 2], [1, 2, 3]]],
    edges: [
      ["empty", [[1, 2], []]],
      ["all-equal", [[2, 2, 2], [2, 2]]],
      ["no-answer", [[5, 6], [1, 2, 3]], "Every cookie is too small."],
    ],
  },
  {
    slug: "lemonade-change",
    title: "Lemonade Change",
    difficulty: "Easy",
    pattern: "Greedy",
    fn: "lemonadeChange",
    params: [["bills", "number[]"]],
    returns: "boolean",
    hints: [
      "You only ever hold $5 and $10 bills. Track how many of each you have.",
      "For $10 give back a $5. For $20 prefer $10 + $5 (keeps more $5s, which are more useful), else three $5s.",
      "five = 0, ten = 0\nfor b in bills:\n  if b == 5: five += 1\n  else if b == 10: if five == 0: return false; five -= 1, ten += 1\n  else if ten > 0 and five > 0: ten -= 1, five -= 1\n  else if five >= 3: five -= 3\n  else: return false\nreturn true",
    ],
    reference: `function lemonadeChange(bills) { let five = 0, ten = 0; for (const b of bills) { if (b === 5) five++; else if (b === 10) { if (!five) return false; five--; ten++; } else if (ten && five) { ten--; five--; } else if (five >= 3) five -= 3; else return false; } return true; }`,
    brute: `function lemonadeChange(bills) { const go = (i, five, ten) => { if (i === bills.length) return true; const b = bills[i]; if (b === 5) return go(i + 1, five + 1, ten); if (b === 10) return five > 0 && go(i + 1, five - 1, ten + 1); return (ten > 0 && five > 0 && go(i + 1, five - 1, ten - 1)) || (five >= 3 && go(i + 1, five - 3, ten)); }; return go(0, 0, 0); }`,
    fuzz: gen(`return [Array.from({ length: __r(rand, 1, 12) }, () => __pick(rand, [5, 5, 5, 10, 10, 20]))];`),
    examples: [[[5, 5, 5, 10, 20]], [[5, 5, 10, 10, 20]]],
    edges: [
      ["single", [[5]]],
      ["boundary", [[10]], "No change at all for the first customer."],
      ["extremes", [[5, 5, 5, 5, 20, 20]], "The second $20 finds only one $5 left."],
    ],
  },
  {
    slug: "maximum-units-on-a-truck",
    title: "Maximum Units on a Truck",
    difficulty: "Easy",
    pattern: "Greedy",
    fn: "maximumUnits",
    params: [["boxTypes", "number[][]"], ["truckSize", "number"]],
    returns: "number",
    hints: [
      "Every box takes one slot, so a slot is best spent on the box with the most units.",
      "Sort box types by units per box, descending, and take as many as fit from the top.",
      "sort boxTypes by units descending\ntotal = 0\nfor (count, units) in boxTypes:\n  take = min(count, truckSize)\n  total = total + take * units\n  truckSize = truckSize - take\nreturn total",
    ],
    reference: `function maximumUnits(boxTypes, truckSize) { let t = 0; for (const [c, u] of boxTypes.slice().sort((a, b) => b[1] - a[1])) { const k = Math.min(c, truckSize); t += k * u; truckSize -= k; } return t; }`,
    brute: `function maximumUnits(boxTypes, truckSize) { const all = []; for (const [c, u] of boxTypes) for (let i = 0; i < c; i++) all.push(u); all.sort((a, b) => b - a); return all.slice(0, truckSize).reduce((a, b) => a + b, 0); }`,
    fuzz: gen(`return [Array.from({ length: __r(rand, 1, 6) }, () => [__r(rand, 1, 5), __r(rand, 1, 10)]), __r(rand, 1, 20)];`),
    examples: [[[[1, 3], [2, 2], [3, 1]], 4], [[[5, 10], [2, 5], [4, 7], [3, 9]], 10]],
    edges: [
      ["single", [[[1, 1]], 1]],
      ["boundary", [[[2, 5], [3, 4]], 100], "The truck fits every box."],
      ["all-equal", [[[2, 3], [2, 3]], 3]],
    ],
  },
  {
    slug: "two-city-scheduling",
    title: "Two City Scheduling",
    difficulty: "Medium",
    pattern: "Greedy",
    fn: "twoCitySchedCost",
    params: [["costs", "number[][]"]],
    returns: "number",
    hints: [
      "Imagine sending everyone to B, then moving n people to A. Moving person i changes the total by a_i - b_i.",
      "Sort by a_i - b_i and send the first half to A, the rest to B.",
      "sort costs by (a - b)\ntotal = 0\nfor i in 0 .. 2n - 1:\n  if i < n: total = total + costs[i].a\n  else: total = total + costs[i].b\nreturn total",
    ],
    reference: `function twoCitySchedCost(costs) { const s = costs.slice().sort((x, y) => x[0] - x[1] - (y[0] - y[1])), n = s.length / 2; let t = 0; s.forEach((c, i) => { t += i < n ? c[0] : c[1]; }); return t; }`,
    brute: `function twoCitySchedCost(costs) { const n = costs.length / 2, memo = new Map(); const go = (i, a) => { if (i === costs.length) return a === n ? 0 : Infinity; const key = i * 100 + a; if (memo.has(key)) return memo.get(key); const r = Math.min(a < n ? costs[i][0] + go(i + 1, a + 1) : Infinity, i - a < n ? costs[i][1] + go(i + 1, a) : Infinity); memo.set(key, r); return r; }; return go(0, 0); }`,
    fuzz: gen(`return [Array.from({ length: 2 * __r(rand, 1, 5) }, () => [__r(rand, 1, 100), __r(rand, 1, 100)])];`),
    examples: [[[[10, 20], [30, 200], [400, 50], [30, 20]]], [[[259, 770], [448, 54], [926, 667], [184, 139], [840, 118], [577, 469]]]],
    edges: [
      ["two", [[[1, 2], [3, 4]]]],
      ["all-equal", [[[5, 5], [5, 5]]]],
      ["extremes", [[[1, 1000], [1, 1000]]], "Both prefer A, but one must go to B."],
    ],
  },
  {
    slug: "bag-of-tokens",
    title: "Bag of Tokens",
    difficulty: "Medium",
    pattern: "Greedy",
    fn: "bagOfTokensScore",
    params: [["tokens", "number[]"], ["power", "number"]],
    returns: "number",
    hints: [
      "Buy score with the cheapest tokens, and when you run out of power, sell a point for the most expensive token.",
      "Sort, two pointers. Play the smallest face up while you can; otherwise, if you have a point and tokens remain, play the largest face down. Track the best score seen.",
      "sort tokens, lo = 0, hi = n - 1, score = 0, best = 0\nwhile lo <= hi:\n  if power >= tokens[lo]: power -= tokens[lo], lo += 1, score += 1, best = max(best, score)\n  else if score > 0 and lo < hi: power += tokens[hi], hi -= 1, score -= 1\n  else: stop\nreturn best",
    ],
    reference: `function bagOfTokensScore(tokens, power) { const t = tokens.slice().sort((a, b) => a - b); let lo = 0, hi = t.length - 1, score = 0, best = 0; while (lo <= hi) { if (power >= t[lo]) { power -= t[lo++]; score++; best = Math.max(best, score); } else if (score > 0 && lo < hi) { power += t[hi--]; score--; } else break; } return best; }`,
    brute: `function bagOfTokensScore(tokens, power) { const memo = new Map(); const go = (mask, p, s) => { const key = mask + ":" + p + ":" + s; if (memo.has(key)) return memo.get(key); let best = s; for (let i = 0; i < tokens.length; i++) { if (mask & (1 << i)) continue; if (p >= tokens[i]) best = Math.max(best, go(mask | (1 << i), p - tokens[i], s + 1)); if (s > 0) best = Math.max(best, go(mask | (1 << i), p + tokens[i], s - 1)); } memo.set(key, best); return best; }; return go(0, power, 0); }`,
    fuzz: gen(`return [__arr(rand, __r(rand, 1, 7), 1, 20), __r(rand, 0, 30)];`),
    examples: [[[100], 50], [[200, 100], 150], [[100, 200, 300, 400], 200]],
    edges: [
      ["empty", [[], 5]],
      ["all-equal", [[10, 10, 10], 10]],
      ["zeros", [[5, 1], 0], "No power and no score: nothing can be played."],
    ],
  },
  {
    slug: "eliminate-maximum-number-of-monsters",
    title: "Eliminate Maximum Number of Monsters",
    difficulty: "Medium",
    pattern: "Greedy",
    fn: "eliminateMaximum",
    params: [["dist", "number[]"], ["speed", "number[]"]],
    returns: "number",
    hints: [
      "What matters is when each monster arrives: ceil(dist / speed) minutes. Shoot the one arriving soonest first.",
      "Sort arrival times. You fire your i-th shot at minute i, so you lose at the first i where arrival[i] <= i.",
      "arrive = sorted [ceil(dist[i] / speed[i])]\nfor i in 0 .. n - 1:\n  if arrive[i] <= i: return i\nreturn n",
    ],
    reference: `function eliminateMaximum(dist, speed) { const t = dist.map((d, i) => Math.ceil(d / speed[i])).sort((a, b) => a - b); for (let i = 0; i < t.length; i++) if (t[i] <= i) return i; return t.length; }`,
    brute: `function eliminateMaximum(dist, speed) { const alive = dist.map((d, i) => i); let killed = 0; for (let t = 0; alive.length; t++) { if (alive.some((i) => dist[i] - t * speed[i] <= 0)) return killed; let best = 0; for (let j = 1; j < alive.length; j++) { const a = alive[j], b = alive[best]; if ((dist[a] - t * speed[a]) / speed[a] < (dist[b] - t * speed[b]) / speed[b]) best = j; } alive.splice(best, 1); killed++; } return killed; }`,
    fuzz: gen(`const n = __r(rand, 1, 10); return [__arr(rand, n, 1, 20), __arr(rand, n, 1, 5)];`),
    examples: [[[1, 3, 4], [1, 1, 1]], [[1, 1, 2, 3], [1, 1, 1, 1]], [[3, 2, 4], [5, 3, 2]]],
    edges: [
      ["single", [[5], [1]]],
      ["all-equal", [[2, 2, 2], [1, 1, 1]], "Two arrive at minute 2: you only get shots at 0 and 1."],
      ["boundary", [[4, 2, 3], [2, 1, 1]]],
    ],
  },
  {
    slug: "best-time-to-buy-and-sell-stock-ii",
    title: "Best Time to Buy and Sell Stock II",
    difficulty: "Medium",
    pattern: "Greedy",
    fn: "maxProfit",
    params: [["prices", "number[]"]],
    returns: "number",
    hints: [
      "Any profitable stretch can be split into daily rises. You can collect every one of them.",
      "Add max(0, prices[i] - prices[i - 1]) for every day.",
      "profit = 0\nfor i in 1 .. n - 1:\n  if prices[i] > prices[i - 1]: profit = profit + prices[i] - prices[i - 1]\nreturn profit",
    ],
    reference: `function maxProfit(prices) { let p = 0; for (let i = 1; i < prices.length; i++) p += Math.max(0, prices[i] - prices[i - 1]); return p; }`,
    brute: `function maxProfit(prices) { let cash = 0, hold = -Infinity; for (const x of prices) { const c = Math.max(cash, hold + x); hold = Math.max(hold, cash - x); cash = c; } return cash; }`,
    fuzz: gen(`return [__arr(rand, __r(rand, 1, 15), 0, 20)];`),
    examples: [[[7, 1, 5, 3, 6, 4]], [[1, 2, 3, 4, 5]], [[7, 6, 4, 3, 1]]],
    edges: [
      ["single", [[5]]],
      ["all-equal", [[3, 3, 3]]],
      ["extremes", [[0, 10000, 0, 10000]]],
    ],
  },
  {
    slug: "jump-game-ii",
    title: "Jump Game II",
    difficulty: "Medium",
    pattern: "Greedy",
    fn: "jump",
    params: [["nums", "number[]"]],
    returns: "number",
    hints: [
      "Think in layers: everything reachable with 1 jump, then with 2 jumps, and so on.",
      "Track the end of the current layer and the farthest index reachable from it. When i reaches the layer's end, jump: the new end is the farthest.",
      "jumps = 0, end = 0, far = 0\nfor i in 0 .. n - 2:\n  far = max(far, i + nums[i])\n  if i == end:\n    jumps = jumps + 1\n    end = far\nreturn jumps",
    ],
    reference: `function jump(nums) { let j = 0, end = 0, far = 0; for (let i = 0; i < nums.length - 1; i++) { far = Math.max(far, i + nums[i]); if (i === end) { j++; end = far; } } return j; }`,
    brute: `function jump(nums) { const n = nums.length, dp = new Array(n).fill(Infinity); dp[0] = 0; for (let i = 0; i < n; i++) for (let k = 1; k <= nums[i] && i + k < n; k++) dp[i + k] = Math.min(dp[i + k], dp[i] + 1); return dp[n - 1]; }`,
    fuzz: gen(`return [__arr(rand, __r(rand, 2, 15), 1, 4)];`),
    examples: [[[2, 3, 1, 1, 4]], [[2, 3, 0, 1, 4]]],
    edges: [
      ["single", [[0]], "Already at the last index: 0 jumps."],
      ["all-equal", [[1, 1, 1, 1]]],
      ["boundary", [[10, 1, 1, 1]], "One jump covers everything."],
    ],
  },
  {
    slug: "gas-station",
    title: "Gas Station",
    difficulty: "Medium",
    pattern: "Greedy",
    fn: "canCompleteCircuit",
    params: [["gas", "number[]"], ["cost", "number[]"]],
    returns: "number",
    hints: [
      "If total gas < total cost, no start works. Otherwise exactly one does.",
      "Drive from 0 keeping a tank. Whenever it goes negative at i, no start in [start, i] can work, so restart at i + 1 with an empty tank.",
      "if sum(gas) < sum(cost): return -1\nstart = 0, tank = 0\nfor i in 0 .. n - 1:\n  tank = tank + gas[i] - cost[i]\n  if tank < 0: start = i + 1, tank = 0\nreturn start",
    ],
    reference: `function canCompleteCircuit(gas, cost) { let total = 0, tank = 0, start = 0; for (let i = 0; i < gas.length; i++) { const d = gas[i] - cost[i]; total += d; tank += d; if (tank < 0) { start = i + 1; tank = 0; } } return total < 0 ? -1 : start; }`,
    brute: `function canCompleteCircuit(gas, cost) { const n = gas.length; for (let s = 0; s < n; s++) { let tank = 0, ok = true; for (let k = 0; k < n; k++) { const i = (s + k) % n; tank += gas[i] - cost[i]; if (tank < 0) { ok = false; break; } } if (ok) return s; } return -1; }`,
    fuzz: gen(`for (;;) { const n = __r(rand, 1, 8), g = __arr(rand, n, 0, 10), c = __arr(rand, n, 0, 10); let valid = 0; for (let s = 0; s < n; s++) { let t = 0, ok = true; for (let k = 0; k < n; k++) { const i = (s + k) % n; t += g[i] - c[i]; if (t < 0) { ok = false; break; } } if (ok) valid++; } if (valid <= 1) return [g, c]; }`),
    examples: [[[1, 2, 3, 4, 5], [3, 4, 5, 1, 2]], [[2, 3, 4], [3, 4, 3]]],
    edges: [
      ["single", [[5], [4]]],
      ["boundary", [[3, 1, 1], [1, 2, 2]]],
      ["zeros", [[0, 0, 10], [1, 1, 1]], "Only the station with all the gas can start."],
    ],
  },
  {
    slug: "increasing-triplet-subsequence",
    title: "Increasing Triplet Subsequence",
    difficulty: "Medium",
    pattern: "Greedy",
    fn: "increasingTriplet",
    params: [["nums", "number[]"]],
    returns: "boolean",
    hints: [
      "Keep the smallest possible first value and the smallest possible second value seen so far.",
      "For each x: if x <= first, update first; else if x <= second, update second; else x completes a triplet.",
      "first = infinity, second = infinity\nfor x in nums:\n  if x <= first: first = x\n  else if x <= second: second = x\n  else: return true\nreturn false",
    ],
    reference: `function increasingTriplet(nums) { let a = Infinity, b = Infinity; for (const x of nums) { if (x <= a) a = x; else if (x <= b) b = x; else return true; } return false; }`,
    brute: `function increasingTriplet(nums) { const n = nums.length; for (let i = 0; i < n; i++) for (let j = i + 1; j < n; j++) for (let k = j + 1; k < n; k++) if (nums[i] < nums[j] && nums[j] < nums[k]) return true; return false; }`,
    fuzz: gen(`return [__arr(rand, __r(rand, 1, 12), 0, 10)];`),
    examples: [[[1, 2, 3, 4, 5]], [[5, 4, 3, 2, 1]], [[2, 1, 5, 0, 4, 6]]],
    edges: [
      ["two", [[1, 2]]],
      ["all-equal", [[1, 1, 1]], "Equal values aren't increasing."],
      ["boundary", [[20, 100, 10, 12, 5, 13]], "The first value is replaced later and still works."],
    ],
  },
  {
    slug: "wiggle-subsequence",
    title: "Wiggle Subsequence",
    difficulty: "Medium",
    pattern: "Greedy",
    fn: "wiggleMaxLength",
    params: [["nums", "number[]"]],
    returns: "number",
    hints: [
      "Every peak and valley of the sequence can be kept; points in the middle of a run can't help.",
      "Track up (longest wiggle ending with a rise) and down (ending with a fall). A rise sets up = down + 1, a fall sets down = up + 1.",
      "up = 1, down = 1\nfor i in 1 .. n - 1:\n  if nums[i] > nums[i - 1]: up = down + 1\n  else if nums[i] < nums[i - 1]: down = up + 1\nreturn max(up, down)",
    ],
    reference: `function wiggleMaxLength(nums) { let up = 1, down = 1; for (let i = 1; i < nums.length; i++) { if (nums[i] > nums[i - 1]) up = down + 1; else if (nums[i] < nums[i - 1]) down = up + 1; } return Math.max(up, down); }`,
    brute: `function wiggleMaxLength(nums) { const n = nums.length, up = new Array(n).fill(1), dn = new Array(n).fill(1); let best = 1; for (let i = 1; i < n; i++) { for (let j = 0; j < i; j++) { if (nums[i] > nums[j]) up[i] = Math.max(up[i], dn[j] + 1); else if (nums[i] < nums[j]) dn[i] = Math.max(dn[i], up[j] + 1); } best = Math.max(best, up[i], dn[i]); } return best; }`,
    fuzz: gen(`return [__arr(rand, __r(rand, 1, 15), 0, 10)];`),
    examples: [[[1, 7, 4, 9, 2, 5]], [[1, 17, 5, 10, 13, 15, 10, 5, 16, 8]], [[1, 2, 3, 4, 5, 6, 7, 8, 9]]],
    edges: [
      ["single", [[0]]],
      ["all-equal", [[3, 3, 3]], "No rise or fall: length 1."],
      ["two", [[2, 5]]],
    ],
  },
  {
    slug: "non-decreasing-array",
    title: "Non-decreasing Array",
    difficulty: "Medium",
    pattern: "Greedy",
    fn: "checkPossibility",
    params: [["nums", "number[]"]],
    returns: "boolean",
    hints: [
      "Find the first drop nums[i] > nums[i + 1]. A second drop means it's impossible.",
      "At a drop, lower nums[i] to nums[i + 1] if that keeps nums[i - 1] <= nums[i]; otherwise raise nums[i + 1] to nums[i]. Then keep scanning.",
      "changes = 0\nfor i in 0 .. n - 2:\n  if nums[i] > nums[i + 1]:\n    changes = changes + 1\n    if changes > 1: return false\n    if i == 0 or nums[i - 1] <= nums[i + 1]: nums[i] = nums[i + 1]\n    else: nums[i + 1] = nums[i]\nreturn true",
    ],
    reference: `function checkPossibility(nums) { const a = nums.slice(); let c = 0; for (let i = 0; i + 1 < a.length; i++) if (a[i] > a[i + 1]) { if (++c > 1) return false; if (i === 0 || a[i - 1] <= a[i + 1]) a[i] = a[i + 1]; else a[i + 1] = a[i]; } return true; }`,
    brute: `function checkPossibility(nums) { const sorted = (a) => a.every((v, i) => i === 0 || a[i - 1] <= v); if (sorted(nums)) return true; for (let i = 0; i < nums.length; i++) { const a = nums.slice(); a[i] = i === 0 ? -1e9 : a[i - 1]; if (sorted(a)) return true; } return false; }`,
    fuzz: gen(`const a = __sorted(rand, __r(rand, 1, 10), 0, 10); const k = __r(rand, 0, 2); for (let t = 0; t < k; t++) a[__r(rand, 0, a.length - 1)] = __r(rand, 0, 10); return [a];`),
    examples: [[[4, 2, 3]], [[4, 2, 1]]],
    edges: [
      ["single", [[1]]],
      ["boundary", [[3, 4, 2, 3]], "Lowering 4 or raising 2 both break something."],
      ["extremes", [[5, 7, 1, 8]], "Raise the 1 to 7."],
    ],
  },
  {
    slug: "maximum-swap",
    title: "Maximum Swap",
    difficulty: "Medium",
    pattern: "Greedy",
    fn: "maximumSwap",
    params: [["num", "number"]],
    returns: "number",
    hints: [
      "Swap the leftmost digit that has a larger digit somewhere to its right, with the largest such digit (its last occurrence).",
      "Record the last index of each digit 0-9. For each position from the left, look for a bigger digit (9 down) whose last index is to the right; swap and stop.",
      "d = digits of num, last[x] = last index of digit x\nfor i in 0 .. len(d) - 1:\n  for x from 9 down to d[i] + 1:\n    if last[x] > i:\n      swap d[i] and d[last[x]]\n      return number(d)\nreturn num",
    ],
    reference: `function maximumSwap(num) { const d = String(num).split("").map(Number), last = {}; d.forEach((x, i) => { last[x] = i; }); for (let i = 0; i < d.length; i++) for (let x = 9; x > d[i]; x--) if (last[x] > i) { [d[i], d[last[x]]] = [d[last[x]], d[i]]; return Number(d.join("")); } return num; }`,
    brute: `function maximumSwap(num) { const s = String(num).split(""); let best = num; for (let i = 0; i < s.length; i++) for (let j = i + 1; j < s.length; j++) { const t = s.slice(); [t[i], t[j]] = [t[j], t[i]]; best = Math.max(best, Number(t.join(""))); } return best; }`,
    fuzz: gen(`return [__r(rand, 0, rand() < 0.5 ? 9999 : 100000000)];`),
    examples: [[2736], [9973]],
    edges: [
      ["zeros", [0]],
      ["boundary", [1993], "Swap with the last 9, not the first."],
      ["duplicates", [98368]],
    ],
  },
  {
    slug: "broken-calculator",
    title: "Broken Calculator",
    difficulty: "Medium",
    pattern: "Greedy",
    fn: "brokenCalc",
    params: [["startValue", "number"], ["target", "number"]],
    returns: "number",
    hints: [
      "Work backwards from target: the reverse moves are 'halve' (if even) and 'add 1'.",
      "While target > startValue, halve it if even, else add 1. Then close the remaining gap with startValue - target decrements.",
      "ops = 0\nwhile target > startValue:\n  if target is even: target = target / 2\n  else: target = target + 1\n  ops = ops + 1\nreturn ops + startValue - target",
    ],
    reference: `function brokenCalc(startValue, target) { let ops = 0; while (target > startValue) { target = target % 2 ? target + 1 : target / 2; ops++; } return ops + startValue - target; }`,
    brute: `function brokenCalc(startValue, target) { const cap = 2 * Math.max(startValue, target) + 2, dist = new Map([[startValue, 0]]), q = [startValue]; for (let h = 0; h < q.length; h++) { const v = q[h]; if (v === target) return dist.get(v); for (const w of [v * 2, v - 1]) if (w >= 1 && w <= cap && !dist.has(w)) { dist.set(w, dist.get(v) + 1); q.push(w); } } return -1; }`,
    fuzz: gen(`return [__r(rand, 1, 100), __r(rand, 1, 100)];`),
    examples: [[2, 3], [5, 8], [3, 10]],
    edges: [
      ["all-equal", [7, 7]],
      ["boundary", [10, 1], "Only decrements help."],
      ["large", [1, 1024], "Ten doublings."],
    ],
  },
  {
    slug: "minimize-maximum-of-array",
    title: "Minimize Maximum of Array",
    difficulty: "Medium",
    pattern: "Greedy",
    fn: "minimizeArrayValue",
    params: [["nums", "number[]"]],
    returns: "number",
    hints: [
      "Values can only move left. So the first i + 1 elements can never average below their current average.",
      "The answer is the largest ceil(prefixSum / (i + 1)) over all prefixes: each prefix can be levelled to that, and no lower.",
      "sum = 0, best = 0\nfor i in 0 .. n - 1:\n  sum = sum + nums[i]\n  best = max(best, ceil(sum / (i + 1)))\nreturn best",
    ],
    reference: `function minimizeArrayValue(nums) { let s = 0, best = 0; nums.forEach((v, i) => { s += v; best = Math.max(best, Math.ceil(s / (i + 1))); }); return best; }`,
    brute: `function minimizeArrayValue(nums) { const ok = (m) => { let carry = 0; for (let i = nums.length - 1; i > 0; i--) carry = Math.max(0, nums[i] + carry - m); return nums[0] + carry <= m; }; let lo = 0, hi = Math.max(...nums); while (lo < hi) { const m = Math.floor((lo + hi) / 2); if (ok(m)) hi = m; else lo = m + 1; } return lo; }`,
    fuzz: gen(`return [__arr(rand, __r(rand, 2, 10), 0, 50)];`),
    examples: [[[3, 7, 1, 6]], [[10, 1]]],
    edges: [
      ["two", [[1, 10]]],
      ["all-equal", [[4, 4, 4]]],
      ["zeros", [[0, 0, 9]], "The 9 spreads across all three slots."],
    ],
  },
  {
    slug: "minimum-moves-to-equal-array-elements-ii",
    title: "Minimum Moves to Equal Array Elements II",
    difficulty: "Medium",
    pattern: "Greedy",
    fn: "minMoves2",
    params: [["nums", "number[]"]],
    returns: "number",
    hints: [
      "The sum of distances |x - t| is minimised when t is a median.",
      "Sort and pair the smallest with the largest: each pair costs their difference no matter where t sits between them.",
      "sort nums\nlo = 0, hi = n - 1, moves = 0\nwhile lo < hi:\n  moves = moves + nums[hi] - nums[lo]\n  lo = lo + 1, hi = hi - 1\nreturn moves",
    ],
    reference: `function minMoves2(nums) { const a = nums.slice().sort((x, y) => x - y); let m = 0; for (let i = 0, j = a.length - 1; i < j; i++, j--) m += a[j] - a[i]; return m; }`,
    brute: `function minMoves2(nums) { let best = Infinity; for (let t = Math.min(...nums); t <= Math.max(...nums); t++) best = Math.min(best, nums.reduce((s, v) => s + Math.abs(v - t), 0)); return best; }`,
    fuzz: gen(`return [__arr(rand, __r(rand, 1, 12), -20, 20)];`),
    examples: [[[1, 2, 3]], [[1, 10, 2, 9]]],
    edges: [
      ["single", [[5]]],
      ["all-equal", [[2, 2, 2]]],
      ["negatives", [[-5, 0, 5]]],
    ],
  },
  {
    slug: "valid-parenthesis-string",
    title: "Valid Parenthesis String",
    difficulty: "Medium",
    pattern: "Greedy",
    fn: "checkValidString",
    params: [["s", "string"]],
    returns: "boolean",
    hints: [
      "You don't need to decide what each * is. Track the range of possible open-bracket counts.",
      "lo and hi bound the open count: '(' raises both, ')' lowers both, '*' lowers lo and raises hi. If hi < 0 fail; clamp lo at 0. Valid if lo == 0 at the end.",
      "lo = 0, hi = 0\nfor c in s:\n  if c == '(': lo += 1, hi += 1\n  else if c == ')': lo -= 1, hi -= 1\n  else: lo -= 1, hi += 1\n  if hi < 0: return false\n  lo = max(lo, 0)\nreturn lo == 0",
    ],
    reference: `function checkValidString(s) { let lo = 0, hi = 0; for (const c of s) { if (c === "(") { lo++; hi++; } else if (c === ")") { lo--; hi--; } else { lo--; hi++; } if (hi < 0) return false; lo = Math.max(lo, 0); } return lo === 0; }`,
    brute: `function checkValidString(s) { const memo = new Map(); const go = (i, open) => { if (open < 0) return false; if (i === s.length) return open === 0; const k = i * 200 + open; if (memo.has(k)) return memo.get(k); const c = s[i]; const r = c === "(" ? go(i + 1, open + 1) : c === ")" ? go(i + 1, open - 1) : go(i + 1, open + 1) || go(i + 1, open - 1) || go(i + 1, open); memo.set(k, r); return r; }; return go(0, 0); }`,
    fuzz: gen(`return [__str(rand, __r(rand, 1, 12), "()*")];`),
    examples: [["()"], ["(*)"], ["(*))"]],
    edges: [
      ["single-char", ["*"], "A lone star can be empty."],
      ["boundary", [")("]],
      ["all-equal", ["(((("]],
    ],
  },
  {
    slug: "insert-interval",
    title: "Insert Interval",
    difficulty: "Medium",
    pattern: "Intervals",
    fn: "insert",
    params: [["intervals", "number[][]"], ["newInterval", "number[]"]],
    returns: "number[][]",
    hints: [
      "The list is sorted and disjoint, so it splits into three parts: entirely before the new interval, overlapping it, entirely after.",
      "Copy intervals that end before it starts. Merge every overlapping one into it (min start, max end). Then copy the rest.",
      "out = [], i = 0, [s, e] = newInterval\nwhile i < n and intervals[i].end < s: append intervals[i], i += 1\nwhile i < n and intervals[i].start <= e:\n  s = min(s, intervals[i].start), e = max(e, intervals[i].end), i += 1\nappend [s, e]\nappend intervals[i ..]\nreturn out",
    ],
    reference: `function insert(intervals, newInterval) { const out = []; let i = 0, [s, e] = newInterval; while (i < intervals.length && intervals[i][1] < s) out.push(intervals[i++]); while (i < intervals.length && intervals[i][0] <= e) { s = Math.min(s, intervals[i][0]); e = Math.max(e, intervals[i][1]); i++; } out.push([s, e]); while (i < intervals.length) out.push(intervals[i++]); return out; }`,
    brute: `function insert(intervals, newInterval) { const all = [...intervals, newInterval].map((x) => x.slice()).sort((a, b) => a[0] - b[0]); const out = []; for (const iv of all) { if (out.length && iv[0] <= out[out.length - 1][1]) out[out.length - 1][1] = Math.max(out[out.length - 1][1], iv[1]); else out.push(iv); } return out; }`,
    fuzz: gen(`${DISJOINT} const s = __r(rand, 0, 25); return [__ivs(rand, __r(rand, 0, 6)), [s, s + __r(rand, 0, 6)]];`),
    examples: [[[[1, 3], [6, 9]], [2, 5]], [[[1, 2], [3, 5], [6, 7], [8, 10], [12, 16]], [4, 8]]],
    edges: [
      ["empty", [[], [5, 7]]],
      ["boundary", [[[1, 5]], [6, 8]], "5 and 6 don't overlap: two intervals."],
      ["extremes", [[[3, 5], [7, 9]], [0, 100]], "The new interval swallows everything."],
    ],
  },
  {
    slug: "non-overlapping-intervals",
    title: "Non-overlapping Intervals",
    difficulty: "Medium",
    pattern: "Intervals",
    fn: "eraseOverlapIntervals",
    params: [["intervals", "number[][]"]],
    returns: "number",
    hints: [
      "Removing the fewest is the same as keeping the most. Which interval should you keep first?",
      "Sort by end. Keep an interval when it starts at or after the last kept end; otherwise remove it. Ending early leaves the most room.",
      "sort intervals by end\nend = -infinity, removed = 0\nfor [s, e] in intervals:\n  if s >= end: end = e\n  else: removed = removed + 1\nreturn removed",
    ],
    reference: `function eraseOverlapIntervals(intervals) { const a = intervals.slice().sort((x, y) => x[1] - y[1]); let end = -Infinity, r = 0; for (const [s, e] of a) { if (s >= end) end = e; else r++; } return r; }`,
    brute: `function eraseOverlapIntervals(intervals) { const n = intervals.length; let keep = 0; for (let m = 0; m < 1 << n; m++) { const pick = intervals.filter((_, i) => m & (1 << i)).sort((a, b) => a[0] - b[0]); if (pick.every((iv, i) => i === 0 || pick[i - 1][1] <= iv[0])) keep = Math.max(keep, pick.length); } return n - keep; }`,
    fuzz: gen(`return [${IVS("__r(rand, 1, 10)", 0, 20, 6)}];`),
    examples: [[[[1, 2], [2, 3], [3, 4], [1, 3]]], [[[1, 2], [1, 2], [1, 2]]], [[[1, 2], [2, 3]]]],
    edges: [
      ["single", [[[1, 5]]]],
      ["extremes", [[[1, 100], [2, 3], [4, 5]]], "Drop the one long interval, not the two short ones."],
      ["negatives", [[[-5, -1], [-3, 2]]]],
    ],
  },
  {
    slug: "minimum-number-of-arrows-to-burst-balloons",
    title: "Minimum Number of Arrows to Burst Balloons",
    difficulty: "Medium",
    pattern: "Intervals",
    fn: "findMinArrowShots",
    params: [["points", "number[][]"]],
    returns: "number",
    hints: [
      "Shoot the balloon that ends first at its right edge: that arrow also bursts everything that started before it.",
      "Sort by end. Fire at the first end; skip every balloon whose start is <= that position; fire again at the next unburst balloon's end.",
      "sort points by end\narrows = 0, pos = -infinity\nfor [s, e] in points:\n  if s > pos:\n    arrows = arrows + 1\n    pos = e\nreturn arrows",
    ],
    reference: `function findMinArrowShots(points) { const a = points.slice().sort((x, y) => x[1] - y[1]); let n = 0, pos = -Infinity; for (const [s, e] of a) if (s > pos) { n++; pos = e; } return n; }`,
    brute: `function findMinArrowShots(points) { const n = points.length, full = (1 << n) - 1, dp = new Array(1 << n).fill(Infinity); dp[0] = 0; const xs = points.map((p) => p[1]); for (let m = 0; m < full; m++) { if (dp[m] === Infinity) continue; for (const x of xs) { let h = m; points.forEach((p, i) => { if (p[0] <= x && x <= p[1]) h |= 1 << i; }); if (h !== m) dp[h] = Math.min(dp[h], dp[m] + 1); } } return dp[full]; }`,
    fuzz: gen(`return [${IVS("__r(rand, 1, 10)", -10, 20, 6, 0)}];`),
    examples: [[[[10, 16], [2, 8], [1, 6], [7, 12]]], [[[1, 2], [3, 4], [5, 6], [7, 8]]], [[[1, 2], [2, 3], [3, 4], [4, 5]]]],
    edges: [
      ["single", [[[1, 1]]]],
      ["extremes", [[[-2147483648, 2147483647]]]],
      ["all-equal", [[[1, 5], [1, 5]]]],
    ],
  },
  {
    slug: "maximum-length-of-pair-chain",
    title: "Maximum Length of Pair Chain",
    difficulty: "Medium",
    pattern: "Greedy",
    fn: "findLongestChain",
    params: [["pairs", "number[][]"]],
    returns: "number",
    hints: [
      "This is interval scheduling with strict inequality: pick the pair that ends first.",
      "Sort by right end. Take a pair when its left end is strictly greater than the last taken right end.",
      "sort pairs by right end\ncur = -infinity, count = 0\nfor [a, b] in pairs:\n  if a > cur:\n    count = count + 1\n    cur = b\nreturn count",
    ],
    reference: `function findLongestChain(pairs) { const a = pairs.slice().sort((x, y) => x[1] - y[1]); let cur = -Infinity, c = 0; for (const [l, r] of a) if (l > cur) { c++; cur = r; } return c; }`,
    brute: `function findLongestChain(pairs) { const a = pairs.slice().sort((x, y) => x[0] - y[0]), dp = a.map(() => 1); for (let i = 0; i < a.length; i++) for (let j = 0; j < i; j++) if (a[j][1] < a[i][0]) dp[i] = Math.max(dp[i], dp[j] + 1); return Math.max(...dp); }`,
    fuzz: gen(`return [${IVS("__r(rand, 1, 10)", -10, 20, 6)}];`),
    examples: [[[[1, 2], [2, 3], [3, 4]]], [[[1, 2], [7, 8], [4, 5]]]],
    edges: [
      ["single", [[[1, 5]]]],
      ["all-equal", [[[1, 2], [1, 2]]]],
      ["negatives", [[[-6, -3], [-2, 0], [1, 4]]]],
    ],
  },
  {
    slug: "remove-covered-intervals",
    title: "Remove Covered Intervals",
    difficulty: "Medium",
    pattern: "Intervals",
    fn: "removeCoveredIntervals",
    params: [["intervals", "number[][]"]],
    returns: "number",
    hints: [
      "Sort by start ascending, and for equal starts by end descending, so a covering interval always comes first.",
      "Scan keeping the largest end so far. An interval whose end is <= that end is covered; otherwise it survives and raises the end.",
      "sort by (start ascending, end descending)\nmaxEnd = -infinity, kept = 0\nfor [s, e] in intervals:\n  if e > maxEnd:\n    kept = kept + 1\n    maxEnd = e\nreturn kept",
    ],
    reference: `function removeCoveredIntervals(intervals) { const a = intervals.slice().sort((x, y) => x[0] - y[0] || y[1] - x[1]); let end = -Infinity, k = 0; for (const [, e] of a) if (e > end) { k++; end = e; } return k; }`,
    brute: `function removeCoveredIntervals(intervals) { return intervals.filter((a, i) => !intervals.some((b, j) => j !== i && b[0] <= a[0] && a[1] <= b[1])).length; }`,
    fuzz: gen(`const seen = new Set(), out = []; const n = __r(rand, 1, 10); while (out.length < n) { const s = __r(rand, 0, 15), e = s + __r(rand, 1, 6); if (!seen.has(s + ":" + e)) { seen.add(s + ":" + e); out.push([s, e]); } } return [out];`),
    examples: [[[[1, 4], [3, 6], [2, 8]]], [[[1, 4], [2, 3]]]],
    edges: [
      ["single", [[[1, 2]]]],
      ["boundary", [[[1, 2], [1, 4], [3, 4]]], "Shared endpoints still count as covered."],
      ["sorted", [[[1, 2], [3, 4]]]],
    ],
  },
  {
    slug: "car-pooling",
    title: "Car Pooling",
    difficulty: "Medium",
    pattern: "Intervals",
    fn: "carPooling",
    params: [["trips", "number[][]"], ["capacity", "number"]],
    returns: "boolean",
    hints: [
      "Passengers board at from and leave at to. Track the change in load at each location.",
      "Add num at from and subtract it at to (a difference array, or sorted events with drop-offs first). Walk the locations; fail if the running load exceeds capacity.",
      "delta = map of location -> change\nfor (num, from, to) in trips: delta[from] += num, delta[to] -= num\nload = 0\nfor location in sorted keys of delta:\n  load = load + delta[location]\n  if load > capacity: return false\nreturn true",
    ],
    reference: `function carPooling(trips, capacity) { const d = new Map(); for (const [n, f, t] of trips) { d.set(f, (d.get(f) || 0) + n); d.set(t, (d.get(t) || 0) - n); } let load = 0; for (const k of [...d.keys()].sort((a, b) => a - b)) { load += d.get(k); if (load > capacity) return false; } return true; }`,
    brute: `function carPooling(trips, capacity) { for (let x = 0; x <= 1000; x++) { let load = 0; for (const [n, f, t] of trips) if (f <= x && x < t) load += n; if (load > capacity) return false; } return true; }`,
    fuzz: gen(`return [Array.from({ length: __r(rand, 1, 8) }, () => { const f = __r(rand, 0, 20); return [__r(rand, 1, 5), f, f + __r(rand, 1, 8)]; }), __r(rand, 1, 15)];`),
    examples: [[[[2, 1, 5], [3, 3, 7]], 4], [[[2, 1, 5], [3, 3, 7]], 5]],
    edges: [
      ["single", [[[3, 0, 1]], 3]],
      ["boundary", [[[2, 1, 5], [3, 5, 7]], 3], "Drop-off at 5 happens before the pick-up at 5."],
      ["extremes", [[[5, 0, 1000]], 4]],
    ],
  },
  {
    slug: "count-days-without-meetings",
    title: "Count Days Without Meetings",
    difficulty: "Medium",
    pattern: "Intervals",
    fn: "countDays",
    params: [["days", "number"], ["meetings", "number[][]"]],
    returns: "number",
    hints: [
      "Merge the meetings into disjoint blocks; the free days are whatever the blocks don't cover.",
      "Sort by start. Keep the end of the covered area so far; a meeting starting after it leaves a gap of start - end - 1 free days.",
      "sort meetings by start\nfree = 0, end = 0\nfor [s, e] in meetings:\n  if s > end + 1: free = free + (s - end - 1)\n  end = max(end, e)\nreturn free + (days - end)",
    ],
    reference: `function countDays(days, meetings) { const a = meetings.slice().sort((x, y) => x[0] - y[0]); let free = 0, end = 0; for (const [s, e] of a) { if (s > end + 1) free += s - end - 1; end = Math.max(end, e); } return free + days - end; }`,
    brute: `function countDays(days, meetings) { const busy = new Array(days + 1).fill(false); for (const [s, e] of meetings) for (let d = s; d <= e; d++) busy[d] = true; let c = 0; for (let d = 1; d <= days; d++) if (!busy[d]) c++; return c; }`,
    fuzz: gen(`const days = __r(rand, 1, 40); return [days, Array.from({ length: __r(rand, 1, 6) }, () => { const s = __r(rand, 1, days); return [s, __r(rand, s, days)]; })];`),
    examples: [[10, [[5, 7], [1, 3], [9, 10]]], [5, [[2, 4], [1, 3]]], [6, [[1, 6]]]],
    edges: [
      ["single", [1, [[1, 1]]]],
      ["boundary", [10, [[2, 3]]], "Free days at both ends."],
      ["duplicates", [8, [[2, 5], [2, 5], [3, 4]]]],
    ],
  },
  {
    slug: "video-stitching",
    title: "Video Stitching",
    difficulty: "Medium",
    pattern: "Greedy",
    fn: "videoStitching",
    params: [["clips", "number[][]"], ["time", "number"]],
    returns: "number",
    hints: [
      "This is jump game in disguise: from each covered point, how far can one more clip take you?",
      "Record for every start the farthest end. Walk t from 0, tracking the farthest reach; when t hits the current clip's end, take another clip (fail if the reach didn't grow).",
      "far[s] = max end among clips starting at s\ncount = 0, end = 0, reach = 0\nfor t in 0 .. time - 1:\n  reach = max(reach, far[t])\n  if t == end:\n    if reach <= t: return -1\n    count = count + 1, end = reach\nreturn count",
    ],
    reference: `function videoStitching(clips, time) { const far = new Array(time + 1).fill(0); for (const [s, e] of clips) if (s <= time) far[s] = Math.max(far[s], e); let c = 0, end = 0, reach = 0; for (let t = 0; t < time; t++) { reach = Math.max(reach, far[t]); if (t === end) { if (reach <= t) return -1; c++; end = reach; } } return c; }`,
    brute: `function videoStitching(clips, time) { const dp = new Array(time + 1).fill(Infinity); dp[0] = 0; for (let round = 0; round <= clips.length; round++) for (const [s, e] of clips) { let best = Infinity; for (let u = s; u <= Math.min(e, time); u++) best = Math.min(best, dp[u]); if (best === Infinity) continue; for (let t = s; t <= Math.min(e, time); t++) dp[t] = Math.min(dp[t], best + 1); } return dp[time] === Infinity ? -1 : dp[time]; }`,
    fuzz: gen(`return [${IVS("__r(rand, 1, 10)", 0, 12, 5, 0)}, __r(rand, 1, 12)];`),
    examples: [[[[0, 2], [4, 6], [8, 10], [1, 9], [1, 5], [5, 9]], 10], [[[0, 1], [1, 2]], 5]],
    edges: [
      ["single", [[[0, 5]], 5]],
      ["no-answer", [[[1, 4]], 3], "Nothing covers time 0."],
      ["boundary", [[[0, 4], [2, 8]], 5]],
    ],
  },
  {
    slug: "largest-number",
    title: "Largest Number",
    difficulty: "Medium",
    pattern: "Greedy",
    fn: "largestNumber",
    params: [["nums", "number[]"]],
    returns: "string",
    hints: [
      "Ordering numbers by value doesn't work (9 should beat 10). Compare a and b by which concatenation is bigger: a + b or b + a.",
      "Sort the strings with that comparator and join. If the result starts with 0, every number was 0: return \"0\".",
      "strs = nums as strings\nsort strs so that a comes before b when a + b > b + a\nresult = join strs\nif result starts with '0': return '0'\nreturn result",
    ],
    reference: `function largestNumber(nums) { const s = nums.map(String).sort((a, b) => (b + a).localeCompare(a + b)).join(""); return s[0] === "0" ? "0" : s; }`,
    brute: `function largestNumber(nums) { let best = ""; const go = (left, cur) => { if (!left.length) { if (best === "" || cur > best) best = cur; return; } left.forEach((v, i) => go([...left.slice(0, i), ...left.slice(i + 1)], cur + v)); }; go(nums.map(String), ""); return best.replace(/^0+(?=.)/, ""); }`,
    fuzz: gen(`return [__arr(rand, __r(rand, 1, 6), 0, 100)];`),
    examples: [[[10, 2]], [[3, 30, 34, 5, 9]]],
    edges: [
      ["zeros", [[0, 0]], "All zeros: \"0\", not \"00\"."],
      ["single", [[1]]],
      ["duplicates", [[121, 12]]],
    ],
  },
  {
    slug: "queue-reconstruction-by-height",
    title: "Queue Reconstruction by Height",
    difficulty: "Medium",
    pattern: "Greedy",
    fn: "reconstructQueue",
    params: [["people", "number[][]"]],
    returns: "number[][]",
    hints: [
      "Shorter people are invisible to taller ones. Place the tallest first; shorter people inserted later don't change their counts.",
      "Sort by height descending, then k ascending. Insert each person at index k of the result.",
      "sort people by (h descending, k ascending)\nqueue = []\nfor [h, k] in people:\n  insert [h, k] at position k in queue\nreturn queue",
    ],
    reference: `function reconstructQueue(people) { const a = people.slice().sort((x, y) => y[0] - x[0] || x[1] - y[1]), q = []; for (const p of a) q.splice(p[1], 0, p); return q; }`,
    brute: `function reconstructQueue(people) { let ans = null; const go = (left, cur) => { if (ans) return; if (!left.length) { ans = cur; return; } left.forEach((p, i) => { if (!ans && cur.filter((x) => x[0] >= p[0]).length === p[1]) go([...left.slice(0, i), ...left.slice(i + 1)], [...cur, p]); }); }; go(people, []); return ans; }`,
    fuzz: gen(`const hs = __arr(rand, __r(rand, 1, 7), 1, 8); const people = hs.map((h, i) => [h, hs.slice(0, i).filter((x) => x >= h).length]); return [__shuffle(rand, people)];`),
    examples: [[[[7, 0], [4, 4], [7, 1], [5, 0], [6, 1], [5, 2]]], [[[6, 0], [5, 0], [4, 0], [3, 2], [2, 2], [1, 4]]]],
    edges: [
      ["single", [[[5, 0]]]],
      ["all-equal", [[[5, 1], [5, 0], [5, 2]]], "Equal heights count as 'taller or equal'."],
      ["sorted", [[[1, 0], [2, 0], [3, 0]]]],
    ],
  },
  {
    slug: "hand-of-straights",
    title: "Hand of Straights",
    difficulty: "Medium",
    pattern: "Greedy",
    fn: "isNStraightHand",
    params: [["hand", "number[]"], ["groupSize", "number"]],
    returns: "boolean",
    hints: [
      "The smallest card left must start a group; nothing smaller can contain it.",
      "Count cards. Walk the values in sorted order; for each value with count c > 0, the next groupSize - 1 values must each have at least c cards. Subtract c from all of them.",
      "if n mod groupSize != 0: return false\ncount = frequency map\nfor x in sorted keys of count:\n  c = count[x]\n  if c > 0:\n    for y in x .. x + groupSize - 1:\n      if count[y] < c: return false\n      count[y] = count[y] - c\nreturn true",
    ],
    reference: `function isNStraightHand(hand, groupSize) { if (hand.length % groupSize) return false; const cnt = new Map(); for (const x of hand) cnt.set(x, (cnt.get(x) || 0) + 1); for (const x of [...cnt.keys()].sort((a, b) => a - b)) { const c = cnt.get(x); if (!c) continue; for (let y = x; y < x + groupSize; y++) { if ((cnt.get(y) || 0) < c) return false; cnt.set(y, cnt.get(y) - c); } } return true; }`,
    brute: `function isNStraightHand(hand, groupSize) { const a = hand.slice().sort((x, y) => x - y); while (a.length) { const start = a[0]; for (let v = start; v < start + groupSize; v++) { const i = a.indexOf(v); if (i < 0) return false; a.splice(i, 1); } } return true; }`,
    fuzz: gen(`const g = __r(rand, 1, 4); if (rand() < 0.5) { const a = []; for (let t = __r(rand, 1, 3); t > 0; t--) { const s = __r(rand, 0, 8); for (let v = s; v < s + g; v++) a.push(v); } return [__shuffle(rand, a), g]; } return [__arr(rand, __r(rand, 1, 10), 0, 8), g];`),
    examples: [[[1, 2, 3, 6, 2, 3, 4, 7, 8], 3], [[1, 2, 3, 4, 5], 4]],
    edges: [
      ["single", [[5], 1]],
      ["boundary", [[1, 1, 2, 2, 3, 3], 3], "Two overlapping straights."],
      ["duplicates", [[1, 1, 2, 3], 2]],
    ],
  },
  {
    slug: "merge-triplets-to-form-target-triplet",
    title: "Merge Triplets to Form Target Triplet",
    difficulty: "Medium",
    pattern: "Greedy",
    fn: "mergeTriplets",
    params: [["triplets", "number[][]"], ["target", "number[]"]],
    returns: "boolean",
    hints: [
      "Merging takes the max in each coordinate, so any triplet with a value above the target ruins it. Ignore those.",
      "Among the safe triplets (every value <= target's), check that each of the three target values is matched by at least one of them.",
      "found = [false, false, false]\nfor t in triplets:\n  if t[0] <= target[0] and t[1] <= target[1] and t[2] <= target[2]:\n    for k in 0 .. 2:\n      if t[k] == target[k]: found[k] = true\nreturn all of found",
    ],
    reference: `function mergeTriplets(triplets, target) { const f = [false, false, false]; for (const t of triplets) if (t.every((v, k) => v <= target[k])) t.forEach((v, k) => { if (v === target[k]) f[k] = true; }); return f.every(Boolean); }`,
    brute: `function mergeTriplets(triplets, target) { const n = triplets.length; for (let m = 1; m < 1 << n; m++) { const r = [0, 0, 0]; for (let i = 0; i < n; i++) if (m & (1 << i)) for (let k = 0; k < 3; k++) r[k] = Math.max(r[k], triplets[i][k]); if (r[0] === target[0] && r[1] === target[1] && r[2] === target[2]) return true; } return false; }`,
    fuzz: gen(`const ts = Array.from({ length: __r(rand, 1, 8) }, () => [__r(rand, 1, 6), __r(rand, 1, 6), __r(rand, 1, 6)]); return [ts, [__r(rand, 1, 6), __r(rand, 1, 6), __r(rand, 1, 6)]];`),
    examples: [[[[2, 5, 3], [1, 8, 4], [1, 7, 5]], [2, 7, 5]], [[[3, 4, 5], [4, 5, 6]], [3, 2, 5]], [[[2, 5, 3], [2, 3, 4], [1, 2, 5], [5, 2, 3]], [5, 5, 5]]],
    edges: [
      ["single", [[[1, 2, 3]], [1, 2, 3]]],
      ["no-answer", [[[1, 1, 1]], [2, 2, 2]]],
      ["boundary", [[[1, 1, 5], [1, 5, 1], [5, 1, 1]], [5, 5, 5]], "Each coordinate comes from a different triplet."],
    ],
  },
  {
    slug: "minimum-deletions-to-make-character-frequencies-unique",
    title: "Minimum Deletions to Make Character Frequencies Unique",
    difficulty: "Medium",
    pattern: "Greedy",
    fn: "minDeletions",
    params: [["s", "string"]],
    returns: "number",
    hints: [
      "Only the multiset of frequencies matters. Two letters with the same count force a deletion.",
      "Process frequencies from largest to smallest, keeping the highest still-allowed value. Each frequency drops to min(itself, allowed); the drop is the cost, and allowed becomes that value minus 1 (not below 0).",
      "freqs = letter counts sorted descending\nallowed = infinity, deletions = 0\nfor f in freqs:\n  keep = min(f, allowed)\n  deletions = deletions + f - keep\n  allowed = max(keep - 1, 0)\nreturn deletions",
    ],
    reference: `function minDeletions(s) { const cnt = {}; for (const c of s) cnt[c] = (cnt[c] || 0) + 1; let allowed = Infinity, d = 0; for (const f of Object.values(cnt).sort((a, b) => b - a)) { const keep = Math.min(f, allowed); d += f - keep; allowed = Math.max(keep - 1, 0); } return d; }`,
    brute: `function minDeletions(s) { const cnt = {}; for (const c of s) cnt[c] = (cnt[c] || 0) + 1; const used = new Set(); let d = 0; for (let f of Object.values(cnt)) { while (f > 0 && used.has(f)) { f--; d++; } if (f > 0) used.add(f); } return d; }`,
    fuzz: gen(`return [__str(rand, __r(rand, 1, 20), "abcde")];`),
    examples: [["aab"], ["aaabbbcc"], ["ceabaacb"]],
    edges: [
      ["single-char", ["z"]],
      ["duplicates", ["abc"], "Three letters with count 1: two must go."],
      ["boundary", ["aaaabbbb"]],
    ],
  },
  {
    slug: "jump-game-vii",
    title: "Jump Game VII",
    difficulty: "Medium",
    pattern: "Greedy",
    fn: "canReach",
    params: [["s", "string"], ["minJump", "number"], ["maxJump", "number"]],
    returns: "boolean",
    hints: [
      "Index i is reachable if s[i] is '0' and some reachable j lies in [i - maxJump, i - minJump].",
      "Keep a running count of reachable indexes inside that sliding window (add i - minJump as it enters, drop i - maxJump - 1 as it leaves).",
      "reach[0] = true, count = 0\nfor i in 1 .. n - 1:\n  if i - minJump >= 0 and reach[i - minJump]: count += 1\n  if i - maxJump - 1 >= 0 and reach[i - maxJump - 1]: count -= 1\n  reach[i] = (s[i] == '0' and count > 0)\nreturn reach[n - 1]",
    ],
    reference: `function canReach(s, minJump, maxJump) { const n = s.length, r = new Array(n).fill(false); r[0] = true; let c = 0; for (let i = 1; i < n; i++) { if (i - minJump >= 0 && r[i - minJump]) c++; if (i - maxJump - 1 >= 0 && r[i - maxJump - 1]) c--; r[i] = s[i] === "0" && c > 0; } return r[n - 1]; }`,
    brute: `function canReach(s, minJump, maxJump) { const n = s.length, r = new Array(n).fill(false); r[0] = true; for (let i = 0; i < n; i++) if (r[i]) for (let j = i + minJump; j <= Math.min(n - 1, i + maxJump); j++) if (s[j] === "0") r[j] = true; return r[n - 1]; }`,
    fuzz: gen(`const lo = __r(rand, 1, 3); return ["0" + __str(rand, __r(rand, 1, 14), "0001"), lo, lo + __r(rand, 0, 4)];`),
    examples: [["011010", 2, 3], ["01101110", 2, 3]],
    edges: [
      ["two", ["00", 1, 1]],
      ["no-answer", ["01", 1, 1], "The last index is '1'."],
      ["boundary", ["0000000", 3, 3], "Exact jumps of 3: 0 -> 3 -> 6."],
    ],
  },
  {
    slug: "candy",
    title: "Candy",
    difficulty: "Hard",
    pattern: "Greedy",
    fn: "candy",
    params: [["ratings", "number[]"]],
    returns: "number",
    hints: [
      "Each child has two constraints, one from each neighbour. Handle them separately.",
      "Left-to-right: if rating rises, give one more than the left neighbour. Right-to-left: if rating rises going left, take the max with one more than the right neighbour. Sum.",
      "c = [1] * n\nfor i in 1 .. n - 1:\n  if ratings[i] > ratings[i - 1]: c[i] = c[i - 1] + 1\nfor i from n - 2 down to 0:\n  if ratings[i] > ratings[i + 1]: c[i] = max(c[i], c[i + 1] + 1)\nreturn sum(c)",
    ],
    reference: `function candy(ratings) { const n = ratings.length, c = new Array(n).fill(1); for (let i = 1; i < n; i++) if (ratings[i] > ratings[i - 1]) c[i] = c[i - 1] + 1; for (let i = n - 2; i >= 0; i--) if (ratings[i] > ratings[i + 1]) c[i] = Math.max(c[i], c[i + 1] + 1); return c.reduce((a, b) => a + b, 0); }`,
    brute: `function candy(ratings) { const n = ratings.length, c = new Array(n).fill(1); let changed = true; while (changed) { changed = false; for (let i = 0; i < n; i++) { if (i > 0 && ratings[i] > ratings[i - 1] && c[i] <= c[i - 1]) { c[i] = c[i - 1] + 1; changed = true; } if (i + 1 < n && ratings[i] > ratings[i + 1] && c[i] <= c[i + 1]) { c[i] = c[i + 1] + 1; changed = true; } } } return c.reduce((a, b) => a + b, 0); }`,
    fuzz: gen(`return [__arr(rand, __r(rand, 1, 12), 0, 5)];`),
    examples: [[[1, 0, 2]], [[1, 2, 2]]],
    edges: [
      ["single", [[5]]],
      ["all-equal", [[3, 3, 3]], "Equal neighbours need no extra candy."],
      ["reverse-sorted", [[5, 4, 3, 2, 1]]],
    ],
  },
  {
    slug: "minimum-number-of-taps-to-open-to-water-a-garden",
    title: "Minimum Number of Taps to Open to Water a Garden",
    difficulty: "Hard",
    pattern: "Greedy",
    fn: "minTaps",
    params: [["n", "number"], ["ranges", "number[]"]],
    returns: "number",
    hints: [
      "Tap i covers [i - ranges[i], i + ranges[i]]. You need the fewest intervals covering [0, n]: the video-stitching / jump-game pattern.",
      "For each left end (clamped at 0), store the farthest right end. Then sweep: when you reach the end of the current coverage, open the tap that reaches farthest; fail if coverage stops growing.",
      "far[l] = max right end among taps whose left end is l (clamped to [0, n])\ntaps = 0, end = 0, reach = 0\nfor x in 0 .. n - 1:\n  reach = max(reach, far[x])\n  if x == end:\n    if reach <= x: return -1\n    taps = taps + 1, end = reach\nreturn taps",
    ],
    reference: `function minTaps(n, ranges) { const far = new Array(n + 1).fill(0); ranges.forEach((r, i) => { const l = Math.max(0, i - r); far[l] = Math.max(far[l], Math.min(n, i + r)); }); let t = 0, end = 0, reach = 0; for (let x = 0; x < n; x++) { reach = Math.max(reach, far[x]); if (x === end) { if (reach <= x) return -1; t++; end = reach; } } return t; }`,
    brute: `function minTaps(n, ranges) { const iv = ranges.map((r, i) => [Math.max(0, i - r), Math.min(n, i + r)]); const dp = new Array(n + 1).fill(Infinity); dp[0] = 0; for (let round = 0; round <= iv.length; round++) for (const [s, e] of iv) { let best = Infinity; for (let u = s; u <= e; u++) best = Math.min(best, dp[u]); if (best === Infinity) continue; for (let t = s; t <= e; t++) dp[t] = Math.min(dp[t], best + 1); } return dp[n] === Infinity ? -1 : dp[n]; }`,
    fuzz: gen(`const n = __r(rand, 1, 12); return [n, __arr(rand, n + 1, 0, 4)];`),
    examples: [[5, [3, 4, 1, 1, 0, 0]], [3, [0, 0, 0, 0]]],
    edges: [
      ["min-size", [1, [1, 0]]],
      ["zeros", [2, [0, 2, 0]], "The middle tap covers everything."],
      ["boundary", [7, [1, 2, 1, 0, 2, 1, 0, 1]]],
    ],
  },
];

export const LADDER_GREEDY_SEEDED: ProblemSpec[] = DEFS.map((d) => define(d).spec);
