import { define, type ProblemDef } from "../../dsa-extras/define";
import { gen } from "../../dsa-extras/gen";
import type { ProblemSpec } from "../types";

/** Generator helpers for grids and edge lists (source text, run in node:vm). */
const GRAPH_PRELUDE = `
function __grid(rand, r, c, p) { return Array.from({ length: r }, function () { return Array.from({ length: c }, function () { return rand() < p ? 1 : 0; }); }); }
function __edges(rand, n, m, base) { var seen = {}, out = [], tries = 0; base = base || 0; while (out.length < m && tries++ < 400) { var a = __r(rand, 0, n - 1), b = __r(rand, 0, n - 1); if (a === b) continue; var k = Math.min(a, b) + "," + Math.max(a, b); if (seen[k]) continue; seen[k] = 1; out.push([a + base, b + base]); } return out; }
function __tree(rand, n, base) { base = base || 0; var out = []; for (var i = 1; i < n; i++) out.push(__shuffle(rand, [__r(rand, 0, i - 1) + base, i + base])); return out; }
function __island(rand, r, c, k) { var g = __grid(rand, r, c, 0), cells = [[__r(rand, 0, r - 1), __r(rand, 0, c - 1)]]; g[cells[0][0]][cells[0][1]] = 1; var tries = 0; while (cells.length < k && tries++ < 400) { var b = __pick(rand, cells), d = __pick(rand, [[1, 0], [-1, 0], [0, 1], [0, -1]]), y = b[0] + d[0], x = b[1] + d[1]; if (y < 0 || x < 0 || y >= r || x >= c || g[y][x]) continue; g[y][x] = 1; cells.push([y, x]); } return g; }
`;
export const ggen = (body: string) => gen(`${GRAPH_PRELUDE}\n${body}`);

const DIRS = "[[1, 0], [-1, 0], [0, 1], [0, -1]]";
const GRID = "number[][]";

/** Judges for seeded LeetCode problems that the Graphs Ladder points at: traversal, grids and BFS. */
const DEFS: ProblemDef[] = [
  {
    slug: "find-if-path-exists-in-graph",
    title: "Find if Path Exists in Graph",
    difficulty: "Easy",
    pattern: "Graphs (BFS/DFS)",
    fn: "validPath",
    params: [["n", "number"], ["edges", "number[][]"], ["source", "number"], ["destination", "number"]],
    returns: "boolean",
    hints: [
      "Build an adjacency list from the undirected edges, then ask whether source can reach destination.",
      "BFS or DFS from source with a visited array; stop as soon as you reach destination. (Union-find also works: same root means connected.)",
      "adj = adjacency list from edges (both directions)\nseen = {source}; queue = [source]\nwhile queue not empty:\n  u = pop front\n  if u == destination: return true\n  for v in adj[u]:\n    if v not in seen: add v to seen; push v\nreturn false",
    ],
    reference: `function validPath(n, edges, source, destination) { const adj = Array.from({ length: n }, () => []); for (const [a, b] of edges) { adj[a].push(b); adj[b].push(a); } const seen = new Array(n).fill(false); seen[source] = true; const q = [source]; while (q.length) { const u = q.shift(); if (u === destination) return true; for (const v of adj[u]) if (!seen[v]) { seen[v] = true; q.push(v); } } return false; }`,
    brute: `function validPath(n, edges, source, destination) { const p = Array.from({ length: n }, (_, i) => i); const f = (x) => (p[x] === x ? x : (p[x] = f(p[x]))); for (const [a, b] of edges) p[f(a)] = f(b); return f(source) === f(destination); }`,
    fuzz: ggen(`const n = __r(rand, 1, 10); return [n, __edges(rand, n, __r(rand, 0, n)), __r(rand, 0, n - 1), __r(rand, 0, n - 1)];`),
    examples: [[3, [[0, 1], [1, 2], [2, 0]], 0, 2], [6, [[0, 1], [0, 2], [3, 5], [5, 4], [4, 3]], 0, 5]],
    edges: [
      ["single", [1, [], 0, 0], "Source and destination are the same node."],
      ["no-answer", [4, [[0, 1], [2, 3]], 0, 3]],
      ["boundary", [2, [[0, 1]], 1, 0], "Edges work in both directions."],
    ],
  },
  {
    slug: "find-the-town-judge",
    title: "Find the Town Judge",
    difficulty: "Easy",
    pattern: "Graphs (BFS/DFS)",
    fn: "findJudge",
    params: [["n", "number"], ["trust", "number[][]"]],
    returns: "number",
    hints: [
      "The judge is trusted by everyone else (n - 1 people) and trusts nobody.",
      "Keep a score per person: +1 when trusted, -1 when trusting. The judge is the one whose score is exactly n - 1.",
      "score = array of n + 1 zeros\nfor (a, b) in trust:\n  score[a] -= 1\n  score[b] += 1\nfor p in 1 .. n:\n  if score[p] == n - 1: return p\nreturn -1",
    ],
    reference: `function findJudge(n, trust) { const s = new Array(n + 1).fill(0); for (const [a, b] of trust) { s[a]--; s[b]++; } for (let p = 1; p <= n; p++) if (s[p] === n - 1) return p; return -1; }`,
    brute: `function findJudge(n, trust) { for (let p = 1; p <= n; p++) { if (trust.some(([a]) => a === p)) continue; let ok = true; for (let q = 1; q <= n; q++) if (q !== p && !trust.some(([a, b]) => a === q && b === p)) ok = false; if (ok) return p; } return -1; }`,
    fuzz: ggen(`const n = __r(rand, 1, 7); const seen = {}, t = []; const add = (a, b) => { const k = a + "," + b; if (a !== b && !seen[k]) { seen[k] = 1; t.push([a, b]); } }; if (rand() < 0.5) { const j = __r(rand, 1, n); for (let p = 1; p <= n; p++) if (p !== j && rand() < 0.9) add(p, j); for (let i = 0; i < n; i++) { const a = __r(rand, 1, n); if (a !== j) add(a, __r(rand, 1, n)); } } else for (let i = 0; i < __r(rand, 0, 2 * n); i++) add(__r(rand, 1, n), __r(rand, 1, n)); return [n, __shuffle(rand, t)];`),
    examples: [[2, [[1, 2]]], [3, [[1, 3], [2, 3]]], [3, [[1, 3], [2, 3], [3, 1]]]],
    edges: [
      ["single", [1, []], "Alone in town: person 1 is the judge."],
      ["no-answer", [3, [[1, 2], [2, 3]]]],
      ["boundary", [4, [[1, 3], [1, 4], [2, 3], [2, 4], [4, 3]]]],
    ],
  },
  {
    slug: "flood-fill",
    title: "Flood Fill",
    difficulty: "Easy",
    pattern: "Graphs (BFS/DFS)",
    fn: "floodFill",
    params: [["image", GRID], ["sr", "number"], ["sc", "number"], ["color", "number"]],
    returns: GRID,
    hints: [
      "Repaint the start pixel and every pixel of the same original colour connected to it up, down, left or right.",
      "DFS from (sr, sc) repainting as you go. If the new colour equals the old one, return immediately, or the search never ends.",
      "old = image[sr][sc]\nif old == color: return image\nfill(r, c):\n  if (r, c) is outside or image[r][c] != old: return\n  image[r][c] = color\n  fill each of the 4 neighbours\nfill(sr, sc)\nreturn image",
    ],
    reference: `function floodFill(image, sr, sc, color) { const old = image[sr][sc]; if (old === color) return image; const fill = (r, c) => { if (r < 0 || c < 0 || r >= image.length || c >= image[0].length || image[r][c] !== old) return; image[r][c] = color; fill(r + 1, c); fill(r - 1, c); fill(r, c + 1); fill(r, c - 1); }; fill(sr, sc); return image; }`,
    brute: `function floodFill(image, sr, sc, color) { const g = image.map((r) => r.slice()), old = g[sr][sc], seen = new Set([sr + "," + sc]), q = [[sr, sc]]; while (q.length) { const [r, c] = q.shift(); for (const [dr, dc] of ${DIRS}) { const y = r + dr, x = c + dc; if (y >= 0 && x >= 0 && y < g.length && x < g[0].length && g[y][x] === old && !seen.has(y + "," + x)) { seen.add(y + "," + x); q.push([y, x]); } } } for (const k of seen) { const [r, c] = k.split(",").map(Number); g[r][c] = color; } return g; }`,
    fuzz: ggen(`const r = __r(rand, 1, 6), c = __r(rand, 1, 6); return [Array.from({ length: r }, () => __arr(rand, c, 0, 2)), __r(rand, 0, r - 1), __r(rand, 0, c - 1), __r(rand, 0, 2)];`),
    examples: [[[[1, 1, 1], [1, 1, 0], [1, 0, 1]], 1, 1, 2], [[[0, 0, 0], [0, 0, 0]], 0, 0, 0]],
    edges: [
      ["single", [[[5]], 0, 0, 3]],
      ["all-equal", [[[1, 1], [1, 1]], 0, 0, 1], "The new colour equals the old one: nothing changes."],
      ["boundary", [[[0, 1], [1, 0]], 0, 0, 7], "Diagonal pixels are not connected."],
    ],
  },
  {
    slug: "island-perimeter",
    title: "Island Perimeter",
    difficulty: "Easy",
    pattern: "Graphs (BFS/DFS)",
    fn: "islandPerimeter",
    params: [["grid", GRID]],
    returns: "number",
    hints: [
      "Each land cell has 4 sides. A side counts toward the perimeter unless another land cell is on the other side.",
      "Count land cells and shared edges (look only right and down so each pair is counted once). Perimeter = 4 * land - 2 * shared.",
      "land = 0; shared = 0\nfor each cell (r, c) with grid[r][c] == 1:\n  land += 1\n  if the cell below is land: shared += 1\n  if the cell to the right is land: shared += 1\nreturn 4 * land - 2 * shared",
    ],
    reference: `function islandPerimeter(grid) { let land = 0, shared = 0; for (let r = 0; r < grid.length; r++) for (let c = 0; c < grid[0].length; c++) if (grid[r][c]) { land++; if (r + 1 < grid.length && grid[r + 1][c]) shared++; if (c + 1 < grid[0].length && grid[r][c + 1]) shared++; } return 4 * land - 2 * shared; }`,
    brute: `function islandPerimeter(grid) { let p = 0; for (let r = 0; r < grid.length; r++) for (let c = 0; c < grid[0].length; c++) if (grid[r][c]) for (const [dr, dc] of ${DIRS}) { const y = r + dr, x = c + dc; if (y < 0 || x < 0 || y >= grid.length || x >= grid[0].length || !grid[y][x]) p++; } return p; }`,
    fuzz: ggen(`const r = __r(rand, 1, 6), c = __r(rand, 1, 6); return [__island(rand, r, c, __r(rand, 1, r * c))];`),
    examples: [[[[0, 1, 0, 0], [1, 1, 1, 0], [0, 1, 0, 0], [1, 1, 0, 0]]], [[[1]]], [[[1, 0]]]],
    edges: [
      ["all-equal", [[[1, 1], [1, 1]]], "A solid block."],
      ["single", [[[0, 0, 0], [0, 1, 0], [0, 0, 0]]]],
      ["boundary", [[[1, 1, 1, 1]]], "A strip touching the grid edges."],
    ],
  },
  {
    slug: "number-of-provinces",
    title: "Number of Provinces",
    difficulty: "Medium",
    pattern: "Graphs (BFS/DFS)",
    fn: "findCircleNum",
    params: [["isConnected", GRID]],
    returns: "number",
    hints: [
      "A province is a connected component in a graph given as an adjacency matrix.",
      "Loop over cities; each unvisited city starts a new DFS that marks its whole component. Count how many DFS starts you made.",
      "seen = array of n false\ncount = 0\nfor i in 0 .. n - 1:\n  if not seen[i]:\n    count += 1\n    dfs(i): seen[i] = true; for j with isConnected[i][j] == 1 and not seen[j]: dfs(j)\nreturn count",
    ],
    reference: `function findCircleNum(isConnected) { const n = isConnected.length, seen = new Array(n).fill(false); let count = 0; const dfs = (i) => { seen[i] = true; for (let j = 0; j < n; j++) if (isConnected[i][j] && !seen[j]) dfs(j); }; for (let i = 0; i < n; i++) if (!seen[i]) { count++; dfs(i); } return count; }`,
    brute: `function findCircleNum(isConnected) { const n = isConnected.length, p = Array.from({ length: n }, (_, i) => i); const f = (x) => (p[x] === x ? x : (p[x] = f(p[x]))); for (let i = 0; i < n; i++) for (let j = 0; j < n; j++) if (isConnected[i][j]) p[f(i)] = f(j); return new Set(p.map((_, i) => f(i))).size; }`,
    fuzz: ggen(`const n = __r(rand, 1, 8), q = rand() * 0.4, m = Array.from({ length: n }, () => new Array(n).fill(0)); for (let i = 0; i < n; i++) { m[i][i] = 1; for (let j = i + 1; j < n; j++) if (rand() < q) m[i][j] = m[j][i] = 1; } return [m];`),
    examples: [[[[1, 1, 0], [1, 1, 0], [0, 0, 1]]], [[[1, 0, 0], [0, 1, 0], [0, 0, 1]]]],
    edges: [
      ["single", [[[1]]]],
      ["all-equal", [[[1, 1, 1], [1, 1, 1], [1, 1, 1]]]],
      ["boundary", [[[1, 0, 0, 1], [0, 1, 1, 0], [0, 1, 1, 1], [1, 0, 1, 1]]], "Connected only through a chain."],
    ],
  },
  {
    slug: "keys-and-rooms",
    title: "Keys and Rooms",
    difficulty: "Medium",
    pattern: "Graphs (BFS/DFS)",
    fn: "canVisitAllRooms",
    params: [["rooms", GRID]],
    returns: "boolean",
    hints: [
      "Room 0 is open. A key is an edge from the room it lies in to the room it opens. Can you reach every room?",
      "DFS (or BFS) from room 0, collecting keys; at the end, check that every room was visited.",
      "seen = {0}; stack = [0]\nwhile stack not empty:\n  room = pop\n  for key in rooms[room]:\n    if key not in seen: add key to seen; push key\nreturn size of seen == number of rooms",
    ],
    reference: `function canVisitAllRooms(rooms) { const seen = new Set([0]), st = [0]; while (st.length) { for (const k of rooms[st.pop()]) if (!seen.has(k)) { seen.add(k); st.push(k); } } return seen.size === rooms.length; }`,
    brute: `function canVisitAllRooms(rooms) { const open = new Array(rooms.length).fill(false); open[0] = true; let changed = true; while (changed) { changed = false; for (let i = 0; i < rooms.length; i++) if (open[i]) for (const k of rooms[i]) if (!open[k]) { open[k] = true; changed = true; } } return open.every(Boolean); }`,
    fuzz: ggen(`const n = __r(rand, 1, 8); return [Array.from({ length: n }, () => __shuffle(rand, Array.from({ length: n }, (_, i) => i)).slice(0, __r(rand, 0, 2)))];`),
    examples: [[[[1], [2], [3], []]], [[[1, 3], [3, 0, 1], [2], [0]]]],
    edges: [
      ["single", [[[]]]],
      ["no-answer", [[[], [0]]], "Room 0 has no keys."],
      ["cycle", [[[1], [2], [0]]]],
    ],
  },
  {
    slug: "number-of-islands",
    title: "Number of Islands",
    difficulty: "Medium",
    pattern: "Graphs (BFS/DFS)",
    fn: "numIslands",
    params: [["grid", "string[][]"]],
    returns: "number",
    hints: [
      "An island is a group of '1' cells connected up, down, left or right. Count the groups.",
      "Scan the grid; on every '1' you find, count one island and sink the whole island (turn it into '0') with DFS or BFS so it is not counted again.",
      "count = 0\nfor each cell (r, c):\n  if grid[r][c] == '1':\n    count += 1\n    sink(r, c)\nsink(r, c):\n  if (r, c) is outside or grid[r][c] != '1': return\n  grid[r][c] = '0'\n  sink each of the 4 neighbours\nreturn count",
    ],
    reference: `function numIslands(grid) { let count = 0; const sink = (r, c) => { if (r < 0 || c < 0 || r >= grid.length || c >= grid[0].length || grid[r][c] !== "1") return; grid[r][c] = "0"; sink(r + 1, c); sink(r - 1, c); sink(r, c + 1); sink(r, c - 1); }; for (let r = 0; r < grid.length; r++) for (let c = 0; c < grid[0].length; c++) if (grid[r][c] === "1") { count++; sink(r, c); } return count; }`,
    brute: `function numIslands(grid) { const R = grid.length, C = grid[0].length, p = Array.from({ length: R * C }, (_, i) => i); const f = (x) => (p[x] === x ? x : (p[x] = f(p[x]))); for (let r = 0; r < R; r++) for (let c = 0; c < C; c++) if (grid[r][c] === "1") { if (r + 1 < R && grid[r + 1][c] === "1") p[f(r * C + c)] = f((r + 1) * C + c); if (c + 1 < C && grid[r][c + 1] === "1") p[f(r * C + c)] = f(r * C + c + 1); } const roots = new Set(); for (let r = 0; r < R; r++) for (let c = 0; c < C; c++) if (grid[r][c] === "1") roots.add(f(r * C + c)); return roots.size; }`,
    fuzz: ggen(`return [__grid(rand, __r(rand, 1, 7), __r(rand, 1, 7), 0.45).map((row) => row.map(String))];`),
    examples: [[[["1", "1", "1", "1", "0"], ["1", "1", "0", "1", "0"], ["1", "1", "0", "0", "0"], ["0", "0", "0", "0", "0"]]], [[["1", "1", "0", "0", "0"], ["1", "1", "0", "0", "0"], ["0", "0", "1", "0", "0"], ["0", "0", "0", "1", "1"]]]],
    edges: [
      ["single", [[["1"]]]],
      ["zeros", [[["0", "0"], ["0", "0"]]]],
      ["boundary", [[["1", "0", "1"], ["0", "1", "0"], ["1", "0", "1"]]], "Diagonal neighbours are separate islands."],
    ],
  },
  {
    slug: "max-area-of-island",
    title: "Max Area of Island",
    difficulty: "Medium",
    pattern: "Graphs (BFS/DFS)",
    fn: "maxAreaOfIsland",
    params: [["grid", GRID]],
    returns: "number",
    hints: [
      "Same as counting islands, but measure each island's size and keep the largest.",
      "DFS that sinks an island returns how many cells it sank: 1 + the sizes from its 4 neighbours.",
      "best = 0\nfor each cell (r, c) with grid[r][c] == 1:\n  best = max(best, area(r, c))\narea(r, c):\n  if (r, c) is outside or grid[r][c] != 1: return 0\n  grid[r][c] = 0\n  return 1 + area of the 4 neighbours\nreturn best",
    ],
    reference: `function maxAreaOfIsland(grid) { const area = (r, c) => { if (r < 0 || c < 0 || r >= grid.length || c >= grid[0].length || grid[r][c] !== 1) return 0; grid[r][c] = 0; return 1 + area(r + 1, c) + area(r - 1, c) + area(r, c + 1) + area(r, c - 1); }; let best = 0; for (let r = 0; r < grid.length; r++) for (let c = 0; c < grid[0].length; c++) best = Math.max(best, area(r, c)); return best; }`,
    brute: `function maxAreaOfIsland(grid) { const R = grid.length, C = grid[0].length, seen = new Set(); let best = 0; for (let r = 0; r < R; r++) for (let c = 0; c < C; c++) { if (!grid[r][c] || seen.has(r * C + c)) continue; let size = 0; const q = [[r, c]]; seen.add(r * C + c); while (q.length) { const [y, x] = q.shift(); size++; for (const [dy, dx] of ${DIRS}) { const ny = y + dy, nx = x + dx; if (ny >= 0 && nx >= 0 && ny < R && nx < C && grid[ny][nx] && !seen.has(ny * C + nx)) { seen.add(ny * C + nx); q.push([ny, nx]); } } } best = Math.max(best, size); } return best; }`,
    fuzz: ggen(`return [__grid(rand, __r(rand, 1, 7), __r(rand, 1, 7), 0.5)];`),
    examples: [[[[0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0], [0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0], [0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0], [0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0], [0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0]]], [[[0, 0, 0, 0, 0, 0, 0, 0]]]],
    edges: [
      ["single", [[[1]]]],
      ["all-equal", [[[1, 1], [1, 1]]]],
      ["boundary", [[[1, 0], [0, 1]]], "Diagonal cells are separate islands."],
    ],
  },
  {
    slug: "surrounded-regions",
    title: "Surrounded Regions",
    difficulty: "Medium",
    pattern: "Graphs (BFS/DFS)",
    fn: "solve",
    params: [["board", "string[][]"]],
    returns: "void",
    argTypes: ["value"],
    returnKind: "arg0",
    hints: [
      "An 'O' survives only if it is connected to an 'O' on the border. Finding the survivors is easier than finding the captured ones.",
      "DFS from every border 'O', marking it safe (say '#'). Then flip every remaining 'O' to 'X' and every '#' back to 'O'.",
      "for each border cell with board[r][c] == 'O': mark(r, c)\nmark(r, c):\n  if (r, c) is outside or board[r][c] != 'O': return\n  board[r][c] = '#'\n  mark each of the 4 neighbours\nfor each cell:\n  if board[r][c] == 'O': board[r][c] = 'X'\n  else if board[r][c] == '#': board[r][c] = 'O'",
    ],
    reference: `function solve(board) { const R = board.length, C = board[0].length; const mark = (r, c) => { if (r < 0 || c < 0 || r >= R || c >= C || board[r][c] !== "O") return; board[r][c] = "#"; mark(r + 1, c); mark(r - 1, c); mark(r, c + 1); mark(r, c - 1); }; for (let r = 0; r < R; r++) { mark(r, 0); mark(r, C - 1); } for (let c = 0; c < C; c++) { mark(0, c); mark(R - 1, c); } for (let r = 0; r < R; r++) for (let c = 0; c < C; c++) board[r][c] = board[r][c] === "#" ? "O" : "X"; }`,
    brute: `function solve(board) { const R = board.length, C = board[0].length, seen = new Set(); for (let r = 0; r < R; r++) for (let c = 0; c < C; c++) { if (board[r][c] !== "O" || seen.has(r * C + c)) continue; const region = [[r, c]], q = [[r, c]]; seen.add(r * C + c); let edge = false; while (q.length) { const [y, x] = q.shift(); if (y === 0 || x === 0 || y === R - 1 || x === C - 1) edge = true; for (const [dy, dx] of ${DIRS}) { const ny = y + dy, nx = x + dx; if (ny >= 0 && nx >= 0 && ny < R && nx < C && board[ny][nx] === "O" && !seen.has(ny * C + nx)) { seen.add(ny * C + nx); q.push([ny, nx]); region.push([ny, nx]); } } } if (!edge) for (const [y, x] of region) board[y][x] = "X"; } }`,
    fuzz: ggen(`return [__grid(rand, __r(rand, 1, 7), __r(rand, 1, 7), 0.45).map((row) => row.map((v) => (v ? "O" : "X")))];`),
    examples: [[[["X", "X", "X", "X"], ["X", "O", "O", "X"], ["X", "X", "O", "X"], ["X", "O", "X", "X"]]], [[["X"]]]],
    edges: [
      ["single", [[["O"]]], "A border cell is never captured."],
      ["boundary", [[["X", "O", "X"], ["X", "O", "X"], ["X", "X", "X"]]], "Connected to the top edge: survives."],
      ["all-equal", [[["O", "O", "O"], ["O", "O", "O"], ["O", "O", "O"]]]],
    ],
  },
  {
    slug: "number-of-enclaves",
    title: "Number of Enclaves",
    difficulty: "Medium",
    pattern: "Graphs (BFS/DFS)",
    fn: "numEnclaves",
    params: [["grid", GRID]],
    returns: "number",
    hints: [
      "A land cell is an enclave when you cannot walk off the grid from it. Land connected to the border is the opposite.",
      "Sink every land cell reachable from the border with DFS, then count the land that is left.",
      "for each border cell with grid[r][c] == 1: sink(r, c)\nsink(r, c):\n  if (r, c) is outside or grid[r][c] != 1: return\n  grid[r][c] = 0\n  sink each of the 4 neighbours\nreturn number of cells still equal to 1",
    ],
    reference: `function numEnclaves(grid) { const R = grid.length, C = grid[0].length; const sink = (r, c) => { if (r < 0 || c < 0 || r >= R || c >= C || grid[r][c] !== 1) return; grid[r][c] = 0; sink(r + 1, c); sink(r - 1, c); sink(r, c + 1); sink(r, c - 1); }; for (let r = 0; r < R; r++) { sink(r, 0); sink(r, C - 1); } for (let c = 0; c < C; c++) { sink(0, c); sink(R - 1, c); } return grid.flat().filter((v) => v === 1).length; }`,
    brute: `function numEnclaves(grid) { const R = grid.length, C = grid[0].length, seen = new Set(); let total = 0; for (let r = 0; r < R; r++) for (let c = 0; c < C; c++) { if (!grid[r][c] || seen.has(r * C + c)) continue; let size = 0, edge = false; const q = [[r, c]]; seen.add(r * C + c); while (q.length) { const [y, x] = q.shift(); size++; if (y === 0 || x === 0 || y === R - 1 || x === C - 1) edge = true; for (const [dy, dx] of ${DIRS}) { const ny = y + dy, nx = x + dx; if (ny >= 0 && nx >= 0 && ny < R && nx < C && grid[ny][nx] && !seen.has(ny * C + nx)) { seen.add(ny * C + nx); q.push([ny, nx]); } } } if (!edge) total += size; } return total; }`,
    fuzz: ggen(`return [__grid(rand, __r(rand, 1, 7), __r(rand, 1, 7), 0.5)];`),
    examples: [[[[0, 0, 0, 0], [1, 0, 1, 0], [0, 1, 1, 0], [0, 0, 0, 0]]], [[[0, 1, 1, 0], [0, 0, 1, 0], [0, 0, 1, 0], [0, 0, 0, 0]]]],
    edges: [
      ["single", [[[1]]]],
      ["zeros", [[[0, 0], [0, 0]]]],
      ["boundary", [[[0, 0, 0], [0, 1, 0], [0, 0, 0]]], "One land cell fully inside."],
    ],
  },
  {
    slug: "number-of-closed-islands",
    title: "Number of Closed Islands",
    difficulty: "Medium",
    pattern: "Graphs (BFS/DFS)",
    fn: "closedIsland",
    params: [["grid", GRID]],
    returns: "number",
    hints: [
      "Careful: here 0 is land and 1 is water. A closed island is land surrounded by water on all four sides, so it cannot touch the border.",
      "First flood away every land region touching the border. Then count the remaining land regions, sinking each as you count it.",
      "for each border cell with grid[r][c] == 0: sink(r, c)\nsink(r, c):\n  if (r, c) is outside or grid[r][c] != 0: return\n  grid[r][c] = 1\n  sink each of the 4 neighbours\ncount = 0\nfor each cell with grid[r][c] == 0: count += 1; sink(r, c)\nreturn count",
    ],
    reference: `function closedIsland(grid) { const R = grid.length, C = grid[0].length; const sink = (r, c) => { if (r < 0 || c < 0 || r >= R || c >= C || grid[r][c] !== 0) return; grid[r][c] = 1; sink(r + 1, c); sink(r - 1, c); sink(r, c + 1); sink(r, c - 1); }; for (let r = 0; r < R; r++) { sink(r, 0); sink(r, C - 1); } for (let c = 0; c < C; c++) { sink(0, c); sink(R - 1, c); } let count = 0; for (let r = 0; r < R; r++) for (let c = 0; c < C; c++) if (grid[r][c] === 0) { count++; sink(r, c); } return count; }`,
    brute: `function closedIsland(grid) { const R = grid.length, C = grid[0].length, seen = new Set(); let count = 0; for (let r = 0; r < R; r++) for (let c = 0; c < C; c++) { if (grid[r][c] !== 0 || seen.has(r * C + c)) continue; let edge = false; const q = [[r, c]]; seen.add(r * C + c); while (q.length) { const [y, x] = q.shift(); if (y === 0 || x === 0 || y === R - 1 || x === C - 1) edge = true; for (const [dy, dx] of ${DIRS}) { const ny = y + dy, nx = x + dx; if (ny >= 0 && nx >= 0 && ny < R && nx < C && grid[ny][nx] === 0 && !seen.has(ny * C + nx)) { seen.add(ny * C + nx); q.push([ny, nx]); } } } if (!edge) count++; } return count; }`,
    fuzz: ggen(`return [__grid(rand, __r(rand, 1, 7), __r(rand, 1, 7), 0.55)];`),
    examples: [[[[1, 1, 1, 1, 1, 1, 1, 0], [1, 0, 0, 0, 0, 1, 1, 0], [1, 0, 1, 0, 1, 1, 1, 0], [1, 0, 0, 0, 0, 1, 0, 1], [1, 1, 1, 1, 1, 1, 1, 0]]], [[[0, 0, 1, 0, 0], [0, 1, 0, 1, 0], [0, 1, 1, 1, 0]]]],
    edges: [
      ["single", [[[0]]], "Land on the border is never closed."],
      ["boundary", [[[1, 1, 1], [1, 0, 1], [1, 1, 1]]]],
      ["all-equal", [[[1, 1], [1, 1]]], "All water."],
    ],
  },
  {
    slug: "count-sub-islands",
    title: "Count Sub Islands",
    difficulty: "Medium",
    pattern: "Graphs (BFS/DFS)",
    fn: "countSubIslands",
    params: [["grid1", GRID], ["grid2", GRID]],
    returns: "number",
    hints: [
      "An island of grid2 is a sub-island when every one of its cells is also land in grid1.",
      "DFS each island of grid2, sinking it, and remember whether any of its cells is water in grid1. Do not stop early: the whole island must be sunk.",
      "count = 0\nfor each cell with grid2[r][c] == 1:\n  if walk(r, c): count += 1\nwalk(r, c):\n  if (r, c) is outside or grid2[r][c] != 1: return true\n  grid2[r][c] = 0\n  ok = grid1[r][c] == 1\n  for each of the 4 neighbours: ok = walk(neighbour) and ok\n  return ok\nreturn count",
    ],
    reference: `function countSubIslands(grid1, grid2) { const R = grid2.length, C = grid2[0].length; const walk = (r, c) => { if (r < 0 || c < 0 || r >= R || c >= C || grid2[r][c] !== 1) return true; grid2[r][c] = 0; let ok = grid1[r][c] === 1; for (const [dr, dc] of ${DIRS}) ok = walk(r + dr, c + dc) && ok; return ok; }; let count = 0; for (let r = 0; r < R; r++) for (let c = 0; c < C; c++) if (grid2[r][c] === 1 && walk(r, c)) count++; return count; }`,
    brute: `function countSubIslands(grid1, grid2) { const R = grid2.length, C = grid2[0].length, seen = new Set(); let count = 0; for (let r = 0; r < R; r++) for (let c = 0; c < C; c++) { if (!grid2[r][c] || seen.has(r * C + c)) continue; const cells = [], q = [[r, c]]; seen.add(r * C + c); while (q.length) { const [y, x] = q.shift(); cells.push([y, x]); for (const [dy, dx] of ${DIRS}) { const ny = y + dy, nx = x + dx; if (ny >= 0 && nx >= 0 && ny < R && nx < C && grid2[ny][nx] && !seen.has(ny * C + nx)) { seen.add(ny * C + nx); q.push([ny, nx]); } } } if (cells.every(([y, x]) => grid1[y][x] === 1)) count++; } return count; }`,
    fuzz: ggen(`const r = __r(rand, 1, 6), c = __r(rand, 1, 6), a = __grid(rand, r, c, 0.65); return [a, a.map((row) => row.map((v) => (rand() < 0.85 ? v && (rand() < 0.85 ? 1 : 0) : rand() < 0.5 ? 1 : 0)))];`),
    examples: [[[[1, 1, 1, 0, 0], [0, 1, 1, 1, 1], [0, 0, 0, 0, 0], [1, 0, 0, 0, 0], [1, 1, 0, 1, 1]], [[1, 1, 1, 0, 0], [0, 0, 1, 1, 1], [0, 1, 0, 0, 0], [1, 0, 1, 1, 0], [0, 1, 0, 1, 0]]], [[[1, 0, 1, 0, 1], [1, 1, 1, 1, 1], [0, 0, 0, 0, 0], [1, 1, 1, 1, 1], [1, 0, 1, 0, 1]], [[0, 0, 0, 0, 0], [1, 1, 1, 1, 1], [0, 1, 0, 1, 0], [0, 1, 0, 1, 0], [1, 0, 0, 0, 1]]]],
    edges: [
      ["single", [[[1]], [[1]]]],
      ["no-answer", [[[0]], [[1]]]],
      ["boundary", [[[1, 1, 0]], [[1, 1, 1]]], "One cell of the island is water in grid1."],
    ],
  },
  {
    slug: "pacific-atlantic-water-flow",
    title: "Pacific Atlantic Water Flow",
    difficulty: "Medium",
    pattern: "Graphs (BFS/DFS)",
    fn: "pacificAtlantic",
    params: [["heights", GRID]],
    returns: "number[][]",
    compare: "unordered",
    hints: [
      "Checking every cell's downhill paths is slow. Turn it around: start from each ocean and walk uphill. Any order of cells is accepted.",
      "BFS from all Pacific border cells (top and left) moving to neighbours that are at least as high; same for the Atlantic (bottom and right). Return the cells reached by both.",
      "pac = cells reachable uphill from the top row and left column\natl = cells reachable uphill from the bottom row and right column\nreach(starts):\n  seen = starts; queue = starts\n  while queue not empty:\n    (r, c) = pop front\n    for each neighbour (y, x) inside with heights[y][x] >= heights[r][c] not in seen:\n      add to seen; push\n  return seen\nreturn every cell in both pac and atl",
    ],
    reference: `function pacificAtlantic(heights) { const R = heights.length, C = heights[0].length; const reach = (starts) => { const seen = new Set(starts.map(([r, c]) => r * C + c)), q = starts.slice(); while (q.length) { const [r, c] = q.shift(); for (const [dr, dc] of ${DIRS}) { const y = r + dr, x = c + dc; if (y >= 0 && x >= 0 && y < R && x < C && !seen.has(y * C + x) && heights[y][x] >= heights[r][c]) { seen.add(y * C + x); q.push([y, x]); } } } return seen; }; const p = [], a = []; for (let r = 0; r < R; r++) { p.push([r, 0]); a.push([r, C - 1]); } for (let c = 0; c < C; c++) { p.push([0, c]); a.push([R - 1, c]); } const P = reach(p), A = reach(a), out = []; for (let r = 0; r < R; r++) for (let c = 0; c < C; c++) if (P.has(r * C + c) && A.has(r * C + c)) out.push([r, c]); return out; }`,
    brute: `function pacificAtlantic(heights) { const R = heights.length, C = heights[0].length, out = []; for (let r = 0; r < R; r++) for (let c = 0; c < C; c++) { let pac = false, atl = false; const seen = new Set([r * C + c]), st = [[r, c]]; while (st.length) { const [y, x] = st.pop(); if (y === 0 || x === 0) pac = true; if (y === R - 1 || x === C - 1) atl = true; for (const [dy, dx] of ${DIRS}) { const ny = y + dy, nx = x + dx; if (ny >= 0 && nx >= 0 && ny < R && nx < C && !seen.has(ny * C + nx) && heights[ny][nx] <= heights[y][x]) { seen.add(ny * C + nx); st.push([ny, nx]); } } } if (pac && atl) out.push([r, c]); } return out; }`,
    fuzz: ggen(`const r = __r(rand, 1, 6), c = __r(rand, 1, 6); return [Array.from({ length: r }, () => __arr(rand, c, 0, 5))];`),
    examples: [[[[1, 2, 2, 3, 5], [3, 2, 3, 4, 4], [2, 4, 5, 3, 1], [6, 7, 1, 4, 5], [5, 1, 1, 2, 4]]], [[[1]]]],
    edges: [
      ["all-equal", [[[2, 2], [2, 2]]], "Flat ground: water flows everywhere."],
      ["boundary", [[[1, 2, 3], [8, 9, 4], [7, 6, 5]]]],
      ["single", [[[3, 1, 2]]], "One row touches both oceans."],
    ],
  },
  {
    slug: "rotting-oranges",
    title: "Rotting Oranges",
    difficulty: "Medium",
    pattern: "Graphs (BFS/DFS)",
    fn: "orangesRotting",
    params: [["grid", GRID]],
    returns: "number",
    hints: [
      "Rot spreads from every rotten orange at once, one step per minute. That is BFS starting from many sources together.",
      "Put every rotten orange in the queue first and count the fresh ones. Process the queue level by level; each level is a minute. If fresh oranges remain at the end, return -1.",
      "queue = all cells with 2; fresh = count of 1s; minutes = 0\nwhile queue not empty and fresh > 0:\n  minutes += 1\n  for each cell in the current level:\n    for each neighbour with value 1:\n      set it to 2; fresh -= 1; push it\nreturn minutes if fresh == 0 else -1",
    ],
    reference: `function orangesRotting(grid) { const R = grid.length, C = grid[0].length; let q = [], fresh = 0, minutes = 0; for (let r = 0; r < R; r++) for (let c = 0; c < C; c++) { if (grid[r][c] === 2) q.push([r, c]); else if (grid[r][c] === 1) fresh++; } while (q.length && fresh) { minutes++; const next = []; for (const [r, c] of q) for (const [dr, dc] of ${DIRS}) { const y = r + dr, x = c + dc; if (y >= 0 && x >= 0 && y < R && x < C && grid[y][x] === 1) { grid[y][x] = 2; fresh--; next.push([y, x]); } } q = next; } return fresh ? -1 : minutes; }`,
    brute: `function orangesRotting(grid) { let g = grid.map((r) => r.slice()), t = 0; for (;;) { const n = g.map((r) => r.slice()); let changed = false; for (let r = 0; r < g.length; r++) for (let c = 0; c < g[0].length; c++) if (g[r][c] === 1 && ${DIRS}.some(([dr, dc]) => (g[r + dr] || [])[c + dc] === 2)) { n[r][c] = 2; changed = true; } if (!changed) break; g = n; t++; } return g.some((r) => r.includes(1)) ? -1 : t; }`,
    fuzz: ggen(`const r = __r(rand, 1, 6), c = __r(rand, 1, 6); return [Array.from({ length: r }, () => Array.from({ length: c }, () => { const x = rand(); return x < 0.2 ? 0 : x < 0.35 ? 2 : 1; }))];`),
    examples: [[[[2, 1, 1], [1, 1, 0], [0, 1, 1]]], [[[2, 1, 1], [0, 1, 1], [1, 0, 1]]], [[[0, 2]]]],
    edges: [
      ["zeros", [[[0]]], "No fresh oranges: 0 minutes."],
      ["no-answer", [[[1]]], "A fresh orange with nothing to rot it."],
      ["boundary", [[[2, 1, 1, 1, 1]]], "A long row."],
    ],
  },
  {
    slug: "01-matrix",
    title: "01 Matrix",
    difficulty: "Medium",
    pattern: "Graphs (BFS/DFS)",
    fn: "updateMatrix",
    params: [["mat", GRID]],
    returns: GRID,
    hints: [
      "Running a BFS from every 1 is too slow. Run one BFS from all the 0s at the same time instead.",
      "Distance 0 for every 0 cell, infinity elsewhere; push all 0s, then BFS: a neighbour gets distance + 1 the first time it is reached.",
      "dist = grid of infinity; queue = []\nfor each cell with mat[r][c] == 0: dist[r][c] = 0; push (r, c)\nwhile queue not empty:\n  (r, c) = pop front\n  for each neighbour (y, x) inside:\n    if dist[y][x] > dist[r][c] + 1:\n      dist[y][x] = dist[r][c] + 1; push (y, x)\nreturn dist",
    ],
    reference: `function updateMatrix(mat) { const R = mat.length, C = mat[0].length, d = mat.map((row) => row.map((v) => (v === 0 ? 0 : Infinity))), q = []; for (let r = 0; r < R; r++) for (let c = 0; c < C; c++) if (mat[r][c] === 0) q.push([r, c]); for (let i = 0; i < q.length; i++) { const [r, c] = q[i]; for (const [dr, dc] of ${DIRS}) { const y = r + dr, x = c + dc; if (y >= 0 && x >= 0 && y < R && x < C && d[y][x] > d[r][c] + 1) { d[y][x] = d[r][c] + 1; q.push([y, x]); } } } return d; }`,
    brute: `function updateMatrix(mat) { const zeros = []; mat.forEach((row, r) => row.forEach((v, c) => { if (v === 0) zeros.push([r, c]); })); return mat.map((row, r) => row.map((v, c) => Math.min(...zeros.map(([y, x]) => Math.abs(y - r) + Math.abs(x - c))))); }`,
    fuzz: ggen(`const r = __r(rand, 1, 6), c = __r(rand, 1, 6), g = __grid(rand, r, c, 0.7); g[__r(rand, 0, r - 1)][__r(rand, 0, c - 1)] = 0; return [g];`),
    examples: [[[[0, 0, 0], [0, 1, 0], [0, 0, 0]]], [[[0, 0, 0], [0, 1, 0], [1, 1, 1]]]],
    edges: [
      ["single", [[[0]]]],
      ["zeros", [[[0, 0], [0, 0]]]],
      ["boundary", [[[0, 1, 1, 1, 1]]], "Distances grow along a row."],
    ],
  },
  {
    slug: "as-far-from-land-as-possible",
    title: "As Far from Land as Possible",
    difficulty: "Medium",
    pattern: "Graphs (BFS/DFS)",
    fn: "maxDistance",
    params: [["grid", GRID]],
    returns: "number",
    hints: [
      "You want the water cell whose nearest land is farthest away (Manhattan distance). Return -1 when there is no land or no water.",
      "Multi-source BFS from every land cell at once; the number of BFS levels until all water is reached is the answer.",
      "queue = all land cells\nif queue is empty or every cell is land: return -1\ndist = -1\nwhile queue not empty:\n  dist += 1\n  for each cell in the current level:\n    for each water neighbour: mark it as land; push it\nreturn dist",
    ],
    reference: `function maxDistance(grid) { const n = grid.length; let q = []; for (let r = 0; r < n; r++) for (let c = 0; c < n; c++) if (grid[r][c]) q.push([r, c]); if (!q.length || q.length === n * n) return -1; let d = -1; while (q.length) { d++; const next = []; for (const [r, c] of q) for (const [dr, dc] of ${DIRS}) { const y = r + dr, x = c + dc; if (y >= 0 && x >= 0 && y < n && x < n && !grid[y][x]) { grid[y][x] = 1; next.push([y, x]); } } q = next; } return d; }`,
    brute: `function maxDistance(grid) { const land = [], water = []; grid.forEach((row, r) => row.forEach((v, c) => (v ? land : water).push([r, c]))); if (!land.length || !water.length) return -1; return Math.max(...water.map(([r, c]) => Math.min(...land.map(([y, x]) => Math.abs(y - r) + Math.abs(x - c))))); }`,
    fuzz: ggen(`const n = __r(rand, 1, 6); return [__grid(rand, n, n, rand() * 0.6)];`),
    examples: [[[[1, 0, 1], [0, 0, 0], [1, 0, 1]]], [[[1, 0, 0], [0, 0, 0], [0, 0, 0]]]],
    edges: [
      ["zeros", [[[0, 0], [0, 0]]], "No land at all."],
      ["all-equal", [[[1, 1], [1, 1]]], "No water at all."],
      ["single", [[[1]]]],
    ],
  },
  {
    slug: "shortest-path-in-binary-matrix",
    title: "Shortest Path in Binary Matrix",
    difficulty: "Medium",
    pattern: "Graphs (BFS/DFS)",
    fn: "shortestPathBinaryMatrix",
    params: [["grid", GRID]],
    returns: "number",
    hints: [
      "Every move costs 1 and you may move in 8 directions through 0 cells. Equal edge costs mean BFS finds the shortest path.",
      "If the start or end is blocked, return -1. BFS from (0, 0) storing the path length (cells visited, so the start counts as 1).",
      "if grid[0][0] or grid[n-1][n-1] is 1: return -1\nqueue = [(0, 0, 1)]; mark (0, 0)\nwhile queue not empty:\n  (r, c, d) = pop front\n  if (r, c) is the bottom-right: return d\n  for each of the 8 neighbours (y, x) inside with grid[y][x] == 0 and unmarked:\n    mark it; push (y, x, d + 1)\nreturn -1",
    ],
    reference: `function shortestPathBinaryMatrix(grid) { const n = grid.length; if (grid[0][0] || grid[n - 1][n - 1]) return -1; const seen = new Set([0]), q = [[0, 0, 1]]; for (let i = 0; i < q.length; i++) { const [r, c, d] = q[i]; if (r === n - 1 && c === n - 1) return d; for (let dr = -1; dr <= 1; dr++) for (let dc = -1; dc <= 1; dc++) { const y = r + dr, x = c + dc; if (y >= 0 && x >= 0 && y < n && x < n && !grid[y][x] && !seen.has(y * n + x)) { seen.add(y * n + x); q.push([y, x, d + 1]); } } } return -1; }`,
    brute: `function shortestPathBinaryMatrix(grid) { const n = grid.length; if (grid[0][0] || grid[n - 1][n - 1]) return -1; const d = grid.map((row) => row.map(() => Infinity)); d[0][0] = 1; for (let it = 0; it < n * n; it++) for (let r = 0; r < n; r++) for (let c = 0; c < n; c++) if (!grid[r][c]) for (let dr = -1; dr <= 1; dr++) for (let dc = -1; dc <= 1; dc++) { const y = r + dr, x = c + dc; if (y >= 0 && x >= 0 && y < n && x < n && d[y][x] + 1 < d[r][c]) d[r][c] = d[y][x] + 1; } return d[n - 1][n - 1] === Infinity ? -1 : d[n - 1][n - 1]; }`,
    fuzz: ggen(`const n = __r(rand, 1, 6), g = __grid(rand, n, n, 0.3); if (rand() < 0.8) { g[0][0] = 0; g[n - 1][n - 1] = 0; } return [g];`),
    examples: [[[[0, 1], [1, 0]]], [[[0, 0, 0], [1, 1, 0], [1, 1, 0]]], [[[1, 0, 0], [1, 1, 0], [1, 1, 0]]]],
    edges: [
      ["single", [[[0]]], "Start is the end: path length 1."],
      ["no-answer", [[[0, 1], [1, 1]]], "The end is blocked."],
      ["boundary", [[[0, 0, 0], [0, 1, 0], [0, 0, 0]]], "Go around the blocked centre."],
    ],
  },
  {
    slug: "open-the-lock",
    title: "Open the Lock",
    difficulty: "Medium",
    pattern: "Graphs (BFS/DFS)",
    fn: "openLock",
    params: [["deadends", "string[]"], ["target", "string"]],
    returns: "number",
    hints: [
      "Each of the 10,000 lock states is a node, and one wheel turn (up or down, with 9 wrapping to 0) is an edge. Deadends are removed nodes.",
      "BFS from '0000' over the 8 neighbours of each state, skipping deadends and visited states. If '0000' is itself a deadend, return -1.",
      "dead = set of deadends\nif '0000' in dead: return -1\nqueue = [('0000', 0)]; seen = {'0000'}\nwhile queue not empty:\n  (s, d) = pop front\n  if s == target: return d\n  for each wheel i and step in (+1, -1):\n    t = s with digit i turned by step (mod 10)\n    if t not in dead and t not in seen: add t; push (t, d + 1)\nreturn -1",
    ],
    reference: `function openLock(deadends, target) { const dead = new Set(deadends); if (dead.has("0000")) return -1; const seen = new Set(["0000"]), q = [["0000", 0]]; for (let i = 0; i < q.length; i++) { const [s, d] = q[i]; if (s === target) return d; for (let w = 0; w < 4; w++) for (const step of [1, 9]) { const t = s.slice(0, w) + ((+s[w] + step) % 10) + s.slice(w + 1); if (!dead.has(t) && !seen.has(t)) { seen.add(t); q.push([t, d + 1]); } } } return -1; }`,
    brute: `function openLock(deadends, target) { const dist = new Int32Array(10000).fill(-1), blocked = new Uint8Array(10000); for (const d of deadends) blocked[+d] = 1; if (blocked[0]) return -1; dist[0] = 0; const q = [0]; for (let i = 0; i < q.length; i++) { const s = q[i]; for (let p = 1; p < 10000; p *= 10) { const dig = Math.floor(s / p) % 10; for (const nd of [(dig + 1) % 10, (dig + 9) % 10]) { const t = s + (nd - dig) * p; if (!blocked[t] && dist[t] < 0) { dist[t] = dist[s] + 1; q.push(t); } } } } return dist[+target]; }`,
    fuzz: gen(`const code = () => String(__r(rand, 0, 9999)).padStart(4, "0"); const near = () => __str(rand, 4, "01239"); const dead = Array.from({ length: __r(rand, 0, 8) }, () => (rand() < 0.7 ? near() : code())).filter((d, i, a) => a.indexOf(d) === i && (d !== "0000" || rand() < 0.1)); let t = rand() < 0.6 ? near() : code(); while (dead.includes(t)) t = code(); return [dead, t];`),
    examples: [[["0201", "0101", "0102", "1212", "2002"], "0202"], [["8888"], "0009"], [["8887", "8889", "8878", "8898", "8788", "8988", "7888", "9888"], "8888"]],
    edges: [
      ["empty", [[], "0000"], "Already open."],
      ["no-answer", [["0000"], "8888"], "The start itself is a deadend."],
      ["boundary", [[], "5555"], "The farthest state: 5 turns on every wheel."],
    ],
  },
  {
    slug: "shortest-bridge",
    title: "Shortest Bridge",
    difficulty: "Medium",
    pattern: "Graphs (BFS/DFS)",
    fn: "shortestBridge",
    params: [["grid", GRID]],
    returns: "number",
    hints: [
      "There are exactly two islands. Find one of them, then grow it outward one ring at a time until it touches the other.",
      "DFS to mark the first island and put all its cells in a queue; then BFS through water, level by level. The level at which you first hit land of the other island is the number of 0s to flip.",
      "find any land cell; DFS from it marking the whole island as 2 and queueing its cells\nsteps = 0\nwhile queue not empty:\n  for each cell in the current level:\n    for each neighbour (y, x) inside:\n      if grid[y][x] == 1: return steps\n      if grid[y][x] == 0: grid[y][x] = 2; push (y, x)\n  steps += 1",
    ],
    reference: `function shortestBridge(grid) { const n = grid.length; let q = []; const mark = (r, c) => { if (r < 0 || c < 0 || r >= n || c >= n || grid[r][c] !== 1) return; grid[r][c] = 2; q.push([r, c]); for (const [dr, dc] of ${DIRS}) mark(r + dr, c + dc); }; outer: for (let r = 0; r < n; r++) for (let c = 0; c < n; c++) if (grid[r][c] === 1) { mark(r, c); break outer; } for (let steps = 0; q.length; steps++) { const next = []; for (const [r, c] of q) for (const [dr, dc] of ${DIRS}) { const y = r + dr, x = c + dc; if (y < 0 || x < 0 || y >= n || x >= n) continue; if (grid[y][x] === 1) return steps; if (grid[y][x] === 0) { grid[y][x] = 2; next.push([y, x]); } } q = next; } return -1; }`,
    brute: `function shortestBridge(grid) { const n = grid.length, seen = new Set(), islands = []; for (let r = 0; r < n; r++) for (let c = 0; c < n; c++) { if (!grid[r][c] || seen.has(r * n + c)) continue; const cells = [], st = [[r, c]]; seen.add(r * n + c); while (st.length) { const [y, x] = st.pop(); cells.push([y, x]); for (const [dy, dx] of ${DIRS}) { const ny = y + dy, nx = x + dx; if (ny >= 0 && nx >= 0 && ny < n && nx < n && grid[ny][nx] && !seen.has(ny * n + nx)) { seen.add(ny * n + nx); st.push([ny, nx]); } } } islands.push(cells); } let best = Infinity; for (const [a, b] of islands[0]) for (const [c, d] of islands[1]) best = Math.min(best, Math.abs(a - c) + Math.abs(b - d) - 1); return best; }`,
    fuzz: ggen(`for (;;) { const n = __r(rand, 2, 6), a = __island(rand, n, n, __r(rand, 1, n)); const cells = []; for (let r = 0; r < n; r++) for (let c = 0; c < n; c++) { const near = a[r][c] || ${DIRS}.some(([dr, dc]) => (a[r + dr] || [])[c + dc] === 1); if (!near) cells.push([r, c]); } if (!cells.length) continue; const g = a.map((row) => row.slice()), start = __pick(rand, cells), grown = [start]; g[start[0]][start[1]] = 1; const ok = (y, x) => y >= 0 && x >= 0 && y < n && x < n && !g[y][x] && !a[y][x] && !${DIRS}.some(([dr, dc]) => (a[y + dr] || [])[x + dc] === 1); for (let i = 0; i < n; i++) { const b = __pick(rand, grown), d = __pick(rand, ${DIRS}), y = b[0] + d[0], x = b[1] + d[1]; if (ok(y, x)) { g[y][x] = 1; grown.push([y, x]); } } return [g]; }`),
    examples: [[[[0, 1], [1, 0]]], [[[0, 1, 0], [0, 0, 0], [0, 0, 1]]], [[[1, 1, 1, 1, 1], [1, 0, 0, 0, 1], [1, 0, 1, 0, 1], [1, 0, 0, 0, 1], [1, 1, 1, 1, 1]]]],
    edges: [
      ["two", [[[1, 0, 1], [0, 0, 0], [0, 0, 0]]], "Two single cells with one gap."],
      ["boundary", [[[1, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 1]]], "Opposite corners."],
      ["min-size", [[[1, 0], [0, 1]]]],
    ],
  },
  {
    slug: "word-ladder",
    title: "Word Ladder",
    difficulty: "Hard",
    pattern: "Graphs (BFS/DFS)",
    fn: "ladderLength",
    params: [["beginWord", "string"], ["endWord", "string"], ["wordList", "string[]"]],
    returns: "number",
    hints: [
      "Words are nodes; two words are joined when they differ in exactly one letter. You want the shortest path, counted in words, or 0 if there is none.",
      "BFS from beginWord. To find neighbours fast, try changing each position to each letter a..z and look the result up in a set of unused words.",
      "words = set of wordList\nif endWord not in words: return 0\nqueue = [(beginWord, 1)]\nwhile queue not empty:\n  (w, d) = pop front\n  if w == endWord: return d\n  for each position i and letter ch:\n    t = w with position i set to ch\n    if t in words: remove t from words; push (t, d + 1)\nreturn 0",
    ],
    reference: `function ladderLength(beginWord, endWord, wordList) { const words = new Set(wordList); if (!words.has(endWord)) return 0; const q = [[beginWord, 1]]; for (let i = 0; i < q.length; i++) { const [w, d] = q[i]; if (w === endWord) return d; for (let p = 0; p < w.length; p++) for (let ch = 97; ch < 123; ch++) { const t = w.slice(0, p) + String.fromCharCode(ch) + w.slice(p + 1); if (words.has(t)) { words.delete(t); q.push([t, d + 1]); } } } return 0; }`,
    brute: `function ladderLength(beginWord, endWord, wordList) { const nodes = [beginWord, ...wordList.filter((w) => w !== beginWord)], diff1 = (a, b) => { let d = 0; for (let i = 0; i < a.length; i++) if (a[i] !== b[i]) d++; return d === 1; }; const dist = new Array(nodes.length).fill(0); dist[0] = 1; const q = [0]; for (let i = 0; i < q.length; i++) { const u = q[i]; if (nodes[u] === endWord && wordList.includes(endWord)) return dist[u]; for (let v = 0; v < nodes.length; v++) if (!dist[v] && diff1(nodes[u], nodes[v])) { dist[v] = dist[u] + 1; q.push(v); } } return 0; }`,
    fuzz: gen(`const L = __r(rand, 2, 3), w = () => __str(rand, L, "abc"); const list = [...new Set(Array.from({ length: __r(rand, 1, 12) }, w))]; let b = w(), e = rand() < 0.8 ? __pick(rand, list) : w(); while (e === b) e = w(); return [b, e, __shuffle(rand, list)];`),
    examples: [["hit", "cog", ["hot", "dot", "dog", "lot", "log", "cog"]], ["hit", "cog", ["hot", "dot", "dog", "lot", "log"]]],
    edges: [
      ["single-char", ["a", "c", ["a", "b", "c"]]],
      ["no-answer", ["ab", "cd", ["ad", "cb"]], "No middle word connects them."],
      ["boundary", ["hot", "dog", ["hot", "dog"]], "beginWord is in the list but too far from endWord."],
    ],
  },
];

export const LADDER_GRAPHS_SEEDED: ProblemSpec[] = DEFS.map((d) => define(d).spec);
