import { UNIQUE } from "../../dsa-extras/a2z-trees";
import { define, type ProblemDef } from "../../dsa-extras/define";
import { treeGen } from "../../dsa-extras/gen";
import type { ProblemSpec } from "../types";

export const ANY_TREE = treeGen(`return [__levelTree(rand, __r(rand, 0, 12), 1, 9)];`);
export const SOME_TREE = treeGen(`return [__levelTree(rand, __r(rand, 1, 12), 1, 9)];`);
/** Distinct values with two of them picked as p and q (LeetCode's node arguments). */
export const TREE_PQ = treeGen(`${UNIQUE} const t = __uniq(rand, __r(rand, 2, 12)); const v = __shuffle(rand, t.filter((x) => x !== null)); return [t, v[0], v[1]];`);
const TRAVERSALS = (order: "pre" | "post") =>
  treeGen(`${UNIQUE} const t = __uniq(rand, __r(rand, 1, 10)); const pre = [], ino = [], post = []; const walk = (n) => { if (!n) return; pre.push(n.val); walk(n.left); ino.push(n.val); walk(n.right); post.push(n.val); }; walk(__treeFromLevelOrder(t)); return ${order === "pre" ? "[pre, ino]" : "[ino, post]"};`);

const T = "TreeNode | null";
const traversal = (slug: string, title: string, fn: string, order: "in" | "pre" | "post", examples: unknown[][], skewed: unknown[]): ProblemDef => {
  const visit = order === "pre" ? "out.push(n.val); go(n.left); go(n.right);" : order === "in" ? "go(n.left); out.push(n.val); go(n.right);" : "go(n.left); go(n.right); out.push(n.val);";
  const iterative =
    order === "pre"
      ? `function ${fn}(root) { const out = [], st = root ? [root] : []; while (st.length) { const n = st.pop(); out.push(n.val); if (n.right) st.push(n.right); if (n.left) st.push(n.left); } return out; }`
      : order === "in"
        ? `function ${fn}(root) { const out = [], st = []; let cur = root; while (cur || st.length) { while (cur) { st.push(cur); cur = cur.left; } cur = st.pop(); out.push(cur.val); cur = cur.right; } return out; }`
        : `function ${fn}(root) { const out = [], st = root ? [root] : []; while (st.length) { const n = st.pop(); out.push(n.val); if (n.left) st.push(n.left); if (n.right) st.push(n.right); } return out.reverse(); }`;
  const name = order === "pre" ? "preorder (node, left, right)" : order === "in" ? "inorder (left, node, right)" : "postorder (left, right, node)";
  return {
    slug,
    title,
    difficulty: "Easy",
    pattern: "Trees",
    fn,
    params: [["root", T]],
    returns: "number[]",
    argTypes: ["TreeNode"],
    hints: [
      `The ${name} order is a three-line recursion. Try writing it, then try it without recursion.`,
      order === "pre"
        ? "Iteratively: pop a node from a stack, record it, push its right child and then its left child so the left comes out first."
        : order === "in"
          ? "Iteratively: walk left pushing every node; pop one, record it, then move to its right child and repeat."
          : "Iteratively: run a node-right-left preorder with a stack and reverse the result.",
      order === "pre"
        ? "stack = [root] if root\nwhile stack not empty:\n  node = pop\n  out.append(node.val)\n  push node.right if present\n  push node.left if present\nreturn out"
        : order === "in"
          ? "stack = [], cur = root\nwhile cur or stack not empty:\n  while cur: push cur; cur = cur.left\n  cur = pop\n  out.append(cur.val)\n  cur = cur.right\nreturn out"
          : "stack = [root] if root\nwhile stack not empty:\n  node = pop\n  out.append(node.val)\n  push node.left if present\n  push node.right if present\nreturn reversed(out)",
    ],
    reference: iterative,
    brute: `function ${fn}(root) { const out = []; const go = (n) => { if (!n) return; ${visit} }; go(root); return out; }`,
    fuzz: ANY_TREE,
    examples,
    edges: [
      ["empty", [[]]],
      ["single", [[7]]],
      ["skewed", [skewed], "Every node has only a left child."],
    ],
  };
};

/** Judges for seeded LeetCode problems that the Binary Trees Ladder points at. LeetCode's own signatures. */
const DEFS: ProblemDef[] = [
  traversal("binary-tree-inorder-traversal", "Binary Tree Inorder Traversal", "inorderTraversal", "in", [[[1, null, 2, 3]], [[1, 2, 3, 4, 5, null, 8, null, null, 6, 7, 9]]], [3, 2, null, 1]),
  traversal("binary-tree-preorder-traversal", "Binary Tree Preorder Traversal", "preorderTraversal", "pre", [[[1, null, 2, 3]], [[1, 2, 3, 4, 5, null, 8, null, null, 6, 7, 9]]], [3, 2, null, 1]),
  traversal("binary-tree-postorder-traversal", "Binary Tree Postorder Traversal", "postorderTraversal", "post", [[[1, null, 2, 3]], [[1, 2, 3, 4, 5, null, 8, null, null, 6, 7, 9]]], [3, 2, null, 1]),
  {
    slug: "balanced-binary-tree",
    title: "Balanced Binary Tree",
    difficulty: "Easy",
    pattern: "Trees",
    fn: "isBalanced",
    params: [["root", T]],
    returns: "boolean",
    argTypes: ["TreeNode"],
    hints: [
      "A tree is balanced when, at every node, the two subtree heights differ by at most 1.",
      "Computing heights separately at every node is O(n^2). Return the height bottom-up instead, and use -1 to mean 'already unbalanced' so the check stops early.",
      "height(node):\n  if node is empty: return 0\n  l = height(node.left); r = height(node.right)\n  if l == -1 or r == -1 or |l - r| > 1: return -1\n  return 1 + max(l, r)\nreturn height(root) != -1",
    ],
    reference: `function isBalanced(root) { const h = (n) => { if (!n) return 0; const l = h(n.left), r = h(n.right); if (l < 0 || r < 0 || Math.abs(l - r) > 1) return -1; return 1 + Math.max(l, r); }; return h(root) !== -1; }`,
    brute: `function isBalanced(root) { const height = (n) => (n ? 1 + Math.max(height(n.left), height(n.right)) : 0); const ok = (n) => !n || (Math.abs(height(n.left) - height(n.right)) <= 1 && ok(n.left) && ok(n.right)); return ok(root); }`,
    fuzz: ANY_TREE,
    examples: [[[3, 9, 20, null, null, 15, 7]], [[1, 2, 2, 3, 3, null, null, 4, 4]]],
    edges: [
      ["empty", [[]], "An empty tree is balanced."],
      ["skewed", [[1, 2, null, 3]]],
      ["boundary", [[1, 2, 3, 4, null, null, null, 5]], "The root's subtrees differ by exactly 2."],
    ],
  },
  {
    slug: "minimum-depth-of-binary-tree",
    title: "Minimum Depth of Binary Tree",
    difficulty: "Easy",
    pattern: "Trees",
    fn: "minDepth",
    params: [["root", T]],
    returns: "number",
    argTypes: ["TreeNode"],
    hints: [
      "Minimum depth counts nodes down to the nearest leaf. A node with one child is not a leaf, so min(left, right) is wrong there.",
      "BFS level by level and return the depth of the first leaf you meet; or recurse and, when one child is missing, use the other side only.",
      "if root is empty: return 0\nqueue = [(root, 1)]\nwhile queue not empty:\n  (node, d) = dequeue\n  if node has no children: return d\n  enqueue (child, d + 1) for each child",
    ],
    reference: `function minDepth(root) { if (!root) return 0; const q = [[root, 1]]; for (let i = 0; i < q.length; i++) { const [n, d] = q[i]; if (!n.left && !n.right) return d; if (n.left) q.push([n.left, d + 1]); if (n.right) q.push([n.right, d + 1]); } return 0; }`,
    brute: `function minDepth(root) { if (!root) return 0; if (!root.left) return 1 + minDepth(root.right); if (!root.right) return 1 + minDepth(root.left); return 1 + Math.min(minDepth(root.left), minDepth(root.right)); }`,
    fuzz: ANY_TREE,
    examples: [[[3, 9, 20, null, null, 15, 7]], [[2, null, 3, null, 4, null, 5, null, 6]]],
    edges: [
      ["empty", [[]]],
      ["single", [[1]]],
      ["skewed", [[1, 2, null, 3]], "The root has one child, so it is not a leaf."],
    ],
  },
  {
    slug: "subtree-of-another-tree",
    title: "Subtree of Another Tree",
    difficulty: "Easy",
    pattern: "Trees",
    fn: "isSubtree",
    params: [["root", T], ["subRoot", T]],
    returns: "boolean",
    argTypes: ["TreeNode", "TreeNode"],
    hints: [
      "A subtree is a node plus all of its descendants. So the question is: is there a node in root where the two trees are identical?",
      "Write sameTree(a, b), then try it at every node of root.",
      "same(a, b):\n  if both empty: return true\n  if one empty or a.val != b.val: return false\n  return same(a.left, b.left) and same(a.right, b.right)\nisSubtree(node, sub):\n  if node is empty: return false\n  return same(node, sub) or isSubtree(node.left, sub) or isSubtree(node.right, sub)",
    ],
    reference: `function isSubtree(root, subRoot) { const same = (a, b) => (!a || !b ? a === b : a.val === b.val && same(a.left, b.left) && same(a.right, b.right)); const go = (n) => !!n && (same(n, subRoot) || go(n.left) || go(n.right)); return go(root); }`,
    brute: `function isSubtree(root, subRoot) { const ser = (n) => (n ? "(" + n.val + ser(n.left) + ser(n.right) + ")" : "#"); return ser(root).includes(ser(subRoot)); }`,
    fuzz: treeGen(`const t = __levelTree(rand, __r(rand, 1, 10), 1, 3); if (rand() < 0.5) { const all = []; const walk = (n) => { if (n) { all.push(n); walk(n.left); walk(n.right); } }; walk(__treeFromLevelOrder(t)); return [t, __treeToLevelOrder(all[__r(rand, 0, all.length - 1)])]; } return [t, __levelTree(rand, __r(rand, 1, 4), 1, 3)];`),
    examples: [[[3, 4, 5, 1, 2], [4, 1, 2]], [[3, 4, 5, 1, 2, null, null, null, null, 0], [4, 1, 2]]],
    edges: [
      ["single", [[1], [1]]],
      ["duplicates", [[1, 1], [1]], "The match is the leaf, not the root."],
      ["no-answer", [[1, 2, 3], [2, 3]], "Node 2 exists but has no child 3."],
    ],
  },
  {
    slug: "average-of-levels-in-binary-tree",
    title: "Average of Levels in Binary Tree",
    difficulty: "Easy",
    pattern: "Trees",
    fn: "averageOfLevels",
    params: [["root", T]],
    returns: "number[]",
    argTypes: ["TreeNode"],
    hints: [
      "You need the sum and the count of every level.",
      "BFS one level at a time: the queue length at the start of a level is its count. Divide the level sum by it.",
      "queue = [root], out = []\nwhile queue not empty:\n  size = len(queue), total = 0\n  repeat size times:\n    node = dequeue; total = total + node.val\n    enqueue node's children\n  out.append(total / size)\nreturn out",
    ],
    reference: `function averageOfLevels(root) { const out = []; let q = [root]; while (q.length) { let s = 0; const next = []; for (const n of q) { s += n.val; if (n.left) next.push(n.left); if (n.right) next.push(n.right); } out.push(s / q.length); q = next; } return out; }`,
    brute: `function averageOfLevels(root) { const sum = [], cnt = []; const go = (n, d) => { if (!n) return; sum[d] = (sum[d] || 0) + n.val; cnt[d] = (cnt[d] || 0) + 1; go(n.left, d + 1); go(n.right, d + 1); }; go(root, 0); return sum.map((s, i) => s / cnt[i]); }`,
    fuzz: treeGen(`return [__levelTree(rand, __r(rand, 1, 12), -9, 9)];`),
    examples: [[[3, 9, 20, null, null, 15, 7]], [[3, 9, 20, 15, 7]]],
    edges: [
      ["single", [[5]]],
      ["negatives", [[-1, -2, -4]]],
      ["skewed", [[1, 2, null, 3]]],
    ],
  },
  {
    slug: "binary-tree-paths",
    title: "Binary Tree Paths",
    difficulty: "Easy",
    pattern: "Trees",
    fn: "binaryTreePaths",
    params: [["root", T]],
    returns: "string[]",
    argTypes: ["TreeNode"],
    compare: "unordered",
    hints: [
      "Carry the path so far down the recursion; a leaf turns it into an answer. Any order is accepted.",
      "DFS with a path string: at each node append its value; at a leaf push the string; otherwise recurse with path + '->'.",
      "out = []\ndfs(node, path):\n  path = path + str(node.val)\n  if node is a leaf: out.append(path); return\n  if node.left: dfs(node.left, path + \"->\")\n  if node.right: dfs(node.right, path + \"->\")\ndfs(root, \"\")\nreturn out",
    ],
    reference: `function binaryTreePaths(root) { const out = []; const go = (n, p) => { p += n.val; if (!n.left && !n.right) { out.push(p); return; } if (n.left) go(n.left, p + "->"); if (n.right) go(n.right, p + "->"); }; go(root, ""); return out; }`,
    brute: `function binaryTreePaths(root) { const out = [], st = [[root, [root.val]]]; while (st.length) { const [n, vals] = st.pop(); if (!n.left && !n.right) out.push(vals.join("->")); for (const c of [n.left, n.right]) if (c) st.push([c, vals.concat(c.val)]); } return out; }`,
    fuzz: treeGen(`return [__levelTree(rand, __r(rand, 1, 10), -3, 9)];`),
    examples: [[[1, 2, 3, null, 5]], [[1]]],
    edges: [
      ["two", [[1, 2]]],
      ["negatives", [[-1, 2, -3]]],
      ["duplicates", [[1, 1, 1]], "Two different paths that read the same."],
    ],
  },
  {
    slug: "sum-of-left-leaves",
    title: "Sum of Left Leaves",
    difficulty: "Easy",
    pattern: "Trees",
    fn: "sumOfLeftLeaves",
    params: [["root", T]],
    returns: "number",
    argTypes: ["TreeNode"],
    hints: [
      "A left leaf is a leaf that is the left child of its parent. The parent is where you can tell.",
      "Recurse with a flag saying whether the node is a left child; add its value when it is a leaf and the flag is set.",
      "go(node, isLeft):\n  if node is empty: return 0\n  if node is a leaf: return node.val if isLeft else 0\n  return go(node.left, true) + go(node.right, false)\nreturn go(root, false)",
    ],
    reference: `function sumOfLeftLeaves(root) { const go = (n, left) => { if (!n) return 0; if (!n.left && !n.right) return left ? n.val : 0; return go(n.left, true) + go(n.right, false); }; return go(root, false); }`,
    brute: `function sumOfLeftLeaves(root) { let s = 0; const q = root ? [root] : []; for (let i = 0; i < q.length; i++) { const n = q[i]; if (n.left && !n.left.left && !n.left.right) s += n.left.val; if (n.left) q.push(n.left); if (n.right) q.push(n.right); } return s; }`,
    fuzz: SOME_TREE,
    examples: [[[3, 9, 20, null, null, 15, 7]], [[1]]],
    edges: [
      ["two", [[1, 2]]],
      ["boundary", [[1, null, 2]], "A right leaf does not count."],
      ["skewed", [[1, 2, null, 3, null, 4]]],
    ],
  },
  {
    slug: "leaf-similar-trees",
    title: "Leaf-Similar Trees",
    difficulty: "Easy",
    pattern: "Trees",
    fn: "leafSimilar",
    params: [["root1", T], ["root2", T]],
    returns: "boolean",
    argTypes: ["TreeNode", "TreeNode"],
    hints: [
      "Only the leaves, read left to right, matter.",
      "Collect each tree's leaf sequence with a DFS that visits left before right, then compare the two lists.",
      "leaves(node, out):\n  if node is empty: return\n  if node is a leaf: out.append(node.val)\n  leaves(node.left, out); leaves(node.right, out)\nreturn leaves(root1) == leaves(root2)",
    ],
    reference: `function leafSimilar(root1, root2) { const leaves = (n, out) => { if (!n) return out; if (!n.left && !n.right) out.push(n.val); leaves(n.left, out); leaves(n.right, out); return out; }; const a = leaves(root1, []), b = leaves(root2, []); return a.length === b.length && a.every((x, i) => x === b[i]); }`,
    brute: `function leafSimilar(root1, root2) { const seq = (r) => { const out = [], st = [r]; while (st.length) { const n = st.pop(); if (!n) continue; if (!n.left && !n.right) out.push(n.val); st.push(n.right, n.left); } return out.join(","); }; return seq(root1) === seq(root2); }`,
    fuzz: treeGen(`return [__levelTree(rand, __r(rand, 1, 7), 1, 2), __levelTree(rand, __r(rand, 1, 7), 1, 2)];`),
    examples: [[[3, 5, 1, 6, 2, 9, 8, null, null, 7, 4], [3, 5, 1, 6, 7, 4, 2, null, null, null, null, null, null, 9, 8]], [[1, 2, 3], [1, 3, 2]]],
    edges: [
      ["single", [[1], [1]]],
      ["no-answer", [[1, 2], [1, 3]]],
      ["boundary", [[4, 2, 3], [9, 2, 3]], "Different inner nodes, same leaves."],
    ],
  },
  {
    slug: "merge-two-binary-trees",
    title: "Merge Two Binary Trees",
    difficulty: "Easy",
    pattern: "Trees",
    fn: "mergeTrees",
    params: [["root1", T], ["root2", T]],
    returns: T,
    argTypes: ["TreeNode", "TreeNode"],
    returnKind: "TreeNode",
    hints: [
      "Walk both trees together. Where both have a node, add the values; where only one has a node, that whole subtree is reused as is.",
      "Recurse: if either is empty return the other; otherwise add root2's value into root1 and merge the children pairwise.",
      "merge(a, b):\n  if a is empty: return b\n  if b is empty: return a\n  a.val = a.val + b.val\n  a.left = merge(a.left, b.left)\n  a.right = merge(a.right, b.right)\n  return a",
    ],
    reference: `function mergeTrees(root1, root2) { if (!root1) return root2; if (!root2) return root1; root1.val += root2.val; root1.left = mergeTrees(root1.left, root2.left); root1.right = mergeTrees(root1.right, root2.right); return root1; }`,
    brute: `function mergeTrees(root1, root2) { const copy = (a, b) => (!a && !b ? null : new TreeNode((a ? a.val : 0) + (b ? b.val : 0), copy(a && a.left, b && b.left), copy(a && a.right, b && b.right))); return copy(root1, root2); }`,
    fuzz: treeGen(`return [__levelTree(rand, __r(rand, 0, 8), -5, 9), __levelTree(rand, __r(rand, 0, 8), -5, 9)];`),
    examples: [[[1, 3, 2, 5], [2, 1, 3, null, 4, null, 7]], [[1], [1, 2]]],
    edges: [
      ["empty", [[], []]],
      ["null-input", [[], [1, 2]], "One tree is empty: the answer is the other tree."],
      ["negatives", [[-1, -2], [1, null, 3]]],
    ],
  },
  {
    slug: "cousins-in-binary-tree",
    title: "Cousins in Binary Tree",
    difficulty: "Easy",
    pattern: "Trees",
    fn: "isCousins",
    params: [["root", T], ["x", "number"], ["y", "number"]],
    returns: "boolean",
    argTypes: ["TreeNode", "value", "value"],
    hints: [
      "Cousins sit at the same depth but have different parents. Find the depth and parent of x and of y.",
      "One DFS (or BFS) records (depth, parent) for both values; compare.",
      "find(node, parent, depth):\n  if node is empty: return\n  if node.val == x: dx, px = depth, parent\n  if node.val == y: dy, py = depth, parent\n  find(node.left, node, depth + 1)\n  find(node.right, node, depth + 1)\nreturn dx == dy and px != py",
    ],
    reference: `function isCousins(root, x, y) { let dx, dy, px, py; const go = (n, p, d) => { if (!n) return; if (n.val === x) { dx = d; px = p; } if (n.val === y) { dy = d; py = p; } go(n.left, n, d + 1); go(n.right, n, d + 1); }; go(root, null, 0); return dx === dy && px !== py; }`,
    brute: `function isCousins(root, x, y) { let level = [root]; while (level.length) { const vals = level.map((n) => n.val); const hx = vals.includes(x), hy = vals.includes(y); if (hx || hy) { if (!(hx && hy)) return false; for (const n of level) { const kids = [n.left, n.right].filter(Boolean).map((c) => c.val); if (kids.includes(x) && kids.includes(y)) return false; } break; } level = level.flatMap((n) => [n.left, n.right].filter(Boolean)); } let par = [root]; while (par.length) { for (const n of par) { const k = [n.left, n.right].filter(Boolean).map((c) => c.val); if (k.includes(x) && k.includes(y)) return false; } par = par.flatMap((n) => [n.left, n.right].filter(Boolean)); } return true; }`,
    fuzz: TREE_PQ,
    examples: [[[1, 2, 3, 4], 4, 3], [[1, 2, 3, null, 4, null, 5], 5, 4], [[1, 2, 3, null, 4], 2, 3]],
    edges: [
      ["two", [[1, 2], 1, 2]],
      ["boundary", [[1, 2, 3, 4, 5], 4, 5], "Same depth, same parent: siblings, not cousins."],
      ["order", [[1, 2, 3, 4, null, null, 5], 5, 4]],
    ],
  },
  {
    slug: "count-good-nodes-in-binary-tree",
    title: "Count Good Nodes in Binary Tree",
    difficulty: "Medium",
    pattern: "Trees",
    fn: "goodNodes",
    params: [["root", T]],
    returns: "number",
    argTypes: ["TreeNode"],
    hints: [
      "A node is good when nothing on the path from the root to it is bigger. You only need the maximum seen so far on the way down.",
      "DFS passing the running maximum; count the node if its value is at least that maximum.",
      "go(node, best):\n  if node is empty: return 0\n  good = 1 if node.val >= best else 0\n  best = max(best, node.val)\n  return good + go(node.left, best) + go(node.right, best)\nreturn go(root, root.val)",
    ],
    reference: `function goodNodes(root) { const go = (n, mx) => { if (!n) return 0; const g = n.val >= mx ? 1 : 0; mx = Math.max(mx, n.val); return g + go(n.left, mx) + go(n.right, mx); }; return go(root, -Infinity); }`,
    brute: `function goodNodes(root) { let c = 0; const go = (n, path) => { if (!n) return; if (path.every((v) => v <= n.val)) c++; go(n.left, path.concat(n.val)); go(n.right, path.concat(n.val)); }; go(root, []); return c; }`,
    fuzz: treeGen(`return [__levelTree(rand, __r(rand, 1, 12), -3, 5)];`),
    examples: [[[3, 1, 4, 3, null, 1, 5]], [[3, 3, null, 4, 2]], [[1]]],
    edges: [
      ["all-equal", [[2, 2, 2]], "Equal values count as good."],
      ["skewed", [[5, 4, null, 3]]],
      ["negatives", [[-1, -2, 0]]],
    ],
  },
  {
    slug: "construct-binary-tree-from-preorder-and-inorder-traversal",
    title: "Construct Binary Tree from Preorder and Inorder Traversal",
    difficulty: "Medium",
    pattern: "Trees",
    fn: "buildTree",
    params: [["preorder", "number[]"], ["inorder", "number[]"]],
    returns: T,
    returnKind: "TreeNode",
    hints: [
      "preorder[0] is the root. Its position in inorder splits the remaining values into the left and right subtrees.",
      "Map each value to its inorder index. Recurse on an inorder range, taking roots from preorder with a moving pointer: build left before right.",
      "pos = map value -> index in inorder; p = 0\nbuild(lo, hi):\n  if lo > hi: return empty\n  root = node(preorder[p]); p += 1\n  m = pos[root.val]\n  root.left = build(lo, m - 1)\n  root.right = build(m + 1, hi)\n  return root\nreturn build(0, n - 1)",
    ],
    reference: `function buildTree(preorder, inorder) { const pos = new Map(inorder.map((v, i) => [v, i])); let p = 0; const build = (lo, hi) => { if (lo > hi) return null; const root = new TreeNode(preorder[p++]); const m = pos.get(root.val); root.left = build(lo, m - 1); root.right = build(m + 1, hi); return root; }; return build(0, inorder.length - 1); }`,
    brute: `function buildTree(preorder, inorder) { if (!preorder.length) return null; const i = inorder.indexOf(preorder[0]); return new TreeNode(preorder[0], buildTree(preorder.slice(1, i + 1), inorder.slice(0, i)), buildTree(preorder.slice(i + 1), inorder.slice(i + 1))); }`,
    fuzz: TRAVERSALS("pre"),
    examples: [[[3, 9, 20, 15, 7], [9, 3, 15, 20, 7]], [[-1], [-1]]],
    edges: [
      ["two", [[1, 2], [2, 1]]],
      ["skewed", [[1, 2, 3], [1, 2, 3]], "Inorder equals preorder: every node has only a right child."],
      ["negatives", [[-3, -5, -1], [-5, -3, -1]]],
    ],
  },
  {
    slug: "construct-binary-tree-from-inorder-and-postorder-traversal",
    title: "Construct Binary Tree from Inorder and Postorder Traversal",
    difficulty: "Medium",
    pattern: "Trees",
    fn: "buildTree",
    params: [["inorder", "number[]"], ["postorder", "number[]"]],
    returns: T,
    returnKind: "TreeNode",
    hints: [
      "The last value of postorder is the root, and its inorder position splits left from right.",
      "Walk postorder from the end with a pointer. Because postorder ends ...left, right, root, build the right subtree before the left.",
      "pos = map value -> index in inorder; p = n - 1\nbuild(lo, hi):\n  if lo > hi: return empty\n  root = node(postorder[p]); p -= 1\n  m = pos[root.val]\n  root.right = build(m + 1, hi)\n  root.left = build(lo, m - 1)\n  return root\nreturn build(0, n - 1)",
    ],
    reference: `function buildTree(inorder, postorder) { const pos = new Map(inorder.map((v, i) => [v, i])); let p = postorder.length - 1; const build = (lo, hi) => { if (lo > hi) return null; const root = new TreeNode(postorder[p--]); const m = pos.get(root.val); root.right = build(m + 1, hi); root.left = build(lo, m - 1); return root; }; return build(0, inorder.length - 1); }`,
    brute: `function buildTree(inorder, postorder) { if (!postorder.length) return null; const r = postorder[postorder.length - 1], i = inorder.indexOf(r); return new TreeNode(r, buildTree(inorder.slice(0, i), postorder.slice(0, i)), buildTree(inorder.slice(i + 1), postorder.slice(i, -1))); }`,
    fuzz: TRAVERSALS("post"),
    examples: [[[9, 3, 15, 20, 7], [9, 15, 7, 20, 3]], [[-1], [-1]]],
    edges: [
      ["two", [[2, 1], [2, 1]]],
      ["skewed", [[1, 2, 3], [3, 2, 1]], "Every node has only a right child."],
      ["negatives", [[-5, -3, -1], [-5, -1, -3]]],
    ],
  },
  {
    slug: "lowest-common-ancestor-of-a-binary-tree",
    title: "Lowest Common Ancestor of a Binary Tree",
    difficulty: "Medium",
    pattern: "Trees",
    fn: "lowestCommonAncestor",
    params: [["root", "TreeNode"], ["p", "TreeNode"], ["q", "TreeNode"]],
    returns: "TreeNode",
    argTypes: ["TreeNode", "TreeNodeRef", "TreeNodeRef"],
    returnKind: "TreeNodeVal",
    hints: [
      "p and q are nodes of the tree. The answer is the deepest node that has both of them in its subtree (a node counts as its own descendant).",
      "Recurse: return the node itself if it is p or q; otherwise ask both children. If both sides found something, this node is the answer; else pass up whichever side did.",
      "lca(node):\n  if node is empty or node == p or node == q: return node\n  l = lca(node.left)\n  r = lca(node.right)\n  if l and r: return node\n  return l if l else r",
    ],
    reference: `function lowestCommonAncestor(root, p, q) { if (!root || root === p || root === q) return root; const l = lowestCommonAncestor(root.left, p, q), r = lowestCommonAncestor(root.right, p, q); return l && r ? root : l || r; }`,
    brute: `function lowestCommonAncestor(root, p, q) { const parent = new Map([[root, null]]), st = [root]; while (st.length) { const n = st.pop(); for (const c of [n.left, n.right]) if (c) { parent.set(c, n); st.push(c); } } const anc = new Set(); for (let n = p; n; n = parent.get(n)) anc.add(n); for (let n = q; n; n = parent.get(n)) if (anc.has(n)) return n; return null; }`,
    fuzz: TREE_PQ,
    examples: [[[3, 5, 1, 6, 2, 0, 8, null, null, 7, 4], 5, 1], [[3, 5, 1, 6, 2, 0, 8, null, null, 7, 4], 5, 4], [[1, 2], 1, 2]],
    edges: [
      ["skewed", [[1, 2, null, 3, null, 4], 4, 3]],
      ["boundary", [[3, 5, 1], 3, 1], "p is the root itself."],
      ["order", [[1, 2, 3, 4, 5, null, null, 6, 7], 6, 5], "Both nodes are deep in the left subtree."],
    ],
  },
  {
    slug: "binary-tree-level-order-traversal-ii",
    title: "Binary Tree Level Order Traversal II",
    difficulty: "Medium",
    pattern: "Trees",
    fn: "levelOrderBottom",
    params: [["root", T]],
    returns: "number[][]",
    argTypes: ["TreeNode"],
    hints: [
      "It is the usual level order, just listed from the bottom level up.",
      "BFS level by level collecting each level's values, then reverse the list of levels.",
      "levels = [], queue = [root] if root\nwhile queue not empty:\n  level = values of the nodes in queue\n  queue = children of those nodes, left to right\n  levels.append(level)\nreturn reversed(levels)",
    ],
    reference: `function levelOrderBottom(root) { const out = []; let q = root ? [root] : []; while (q.length) { out.push(q.map((n) => n.val)); q = q.flatMap((n) => [n.left, n.right].filter(Boolean)); } return out.reverse(); }`,
    brute: `function levelOrderBottom(root) { const lv = []; const go = (n, d) => { if (!n) return; (lv[d] = lv[d] || []).push(n.val); go(n.left, d + 1); go(n.right, d + 1); }; go(root, 0); const out = []; for (let i = lv.length - 1; i >= 0; i--) out.push(lv[i]); return out; }`,
    fuzz: ANY_TREE,
    examples: [[[3, 9, 20, null, null, 15, 7]], [[1]]],
    edges: [
      ["empty", [[]]],
      ["skewed", [[1, 2, null, 3]]],
      ["negatives", [[0, -1, -2]]],
    ],
  },
  {
    slug: "binary-tree-zigzag-level-order-traversal",
    title: "Binary Tree Zigzag Level Order Traversal",
    difficulty: "Medium",
    pattern: "Trees",
    fn: "zigzagLevelOrder",
    params: [["root", T]],
    returns: "number[][]",
    argTypes: ["TreeNode"],
    hints: [
      "Level order, but every other level is read right to left.",
      "BFS by level as usual, and reverse the values of odd-numbered levels (or insert at the front) before adding them.",
      "levels = [], queue = [root] if root, depth = 0\nwhile queue not empty:\n  level = values in queue\n  if depth is odd: reverse level\n  levels.append(level)\n  queue = children, left to right\n  depth += 1\nreturn levels",
    ],
    reference: `function zigzagLevelOrder(root) { const out = []; let q = root ? [root] : [], d = 0; while (q.length) { const vals = q.map((n) => n.val); out.push(d % 2 ? vals.reverse() : vals); q = q.flatMap((n) => [n.left, n.right].filter(Boolean)); d++; } return out; }`,
    brute: `function zigzagLevelOrder(root) { const lv = []; const go = (n, d) => { if (!n) return; lv[d] = lv[d] || []; if (d % 2) lv[d].unshift(n.val); else lv[d].push(n.val); go(n.left, d + 1); go(n.right, d + 1); }; go(root, 0); return lv; }`,
    fuzz: ANY_TREE,
    examples: [[[3, 9, 20, null, null, 15, 7]], [[1]]],
    edges: [
      ["empty", [[]]],
      ["skewed", [[1, 2, null, 3]]],
      ["order", [[1, 2, 3, 4, 5, 6, 7]], "Level 2 is read right to left, level 3 left to right."],
    ],
  },
  {
    slug: "path-sum-ii",
    title: "Path Sum II",
    difficulty: "Medium",
    pattern: "Trees",
    fn: "pathSum",
    params: [["root", T], ["targetSum", "number"]],
    returns: "number[][]",
    argTypes: ["TreeNode", "value"],
    compare: "unordered-outer",
    hints: [
      "Like Path Sum, but you must return every root-to-leaf path with the target sum, so carry the path itself. Any order of paths is accepted.",
      "Backtracking DFS: push the node, recurse with the remaining sum, pop on the way back. At a leaf with remaining 0, save a copy of the path.",
      "out = [], path = []\ndfs(node, left):\n  if node is empty: return\n  path.append(node.val); left = left - node.val\n  if node is a leaf and left == 0: out.append(copy of path)\n  dfs(node.left, left); dfs(node.right, left)\n  path.pop()\ndfs(root, targetSum)\nreturn out",
    ],
    reference: `function pathSum(root, targetSum) { const out = [], path = []; const go = (n, left) => { if (!n) return; path.push(n.val); left -= n.val; if (!n.left && !n.right && left === 0) out.push(path.slice()); go(n.left, left); go(n.right, left); path.pop(); }; go(root, targetSum); return out; }`,
    brute: `function pathSum(root, targetSum) { const all = []; const go = (n, p) => { if (!n) return; p = p.concat(n.val); if (!n.left && !n.right) all.push(p); go(n.left, p); go(n.right, p); }; go(root, []); return all.filter((p) => p.reduce((a, b) => a + b, 0) === targetSum); }`,
    fuzz: treeGen(`const t = __levelTree(rand, __r(rand, 0, 10), -3, 5); let target = __r(rand, -5, 12); if (t.length && rand() < 0.6) { let n = __treeFromLevelOrder(t), s = 0; while (n) { s += n.val; n = n.left && n.right ? (rand() < 0.5 ? n.left : n.right) : n.left || n.right; } target = s; } return [t, target];`),
    examples: [[[5, 4, 8, 11, null, 13, 4, 7, 2, null, null, 5, 1], 22], [[1, 2, 3], 5], [[1, 2], 0]],
    edges: [
      ["empty", [[], 0]],
      ["negatives", [[-2, null, -3], -5]],
      ["duplicates", [[1, 1, 1], 2], "Two different paths with the same values."],
    ],
  },
  {
    slug: "path-sum-iii",
    title: "Path Sum III",
    difficulty: "Medium",
    pattern: "Trees",
    fn: "pathSum",
    params: [["root", T], ["targetSum", "number"]],
    returns: "number",
    argTypes: ["TreeNode", "value"],
    hints: [
      "A path can start and end anywhere, as long as it goes downward. That is a subarray-sum question on every root-to-node path.",
      "DFS carrying the running prefix sum and a map of prefix sums seen on the current path. Paths ending here = count[sum - target]. Undo the map entry when you return.",
      "count = {0: 1}\ndfs(node, sum):\n  if node is empty: return 0\n  sum = sum + node.val\n  found = count[sum - targetSum]\n  count[sum] += 1\n  found = found + dfs(node.left, sum) + dfs(node.right, sum)\n  count[sum] -= 1\n  return found\nreturn dfs(root, 0)",
    ],
    reference: `function pathSum(root, targetSum) { const cnt = new Map([[0, 1]]); const go = (n, s) => { if (!n) return 0; s += n.val; let f = cnt.get(s - targetSum) || 0; cnt.set(s, (cnt.get(s) || 0) + 1); f += go(n.left, s) + go(n.right, s); cnt.set(s, cnt.get(s) - 1); return f; }; return go(root, 0); }`,
    brute: `function pathSum(root, targetSum) { const from = (n, left) => (n ? (n.val === left ? 1 : 0) + from(n.left, left - n.val) + from(n.right, left - n.val) : 0); const all = (n) => (n ? from(n, targetSum) + all(n.left) + all(n.right) : 0); return all(root); }`,
    fuzz: treeGen(`return [__levelTree(rand, __r(rand, 0, 12), -3, 5), __r(rand, -3, 8)];`),
    examples: [[[10, 5, -3, 3, 2, null, 11, 3, -2, null, 1], 8], [[5, 4, 8, 11, null, 13, 4, 7, 2, null, null, 5, 1], 22]],
    edges: [
      ["empty", [[], 1]],
      ["zeros", [[0, 0, 0], 0], "Every single node and both two-node paths sum to 0."],
      ["negatives", [[1, -2, -3, 1, 3, -2, null, -1], -1]],
    ],
  },
  {
    slug: "sum-root-to-leaf-numbers",
    title: "Sum Root to Leaf Numbers",
    difficulty: "Medium",
    pattern: "Trees",
    fn: "sumNumbers",
    params: [["root", T]],
    returns: "number",
    argTypes: ["TreeNode"],
    hints: [
      "Each root-to-leaf path spells a number. Going down one level multiplies the number so far by 10 and adds the digit.",
      "DFS carrying the number built so far; at a leaf return it, otherwise return the sum of both children.",
      "go(node, cur):\n  if node is empty: return 0\n  cur = cur * 10 + node.val\n  if node is a leaf: return cur\n  return go(node.left, cur) + go(node.right, cur)\nreturn go(root, 0)",
    ],
    reference: `function sumNumbers(root) { const go = (n, cur) => { if (!n) return 0; cur = cur * 10 + n.val; if (!n.left && !n.right) return cur; return go(n.left, cur) + go(n.right, cur); }; return go(root, 0); }`,
    brute: `function sumNumbers(root) { let total = 0; const go = (n, s) => { if (!n) return; s += String(n.val); if (!n.left && !n.right) total += Number(s); go(n.left, s); go(n.right, s); }; go(root, ""); return total; }`,
    fuzz: treeGen(`return [__levelTree(rand, __r(rand, 1, 10), 0, 9)];`),
    examples: [[[1, 2, 3]], [[4, 9, 0, 5, 1]]],
    edges: [
      ["single", [[0]]],
      ["zeros", [[1, 0, 0]], "Leading digit 1, trailing zeros: 10 + 10."],
      ["skewed", [[1, 2, null, 3]]],
    ],
  },
  {
    slug: "flatten-binary-tree-to-linked-list",
    title: "Flatten Binary Tree to Linked List",
    difficulty: "Medium",
    pattern: "Trees",
    fn: "flatten",
    params: [["root", T]],
    returns: "void",
    argTypes: ["TreeNode"],
    returnKind: "arg0",
    hints: [
      "The result is the preorder sequence, linked through right pointers, with every left pointer null. Change the tree in place.",
      "For each node with a left subtree: find the rightmost node of that left subtree, hang the node's right subtree there, move left to right, and set left to null. Then step right.",
      "cur = root\nwhile cur:\n  if cur.left:\n    tail = cur.left\n    while tail.right: tail = tail.right\n    tail.right = cur.right\n    cur.right = cur.left\n    cur.left = empty\n  cur = cur.right",
    ],
    reference: `function flatten(root) { let cur = root; while (cur) { if (cur.left) { let t = cur.left; while (t.right) t = t.right; t.right = cur.right; cur.right = cur.left; cur.left = null; } cur = cur.right; } }`,
    brute: `function flatten(root) { const order = []; const go = (n) => { if (!n) return; order.push(n); go(n.left); go(n.right); }; go(root); for (let i = 0; i < order.length; i++) { order[i].left = null; order[i].right = order[i + 1] || null; } }`,
    fuzz: ANY_TREE,
    examples: [[[1, 2, 5, 3, 4, null, 6]], [[]]],
    edges: [
      ["single", [[0]]],
      ["skewed", [[1, 2, null, 3]], "A left chain becomes a right chain."],
      ["order", [[1, null, 2, null, 3]], "Already flat: nothing moves."],
    ],
  },
];

export const LADDER_TREES_SEEDED: ProblemSpec[] = DEFS.map((d) => define(d).spec);
