import { define, type ProblemDef } from "../../dsa-extras/define";
import { gen } from "../../dsa-extras/gen";
import type { ProblemSpec } from "../types";

const NUMS_TARGET: Array<[string, string]> = [["nums", "number[]"], ["target", "number"]];
const SORTED_MATRIX = `function __smatrix(rand, rows, cols) { var m = []; for (var i = 0; i < rows; i++) { var row = []; for (var j = 0; j < cols; j++) { var up = i ? m[i - 1][j] : 0, left = j ? row[j - 1] : 0; row.push(Math.max(up, left) + __r(rand, 0, 3)); } m.push(row); } return m; }`;
const ROTATED = `function __rotated(rand, n, lo, hi) { var a = __sorted(rand, n, lo, hi); var k = __r(rand, 0, n - 1); return a.slice(k).concat(a.slice(0, k)); }`;

/** Judges for seeded LeetCode problems that the Binary Search Ladder points at. LeetCode's own signatures. */
const DEFS: ProblemDef[] = [
  {
    slug: "find-first-and-last-position-of-element-in-sorted-array",
    title: "Find First and Last Position of Element in Sorted Array",
    difficulty: "Medium",
    pattern: "Binary Search",
    fn: "searchRange",
    params: NUMS_TARGET,
    returns: "number[]",
    hints: [
      "A plain binary search finds some copy of target. How do you make it keep going towards the first (or last) copy?",
      "Run two searches: one that moves left after a match (first index) and one that moves right after a match (last index). Return [-1, -1] if the first search finds nothing.",
      "first = -1, lo = 0, hi = n - 1\nwhile lo <= hi:\n  mid = (lo + hi) div 2\n  if nums[mid] >= target: hi = mid - 1; if nums[mid] == target: first = mid\n  else: lo = mid + 1\nlast = the same search, moving lo = mid + 1 when nums[mid] <= target\nreturn [first, last]",
    ],
    reference: `function searchRange(nums, target) { const find = (left) => { let lo = 0, hi = nums.length - 1, ans = -1; while (lo <= hi) { const m = (lo + hi) >> 1; if (nums[m] === target) { ans = m; if (left) hi = m - 1; else lo = m + 1; } else if (nums[m] < target) lo = m + 1; else hi = m - 1; } return ans; }; return [find(true), find(false)]; }`,
    brute: `function searchRange(nums, target) { return [nums.indexOf(target), nums.lastIndexOf(target)]; }`,
    fuzz: gen(`return [__sorted(rand, __r(rand, 0, 12), 0, 6), __r(rand, -1, 7)];`),
    examples: [[[5, 7, 7, 8, 8, 10], 8], [[5, 7, 7, 8, 8, 10], 6]],
    edges: [
      ["empty", [[], 0]],
      ["all-equal", [[2, 2, 2, 2], 2], "Every index matches: [0, n - 1]."],
      ["boundary", [[1, 2, 3], 3]],
    ],
  },
  {
    slug: "valid-perfect-square",
    title: "Valid Perfect Square",
    difficulty: "Easy",
    pattern: "Binary Search",
    fn: "isPerfectSquare",
    params: [["num", "number"]],
    returns: "boolean",
    hints: [
      "If num is a perfect square, its root lies between 1 and num. Squares grow monotonically, so you can search that range.",
      "Binary search x in [1, num]: if x * x equals num return true, if it's smaller move right, otherwise move left. Return false when the range empties.",
      "lo = 1, hi = num\nwhile lo <= hi:\n  mid = (lo + hi) div 2\n  sq = mid * mid\n  if sq == num: return true\n  if sq < num: lo = mid + 1\n  else: hi = mid - 1\nreturn false",
    ],
    reference: `function isPerfectSquare(num) { let lo = 1, hi = num; while (lo <= hi) { const m = Math.floor((lo + hi) / 2), s = m * m; if (s === num) return true; if (s < num) lo = m + 1; else hi = m - 1; } return false; }`,
    brute: `function isPerfectSquare(num) { for (let x = 1; x * x <= num; x++) if (x * x === num) return true; return false; }`,
    fuzz: gen(`const r = __r(rand, 1, 3000); return [rand() < 0.5 ? r * r : r * r + __r(rand, 1, 2 * r)];`),
    examples: [[16], [14]],
    edges: [
      ["min-size", [1]],
      ["extremes", [2147395600], "46340^2: mid * mid must not lose precision."],
      ["boundary", [2147483647], "Just above the largest square below 2^31."],
    ],
  },
  {
    slug: "arranging-coins",
    title: "Arranging Coins",
    difficulty: "Easy",
    pattern: "Binary Search",
    fn: "arrangeCoins",
    params: [["n", "number"]],
    returns: "number",
    hints: [
      "k complete rows need k(k + 1) / 2 coins. That grows with k, so the largest k that fits can be binary searched.",
      "Search k in [0, n] for the largest k with k(k + 1) / 2 <= n.",
      "lo = 0, hi = n\nwhile lo < hi:\n  mid = (lo + hi + 1) div 2\n  if mid * (mid + 1) / 2 <= n: lo = mid\n  else: hi = mid - 1\nreturn lo",
    ],
    reference: `function arrangeCoins(n) { let lo = 0, hi = n; while (lo < hi) { const m = Math.floor((lo + hi + 1) / 2); if ((m * (m + 1)) / 2 <= n) lo = m; else hi = m - 1; } return lo; }`,
    brute: `function arrangeCoins(n) { let k = 0; while (n >= k + 1) { k++; n -= k; } return k; }`,
    fuzz: gen(`return [__r(rand, 1, 5000)];`),
    examples: [[5], [8]],
    edges: [
      ["min-size", [1]],
      ["boundary", [6], "Exactly 3 full rows."],
      ["large", [1804289383]],
    ],
  },
  {
    slug: "search-in-rotated-sorted-array-ii",
    title: "Search in Rotated Sorted Array II",
    difficulty: "Medium",
    pattern: "Binary Search",
    fn: "search",
    params: NUMS_TARGET,
    returns: "boolean",
    hints: [
      "Without duplicates, one half around mid is always sorted. With duplicates, when can't you tell which half is sorted?",
      "If nums[lo] == nums[mid] == nums[hi], shrink both ends by one. Otherwise decide which half is sorted, and whether target lies inside it, as in the version without duplicates.",
      "lo = 0, hi = n - 1\nwhile lo <= hi:\n  mid = (lo + hi) div 2\n  if nums[mid] == target: return true\n  if nums[lo] == nums[mid] == nums[hi]: lo += 1, hi -= 1\n  else if nums[lo] <= nums[mid]:\n    if nums[lo] <= target < nums[mid]: hi = mid - 1 else lo = mid + 1\n  else:\n    if nums[mid] < target <= nums[hi]: lo = mid + 1 else hi = mid - 1\nreturn false",
    ],
    reference: `function search(nums, target) { let lo = 0, hi = nums.length - 1; while (lo <= hi) { const m = (lo + hi) >> 1; if (nums[m] === target) return true; if (nums[lo] === nums[m] && nums[m] === nums[hi]) { lo++; hi--; } else if (nums[lo] <= nums[m]) { if (nums[lo] <= target && target < nums[m]) hi = m - 1; else lo = m + 1; } else { if (nums[m] < target && target <= nums[hi]) lo = m + 1; else hi = m - 1; } } return false; }`,
    brute: `function search(nums, target) { return nums.includes(target); }`,
    fuzz: gen(`${ROTATED} return [__rotated(rand, __r(rand, 1, 12), 0, 4), __r(rand, -1, 5)];`),
    examples: [[[2, 5, 6, 0, 0, 1, 2], 0], [[2, 5, 6, 0, 0, 1, 2], 3]],
    edges: [
      ["all-equal", [[1, 0, 1, 1, 1], 0], "nums[lo], nums[mid] and nums[hi] are all 1: you can't tell which half is sorted."],
      ["single", [[1], 0]],
      ["duplicates", [[1, 1, 1, 1, 1, 1, 1, 1, 1, 13, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 13]],
    ],
  },
  {
    slug: "single-element-in-a-sorted-array",
    title: "Single Element in a Sorted Array",
    difficulty: "Medium",
    pattern: "Binary Search",
    fn: "singleNonDuplicate",
    params: [["nums", "number[]"]],
    returns: "number",
    hints: [
      "Before the single element, pairs start at even indices. After it, pairs start at odd indices.",
      "Binary search on even indices only: if nums[mid] == nums[mid + 1] (mid even), the single element is to the right; otherwise it's at mid or to the left.",
      "lo = 0, hi = n - 1\nwhile lo < hi:\n  mid = (lo + hi) div 2\n  if mid is odd: mid -= 1\n  if nums[mid] == nums[mid + 1]: lo = mid + 2\n  else: hi = mid\nreturn nums[lo]",
    ],
    reference: `function singleNonDuplicate(nums) { let lo = 0, hi = nums.length - 1; while (lo < hi) { let m = (lo + hi) >> 1; if (m % 2) m--; if (nums[m] === nums[m + 1]) lo = m + 2; else hi = m; } return nums[lo]; }`,
    brute: `function singleNonDuplicate(nums) { return nums.reduce((a, b) => a ^ b, 0); }`,
    fuzz: gen(`const vals = __shuffle(rand, Array.from({ length: 20 }, (_, i) => i)).slice(0, __r(rand, 1, 6)).sort((a, b) => a - b); const single = __pick(rand, vals); const out = []; for (const v of vals) { out.push(v); if (v !== single) out.push(v); } return [out];`),
    examples: [[[1, 1, 2, 3, 3, 4, 4, 8, 8]], [[3, 3, 7, 7, 10, 11, 11]]],
    edges: [
      ["single", [[5]]],
      ["boundary", [[1, 2, 2, 3, 3]], "The single element is first."],
      ["sorted", [[1, 1, 2, 2, 9]], "The single element is last."],
    ],
  },
  {
    slug: "peak-index-in-a-mountain-array",
    title: "Peak Index in a Mountain Array",
    difficulty: "Medium",
    pattern: "Binary Search",
    fn: "peakIndexInMountainArray",
    params: [["arr", "number[]"]],
    returns: "number",
    hints: [
      "Compare arr[mid] with arr[mid + 1]. Which side of the peak are you on?",
      "If arr[mid] < arr[mid + 1] you're on the rising slope, so the peak is to the right; otherwise it's at mid or to the left.",
      "lo = 0, hi = n - 1\nwhile lo < hi:\n  mid = (lo + hi) div 2\n  if arr[mid] < arr[mid + 1]: lo = mid + 1\n  else: hi = mid\nreturn lo",
    ],
    reference: `function peakIndexInMountainArray(arr) { let lo = 0, hi = arr.length - 1; while (lo < hi) { const m = (lo + hi) >> 1; if (arr[m] < arr[m + 1]) lo = m + 1; else hi = m; } return lo; }`,
    brute: `function peakIndexInMountainArray(arr) { return arr.indexOf(Math.max(...arr)); }`,
    fuzz: gen(`const up = __r(rand, 1, 6), down = __r(rand, 1, 6); const top = __r(rand, 10, 20); const a = []; let v = top - up * __r(rand, 1, 2); for (let i = 0; i < up; i++) { a.push(v); v += __r(rand, 1, 2); } a.push(Math.max(top, v)); v = a[a.length - 1]; for (let i = 0; i < down; i++) { v -= __r(rand, 1, 2); a.push(v); } return [a];`),
    examples: [[[0, 1, 0]], [[0, 2, 1, 0]]],
    edges: [
      ["min-size", [[1, 3, 2]]],
      ["boundary", [[0, 10, 5, 2]], "The peak sits right after the first element."],
      ["sorted", [[1, 2, 3, 4, 5, 0]], "The peak is the second-to-last element."],
    ],
  },
  {
    slug: "find-peak-element",
    title: "Find Peak Element",
    difficulty: "Medium",
    pattern: "Binary Search",
    fn: "findPeakElement",
    params: [["nums", "number[]"]],
    returns: "number",
    hints: [
      "Treat nums[-1] and nums[n] as minus infinity. If nums[mid] < nums[mid + 1], is there certainly a peak to the right?",
      "Yes: walking uphill to the right must end at a peak. So move lo = mid + 1 when nums[mid] < nums[mid + 1], else hi = mid. Every test here has exactly one peak.",
      "lo = 0, hi = n - 1\nwhile lo < hi:\n  mid = (lo + hi) div 2\n  if nums[mid] < nums[mid + 1]: lo = mid + 1\n  else: hi = mid\nreturn lo",
    ],
    reference: `function findPeakElement(nums) { let lo = 0, hi = nums.length - 1; while (lo < hi) { const m = (lo + hi) >> 1; if (nums[m] < nums[m + 1]) lo = m + 1; else hi = m; } return lo; }`,
    brute: `function findPeakElement(nums) { for (let i = 0; i < nums.length; i++) if ((i === 0 || nums[i] > nums[i - 1]) && (i === nums.length - 1 || nums[i] > nums[i + 1])) return i; return -1; }`,
    fuzz: gen(`const up = __r(rand, 0, 6), down = __r(rand, 0, 6); const a = []; let v = __r(rand, -5, 5); for (let i = 0; i < up; i++) { a.push(v); v += __r(rand, 1, 3); } a.push(v); for (let i = 0; i < down; i++) { v -= __r(rand, 1, 3); a.push(v); } return [a];`),
    examples: [[[1, 2, 3, 1]], [[1, 3, 5, 6, 4, 2]]],
    edges: [
      ["single", [[7]], "One element is a peak by itself."],
      ["sorted", [[1, 2, 3, 4]], "Strictly rising: the last index is the peak."],
      ["reverse-sorted", [[9, 5, 2]], "Strictly falling: index 0 is the peak."],
    ],
  },
  {
    slug: "find-the-smallest-divisor-given-a-threshold",
    title: "Find the Smallest Divisor Given a Threshold",
    difficulty: "Medium",
    pattern: "Binary Search",
    fn: "smallestDivisor",
    params: [["nums", "number[]"], ["threshold", "number"]],
    returns: "number",
    hints: [
      "A bigger divisor never makes the rounded-up sum larger. That monotonic yes/no question is what binary search on the answer needs.",
      "Search d in [1, max(nums)]. If the sum of ceil(v / d) is within threshold, try smaller d (hi = d); otherwise lo = d + 1.",
      "lo = 1, hi = max(nums)\nwhile lo < hi:\n  mid = (lo + hi) div 2\n  total = sum of ceil(v / mid) over nums\n  if total <= threshold: hi = mid\n  else: lo = mid + 1\nreturn lo",
    ],
    reference: `function smallestDivisor(nums, threshold) { let lo = 1, hi = Math.max(...nums); while (lo < hi) { const m = (lo + hi) >> 1; let t = 0; for (const v of nums) t += Math.ceil(v / m); if (t <= threshold) hi = m; else lo = m + 1; } return lo; }`,
    brute: `function smallestDivisor(nums, threshold) { for (let d = 1; ; d++) if (nums.reduce((s, v) => s + Math.ceil(v / d), 0) <= threshold) return d; }`,
    fuzz: gen(`const a = __arr(rand, __r(rand, 1, 8), 1, 40); return [a, __r(rand, a.length, a.length + 30)];`),
    examples: [[[1, 2, 5, 9], 6], [[44, 22, 33, 11, 1], 5]],
    edges: [
      ["single", [[19], 5]],
      ["boundary", [[2, 3, 5, 7, 11], 11], "The rounded-up sum hits the threshold exactly at divisor 3."],
      ["all-equal", [[10, 10, 10], 3], "Threshold equals the length: the divisor must be max(nums)."],
    ],
  },
  {
    slug: "capacity-to-ship-packages-within-d-days",
    title: "Capacity To Ship Packages Within D Days",
    difficulty: "Medium",
    pattern: "Binary Search",
    fn: "shipWithinDays",
    params: [["weights", "number[]"], ["days", "number"]],
    returns: "number",
    hints: [
      "For a fixed capacity, how many days does a greedy left-to-right loading take? Does that count go up or down as capacity grows?",
      "Binary search the capacity in [max(weights), sum(weights)]. Simulate loading greedily; if it fits in days, try smaller, else larger.",
      "lo = max(weights), hi = sum(weights)\nwhile lo < hi:\n  cap = (lo + hi) div 2\n  need = 1, load = 0\n  for each w in weights:\n    if load + w > cap: need += 1, load = 0\n    load += w\n  if need <= days: hi = cap\n  else: lo = cap + 1\nreturn lo",
    ],
    reference: `function shipWithinDays(weights, days) { let lo = Math.max(...weights), hi = weights.reduce((a, b) => a + b, 0); while (lo < hi) { const c = (lo + hi) >> 1; let need = 1, load = 0; for (const w of weights) { if (load + w > c) { need++; load = 0; } load += w; } if (need <= days) hi = c; else lo = c + 1; } return lo; }`,
    brute: `function shipWithinDays(weights, days) { for (let c = Math.max(...weights); ; c++) { let need = 1, load = 0; for (const w of weights) { if (load + w > c) { need++; load = 0; } load += w; } if (need <= days) return c; } }`,
    fuzz: gen(`const w = __arr(rand, __r(rand, 1, 10), 1, 10); return [w, __r(rand, 1, w.length)];`),
    examples: [[[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], 5], [[3, 2, 2, 4, 1, 4], 3]],
    edges: [
      ["single", [[7], 1]],
      ["boundary", [[1, 2, 3, 1, 1], 5], "One package per day: the answer is the heaviest package."],
      ["min-size", [[4, 5, 6], 1], "One day: carry everything at once."],
    ],
  },
  {
    slug: "minimum-number-of-days-to-make-m-bouquets",
    title: "Minimum Number of Days to Make m Bouquets",
    difficulty: "Medium",
    pattern: "Binary Search",
    fn: "minDays",
    params: [["bloomDay", "number[]"], ["m", "number"], ["k", "number"]],
    returns: "number",
    hints: [
      "If m * k exceeds the number of flowers it's impossible. Otherwise, if you can make m bouquets by day d, can you also by day d + 1?",
      "Binary search the day between min and max bloomDay. For a day d, count runs of adjacent bloomed flowers and how many bouquets of k they give.",
      "if m * k > n: return -1\nlo = min(bloomDay), hi = max(bloomDay)\nwhile lo < hi:\n  d = (lo + hi) div 2\n  bouquets = 0, run = 0\n  for each b in bloomDay:\n    run = run + 1 if b <= d else 0\n    if run == k: bouquets += 1, run = 0\n  if bouquets >= m: hi = d\n  else: lo = d + 1\nreturn lo",
    ],
    reference: `function minDays(bloomDay, m, k) { if (m * k > bloomDay.length) return -1; let lo = Math.min(...bloomDay), hi = Math.max(...bloomDay); while (lo < hi) { const d = (lo + hi) >> 1; let b = 0, run = 0; for (const x of bloomDay) { run = x <= d ? run + 1 : 0; if (run === k) { b++; run = 0; } } if (b >= m) hi = d; else lo = d + 1; } return lo; }`,
    brute: `function minDays(bloomDay, m, k) { const days = [...new Set(bloomDay)].sort((a, b) => a - b); for (const d of days) { let b = 0, run = 0; for (const x of bloomDay) { run = x <= d ? run + 1 : 0; if (run === k) { b++; run = 0; } } if (b >= m) return d; } return -1; }`,
    fuzz: gen(`const n = __r(rand, 1, 10); return [__arr(rand, n, 1, 12), __r(rand, 1, 4), __r(rand, 1, 3)];`),
    examples: [[[1, 10, 3, 10, 2], 3, 1], [[1, 10, 3, 10, 2], 3, 2]],
    edges: [
      ["no-answer", [[1, 2], 2, 2], "Needs 4 flowers but there are only 2: -1."],
      ["single", [[7], 1, 1]],
      ["boundary", [[7, 7, 7, 7, 12, 7, 7], 2, 3], "Adjacency matters: day 12 is needed."],
    ],
  },
  {
    slug: "successful-pairs-of-spells-and-potions",
    title: "Successful Pairs of Spells and Potions",
    difficulty: "Medium",
    pattern: "Binary Search",
    fn: "successfulPairs",
    params: [["spells", "number[]"], ["potions", "number[]"], ["success", "number"]],
    returns: "number[]",
    hints: [
      "For one spell s, a potion p works when s * p >= success. If potions were sorted, the working ones would form a suffix.",
      "Sort potions once. For each spell, binary search the first potion with spell * potion >= success; the answer is potions.length minus that index.",
      "sort potions\nfor each spell s:\n  lo = 0, hi = m\n  while lo < hi:\n    mid = (lo + hi) div 2\n    if s * potions[mid] >= success: hi = mid\n    else: lo = mid + 1\n  add m - lo to result\nreturn result",
    ],
    reference: `function successfulPairs(spells, potions, success) { const p = potions.slice().sort((a, b) => a - b); return spells.map((s) => { let lo = 0, hi = p.length; while (lo < hi) { const m = (lo + hi) >> 1; if (s * p[m] >= success) hi = m; else lo = m + 1; } return p.length - lo; }); }`,
    brute: `function successfulPairs(spells, potions, success) { return spells.map((s) => potions.filter((p) => s * p >= success).length); }`,
    fuzz: gen(`return [__arr(rand, __r(rand, 1, 6), 1, 10), __arr(rand, __r(rand, 1, 8), 1, 10), __r(rand, 1, 60)];`),
    examples: [[[5, 1, 3], [1, 2, 3, 4, 5], 7], [[3, 1, 2], [8, 5, 8], 16]],
    edges: [
      ["no-answer", [[1, 1], [1, 2], 100], "No pair is strong enough."],
      ["single", [[4], [5], 20], "Exactly reaches success: counts."],
      ["duplicates", [[2], [3, 3, 3, 1], 6]],
    ],
  },
  {
    slug: "minimum-time-to-complete-trips",
    title: "Minimum Time to Complete Trips",
    difficulty: "Medium",
    pattern: "Binary Search",
    fn: "minimumTime",
    params: [["time", "number[]"], ["totalTrips", "number"]],
    returns: "number",
    hints: [
      "In t units of time, bus i completes floor(t / time[i]) trips. More time never means fewer trips.",
      "Binary search t in [1, min(time) * totalTrips]; check whether the trips add up to at least totalTrips.",
      "lo = 1, hi = min(time) * totalTrips\nwhile lo < hi:\n  t = (lo + hi) div 2\n  trips = sum of floor(t / x) over time\n  if trips >= totalTrips: hi = t\n  else: lo = t + 1\nreturn lo",
    ],
    reference: `function minimumTime(time, totalTrips) { let lo = 1, hi = Math.min(...time) * totalTrips; while (lo < hi) { const t = Math.floor((lo + hi) / 2); let s = 0; for (const x of time) s += Math.floor(t / x); if (s >= totalTrips) hi = t; else lo = t + 1; } return lo; }`,
    brute: `function minimumTime(time, totalTrips) { for (let t = 1; ; t++) if (time.reduce((s, x) => s + Math.floor(t / x), 0) >= totalTrips) return t; }`,
    fuzz: gen(`return [__arr(rand, __r(rand, 1, 6), 1, 9), __r(rand, 1, 30)];`),
    examples: [[[1, 2, 3], 5], [[2], 1]],
    edges: [
      ["single", [[5], 3]],
      ["all-equal", [[3, 3, 3], 3], "Three buses finish one trip each at t = 3."],
      ["boundary", [[9, 1], 10], "The fast bus does almost everything."],
    ],
  },
  {
    slug: "magnetic-force-between-two-balls",
    title: "Magnetic Force Between Two Balls",
    difficulty: "Medium",
    pattern: "Binary Search",
    fn: "maxDistance",
    params: [["position", "number[]"], ["m", "number"]],
    returns: "number",
    hints: [
      "This is aggressive cows: can you place m balls so every pair is at least d apart? A smaller d is always easier.",
      "Sort positions. Binary search d for the largest value where greedy placement (put a ball as soon as the gap reaches d) places at least m balls.",
      "sort position\nlo = 1, hi = position[n - 1] - position[0]\nwhile lo < hi:\n  d = (lo + hi + 1) div 2\n  placed = 1, last = position[0]\n  for each p in position:\n    if p - last >= d: placed += 1, last = p\n  if placed >= m: lo = d\n  else: hi = d - 1\nreturn lo",
    ],
    reference: `function maxDistance(position, m) { const p = position.slice().sort((a, b) => a - b); let lo = 1, hi = p[p.length - 1] - p[0]; while (lo < hi) { const d = Math.floor((lo + hi + 1) / 2); let c = 1, last = p[0]; for (const x of p) if (x - last >= d) { c++; last = x; } if (c >= m) lo = d; else hi = d - 1; } return lo; }`,
    brute: `function maxDistance(position, m) { const p = position.slice().sort((a, b) => a - b); const cands = new Set(); for (let i = 0; i < p.length; i++) for (let j = i + 1; j < p.length; j++) cands.add(p[j] - p[i]); let best = 0; for (const d of cands) { let c = 1, last = p[0]; for (const x of p) if (x - last >= d) { c++; last = x; } if (c >= m) best = Math.max(best, d); } return best; }`,
    fuzz: gen(`const s = new Set(); const n = __r(rand, 2, 8); while (s.size < n) s.add(__r(rand, 1, 40)); const a = [...s]; return [a, __r(rand, 2, a.length)];`),
    examples: [[[1, 2, 3, 4, 7], 3], [[5, 4, 3, 2, 1, 1000000000], 2]],
    edges: [
      ["two", [[1, 100], 2]],
      ["boundary", [[1, 2, 3, 4, 5], 5], "Every position is used: the gap is 1."],
      ["sorted", [[10, 20, 30, 40], 3]],
    ],
  },
  {
    slug: "minimized-maximum-of-products-distributed-to-any-store",
    title: "Minimized Maximum of Products Distributed to Any Store",
    difficulty: "Medium",
    pattern: "Binary Search",
    fn: "minimizedMaximum",
    params: [["n", "number"], ["quantities", "number[]"]],
    returns: "number",
    hints: [
      "If every store may receive at most x items, product type q needs ceil(q / x) stores. Is the total count monotonic in x?",
      "Binary search x in [1, max(quantities)]: x works when the sum of ceil(q / x) is at most n.",
      "lo = 1, hi = max(quantities)\nwhile lo < hi:\n  x = (lo + hi) div 2\n  stores = sum of ceil(q / x) over quantities\n  if stores <= n: hi = x\n  else: lo = x + 1\nreturn lo",
    ],
    reference: `function minimizedMaximum(n, quantities) { let lo = 1, hi = Math.max(...quantities); while (lo < hi) { const x = (lo + hi) >> 1; let s = 0; for (const q of quantities) s += Math.ceil(q / x); if (s <= n) hi = x; else lo = x + 1; } return lo; }`,
    brute: `function minimizedMaximum(n, quantities) { for (let x = 1; ; x++) if (quantities.reduce((s, q) => s + Math.ceil(q / x), 0) <= n) return x; }`,
    fuzz: gen(`const q = __arr(rand, __r(rand, 1, 5), 1, 20); return [__r(rand, q.length, q.length + 8), q];`),
    examples: [[6, [11, 6]], [7, [15, 10, 10]]],
    edges: [
      ["boundary", [1, [100000]], "One store gets everything."],
      ["single", [3, [1]]],
      ["all-equal", [4, [5, 5]]],
    ],
  },
  {
    slug: "split-array-largest-sum",
    title: "Split Array Largest Sum",
    difficulty: "Hard",
    pattern: "Binary Search",
    fn: "splitArray",
    params: [["nums", "number[]"], ["k", "number"]],
    returns: "number",
    hints: [
      "Guess the answer S: can you cut the array into at most k pieces each summing to at most S? A bigger S only makes that easier.",
      "Binary search S in [max(nums), sum(nums)]. Greedily extend the current piece until adding the next number would exceed S, then start a new piece; S works if pieces <= k.",
      "lo = max(nums), hi = sum(nums)\nwhile lo < hi:\n  S = (lo + hi) div 2\n  pieces = 1, cur = 0\n  for each v in nums:\n    if cur + v > S: pieces += 1, cur = 0\n    cur += v\n  if pieces <= k: hi = S\n  else: lo = S + 1\nreturn lo",
    ],
    reference: `function splitArray(nums, k) { let lo = Math.max(...nums), hi = nums.reduce((a, b) => a + b, 0); while (lo < hi) { const S = Math.floor((lo + hi) / 2); let p = 1, c = 0; for (const v of nums) { if (c + v > S) { p++; c = 0; } c += v; } if (p <= k) hi = S; else lo = S + 1; } return lo; }`,
    brute: `function splitArray(nums, k) { const n = nums.length; const memo = new Map(); const go = (i, parts) => { if (i === n) return parts === 0 ? 0 : Infinity; if (parts === 0) return Infinity; const key = i + "," + parts; if (memo.has(key)) return memo.get(key); let best = Infinity, s = 0; for (let j = i; j < n; j++) { s += nums[j]; best = Math.min(best, Math.max(s, go(j + 1, parts - 1))); } memo.set(key, best); return best; }; return go(0, k); }`,
    fuzz: gen(`const a = __arr(rand, __r(rand, 1, 9), 0, 12); return [a, __r(rand, 1, a.length)];`),
    examples: [[[7, 2, 5, 10, 8], 2], [[1, 2, 3, 4, 5], 2]],
    edges: [
      ["single", [[9], 1]],
      ["boundary", [[1, 4, 4], 3], "One number per piece: the answer is the largest number."],
      ["zeros", [[0, 0, 0, 5], 2]],
    ],
  },
  {
    slug: "search-a-2d-matrix-ii",
    title: "Search a 2D Matrix II",
    difficulty: "Medium",
    pattern: "Binary Search",
    fn: "searchMatrix",
    params: [["matrix", "number[][]"], ["target", "number"]],
    returns: "boolean",
    hints: [
      "Rows and columns are sorted, but the whole matrix isn't. Which corner lets every comparison throw away a full row or column?",
      "Start at the top-right. If the value is larger than target, move left (the column is useless); if smaller, move down (the row is useless).",
      "r = 0, c = cols - 1\nwhile r < rows and c >= 0:\n  v = matrix[r][c]\n  if v == target: return true\n  if v > target: c -= 1\n  else: r += 1\nreturn false",
    ],
    reference: `function searchMatrix(matrix, target) { let r = 0, c = matrix[0].length - 1; while (r < matrix.length && c >= 0) { const v = matrix[r][c]; if (v === target) return true; if (v > target) c--; else r++; } return false; }`,
    brute: `function searchMatrix(matrix, target) { return matrix.some((row) => row.includes(target)); }`,
    fuzz: gen(`${SORTED_MATRIX} const m = __smatrix(rand, __r(rand, 1, 5), __r(rand, 1, 5)); return [m, __r(rand, 0, 20)];`),
    examples: [[[[1, 4, 7, 11, 15], [2, 5, 8, 12, 19], [3, 6, 9, 16, 22], [10, 13, 14, 17, 24], [18, 21, 23, 26, 30]], 5], [[[1, 4, 7, 11, 15], [2, 5, 8, 12, 19], [3, 6, 9, 16, 22], [10, 13, 14, 17, 24], [18, 21, 23, 26, 30]], 20]],
    edges: [
      ["single", [[[5]], 5]],
      ["boundary", [[[1, 2], [3, 4]], 3], "Found in the bottom-left corner."],
      ["no-answer", [[[1, 3, 5]], 4]],
    ],
  },
  {
    slug: "kth-smallest-element-in-a-sorted-matrix",
    title: "Kth Smallest Element in a Sorted Matrix",
    difficulty: "Medium",
    pattern: "Binary Search",
    fn: "kthSmallest",
    params: [["matrix", "number[][]"], ["k", "number"]],
    returns: "number",
    hints: [
      "Instead of searching positions, search values: how many entries are <= x? That count grows with x.",
      "Binary search x between matrix[0][0] and matrix[n-1][n-1]. Count entries <= x with the staircase walk from the bottom-left; the smallest x with count >= k is the answer.",
      "lo = matrix[0][0], hi = matrix[n - 1][n - 1]\nwhile lo < hi:\n  x = (lo + hi) div 2\n  count = 0, r = n - 1, c = 0\n  while r >= 0 and c < n:\n    if matrix[r][c] <= x: count += r + 1, c += 1\n    else: r -= 1\n  if count >= k: hi = x\n  else: lo = x + 1\nreturn lo",
    ],
    reference: `function kthSmallest(matrix, k) { const n = matrix.length; let lo = matrix[0][0], hi = matrix[n - 1][n - 1]; while (lo < hi) { const x = Math.floor((lo + hi) / 2); let cnt = 0, r = n - 1, c = 0; while (r >= 0 && c < n) { if (matrix[r][c] <= x) { cnt += r + 1; c++; } else r--; } if (cnt >= k) hi = x; else lo = x + 1; } return lo; }`,
    brute: `function kthSmallest(matrix, k) { return matrix.flat().sort((a, b) => a - b)[k - 1]; }`,
    fuzz: gen(`${SORTED_MATRIX} const n = __r(rand, 1, 4); return [__smatrix(rand, n, n), __r(rand, 1, n * n)];`),
    examples: [[[[1, 5, 9], [10, 11, 13], [12, 13, 15]], 8], [[[-5]], 1]],
    edges: [
      ["duplicates", [[[1, 2], [1, 3]], 2], "Equal values count separately."],
      ["boundary", [[[1, 2], [3, 4]], 4], "k = n^2: the largest value."],
      ["negatives", [[[-5, -4], [-5, -4]], 3]],
    ],
  },
  {
    slug: "find-k-closest-elements",
    title: "Find K Closest Elements",
    difficulty: "Medium",
    pattern: "Binary Search",
    fn: "findClosestElements",
    params: [["arr", "number[]"], ["k", "number"], ["x", "number"]],
    returns: "number[]",
    hints: [
      "The answer is a contiguous window of length k. Can you binary search where that window starts?",
      "Search the start i in [0, n - k]. Compare x - arr[i] with arr[i + k] - x: if the left end is farther, the window should move right; otherwise left (ties prefer the smaller elements).",
      "lo = 0, hi = n - k\nwhile lo < hi:\n  mid = (lo + hi) div 2\n  if x - arr[mid] > arr[mid + k] - x: lo = mid + 1\n  else: hi = mid\nreturn arr[lo .. lo + k - 1]",
    ],
    reference: `function findClosestElements(arr, k, x) { let lo = 0, hi = arr.length - k; while (lo < hi) { const m = (lo + hi) >> 1; if (x - arr[m] > arr[m + k] - x) lo = m + 1; else hi = m; } return arr.slice(lo, lo + k); }`,
    brute: `function findClosestElements(arr, k, x) { return arr.slice().sort((a, b) => Math.abs(a - x) - Math.abs(b - x) || a - b).slice(0, k).sort((a, b) => a - b); }`,
    fuzz: gen(`const a = __sorted(rand, __r(rand, 1, 10), -5, 8); return [a, __r(rand, 1, a.length), __r(rand, -8, 10)];`),
    examples: [[[1, 2, 3, 4, 5], 4, 3], [[1, 1, 2, 3, 4, 5], 4, -1]],
    edges: [
      ["boundary", [[1, 2, 3, 4, 5], 4, 10], "x beyond the right end: take the last k."],
      ["duplicates", [[1, 1, 1, 10, 10, 10], 1, 9]],
      ["single", [[4], 1, 4]],
    ],
  },
  {
    slug: "median-of-two-sorted-arrays",
    title: "Median of Two Sorted Arrays",
    difficulty: "Hard",
    pattern: "Binary Search",
    fn: "findMedianSortedArrays",
    params: [["nums1", "number[]"], ["nums2", "number[]"]],
    returns: "number",
    hints: [
      "Merging is O(m + n). The median splits the combined array into two equal halves. Can you search how many elements of the shorter array go into the left half?",
      "Binary search i (from nums1) with j = half - i (from nums2) so that every left element is <= every right element: nums1[i-1] <= nums2[j] and nums2[j-1] <= nums1[i]. Then the median comes from the four border values.",
      "make nums1 the shorter array\nlo = 0, hi = m, half = (m + n + 1) div 2\nwhile lo <= hi:\n  i = (lo + hi) div 2, j = half - i\n  L1, R1 = nums1[i - 1], nums1[i] (minus/plus infinity past the ends)\n  L2, R2 = nums2[j - 1], nums2[j] (same)\n  if L1 <= R2 and L2 <= R1:\n    if m + n is odd: return max(L1, L2)\n    return (max(L1, L2) + min(R1, R2)) / 2\n  if L1 > R2: hi = i - 1\n  else: lo = i + 1",
    ],
    reference: `function findMedianSortedArrays(nums1, nums2) { if (nums1.length > nums2.length) return findMedianSortedArrays(nums2, nums1); const m = nums1.length, n = nums2.length, half = (m + n + 1) >> 1; let lo = 0, hi = m; while (lo <= hi) { const i = (lo + hi) >> 1, j = half - i; const L1 = i ? nums1[i - 1] : -Infinity, R1 = i < m ? nums1[i] : Infinity, L2 = j ? nums2[j - 1] : -Infinity, R2 = j < n ? nums2[j] : Infinity; if (L1 <= R2 && L2 <= R1) return (m + n) % 2 ? Math.max(L1, L2) : (Math.max(L1, L2) + Math.min(R1, R2)) / 2; if (L1 > R2) hi = i - 1; else lo = i + 1; } return 0; }`,
    brute: `function findMedianSortedArrays(nums1, nums2) { const a = nums1.concat(nums2).sort((x, y) => x - y), n = a.length; return n % 2 ? a[n >> 1] : (a[n / 2 - 1] + a[n / 2]) / 2; }`,
    fuzz: gen(`const a = __sorted(rand, __r(rand, 0, 6), -10, 10); const b = __sorted(rand, __r(rand, a.length ? 0 : 1, 6), -10, 10); return [a, b];`),
    examples: [[[1, 3], [2]], [[1, 2], [3, 4]]],
    edges: [
      ["empty", [[], [1]], "One array is empty."],
      ["negatives", [[-5, -3], [-4]]],
      ["duplicates", [[1, 1], [1, 1]]],
    ],
  },
  {
    slug: "find-minimum-in-rotated-sorted-array-ii",
    title: "Find Minimum in Rotated Sorted Array II",
    difficulty: "Hard",
    pattern: "Binary Search",
    fn: "findMin",
    params: [["nums", "number[]"]],
    returns: "number",
    hints: [
      "Compare nums[mid] with nums[hi]. Which outcomes tell you where the minimum is, and which tells you nothing?",
      "nums[mid] > nums[hi]: the minimum is right of mid. nums[mid] < nums[hi]: it's at mid or left. Equal: you can only drop hi by one safely.",
      "lo = 0, hi = n - 1\nwhile lo < hi:\n  mid = (lo + hi) div 2\n  if nums[mid] > nums[hi]: lo = mid + 1\n  else if nums[mid] < nums[hi]: hi = mid\n  else: hi -= 1\nreturn nums[lo]",
    ],
    reference: `function findMin(nums) { let lo = 0, hi = nums.length - 1; while (lo < hi) { const m = (lo + hi) >> 1; if (nums[m] > nums[hi]) lo = m + 1; else if (nums[m] < nums[hi]) hi = m; else hi--; } return nums[lo]; }`,
    brute: `function findMin(nums) { return Math.min(...nums); }`,
    fuzz: gen(`${ROTATED} return [__rotated(rand, __r(rand, 1, 12), 0, 4)];`),
    examples: [[[1, 3, 5]], [[2, 2, 2, 0, 1]]],
    edges: [
      ["all-equal", [[3, 3, 3, 3]]],
      ["single", [[4]]],
      ["duplicates", [[3, 1, 3, 3, 3]], "nums[mid] == nums[hi] while the minimum hides on the left."],
    ],
  },
  {
    slug: "find-k-th-smallest-pair-distance",
    title: "Find K-th Smallest Pair Distance",
    difficulty: "Hard",
    pattern: "Binary Search",
    fn: "smallestDistancePair",
    params: [["nums", "number[]"], ["k", "number"]],
    returns: "number",
    hints: [
      "There are n(n - 1) / 2 distances: too many to list. How many pairs have distance <= d? That count grows with d.",
      "Sort nums and binary search d in [0, max - min]. Count pairs with distance <= d using a sliding left pointer; the smallest d with count >= k is the answer.",
      "sort nums\nlo = 0, hi = nums[n - 1] - nums[0]\nwhile lo < hi:\n  d = (lo + hi) div 2\n  count = 0, l = 0\n  for r from 0 to n - 1:\n    while nums[r] - nums[l] > d: l += 1\n    count += r - l\n  if count >= k: hi = d\n  else: lo = d + 1\nreturn lo",
    ],
    reference: `function smallestDistancePair(nums, k) { const a = nums.slice().sort((x, y) => x - y); let lo = 0, hi = a[a.length - 1] - a[0]; while (lo < hi) { const d = (lo + hi) >> 1; let c = 0, l = 0; for (let r = 0; r < a.length; r++) { while (a[r] - a[l] > d) l++; c += r - l; } if (c >= k) hi = d; else lo = d + 1; } return lo; }`,
    brute: `function smallestDistancePair(nums, k) { const d = []; for (let i = 0; i < nums.length; i++) for (let j = i + 1; j < nums.length; j++) d.push(Math.abs(nums[i] - nums[j])); return d.sort((x, y) => x - y)[k - 1]; }`,
    fuzz: gen(`const a = __arr(rand, __r(rand, 2, 9), 0, 20); return [a, __r(rand, 1, (a.length * (a.length - 1)) / 2)];`),
    examples: [[[1, 3, 1], 1], [[1, 1, 1], 2]],
    edges: [
      ["two", [[1, 6], 1]],
      ["boundary", [[1, 6, 1], 3], "k is the last pair: the largest distance."],
      ["duplicates", [[9, 10, 7, 10, 6, 1, 5, 4, 9, 8], 18]],
    ],
  },
];

export const LADDER_BINARY_SEARCH_SEEDED: ProblemSpec[] = DEFS.map((d) => define(d).spec);
