import { define, type ProblemDef } from "../../dsa-extras/define";
import { gen } from "../../dsa-extras/gen";
import type { ProblemSpec } from "../types";

const S: Array<[string, string]> = [["s", "string"]];
const ST: Array<[string, string]> = [["s", "string"], ["t", "string"]];

/** Judges for seeded LeetCode problems that the Strings Ladder points at. LeetCode's own signatures. */
const DEFS: ProblemDef[] = [
  {
    slug: "length-of-last-word",
    title: "Length of Last Word",
    difficulty: "Easy",
    pattern: "Arrays & Hashing",
    fn: "lengthOfLastWord",
    params: S,
    returns: "number",
    hints: [
      "The last word ends at the last non-space character. Where should you start reading?",
      "Scan from the end: skip trailing spaces, then count characters until you hit a space or the start of the string.",
      "i = n - 1\nwhile s[i] == ' ': i -= 1\nlength = 0\nwhile i >= 0 and s[i] != ' ':\n  length += 1\n  i -= 1\nreturn length",
    ],
    reference: `function lengthOfLastWord(s) { let i = s.length - 1; while (s[i] === " ") i--; let n = 0; while (i >= 0 && s[i] !== " ") { n++; i--; } return n; }`,
    brute: `function lengthOfLastWord(s) { const w = s.split(" ").filter(Boolean); return w[w.length - 1].length; }`,
    fuzz: gen(`return [" ".repeat(__r(rand, 0, 2)) + __str(rand, __r(rand, 1, 6), "ab") + __str(rand, __r(rand, 0, 8), "ab  ") + "x" + " ".repeat(__r(rand, 0, 3))];`),
    examples: [["Hello World"], ["   fly me   to   the moon  "]],
    edges: [
      ["single-char", ["a"]],
      ["boundary", ["day   "], "Trailing spaces: the last word is still 'day'."],
      ["single", ["   a"], "One word after leading spaces."],
    ],
  },
  {
    slug: "isomorphic-strings",
    title: "Isomorphic Strings",
    difficulty: "Easy",
    pattern: "Arrays & Hashing",
    fn: "isIsomorphic",
    params: ST,
    returns: "boolean",
    hints: [
      "A mapping s -> t must be consistent, but that alone isn't enough. Can two different letters of s map to the same letter of t?",
      "Keep two maps, s-to-t and t-to-s. At each index, if either map already holds a different partner, the strings aren't isomorphic.",
      "for i from 0 to n - 1:\n  a = s[i], b = t[i]\n  if a in st and st[a] != b: return false\n  if b in ts and ts[b] != a: return false\n  st[a] = b\n  ts[b] = a\nreturn true",
    ],
    reference: `function isIsomorphic(s, t) { const a = new Map(), b = new Map(); for (let i = 0; i < s.length; i++) { const x = s[i], y = t[i]; if (a.has(x) && a.get(x) !== y) return false; if (b.has(y) && b.get(y) !== x) return false; a.set(x, y); b.set(y, x); } return true; }`,
    brute: `function isIsomorphic(s, t) { for (let i = 0; i < s.length; i++) for (let j = 0; j < s.length; j++) if ((s[i] === s[j]) !== (t[i] === t[j])) return false; return true; }`,
    fuzz: gen(`const n = __r(rand, 1, 8); return [__str(rand, n, "abc"), __str(rand, n, "xyz")];`),
    examples: [["egg", "add"], ["foo", "bar"]],
    edges: [
      ["single-char", ["a", "b"]],
      ["duplicates", ["badc", "baba"], "Two letters of s can't share one letter of t."],
      ["two", ["ab", "aa"], "Two different letters can't both map to 'a'."],
    ],
  },
  {
    slug: "word-pattern",
    title: "Word Pattern",
    difficulty: "Easy",
    pattern: "Arrays & Hashing",
    fn: "wordPattern",
    params: [["pattern", "string"], ["s", "string"]],
    returns: "boolean",
    hints: [
      "Split s into words first. If the counts differ from the pattern length, can it ever match?",
      "It's isomorphic strings with words: keep a letter-to-word map and a word-to-letter map and reject any conflicting pair.",
      "words = s split on spaces\nif len(words) != len(pattern): return false\nfor i from 0 to len(words) - 1:\n  p = pattern[i], w = words[i]\n  if p in pw and pw[p] != w: return false\n  if w in wp and wp[w] != p: return false\n  pw[p] = w\n  wp[w] = p\nreturn true",
    ],
    reference: `function wordPattern(pattern, s) { const w = s.split(" "); if (w.length !== pattern.length) return false; const a = new Map(), b = new Map(); for (let i = 0; i < w.length; i++) { const p = pattern[i]; if (a.has(p) && a.get(p) !== w[i]) return false; if (b.has(w[i]) && b.get(w[i]) !== p) return false; a.set(p, w[i]); b.set(w[i], p); } return true; }`,
    brute: `function wordPattern(pattern, s) { const w = s.split(" "); if (w.length !== pattern.length) return false; for (let i = 0; i < w.length; i++) for (let j = 0; j < w.length; j++) if ((pattern[i] === pattern[j]) !== (w[i] === w[j])) return false; return true; }`,
    fuzz: gen(`const n = __r(rand, 1, 6); const words = ["dog", "cat", "fish"]; const m = rand() < 0.2 ? n + 1 : n; return [__str(rand, n, "ab"), Array.from({ length: m }, () => __pick(rand, words)).join(" ")];`),
    examples: [["abba", "dog cat cat dog"], ["abba", "dog cat cat fish"]],
    edges: [
      ["duplicates", ["abba", "dog dog dog dog"], "Two letters can't map to the same word."],
      ["no-answer", ["aaa", "dog dog"], "Different counts can never match."],
      ["single-char", ["a", "dog"]],
    ],
  },
  {
    slug: "longest-palindrome",
    title: "Longest Palindrome",
    difficulty: "Easy",
    pattern: "Arrays & Hashing",
    fn: "longestPalindrome",
    params: S,
    returns: "number",
    hints: [
      "A palindrome uses letters in mirrored pairs, plus at most one letter alone in the middle.",
      "Count every letter. Each count contributes its largest even part; if any count was odd, add 1 for the centre.",
      "count each character\nlength = 0, odd = false\nfor each c in counts:\n  length += c - (c mod 2)\n  if c is odd: odd = true\nreturn length + (1 if odd else 0)",
    ],
    reference: `function longestPalindrome(s) { const c = {}; for (const ch of s) c[ch] = (c[ch] || 0) + 1; let n = 0, odd = false; for (const k in c) { n += c[k] - (c[k] % 2); if (c[k] % 2) odd = true; } return n + (odd ? 1 : 0); }`,
    brute: `function longestPalindrome(s) { const seen = new Set(); let pairs = 0; for (const ch of s) { if (seen.has(ch)) { seen.delete(ch); pairs++; } else seen.add(ch); } return pairs * 2 + (seen.size ? 1 : 0); }`,
    fuzz: gen(`return [__str(rand, __r(rand, 1, 16), "abcAB")];`),
    examples: [["abccccdd"], ["a"]],
    edges: [
      ["case-mix", ["Aa"], "Case-sensitive: 'A' and 'a' don't pair."],
      ["all-equal", ["bbbbb"]],
      ["duplicates", ["aabbcc"], "All counts even: no centre letter is needed."],
    ],
  },
  {
    slug: "ransom-note",
    title: "Ransom Note",
    difficulty: "Easy",
    pattern: "Arrays & Hashing",
    fn: "canConstruct",
    params: [["ransomNote", "string"], ["magazine", "string"]],
    returns: "boolean",
    hints: [
      "Each magazine letter can be used once. What do you need to know about the magazine before reading the note?",
      "Count the magazine's letters, then spend them on the note. If any letter runs out, the note can't be built.",
      "count each character of magazine\nfor each ch in ransomNote:\n  if count[ch] == 0: return false\n  count[ch] -= 1\nreturn true",
    ],
    reference: `function canConstruct(ransomNote, magazine) { const c = {}; for (const ch of magazine) c[ch] = (c[ch] || 0) + 1; for (const ch of ransomNote) { if (!c[ch]) return false; c[ch]--; } return true; }`,
    brute: `function canConstruct(ransomNote, magazine) { const m = magazine.split(""); for (const ch of ransomNote) { const i = m.indexOf(ch); if (i < 0) return false; m.splice(i, 1); } return true; }`,
    fuzz: gen(`return [__str(rand, __r(rand, 1, 6), "abc"), __str(rand, __r(rand, 1, 10), "abc")];`),
    examples: [["a", "b"], ["aa", "aab"]],
    edges: [
      ["duplicates", ["aa", "ab"], "Each magazine letter can be used only once."],
      ["single-char", ["z", "z"]],
      ["boundary", ["abc", "cba"], "The magazine has exactly the letters needed."],
    ],
  },
  {
    slug: "sort-characters-by-frequency",
    title: "Sort Characters By Frequency",
    difficulty: "Medium",
    pattern: "Heap / Priority Queue",
    fn: "frequencySort",
    params: S,
    returns: "string",
    hints: [
      "First find how often each character appears. Then the question is only about ordering those characters.",
      "Count the characters, sort the distinct characters by count (highest first), and append each one repeated count times. Bucket sort by count avoids the sort entirely.",
      "count each character\nchars = distinct characters sorted by count, descending\nout = \"\"\nfor each ch in chars:\n  out += ch repeated count[ch] times\nreturn out",
    ],
    reference: `function frequencySort(s) { const c = new Map(); for (const ch of s) c.set(ch, (c.get(ch) || 0) + 1); return [...c.entries()].sort((a, b) => b[1] - a[1]).map(([ch, n]) => ch.repeat(n)).join(""); }`,
    brute: `function frequencySort(s) { const c = {}; for (const ch of s) c[ch] = (c[ch] || 0) + 1; return s.split("").sort((a, b) => c[b] - c[a] || (a < b ? -1 : a > b ? 1 : 0)).join(""); }`,
    fuzz: gen(`const pool = __shuffle(rand, "abcdeXY12".split("")).slice(0, __r(rand, 1, 4)); const counts = __shuffle(rand, [1, 2, 3, 4, 5]).slice(0, pool.length); let s = ""; pool.forEach((ch, i) => { s += ch.repeat(counts[i]); }); return [__shuffle(rand, s.split("")).join("")];`),
    examples: [["zyzyz"], ["cccaab"]],
    edges: [
      ["single-char", ["a"]],
      ["all-equal", ["bbbb"]],
      ["case-mix", ["aAaaA"], "'A' and 'a' are different characters with different counts."],
    ],
  },
  {
    slug: "determine-if-two-strings-are-close",
    title: "Determine if Two Strings Are Close",
    difficulty: "Medium",
    pattern: "Arrays & Hashing",
    fn: "closeStrings",
    params: [["word1", "string"], ["word2", "string"]],
    returns: "boolean",
    hints: [
      "Swapping positions lets you reorder freely. Swapping letter identities lets you trade counts between letters. What can never change?",
      "Both words must use the same set of letters, and the multiset of counts must match (sort the count lists and compare).",
      "if len(word1) != len(word2): return false\nc1 = counts of word1, c2 = counts of word2\nif keys of c1 != keys of c2: return false\nreturn sorted values of c1 == sorted values of c2",
    ],
    reference: `function closeStrings(word1, word2) { if (word1.length !== word2.length) return false; const a = new Array(26).fill(0), b = new Array(26).fill(0); for (const c of word1) a[c.charCodeAt(0) - 97]++; for (const c of word2) b[c.charCodeAt(0) - 97]++; for (let i = 0; i < 26; i++) if ((a[i] === 0) !== (b[i] === 0)) return false; a.sort((x, y) => x - y); b.sort((x, y) => x - y); return a.every((v, i) => v === b[i]); }`,
    brute: `function closeStrings(word1, word2) { const f = (w) => { const m = {}; for (const c of w) m[c] = (m[c] || 0) + 1; return m; }; const a = f(word1), b = f(word2); const ka = Object.keys(a).sort().join(), kb = Object.keys(b).sort().join(); if (ka !== kb) return false; return Object.values(a).sort((x, y) => x - y).join() === Object.values(b).sort((x, y) => x - y).join(); }`,
    fuzz: gen(`const n = __r(rand, 1, 8); const a = __str(rand, n, "abc"); const b = rand() < 0.5 ? __shuffle(rand, a.split("")).join("") : __str(rand, __r(rand, n - 1, n), "abcd"); return [a, b.length ? b : "a"];`),
    examples: [["abc", "bca"], ["a", "aa"]],
    edges: [
      ["duplicates", ["cabbba", "abbccc"], "Counts {1,2,3} can be traded between letters."],
      ["no-answer", ["uau", "ssx"], "Different letter sets can never be made equal."],
      ["single-char", ["a", "b"]],
    ],
  },
  {
    slug: "minimum-number-of-steps-to-make-two-strings-anagram",
    title: "Minimum Number of Steps to Make Two Strings Anagram",
    difficulty: "Medium",
    pattern: "Arrays & Hashing",
    fn: "minSteps",
    params: ST,
    returns: "number",
    hints: [
      "You only replace characters in t. Which characters of t are already fine?",
      "Count s, subtract t's characters. Every count that stays positive is a character t is missing; the sum of those surpluses is the answer.",
      "count = counts of s\nfor each ch in t: count[ch] -= 1\nsteps = 0\nfor each c in count:\n  if c > 0: steps += c\nreturn steps",
    ],
    reference: `function minSteps(s, t) { const c = new Array(26).fill(0); for (const ch of s) c[ch.charCodeAt(0) - 97]++; for (const ch of t) c[ch.charCodeAt(0) - 97]--; return c.reduce((a, v) => a + (v > 0 ? v : 0), 0); }`,
    brute: `function minSteps(s, t) { const m = t.split(""); let keep = 0; for (const ch of s) { const i = m.indexOf(ch); if (i >= 0) { m.splice(i, 1); keep++; } } return s.length - keep; }`,
    fuzz: gen(`const n = __r(rand, 1, 10); return [__str(rand, n, "abc"), __str(rand, n, "abcd")];`),
    examples: [["bab", "aba"], ["leetcode", "practice"]],
    edges: [
      ["all-equal", ["anagram", "mangaar"], "Already anagrams: 0 steps."],
      ["single-char", ["a", "b"]],
      ["no-answer", ["aaa", "bbb"], "Nothing in common: every character must change."],
    ],
  },
  {
    slug: "merge-strings-alternately",
    title: "Merge Strings Alternately",
    difficulty: "Easy",
    pattern: "Two Pointers",
    fn: "mergeAlternately",
    params: [["word1", "string"], ["word2", "string"]],
    returns: "string",
    hints: [
      "Walk both strings with the same index. What happens once the shorter one runs out?",
      "Loop i up to the longer length; append word1[i] if it exists, then word2[i] if it exists.",
      "out = \"\"\nfor i from 0 to max(len(word1), len(word2)) - 1:\n  if i < len(word1): out += word1[i]\n  if i < len(word2): out += word2[i]\nreturn out",
    ],
    reference: `function mergeAlternately(word1, word2) { let out = ""; for (let i = 0; i < Math.max(word1.length, word2.length); i++) { if (i < word1.length) out += word1[i]; if (i < word2.length) out += word2[i]; } return out; }`,
    brute: `function mergeAlternately(word1, word2) { const a = word1.split(""), b = word2.split(""); let out = ""; while (a.length || b.length) { if (a.length) out += a.shift(); if (b.length) out += b.shift(); } return out; }`,
    fuzz: gen(`return [__str(rand, __r(rand, 1, 7), "abc"), __str(rand, __r(rand, 1, 7), "xyz")];`),
    examples: [["abc", "pqr"], ["ab", "pqrs"]],
    edges: [
      ["boundary", ["abcd", "pq"], "word1 is longer: its tail is appended."],
      ["single-char", ["a", "z"]],
      ["two", ["ab", "x"]],
    ],
  },
  {
    slug: "backspace-string-compare",
    title: "Backspace String Compare",
    difficulty: "Easy",
    pattern: "Two Pointers",
    fn: "backspaceCompare",
    params: ST,
    returns: "boolean",
    hints: [
      "Build what each string types out, treating '#' as delete-the-last-character. A stack does exactly that.",
      "For O(1) space, walk both strings from the end, skipping characters that a later '#' deletes, and compare the surviving characters one by one.",
      "build(x):\n  stack = []\n  for each ch in x:\n    if ch == '#': pop from stack if it isn't empty\n    else: push ch\n  return stack joined\nreturn build(s) == build(t)",
    ],
    reference: `function backspaceCompare(s, t) { let i = s.length - 1, j = t.length - 1; for (;;) { let k = 0; while (i >= 0 && (k || s[i] === "#")) { k += s[i] === "#" ? 1 : -1; i--; } k = 0; while (j >= 0 && (k || t[j] === "#")) { k += t[j] === "#" ? 1 : -1; j--; } if (i < 0 || j < 0) return i < 0 && j < 0; if (s[i] !== t[j]) return false; i--; j--; } }`,
    brute: `function backspaceCompare(s, t) { const b = (x) => { const st = []; for (const c of x) { if (c === "#") st.pop(); else st.push(c); } return st.join(""); }; return b(s) === b(t); }`,
    fuzz: gen(`return [__str(rand, __r(rand, 1, 8), "ab#"), __str(rand, __r(rand, 1, 8), "ab#")];`),
    examples: [["ab#c", "ad#c"], ["a#c", "b"]],
    edges: [
      ["boundary", ["ab##", "c#d#"], "Both type out the empty string."],
      ["extremes", ["###a", "a"], "Backspace on an empty text does nothing."],
      ["single-char", ["a", "b"]],
    ],
  },
  {
    slug: "reverse-words-in-a-string",
    title: "Reverse Words in a String",
    difficulty: "Medium",
    pattern: "Two Pointers",
    fn: "reverseWords",
    params: S,
    returns: "string",
    hints: [
      "Extra spaces anywhere must vanish in the answer. What are the real units you reorder?",
      "Collect the words (runs of non-space characters) scanning left to right, then join them in reverse order with single spaces.",
      "words = []\ni = 0\nwhile i < n:\n  skip spaces\n  read characters until a space into word\n  if word is not empty: add word to words\nreturn words in reverse order joined by ' '",
    ],
    reference: `function reverseWords(s) { const w = []; let i = 0; while (i < s.length) { while (i < s.length && s[i] === " ") i++; let j = i; while (j < s.length && s[j] !== " ") j++; if (j > i) w.push(s.slice(i, j)); i = j; } let out = ""; for (let k = w.length - 1; k >= 0; k--) out += (out ? " " : "") + w[k]; return out; }`,
    brute: `function reverseWords(s) { return s.trim().split(/\\s+/).reverse().join(" "); }`,
    fuzz: gen(`return [__str(rand, __r(rand, 0, 2), " ") + __str(rand, __r(rand, 1, 14), "abc  ") + "d" + __str(rand, __r(rand, 0, 2), " ")];`),
    examples: [["the sky is blue"], ["  hello world  "]],
    edges: [
      ["single-char", ["a"]],
      ["duplicates", ["a good   example"], "Several spaces between words collapse to one."],
      ["all-equal", ["  x  "], "One word with spaces around it."],
    ],
  },
  {
    slug: "string-compression",
    title: "String Compression",
    difficulty: "Medium",
    pattern: "Two Pointers",
    fn: "compress",
    params: [["chars", "character[]"]],
    returns: "number",
    returnKind: "arg0Prefix",
    hints: [
      "Read a whole run of equal characters before writing anything. Where can you write without overwriting unread input?",
      "Keep a read pointer and a write pointer. For each run, write the character, then the run length's digits if the length is more than 1. The write pointer never passes the read pointer.",
      "write = 0, read = 0\nwhile read < n:\n  ch = chars[read], start = read\n  while read < n and chars[read] == ch: read += 1\n  chars[write] = ch; write += 1\n  if read - start > 1:\n    for each digit d of (read - start):\n      chars[write] = d; write += 1\nreturn write",
    ],
    reference: `function compress(chars) { let w = 0, r = 0; while (r < chars.length) { const ch = chars[r], st = r; while (r < chars.length && chars[r] === ch) r++; chars[w++] = ch; if (r - st > 1) for (const d of String(r - st)) chars[w++] = d; } return w; }`,
    brute: `function compress(chars) { let s = "", i = 0; while (i < chars.length) { let j = i; while (j < chars.length && chars[j] === chars[i]) j++; s += chars[i] + (j - i > 1 ? String(j - i) : ""); i = j; } for (let k = 0; k < s.length; k++) chars[k] = s[k]; return s.length; }`,
    fuzz: gen(`const out = []; const runs = __r(rand, 1, 4); for (let i = 0; i < runs; i++) { const ch = __pick(rand, ["a", "b", "c"]); const len = __pick(rand, [1, 1, 2, 3, 12]); for (let k = 0; k < len; k++) out.push(ch); } return [out];`),
    examples: [[["a", "a", "b", "b", "c", "c", "c"]], [["a"]]],
    edges: [
      ["large", [["a", "b", "b", "b", "b", "b", "b", "b", "b", "b", "b", "b", "b"]], "A run of 12 writes two digits."],
      ["all-equal", [["z", "z", "z"]]],
      ["duplicates", [["a", "a", "b", "a", "a"]], "Separate runs of the same character are compressed separately."],
    ],
  },
  {
    slug: "rotate-string",
    title: "Rotate String",
    difficulty: "Easy",
    pattern: "Two Pointers",
    fn: "rotateString",
    params: [["s", "string"], ["goal", "string"]],
    returns: "boolean",
    hints: [
      "Every rotation of s appears somewhere inside one particular string built from s. Which one?",
      "If the lengths match, goal is a rotation of s exactly when goal occurs inside s + s.",
      "if len(s) != len(goal): return false\nreturn goal occurs inside s + s",
    ],
    reference: `function rotateString(s, goal) { return s.length === goal.length && (s + s).includes(goal); }`,
    brute: `function rotateString(s, goal) { if (s.length !== goal.length) return false; for (let k = 0; k < s.length; k++) if (s.slice(k) + s.slice(0, k) === goal) return true; return s === goal; }`,
    fuzz: gen(`const s = __str(rand, __r(rand, 1, 8), "ab"); const k = __r(rand, 0, s.length - 1); const rot = s.slice(k) + s.slice(0, k); return [s, rand() < 0.5 ? rot : __str(rand, __r(rand, s.length - 1, s.length), "ab") || "a"];`),
    examples: [["abcde", "cdeab"], ["abcde", "abced"]],
    edges: [
      ["no-answer", ["aa", "a"], "Different lengths are never rotations."],
      ["single-char", ["a", "a"]],
      ["duplicates", ["abab", "baba"]],
    ],
  },
  {
    slug: "find-the-index-of-the-first-occurrence-in-a-string",
    title: "Find the Index of the First Occurrence in a String",
    difficulty: "Easy",
    pattern: "Two Pointers",
    fn: "strStr",
    params: [["haystack", "string"], ["needle", "string"]],
    returns: "number",
    hints: [
      "Try every starting index of haystack. How many characters do you need to compare at each one?",
      "For each start i up to n - m, compare needle against haystack from i; return i on the first full match, or -1 after the loop. KMP removes the re-comparisons.",
      "for i from 0 to n - m:\n  j = 0\n  while j < m and haystack[i + j] == needle[j]: j += 1\n  if j == m: return i\nreturn -1",
    ],
    reference: `function strStr(haystack, needle) { for (let i = 0; i + needle.length <= haystack.length; i++) { let j = 0; while (j < needle.length && haystack[i + j] === needle[j]) j++; if (j === needle.length) return i; } return -1; }`,
    brute: `function strStr(haystack, needle) { return haystack.indexOf(needle); }`,
    fuzz: gen(`return [__str(rand, __r(rand, 1, 12), "ab"), __str(rand, __r(rand, 1, 3), "ab")];`),
    examples: [["sadbutsad", "sad"], ["leetcode", "leeto"]],
    edges: [
      ["boundary", ["hello", "lo"], "The match ends at the last character."],
      ["no-answer", ["a", "aa"], "The needle is longer than the haystack."],
      ["duplicates", ["aaaab", "aab"], "A false start overlaps the real match."],
    ],
  },
  {
    slug: "integer-to-roman",
    title: "Integer to Roman",
    difficulty: "Medium",
    pattern: "Arrays & Hashing",
    fn: "intToRoman",
    params: [["num", "number"]],
    returns: "string",
    hints: [
      "Include the subtractive forms (CM, CD, XC, XL, IX, IV) as symbols of their own. Then is a greedy choice always right?",
      "Walk the 13 values from 1000 down to 1. While num is at least the value, append its symbol and subtract.",
      "values = [1000, 900, 500, 400, 100, 90, 50, 40, 10, 9, 5, 4, 1]\nsymbols = [M, CM, D, CD, C, XC, L, XL, X, IX, V, IV, I]\nout = \"\"\nfor i from 0 to 12:\n  while num >= values[i]:\n    out += symbols[i]\n    num -= values[i]\nreturn out",
    ],
    reference: `function intToRoman(num) { const v = [1000, 900, 500, 400, 100, 90, 50, 40, 10, 9, 5, 4, 1], s = ["M", "CM", "D", "CD", "C", "XC", "L", "XL", "X", "IX", "V", "IV", "I"]; let out = ""; for (let i = 0; i < v.length; i++) while (num >= v[i]) { out += s[i]; num -= v[i]; } return out; }`,
    brute: `function intToRoman(num) { const th = ["", "M", "MM", "MMM"], h = ["", "C", "CC", "CCC", "CD", "D", "DC", "DCC", "DCCC", "CM"], t = ["", "X", "XX", "XXX", "XL", "L", "LX", "LXX", "LXXX", "XC"], o = ["", "I", "II", "III", "IV", "V", "VI", "VII", "VIII", "IX"]; return th[Math.floor(num / 1000)] + h[Math.floor(num / 100) % 10] + t[Math.floor(num / 10) % 10] + o[num % 10]; }`,
    fuzz: gen(`return [__r(rand, 1, 3999)];`),
    examples: [[3749], [58]],
    edges: [
      ["min-size", [1]],
      ["extremes", [3999], "The largest value: MMMCMXCIX."],
      ["boundary", [1994], "Uses three subtractive pairs: CM, XC and IV."],
    ],
  },
  {
    slug: "string-to-integer-atoi",
    title: "String to Integer (atoi)",
    difficulty: "Medium",
    pattern: "Arrays & Hashing",
    fn: "myAtoi",
    params: S,
    returns: "number",
    hints: [
      "Process the string in stages: leading spaces, an optional sign, then digits. What stops the digit stage?",
      "Skip spaces, read one '+' or '-', then accumulate digits until a non-digit. Clamp the result to [-2^31, 2^31 - 1] as you go so it never grows unbounded.",
      "i = 0, sign = 1, result = 0\nskip spaces\nif s[i] is '+' or '-': set sign, i += 1\nwhile s[i] is a digit:\n  result = result * 10 + digit\n  if result exceeds 2^31: stop growing it\n  i += 1\nresult = sign * result\nreturn result clamped to [-2^31, 2^31 - 1]",
    ],
    reference: `function myAtoi(s) { let i = 0, sign = 1, r = 0; while (s[i] === " ") i++; if (s[i] === "+" || s[i] === "-") { if (s[i] === "-") sign = -1; i++; } while (i < s.length && s[i] >= "0" && s[i] <= "9") { r = r * 10 + (s.charCodeAt(i) - 48); if (r > 2147483648) r = 2147483648; i++; } r *= sign; if (r > 2147483647) return 2147483647; if (r < -2147483648) return -2147483648; return r === 0 ? 0 : r; }`,
    brute: `function myAtoi(s) { const m = s.match(/^ *([+-]?\\d+)/); if (!m) return 0; const v = BigInt(m[1]); const hi = 2147483647n, lo = -2147483648n; const c = v > hi ? hi : v < lo ? lo : v; return Number(c) === 0 ? 0 : Number(c); }`,
    fuzz: gen(`const parts = [" ".repeat(__r(rand, 0, 2)), __pick(rand, ["", "", "+", "-", "+-"]), __str(rand, __r(rand, 0, 12), "0123456789"), __pick(rand, ["", "abc", " 12", "."])]; return [parts.join("")];`),
    examples: [["42"], [" -042"]],
    edges: [
      ["no-answer", ["words and 987"], "Starts with a letter: return 0."],
      ["extremes", ["-91283472332"], "Below -2^31: clamp."],
      ["boundary", ["1337c0d3"], "Stop at the first non-digit."],
      ["empty", [""]],
    ],
  },
  {
    slug: "count-and-say",
    title: "Count and Say",
    difficulty: "Medium",
    pattern: "Arrays & Hashing",
    fn: "countAndSay",
    params: [["n", "number"]],
    returns: "string",
    hints: [
      "Each term describes the previous one run by run. Start from \"1\" and build forward.",
      "Repeat n - 1 times: scan the current term, and for every run of equal digits append the run length followed by the digit.",
      "term = \"1\"\nrepeat n - 1 times:\n  next = \"\"\n  for each run of equal digits d with length k in term:\n    next += k as text + d\n  term = next\nreturn term",
    ],
    reference: `function countAndSay(n) { let t = "1"; for (let k = 1; k < n; k++) { let nx = "", i = 0; while (i < t.length) { let j = i; while (j < t.length && t[j] === t[i]) j++; nx += String(j - i) + t[i]; i = j; } t = nx; } return t; }`,
    brute: `function countAndSay(n) { let t = "1"; for (let k = 1; k < n; k++) t = t.replace(/(\\d)\\1*/g, (m) => m.length + m[0]); return t; }`,
    fuzz: gen(`return [__r(rand, 1, 15)];`),
    examples: [[4], [1]],
    edges: [
      ["min-size", [2], "\"1\" is one 1: \"11\"."],
      ["boundary", [5]],
      ["large", [12]],
    ],
  },
  {
    slug: "multiply-strings",
    title: "Multiply Strings",
    difficulty: "Medium",
    pattern: "Math & Geometry",
    fn: "multiply",
    params: [["num1", "string"], ["num2", "string"]],
    returns: "string",
    hints: [
      "Do long multiplication by hand. Where does the product of digit i of num1 and digit j of num2 land?",
      "Use an array of length m + n. The product of num1[i] and num2[j] adds into position i + j + 1, with the carry going to i + j. Strip leading zeros at the end.",
      "pos = array of m + n zeros\nfor i from m - 1 down to 0:\n  for j from n - 1 down to 0:\n    sum = num1[i] * num2[j] + pos[i + j + 1]\n    pos[i + j + 1] = sum mod 10\n    pos[i + j] += sum div 10\nremove leading zeros from pos\nreturn digits of pos, or \"0\" if none remain",
    ],
    reference: `function multiply(num1, num2) { const m = num1.length, n = num2.length, p = new Array(m + n).fill(0); for (let i = m - 1; i >= 0; i--) for (let j = n - 1; j >= 0; j--) { const s = (num1.charCodeAt(i) - 48) * (num2.charCodeAt(j) - 48) + p[i + j + 1]; p[i + j + 1] = s % 10; p[i + j] += Math.floor(s / 10); } let k = 0; while (k < p.length - 1 && p[k] === 0) k++; return p.slice(k).join(""); }`,
    brute: `function multiply(num1, num2) { return (BigInt(num1) * BigInt(num2)).toString(); }`,
    fuzz: gen(`const num = () => rand() < 0.1 ? "0" : String(__r(rand, 1, 9)) + __str(rand, __r(rand, 0, 14), "0123456789"); return [num(), num()];`),
    examples: [["2", "3"], ["123", "456"]],
    edges: [
      ["zeros", ["0", "52"], "Anything times 0 is \"0\", not \"00\"."],
      ["large", ["99999999999999999999", "99999999999999999999"], "Far beyond Number precision: no parseInt."],
      ["single-char", ["9", "9"]],
    ],
  },
  {
    slug: "remove-all-adjacent-duplicates-in-string",
    title: "Remove All Adjacent Duplicates In String",
    difficulty: "Easy",
    pattern: "Stack & Monotonic Stack",
    fn: "removeDuplicates",
    params: S,
    returns: "string",
    hints: [
      "Removing a pair can make two new characters adjacent. What structure lets you look at the last kept character instantly?",
      "Use a stack of kept characters. If the next character equals the top, pop; otherwise push. The stack, bottom to top, is the answer.",
      "stack = []\nfor each ch in s:\n  if stack is not empty and top of stack == ch: pop\n  else: push ch\nreturn stack joined",
    ],
    reference: `function removeDuplicates(s) { const st = []; for (const c of s) { if (st.length && st[st.length - 1] === c) st.pop(); else st.push(c); } return st.join(""); }`,
    brute: `function removeDuplicates(s) { let prev; do { prev = s; s = s.replace(/(.)\\1/, ""); } while (s !== prev); return s; }`,
    fuzz: gen(`return [__str(rand, __r(rand, 1, 14), "abc")];`),
    examples: [["abbaca"], ["azxxzy"]],
    edges: [
      ["two", ["aa"], "Everything cancels: return the empty string."],
      ["single-char", ["a"]],
      ["all-equal", ["aaa"], "Pairs cancel; one 'a' is left over."],
    ],
  },
  {
    slug: "removing-stars-from-a-string",
    title: "Removing Stars From a String",
    difficulty: "Medium",
    pattern: "Stack & Monotonic Stack",
    fn: "removeStars",
    params: S,
    returns: "string",
    hints: [
      "Each star deletes the closest kept character to its left. That's the most recently kept one.",
      "Push letters onto a stack; on '*', pop. Join the stack at the end.",
      "stack = []\nfor each ch in s:\n  if ch == '*': pop\n  else: push ch\nreturn stack joined",
    ],
    reference: `function removeStars(s) { const st = []; for (const c of s) { if (c === "*") st.pop(); else st.push(c); } return st.join(""); }`,
    brute: `function removeStars(s) { let prev; do { prev = s; s = s.replace(/[a-z]\\*/, ""); } while (s !== prev); return s; }`,
    fuzz: gen(`let s = "", letters = 0; const n = __r(rand, 1, 14); for (let i = 0; i < n; i++) { if (letters > 0 && rand() < 0.35) { s += "*"; letters--; } else { s += __pick(rand, ["a", "b", "c"]); letters++; } } return [s];`),
    examples: [["leet**cod*e"], ["erase*****"]],
    edges: [
      ["single-char", ["a"]],
      ["boundary", ["ab*"], "The star removes the last letter."],
      ["all-equal", ["abc"], "No stars: nothing changes."],
    ],
  },
  {
    slug: "minimum-add-to-make-parentheses-valid",
    title: "Minimum Add to Make Parentheses Valid",
    difficulty: "Medium",
    pattern: "Greedy",
    fn: "minAddToMakeValid",
    params: S,
    returns: "number",
    hints: [
      "Scan left to right keeping the number of currently open brackets. When does a ')' force an insertion?",
      "Track open. On '(' increment it. On ')' decrement it if it's positive, otherwise you must insert a '(' (count it). At the end, every still-open bracket needs a ')'.",
      "open = 0, inserts = 0\nfor each ch in s:\n  if ch == '(': open += 1\n  else if open > 0: open -= 1\n  else: inserts += 1\nreturn inserts + open",
    ],
    reference: `function minAddToMakeValid(s) { let o = 0, add = 0; for (const c of s) { if (c === "(") o++; else if (o) o--; else add++; } return add + o; }`,
    brute: `function minAddToMakeValid(s) { let prev; do { prev = s; s = s.replace("()", ""); } while (s !== prev); return s.length; }`,
    fuzz: gen(`return [__str(rand, __r(rand, 1, 14), "()")];`),
    examples: [["())"], ["((("]],
    edges: [
      ["all-equal", ["()()"], "Already valid: 0 insertions."],
      ["reverse-sorted", [")))((("], "Closers before openers: each needs its own partner."],
      ["single-char", [")"]],
    ],
  },
  {
    slug: "maximum-number-of-vowels-in-a-substring-of-given-length",
    title: "Maximum Number of Vowels in a Substring of Given Length",
    difficulty: "Medium",
    pattern: "Sliding Window",
    fn: "maxVowels",
    params: [["s", "string"], ["k", "number"]],
    returns: "number",
    hints: [
      "All windows have the same length k. When the window moves one step, which two characters change the count?",
      "Count vowels in the first k characters, then slide: add 1 if the entering character is a vowel, subtract 1 if the leaving one was. Track the maximum.",
      "count = vowels in s[0..k-1]\nbest = count\nfor i from k to n - 1:\n  if s[i] is a vowel: count += 1\n  if s[i - k] is a vowel: count -= 1\n  best = max(best, count)\nreturn best",
    ],
    reference: `function maxVowels(s, k) { const v = (c) => "aeiou".includes(c); let c = 0; for (let i = 0; i < k; i++) if (v(s[i])) c++; let best = c; for (let i = k; i < s.length; i++) { if (v(s[i])) c++; if (v(s[i - k])) c--; if (c > best) best = c; } return best; }`,
    brute: `function maxVowels(s, k) { let best = 0; for (let i = 0; i + k <= s.length; i++) best = Math.max(best, (s.slice(i, i + k).match(/[aeiou]/g) || []).length); return best; }`,
    fuzz: gen(`const n = __r(rand, 1, 14); return [__str(rand, n, "aeibcd"), __r(rand, 1, n)];`),
    examples: [["abciiidef", 3], ["aeiou", 2]],
    edges: [
      ["no-answer", ["rhythms", 4], "No vowels anywhere: 0."],
      ["boundary", ["tryhard", 7], "k = n: the only window is the whole string."],
      ["single-char", ["e", 1]],
    ],
  },
  {
    slug: "number-of-substrings-containing-all-three-characters",
    title: "Number of Substrings Containing All Three Characters",
    difficulty: "Medium",
    pattern: "Sliding Window",
    fn: "numberOfSubstrings",
    params: S,
    returns: "number",
    hints: [
      "If s[i..j] already contains a, b and c, what about every longer substring that starts at i?",
      "For each right end j, track the last positions of a, b and c. Every start up to the smallest of those three positions works, so add min(last) + 1.",
      "last = {a: -1, b: -1, c: -1}\ncount = 0\nfor j from 0 to n - 1:\n  last[s[j]] = j\n  count += min(last[a], last[b], last[c]) + 1\nreturn count",
    ],
    reference: `function numberOfSubstrings(s) { const last = { a: -1, b: -1, c: -1 }; let n = 0; for (let j = 0; j < s.length; j++) { last[s[j]] = j; n += Math.min(last.a, last.b, last.c) + 1; } return n; }`,
    brute: `function numberOfSubstrings(s) { let n = 0; for (let i = 0; i < s.length; i++) { const seen = new Set(); for (let j = i; j < s.length; j++) { seen.add(s[j]); if (seen.size === 3) n++; } } return n; }`,
    fuzz: gen(`return [__str(rand, __r(rand, 3, 14), "abc")];`),
    examples: [["abcabc"], ["aaacb"]],
    edges: [
      ["min-size", ["abc"], "Exactly one substring: the whole string."],
      ["no-answer", ["aabb"], "'c' never appears: 0."],
      ["boundary", ["cbaa"]],
    ],
  },
  {
    slug: "longest-palindromic-substring",
    title: "Longest Palindromic Substring",
    difficulty: "Medium",
    pattern: "1-D Dynamic Programming",
    fn: "longestPalindrome",
    params: S,
    returns: "string",
    hints: [
      "Every palindrome mirrors around a centre. How many possible centres does a string of length n have?",
      "Expand around each of the 2n - 1 centres (a character, or the gap between two characters) while the ends match, and keep the longest span found. Every test here has exactly one longest palindrome.",
      "best = \"\"\nfor each centre c (each index, and each gap between indices):\n  l, r = the ends of c\n  while l >= 0 and r < n and s[l] == s[r]:\n    l -= 1, r += 1\n  if r - l - 1 > len(best): best = s[l + 1 .. r - 1]\nreturn best",
    ],
    reference: `function longestPalindrome(s) { let bs = 0, bl = 0; for (let c = 0; c < 2 * s.length - 1; c++) { let l = Math.floor(c / 2), r = l + (c % 2); while (l >= 0 && r < s.length && s[l] === s[r]) { l--; r++; } if (r - l - 1 > bl) { bl = r - l - 1; bs = l + 1; } } return s.slice(bs, bs + bl); }`,
    brute: `function longestPalindrome(s) { let best = ""; for (let i = 0; i < s.length; i++) for (let j = i + 1; j <= s.length; j++) { const t = s.slice(i, j); if (t.length > best.length && t === t.split("").reverse().join("")) best = t; } return best; }`,
    fuzz: gen(`for (;;) { const s = __str(rand, __r(rand, 1, 12), "abc"); let best = 0; const found = new Set(); for (let i = 0; i < s.length; i++) for (let j = i + 1; j <= s.length; j++) { const t = s.slice(i, j); if (t === t.split("").reverse().join("")) { if (t.length > best) { best = t.length; found.clear(); } if (t.length === best) found.add(t); } } if (found.size === 1) return [s]; }`),
    examples: [["cbbd"], ["forgeeksskeegfor"]],
    edges: [
      ["single-char", ["a"]],
      ["all-equal", ["aaaa"], "The whole string is a palindrome."],
      ["boundary", ["abacdfgdcaba"], "The longest is 'aba'; the reversed-substring trick finds the wrong answer here."],
    ],
  },
  {
    slug: "palindromic-substrings",
    title: "Palindromic Substrings",
    difficulty: "Medium",
    pattern: "1-D Dynamic Programming",
    fn: "countSubstrings",
    params: S,
    returns: "number",
    hints: [
      "Count by centre instead of by substring: every palindrome has exactly one centre.",
      "Expand around each of the 2n - 1 centres; every successful expansion step is one more palindromic substring.",
      "count = 0\nfor each centre c (each index, and each gap between indices):\n  l, r = the ends of c\n  while l >= 0 and r < n and s[l] == s[r]:\n    count += 1\n    l -= 1, r += 1\nreturn count",
    ],
    reference: `function countSubstrings(s) { let n = 0; for (let c = 0; c < 2 * s.length - 1; c++) { let l = Math.floor(c / 2), r = l + (c % 2); while (l >= 0 && r < s.length && s[l] === s[r]) { n++; l--; r++; } } return n; }`,
    brute: `function countSubstrings(s) { let n = 0; for (let i = 0; i < s.length; i++) for (let j = i + 1; j <= s.length; j++) { const t = s.slice(i, j); if (t === t.split("").reverse().join("")) n++; } return n; }`,
    fuzz: gen(`return [__str(rand, __r(rand, 1, 14), "ab")];`),
    examples: [["abc"], ["aaa"]],
    edges: [
      ["single-char", ["z"]],
      ["all-equal", ["aaaa"], "n(n+1)/2 palindromes: every substring."],
      ["two", ["ab"]],
    ],
  },
];

export const LADDER_STRINGS_SEEDED: ProblemSpec[] = DEFS.map((d) => define(d).spec);
