import { define, type ProblemDef } from "../../dsa-extras/define";
import { gen } from "../../dsa-extras/gen";
import type { ProblemSpec } from "../types";

const NUMS_K: Array<[string, string]> = [["nums", "number[]"], ["k", "number"]];
const BITS = (n: string, p: number) => `Array.from({ length: ${n} }, () => (rand() < ${p} ? 1 : 0))`;
const INTERVALS = `function __ivs(rand, n) { var out = [], at = __r(rand, 0, 3); for (var i = 0; i < n; i++) { var len = __r(rand, 0, 4); out.push([at, at + len]); at += len + __r(rand, 1, 3); } return out; }`;

/** Judges for seeded LeetCode problems that the Sliding Window & Two Pointers Ladder points at. LeetCode's own signatures. */
const DEFS: ProblemDef[] = [
  {
    slug: "remove-duplicates-from-sorted-array-ii",
    title: "Remove Duplicates from Sorted Array II",
    difficulty: "Medium",
    pattern: "Two Pointers",
    fn: "removeDuplicates",
    params: [["nums", "number[]"]],
    returns: "number",
    returnKind: "arg0Prefix",
    hints: [
      "The array is sorted, so a value already kept twice would sit exactly two slots behind the write position.",
      "Keep a write pointer k. Copy nums[i] to nums[k] unless k >= 2 and nums[k - 2] equals nums[i].",
      "k = 0\nfor x in nums:\n  if k < 2 or nums[k - 2] != x:\n    nums[k] = x\n    k = k + 1\nreturn k",
    ],
    reference: `function removeDuplicates(nums) { let k = 0; for (const x of nums) if (k < 2 || nums[k - 2] !== x) nums[k++] = x; return k; }`,
    brute: `function removeDuplicates(nums) { const out = [], seen = {}; for (const x of nums) { seen[x] = (seen[x] || 0) + 1; if (seen[x] <= 2) out.push(x); } out.forEach((v, i) => { nums[i] = v; }); return out.length; }`,
    fuzz: gen(`return [__sorted(rand, __r(rand, 1, 14), -3, 3)];`),
    examples: [[[1, 1, 1, 2, 2, 3]], [[0, 0, 1, 1, 1, 1, 2, 3, 3]]],
    edges: [
      ["single", [[7]]],
      ["all-equal", [[2, 2, 2, 2, 2]], "Only two copies survive."],
      ["two", [[4, 4]]],
    ],
  },
  {
    slug: "max-consecutive-ones",
    title: "Max Consecutive Ones",
    difficulty: "Easy",
    pattern: "Sliding Window",
    fn: "findMaxConsecutiveOnes",
    params: [["nums", "number[]"]],
    returns: "number",
    hints: [
      "You only care about the current run of 1s and the best run so far.",
      "Walk once: a 1 extends the run, a 0 resets it to zero. Track the maximum after each step.",
      "best = 0, run = 0\nfor x in nums:\n  if x == 1: run = run + 1\n  else: run = 0\n  best = max(best, run)\nreturn best",
    ],
    reference: `function findMaxConsecutiveOnes(nums) { let best = 0, run = 0; for (const x of nums) { run = x === 1 ? run + 1 : 0; if (run > best) best = run; } return best; }`,
    brute: `function findMaxConsecutiveOnes(nums) { let best = 0; for (let i = 0; i < nums.length; i++) { let j = i; while (j < nums.length && nums[j] === 1) j++; best = Math.max(best, j - i); } return best; }`,
    fuzz: gen(`return [${BITS("__r(rand, 1, 30)", 0.7)}];`),
    examples: [[[1, 1, 0, 1, 1, 1]], [[1, 0, 1, 1, 0, 1]]],
    edges: [
      ["zeros", [[0, 0]], "No 1s at all: the answer is 0."],
      ["all-equal", [[1, 1, 1, 1]]],
      ["boundary", [[0, 0, 1, 1]], "The best run ends at the last index."],
    ],
  },
  {
    slug: "minimum-difference-between-highest-and-lowest-of-k-scores",
    title: "Minimum Difference Between Highest and Lowest of K Scores",
    difficulty: "Easy",
    pattern: "Two Pointers",
    fn: "minimumDifference",
    params: NUMS_K,
    returns: "number",
    hints: [
      "After sorting, the best k scores are always next to each other.",
      "Sort, then slide a window of size k: its spread is a[i + k - 1] - a[i]. Take the smallest.",
      "sort nums\nbest = infinity\nfor i in 0 .. n - k:\n  best = min(best, nums[i + k - 1] - nums[i])\nreturn best",
    ],
    reference: `function minimumDifference(nums, k) { const a = nums.slice().sort((x, y) => x - y); let best = Infinity; for (let i = 0; i + k <= a.length; i++) best = Math.min(best, a[i + k - 1] - a[i]); return best; }`,
    brute: `function minimumDifference(nums, k) { let best = Infinity; for (const lo of nums) for (const hi of nums) { if (hi < lo) continue; if (nums.filter((v) => v >= lo && v <= hi).length >= k) best = Math.min(best, hi - lo); } return best; }`,
    fuzz: gen(`const n = __r(rand, 2, 10); return [__arr(rand, n, 0, 60), __r(rand, 2, n)];`),
    examples: [[[90], 1], [[9, 4, 1, 7], 2]],
    edges: [
      ["two", [[1, 100], 2]],
      ["extremes", [[0, 100000, 50000], 2]],
      ["boundary", [[1, 2, 3, 100], 4], "k == n: every score is taken."],
    ],
  },
  {
    slug: "number-of-sub-arrays-of-size-k-and-average-greater-than-or-equal-to-threshold",
    title: "Number of Sub-arrays of Size K and Average Greater than or Equal to Threshold",
    difficulty: "Medium",
    pattern: "Sliding Window",
    fn: "numOfSubarrays",
    params: [["arr", "number[]"], ["k", "number"], ["threshold", "number"]],
    returns: "number",
    hints: [
      "Average >= threshold is the same as sum >= k * threshold, so you never need division.",
      "Keep a running sum of the last k values: add the new one, drop the one that left, and count windows whose sum is large enough.",
      "sum = 0, count = 0\nfor i in 0 .. n - 1:\n  sum = sum + arr[i]\n  if i >= k: sum = sum - arr[i - k]\n  if i >= k - 1 and sum >= k * threshold: count = count + 1\nreturn count",
    ],
    reference: `function numOfSubarrays(arr, k, threshold) { let s = 0, c = 0; for (let i = 0; i < arr.length; i++) { s += arr[i]; if (i >= k) s -= arr[i - k]; if (i >= k - 1 && s >= k * threshold) c++; } return c; }`,
    brute: `function numOfSubarrays(arr, k, threshold) { let c = 0; for (let i = 0; i + k <= arr.length; i++) { const w = arr.slice(i, i + k); if (w.reduce((a, b) => a + b, 0) / k >= threshold) c++; } return c; }`,
    fuzz: gen(`const n = __r(rand, 1, 15); return [__arr(rand, n, 1, 10), __r(rand, 1, n), __r(rand, 1, 7)];`),
    examples: [[[2, 2, 2, 2, 5, 5, 5, 8], 3, 4], [[11, 13, 17, 23, 29, 31, 7, 5, 2, 3], 3, 5]],
    edges: [
      ["single", [[5], 1, 5], "One window, average exactly equal: it counts."],
      ["all-equal", [[3, 3, 3], 2, 3]],
      ["no-answer", [[1, 1, 1], 1, 2]],
    ],
  },
  {
    slug: "maximum-points-you-can-obtain-from-cards",
    title: "Maximum Points You Can Obtain from Cards",
    difficulty: "Medium",
    pattern: "Sliding Window",
    fn: "maxScore",
    params: [["cardPoints", "number[]"], ["k", "number"]],
    returns: "number",
    hints: [
      "Whatever you take from the ends, the cards you leave form one contiguous block of n - k cards.",
      "Maximising what you take means minimising the block you leave. Slide a window of size n - k and keep its smallest sum.",
      "total = sum(cardPoints), w = n - k\nwindow = sum of first w cards, low = window\nfor i in w .. n - 1:\n  window = window + cardPoints[i] - cardPoints[i - w]\n  low = min(low, window)\nreturn total - low",
    ],
    reference: `function maxScore(cardPoints, k) { const n = cardPoints.length, w = n - k; let total = 0; for (const v of cardPoints) total += v; let s = 0; for (let i = 0; i < w; i++) s += cardPoints[i]; let min = s; for (let i = w; i < n; i++) { s += cardPoints[i] - cardPoints[i - w]; min = Math.min(min, s); } return total - min; }`,
    brute: `function maxScore(cardPoints, k) { let best = 0; const n = cardPoints.length; for (let i = 0; i <= k; i++) { let s = 0; for (let a = 0; a < i; a++) s += cardPoints[a]; for (let b = 0; b < k - i; b++) s += cardPoints[n - 1 - b]; best = Math.max(best, s); } return best; }`,
    fuzz: gen(`const n = __r(rand, 1, 12); return [__arr(rand, n, 1, 20), __r(rand, 1, n)];`),
    examples: [[[1, 2, 3, 4, 5, 6, 1], 3], [[2, 2, 2], 2]],
    edges: [
      ["boundary", [[9, 7, 7, 9, 7, 7, 9], 7], "k == n: take everything."],
      ["single", [[5], 1]],
      ["extremes", [[1, 1000, 1], 1], "The big card sits in the middle and can't be reached."],
    ],
  },
  {
    slug: "grumpy-bookstore-owner",
    title: "Grumpy Bookstore Owner",
    difficulty: "Medium",
    pattern: "Sliding Window",
    fn: "maxSatisfied",
    params: [["customers", "number[]"], ["grumpy", "number[]"], ["minutes", "number"]],
    returns: "number",
    hints: [
      "Customers in calm minutes are happy no matter what. The technique only changes the grumpy minutes inside one window.",
      "Add up the always-happy customers, then slide a window of length minutes summing only the grumpy-minute customers it rescues. Add the best window.",
      "base = sum of customers[i] where grumpy[i] == 0\nextra = 0, best = 0\nfor i in 0 .. n - 1:\n  if grumpy[i]: extra = extra + customers[i]\n  if i >= minutes and grumpy[i - minutes]: extra = extra - customers[i - minutes]\n  best = max(best, extra)\nreturn base + best",
    ],
    reference: `function maxSatisfied(customers, grumpy, minutes) { let base = 0, extra = 0, best = 0; for (let i = 0; i < customers.length; i++) { if (!grumpy[i]) base += customers[i]; else extra += customers[i]; if (i >= minutes && grumpy[i - minutes]) extra -= customers[i - minutes]; best = Math.max(best, extra); } return base + best; }`,
    brute: `function maxSatisfied(customers, grumpy, minutes) { let best = 0; for (let s = 0; s + minutes <= customers.length; s++) { let t = 0; for (let i = 0; i < customers.length; i++) if (!grumpy[i] || (i >= s && i < s + minutes)) t += customers[i]; best = Math.max(best, t); } return best; }`,
    fuzz: gen(`const n = __r(rand, 1, 12); return [__arr(rand, n, 0, 10), ${BITS("n", 0.5)}, __r(rand, 1, n)];`),
    examples: [[[1, 0, 1, 2, 1, 1, 7, 5], [0, 1, 0, 1, 0, 1, 0, 1], 3], [[1], [0], 1]],
    edges: [
      ["zeros", [[0, 0, 0], [1, 1, 1], 2]],
      ["all-equal", [[4, 4, 4, 4], [1, 1, 1, 1], 2]],
      ["boundary", [[2, 6, 6, 9], [0, 0, 1, 1], 1], "The best minute to rescue is the last one."],
    ],
  },
  {
    slug: "minimum-swaps-to-group-all-1s-together-ii",
    title: "Minimum Swaps to Group All 1's Together II",
    difficulty: "Medium",
    pattern: "Sliding Window",
    fn: "minSwaps",
    params: [["nums", "number[]"]],
    returns: "number",
    hints: [
      "If there are m ones, they must end up in some circular window of length m. Every 0 inside that window needs one swap.",
      "Slide a window of length m around the circle (use index mod n) and find the window with the most 1s. The answer is m minus that.",
      "m = count of 1s\nif m == 0: return 0\nones = 1s in nums[0 .. m - 1], best = ones\nfor i in m .. n + m - 1:\n  ones = ones + nums[i mod n] - nums[(i - m) mod n]\n  best = max(best, ones)\nreturn m - best",
    ],
    reference: `function minSwaps(nums) { const n = nums.length, m = nums.reduce((a, b) => a + b, 0); if (m === 0) return 0; let ones = 0; for (let i = 0; i < m; i++) ones += nums[i]; let best = ones; for (let i = m; i < n + m; i++) { ones += nums[i % n] - nums[(i - m) % n]; best = Math.max(best, ones); } return m - best; }`,
    brute: `function minSwaps(nums) { const n = nums.length, m = nums.filter((x) => x === 1).length; let best = Infinity; for (let s = 0; s < n; s++) { let z = 0; for (let j = 0; j < m; j++) if (nums[(s + j) % n] === 0) z++; best = Math.min(best, z); } return best; }`,
    fuzz: gen(`return [${BITS("__r(rand, 4, 20)", 0.5)}];`),
    examples: [[[0, 1, 0, 1, 1, 0, 0]], [[0, 1, 1, 1, 0, 0, 1, 1, 0]]],
    edges: [
      ["zeros", [[0, 0, 0]]],
      ["boundary", [[1, 0, 0, 1, 0, 1]], "The best window wraps around the end."],
      ["large", [Array.from({ length: 3000 }, (_, i) => ((i * 7) % 3 === 0 ? 1 : 0))]],
    ],
  },
  {
    slug: "fruit-into-baskets",
    title: "Fruit Into Baskets",
    difficulty: "Medium",
    pattern: "Sliding Window",
    fn: "totalFruit",
    params: [["fruits", "number[]"]],
    returns: "number",
    hints: [
      "Reworded: find the longest subarray with at most two distinct values.",
      "Grow a window to the right while counting each type. When a third type appears, shrink from the left until only two remain.",
      "count = empty map, left = 0, best = 0\nfor right in 0 .. n - 1:\n  count[fruits[right]] += 1\n  while count has more than 2 keys:\n    count[fruits[left]] -= 1, drop it at 0\n    left = left + 1\n  best = max(best, right - left + 1)\nreturn best",
    ],
    reference: `function totalFruit(fruits) { const cnt = new Map(); let l = 0, best = 0; for (let r = 0; r < fruits.length; r++) { cnt.set(fruits[r], (cnt.get(fruits[r]) || 0) + 1); while (cnt.size > 2) { const f = fruits[l++]; cnt.set(f, cnt.get(f) - 1); if (cnt.get(f) === 0) cnt.delete(f); } best = Math.max(best, r - l + 1); } return best; }`,
    brute: `function totalFruit(fruits) { let best = 0; for (let i = 0; i < fruits.length; i++) { const seen = new Set(); for (let j = i; j < fruits.length; j++) { seen.add(fruits[j]); if (seen.size > 2) break; best = Math.max(best, j - i + 1); } } return best; }`,
    fuzz: gen(`return [__arr(rand, __r(rand, 1, 15), 0, 4)];`),
    examples: [[[1, 2, 1]], [[0, 1, 2, 2]], [[1, 2, 3, 2, 2]]],
    edges: [
      ["single", [[7]]],
      ["all-equal", [[3, 3, 3]]],
      ["boundary", [[3, 3, 3, 1, 2, 1, 1, 2, 3, 3, 4]], "The longest window sits in the middle."],
    ],
  },
  {
    slug: "longest-subarray-of-1s-after-deleting-one-element",
    title: "Longest Subarray of 1's After Deleting One Element",
    difficulty: "Medium",
    pattern: "Sliding Window",
    fn: "longestSubarray",
    params: [["nums", "number[]"]],
    returns: "number",
    hints: [
      "Deleting one element means the window may hold at most one 0, and you must remove one element even if there are no 0s.",
      "Slide a window that allows at most one zero. Its length minus one is the run you get after deleting.",
      "left = 0, zeros = 0, best = 0\nfor right in 0 .. n - 1:\n  if nums[right] == 0: zeros = zeros + 1\n  while zeros > 1:\n    if nums[left] == 0: zeros = zeros - 1\n    left = left + 1\n  best = max(best, right - left)\nreturn best",
    ],
    reference: `function longestSubarray(nums) { let l = 0, zeros = 0, best = 0; for (let r = 0; r < nums.length; r++) { if (nums[r] === 0) zeros++; while (zeros > 1) if (nums[l++] === 0) zeros--; best = Math.max(best, r - l); } return best; }`,
    brute: `function longestSubarray(nums) { let best = 0; for (let d = 0; d < nums.length; d++) { let run = 0; for (let i = 0; i < nums.length; i++) { if (i === d) continue; run = nums[i] === 1 ? run + 1 : 0; best = Math.max(best, run); } } return best; }`,
    fuzz: gen(`return [${BITS("__r(rand, 2, 20)", 0.7)}];`),
    examples: [[[1, 1, 0, 1]], [[0, 1, 1, 1, 0, 1, 1, 0, 1]]],
    edges: [
      ["all-equal", [[1, 1, 1]], "No zero to delete, but one element must still go."],
      ["zeros", [[0, 0, 0]]],
      ["two", [[0, 1]]],
    ],
  },
  {
    slug: "longest-turbulent-subarray",
    title: "Longest Turbulent Subarray",
    difficulty: "Medium",
    pattern: "Sliding Window",
    fn: "maxTurbulenceSize",
    params: [["arr", "number[]"]],
    returns: "number",
    hints: [
      "Turbulent means the comparison sign flips between every adjacent pair: up, down, up, ...",
      "Track two lengths ending at i: one whose last step went up and one whose last step went down. An up step extends the down-ending run, and vice versa. Equal values reset both.",
      "up = 1, down = 1, best = 1\nfor i in 1 .. n - 1:\n  if arr[i] > arr[i - 1]: up = down + 1, down = 1\n  else if arr[i] < arr[i - 1]: down = up + 1, up = 1\n  else: up = 1, down = 1\n  best = max(best, up, down)\nreturn best",
    ],
    reference: `function maxTurbulenceSize(arr) { let inc = 1, dec = 1, best = 1; for (let i = 1; i < arr.length; i++) { if (arr[i] > arr[i - 1]) { inc = dec + 1; dec = 1; } else if (arr[i] < arr[i - 1]) { dec = inc + 1; inc = 1; } else { inc = 1; dec = 1; } best = Math.max(best, inc, dec); } return best; }`,
    brute: `function maxTurbulenceSize(arr) { let best = 1; for (let i = 0; i < arr.length; i++) { let j = i + 1; while (j < arr.length && arr[j] !== arr[j - 1] && (j === i + 1 || Math.sign(arr[j] - arr[j - 1]) !== Math.sign(arr[j - 1] - arr[j - 2]))) j++; best = Math.max(best, j - i); } return best; }`,
    fuzz: gen(`return [__arr(rand, __r(rand, 2, 15), 0, 9)];`),
    examples: [[[9, 4, 2, 10, 7, 8, 8, 1, 9]], [[4, 8, 12, 16]]],
    edges: [
      ["single", [[100]]],
      ["all-equal", [[5, 5, 5]], "Equal neighbours are never turbulent: the answer is 1."],
      ["boundary", [[1, 1, 3, 2, 4, 3, 5]], "The run starts at index 1 and reaches the end."],
    ],
  },
  {
    slug: "frequency-of-the-most-frequent-element",
    title: "Frequency of the Most Frequent Element",
    difficulty: "Medium",
    pattern: "Sliding Window",
    fn: "maxFrequency",
    params: NUMS_K,
    returns: "number",
    hints: [
      "You can only increase values, so the target should be one of the existing values, and it is cheapest to raise the values just below it.",
      "Sort. For a window ending at r, raising everything to nums[r] costs nums[r] * size - sum. Shrink from the left while that exceeds k.",
      "sort nums\nleft = 0, sum = 0, best = 0\nfor right in 0 .. n - 1:\n  sum = sum + nums[right]\n  while nums[right] * (right - left + 1) - sum > k:\n    sum = sum - nums[left], left = left + 1\n  best = max(best, right - left + 1)\nreturn best",
    ],
    reference: `function maxFrequency(nums, k) { const a = nums.slice().sort((x, y) => x - y); let l = 0, sum = 0, best = 0; for (let r = 0; r < a.length; r++) { sum += a[r]; while (a[r] * (r - l + 1) - sum > k) sum -= a[l++]; best = Math.max(best, r - l + 1); } return best; }`,
    brute: `function maxFrequency(nums, k) { let best = 0; for (const t of nums) { const below = nums.filter((v) => v <= t).sort((x, y) => y - x); let cost = 0, c = 0; for (const v of below) { if (cost + t - v > k) break; cost += t - v; c++; } best = Math.max(best, c); } return best; }`,
    fuzz: gen(`return [__arr(rand, __r(rand, 1, 12), 1, 20), __r(rand, 0, 20)];`),
    examples: [[[1, 2, 4], 5], [[1, 4, 8, 13], 5], [[3, 9, 6], 2]],
    edges: [
      ["single", [[5], 0]],
      ["zeros", [[3, 1, 3, 2], 0], "k = 0: only existing duplicates count."],
      ["all-equal", [[2, 2, 2], 1]],
    ],
  },
  {
    slug: "length-of-longest-subarray-with-at-most-k-frequency",
    title: "Length of Longest Subarray With at Most K Frequency",
    difficulty: "Medium",
    pattern: "Sliding Window",
    fn: "maxSubarrayLength",
    params: NUMS_K,
    returns: "number",
    hints: [
      "A window is good while no value appears more than k times. Adding one value can only break it for that value.",
      "Grow right and count values. If the new value's count passes k, move left forward (decrementing counts) until it is back to k.",
      "count = empty map, left = 0, best = 0\nfor right in 0 .. n - 1:\n  count[nums[right]] += 1\n  while count[nums[right]] > k:\n    count[nums[left]] -= 1, left = left + 1\n  best = max(best, right - left + 1)\nreturn best",
    ],
    reference: `function maxSubarrayLength(nums, k) { const cnt = new Map(); let l = 0, best = 0; for (let r = 0; r < nums.length; r++) { cnt.set(nums[r], (cnt.get(nums[r]) || 0) + 1); while (cnt.get(nums[r]) > k) { cnt.set(nums[l], cnt.get(nums[l]) - 1); l++; } best = Math.max(best, r - l + 1); } return best; }`,
    brute: `function maxSubarrayLength(nums, k) { let best = 0; for (let i = 0; i < nums.length; i++) { const c = {}; for (let j = i; j < nums.length; j++) { c[nums[j]] = (c[nums[j]] || 0) + 1; if (c[nums[j]] > k) break; best = Math.max(best, j - i + 1); } } return best; }`,
    fuzz: gen(`return [__arr(rand, __r(rand, 1, 15), 1, 5), __r(rand, 1, 3)];`),
    examples: [[[1, 2, 3, 1, 2, 3, 1, 2], 2], [[1, 2, 1, 2, 1, 2, 1, 2], 1], [[5, 5, 5, 5, 5, 5, 5], 4]],
    edges: [
      ["single", [[1], 1]],
      ["all-equal", [[2, 2, 2], 1]],
      ["boundary", [[1, 2, 1, 2, 3], 2], "The whole array is already good."],
    ],
  },
  {
    slug: "longest-nice-subarray",
    title: "Longest Nice Subarray",
    difficulty: "Medium",
    pattern: "Sliding Window",
    fn: "longestNiceSubarray",
    params: [["nums", "number[]"]],
    returns: "number",
    hints: [
      "Nice means no two numbers share a set bit, so the OR of the window is also the sum of its bits with no overlaps.",
      "Keep the OR of the window in a mask. Before adding nums[r], remove numbers from the left (XOR them out) until mask & nums[r] is 0.",
      "left = 0, used = 0, best = 0\nfor right in 0 .. n - 1:\n  while used AND nums[right] != 0:\n    used = used XOR nums[left], left = left + 1\n  used = used OR nums[right]\n  best = max(best, right - left + 1)\nreturn best",
    ],
    reference: `function longestNiceSubarray(nums) { let l = 0, used = 0, best = 0; for (let r = 0; r < nums.length; r++) { while (used & nums[r]) used ^= nums[l++]; used |= nums[r]; best = Math.max(best, r - l + 1); } return best; }`,
    brute: `function longestNiceSubarray(nums) { let best = 0; for (let i = 0; i < nums.length; i++) for (let j = i; j < nums.length; j++) { let ok = true; for (let a = i; a <= j && ok; a++) for (let b = a + 1; b <= j; b++) if (nums[a] & nums[b]) { ok = false; break; } if (ok) best = Math.max(best, j - i + 1); } return best; }`,
    fuzz: gen(`return [Array.from({ length: __r(rand, 2, 12) }, () => (rand() < 0.6 ? 1 << __r(rand, 0, 7) : __r(rand, 1, 100)))];`),
    examples: [[[1, 3, 8, 48, 10]], [[3, 1, 5, 11, 13]]],
    edges: [
      ["single", [[7]]],
      ["sorted", [[1, 2, 4, 8]], "Distinct powers of two never overlap: the whole array."],
      ["extremes", [[1073741824, 1, 2]]],
    ],
  },
  {
    slug: "count-subarrays-where-max-element-appears-at-least-k-times",
    title: "Count Subarrays Where Max Element Appears at Least K Times",
    difficulty: "Medium",
    pattern: "Sliding Window",
    fn: "countSubarrays",
    params: NUMS_K,
    returns: "number",
    hints: [
      "The maximum of the whole array is fixed. Count subarrays that contain it at least k times.",
      "For each right end, move left as far as possible while the window still has k copies. Every start before left works, so add left.",
      "mx = max(nums), left = 0, seen = 0, ans = 0\nfor right in 0 .. n - 1:\n  if nums[right] == mx: seen = seen + 1\n  while seen >= k:\n    if nums[left] == mx: seen = seen - 1\n    left = left + 1\n  ans = ans + left\nreturn ans",
    ],
    reference: `function countSubarrays(nums, k) { const mx = Math.max(...nums); let l = 0, c = 0, ans = 0; for (let r = 0; r < nums.length; r++) { if (nums[r] === mx) c++; while (c >= k) { if (nums[l] === mx) c--; l++; } ans += l; } return ans; }`,
    brute: `function countSubarrays(nums, k) { let mx = -Infinity; for (const v of nums) mx = Math.max(mx, v); let ans = 0; for (let i = 0; i < nums.length; i++) { let c = 0; for (let j = i; j < nums.length; j++) { if (nums[j] === mx) c++; if (c >= k) ans++; } } return ans; }`,
    fuzz: gen(`return [__arr(rand, __r(rand, 3, 15), 1, 4), __r(rand, 1, 3)];`),
    examples: [[[1, 3, 2, 3, 3], 2], [[1, 4, 2, 1], 3]],
    edges: [
      ["single", [[4], 1]],
      ["all-equal", [[2, 2, 2], 2]],
      ["large", [Array.from({ length: 2000 }, (_, i) => (i % 3 === 0 ? 9 : i % 5)), 5]],
    ],
  },
  {
    slug: "subarray-product-less-than-k",
    title: "Subarray Product Less Than K",
    difficulty: "Medium",
    pattern: "Sliding Window",
    fn: "numSubarrayProductLessThanK",
    params: NUMS_K,
    returns: "number",
    hints: [
      "All values are positive, so extending a window only grows its product and shrinking only lowers it.",
      "For each right end, shrink from the left until the product is below k. Then every subarray ending at right and starting in the window counts: right - left + 1 of them.",
      "if k <= 1: return 0\nproduct = 1, left = 0, ans = 0\nfor right in 0 .. n - 1:\n  product = product * nums[right]\n  while product >= k:\n    product = product / nums[left], left = left + 1\n  ans = ans + right - left + 1\nreturn ans",
    ],
    reference: `function numSubarrayProductLessThanK(nums, k) { if (k <= 1) return 0; let p = 1, l = 0, ans = 0; for (let r = 0; r < nums.length; r++) { p *= nums[r]; while (p >= k) p /= nums[l++]; ans += r - l + 1; } return ans; }`,
    brute: `function numSubarrayProductLessThanK(nums, k) { let ans = 0; for (let i = 0; i < nums.length; i++) { let p = 1; for (let j = i; j < nums.length; j++) { p *= nums[j]; if (p >= k) break; ans++; } } return ans; }`,
    fuzz: gen(`return [__arr(rand, __r(rand, 1, 15), 1, 10), __r(rand, 2, 100)];`),
    examples: [[[10, 5, 2, 6], 100], [[1, 2, 3], 0]],
    edges: [
      ["single", [[1], 2]],
      ["all-equal", [[1, 1, 1], 2], "Every subarray has product 1: all 6 count."],
      ["boundary", [[5, 2], 10], "A product equal to k does not count."],
    ],
  },
  {
    slug: "minimum-operations-to-reduce-x-to-zero",
    title: "Minimum Operations to Reduce X to Zero",
    difficulty: "Medium",
    pattern: "Sliding Window",
    fn: "minOperations",
    params: [["nums", "number[]"], ["x", "number"]],
    returns: "number",
    hints: [
      "Removing from both ends leaves a middle block. Its sum must be total - x.",
      "Find the longest subarray with sum total - x (all values are positive, so a sliding window works). The answer is n minus its length, or -1 if none exists.",
      "need = sum(nums) - x\nif need < 0: return -1\nleft = 0, sum = 0, longest = -1\nfor right in 0 .. n - 1:\n  sum = sum + nums[right]\n  while sum > need: sum = sum - nums[left], left = left + 1\n  if sum == need: longest = max(longest, right - left + 1)\nreturn -1 if longest == -1 else n - longest",
    ],
    reference: `function minOperations(nums, x) { const need = nums.reduce((a, b) => a + b, 0) - x; if (need < 0) return -1; let l = 0, s = 0, best = -1; for (let r = 0; r < nums.length; r++) { s += nums[r]; while (s > need) s -= nums[l++]; if (s === need) best = Math.max(best, r - l + 1); } return best === -1 ? -1 : nums.length - best; }`,
    brute: `function minOperations(nums, x) { const n = nums.length; let best = Infinity; for (let a = 0; a <= n; a++) for (let b = 0; a + b <= n; b++) { let s = 0; for (let i = 0; i < a; i++) s += nums[i]; for (let i = 0; i < b; i++) s += nums[n - 1 - i]; if (s === x) best = Math.min(best, a + b); } return best === Infinity ? -1 : best; }`,
    fuzz: gen(`const a = __arr(rand, __r(rand, 1, 12), 1, 10); let x; if (rand() < 0.65) { const p = __r(rand, 0, a.length), q = __r(rand, 0, a.length - p); x = a.slice(0, p).reduce((s, v) => s + v, 0) + a.slice(a.length - q).reduce((s, v) => s + v, 0); if (x === 0) x = a[0]; } else x = __r(rand, 1, 60); return [a, x];`),
    examples: [[[1, 1, 4, 2, 3], 5], [[5, 6, 7, 8, 9], 4], [[3, 2, 20, 1, 1, 3], 10]],
    edges: [
      ["boundary", [[1, 1], 2], "x equals the total: remove everything."],
      ["single", [[5], 5]],
      ["duplicates", [[1, 1, 1, 1, 1], 3]],
    ],
  },
  {
    slug: "partition-labels",
    title: "Partition Labels",
    difficulty: "Medium",
    pattern: "Two Pointers",
    fn: "partitionLabels",
    params: [["s", "string"]],
    returns: "number[]",
    hints: [
      "A part that contains a letter must reach that letter's last occurrence.",
      "Record each letter's last index. Walk the string extending the current part's end to the furthest last index seen; when i reaches that end, close the part.",
      "last[c] = last index of c in s\nstart = 0, end = 0, out = []\nfor i in 0 .. n - 1:\n  end = max(end, last[s[i]])\n  if i == end:\n    append end - start + 1 to out\n    start = i + 1\nreturn out",
    ],
    reference: `function partitionLabels(s) { const last = {}; for (let i = 0; i < s.length; i++) last[s[i]] = i; const out = []; let start = 0, end = 0; for (let i = 0; i < s.length; i++) { end = Math.max(end, last[s[i]]); if (i === end) { out.push(end - start + 1); start = i + 1; } } return out; }`,
    brute: `function partitionLabels(s) { const out = []; let prev = 0; for (let p = 0; p < s.length; p++) { const left = new Set(s.slice(0, p + 1)); let ok = true; for (const c of s.slice(p + 1)) if (left.has(c)) { ok = false; break; } if (ok) { out.push(p + 1 - prev); prev = p + 1; } } return out; }`,
    fuzz: gen(`return [__str(rand, __r(rand, 1, 20), "abcdef")];`),
    examples: [["ababcbacadefegdehijhklij"], ["eccbbbbdec"]],
    edges: [
      ["single-char", ["z"]],
      ["all-equal", ["aaaa"]],
      ["boundary", ["abc"], "Every letter is unique: each is its own part."],
    ],
  },
  {
    slug: "3sum-closest",
    title: "3Sum Closest",
    difficulty: "Medium",
    pattern: "Two Pointers",
    fn: "threeSumClosest",
    params: [["nums", "number[]"], ["target", "number"]],
    returns: "number",
    hints: [
      "Fix one number, then the other two come from a sorted range, which two pointers can scan in linear time.",
      "Sort. For each i, set lo = i + 1 and hi = n - 1. Compare the sum with target: too small moves lo up, too big moves hi down. Keep the sum closest to target.",
      "sort nums, best = nums[0] + nums[1] + nums[2]\nfor i in 0 .. n - 3:\n  lo = i + 1, hi = n - 1\n  while lo < hi:\n    s = nums[i] + nums[lo] + nums[hi]\n    if abs(s - target) < abs(best - target): best = s\n    if s < target: lo = lo + 1\n    else if s > target: hi = hi - 1\n    else: return s\nreturn best",
    ],
    reference: `function threeSumClosest(nums, target) { const a = nums.slice().sort((x, y) => x - y); let best = a[0] + a[1] + a[2]; for (let i = 0; i < a.length - 2; i++) { let lo = i + 1, hi = a.length - 1; while (lo < hi) { const s = a[i] + a[lo] + a[hi]; if (Math.abs(s - target) < Math.abs(best - target)) best = s; if (s < target) lo++; else if (s > target) hi--; else return s; } } return best; }`,
    brute: `function threeSumClosest(nums, target) { let best = null; for (let i = 0; i < nums.length; i++) for (let j = i + 1; j < nums.length; j++) for (let k = j + 1; k < nums.length; k++) { const s = nums[i] + nums[j] + nums[k]; if (best === null || Math.abs(s - target) < Math.abs(best - target)) best = s; } return best; }`,
    fuzz: gen(`const n = __r(rand, 3, 10); const a = __arr(rand, n, -10, 10); let t = __r(rand, -25, 25); const sums = []; for (let i = 0; i < n; i++) for (let j = i + 1; j < n; j++) for (let k = j + 1; k < n; k++) sums.push(a[i] + a[j] + a[k]); let d = Infinity; for (const s of sums) d = Math.min(d, Math.abs(s - t)); if (d > 0 && sums.includes(t - d) && sums.includes(t + d)) t = sums[0]; return [a, t];`),
    examples: [[[-1, 2, 1, -4], 1], [[0, 0, 0], 1]],
    edges: [
      ["negatives", [[-5, -3, -1, -2], -100], "Target far below: the three smallest values."],
      ["boundary", [[1, 1, 1, 0], 100]],
      ["duplicates", [[1, 1, -1, -1, 3], -1], "An exact match exists."],
    ],
  },
  {
    slug: "boats-to-save-people",
    title: "Boats to Save People",
    difficulty: "Medium",
    pattern: "Two Pointers",
    fn: "numRescueBoats",
    params: [["people", "number[]"], ["limit", "number"]],
    returns: "number",
    hints: [
      "The heaviest person needs a boat no matter what. The best partner for them is the lightest person, if anyone fits.",
      "Sort. Point at the lightest and heaviest. The heaviest always boards; the lightest joins if the pair fits. Count boats until the pointers cross.",
      "sort people\ni = 0, j = n - 1, boats = 0\nwhile i <= j:\n  if people[i] + people[j] <= limit: i = i + 1\n  j = j - 1\n  boats = boats + 1\nreturn boats",
    ],
    reference: `function numRescueBoats(people, limit) { const a = people.slice().sort((x, y) => x - y); let i = 0, j = a.length - 1, b = 0; while (i <= j) { if (a[i] + a[j] <= limit) i++; j--; b++; } return b; }`,
    brute: `function numRescueBoats(people, limit) { const n = people.length, full = (1 << n) - 1, dp = new Array(1 << n).fill(Infinity); dp[0] = 0; for (let m = 0; m < full; m++) { if (dp[m] === Infinity) continue; let i = 0; while (m & (1 << i)) i++; const a = m | (1 << i); dp[a] = Math.min(dp[a], dp[m] + 1); for (let j = i + 1; j < n; j++) if (!(m & (1 << j)) && people[i] + people[j] <= limit) dp[a | (1 << j)] = Math.min(dp[a | (1 << j)], dp[m] + 1); } return dp[full]; }`,
    fuzz: gen(`const limit = __r(rand, 1, 15); return [__arr(rand, __r(rand, 2, 9), 1, limit), limit];`),
    examples: [[[1, 2], 3], [[3, 2, 2, 1], 3], [[3, 5, 3, 4], 5]],
    edges: [
      ["single", [[5], 5]],
      ["all-equal", [[2, 2, 2, 2], 4]],
      ["extremes", [[5, 5, 5], 5], "Everyone weighs the limit: one person per boat."],
    ],
  },
  {
    slug: "interval-list-intersections",
    title: "Interval List Intersections",
    difficulty: "Medium",
    pattern: "Two Pointers",
    fn: "intervalIntersection",
    params: [["firstList", "number[][]"], ["secondList", "number[][]"]],
    returns: "number[][]",
    hints: [
      "Two intervals overlap on [max(starts), min(ends)] when that range is not empty.",
      "Walk both lists with one pointer each. Record the overlap of the current pair, then advance whichever interval ends first: it can't overlap anything later.",
      "i = 0, j = 0, out = []\nwhile i < len(A) and j < len(B):\n  lo = max(A[i].start, B[j].start)\n  hi = min(A[i].end, B[j].end)\n  if lo <= hi: append [lo, hi]\n  if A[i].end < B[j].end: i = i + 1\n  else: j = j + 1\nreturn out",
    ],
    reference: `function intervalIntersection(firstList, secondList) { const out = []; let i = 0, j = 0; while (i < firstList.length && j < secondList.length) { const lo = Math.max(firstList[i][0], secondList[j][0]), hi = Math.min(firstList[i][1], secondList[j][1]); if (lo <= hi) out.push([lo, hi]); if (firstList[i][1] < secondList[j][1]) i++; else j++; } return out; }`,
    brute: `function intervalIntersection(firstList, secondList) { const out = []; for (const a of firstList) for (const b of secondList) { const lo = Math.max(a[0], b[0]), hi = Math.min(a[1], b[1]); if (lo <= hi) out.push([lo, hi]); } return out.sort((x, y) => x[0] - y[0]); }`,
    fuzz: gen(`${INTERVALS} return [__ivs(rand, __r(rand, 1, 5)), __ivs(rand, __r(rand, 1, 5))];`),
    examples: [[[[0, 2], [5, 10], [13, 23], [24, 25]], [[1, 5], [8, 12], [15, 24], [25, 26]]], [[[1, 3], [5, 9]], []]],
    edges: [
      ["empty", [[], [[4, 8]]]],
      ["boundary", [[[1, 2]], [[2, 3]]], "Touching endpoints intersect in a single point."],
      ["all-equal", [[[1, 5], [7, 9]], [[1, 5], [7, 9]]]],
    ],
  },
  {
    slug: "number-of-subsequences-that-satisfy-the-given-sum-condition",
    title: "Number of Subsequences That Satisfy the Given Sum Condition",
    difficulty: "Medium",
    pattern: "Two Pointers",
    fn: "numSubseq",
    params: [["nums", "number[]"], ["target", "number"]],
    returns: "number",
    hints: [
      "Only the minimum and maximum matter, and order doesn't, so sort.",
      "With lo as the minimum and hi the furthest index where nums[lo] + nums[hi] <= target, any subset of the elements between them (with lo included) works: 2^(hi - lo) subsequences. Move two pointers and add powers of two mod 1e9+7.",
      "sort nums, pow2[i] = 2^i mod M\nlo = 0, hi = n - 1, ans = 0\nwhile lo <= hi:\n  if nums[lo] + nums[hi] <= target:\n    ans = (ans + pow2[hi - lo]) mod M\n    lo = lo + 1\n  else: hi = hi - 1\nreturn ans",
    ],
    reference: `function numSubseq(nums, target) { const MOD = 1000000007, a = nums.slice().sort((x, y) => x - y), n = a.length, pw = [1]; for (let i = 1; i < n; i++) pw.push((pw[i - 1] * 2) % MOD); let i = 0, j = n - 1, ans = 0; while (i <= j) { if (a[i] + a[j] <= target) { ans = (ans + pw[j - i]) % MOD; i++; } else j--; } return ans; }`,
    brute: `function numSubseq(nums, target) { const n = nums.length; let ans = 0; for (let m = 1; m < (1 << n); m++) { let lo = Infinity, hi = -Infinity; for (let i = 0; i < n; i++) if (m & (1 << i)) { lo = Math.min(lo, nums[i]); hi = Math.max(hi, nums[i]); } if (lo + hi <= target) ans++; } return ans % 1000000007; }`,
    fuzz: gen(`return [__arr(rand, __r(rand, 1, 12), 1, 20), __r(rand, 2, 40)];`),
    examples: [[[3, 5, 6, 7], 9], [[3, 3, 6, 8], 10], [[2, 3, 3, 4, 6, 7], 12]],
    edges: [
      ["single", [[5], 10]],
      ["no-answer", [[5, 6], 4]],
      ["extremes", [Array.from({ length: 16 }, () => 1), 2], "Every non-empty subsequence counts: 2^16 - 1."],
    ],
  },
  {
    slug: "shortest-unsorted-continuous-subarray",
    title: "Shortest Unsorted Continuous Subarray",
    difficulty: "Medium",
    pattern: "Two Pointers",
    fn: "findUnsortedSubarray",
    params: [["nums", "number[]"]],
    returns: "number",
    hints: [
      "The right end of the subarray is the last index that is smaller than the maximum seen before it. The left end is the mirror image.",
      "Scan left to right with a running max: any value below it marks a new right end. Scan right to left with a running min: any value above it marks a new left end.",
      "end = -1, hi = -infinity\nfor i in 0 .. n - 1:\n  if nums[i] < hi: end = i\n  else: hi = nums[i]\nstart = 0, lo = infinity\nfor i in n - 1 down to 0:\n  if nums[i] > lo: start = i\n  else: lo = nums[i]\nreturn 0 if end == -1 else end - start + 1",
    ],
    reference: `function findUnsortedSubarray(nums) { const n = nums.length; let end = -1, start = 0, max = -Infinity, min = Infinity; for (let i = 0; i < n; i++) { if (nums[i] < max) end = i; else max = nums[i]; } for (let i = n - 1; i >= 0; i--) { if (nums[i] > min) start = i; else min = nums[i]; } return end === -1 ? 0 : end - start + 1; }`,
    brute: `function findUnsortedSubarray(nums) { const s = nums.slice().sort((a, b) => a - b); let i = 0, j = nums.length - 1; while (i < nums.length && s[i] === nums[i]) i++; if (i === nums.length) return 0; while (s[j] === nums[j]) j--; return j - i + 1; }`,
    fuzz: gen(`const a = __sorted(rand, __r(rand, 2, 15), 0, 20); if (rand() < 0.9) { const i = __r(rand, 0, a.length - 2), j = __r(rand, i + 1, a.length - 1); const seg = __shuffle(rand, a.slice(i, j + 1)); a.splice(i, seg.length, ...seg); } return [a];`),
    examples: [[[2, 6, 4, 8, 10, 9, 15]], [[1, 2, 3, 4]]],
    edges: [
      ["reverse-sorted", [[5, 4, 3, 2, 1]]],
      ["duplicates", [[1, 3, 2, 2, 2]], "Equal values still need to move past the 3."],
      ["two", [[2, 1]]],
    ],
  },
  {
    slug: "longest-mountain-in-array",
    title: "Longest Mountain in Array",
    difficulty: "Medium",
    pattern: "Two Pointers",
    fn: "longestMountain",
    params: [["arr", "number[]"]],
    returns: "number",
    hints: [
      "A mountain is a strictly rising run followed by a strictly falling run, each at least one step long.",
      "Walk once counting up-steps and down-steps of the current mountain. Reset both on a flat step or when a rise starts after a fall. Whenever both are positive, up + down + 1 is a mountain.",
      "up = 0, down = 0, best = 0\nfor i in 1 .. n - 1:\n  if arr[i] == arr[i - 1] or (down > 0 and arr[i] > arr[i - 1]): up = 0, down = 0\n  if arr[i] > arr[i - 1]: up = up + 1\n  if arr[i] < arr[i - 1]: down = down + 1\n  if up > 0 and down > 0: best = max(best, up + down + 1)\nreturn best",
    ],
    reference: `function longestMountain(arr) { let best = 0, up = 0, down = 0; for (let i = 1; i < arr.length; i++) { if ((down > 0 && arr[i] > arr[i - 1]) || arr[i] === arr[i - 1]) { up = 0; down = 0; } if (arr[i] > arr[i - 1]) up++; if (arr[i] < arr[i - 1]) down++; if (up > 0 && down > 0) best = Math.max(best, up + down + 1); } return best; }`,
    brute: `function longestMountain(arr) { let best = 0; for (let p = 1; p + 1 < arr.length; p++) { let l = p, r = p; while (l > 0 && arr[l - 1] < arr[l]) l--; while (r + 1 < arr.length && arr[r + 1] < arr[r]) r++; if (l < p && r > p) best = Math.max(best, r - l + 1); } return best; }`,
    fuzz: gen(`return [__arr(rand, __r(rand, 4, 15), 0, 6)];`),
    examples: [[[2, 1, 4, 7, 3, 2, 5]], [[2, 2, 2]]],
    edges: [
      ["min-size", [[1, 2, 1]]],
      ["sorted", [[1, 2, 3, 4]], "Only rising, never falling: no mountain."],
      ["boundary", [[0, 1, 2, 3, 4, 5, 4, 3, 2, 1, 0]], "The whole array is one mountain."],
    ],
  },
  {
    slug: "sliding-window-median",
    title: "Sliding Window Median",
    difficulty: "Hard",
    pattern: "Sliding Window",
    fn: "medianSlidingWindow",
    params: NUMS_K,
    returns: "number[]",
    hints: [
      "Keep the window's values in sorted order so the median is just the middle element (or the average of the two middle ones).",
      "Each step removes one value and adds one. With a sorted array and binary search you can find both positions quickly; two heaps with lazy deletion get it to O(log k).",
      "window = sorted copy of nums[0 .. k - 1]\nout = [median(window)]\nfor i in k .. n - 1:\n  remove nums[i - k] from window (binary search)\n  insert nums[i] into window (binary search)\n  append median(window) to out\nreturn out",
    ],
    reference: `function medianSlidingWindow(nums, k) { const w = nums.slice(0, k).sort((a, b) => a - b), out = []; const pos = (v) => { let lo = 0, hi = w.length; while (lo < hi) { const m = (lo + hi) >> 1; if (w[m] < v) lo = m + 1; else hi = m; } return lo; }; const med = () => (k % 2 ? w[(k - 1) / 2] : w[k / 2 - 1] / 2 + w[k / 2] / 2); out.push(med()); for (let i = k; i < nums.length; i++) { w.splice(pos(nums[i - k]), 1); w.splice(pos(nums[i]), 0, nums[i]); out.push(med()); } return out; }`,
    brute: `function medianSlidingWindow(nums, k) { const out = []; for (let i = 0; i + k <= nums.length; i++) { const w = nums.slice(i, i + k).sort((a, b) => a - b); out.push(k % 2 ? w[(k - 1) / 2] : (w[k / 2 - 1] + w[k / 2]) / 2); } return out; }`,
    fuzz: gen(`const n = __r(rand, 1, 12); return [__arr(rand, n, -10, 10), __r(rand, 1, n)];`),
    examples: [[[1, 3, -1, -3, 5, 3, 6, 7], 3], [[1, 2, 3, 4, 2, 3, 1, 4, 2], 3]],
    edges: [
      ["single", [[5], 1]],
      ["two", [[1, 2], 2], "Even window: the average of the two middle values."],
      ["extremes", [[2147483647, 2147483647], 2], "Adding the two middles can overflow a 32-bit int."],
    ],
  },
  {
    slug: "substring-with-concatenation-of-all-words",
    title: "Substring with Concatenation of All Words",
    difficulty: "Hard",
    pattern: "Sliding Window",
    fn: "findSubstring",
    params: [["s", "string"], ["words", "string[]"]],
    returns: "number[]",
    compare: "unordered",
    hints: [
      "All words have the same length L, so a match is m consecutive chunks of length L that use each word exactly as often as it appears in words.",
      "For each offset 0 .. L - 1, slide a window over chunks: add the next chunk, and if it is not a word, reset; if it is used too often, drop chunks from the left. A full window of m chunks is a match.",
      "need = counts of words, L = word length, m = len(words)\nfor offset in 0 .. L - 1:\n  left = offset, have = empty map, used = 0\n  for right = offset; right + L <= n; right += L:\n    w = s[right .. right + L)\n    if w not in need: clear have, used = 0, left = right + L; continue\n    have[w] += 1, used += 1\n    while have[w] > need[w]: drop the chunk at left, left += L, used -= 1\n    if used == m: record left, drop the chunk at left, left += L, used -= 1\nreturn the recorded starts",
    ],
    reference: `function findSubstring(s, words) { const L = words[0].length, n = words.length, need = new Map(), out = []; for (const w of words) need.set(w, (need.get(w) || 0) + 1); for (let off = 0; off < L; off++) { let l = off, cnt = 0; const have = new Map(); for (let r = off; r + L <= s.length; r += L) { const w = s.substr(r, L); if (!need.has(w)) { have.clear(); cnt = 0; l = r + L; continue; } have.set(w, (have.get(w) || 0) + 1); cnt++; while (have.get(w) > need.get(w)) { const x = s.substr(l, L); have.set(x, have.get(x) - 1); cnt--; l += L; } if (cnt === n) { out.push(l); const x = s.substr(l, L); have.set(x, have.get(x) - 1); cnt--; l += L; } } } return out.sort((a, b) => a - b); }`,
    brute: `function findSubstring(s, words) { const L = words[0].length, total = L * words.length, key = words.slice().sort().join(","), out = []; for (let i = 0; i + total <= s.length; i++) { const parts = []; for (let j = 0; j < words.length; j++) parts.push(s.substr(i + j * L, L)); if (parts.sort().join(",") === key) out.push(i); } return out; }`,
    fuzz: gen(`const L = __r(rand, 1, 3), m = __r(rand, 1, 4); const words = Array.from({ length: m }, () => __str(rand, L, "ab")); let s = __str(rand, __r(rand, 0, 8), "ab"); if (rand() < 0.8) s += __shuffle(rand, words.slice()).join("") + __str(rand, __r(rand, 0, 6), "ab"); if (!s) s = "a"; return [s, words];`),
    examples: [["barfoothefoobarman", ["foo", "bar"]], ["wordgoodgoodgoodbestword", ["word", "good", "best", "word"]], ["barfoofoobarthefoobarman", ["bar", "foo", "the"]]],
    edges: [
      ["duplicates", ["aaaa", ["a", "a"]], "Repeated words: matches overlap."],
      ["boundary", ["foobar", ["bar", "foo"]]],
      ["no-answer", ["ab", ["abc"]], "The words are longer than s."],
    ],
  },
  {
    slug: "minimum-number-of-flips-to-make-the-binary-string-alternating",
    title: "Minimum Number of Flips to Make the Binary String Alternating",
    difficulty: "Medium",
    pattern: "Sliding Window",
    fn: "minFlips",
    params: [["s", "string"]],
    returns: "number",
    hints: [
      "Moving the first character to the end any number of times gives every rotation of s. All rotations appear as windows of length n in s + s.",
      "Slide a window of length n over s + s, counting mismatches against \"0101...\" and against \"1010...\". The answer is the smallest count over all windows.",
      "t = s + s, a = 0, b = 0, best = infinity\nfor i in 0 .. 2n - 1:\n  if t[i] != (i mod 2 as a char): a = a + 1 else b = b + 1\n  if i >= n: undo the same count for index i - n\n  if i >= n - 1: best = min(best, a, b)\nreturn best",
    ],
    reference: `function minFlips(s) { const n = s.length, t = s + s; let d1 = 0, d2 = 0, best = Infinity; for (let i = 0; i < 2 * n; i++) { const want = i % 2 ? "1" : "0"; if (t[i] !== want) d1++; else d2++; if (i >= n) { const o = i - n, w2 = o % 2 ? "1" : "0"; if (t[o] !== w2) d1--; else d2--; } if (i >= n - 1) best = Math.min(best, d1, d2); } return best; }`,
    brute: `function minFlips(s) { let best = Infinity, cur = s; for (let r = 0; r < s.length; r++) { let a = 0, b = 0; for (let i = 0; i < cur.length; i++) { if (cur[i] !== (i % 2 ? "1" : "0")) a++; else b++; } best = Math.min(best, a, b); cur = cur.slice(1) + cur[0]; } return best; }`,
    fuzz: gen(`return [__str(rand, __r(rand, 3, 20), "01")];`),
    examples: [["111000"], ["010"], ["1110"]],
    edges: [
      ["all-equal", ["0000"]],
      ["boundary", ["01001001101"]],
      ["two", ["11"]],
    ],
  },
];

export const LADDER_WINDOW_SEEDED: ProblemSpec[] = DEFS.map((d) => define(d).spec);
