import { define, type ProblemDef } from "../../dsa-extras/define";
import { gen } from "../../dsa-extras/gen";
import type { ProblemSpec } from "../types";

const H = `const toA = (h) => { const a = []; for (let n = h; n; n = n.next) a.push(n.val); return a; }; const fromA = (a) => { let h = null; for (let i = a.length - 1; i >= 0; i--) h = new ListNode(a[i], h); return h; };`;
const HEAD: Array<[string, string]> = [["head", "ListNode"]];
const L1: ["ListNode"] = ["ListNode"];
const LV: ["ListNode", "value"] = ["ListNode", "value"];
const LIST = (min: number, max: number, lo = 0, hi = 9) => gen(`return [__arr(rand, __r(rand, ${min}, ${max}), ${lo}, ${hi})];`);

/** Judges for seeded LeetCode problems that the Linked List Ladder points at. LeetCode's own signatures. */
const DEFS: ProblemDef[] = [
  {
    slug: "remove-duplicates-from-sorted-list",
    title: "Remove Duplicates from Sorted List",
    difficulty: "Easy",
    pattern: "Linked List",
    fn: "deleteDuplicates",
    params: HEAD,
    returns: "ListNode",
    argTypes: L1,
    returnKind: "ListNode",
    hints: [
      "The list is sorted, so copies of a value sit next to each other.",
      "Walk with one pointer: while the next node has the same value, skip it by relinking cur.next; otherwise move on.",
      "cur = head\nwhile cur and cur.next:\n  if cur.next.val == cur.val: cur.next = cur.next.next\n  else: cur = cur.next\nreturn head",
    ],
    reference: `function deleteDuplicates(head) { let c = head; while (c && c.next) { if (c.next.val === c.val) c.next = c.next.next; else c = c.next; } return head; }`,
    brute: `function deleteDuplicates(head) { ${H} return fromA([...new Set(toA(head))]); }`,
    fuzz: gen(`return [__sorted(rand, __r(rand, 0, 12), 0, 5)];`),
    examples: [[[1, 1, 2]], [[1, 1, 2, 3, 3]]],
    edges: [
      ["empty", [[]]],
      ["all-equal", [[4, 4, 4, 4]], "Everything collapses to one node."],
      ["sorted", [[1, 2, 3]], "Nothing to remove."],
    ],
  },
  {
    slug: "delete-the-middle-node-of-a-linked-list",
    title: "Delete the Middle Node of a Linked List",
    difficulty: "Medium",
    pattern: "Fast & Slow Pointers",
    fn: "deleteMiddle",
    params: HEAD,
    returns: "ListNode",
    argTypes: L1,
    returnKind: "ListNode",
    hints: [
      "The middle is node floor(n / 2). To delete it you need the node just before it.",
      "Start fast two steps ahead (fast = head.next.next) and slow at head; when fast reaches the end, slow is just before the middle. A single node returns null.",
      "if head.next is null: return null\nslow = head, fast = head.next.next\nwhile fast and fast.next:\n  slow = slow.next; fast = fast.next.next\nslow.next = slow.next.next\nreturn head",
    ],
    reference: `function deleteMiddle(head) { if (!head.next) return null; let s = head, f = head.next.next; while (f && f.next) { s = s.next; f = f.next.next; } s.next = s.next.next; return head; }`,
    brute: `function deleteMiddle(head) { ${H} const a = toA(head); a.splice(Math.floor(a.length / 2), 1); return fromA(a); }`,
    fuzz: LIST(1, 12),
    examples: [[[1, 3, 4, 7, 1, 2, 6]], [[1, 2, 3, 4]]],
    edges: [
      ["single", [[1]], "The only node is the middle: return null."],
      ["two", [[2, 1]], "With two nodes the second one is the middle."],
      ["duplicates", [[5, 5, 5]]],
    ],
  },
  {
    slug: "maximum-twin-sum-of-a-linked-list",
    title: "Maximum Twin Sum of a Linked List",
    difficulty: "Medium",
    pattern: "Fast & Slow Pointers",
    fn: "pairSum",
    params: HEAD,
    returns: "number",
    argTypes: L1,
    hints: [
      "Node i's twin is node n - 1 - i. If you could walk the second half backwards, the twins would line up.",
      "Find the middle with fast/slow, reverse the second half, then walk both halves together and keep the largest sum.",
      "slow = fast = head\nwhile fast and fast.next: slow = slow.next; fast = fast.next.next\nreverse the list starting at slow, giving second\nbest = 0, first = head\nwhile second:\n  best = max(best, first.val + second.val)\n  first = first.next; second = second.next\nreturn best",
    ],
    reference: `function pairSum(head) { let s = head, f = head; while (f && f.next) { s = s.next; f = f.next.next; } let prev = null; while (s) { const n = s.next; s.next = prev; prev = s; s = n; } let best = 0; for (let a = head, b = prev; b; a = a.next, b = b.next) best = Math.max(best, a.val + b.val); return best; }`,
    brute: `function pairSum(head) { ${H} const a = toA(head); let best = 0; for (let i = 0; i < a.length / 2; i++) best = Math.max(best, a[i] + a[a.length - 1 - i]); return best; }`,
    fuzz: gen(`return [__arr(rand, 2 * __r(rand, 1, 6), 1, 20)];`),
    examples: [[[5, 4, 2, 1]], [[4, 2, 2, 3]]],
    edges: [
      ["two", [[1, 100000]]],
      ["all-equal", [[3, 3, 3, 3, 3, 3]]],
      ["boundary", [[1, 9, 9, 1]], "The best pair is in the middle."],
    ],
  },
  {
    slug: "odd-even-linked-list",
    title: "Odd Even Linked List",
    difficulty: "Medium",
    pattern: "Linked List",
    fn: "oddEvenList",
    params: HEAD,
    returns: "ListNode",
    argTypes: L1,
    returnKind: "ListNode",
    hints: [
      "Positions alternate odd, even, odd... Build two chains as you walk, then join them.",
      "Keep odd and even tails; link odd.next = even.next and even.next = odd.next in turn. Finally attach the even chain's head after the odd tail.",
      "if head is null: return null\nodd = head, even = head.next, evenHead = even\nwhile even and even.next:\n  odd.next = even.next; odd = odd.next\n  even.next = odd.next; even = even.next\nodd.next = evenHead\nreturn head",
    ],
    reference: `function oddEvenList(head) { if (!head) return null; let o = head, e = head.next; const eh = e; while (e && e.next) { o.next = e.next; o = o.next; e.next = o.next; e = e.next; } o.next = eh; return head; }`,
    brute: `function oddEvenList(head) { ${H} const a = toA(head); return fromA(a.filter((_, i) => i % 2 === 0).concat(a.filter((_, i) => i % 2 === 1))); }`,
    fuzz: LIST(0, 12),
    examples: [[[1, 2, 3, 4, 5]], [[2, 1, 3, 5, 6, 4, 7]]],
    edges: [
      ["empty", [[]]],
      ["two", [[1, 2]], "Already in order."],
      ["single", [[8]]],
    ],
  },
  {
    slug: "partition-list",
    title: "Partition List",
    difficulty: "Medium",
    pattern: "Linked List",
    fn: "partition",
    params: [["head", "ListNode"], ["x", "number"]],
    returns: "ListNode",
    argTypes: LV,
    returnKind: "ListNode",
    hints: [
      "Nodes less than x go first, the rest after, and both groups keep their original order.",
      "Build two lists with dummy heads (less, rest) as you walk, then link less's tail to rest's head and end rest with null.",
      "lessDummy, restDummy = new nodes; a = lessDummy, b = restDummy\nfor each node in the list:\n  if node.val < x: a.next = node; a = node\n  else: b.next = node; b = node\nb.next = null\na.next = restDummy.next\nreturn lessDummy.next",
    ],
    reference: `function partition(head, x) { const d1 = new ListNode(0), d2 = new ListNode(0); let a = d1, b = d2; for (let n = head; n; n = n.next) { if (n.val < x) { a.next = n; a = n; } else { b.next = n; b = n; } } b.next = null; a.next = d2.next; return d1.next; }`,
    brute: `function partition(head, x) { ${H} const a = toA(head); return fromA(a.filter((v) => v < x).concat(a.filter((v) => v >= x))); }`,
    fuzz: gen(`return [__arr(rand, __r(rand, 0, 12), 0, 9), __r(rand, 0, 10)];`),
    examples: [[[1, 4, 3, 2, 5, 2], 3], [[2, 1], 2]],
    edges: [
      ["empty", [[], 0]],
      ["all-equal", [[3, 3, 3], 3], "Nothing is less than x: order unchanged."],
      ["boundary", [[5, 1, 4, 0], 10], "Everything is less than x."],
    ],
  },
  {
    slug: "swap-nodes-in-pairs",
    title: "Swap Nodes in Pairs",
    difficulty: "Medium",
    pattern: "Linked List",
    fn: "swapPairs",
    params: HEAD,
    returns: "ListNode",
    argTypes: L1,
    returnKind: "ListNode",
    hints: [
      "Swap the nodes themselves, not their values. A dummy node before the head makes the first swap like every other.",
      "With prev before a pair (a, b): prev.next = b, a.next = b.next, b.next = a, then prev = a.",
      "dummy.next = head; prev = dummy\nwhile prev.next and prev.next.next:\n  a = prev.next; b = a.next\n  prev.next = b\n  a.next = b.next\n  b.next = a\n  prev = a\nreturn dummy.next",
    ],
    reference: `function swapPairs(head) { const d = new ListNode(0, head); let p = d; while (p.next && p.next.next) { const a = p.next, b = a.next; p.next = b; a.next = b.next; b.next = a; p = a; } return d.next; }`,
    brute: `function swapPairs(head) { ${H} const a = toA(head); for (let i = 0; i + 1 < a.length; i += 2) [a[i], a[i + 1]] = [a[i + 1], a[i]]; return fromA(a); }`,
    fuzz: LIST(0, 12),
    examples: [[[1, 2, 3, 4]], [[1, 2, 3]]],
    edges: [
      ["empty", [[]]],
      ["single", [[1]]],
      ["two", [[7, 8]]],
    ],
  },
  {
    slug: "rotate-list",
    title: "Rotate List",
    difficulty: "Medium",
    pattern: "Linked List",
    fn: "rotateRight",
    params: [["head", "ListNode"], ["k", "number"]],
    returns: "ListNode",
    argTypes: LV,
    returnKind: "ListNode",
    hints: [
      "Rotating by the list's length changes nothing, so only k mod n matters. Where does the new head come from?",
      "Find the length and tail, link the tail to the head (a ring), then step n - k mod n nodes to the new tail and cut there.",
      "if head is null: return null\nn = length, tail = last node\nk = k mod n; if k == 0: return head\ntail.next = head\nnewTail = node at index n - k - 1\nnewHead = newTail.next\nnewTail.next = null\nreturn newHead",
    ],
    reference: `function rotateRight(head, k) { if (!head) return null; let n = 1, t = head; while (t.next) { t = t.next; n++; } k %= n; if (!k) return head; t.next = head; let nt = head; for (let i = 0; i < n - k - 1; i++) nt = nt.next; const nh = nt.next; nt.next = null; return nh; }`,
    brute: `function rotateRight(head, k) { ${H} let a = toA(head); for (let i = 0; i < k % Math.max(a.length, 1); i++) a.unshift(a.pop()); return fromA(a); }`,
    fuzz: gen(`return [__arr(rand, __r(rand, 0, 8), 0, 9), __r(rand, 0, 20)];`),
    examples: [[[1, 2, 3, 4, 5], 2], [[0, 1, 2], 4]],
    edges: [
      ["empty", [[], 3]],
      ["boundary", [[1, 2, 3], 3], "k equals the length: unchanged."],
      ["extremes", [[1, 2], 2000000000], "Huge k: reduce it mod n first."],
    ],
  },
  {
    slug: "reorder-list",
    title: "Reorder List",
    difficulty: "Medium",
    pattern: "Linked List",
    fn: "reorderList",
    params: HEAD,
    returns: "void",
    argTypes: L1,
    returnKind: "arg0",
    hints: [
      "The order is first, last, second, second-last... The back half is needed in reverse.",
      "Split at the middle (fast/slow), reverse the second half, then merge the two halves by alternating nodes. Modify the list in place.",
      "find middle with slow / fast\nsecond = reverse(slow.next); slow.next = null\nfirst = head\nwhile second:\n  a = first.next; b = second.next\n  first.next = second; second.next = a\n  first = a; second = b",
    ],
    reference: `function reorderList(head) { if (!head) return; let s = head, f = head; while (f.next && f.next.next) { s = s.next; f = f.next.next; } let prev = null, c = s.next; s.next = null; while (c) { const n = c.next; c.next = prev; prev = c; c = n; } let a = head, b = prev; while (b) { const an = a.next, bn = b.next; a.next = b; b.next = an; a = an; b = bn; } }`,
    brute: `function reorderList(head) { const nodes = []; for (let n = head; n; n = n.next) nodes.push(n); let i = 0, j = nodes.length - 1; const order = []; while (i <= j) { order.push(nodes[i++]); if (i <= j) order.push(nodes[j--]); } for (let k = 0; k < order.length; k++) order[k].next = order[k + 1] || null; }`,
    fuzz: LIST(1, 12),
    examples: [[[1, 2, 3, 4]], [[1, 2, 3, 4, 5]]],
    edges: [
      ["single", [[1]]],
      ["two", [[1, 2]], "Already in the right order."],
      ["duplicates", [[1, 1, 2, 2, 3]]],
    ],
  },
  {
    slug: "swapping-nodes-in-a-linked-list",
    title: "Swapping Nodes in a Linked List",
    difficulty: "Medium",
    pattern: "Linked List",
    fn: "swapNodes",
    params: [["head", "ListNode"], ["k", "number"]],
    returns: "ListNode",
    argTypes: LV,
    returnKind: "ListNode",
    hints: [
      "The kth node from the start is easy. The kth from the end is the kth from the start of a gap pointer trick.",
      "Walk k - 1 steps to node a. Then start b at head and a runner at a; move both until the runner hits the tail: b is kth from the end. Swap their values.",
      "a = head moved k - 1 steps\nrunner = a, b = head\nwhile runner.next:\n  runner = runner.next; b = b.next\nswap a.val and b.val\nreturn head",
    ],
    reference: `function swapNodes(head, k) { let a = head; for (let i = 1; i < k; i++) a = a.next; let r = a, b = head; while (r.next) { r = r.next; b = b.next; } [a.val, b.val] = [b.val, a.val]; return head; }`,
    brute: `function swapNodes(head, k) { ${H} const a = toA(head); [a[k - 1], a[a.length - k]] = [a[a.length - k], a[k - 1]]; return fromA(a); }`,
    fuzz: gen(`const a = __arr(rand, __r(rand, 1, 10), 0, 9); return [a, __r(rand, 1, a.length)];`),
    examples: [[[1, 2, 3, 4, 5], 2], [[7, 9, 6, 6, 7, 8, 3, 0, 9, 5], 5]],
    edges: [
      ["single", [[1], 1]],
      ["boundary", [[1, 2, 3], 2], "The middle node swaps with itself."],
      ["two", [[1, 2], 1]],
    ],
  },
  {
    slug: "reverse-linked-list-ii",
    title: "Reverse Linked List II",
    difficulty: "Medium",
    pattern: "Linked List",
    fn: "reverseBetween",
    params: [["head", "ListNode"], ["left", "number"], ["right", "number"]],
    returns: "ListNode",
    argTypes: ["ListNode", "value", "value"],
    returnKind: "ListNode",
    hints: [
      "Only positions left..right flip. You need the node before position left so you can reattach the reversed part.",
      "Use a dummy head, walk to the node before left, then repeatedly move the node after the current one to the front of the sublist (right - left times).",
      "dummy.next = head; prev = dummy\nrepeat left - 1 times: prev = prev.next\ncur = prev.next\nrepeat right - left times:\n  nxt = cur.next\n  cur.next = nxt.next\n  nxt.next = prev.next\n  prev.next = nxt\nreturn dummy.next",
    ],
    reference: `function reverseBetween(head, left, right) { const d = new ListNode(0, head); let p = d; for (let i = 1; i < left; i++) p = p.next; const c = p.next; for (let i = 0; i < right - left; i++) { const n = c.next; c.next = n.next; n.next = p.next; p.next = n; } return d.next; }`,
    brute: `function reverseBetween(head, left, right) { ${H} const a = toA(head); return fromA([...a.slice(0, left - 1), ...a.slice(left - 1, right).reverse(), ...a.slice(right)]); }`,
    fuzz: gen(`const a = __arr(rand, __r(rand, 1, 10), 0, 9); const l = __r(rand, 1, a.length); return [a, l, __r(rand, l, a.length)];`),
    examples: [[[1, 2, 3, 4, 5], 2, 4], [[5], 1, 1]],
    edges: [
      ["boundary", [[1, 2, 3], 1, 3], "The whole list flips: the head changes."],
      ["two", [[3, 5], 1, 2]],
      ["single", [[1, 2, 3, 4], 2, 2], "left == right: nothing changes."],
    ],
  },
  {
    slug: "add-two-numbers-ii",
    title: "Add Two Numbers II",
    difficulty: "Medium",
    pattern: "Linked List",
    fn: "addTwoNumbers",
    params: [["l1", "ListNode"], ["l2", "ListNode"]],
    returns: "ListNode",
    argTypes: ["ListNode", "ListNode"],
    returnKind: "ListNode",
    hints: [
      "Digits are stored most significant first, but addition starts from the least significant digit.",
      "Push both lists' digits onto stacks (or reverse them). Pop and add with a carry, building the answer by prepending nodes.",
      "push digits of l1 onto s1, of l2 onto s2\ncarry = 0, head = null\nwhile s1 or s2 or carry:\n  sum = carry + (pop s1 or 0) + (pop s2 or 0)\n  head = new node(sum mod 10, next = head)\n  carry = sum div 10\nreturn head",
    ],
    reference: `function addTwoNumbers(l1, l2) { const a = [], b = []; for (let n = l1; n; n = n.next) a.push(n.val); for (let n = l2; n; n = n.next) b.push(n.val); let c = 0, h = null; while (a.length || b.length || c) { const s = c + (a.pop() || 0) + (b.pop() || 0); h = new ListNode(s % 10, h); c = Math.floor(s / 10); } return h; }`,
    brute: `function addTwoNumbers(l1, l2) { ${H} const s = (BigInt(toA(l1).join("")) + BigInt(toA(l2).join(""))).toString(); return fromA(s.split("").map(Number)); }`,
    fuzz: gen(`const num = () => { const n = __r(rand, 1, 8); const a = __arr(rand, n, 0, 9); if (n > 1 && a[0] === 0) a[0] = __r(rand, 1, 9); return a; }; return [num(), num()];`),
    examples: [[[7, 2, 4, 3], [5, 6, 4]], [[2, 4, 3], [5, 6, 4]]],
    edges: [
      ["zeros", [[0], [0]]],
      ["boundary", [[9, 9, 9], [1]], "A carry adds a new leading digit."],
      ["extremes", [[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1], [5, 6, 4]], "21 digits: too big for a 64-bit integer."],
    ],
  },
  {
    slug: "remove-duplicates-from-sorted-list-ii",
    title: "Remove Duplicates from Sorted List II",
    difficulty: "Medium",
    pattern: "Linked List",
    fn: "deleteDuplicates",
    params: HEAD,
    returns: "ListNode",
    argTypes: L1,
    returnKind: "ListNode",
    hints: [
      "This time every value that repeats is removed completely, including its first copy. The head itself may go.",
      "Use a dummy head and a prev pointer. When cur and cur.next share a value, skip the whole run and link prev past it; otherwise advance prev.",
      "dummy.next = head; prev = dummy\nwhile prev.next:\n  cur = prev.next\n  if cur.next and cur.next.val == cur.val:\n    while cur.next and cur.next.val == cur.val: cur = cur.next\n    prev.next = cur.next\n  else: prev = cur\nreturn dummy.next",
    ],
    reference: `function deleteDuplicates(head) { const d = new ListNode(0, head); let p = d; while (p.next) { let c = p.next; if (c.next && c.next.val === c.val) { while (c.next && c.next.val === c.val) c = c.next; p.next = c.next; } else p = c; } return d.next; }`,
    brute: `function deleteDuplicates(head) { ${H} const a = toA(head), cnt = new Map(); for (const v of a) cnt.set(v, (cnt.get(v) || 0) + 1); return fromA(a.filter((v) => cnt.get(v) === 1)); }`,
    fuzz: gen(`return [__sorted(rand, __r(rand, 0, 12), 0, 6)];`),
    examples: [[[1, 2, 3, 3, 4, 4, 5]], [[1, 1, 1, 2, 3]]],
    edges: [
      ["all-equal", [[2, 2, 2]], "Everything repeats: an empty list."],
      ["empty", [[]]],
      ["boundary", [[1, 2, 2]], "The repeated run is at the tail."],
    ],
  },
  {
    slug: "remove-nodes-from-linked-list",
    title: "Remove Nodes From Linked List",
    difficulty: "Medium",
    pattern: "Monotonic Stack",
    fn: "removeNodes",
    params: HEAD,
    returns: "ListNode",
    argTypes: L1,
    returnKind: "ListNode",
    hints: [
      "A node survives only if nothing to its right is strictly greater. That's easiest to decide walking from the right.",
      "Reverse the list, keep nodes that are >= the running maximum, then reverse back. (A monotonic stack works too.)",
      "reverse the list\nmax = minus infinity, keep = empty\nfor each node:\n  if node.val >= max: max = node.val; add node to keep\nlink keep in order, then reverse it back\nreturn the head",
    ],
    reference: `function removeNodes(head) { const rev = (h) => { let p = null; while (h) { const n = h.next; h.next = p; p = h; h = n; } return p; }; let h = rev(head), mx = -Infinity; const d = new ListNode(0); let t = d; while (h) { const n = h.next; if (h.val >= mx) { mx = h.val; t.next = h; t = h; } h = n; } t.next = null; return rev(d.next); }`,
    brute: `function removeNodes(head) { ${H} const a = toA(head); return fromA(a.filter((v, i) => a.slice(i + 1).every((w) => w <= v))); }`,
    fuzz: LIST(1, 12, 1, 9),
    examples: [[[5, 2, 13, 3, 8]], [[1, 1, 1, 1]]],
    edges: [
      ["single", [[4]]],
      ["sorted", [[1, 2, 3, 4]], "Only the last node survives."],
      ["reverse-sorted", [[9, 7, 4, 1]], "Nothing is removed."],
    ],
  },
  {
    slug: "insertion-sort-list",
    title: "Insertion Sort List",
    difficulty: "Medium",
    pattern: "Linked List",
    fn: "insertionSortList",
    params: HEAD,
    returns: "ListNode",
    argTypes: L1,
    returnKind: "ListNode",
    hints: [
      "Build a sorted list one node at a time. For each node, where does it go in the sorted part?",
      "Keep a dummy head for the sorted list. Detach each node, walk from the dummy to the last node with a smaller value, and splice it in.",
      "dummy = new node\ncur = head\nwhile cur:\n  nxt = cur.next\n  p = dummy\n  while p.next and p.next.val < cur.val: p = p.next\n  cur.next = p.next; p.next = cur\n  cur = nxt\nreturn dummy.next",
    ],
    reference: `function insertionSortList(head) { const d = new ListNode(0); let c = head; while (c) { const n = c.next; let p = d; while (p.next && p.next.val < c.val) p = p.next; c.next = p.next; p.next = c; c = n; } return d.next; }`,
    brute: `function insertionSortList(head) { ${H} return fromA(toA(head).sort((a, b) => a - b)); }`,
    fuzz: LIST(1, 12, -9, 9),
    examples: [[[4, 2, 1, 3]], [[-1, 5, 3, 4, 0]]],
    edges: [
      ["single", [[1]]],
      ["reverse-sorted", [[5, 4, 3, 2, 1]]],
      ["duplicates", [[2, 1, 2, 1]]],
    ],
  },
  {
    slug: "sort-list",
    title: "Sort List",
    difficulty: "Medium",
    pattern: "Linked List",
    fn: "sortList",
    params: HEAD,
    returns: "ListNode",
    argTypes: L1,
    returnKind: "ListNode",
    hints: [
      "O(n log n) on a linked list: which sort needs no random access?",
      "Merge sort: split at the middle with fast/slow pointers, sort both halves recursively, and merge the two sorted lists.",
      "sortList(head):\n  if head is null or head.next is null: return head\n  find the middle with slow / fast; cut after slow\n  left = sortList(head); right = sortList(second half)\n  return merge(left, right)",
    ],
    reference: `function sortList(head) { if (!head || !head.next) return head; let s = head, f = head.next; while (f && f.next) { s = s.next; f = f.next.next; } const r = s.next; s.next = null; let a = sortList(head), b = sortList(r); const d = new ListNode(0); let t = d; while (a && b) { if (a.val <= b.val) { t.next = a; a = a.next; } else { t.next = b; b = b.next; } t = t.next; } t.next = a || b; return d.next; }`,
    brute: `function sortList(head) { ${H} return fromA(toA(head).sort((a, b) => a - b)); }`,
    fuzz: LIST(0, 14, -9, 9),
    examples: [[[4, 2, 1, 3]], [[-1, 5, 3, 4, 0]]],
    edges: [
      ["empty", [[]]],
      ["all-equal", [[7, 7, 7]]],
      ["large", [Array.from({ length: 1800 }, (_, i) => (i * 7919) % 100)], "1800 nodes: an O(n^2) sort starts to show."],
    ],
  },
  {
    slug: "split-linked-list-in-parts",
    title: "Split Linked List in Parts",
    difficulty: "Medium",
    pattern: "Linked List",
    fn: "splitListToParts",
    params: [["head", "ListNode"], ["k", "number"]],
    returns: "ListNode[]",
    argTypes: LV,
    returnKind: "ListNode[]",
    hints: [
      "With n nodes and k parts, each part gets n div k nodes and the first n mod k parts get one extra.",
      "Count n, then for each of the k parts walk the right number of nodes, cut after the last one and record the part's head (null when you run out).",
      "n = length of the list\nbase = n div k, extra = n mod k\ncur = head\nfor i from 0 to k - 1:\n  add cur to parts\n  size = base + (1 if i < extra else 0)\n  move cur forward size - 1 nodes (if size > 0)\n  if cur: nxt = cur.next; cur.next = null; cur = nxt\nreturn parts",
    ],
    reference: `function splitListToParts(head, k) { let n = 0; for (let c = head; c; c = c.next) n++; const base = Math.floor(n / k), extra = n % k, out = []; let c = head; for (let i = 0; i < k; i++) { out.push(c); const size = base + (i < extra ? 1 : 0); for (let j = 1; j < size && c; j++) c = c.next; if (c && size > 0) { const nx = c.next; c.next = null; c = nx; } } return out; }`,
    brute: `function splitListToParts(head, k) { ${H} const a = toA(head), out = []; let i = 0; for (let p = 0; p < k; p++) { const size = Math.floor(a.length / k) + (p < a.length % k ? 1 : 0); out.push(fromA(a.slice(i, i + size))); i += size; } return out; }`,
    fuzz: gen(`return [__arr(rand, __r(rand, 0, 12), 0, 9), __r(rand, 1, 6)];`),
    examples: [[[1, 2, 3], 5], [[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], 3]],
    edges: [
      ["empty", [[], 3], "Every part is empty."],
      ["single", [[4, 5], 1], "One part holds the whole list."],
      ["boundary", [[1, 2, 3, 4], 4], "One node per part."],
    ],
  },
  {
    slug: "merge-in-between-linked-lists",
    title: "Merge In Between Linked Lists",
    difficulty: "Medium",
    pattern: "Linked List",
    fn: "mergeInBetween",
    params: [["list1", "ListNode"], ["a", "number"], ["b", "number"], ["list2", "ListNode"]],
    returns: "ListNode",
    argTypes: ["ListNode", "value", "value", "ListNode"],
    returnKind: "ListNode",
    hints: [
      "You need the node just before position a and the node just after position b.",
      "Walk to node a - 1 and node b + 1, then link (a - 1).next to list2's head and list2's tail to node b + 1.",
      "before = node at index a - 1 in list1\nafter = node at index b + 1 in list1\ntail2 = last node of list2\nbefore.next = list2\ntail2.next = after\nreturn list1",
    ],
    reference: `function mergeInBetween(list1, a, b, list2) { let p = list1; for (let i = 0; i < a - 1; i++) p = p.next; let q = p; for (let i = a - 1; i <= b; i++) q = q.next; let t = list2; while (t.next) t = t.next; p.next = list2; t.next = q; return list1; }`,
    brute: `function mergeInBetween(list1, a, b, list2) { ${H} const x = toA(list1); return fromA([...x.slice(0, a), ...toA(list2), ...x.slice(b + 1)]); }`,
    fuzz: gen(`const n = __r(rand, 3, 10); const a = __r(rand, 1, n - 2); return [__arr(rand, n, 0, 9), a, __r(rand, a, n - 2), __arr(rand, __r(rand, 1, 4), 10, 19)];`),
    examples: [[[10, 1, 13, 6, 9, 5], 3, 4, [1000000, 1000001, 1000002]], [[0, 1, 2, 3, 4, 5, 6], 2, 5, [1000000, 1000001, 1000002, 1000003, 1000004]]],
    edges: [
      ["min-size", [[0, 1, 2], 1, 1, [9]]],
      ["boundary", [[0, 1, 2, 3, 4], 1, 3, [7, 8]], "Everything except the two ends is replaced."],
      ["single", [[5, 6, 7, 8], 2, 2, [1]]],
    ],
  },
  {
    slug: "merge-k-sorted-lists",
    title: "Merge k Sorted Lists",
    difficulty: "Hard",
    pattern: "Linked List",
    fn: "mergeKLists",
    params: [["lists", "ListNode[]"]],
    returns: "ListNode",
    argTypes: ["ListNode[]"],
    returnKind: "ListNode",
    hints: [
      "Merging lists one after another is O(k * N). Can you always take the smallest current head among all lists quickly?",
      "Either use a min-heap of current heads, or merge in pairs (divide and conquer) so each node is merged O(log k) times.",
      "if lists is empty: return null\nwhile more than one list remains:\n  merged = []\n  for i in steps of 2:\n    add merge(lists[i], lists[i + 1] or null) to merged\n  lists = merged\nreturn lists[0]",
    ],
    reference: `function mergeKLists(lists) { const merge = (a, b) => { const d = new ListNode(0); let t = d; while (a && b) { if (a.val <= b.val) { t.next = a; a = a.next; } else { t.next = b; b = b.next; } t = t.next; } t.next = a || b; return d.next; }; if (!lists.length) return null; let ls = lists; while (ls.length > 1) { const m = []; for (let i = 0; i < ls.length; i += 2) m.push(merge(ls[i], ls[i + 1] || null)); ls = m; } return ls[0]; }`,
    brute: `function mergeKLists(lists) { ${H} return fromA(lists.flatMap(toA).sort((a, b) => a - b)); }`,
    fuzz: gen(`return [Array.from({ length: __r(rand, 0, 5) }, () => __sorted(rand, __r(rand, 0, 5), -5, 9))];`),
    examples: [[[[1, 4, 5], [1, 3, 4], [2, 6]]], [[[2], [], [-1]]]],
    edges: [
      ["empty", [[]], "No lists at all."],
      ["null-input", [[[]]], "One list, and it's empty."],
      ["duplicates", [[[1, 1], [1, 1], [1]]]],
    ],
  },
  {
    slug: "reverse-nodes-in-k-group",
    title: "Reverse Nodes in k-Group",
    difficulty: "Hard",
    pattern: "Linked List",
    fn: "reverseKGroup",
    params: [["head", "ListNode"], ["k", "number"]],
    returns: "ListNode",
    argTypes: LV,
    returnKind: "ListNode",
    hints: [
      "Reverse k nodes at a time; a final group with fewer than k nodes stays as it is. Before reversing, check that k nodes exist.",
      "Keep prevTail (the node before the group). Find the kth node; if it's missing, stop. Reverse the group, link prevTail to the new front and the old front to the next group.",
      "dummy.next = head; prevTail = dummy\nloop:\n  kth = prevTail moved k steps; if kth is null: stop\n  nextGroup = kth.next\n  reverse the nodes from prevTail.next to kth\n  first = prevTail.next\n  prevTail.next = kth\n  first.next = nextGroup\n  prevTail = first\nreturn dummy.next",
    ],
    reference: `function reverseKGroup(head, k) { const d = new ListNode(0, head); let pt = d; for (;;) { let kth = pt; for (let i = 0; i < k && kth; i++) kth = kth.next; if (!kth) break; const ng = kth.next, first = pt.next; let prev = ng, c = first; while (c !== ng) { const n = c.next; c.next = prev; prev = c; c = n; } pt.next = kth; pt = first; } return d.next; }`,
    brute: `function reverseKGroup(head, k) { ${H} const a = toA(head), out = []; for (let i = 0; i < a.length; i += k) { const g = a.slice(i, i + k); out.push(...(g.length === k ? g.reverse() : g)); } return fromA(out); }`,
    fuzz: gen(`const a = __arr(rand, __r(rand, 1, 12), 0, 9); return [a, __r(rand, 1, a.length)];`),
    examples: [[[1, 2, 3, 4, 5], 2], [[1, 2, 3, 4, 5], 3]],
    edges: [
      ["single", [[1, 2, 3], 1], "k = 1: nothing changes."],
      ["boundary", [[1, 2, 3, 4], 4], "One group: the whole list reverses."],
      ["min-size", [[7], 1]],
    ],
  },
];

export const LADDER_LISTS_SEEDED: ProblemSpec[] = DEFS.map((d) => define(d).spec);
