import { define, type ProblemDef } from "../../dsa-extras/define";
import { gen } from "../../dsa-extras/gen";
import type { ProblemSpec } from "../types";

/**
 * LeetCode design problems are judged through `runOps(ops)`: the first operation is the constructor call
 * (`["LRUCache", 2]`), every later one is `[method, ...args]`, and the answer is what each call returns
 * (`null` for the constructor and for methods that return nothing), just like LeetCode's output.
 */
const OPS_DRIVER = (cls: string) =>
  `/**\n * Runs the operations and collects each result. Don't change this function.\n * The first operation is the constructor call.\n * @param {Array<Array<string | number>>} ops\n * @return {Array<number | boolean | null>}\n */\nfunction runOps(ops) {\n  const [[, ...ctorArgs], ...calls] = ops;\n  const obj = new ${cls}(...ctorArgs);\n  return [null, ...calls.map(([op, ...args]) => {\n    const out = obj[op](...args);\n    return out === undefined ? null : out;\n  })];\n}`;
const opsFn = (cls: string, body: string) => `${body}\nfunction runOps(ops) { const [[, ...ctorArgs], ...calls] = ops; const obj = new ${cls}(...ctorArgs); return [null, ...calls.map(([op, ...args]) => { const out = obj[op](...args); return out === undefined ? null : out; })]; }`;

export function design(d: Omit<ProblemDef, "fn" | "params" | "returns" | "starter"> & { cls: string; ctor?: string; methods: string[] }): ProblemDef {
  const { cls, ctor = "", methods, ...rest } = d;
  const stubs = methods.map((m) => `  ${m} {\n    \n  }`).join("\n");
  return {
    ...rest,
    fn: "runOps",
    params: [["ops", "Array<Array<string | number>>"]],
    returns: "Array<number | boolean | null>",
    starter: `class ${cls} {\n  constructor(${ctor}) {\n    \n  }\n${stubs}\n}\n\n${OPS_DRIVER(cls)}`,
    reference: opsFn(cls, d.reference),
    brute: opsFn(cls, d.brute),
  };
}

/** Random valid operation lists: `size` tracks how many items are stored so removals only happen when allowed. */
const stackOpsGen = (ctor: string, push: string, reads: string[], pop: string) =>
  gen(`const ops = [[${JSON.stringify(ctor)}]]; let size = 0; const reads = ${JSON.stringify(reads)}; const n = __r(rand, 1, 14); for (let i = 0; i < n; i++) { const r = rand(); if (size === 0 || r < 0.45) { ops.push([${JSON.stringify(push)}, __r(rand, -5, 9)]); size++; } else if (r < 0.65) { ops.push([${JSON.stringify(pop)}]); size--; } else ops.push([__pick(rand, reads)]); } return [ops];`);

const cacheOpsGen = (cls: string) =>
  gen(`const ops = [[${JSON.stringify(cls)}, __r(rand, 1, 3)]]; const n = __r(rand, 1, 16); for (let i = 0; i < n; i++) ops.push(rand() < 0.5 ? ["get", __r(rand, 1, 5)] : ["put", __r(rand, 1, 5), __r(rand, 1, 20)]); return [ops];`);

const BALANCED = `function __balanced(rand, pairs) { var s = "", open = 0, left = pairs; while (left > 0 || open > 0) { if (left > 0 && (open === 0 || rand() < 0.5)) { s += "("; open++; left--; } else { s += ")"; open--; } } return s; }`;

const DEFS: ProblemDef[] = [
  design({
    slug: "implement-stack-using-queues",
    title: "Implement Stack using Queues",
    difficulty: "Easy",
    pattern: "Design (Coding)",
    cls: "MyStack",
    methods: ["push(x)", "pop()", "top()", "empty()"],
    hints: [
      "A queue gives you the oldest item; a stack needs the newest. Can you rearrange the queue right after each push?",
      "After pushing x onto the queue, rotate the queue size - 1 times (dequeue and re-enqueue) so x comes out first. pop/top then just read the front.",
      "push(x):\n  enqueue x\n  repeat size - 1 times: enqueue(dequeue())\npop(): return dequeue()\ntop(): return front\nempty(): return size == 0",
    ],
    reference: `class MyStack { constructor() { this.q = []; } push(x) { this.q.push(x); for (let i = 0; i < this.q.length - 1; i++) this.q.push(this.q.shift()); } pop() { return this.q.shift(); } top() { return this.q[0]; } empty() { return this.q.length === 0; } }`,
    brute: `class MyStack { constructor() { this.a = []; } push(x) { this.a.push(x); } pop() { return this.a.pop(); } top() { return this.a[this.a.length - 1]; } empty() { return !this.a.length; } }`,
    fuzz: stackOpsGen("MyStack", "push", ["top", "empty"], "pop"),
    examples: [[[["MyStack"], ["push", 1], ["push", 2], ["top"], ["pop"], ["empty"]]], [[["MyStack"], ["push", 5], ["pop"], ["empty"]]]],
    edges: [
      ["empty", [[["MyStack"], ["empty"]]], "A new stack is empty."],
      ["order", [[["MyStack"], ["push", 1], ["push", 2], ["push", 3], ["pop"], ["pop"], ["pop"]]], "Last in, first out."],
      ["duplicates", [[["MyStack"], ["push", 4], ["push", 4], ["pop"], ["top"]]]],
    ],
  }),
  design({
    slug: "implement-queue-using-stacks",
    title: "Implement Queue using Stacks",
    difficulty: "Easy",
    pattern: "Design (Coding)",
    cls: "MyQueue",
    methods: ["push(x)", "pop()", "peek()", "empty()"],
    hints: [
      "Pouring one stack into another reverses its order. When should you pour?",
      "Keep an in-stack for pushes and an out-stack for pops. Only when the out-stack is empty, move everything from in to out. Each item moves at most once: amortised O(1).",
      "push(x): push x onto inStack\npeek():\n  if outStack is empty: move every item from inStack to outStack\n  return top of outStack\npop(): peek(); return pop of outStack\nempty(): both stacks empty",
    ],
    reference: `class MyQueue { constructor() { this.i = []; this.o = []; } push(x) { this.i.push(x); } move() { if (!this.o.length) while (this.i.length) this.o.push(this.i.pop()); } pop() { this.move(); return this.o.pop(); } peek() { this.move(); return this.o[this.o.length - 1]; } empty() { return !this.i.length && !this.o.length; } }`,
    brute: `class MyQueue { constructor() { this.a = []; } push(x) { this.a.push(x); } pop() { return this.a.shift(); } peek() { return this.a[0]; } empty() { return !this.a.length; } }`,
    fuzz: stackOpsGen("MyQueue", "push", ["peek", "empty"], "pop"),
    examples: [[[["MyQueue"], ["push", 1], ["push", 2], ["peek"], ["pop"], ["empty"]]], [[["MyQueue"], ["push", 5], ["pop"], ["empty"]]]],
    edges: [
      ["empty", [[["MyQueue"], ["empty"]]]],
      ["order", [[["MyQueue"], ["push", 1], ["push", 2], ["push", 3], ["pop"], ["pop"], ["pop"]]], "First in, first out."],
      ["boundary", [[["MyQueue"], ["push", 1], ["pop"], ["push", 2], ["push", 3], ["pop"], ["peek"]]], "Pushes arrive after the out-stack was filled."],
    ],
  }),
  {
    slug: "baseball-game",
    title: "Baseball Game",
    difficulty: "Easy",
    pattern: "Stack",
    fn: "calPoints",
    params: [["operations", "string[]"]],
    returns: "number",
    hints: [
      "Every operation looks only at the most recent valid scores. Which structure gives you the latest items?",
      "Keep a stack of scores: a number pushes it, '+' pushes the sum of the top two, 'D' pushes double the top, 'C' pops. Return the stack's sum.",
      "stack = []\nfor op in operations:\n  if op == \"+\": push top + second\n  else if op == \"D\": push 2 * top\n  else if op == \"C\": pop\n  else: push number(op)\nreturn sum of stack",
    ],
    reference: `function calPoints(operations) { const s = []; for (const o of operations) { if (o === "+") s.push(s[s.length - 1] + s[s.length - 2]); else if (o === "D") s.push(2 * s[s.length - 1]); else if (o === "C") s.pop(); else s.push(+o); } return s.reduce((a, b) => a + b, 0); }`,
    brute: `function calPoints(operations) { let s = []; for (const o of operations) { if (o === "C") s = s.slice(0, -1); else if (o === "D") s = [...s, s[s.length - 1] * 2]; else if (o === "+") s = [...s, s[s.length - 1] + s[s.length - 2]]; else s = [...s, parseInt(o, 10)]; } let t = 0; for (const v of s) t += v; return t; }`,
    fuzz: gen(`const ops = []; let size = 0; const n = __r(rand, 1, 12); for (let i = 0; i < n; i++) { const r = rand(); if (size >= 2 && r < 0.2) { ops.push("+"); size++; } else if (size >= 1 && r < 0.35) { ops.push("D"); size++; } else if (size >= 1 && r < 0.5) { ops.push("C"); size--; } else { ops.push(String(__r(rand, -9, 9))); size++; } } return [ops];`),
    examples: [[["5", "2", "C", "D", "+"]], [["5", "-2", "4", "C", "D", "9", "+", "+"]]],
    edges: [
      ["empty", [["1", "C"]], "Everything cancelled: 0."],
      ["negatives", [["-3", "D"]]],
      ["single", [["7"]]],
    ],
  },
  {
    slug: "make-the-string-great",
    title: "Make The String Great",
    difficulty: "Easy",
    pattern: "Stack",
    fn: "makeGood",
    params: [["s", "string"]],
    returns: "string",
    hints: [
      "Removing a bad pair can create a new bad pair from its neighbours. That's the same shape as matching brackets.",
      "Use a stack of characters: if the top is the same letter in the other case, pop it; otherwise push.",
      "stack = []\nfor ch in s:\n  if stack not empty and top != ch and lower(top) == lower(ch): pop\n  else: push ch\nreturn stack joined",
    ],
    reference: `function makeGood(s) { const st = []; for (const c of s) { const t = st[st.length - 1]; if (t !== undefined && t !== c && t.toLowerCase() === c.toLowerCase()) st.pop(); else st.push(c); } return st.join(""); }`,
    brute: `function makeGood(s) { for (;;) { let found = false; for (let i = 0; i + 1 < s.length; i++) if (s[i] !== s[i + 1] && s[i].toLowerCase() === s[i + 1].toLowerCase()) { s = s.slice(0, i) + s.slice(i + 2); found = true; break; } if (!found) return s; } }`,
    fuzz: gen(`return [__str(rand, __r(rand, 1, 12), "aAbB")];`),
    examples: [["leEeetcode"], ["abBAcC"]],
    edges: [
      ["single-char", ["s"]],
      ["case-mix", ["aA"], "Exactly one bad pair: the empty string."],
      ["all-equal", ["aaAA"], "Removals cascade from the middle out."],
    ],
  },
  design({
    slug: "number-of-recent-calls",
    title: "Number of Recent Calls",
    difficulty: "Easy",
    pattern: "Queue",
    cls: "RecentCounter",
    methods: ["ping(t)"],
    hints: [
      "Pings arrive in increasing time order. Which old pings can never count again?",
      "Keep a queue of ping times. On ping(t), add t and drop times from the front that are less than t - 3000. The queue's length is the answer.",
      "ping(t):\n  enqueue t\n  while front < t - 3000: dequeue\n  return size of the queue",
    ],
    reference: `class RecentCounter { constructor() { this.q = []; this.h = 0; } ping(t) { this.q.push(t); while (this.q[this.h] < t - 3000) this.h++; return this.q.length - this.h; } }`,
    brute: `class RecentCounter { constructor() { this.all = []; } ping(t) { this.all.push(t); return this.all.filter((x) => x >= t - 3000).length; } }`,
    fuzz: gen(`const ops = [["RecentCounter"]]; let t = 0; const n = __r(rand, 1, 12); for (let i = 0; i < n; i++) { t += __r(rand, 1, 1500); ops.push(["ping", t]); } return [ops];`),
    examples: [[[["RecentCounter"], ["ping", 1], ["ping", 100], ["ping", 3001], ["ping", 3002]]], [[["RecentCounter"], ["ping", 5]]]],
    edges: [
      ["boundary", [[["RecentCounter"], ["ping", 1000], ["ping", 4000]]], "Exactly 3000 apart: both still count."],
      ["min-size", [[["RecentCounter"], ["ping", 1]]]],
      ["large", [[["RecentCounter"], ["ping", 1], ["ping", 10000], ["ping", 20000]]], "Each ping forgets everything before it."],
    ],
  }),
  design({
    slug: "min-stack",
    title: "Min Stack",
    difficulty: "Medium",
    pattern: "Design (Coding)",
    cls: "MinStack",
    methods: ["push(val)", "pop()", "top()", "getMin()"],
    hints: [
      "Scanning for the minimum is O(n). What if every stack entry remembered the minimum at the time it was pushed?",
      "Push pairs (value, min so far). getMin reads the top pair's min; popping restores the previous minimum automatically.",
      "push(val): push (val, min(val, current min or val))\npop(): pop\ntop(): top value\ngetMin(): top min",
    ],
    reference: `class MinStack { constructor() { this.s = []; } push(v) { const m = this.s.length ? Math.min(v, this.s[this.s.length - 1][1]) : v; this.s.push([v, m]); } pop() { this.s.pop(); } top() { return this.s[this.s.length - 1][0]; } getMin() { return this.s[this.s.length - 1][1]; } }`,
    brute: `class MinStack { constructor() { this.a = []; } push(v) { this.a.push(v); } pop() { this.a.pop(); } top() { return this.a[this.a.length - 1]; } getMin() { return Math.min(...this.a); } }`,
    fuzz: stackOpsGen("MinStack", "push", ["top", "getMin"], "pop"),
    examples: [[[["MinStack"], ["push", -2], ["push", 0], ["push", -3], ["getMin"], ["pop"], ["top"], ["getMin"]]], [[["MinStack"], ["push", 1], ["getMin"]]]],
    edges: [
      ["duplicates", [[["MinStack"], ["push", 0], ["push", 0], ["pop"], ["getMin"]]], "Popping one copy of the minimum leaves the other."],
      ["negatives", [[["MinStack"], ["push", -1], ["push", -5], ["pop"], ["getMin"]]]],
      ["reverse-sorted", [[["MinStack"], ["push", 3], ["push", 2], ["push", 1], ["pop"], ["pop"], ["getMin"]]]],
    ],
  }),
  {
    slug: "simplify-path",
    title: "Simplify Path",
    difficulty: "Medium",
    pattern: "Stack",
    fn: "simplifyPath",
    params: [["path", "string"]],
    returns: "string",
    hints: [
      "Split the path on '/'. Each piece either goes deeper, stays put, or goes up one level.",
      "Use a stack of directory names: skip empty pieces and '.', pop on '..' (if not empty), push anything else. Join with '/' and prefix '/'.",
      "stack = []\nfor part in path split by \"/\":\n  if part == \"\" or part == \".\": skip\n  else if part == \"..\": pop if stack not empty\n  else: push part\nreturn \"/\" + stack joined by \"/\"",
    ],
    reference: `function simplifyPath(path) { const st = []; for (const p of path.split("/")) { if (!p || p === ".") continue; if (p === "..") st.pop(); else st.push(p); } return "/" + st.join("/"); }`,
    brute: `function simplifyPath(path) { let parts = path.split("/").filter((p) => p && p !== "."); let changed = true; while (changed) { changed = false; for (let i = 0; i < parts.length; i++) if (parts[i] === "..") { parts.splice(Math.max(0, i - 1), i === 0 ? 1 : 2); changed = true; break; } } return "/" + parts.join("/"); }`,
    fuzz: gen(`const parts = Array.from({ length: __r(rand, 0, 6) }, () => __pick(rand, ["a", "b", "..", ".", "", "abc", "..."])); return ["/" + parts.join("/") + (rand() < 0.3 ? "/" : "")];`),
    examples: [["/home/"], ["/home//foo/"]],
    edges: [
      ["extremes", ["/../"], "Going above the root stays at the root."],
      ["min-size", ["/"]],
      ["boundary", ["/.../a/../b/c/../d/./"], "\"...\" is a valid directory name."],
    ],
  },
  {
    slug: "validate-stack-sequences",
    title: "Validate Stack Sequences",
    difficulty: "Medium",
    pattern: "Stack",
    fn: "validateStackSequences",
    params: [["pushed", "number[]"], ["popped", "number[]"]],
    returns: "boolean",
    hints: [
      "Just replay it. When is popping the next expected value allowed?",
      "Push values in order; after each push, while the stack's top equals popped[j], pop and advance j. Valid if the stack ends empty.",
      "stack = [], j = 0\nfor x in pushed:\n  push x\n  while stack not empty and top == popped[j]: pop; j += 1\nreturn stack is empty",
    ],
    reference: `function validateStackSequences(pushed, popped) { const s = []; let j = 0; for (const x of pushed) { s.push(x); while (s.length && s[s.length - 1] === popped[j]) { s.pop(); j++; } } return s.length === 0; }`,
    brute: `function validateStackSequences(pushed, popped) { const go = (i, j, st) => { if (j === popped.length) return true; if (st.length && st[st.length - 1] === popped[j] && go(i, j + 1, st.slice(0, -1))) return true; if (i < pushed.length && go(i + 1, j, st.concat(pushed[i]))) return true; return false; }; return go(0, 0, []); }`,
    fuzz: gen(`const n = __r(rand, 1, 7); const pushed = __shuffle(rand, Array.from({ length: n }, (_, i) => i)); let popped; if (rand() < 0.5) { const st = []; popped = []; let i = 0; while (popped.length < n) { if (i < n && (st.length === 0 || rand() < 0.5)) st.push(pushed[i++]); else popped.push(st.pop()); } } else popped = __shuffle(rand, pushed.slice()); return [pushed, popped];`),
    examples: [[[1, 2, 3, 4, 5], [4, 5, 3, 2, 1]], [[1, 2, 3, 4, 5], [4, 3, 5, 1, 2]]],
    edges: [
      ["single", [[1], [1]]],
      ["reverse-sorted", [[1, 2, 3], [3, 2, 1]], "Push everything, then pop everything."],
      ["sorted", [[1, 2, 3], [1, 2, 3]], "Pop right after each push."],
    ],
  },
  {
    slug: "asteroid-collision",
    title: "Asteroid Collision",
    difficulty: "Medium",
    pattern: "Stack",
    fn: "asteroidCollision",
    params: [["asteroids", "number[]"]],
    returns: "number[]",
    hints: [
      "A collision only happens when a left-moving asteroid meets right-moving ones before it. Which earlier asteroids does it meet first?",
      "Keep a stack of survivors. For a negative asteroid, pop smaller positive tops; if the top is equal, both explode; if the top is bigger, it dies; otherwise push it.",
      "stack = []\nfor a in asteroids:\n  alive = true\n  while alive and a < 0 and stack top > 0:\n    if top < -a: pop; continue\n    if top == -a: pop\n    alive = false\n  if alive: push a\nreturn stack",
    ],
    reference: `function asteroidCollision(asteroids) { const s = []; for (const a of asteroids) { let alive = true; while (alive && a < 0 && s.length && s[s.length - 1] > 0) { const t = s[s.length - 1]; if (t < -a) { s.pop(); continue; } if (t === -a) s.pop(); alive = false; } if (alive) s.push(a); } return s; }`,
    brute: `function asteroidCollision(asteroids) { let a = asteroids.slice(); for (;;) { let i = 0; while (i + 1 < a.length && !(a[i] > 0 && a[i + 1] < 0)) i++; if (i + 1 >= a.length) return a; const x = a[i], y = -a[i + 1]; if (x > y) a.splice(i + 1, 1); else if (x < y) a.splice(i, 1); else a.splice(i, 2); } }`,
    fuzz: gen(`return [Array.from({ length: __r(rand, 1, 10) }, () => (rand() < 0.5 ? 1 : -1) * __r(rand, 1, 6))];`),
    examples: [[[5, 10, -5]], [[8, -8]]],
    edges: [
      ["sorted", [[-2, -1, 1, 2]], "Moving apart: no collisions."],
      ["boundary", [[10, 2, -5]], "The left-mover destroys one, then loses to the next."],
      ["all-equal", [[1, -1, 1, -1]]],
    ],
  },
  {
    slug: "remove-all-adjacent-duplicates-in-string-ii",
    title: "Remove All Adjacent Duplicates in String II",
    difficulty: "Medium",
    pattern: "Stack",
    fn: "removeDuplicates",
    params: [["s", "string"], ["k", "number"]],
    returns: "string",
    hints: [
      "Removing k equal letters can bring two runs together. Track runs, not single letters.",
      "Keep a stack of [char, count]. Same as the top: increment, and pop when it reaches k. Different: push [ch, 1]. Rebuild the string at the end.",
      "stack = []\nfor ch in s:\n  if stack not empty and top.char == ch:\n    top.count += 1\n    if top.count == k: pop\n  else: push (ch, 1)\nreturn each char repeated count times, in order",
    ],
    reference: `function removeDuplicates(s, k) { const st = []; for (const c of s) { if (st.length && st[st.length - 1][0] === c) { if (++st[st.length - 1][1] === k) st.pop(); } else st.push([c, 1]); } return st.map(([c, n]) => c.repeat(n)).join(""); }`,
    brute: `function removeDuplicates(s, k) { for (;;) { let found = false; for (let i = 0; i + k <= s.length; i++) { let ok = true; for (let j = 1; j < k; j++) if (s[i + j] !== s[i]) { ok = false; break; } if (ok) { s = s.slice(0, i) + s.slice(i + k); found = true; break; } } if (!found) return s; } }`,
    fuzz: gen(`return [__str(rand, __r(rand, 1, 14), "ab"), __r(rand, 2, 3)];`),
    examples: [["abcd", 2], ["deeedbbcccbdaa", 3]],
    edges: [
      ["all-equal", ["aaaa", 2], "Two removals: the empty string."],
      ["boundary", ["pbbcggttciiippooaais", 2]],
      ["single-char", ["a", 2]],
    ],
  },
  {
    slug: "score-of-parentheses",
    title: "Score of Parentheses",
    difficulty: "Medium",
    pattern: "Stack",
    fn: "scoreOfParentheses",
    params: [["s", "string"]],
    returns: "number",
    hints: [
      "() is 1, AB adds, (A) doubles. A stack of partial scores per nesting level fits this naturally.",
      "Push 0 on '('. On ')', pop v and add max(2 * v, 1) to the new top. Start with a 0 on the stack for the outer level.",
      "stack = [0]\nfor ch in s:\n  if ch == '(': push 0\n  else:\n    v = pop\n    top += max(2 * v, 1)\nreturn stack[0]",
    ],
    reference: `function scoreOfParentheses(s) { const st = [0]; for (const c of s) { if (c === "(") st.push(0); else { const v = st.pop(); st[st.length - 1] += Math.max(2 * v, 1); } } return st[0]; }`,
    brute: `function scoreOfParentheses(s) { if (!s) return 0; let bal = 0, total = 0, start = 0; for (let i = 0; i < s.length; i++) { bal += s[i] === "(" ? 1 : -1; if (bal === 0) { const inner = s.slice(start + 1, i); total += inner ? 2 * scoreOfParentheses(inner) : 1; start = i + 1; } } return total; }`,
    fuzz: gen(`${BALANCED} return [__balanced(rand, __r(rand, 1, 7))];`),
    examples: [["()"], ["(())"]],
    edges: [
      ["two", ["()()"]],
      ["boundary", ["(()(()))"], "Nested and side by side together."],
      ["large", ["((((((((((()))))))))))"], "Ten doublings: 1024."],
    ],
  },
  {
    slug: "exclusive-time-of-functions",
    title: "Exclusive Time of Functions",
    difficulty: "Medium",
    pattern: "Stack",
    fn: "exclusiveTime",
    params: [["n", "number"], ["logs", "string[]"]],
    returns: "number[]",
    hints: [
      "Calls nest like brackets. The running function is always the one on top of a call stack.",
      "Keep a stack of ids and the previous timestamp. On start at t: credit the current top with t - prev, push, prev = t. On end at t: credit the top with t - prev + 1, pop, prev = t + 1.",
      "stack = [], prev = 0, res = n zeros\nfor log in logs:\n  id, kind, t = parse log\n  if kind == \"start\":\n    if stack not empty: res[top] += t - prev\n    push id; prev = t\n  else:\n    res[pop] += t - prev + 1\n    prev = t + 1\nreturn res",
    ],
    reference: `function exclusiveTime(n, logs) { const res = new Array(n).fill(0), st = []; let prev = 0; for (const l of logs) { const [id, kind, ts] = l.split(":"); const t = +ts; if (kind === "start") { if (st.length) res[st[st.length - 1]] += t - prev; st.push(+id); prev = t; } else { res[st.pop()] += t - prev + 1; prev = t + 1; } } return res; }`,
    brute: `function exclusiveTime(n, logs) { const ev = logs.map((l) => { const [id, kind, t] = l.split(":"); return [+id, kind, +t]; }); const last = ev[ev.length - 1][2]; const owner = new Array(last + 1).fill(-1), st = []; let k = 0; for (let t = 0; t <= last; t++) { while (k < ev.length && ev[k][1] === "start" && ev[k][2] === t) { st.push(ev[k][0]); k++; } if (st.length) owner[t] = st[st.length - 1]; while (k < ev.length && ev[k][1] === "end" && ev[k][2] === t) { st.pop(); k++; } } const res = new Array(n).fill(0); for (const o of owner) if (o >= 0) res[o]++; return res; }`,
    fuzz: gen(`const n = __r(rand, 1, 3); const logs = [], st = []; let t = 0, starts = __r(rand, 1, 5); logs.push("0:start:0"); st.push(0); starts--; while (st.length) { t += __r(rand, 1, 3); if (starts > 0 && rand() < 0.5) { const id = __r(rand, 0, n - 1); logs.push(id + ":start:" + t); st.push(id); starts--; } else logs.push(st.pop() + ":end:" + t); } return [n, logs];`),
    examples: [[2, ["0:start:0", "1:start:2", "1:end:5", "0:end:6"]], [1, ["0:start:0", "0:start:2", "0:end:5", "0:start:6", "0:end:6", "0:end:7"]]],
    edges: [
      ["single", [1, ["0:start:0", "0:end:0"]], "Starts and ends in the same unit: 1."],
      ["reuse", [2, ["0:start:0", "0:start:2", "0:end:5", "1:start:7", "1:end:7", "0:end:8"]], "A function calls itself."],
      ["boundary", [2, ["0:start:0", "1:start:1", "1:end:1", "0:end:2"]]],
    ],
  },
  {
    slug: "basic-calculator-ii",
    title: "Basic Calculator II",
    difficulty: "Medium",
    pattern: "Stack",
    fn: "calculate",
    params: [["s", "string"]],
    returns: "number",
    hints: [
      "'*' and '/' bind tighter than '+' and '-'. What if you settle them immediately and leave the additions for the end?",
      "Scan numbers with the operator before them: '+' pushes n, '-' pushes -n, '*' and '/' replace the top with top * n or trunc(top / n). Sum the stack.",
      "stack = [], num = 0, op = '+'\nfor each char c (plus one final pass):\n  if c is a digit: num = num * 10 + c\n  if c is an operator or at the end:\n    if op == '+': push num\n    if op == '-': push -num\n    if op == '*': push pop * num\n    if op == '/': push trunc(pop / num)\n    op = c, num = 0\nreturn sum of stack",
    ],
    reference: `function calculate(s) { const st = []; let num = 0, op = "+"; for (let i = 0; i <= s.length; i++) { const c = s[i]; if (c >= "0" && c <= "9") { num = num * 10 + (c.charCodeAt(0) - 48); continue; } if (c === " ") continue; if (op === "+") st.push(num); else if (op === "-") st.push(-num); else if (op === "*") st.push(st.pop() * num); else st.push(Math.trunc(st.pop() / num)); op = c; num = 0; } return st.reduce((a, b) => a + b, 0); }`,
    brute: `function calculate(s) { const t = s.replace(/ /g, "").match(/\\d+|[-+*/]/g); const nums = [+t[0]], ops = []; for (let i = 1; i < t.length; i += 2) { const op = t[i], v = +t[i + 1]; if (op === "*") nums[nums.length - 1] *= v; else if (op === "/") nums[nums.length - 1] = Math.trunc(nums[nums.length - 1] / v); else { ops.push(op); nums.push(v); } } let r = nums[0]; for (let i = 0; i < ops.length; i++) r = ops[i] === "+" ? r + nums[i + 1] : r - nums[i + 1]; return r; }`,
    fuzz: gen(`const k = __r(rand, 0, 5); let s = String(__r(rand, 0, 20)); for (let i = 0; i < k; i++) { const op = __pick(rand, ["+", "-", "*", "/"]); s += (rand() < 0.3 ? " " : "") + op + (rand() < 0.3 ? " " : "") + (op === "/" ? __r(rand, 1, 9) : __r(rand, 0, 20)); } return [s];`),
    examples: [["3+2*2"], [" 3/2 "]],
    edges: [
      ["single", ["42"]],
      ["negatives", ["1-7/2"], "7/2 truncates to 3, then 1 - 3 = -2."],
      ["boundary", [" 3+5 / 2 "]],
    ],
  },
  {
    slug: "dota2-senate",
    title: "Dota2 Senate",
    difficulty: "Medium",
    pattern: "Queue",
    fn: "predictPartyVictory",
    params: [["senate", "string"]],
    returns: "string",
    hints: [
      "Each senator's best move is to ban the next opposing senator who would act. Order matters, so think in turns.",
      "Put the indexes of R and D senators in two queues. Compare the fronts: the smaller index bans the other and re-enters its queue with index + n. The non-empty queue wins.",
      "qr, qd = indexes of 'R' and 'D'\nwhile both non-empty:\n  r = dequeue qr; d = dequeue qd\n  if r < d: enqueue qr with r + n\n  else: enqueue qd with d + n\nreturn \"Radiant\" if qr non-empty else \"Dire\"",
    ],
    reference: `function predictPartyVictory(senate) { const n = senate.length, r = [], d = []; for (let i = 0; i < n; i++) (senate[i] === "R" ? r : d).push(i); let i = 0, j = 0; while (i < r.length && j < d.length) { if (r[i] < d[j]) r.push(r[i] + n); else d.push(d[j] + n); i++; j++; } return i < r.length ? "Radiant" : "Dire"; }`,
    brute: `function predictPartyVictory(senate) { const a = senate.split(""), banned = new Array(a.length).fill(false); for (;;) { for (let i = 0; i < a.length; i++) { if (banned[i]) continue; const foe = a[i] === "R" ? "D" : "R"; let hit = -1; for (let k = 1; k < a.length; k++) { const j = (i + k) % a.length; if (!banned[j] && a[j] === foe) { hit = j; break; } } if (hit < 0) return a[i] === "R" ? "Radiant" : "Dire"; banned[hit] = true; } } }`,
    fuzz: gen(`return [__str(rand, __r(rand, 1, 12), "RD")];`),
    examples: [["RD"], ["RDD"]],
    edges: [
      ["single-char", ["D"]],
      ["all-equal", ["RRRR"]],
      ["boundary", ["DDRRR"], "D acts first, twice."],
    ],
  },
  {
    slug: "next-greater-element-ii",
    title: "Next Greater Element II",
    difficulty: "Medium",
    pattern: "Monotonic Stack",
    fn: "nextGreaterElements",
    params: [["nums", "number[]"]],
    returns: "number[]",
    hints: [
      "The array is circular: the answer may wrap around to the start. How can one pass of a stack see the wrap?",
      "Walk indexes 0..2n-1 using i mod n, with a stack of indexes still waiting for a greater value. Pop and fill while the current value is greater; push only in the first pass.",
      "res = n copies of -1, stack = []\nfor i from 0 to 2n - 1:\n  v = nums[i mod n]\n  while stack not empty and nums[top] < v:\n    res[pop] = v\n  if i < n: push i\nreturn res",
    ],
    reference: `function nextGreaterElements(nums) { const n = nums.length, res = new Array(n).fill(-1), st = []; for (let i = 0; i < 2 * n; i++) { const v = nums[i % n]; while (st.length && nums[st[st.length - 1]] < v) res[st.pop()] = v; if (i < n) st.push(i); } return res; }`,
    brute: `function nextGreaterElements(nums) { const n = nums.length; return nums.map((v, i) => { for (let k = 1; k < n; k++) if (nums[(i + k) % n] > v) return nums[(i + k) % n]; return -1; }); }`,
    fuzz: gen(`return [__arr(rand, __r(rand, 1, 10), -3, 6)];`),
    examples: [[[1, 2, 1]], [[1, 2, 3, 4, 3]]],
    edges: [
      ["single", [[5]]],
      ["all-equal", [[2, 2, 2]], "Nothing is greater: all -1."],
      ["reverse-sorted", [[5, 4, 3, 2, 1]], "Every answer wraps around to 5."],
    ],
  },
  design({
    slug: "online-stock-span",
    title: "Online Stock Span",
    difficulty: "Medium",
    pattern: "Monotonic Stack",
    cls: "StockSpanner",
    methods: ["next(price)"],
    hints: [
      "Today's span swallows the spans of every earlier day with a price <= today's. Do you need to keep those days around?",
      "Keep a stack of (price, span) with strictly decreasing prices. On next(price), pop every entry with price <= today's and add its span; push (price, total).",
      "next(price):\n  span = 1\n  while stack not empty and top.price <= price:\n    span += pop.span\n  push (price, span)\n  return span",
    ],
    reference: `class StockSpanner { constructor() { this.s = []; } next(p) { let span = 1; while (this.s.length && this.s[this.s.length - 1][0] <= p) span += this.s.pop()[1]; this.s.push([p, span]); return span; } }`,
    brute: `class StockSpanner { constructor() { this.a = []; } next(p) { this.a.push(p); let c = 0; for (let i = this.a.length - 1; i >= 0 && this.a[i] <= p; i--) c++; return c; } }`,
    fuzz: gen(`const ops = [["StockSpanner"]]; const n = __r(rand, 1, 12); for (let i = 0; i < n; i++) ops.push(["next", __r(rand, 1, 10)]); return [ops];`),
    examples: [[[["StockSpanner"], ["next", 100], ["next", 80], ["next", 60], ["next", 70], ["next", 60], ["next", 75], ["next", 85]]], [[["StockSpanner"], ["next", 5]]]],
    edges: [
      ["sorted", [[["StockSpanner"], ["next", 1], ["next", 2], ["next", 3]]], "Rising prices: the span keeps growing."],
      ["all-equal", [[["StockSpanner"], ["next", 4], ["next", 4], ["next", 4]]], "Equal prices count (<=)."],
      ["reverse-sorted", [[["StockSpanner"], ["next", 9], ["next", 5], ["next", 2]]]],
    ],
  }),
  {
    slug: "remove-k-digits",
    title: "Remove K Digits",
    difficulty: "Medium",
    pattern: "Monotonic Stack",
    fn: "removeKdigits",
    params: [["num", "string"], ["k", "number"]],
    returns: "string",
    hints: [
      "The leftmost digits matter most. When does dropping a digit make the number smaller?",
      "Keep an increasing stack: while k > 0 and the top is bigger than the current digit, pop (k -= 1). Drop any remaining k from the end, strip leading zeros, return \"0\" if empty.",
      "stack = []\nfor d in num:\n  while k > 0 and stack not empty and top > d: pop; k -= 1\n  push d\nremove k digits from the end\nstrip leading zeros\nreturn result or \"0\"",
    ],
    reference: `function removeKdigits(num, k) { const st = []; for (const d of num) { while (k > 0 && st.length && st[st.length - 1] > d) { st.pop(); k--; } st.push(d); } st.length -= Math.min(k, st.length); const r = st.join("").replace(/^0+/, ""); return r || "0"; }`,
    brute: `function removeKdigits(num, k) { let s = num; for (let t = 0; t < k; t++) { let i = 0; while (i + 1 < s.length && s[i] <= s[i + 1]) i++; s = s.slice(0, i) + s.slice(i + 1); } s = s.replace(/^0+/, ""); return s || "0"; }`,
    fuzz: gen(`const s = __str(rand, __r(rand, 1, 10), "0123459"); return [s, __r(rand, 0, s.length)];`),
    examples: [["1432219", 3], ["10200", 1]],
    edges: [
      ["boundary", ["10", 2], "Remove everything: \"0\"."],
      ["zeros", ["100200", 1], "Leading zeros disappear after removing the 1."],
      ["sorted", ["12345", 2], "Increasing digits: drop from the end."],
    ],
  },
  {
    slug: "car-fleet",
    title: "Car Fleet",
    difficulty: "Medium",
    pattern: "Monotonic Stack",
    fn: "carFleet",
    params: [["target", "number"], ["position", "number[]"], ["speed", "number[]"]],
    returns: "number",
    hints: [
      "A car can only be blocked by cars ahead of it. Process cars from the one closest to the target.",
      "Sort by position descending and compute each car's time to the target. A car whose time is larger than the slowest fleet ahead starts a new fleet; otherwise it joins.",
      "sort cars by position, largest first\nfleets = 0, slowest = 0\nfor each car:\n  t = (target - position) / speed\n  if t > slowest:\n    fleets += 1\n    slowest = t\nreturn fleets",
    ],
    reference: `function carFleet(target, position, speed) { const cars = position.map((p, i) => [p, (target - p) / speed[i]]).sort((a, b) => b[0] - a[0]); let f = 0, slow = 0; for (const [, t] of cars) if (t > slow) { f++; slow = t; } return f; }`,
    brute: `function carFleet(target, position, speed) { const n = position.length; let fleets = 0; for (let i = 0; i < n; i++) { const ti = (target - position[i]) / speed[i]; let blocked = false; for (let j = 0; j < n; j++) if (position[j] > position[i] && (target - position[j]) / speed[j] >= ti) { blocked = true; break; } if (!blocked) fleets++; } return fleets; }`,
    fuzz: gen(`const target = __r(rand, 5, 30); const s = new Set(); const n = __r(rand, 1, Math.min(8, target)); while (s.size < n) s.add(__r(rand, 0, target - 1)); const pos = [...s]; return [target, pos, pos.map(() => __r(rand, 1, 5))];`),
    examples: [[12, [10, 8, 0, 5, 3], [2, 4, 1, 1, 3]], [10, [3], [3]]],
    edges: [
      ["all-equal", [12, [0, 6, 9], [4, 2, 1]], "All three arrive at the same moment: one fleet."],
      ["sorted", [10, [0, 4, 8], [1, 1, 1]], "Same speed: nobody catches up."],
      ["boundary", [10, [6, 8], [4, 2]], "The back car catches up exactly at the target."],
    ],
  },
  {
    slug: "132-pattern",
    title: "132 Pattern",
    difficulty: "Medium",
    pattern: "Monotonic Stack",
    fn: "find132pattern",
    params: [["nums", "number[]"]],
    returns: "boolean",
    hints: [
      "Fix the '3' (nums[j]). You want a smaller '1' before it and a '2' after it that sits between them.",
      "Scan from the right with a decreasing stack. Popped values are candidates for the '2' (keep the largest as third). If you meet a value smaller than third, that's the '1'.",
      "third = minus infinity, stack = []\nfor i from n - 1 down to 0:\n  if nums[i] < third: return true\n  while stack not empty and top < nums[i]: third = pop\n  push nums[i]\nreturn false",
    ],
    reference: `function find132pattern(nums) { let third = -Infinity; const st = []; for (let i = nums.length - 1; i >= 0; i--) { if (nums[i] < third) return true; while (st.length && st[st.length - 1] < nums[i]) third = st.pop(); st.push(nums[i]); } return false; }`,
    brute: `function find132pattern(nums) { const n = nums.length; for (let i = 0; i < n; i++) for (let j = i + 1; j < n; j++) for (let k = j + 1; k < n; k++) if (nums[i] < nums[k] && nums[k] < nums[j]) return true; return false; }`,
    fuzz: gen(`return [__arr(rand, __r(rand, 1, 9), -4, 6)];`),
    examples: [[[1, 2, 3, 4]], [[3, 1, 4, 2]]],
    edges: [
      ["negatives", [[-1, 3, 2, 0]]],
      ["all-equal", [[1, 1, 1]], "Strict inequalities: equal values never form the pattern."],
      ["two", [[1, 2]]],
    ],
  },
  {
    slug: "sum-of-subarray-minimums",
    title: "Sum of Subarray Minimums",
    difficulty: "Medium",
    pattern: "Monotonic Stack",
    fn: "sumSubarrayMins",
    params: [["arr", "number[]"]],
    returns: "number",
    hints: [
      "Count, for each element, how many subarrays have it as their minimum. Its contribution is value * that count.",
      "With previous-less and next-less-or-equal boundaries (two monotonic stacks), arr[i] is the minimum of left * right subarrays. Sum modulo 1e9+7.",
      "left[i] = distance to the previous strictly smaller element\nright[i] = distance to the next smaller-or-equal element\nanswer = sum of arr[i] * left[i] * right[i], mod 1e9+7",
    ],
    reference: `function sumSubarrayMins(arr) { const n = arr.length, M = 1000000007n, left = new Array(n), right = new Array(n); let st = []; for (let i = 0; i < n; i++) { while (st.length && arr[st[st.length - 1]] > arr[i]) st.pop(); left[i] = st.length ? i - st[st.length - 1] : i + 1; st.push(i); } st = []; for (let i = n - 1; i >= 0; i--) { while (st.length && arr[st[st.length - 1]] >= arr[i]) st.pop(); right[i] = st.length ? st[st.length - 1] - i : n - i; st.push(i); } let s = 0n; for (let i = 0; i < n; i++) s = (s + BigInt(arr[i]) * BigInt(left[i]) * BigInt(right[i])) % M; return Number(s); }`,
    brute: `function sumSubarrayMins(arr) { let s = 0; for (let i = 0; i < arr.length; i++) { let m = Infinity; for (let j = i; j < arr.length; j++) { m = Math.min(m, arr[j]); s = (s + m) % 1000000007; } } return s; }`,
    fuzz: gen(`return [__arr(rand, __r(rand, 1, 12), 1, 9)];`),
    examples: [[[3, 1, 2, 4]], [[11, 81, 94, 43, 3]]],
    edges: [
      ["single", [[5]]],
      ["all-equal", [[2, 2, 2]], "Ties must be counted once per subarray."],
      ["large", [Array.from({ length: 1000 }, () => 30000)], "Big sums: take the modulus as you go."],
    ],
  },
  {
    slug: "remove-duplicate-letters",
    title: "Remove Duplicate Letters",
    difficulty: "Medium",
    pattern: "Monotonic Stack",
    fn: "removeDuplicateLetters",
    params: [["s", "string"]],
    returns: "string",
    hints: [
      "You may drop an earlier letter if a smaller letter comes next and the earlier one appears again later.",
      "Count the last index of each letter. Keep a stack and a 'used' set: skip used letters; while the top is larger than c and occurs later, pop it; push c.",
      "last[c] = last index of c\nstack = [], used = empty set\nfor i, c in s:\n  if c in used: skip\n  while stack not empty and top > c and last[top] > i:\n    remove pop from used\n  push c; add c to used\nreturn stack joined",
    ],
    reference: `function removeDuplicateLetters(s) { const last = {}; for (let i = 0; i < s.length; i++) last[s[i]] = i; const st = [], used = new Set(); for (let i = 0; i < s.length; i++) { const c = s[i]; if (used.has(c)) continue; while (st.length && st[st.length - 1] > c && last[st[st.length - 1]] > i) used.delete(st.pop()); st.push(c); used.add(c); } return st.join(""); }`,
    brute: `function removeDuplicateLetters(s) { let res = ""; while (s.length) { const letters = [...new Set(s)].sort(); for (const c of letters) { const rest = s.slice(s.indexOf(c)); if (letters.every((x) => rest.includes(x))) { res += c; s = rest.slice(1).split(c).join(""); break; } } } return res; }`,
    fuzz: gen(`return [__str(rand, __r(rand, 1, 12), "abcd")];`),
    examples: [["bcabc"], ["cbacdcbc"]],
    edges: [
      ["single-char", ["z"]],
      ["all-equal", ["aaaa"]],
      ["reverse-sorted", ["dcba"], "No letter repeats, so nothing can be reordered."],
    ],
  },
  {
    slug: "maximal-rectangle",
    title: "Maximal Rectangle",
    difficulty: "Hard",
    pattern: "Monotonic Stack",
    fn: "maximalRectangle",
    params: [["matrix", "character[][]"]],
    returns: "number",
    hints: [
      "Treat each row as the floor of a histogram: the bar height at column c is how many 1s stack up above it.",
      "Update heights row by row (reset to 0 on '0') and run largest-rectangle-in-histogram on each row with a monotonic stack.",
      "heights = zeros\nbest = 0\nfor each row:\n  for c: heights[c] = heights[c] + 1 if row[c] == '1' else 0\n  best = max(best, largest rectangle in heights)\nreturn best",
    ],
    reference: `function maximalRectangle(matrix) { const C = matrix[0].length, h = new Array(C).fill(0); let best = 0; for (const row of matrix) { for (let c = 0; c < C; c++) h[c] = row[c] === "1" ? h[c] + 1 : 0; const st = []; for (let i = 0; i <= C; i++) { const cur = i === C ? 0 : h[i]; while (st.length && h[st[st.length - 1]] >= cur) { const top = st.pop(); const w = st.length ? i - st[st.length - 1] - 1 : i; best = Math.max(best, h[top] * w); } st.push(i); } } return best; }`,
    brute: `function maximalRectangle(matrix) { const R = matrix.length, C = matrix[0].length; let best = 0; for (let r1 = 0; r1 < R; r1++) for (let c1 = 0; c1 < C; c1++) for (let r2 = r1; r2 < R; r2++) for (let c2 = c1; c2 < C; c2++) { let ok = true; for (let r = r1; r <= r2 && ok; r++) for (let c = c1; c <= c2; c++) if (matrix[r][c] !== "1") { ok = false; break; } if (ok) best = Math.max(best, (r2 - r1 + 1) * (c2 - c1 + 1)); } return best; }`,
    fuzz: gen(`const R = __r(rand, 1, 5), C = __r(rand, 1, 5); return [Array.from({ length: R }, () => Array.from({ length: C }, () => (rand() < 0.65 ? "1" : "0")))];`),
    examples: [[[["1", "0", "1", "0", "0"], ["1", "0", "1", "1", "1"], ["1", "1", "1", "1", "1"], ["1", "0", "0", "1", "0"]]], [[["0"]]]],
    edges: [
      ["single", [[["1"]]]],
      ["all-equal", [[["1", "1"], ["1", "1"]]], "The whole matrix."],
      ["boundary", [[["0", "1"], ["1", "0"]]], "Only single cells."],
    ],
  },
  {
    slug: "sliding-window-maximum",
    title: "Sliding Window Maximum",
    difficulty: "Hard",
    pattern: "Monotonic Queue",
    fn: "maxSlidingWindow",
    params: [["nums", "number[]"], ["k", "number"]],
    returns: "number[]",
    hints: [
      "When a bigger value enters the window, every smaller value before it can never be the maximum again.",
      "Keep a deque of indexes with decreasing values. Push i after popping smaller values from the back; drop the front when it leaves the window; the front is each window's max.",
      "dq = empty deque, res = []\nfor i from 0 to n - 1:\n  while dq not empty and nums[back] <= nums[i]: pop back\n  push i at back\n  if front <= i - k: pop front\n  if i >= k - 1: add nums[front] to res\nreturn res",
    ],
    reference: `function maxSlidingWindow(nums, k) { const dq = [], res = []; let h = 0; for (let i = 0; i < nums.length; i++) { while (dq.length > h && nums[dq[dq.length - 1]] <= nums[i]) dq.pop(); dq.push(i); if (dq[h] <= i - k) h++; if (i >= k - 1) res.push(nums[dq[h]]); } return res; }`,
    brute: `function maxSlidingWindow(nums, k) { const res = []; for (let i = 0; i + k <= nums.length; i++) res.push(Math.max(...nums.slice(i, i + k))); return res; }`,
    fuzz: gen(`const a = __arr(rand, __r(rand, 1, 12), -5, 9); return [a, __r(rand, 1, a.length)];`),
    examples: [[[1, 3, -1, -3, 5, 3, 6, 7], 3], [[1], 1]],
    edges: [
      ["boundary", [[4, 2, 7], 3], "k = n: one window."],
      ["reverse-sorted", [[9, 8, 7, 6], 2], "The maximum leaves the window each step."],
      ["duplicates", [[1, 3, 3, 1], 2]],
    ],
  },
  {
    slug: "longest-valid-parentheses",
    title: "Longest Valid Parentheses",
    difficulty: "Hard",
    pattern: "Stack",
    fn: "longestValidParentheses",
    params: [["s", "string"]],
    returns: "number",
    hints: [
      "A valid run ends where some ')' closes the run's first '('. What marks where the current run started?",
      "Keep a stack of indexes with a base marker (-1 initially). Push on '('. On ')', pop; if the stack is empty, push i as the new base; otherwise the run length is i - top.",
      "stack = [-1], best = 0\nfor i, ch in s:\n  if ch == '(': push i\n  else:\n    pop\n    if stack is empty: push i\n    else: best = max(best, i - top)\nreturn best",
    ],
    reference: `function longestValidParentheses(s) { const st = [-1]; let best = 0; for (let i = 0; i < s.length; i++) { if (s[i] === "(") st.push(i); else { st.pop(); if (!st.length) st.push(i); else best = Math.max(best, i - st[st.length - 1]); } } return best; }`,
    brute: `function longestValidParentheses(s) { const ok = (t) => { let b = 0; for (const c of t) { b += c === "(" ? 1 : -1; if (b < 0) return false; } return b === 0; }; let best = 0; for (let i = 0; i < s.length; i++) for (let j = i + 2; j <= s.length; j += 2) if (ok(s.slice(i, j))) best = Math.max(best, j - i); return best; }`,
    fuzz: gen(`return [__str(rand, __r(rand, 0, 14), "()")];`),
    examples: [["(()"], [")()())"]],
    edges: [
      ["empty", [""]],
      ["boundary", ["()(())"], "Two valid runs side by side join up."],
      ["reverse-sorted", ["))(("], "No valid run at all."],
    ],
  },
  {
    slug: "basic-calculator",
    title: "Basic Calculator",
    difficulty: "Hard",
    pattern: "Stack",
    fn: "calculate",
    params: [["s", "string"]],
    returns: "number",
    hints: [
      "Only + and - (and parentheses). A minus before '(' flips the sign of everything inside.",
      "Scan with a running result and sign. On '(' push (result, sign) and reset; on ')' finish the inner value, then result = savedResult + savedSign * inner.",
      "result = 0, sign = 1, num = 0, stack = []\nfor ch in s:\n  digit: num = num * 10 + ch\n  '+' or '-': result += sign * num; num = 0; sign = +1 or -1\n  '(': push result, push sign; result = 0; sign = 1\n  ')': result += sign * num; num = 0\n       result = result * pop + pop\nreturn result + sign * num",
    ],
    reference: `function calculate(s) { let res = 0, sign = 1, num = 0; const st = []; for (const c of s) { if (c >= "0" && c <= "9") num = num * 10 + (c.charCodeAt(0) - 48); else if (c === "+" || c === "-") { res += sign * num; num = 0; sign = c === "+" ? 1 : -1; } else if (c === "(") { st.push(res, sign); res = 0; sign = 1; } else if (c === ")") { res += sign * num; num = 0; const sg = st.pop(), prev = st.pop(); res = prev + sg * res; } } return res + sign * num; }`,
    brute: `function calculate(s) { const t = s.replace(/ /g, ""); let i = 0; const expr = () => { let v = term(); while (t[i] === "+" || t[i] === "-") { const op = t[i++]; const w = term(); v = op === "+" ? v + w : v - w; } return v; }; const term = () => { if (t[i] === "-") { i++; return -term(); } if (t[i] === "(") { i++; const v = expr(); i++; return v; } let n = 0; while (i < t.length && t[i] >= "0" && t[i] <= "9") n = n * 10 + +t[i++]; return n; }; return expr(); }`,
    fuzz: gen(`const sp = () => (rand() < 0.25 ? " " : ""); const expr = (d) => { let s = (rand() < 0.2 ? "-" : "") + atom(d); const k = __r(rand, 0, 3); for (let i = 0; i < k; i++) s += sp() + __pick(rand, ["+", "-"]) + sp() + atom(d); return s; }; const atom = (d) => (d > 0 && rand() < 0.35 ? "(" + expr(d - 1) + ")" : String(__r(rand, 0, 30))); return [expr(2)];`),
    examples: [["1 + 1"], [" 2-1 + 2 "]],
    edges: [
      ["negatives", ["-(2+3)"], "A unary minus before a parenthesis."],
      ["boundary", ["(1+(4+5+2)-3)+(6+8)"]],
      ["single", ["7"]],
    ],
  },
  design({
    slug: "maximum-frequency-stack",
    title: "Maximum Frequency Stack",
    difficulty: "Hard",
    pattern: "Design (Coding)",
    cls: "FreqStack",
    methods: ["push(val)", "pop()"],
    hints: [
      "pop removes the most frequent value, breaking ties by recency. What if you kept one stack per frequency level?",
      "Track freq[val] and a stack for each frequency. push increments freq and pushes onto stacks[freq]. pop takes from stacks[maxFreq], decrements that value's freq, and lowers maxFreq when that stack empties.",
      "push(val):\n  freq[val] += 1; f = freq[val]\n  maxFreq = max(maxFreq, f)\n  push val onto group[f]\npop():\n  val = pop from group[maxFreq]\n  freq[val] -= 1\n  if group[maxFreq] is empty: maxFreq -= 1\n  return val",
    ],
    reference: `class FreqStack { constructor() { this.f = new Map(); this.g = new Map(); this.m = 0; } push(v) { const f = (this.f.get(v) || 0) + 1; this.f.set(v, f); if (f > this.m) this.m = f; if (!this.g.has(f)) this.g.set(f, []); this.g.get(f).push(v); } pop() { const st = this.g.get(this.m); const v = st.pop(); this.f.set(v, this.f.get(v) - 1); if (!st.length) this.m--; return v; } }`,
    brute: `class FreqStack { constructor() { this.a = []; } push(v) { this.a.push(v); } pop() { const cnt = new Map(); for (const v of this.a) cnt.set(v, (cnt.get(v) || 0) + 1); const mx = Math.max(...cnt.values()); for (let i = this.a.length - 1; i >= 0; i--) if (cnt.get(this.a[i]) === mx) return this.a.splice(i, 1)[0]; } }`,
    fuzz: gen(`const ops = [["FreqStack"]]; let size = 0; const n = __r(rand, 1, 14); for (let i = 0; i < n; i++) { if (size === 0 || rand() < 0.6) { ops.push(["push", __r(rand, 1, 4)]); size++; } else { ops.push(["pop"]); size--; } } return [ops];`),
    examples: [[[["FreqStack"], ["push", 5], ["push", 7], ["push", 5], ["push", 7], ["push", 4], ["push", 5], ["pop"], ["pop"], ["pop"], ["pop"]]], [[["FreqStack"], ["push", 1], ["pop"]]]],
    edges: [
      ["order", [[["FreqStack"], ["push", 1], ["push", 2], ["push", 3], ["pop"], ["pop"]]], "All frequencies tie: plain stack order."],
      ["all-equal", [[["FreqStack"], ["push", 2], ["push", 2], ["pop"], ["pop"]]]],
      ["boundary", [[["FreqStack"], ["push", 1], ["push", 1], ["push", 2], ["pop"], ["pop"], ["pop"]]], "After one pop, 1 and 2 tie and the more recent 2 goes next."],
    ],
  }),
  design({
    slug: "lru-cache",
    title: "LRU Cache",
    difficulty: "Medium",
    pattern: "Design (Coding)",
    cls: "LRUCache",
    ctor: "capacity",
    methods: ["get(key)", "put(key, value)"],
    hints: [
      "You need O(1) lookup by key and O(1) 'move to most recent' plus 'evict least recent'.",
      "A hash map from key to node of a doubly linked list ordered by recency (or a Map, which keeps insertion order): get moves the key to the end; put inserts at the end and evicts the front when over capacity.",
      "get(key):\n  if key missing: return -1\n  move key to the most-recent end\n  return its value\nput(key, value):\n  if key present: remove it\n  insert key at the most-recent end\n  if size > capacity: evict the least-recent key",
    ],
    reference: `class LRUCache { constructor(c) { this.c = c; this.m = new Map(); } get(k) { if (!this.m.has(k)) return -1; const v = this.m.get(k); this.m.delete(k); this.m.set(k, v); return v; } put(k, v) { this.m.delete(k); this.m.set(k, v); if (this.m.size > this.c) this.m.delete(this.m.keys().next().value); } }`,
    brute: `class LRUCache { constructor(c) { this.c = c; this.a = []; } get(k) { const i = this.a.findIndex((e) => e[0] === k); if (i < 0) return -1; const e = this.a.splice(i, 1)[0]; this.a.push(e); return e[1]; } put(k, v) { const i = this.a.findIndex((e) => e[0] === k); if (i >= 0) this.a.splice(i, 1); this.a.push([k, v]); if (this.a.length > this.c) this.a.shift(); } }`,
    fuzz: cacheOpsGen("LRUCache"),
    examples: [[[["LRUCache", 2], ["put", 1, 1], ["put", 2, 2], ["get", 1], ["put", 3, 3], ["get", 2], ["put", 4, 4], ["get", 1], ["get", 3], ["get", 4]]], [[["LRUCache", 1], ["put", 2, 1], ["get", 2]]]],
    edges: [
      ["min-size", [[["LRUCache", 1], ["put", 1, 1], ["put", 2, 2], ["get", 1], ["get", 2]]], "Capacity 1: every new key evicts the old one."],
      ["reuse", [[["LRUCache", 2], ["put", 1, 1], ["put", 1, 5], ["get", 1]]], "Updating a key overwrites its value."],
      ["order", [[["LRUCache", 2], ["put", 1, 1], ["put", 2, 2], ["get", 1], ["put", 3, 3], ["get", 2], ["get", 1]]], "get(1) made key 2 the least recent."],
    ],
  }),
  design({
    slug: "lfu-cache",
    title: "LFU Cache",
    difficulty: "Hard",
    pattern: "Design (Coding)",
    cls: "LFUCache",
    ctor: "capacity",
    methods: ["get(key)", "put(key, value)"],
    hints: [
      "Evict the key with the lowest use count, and among those the least recently used. Group keys by their count.",
      "Keep key -> (value, count), count -> ordered set of keys (a Map keeps order), and the current minimum count. Each access moves the key to count + 1; a new key starts at count 1 and resets minCount to 1.",
      "touch(key): move key from group[count] to group[count + 1]; if group[minCount] is empty: minCount += 1\nget(key): if missing: return -1; touch(key); return value\nput(key, value):\n  if key present: update value; touch(key); return\n  if size == capacity: evict the oldest key in group[minCount]\n  add key with count 1 to group[1]; minCount = 1",
    ],
    reference: `class LFUCache { constructor(c) { this.c = c; this.kv = new Map(); this.g = new Map(); this.min = 0; } touch(k) { const e = this.kv.get(k); const s = this.g.get(e.f); s.delete(k); if (!s.size && this.min === e.f) this.min++; e.f++; if (!this.g.has(e.f)) this.g.set(e.f, new Set()); this.g.get(e.f).add(k); } get(k) { if (!this.kv.has(k)) return -1; this.touch(k); return this.kv.get(k).v; } put(k, v) { if (this.kv.has(k)) { this.kv.get(k).v = v; this.touch(k); return; } if (this.kv.size === this.c) { const s = this.g.get(this.min); const old = s.values().next().value; s.delete(old); this.kv.delete(old); } this.kv.set(k, { v, f: 1 }); if (!this.g.has(1)) this.g.set(1, new Set()); this.g.get(1).add(k); this.min = 1; } }`,
    brute: `class LFUCache { constructor(c) { this.c = c; this.e = new Map(); this.t = 0; } get(k) { const x = this.e.get(k); if (!x) return -1; x.f++; x.t = ++this.t; return x.v; } put(k, v) { const x = this.e.get(k); if (x) { x.v = v; x.f++; x.t = ++this.t; return; } if (this.e.size === this.c) { let worst = null; for (const [key, y] of this.e) if (!worst || y.f < worst[1].f || (y.f === worst[1].f && y.t < worst[1].t)) worst = [key, y]; this.e.delete(worst[0]); } this.e.set(k, { v, f: 1, t: ++this.t }); } }`,
    fuzz: cacheOpsGen("LFUCache"),
    examples: [[[["LFUCache", 2], ["put", 1, 1], ["put", 2, 2], ["get", 1], ["put", 3, 3], ["get", 2], ["get", 3], ["put", 4, 4], ["get", 1], ["get", 3], ["get", 4]]], [[["LFUCache", 1], ["put", 2, 1], ["get", 2]]]],
    edges: [
      ["min-size", [[["LFUCache", 1], ["put", 1, 1], ["get", 1], ["put", 2, 2], ["get", 1], ["get", 2]]], "Capacity 1: the new key always replaces the old one."],
      ["order", [[["LFUCache", 2], ["put", 1, 1], ["put", 2, 2], ["put", 3, 3], ["get", 1], ["get", 2]]], "Both keys used once: the least recent one goes."],
      ["reuse", [[["LFUCache", 2], ["put", 1, 1], ["put", 1, 2], ["put", 2, 2], ["put", 3, 3], ["get", 1], ["get", 2]]], "Updating a key counts as a use."],
    ],
  }),
];

export const LADDER_STACK_SEEDED: ProblemSpec[] = DEFS.map((d) => define(d).spec);
