import { define, type ProblemDef } from "../../dsa-extras/define";
import { arrayGen, gen } from "../../dsa-extras/gen";
import type { ProblemSpec } from "../types";

const NUMS: Array<[string, string]> = [["nums", "number[]"]];
const NUMS_K: Array<[string, string]> = [["nums", "number[]"], ["k", "number"]];
const TWO: Array<[string, string]> = [["nums1", "number[]"], ["nums2", "number[]"]];
const S: Array<[string, string]> = [["s", "string"]];

/** Judges for seeded LeetCode problems that the Hashing Ladder points at. LeetCode's own signatures. */
const DEFS: ProblemDef[] = [
  {
    slug: "intersection-of-two-arrays",
    title: "Intersection of Two Arrays",
    difficulty: "Easy",
    pattern: "Arrays & Hashing",
    fn: "intersection",
    params: TWO,
    returns: "number[]",
    compare: "unordered",
    hints: [
      "Each common value appears once in the answer, however often it repeats. Which structure removes repeats for free?",
      "Put nums1 in a Set. Walk nums2 and collect values found in that Set into a second Set, so each common value is added once.",
      "a = set of nums1\nresult = empty set\nfor each v in nums2:\n  if v in a: add v to result\nreturn result as a list",
    ],
    reference: `function intersection(nums1, nums2) { const a = new Set(nums1), r = new Set(); for (const v of nums2) if (a.has(v)) r.add(v); return [...r]; }`,
    brute: `function intersection(nums1, nums2) { const out = []; for (const v of nums1) if (nums2.includes(v) && !out.includes(v)) out.push(v); return out; }`,
    fuzz: gen(`return [__arr(rand, __r(rand, 1, 8), 0, 6), __arr(rand, __r(rand, 1, 8), 0, 6)];`),
    examples: [[[1, 2, 2, 1], [2, 2]], [[4, 9, 5], [9, 4, 9, 8, 4]]],
    edges: [
      ["no-answer", [[1, 2], [3, 4]], "Nothing in common: an empty list."],
      ["duplicates", [[3, 3, 3], [3]], "A repeated common value appears once."],
      ["single", [[7], [7]]],
    ],
  },
  {
    slug: "find-all-numbers-disappeared-in-an-array",
    title: "Find All Numbers Disappeared in an Array",
    difficulty: "Easy",
    pattern: "Arrays & Hashing",
    fn: "findDisappearedNumbers",
    params: NUMS,
    returns: "number[]",
    compare: "unordered",
    hints: [
      "Values are all in 1..n. A Set of what you saw makes the missing ones easy to list. Can the array itself act as that Set?",
      "For each value v, mark index |v| - 1 by making it negative. Afterwards, every index i still holding a positive number means i + 1 never appeared.",
      "for each v in nums:\n  i = |v| - 1\n  nums[i] = -|nums[i]|\nresult = []\nfor i from 0 to n - 1:\n  if nums[i] > 0: add i + 1 to result\nreturn result",
    ],
    reference: `function findDisappearedNumbers(nums) { const a = nums.slice(); for (const v of a) { const i = Math.abs(v) - 1; a[i] = -Math.abs(a[i]); } const r = []; for (let i = 0; i < a.length; i++) if (a[i] > 0) r.push(i + 1); return r; }`,
    brute: `function findDisappearedNumbers(nums) { const r = []; for (let x = 1; x <= nums.length; x++) if (!nums.includes(x)) r.push(x); return r; }`,
    fuzz: gen(`const n = __r(rand, 1, 10); return [__arr(rand, n, 1, n)];`),
    examples: [[[4, 3, 2, 7, 8, 2, 3, 1]], [[1, 1]]],
    edges: [
      ["sorted", [[1, 2, 3]], "Nothing is missing: an empty list."],
      ["all-equal", [[2, 2, 2, 2]]],
      ["single", [[1]]],
    ],
  },
  {
    slug: "contains-duplicate-ii",
    title: "Contains Duplicate II",
    difficulty: "Easy",
    pattern: "Sliding Window",
    fn: "containsNearbyDuplicate",
    params: NUMS_K,
    returns: "boolean",
    hints: [
      "For each value you only care about its most recent earlier position. What do you store per value?",
      "Keep a map value -> last index. At index i, if the value was seen at j with i - j <= k, return true; then update its last index to i.",
      "last = empty map\nfor i from 0 to n - 1:\n  if nums[i] in last and i - last[nums[i]] <= k: return true\n  last[nums[i]] = i\nreturn false",
    ],
    reference: `function containsNearbyDuplicate(nums, k) { const last = new Map(); for (let i = 0; i < nums.length; i++) { if (last.has(nums[i]) && i - last.get(nums[i]) <= k) return true; last.set(nums[i], i); } return false; }`,
    brute: `function containsNearbyDuplicate(nums, k) { for (let i = 0; i < nums.length; i++) for (let j = i + 1; j <= i + k && j < nums.length; j++) if (nums[i] === nums[j]) return true; return false; }`,
    fuzz: gen(`return [__arr(rand, __r(rand, 1, 12), 0, 5), __r(rand, 0, 4)];`),
    examples: [[[1, 2, 3, 1], 3], [[1, 2, 3, 1, 2, 3], 2]],
    edges: [
      ["zeros", [[1, 1], 0], "k = 0: two different indices can never be within distance 0."],
      ["boundary", [[1, 0, 1, 1], 1], "Only the last two copies are close enough."],
      ["single", [[5], 3]],
    ],
  },
  {
    slug: "unique-number-of-occurrences",
    title: "Unique Number of Occurrences",
    difficulty: "Easy",
    pattern: "Arrays & Hashing",
    fn: "uniqueOccurrences",
    params: [["arr", "number[]"]],
    returns: "boolean",
    hints: [
      "Two hash steps: first count each value, then check something about the counts themselves.",
      "Build value -> count, then put every count into a Set. The counts are unique exactly when the Set has as many entries as there are distinct values.",
      "count = counts of arr\nreturn size of set(values of count) == number of keys in count",
    ],
    reference: `function uniqueOccurrences(arr) { const c = new Map(); for (const v of arr) c.set(v, (c.get(v) || 0) + 1); return new Set(c.values()).size === c.size; }`,
    brute: `function uniqueOccurrences(arr) { const vals = [...new Set(arr)]; const counts = vals.map((v) => arr.filter((x) => x === v).length); for (let i = 0; i < counts.length; i++) for (let j = i + 1; j < counts.length; j++) if (counts[i] === counts[j]) return false; return true; }`,
    fuzz: arrayGen(1, 12, -2, 3),
    examples: [[[1, 2, 2, 1, 1, 3]], [[1, 2]]],
    edges: [
      ["single", [[4]]],
      ["negatives", [[-3, 0, 1, -3, 1, 1, 1, -3, 10, 0]]],
      ["all-equal", [[2, 2, 2]]],
    ],
  },
  {
    slug: "maximum-number-of-balloons",
    title: "Maximum Number of Balloons",
    difficulty: "Easy",
    pattern: "Arrays & Hashing",
    fn: "maxNumberOfBalloons",
    params: [["text", "string"]],
    returns: "number",
    hints: [
      "Each 'balloon' uses b, a, n once and l, o twice. Which letter runs out first?",
      "Count the letters of text. The answer is the minimum of count[b], count[a], count[n], count[l] / 2 and count[o] / 2, each rounded down.",
      "count = counts of text\nreturn min(count[b], count[a], count[n], floor(count[l] / 2), floor(count[o] / 2))",
    ],
    reference: `function maxNumberOfBalloons(text) { const c = {}; for (const ch of text) c[ch] = (c[ch] || 0) + 1; const g = (x) => c[x] || 0; return Math.min(g("b"), g("a"), g("n"), Math.floor(g("l") / 2), Math.floor(g("o") / 2)); }`,
    brute: `function maxNumberOfBalloons(text) { const pool = text.split(""); let n = 0; for (;;) { for (const ch of "balloon") { const i = pool.indexOf(ch); if (i < 0) return n; pool.splice(i, 1); } n++; } }`,
    fuzz: gen(`return [__str(rand, __r(rand, 1, 24), "balonxz")];`),
    examples: [["nlaebolko"], ["loonbalxballpoon"]],
    edges: [
      ["no-answer", ["leetcode"], "No 'b': zero balloons."],
      ["boundary", ["balon"], "One 'l' and one 'o' aren't enough for a balloon."],
      ["single-char", ["b"]],
    ],
  },
  {
    slug: "intersection-of-two-arrays-ii",
    title: "Intersection of Two Arrays II",
    difficulty: "Easy",
    pattern: "Arrays & Hashing",
    fn: "intersect",
    params: TWO,
    returns: "number[]",
    compare: "unordered",
    hints: [
      "Now a common value appears as many times as it shows up in both arrays. What should you count?",
      "Count nums1. For each value of nums2 with a positive count, add it to the result and decrement the count.",
      "count = counts of nums1\nresult = []\nfor each v in nums2:\n  if count[v] > 0:\n    add v to result\n    count[v] -= 1\nreturn result",
    ],
    reference: `function intersect(nums1, nums2) { const c = new Map(); for (const v of nums1) c.set(v, (c.get(v) || 0) + 1); const r = []; for (const v of nums2) if (c.get(v) > 0) { r.push(v); c.set(v, c.get(v) - 1); } return r; }`,
    brute: `function intersect(nums1, nums2) { const pool = nums1.slice(), r = []; for (const v of nums2) { const i = pool.indexOf(v); if (i >= 0) { r.push(v); pool.splice(i, 1); } } return r; }`,
    fuzz: gen(`return [__arr(rand, __r(rand, 1, 8), 0, 4), __arr(rand, __r(rand, 1, 8), 0, 4)];`),
    examples: [[[1, 2, 2, 1], [2, 2]], [[4, 9, 5], [9, 4, 9, 8, 4]]],
    edges: [
      ["no-answer", [[1, 2], [3]]],
      ["duplicates", [[3, 3, 3], [3, 3]], "Two common copies of 3."],
      ["single", [[1], [1]]],
    ],
  },
  {
    slug: "degree-of-an-array",
    title: "Degree of an Array",
    difficulty: "Easy",
    pattern: "Arrays & Hashing",
    fn: "findShortestSubArray",
    params: NUMS,
    returns: "number",
    hints: [
      "A subarray with the same degree must contain every copy of some most-frequent value. What's the shortest span containing all copies of a value?",
      "For each value record its count, first index and last index. Among values with the maximum count, return the smallest last - first + 1.",
      "for i from 0 to n - 1:\n  v = nums[i]\n  count[v] += 1\n  if v not in first: first[v] = i\n  last[v] = i\ndegree = max of count\nreturn min of last[v] - first[v] + 1 over v with count[v] == degree",
    ],
    reference: `function findShortestSubArray(nums) { const c = new Map(), f = new Map(), l = new Map(); nums.forEach((v, i) => { c.set(v, (c.get(v) || 0) + 1); if (!f.has(v)) f.set(v, i); l.set(v, i); }); const d = Math.max(...c.values()); let best = Infinity; for (const [v, n] of c) if (n === d) best = Math.min(best, l.get(v) - f.get(v) + 1); return best; }`,
    brute: `function findShortestSubArray(nums) { const deg = (a) => { const m = {}; let d = 0; for (const v of a) { m[v] = (m[v] || 0) + 1; d = Math.max(d, m[v]); } return d; }; const D = deg(nums); for (let len = 1; len <= nums.length; len++) for (let i = 0; i + len <= nums.length; i++) if (deg(nums.slice(i, i + len)) === D) return len; return nums.length; }`,
    fuzz: arrayGen(1, 12, 0, 4),
    examples: [[[1, 2, 2, 3, 1]], [[1, 2, 2, 3, 1, 4, 2]]],
    edges: [
      ["single", [[5]]],
      ["all-equal", [[3, 3, 3]], "The whole array is needed."],
      ["sorted", [[1, 2, 3, 4]], "Degree 1: any single element works."],
    ],
  },
  {
    slug: "longest-harmonious-subsequence",
    title: "Longest Harmonious Subsequence",
    difficulty: "Easy",
    pattern: "Arrays & Hashing",
    fn: "findLHS",
    params: NUMS,
    returns: "number",
    hints: [
      "A harmonious subsequence uses only two values, x and x + 1. Order doesn't matter for its length.",
      "Count every value. For each x whose x + 1 is also present, count[x] + count[x + 1] is a candidate; return the largest (0 if none).",
      "count = counts of nums\nbest = 0\nfor each x in count:\n  if x + 1 in count:\n    best = max(best, count[x] + count[x + 1])\nreturn best",
    ],
    reference: `function findLHS(nums) { const c = new Map(); for (const v of nums) c.set(v, (c.get(v) || 0) + 1); let b = 0; for (const [x, n] of c) if (c.has(x + 1)) b = Math.max(b, n + c.get(x + 1)); return b; }`,
    brute: `function findLHS(nums) { let b = 0; for (const x of nums) { const lo = nums.filter((v) => v === x).length, hi = nums.filter((v) => v === x + 1).length; if (hi) b = Math.max(b, lo + hi); } return b; }`,
    fuzz: arrayGen(1, 12, -2, 3),
    examples: [[[1, 3, 2, 2, 5, 2, 3, 7]], [[1, 2, 3, 4]]],
    edges: [
      ["all-equal", [[1, 1, 1, 1]], "Max - min must be exactly 1, so one value alone doesn't count."],
      ["negatives", [[-1, 0, -1]]],
      ["single", [[4]]],
    ],
  },
  {
    slug: "find-players-with-zero-or-one-losses",
    title: "Find Players With Zero or One Losses",
    difficulty: "Medium",
    pattern: "Arrays & Hashing",
    fn: "findWinners",
    params: [["matches", "number[][]"]],
    returns: "number[][]",
    hints: [
      "Only losses matter, but a player who never lost still has to be known. What do you track per player?",
      "Map every player to their loss count (winners get 0 if absent). Collect players with 0 and with exactly 1 loss, and sort both lists.",
      "losses = empty map\nfor each [w, l] in matches:\n  if w not in losses: losses[w] = 0\n  losses[l] += 1\nzero = sorted players with 0 losses\none = sorted players with 1 loss\nreturn [zero, one]",
    ],
    reference: `function findWinners(matches) { const L = new Map(); for (const [w, l] of matches) { if (!L.has(w)) L.set(w, 0); L.set(l, (L.get(l) || 0) + 1); } const z = [], o = []; for (const [p, n] of L) { if (n === 0) z.push(p); else if (n === 1) o.push(p); } z.sort((a, b) => a - b); o.sort((a, b) => a - b); return [z, o]; }`,
    brute: `function findWinners(matches) { const players = [...new Set(matches.flat())].sort((a, b) => a - b); const lost = (p) => matches.filter((m) => m[1] === p).length; return [players.filter((p) => lost(p) === 0), players.filter((p) => lost(p) === 1)]; }`,
    fuzz: gen(`const m = []; const n = __r(rand, 1, 8); for (let i = 0; i < n; i++) { const w = __r(rand, 1, 6); let l = __r(rand, 1, 6); if (l === w) l = w === 6 ? 1 : w + 1; m.push([w, l]); } return [m];`),
    examples: [[[[1, 3], [2, 3], [3, 6], [5, 6], [5, 7], [4, 5], [4, 8], [4, 9], [10, 4], [10, 9]]], [[[2, 3], [1, 3], [5, 4], [6, 4]]]],
    edges: [
      ["single", [[[1, 2]]]],
      ["duplicates", [[[1, 2], [1, 2], [1, 2]]], "The same loser three times has 3 losses: in neither list."],
      ["boundary", [[[3, 1], [1, 3]]], "Each lost once: nobody is unbeaten."],
    ],
  },
  {
    slug: "equal-row-and-column-pairs",
    title: "Equal Row and Column Pairs",
    difficulty: "Medium",
    pattern: "Arrays & Hashing",
    fn: "equalPairs",
    params: [["grid", "number[][]"]],
    returns: "number",
    hints: [
      "Comparing every row with every column is O(n^3). Can a row be turned into a key you can look up?",
      "Count each row as a string key (e.g. joined with commas). Then build each column's key and add the count of matching rows.",
      "rows = empty map\nfor each row r: rows[key(r)] += 1\npairs = 0\nfor each column c:\n  pairs += rows[key(c)] (0 if missing)\nreturn pairs",
    ],
    reference: `function equalPairs(grid) { const n = grid.length, m = new Map(); for (const r of grid) { const k = r.join(","); m.set(k, (m.get(k) || 0) + 1); } let p = 0; for (let c = 0; c < n; c++) { const k = grid.map((r) => r[c]).join(","); p += m.get(k) || 0; } return p; }`,
    brute: `function equalPairs(grid) { const n = grid.length; let p = 0; for (let r = 0; r < n; r++) for (let c = 0; c < n; c++) { let ok = true; for (let i = 0; i < n; i++) if (grid[r][i] !== grid[i][c]) { ok = false; break; } if (ok) p++; } return p; }`,
    fuzz: gen(`const n = __r(rand, 1, 4); return [Array.from({ length: n }, () => __arr(rand, n, 1, 2))];`),
    examples: [[[[3, 2, 1], [1, 7, 6], [2, 7, 7]]], [[[3, 1, 2, 2], [1, 4, 4, 5], [2, 4, 2, 2], [2, 4, 2, 2]]]],
    edges: [
      ["single", [[[5]]], "A 1x1 grid: its row equals its column."],
      ["all-equal", [[[1, 1], [1, 1]]], "Every row matches every column: 4 pairs."],
      ["no-answer", [[[1, 2], [3, 4]]]],
    ],
  },
  {
    slug: "valid-sudoku",
    title: "Valid Sudoku",
    difficulty: "Medium",
    pattern: "Arrays & Hashing",
    fn: "isValidSudoku",
    params: [["board", "character[][]"]],
    returns: "boolean",
    hints: [
      "Each filled digit belongs to one row, one column and one 3x3 box. How do you remember what each of those already holds?",
      "Keep a Set per row, per column and per box (box index = floor(r / 3) * 3 + floor(c / 3)). A digit already in any of its three sets means invalid.",
      "for r from 0 to 8:\n  for c from 0 to 8:\n    d = board[r][c]\n    if d == '.': continue\n    b = (r div 3) * 3 + (c div 3)\n    if d in rows[r] or d in cols[c] or d in boxes[b]: return false\n    add d to rows[r], cols[c], boxes[b]\nreturn true",
    ],
    reference: `function isValidSudoku(board) { const R = [], C = [], B = []; for (let i = 0; i < 9; i++) { R.push(new Set()); C.push(new Set()); B.push(new Set()); } for (let r = 0; r < 9; r++) for (let c = 0; c < 9; c++) { const d = board[r][c]; if (d === ".") continue; const b = Math.floor(r / 3) * 3 + Math.floor(c / 3); if (R[r].has(d) || C[c].has(d) || B[b].has(d)) return false; R[r].add(d); C[c].add(d); B[b].add(d); } return true; }`,
    brute: `function isValidSudoku(board) { const ok = (cells) => { const d = cells.filter((x) => x !== "."); return new Set(d).size === d.length; }; for (let i = 0; i < 9; i++) { if (!ok(board[i])) return false; if (!ok(board.map((r) => r[i]))) return false; const br = Math.floor(i / 3) * 3, bc = (i % 3) * 3, cells = []; for (let r = 0; r < 3; r++) for (let c = 0; c < 3; c++) cells.push(board[br + r][bc + c]); if (!ok(cells)) return false; } return true; }`,
    fuzz: gen(`const perm = __shuffle(rand, [1, 2, 3, 4, 5, 6, 7, 8, 9]); const b = []; for (let r = 0; r < 9; r++) { const row = []; for (let c = 0; c < 9; c++) row.push(rand() < 0.65 ? "." : String(perm[(r * 3 + Math.floor(r / 3) + c) % 9])); b.push(row); } if (rand() < 0.5) b[__r(rand, 0, 8)][__r(rand, 0, 8)] = String(__r(rand, 1, 9)); return [b];`),
    examples: [
      [[["5", "3", ".", ".", "7", ".", ".", ".", "."], ["6", ".", ".", "1", "9", "5", ".", ".", "."], [".", "9", "8", ".", ".", ".", ".", "6", "."], ["8", ".", ".", ".", "6", ".", ".", ".", "3"], ["4", ".", ".", "8", ".", "3", ".", ".", "1"], ["7", ".", ".", ".", "2", ".", ".", ".", "6"], [".", "6", ".", ".", ".", ".", "2", "8", "."], [".", ".", ".", "4", "1", "9", ".", ".", "5"], [".", ".", ".", ".", "8", ".", ".", "7", "9"]]],
      [[["8", "3", ".", ".", "7", ".", ".", ".", "."], ["6", ".", ".", "1", "9", "5", ".", ".", "."], [".", "9", "8", ".", ".", ".", ".", "6", "."], ["8", ".", ".", ".", "6", ".", ".", ".", "3"], ["4", ".", ".", "8", ".", "3", ".", ".", "1"], ["7", ".", ".", ".", "2", ".", ".", ".", "6"], [".", "6", ".", ".", ".", ".", "2", "8", "."], [".", ".", ".", "4", "1", "9", ".", ".", "5"], [".", ".", ".", ".", "8", ".", ".", "7", "9"]]],
    ],
    edges: [
      ["empty", [Array.from({ length: 9 }, () => Array(9).fill("."))], "An empty board is valid."],
      ["duplicates", [[["1", ".", ".", ".", ".", ".", ".", ".", "."], [".", "1", ".", ".", ".", ".", ".", ".", "."], [".", ".", ".", ".", ".", ".", ".", ".", "."], [".", ".", ".", ".", ".", ".", ".", ".", "."], [".", ".", ".", ".", ".", ".", ".", ".", "."], [".", ".", ".", ".", ".", ".", ".", ".", "."], [".", ".", ".", ".", ".", ".", ".", ".", "."], [".", ".", ".", ".", ".", ".", ".", ".", "."], [".", ".", ".", ".", ".", ".", ".", ".", "."]]], "Different row and column, same 3x3 box."],
      ["boundary", [[[".", ".", ".", ".", ".", ".", ".", ".", "9"], [".", ".", ".", ".", ".", ".", ".", ".", "."], [".", ".", ".", ".", ".", ".", ".", ".", "."], [".", ".", ".", ".", ".", ".", ".", ".", "."], [".", ".", ".", ".", ".", ".", ".", ".", "."], [".", ".", ".", ".", ".", ".", ".", ".", "."], [".", ".", ".", ".", ".", ".", ".", ".", "."], [".", ".", ".", ".", ".", ".", ".", ".", "."], [".", ".", ".", ".", ".", ".", ".", ".", "9"]]], "Same column, far apart."],
    ],
  },
  {
    slug: "repeated-dna-sequences",
    title: "Repeated DNA Sequences",
    difficulty: "Medium",
    pattern: "Arrays & Hashing",
    fn: "findRepeatedDnaSequences",
    params: S,
    returns: "string[]",
    compare: "unordered",
    hints: [
      "Every 10-letter window is a candidate. How do you know you've seen a window before?",
      "Slide over all windows of length 10, adding each to a 'seen' Set. When a window is already in it, add it to a 'repeated' Set (so it's reported once).",
      "seen = empty set, repeated = empty set\nfor i from 0 to n - 10:\n  w = s[i .. i + 9]\n  if w in seen: add w to repeated\n  add w to seen\nreturn repeated as a list",
    ],
    reference: `function findRepeatedDnaSequences(s) { const seen = new Set(), rep = new Set(); for (let i = 0; i + 10 <= s.length; i++) { const w = s.slice(i, i + 10); if (seen.has(w)) rep.add(w); seen.add(w); } return [...rep]; }`,
    brute: `function findRepeatedDnaSequences(s) { const out = []; for (let i = 0; i + 10 <= s.length; i++) { const w = s.slice(i, i + 10); if (s.indexOf(w) !== i) continue; if (s.indexOf(w, i + 1) >= 0) out.push(w); } return out; }`,
    fuzz: gen(`return [__str(rand, __r(rand, 1, 24), rand() < 0.5 ? "AC" : "ACGT")];`),
    examples: [["AAAAACCCCCAAAAACCCCCCAAAAAGGGTTT"], ["AAAAAAAAAAAAA"]],
    edges: [
      ["min-size", ["ACGT"], "Shorter than 10: no windows at all."],
      ["boundary", ["AAAAAAAAAAA"], "Two overlapping windows of the same sequence."],
      ["no-answer", ["ACGTACGTAC"], "Exactly one window: nothing repeats."],
    ],
  },
  {
    slug: "bulls-and-cows",
    title: "Bulls and Cows",
    difficulty: "Medium",
    pattern: "Arrays & Hashing",
    fn: "getHint",
    params: [["secret", "string"], ["guess", "string"]],
    returns: "string",
    hints: [
      "Bulls are easy: same digit, same position. Cows need counts of the leftover digits on both sides.",
      "Count bulls in one pass. For non-bull positions, count digits of secret and of guess separately; cows = sum over digits of the smaller of the two counts.",
      "bulls = 0\nfor i from 0 to n - 1:\n  if secret[i] == guess[i]: bulls += 1\n  else:\n    s[secret[i]] += 1\n    g[guess[i]] += 1\ncows = sum over digits d of min(s[d], g[d])\nreturn bulls + \"A\" + cows + \"B\"",
    ],
    reference: `function getHint(secret, guess) { let b = 0; const s = new Array(10).fill(0), g = new Array(10).fill(0); for (let i = 0; i < secret.length; i++) { if (secret[i] === guess[i]) b++; else { s[+secret[i]]++; g[+guess[i]]++; } } let c = 0; for (let d = 0; d < 10; d++) c += Math.min(s[d], g[d]); return b + "A" + c + "B"; }`,
    brute: `function getHint(secret, guess) { let b = 0; const rs = [], rg = []; for (let i = 0; i < secret.length; i++) { if (secret[i] === guess[i]) b++; else { rs.push(secret[i]); rg.push(guess[i]); } } let c = 0; for (const d of rg) { const i = rs.indexOf(d); if (i >= 0) { c++; rs.splice(i, 1); } } return b + "A" + c + "B"; }`,
    fuzz: gen(`const n = __r(rand, 1, 8); return [__str(rand, n, "0123"), __str(rand, n, "0123")];`),
    examples: [["1807", "7810"], ["1123", "0111"]],
    edges: [
      ["all-equal", ["1234", "1234"], "All bulls, no cows."],
      ["duplicates", ["1122", "2211"], "No bulls, all cows."],
      ["single-char", ["1", "0"]],
    ],
  },
  {
    slug: "number-of-pairs-of-interchangeable-rectangles",
    title: "Number of Pairs of Interchangeable Rectangles",
    difficulty: "Medium",
    pattern: "Arrays & Hashing",
    fn: "interchangeableRectangles",
    params: [["rectangles", "number[][]"]],
    returns: "number",
    hints: [
      "Two rectangles are interchangeable when width/height match. How do you group ratios safely, without floating-point surprises?",
      "Reduce each [w, h] by gcd(w, h) and use the reduced pair as a key. A group of size m contributes m * (m - 1) / 2 pairs; or add the group's current size before inserting each rectangle.",
      "count = empty map, pairs = 0\nfor each [w, h] in rectangles:\n  g = gcd(w, h)\n  key = (w / g, h / g)\n  pairs += count[key] (0 if missing)\n  count[key] += 1\nreturn pairs",
    ],
    reference: `function interchangeableRectangles(rectangles) { const gcd = (a, b) => (b ? gcd(b, a % b) : a); const m = new Map(); let p = 0; for (const [w, h] of rectangles) { const g = gcd(w, h), k = w / g + "/" + h / g; p += m.get(k) || 0; m.set(k, (m.get(k) || 0) + 1); } return p; }`,
    brute: `function interchangeableRectangles(rectangles) { let p = 0; for (let i = 0; i < rectangles.length; i++) for (let j = i + 1; j < rectangles.length; j++) if (rectangles[i][0] * rectangles[j][1] === rectangles[j][0] * rectangles[i][1]) p++; return p; }`,
    fuzz: gen(`return [Array.from({ length: __r(rand, 1, 10) }, () => [__r(rand, 1, 6), __r(rand, 1, 6)])];`),
    examples: [[[[4, 8], [3, 6], [10, 20], [15, 30]]], [[[4, 5], [7, 8]]]],
    edges: [
      ["single", [[[2, 3]]]],
      ["all-equal", [[[1, 1], [2, 2], [3, 3]]], "All squares: 3 pairs."],
      ["boundary", [[[2, 4], [4, 2]]], "Width/height order matters: 1/2 isn't 2/1."],
    ],
  },
  {
    slug: "brick-wall",
    title: "Brick Wall",
    difficulty: "Medium",
    pattern: "Arrays & Hashing",
    fn: "leastBricks",
    params: [["wall", "number[][]"]],
    returns: "number",
    hints: [
      "A line crosses the fewest bricks where the most rows have an edge. Where are a row's edges?",
      "For every row, walk its prefix sums (excluding the full width) and count how often each edge position appears. Answer = rows - the most common edge count.",
      "edges = empty map\nfor each row in wall:\n  x = 0\n  for each brick except the last:\n    x += brick\n    edges[x] += 1\nreturn number of rows - max(edges values, or 0)",
    ],
    reference: `function leastBricks(wall) { const e = new Map(); let best = 0; for (const row of wall) { let x = 0; for (let i = 0; i < row.length - 1; i++) { x += row[i]; const n = (e.get(x) || 0) + 1; e.set(x, n); if (n > best) best = n; } } return wall.length - best; }`,
    brute: `function leastBricks(wall) { const W = wall[0].reduce((a, b) => a + b, 0); let best = wall.length; for (let x = 1; x < W; x++) { let crossed = 0; for (const row of wall) { let s = 0, edge = false; for (const b of row) { s += b; if (s === x) { edge = true; break; } if (s > x) break; } if (!edge) crossed++; } best = Math.min(best, crossed); } return best; }`,
    fuzz: gen(`const W = __r(rand, 1, 7); const rows = __r(rand, 1, 5); const wall = []; for (let r = 0; r < rows; r++) { const row = []; let left = W; while (left > 0) { const b = __r(rand, 1, left); row.push(b); left -= b; } wall.push(row); } return [wall];`),
    examples: [[[[1, 2, 2, 1], [3, 1, 2], [1, 3, 2], [2, 4], [3, 1, 2], [1, 3, 1, 1]]], [[[1], [1], [1]]]],
    edges: [
      ["single", [[[2, 3]]], "One row with an inner edge: cross 0 bricks."],
      ["all-equal", [[[1, 1], [1, 1]]]],
      ["no-answer", [[[3], [1, 2], [2, 1]]], "No edge is shared by every row."],
    ],
  },
  {
    slug: "check-if-a-string-contains-all-binary-codes-of-size-k",
    title: "Check If a String Contains All Binary Codes of Size K",
    difficulty: "Medium",
    pattern: "Arrays & Hashing",
    fn: "hasAllCodes",
    params: [["s", "string"], ["k", "number"]],
    returns: "boolean",
    hints: [
      "There are exactly 2^k binary codes of length k. How many distinct windows of length k does s have?",
      "Collect every length-k window into a Set. s contains all codes exactly when the Set reaches size 2^k.",
      "seen = empty set\nfor i from 0 to n - k:\n  add s[i .. i + k - 1] to seen\nreturn size of seen == 2^k",
    ],
    reference: `function hasAllCodes(s, k) { const seen = new Set(); for (let i = 0; i + k <= s.length; i++) seen.add(s.slice(i, i + k)); return seen.size === 1 << k; }`,
    brute: `function hasAllCodes(s, k) { for (let x = 0; x < 1 << k; x++) if (!s.includes(x.toString(2).padStart(k, "0"))) return false; return true; }`,
    fuzz: gen(`return [__str(rand, __r(rand, 1, 18), "01"), __r(rand, 1, 3)];`),
    examples: [["00110110", 2], ["0110", 1]],
    edges: [
      ["no-answer", ["0110", 2], "\"00\" never appears."],
      ["min-size", ["0", 1], "Only one of the two codes."],
      ["boundary", ["00010111", 3], "Exactly all 8 codes, each once (a de Bruijn sequence)."],
    ],
  },
  {
    slug: "optimal-partition-of-string",
    title: "Optimal Partition of String",
    difficulty: "Medium",
    pattern: "Arrays & Hashing",
    fn: "partitionString",
    params: S,
    returns: "number",
    hints: [
      "Greedy: make each piece as long as possible. When must a piece end?",
      "Keep the letters of the current piece in a Set. When the next letter is already in it, start a new piece (clear the Set). Count the pieces.",
      "pieces = 1, seen = empty set\nfor each ch in s:\n  if ch in seen:\n    pieces += 1\n    seen = empty set\n  add ch to seen\nreturn pieces",
    ],
    reference: `function partitionString(s) { let n = 1, seen = new Set(); for (const ch of s) { if (seen.has(ch)) { n++; seen = new Set(); } seen.add(ch); } return n; }`,
    brute: `function partitionString(s) { let n = 0, i = 0; while (i < s.length) { let j = i; while (j < s.length && !s.slice(i, j).includes(s[j])) j++; n++; i = j; } return n; }`,
    fuzz: gen(`return [__str(rand, __r(rand, 1, 16), "abcd")];`),
    examples: [["abacaba"], ["ssssss"]],
    edges: [
      ["single-char", ["z"]],
      ["sorted", ["abcdef"], "All letters different: one piece."],
      ["two", ["aa"]],
    ],
  },
  {
    slug: "contiguous-array",
    title: "Contiguous Array",
    difficulty: "Medium",
    pattern: "Prefix Sum",
    fn: "findMaxLength",
    params: NUMS,
    returns: "number",
    hints: [
      "Treat 0 as -1. Then 'equal numbers of 0 and 1' means the subarray sums to 0.",
      "Track a running sum and the first index each sum value appeared (sum 0 at index -1). When a sum repeats, the subarray between the two indices sums to 0.",
      "first = {0: -1}, sum = 0, best = 0\nfor i from 0 to n - 1:\n  sum += 1 if nums[i] == 1 else -1\n  if sum in first: best = max(best, i - first[sum])\n  else: first[sum] = i\nreturn best",
    ],
    reference: `function findMaxLength(nums) { const f = new Map([[0, -1]]); let s = 0, b = 0; for (let i = 0; i < nums.length; i++) { s += nums[i] ? 1 : -1; if (f.has(s)) b = Math.max(b, i - f.get(s)); else f.set(s, i); } return b; }`,
    brute: `function findMaxLength(nums) { let b = 0; for (let i = 0; i < nums.length; i++) { let z = 0, o = 0; for (let j = i; j < nums.length; j++) { if (nums[j]) o++; else z++; if (z === o) b = Math.max(b, j - i + 1); } } return b; }`,
    fuzz: arrayGen(1, 14, 0, 1),
    examples: [[[0, 1]], [[0, 1, 1, 1, 1, 1, 0, 0, 0]]],
    edges: [
      ["all-equal", [[1, 1, 1]], "No zeros at all: 0."],
      ["single", [[0]]],
      ["boundary", [[0, 0, 1, 0, 0, 0, 1, 1]], "The best subarray runs to the last element."],
    ],
  },
  {
    slug: "continuous-subarray-sum",
    title: "Continuous Subarray Sum",
    difficulty: "Medium",
    pattern: "Prefix Sum",
    fn: "checkSubarraySum",
    params: NUMS_K,
    returns: "boolean",
    hints: [
      "A subarray sum is a multiple of k when two prefix sums leave the same remainder mod k.",
      "Store the first index of each prefix remainder (remainder 0 at index -1). If a remainder repeats at least two indices later, the subarray has length >= 2 and a sum divisible by k.",
      "first = {0: -1}, sum = 0\nfor i from 0 to n - 1:\n  sum = (sum + nums[i]) mod k\n  if sum in first:\n    if i - first[sum] >= 2: return true\n  else: first[sum] = i\nreturn false",
    ],
    reference: `function checkSubarraySum(nums, k) { const f = new Map([[0, -1]]); let s = 0; for (let i = 0; i < nums.length; i++) { s = (s + nums[i]) % k; if (f.has(s)) { if (i - f.get(s) >= 2) return true; } else f.set(s, i); } return false; }`,
    brute: `function checkSubarraySum(nums, k) { for (let i = 0; i < nums.length; i++) { let s = nums[i]; for (let j = i + 1; j < nums.length; j++) { s += nums[j]; if (s % k === 0) return true; } } return false; }`,
    fuzz: gen(`return [__arr(rand, __r(rand, 1, 10), 0, 9), __r(rand, 1, 12)];`),
    examples: [[[23, 2, 4, 6, 7], 6], [[23, 2, 6, 4, 7], 13]],
    edges: [
      ["zeros", [[0, 0], 1], "Two zeros sum to 0, a multiple of every k."],
      ["single", [[6], 6], "A single element isn't long enough."],
      ["boundary", [[5, 0, 0, 0], 3], "Only the zeros form a valid subarray."],
    ],
  },
  {
    slug: "subarray-sums-divisible-by-k",
    title: "Subarray Sums Divisible by K",
    difficulty: "Medium",
    pattern: "Prefix Sum",
    fn: "subarraysDivByK",
    params: NUMS_K,
    returns: "number",
    hints: [
      "Two prefix sums with the same remainder mod k bound a subarray whose sum is divisible by k. Careful: JavaScript's % can be negative.",
      "Count remainders of prefix sums (normalised to 0..k-1, starting with remainder 0 once). Each new prefix adds the number of earlier prefixes with the same remainder.",
      "count = {0: 1}, sum = 0, total = 0\nfor each v in nums:\n  sum = ((sum + v) mod k + k) mod k\n  total += count[sum] (0 if missing)\n  count[sum] += 1\nreturn total",
    ],
    reference: `function subarraysDivByK(nums, k) { const c = new Map([[0, 1]]); let s = 0, t = 0; for (const v of nums) { s = (((s + v) % k) + k) % k; t += c.get(s) || 0; c.set(s, (c.get(s) || 0) + 1); } return t; }`,
    brute: `function subarraysDivByK(nums, k) { let t = 0; for (let i = 0; i < nums.length; i++) { let s = 0; for (let j = i; j < nums.length; j++) { s += nums[j]; if (s % k === 0) t++; } } return t; }`,
    fuzz: gen(`return [__arr(rand, __r(rand, 1, 12), -6, 6), __r(rand, 2, 6)];`),
    examples: [[[4, 5, 0, -2, -3, 1], 5], [[5], 9]],
    edges: [
      ["negatives", [[-1, 2, 9], 2], "Negative prefix sums need their remainder normalised."],
      ["zeros", [[0, 0, 0], 3], "Every subarray of zeros counts: 6."],
      ["single", [[10], 5]],
    ],
  },
  {
    slug: "binary-subarrays-with-sum",
    title: "Binary Subarrays With Sum",
    difficulty: "Medium",
    pattern: "Prefix Sum",
    fn: "numSubarraysWithSum",
    params: [["nums", "number[]"], ["goal", "number"]],
    returns: "number",
    hints: [
      "Subarray sum = goal means prefix[j] - prefix[i] = goal. How many earlier prefixes equal prefix[j] - goal?",
      "Keep a count of prefix sums seen (prefix 0 once at the start). For each new prefix add count[prefix - goal], then record the prefix.",
      "count = {0: 1}, sum = 0, total = 0\nfor each v in nums:\n  sum += v\n  total += count[sum - goal] (0 if missing)\n  count[sum] += 1\nreturn total",
    ],
    reference: `function numSubarraysWithSum(nums, goal) { const c = new Map([[0, 1]]); let s = 0, t = 0; for (const v of nums) { s += v; t += c.get(s - goal) || 0; c.set(s, (c.get(s) || 0) + 1); } return t; }`,
    brute: `function numSubarraysWithSum(nums, goal) { let t = 0; for (let i = 0; i < nums.length; i++) { let s = 0; for (let j = i; j < nums.length; j++) { s += nums[j]; if (s === goal) t++; } } return t; }`,
    fuzz: gen(`return [__arr(rand, __r(rand, 1, 12), 0, 1), __r(rand, 0, 3)];`),
    examples: [[[1, 0, 1, 0, 1], 2], [[0, 0, 0, 0, 0], 0]],
    edges: [
      ["no-answer", [[1, 1], 3], "The whole array sums to less than goal."],
      ["single", [[1], 1]],
      ["zeros", [[0, 1, 0], 0], "goal = 0 counts the runs of zeros."],
    ],
  },
  {
    slug: "count-number-of-nice-subarrays",
    title: "Count Number of Nice Subarrays",
    difficulty: "Medium",
    pattern: "Prefix Sum",
    fn: "numberOfSubarrays",
    params: NUMS_K,
    returns: "number",
    hints: [
      "Replace each number by 1 if odd and 0 if even. Now you're counting subarrays with sum exactly k.",
      "Use the prefix-count map: running count of odds, add count[odds - k] at each step, then record the running count.",
      "count = {0: 1}, odds = 0, total = 0\nfor each v in nums:\n  if v is odd: odds += 1\n  total += count[odds - k] (0 if missing)\n  count[odds] += 1\nreturn total",
    ],
    reference: `function numberOfSubarrays(nums, k) { const c = new Map([[0, 1]]); let o = 0, t = 0; for (const v of nums) { if (v % 2) o++; t += c.get(o - k) || 0; c.set(o, (c.get(o) || 0) + 1); } return t; }`,
    brute: `function numberOfSubarrays(nums, k) { let t = 0; for (let i = 0; i < nums.length; i++) { let o = 0; for (let j = i; j < nums.length; j++) { if (nums[j] % 2) o++; if (o === k) t++; } } return t; }`,
    fuzz: gen(`return [__arr(rand, __r(rand, 1, 12), 1, 6), __r(rand, 1, 3)];`),
    examples: [[[1, 1, 2, 1, 1], 3], [[2, 4, 6], 1]],
    edges: [
      ["boundary", [[2, 2, 2, 1, 2, 2, 1, 2, 2, 2], 2], "Evens on both sides multiply the count."],
      ["single", [[1], 1]],
      ["all-equal", [[3, 3, 3], 1]],
    ],
  },
  {
    slug: "4sum",
    title: "4Sum",
    difficulty: "Medium",
    pattern: "Two Pointers",
    fn: "fourSum",
    params: [["nums", "number[]"], ["target", "number"]],
    returns: "number[][]",
    compare: "unordered",
    hints: [
      "It's 3Sum with one more fixed index. Sorting is what makes skipping duplicates easy.",
      "Sort. Fix i, then j > i, skipping repeated values for both. Use two pointers on the rest to find pairs summing to target - nums[i] - nums[j], skipping duplicates as you move.",
      "sort nums\nfor i from 0 to n - 1 (skip repeats):\n  for j from i + 1 to n - 1 (skip repeats):\n    l = j + 1, r = n - 1\n    while l < r:\n      s = nums[i] + nums[j] + nums[l] + nums[r]\n      if s == target: record, move l and r past repeats\n      else if s < target: l += 1\n      else: r -= 1\nreturn records",
    ],
    reference: `function fourSum(nums, target) { const a = nums.slice().sort((x, y) => x - y), n = a.length, out = []; for (let i = 0; i < n; i++) { if (i && a[i] === a[i - 1]) continue; for (let j = i + 1; j < n; j++) { if (j > i + 1 && a[j] === a[j - 1]) continue; let l = j + 1, r = n - 1; while (l < r) { const s = a[i] + a[j] + a[l] + a[r]; if (s === target) { out.push([a[i], a[j], a[l], a[r]]); l++; r--; while (l < r && a[l] === a[l - 1]) l++; while (l < r && a[r] === a[r + 1]) r--; } else if (s < target) l++; else r--; } } } return out; }`,
    brute: `function fourSum(nums, target) { const seen = new Set(), out = [], n = nums.length; for (let a = 0; a < n; a++) for (let b = a + 1; b < n; b++) for (let c = b + 1; c < n; c++) for (let d = c + 1; d < n; d++) if (nums[a] + nums[b] + nums[c] + nums[d] === target) { const q = [nums[a], nums[b], nums[c], nums[d]].sort((x, y) => x - y); const k = q.join(","); if (!seen.has(k)) { seen.add(k); out.push(q); } } return out; }`,
    fuzz: gen(`return [__arr(rand, __r(rand, 1, 9), -3, 3), __r(rand, -3, 3)];`),
    examples: [[[1, 0, -1, 0, -2, 2], 0], [[2, 2, 2, 2, 2], 8]],
    edges: [
      ["no-answer", [[1, 2, 3], 6], "Fewer than four numbers: no quadruplets."],
      ["duplicates", [[0, 0, 0, 0, 0, 0], 0], "Many equal values still give one quadruplet."],
      ["negatives", [[-3, -2, -1, 0, 0, 1, 2, 3], 0]],
    ],
  },
  {
    slug: "subarrays-with-k-different-integers",
    title: "Subarrays with K Different Integers",
    difficulty: "Hard",
    pattern: "Sliding Window",
    fn: "subarraysWithKDistinct",
    params: NUMS_K,
    returns: "number",
    hints: [
      "Counting 'exactly k distinct' directly is awkward. Counting 'at most k distinct' with a sliding window is easy. How do the two relate?",
      "exactly(k) = atMost(k) - atMost(k - 1). atMost(k): grow the window, shrink from the left while it has more than k distinct values, and add the window length at each right end.",
      "atMost(k):\n  count = empty map, l = 0, total = 0\n  for r from 0 to n - 1:\n    count[nums[r]] += 1\n    while number of keys in count > k:\n      count[nums[l]] -= 1, remove it at 0, l += 1\n    total += r - l + 1\n  return total\nreturn atMost(k) - atMost(k - 1)",
    ],
    reference: `function subarraysWithKDistinct(nums, k) { const at = (K) => { const c = new Map(); let l = 0, t = 0; for (let r = 0; r < nums.length; r++) { c.set(nums[r], (c.get(nums[r]) || 0) + 1); while (c.size > K) { const v = nums[l++]; c.set(v, c.get(v) - 1); if (!c.get(v)) c.delete(v); } t += r - l + 1; } return t; }; return at(k) - at(k - 1); }`,
    brute: `function subarraysWithKDistinct(nums, k) { let t = 0; for (let i = 0; i < nums.length; i++) { const s = new Set(); for (let j = i; j < nums.length; j++) { s.add(nums[j]); if (s.size === k) t++; if (s.size > k) break; } } return t; }`,
    fuzz: gen(`const n = __r(rand, 1, 12); return [__arr(rand, n, 1, 4), __r(rand, 1, 3)];`),
    examples: [[[1, 2, 1, 2, 3], 2], [[1, 2, 1, 3, 4], 3]],
    edges: [
      ["all-equal", [[2, 2, 2], 1], "Every subarray has exactly one distinct value: 6."],
      ["no-answer", [[1, 2], 3], "Never 3 distinct values: 0."],
      ["single", [[1], 1]],
    ],
  },
  {
    slug: "naming-a-company",
    title: "Naming a Company",
    difficulty: "Hard",
    pattern: "Arrays & Hashing",
    fn: "distinctNames",
    params: [["ideas", "string[]"]],
    returns: "number",
    hints: [
      "Group the ideas by first letter, keeping only the suffix. Swapping letters a and b works for a pair of suffixes when neither suffix exists under the other letter.",
      "For each pair of letters (a, b), count the suffixes they share. Valid pairs = (|A| - common) * (|B| - common), and each unordered letter pair gives two names.",
      "groups[c] = set of suffixes of ideas starting with c\ntotal = 0\nfor each letter pair a < b:\n  common = size of groups[a] intersect groups[b]\n  total += 2 * (size(groups[a]) - common) * (size(groups[b]) - common)\nreturn total",
    ],
    reference: `function distinctNames(ideas) { const g = Array.from({ length: 26 }, () => new Set()); for (const w of ideas) g[w.charCodeAt(0) - 97].add(w.slice(1)); let t = 0; for (let a = 0; a < 26; a++) for (let b = a + 1; b < 26; b++) { let c = 0; for (const s of g[a]) if (g[b].has(s)) c++; t += 2 * (g[a].size - c) * (g[b].size - c); } return t; }`,
    brute: `function distinctNames(ideas) { const set = new Set(ideas); let t = 0; for (const x of ideas) for (const y of ideas) { if (x === y) continue; const nx = y[0] + x.slice(1), ny = x[0] + y.slice(1); if (!set.has(nx) && !set.has(ny)) t++; } return t; }`,
    fuzz: gen(`const s = new Set(); const n = __r(rand, 2, 8); while (s.size < n) s.add(__pick(rand, ["c", "t", "d", "f"]) + __str(rand, __r(rand, 1, 2), "ao")); return [[...s]];`),
    examples: [[["coffee", "donuts", "time", "toffee"]], [["lack", "back"]]],
    edges: [
      ["boundary", [["aaa", "baa", "caa", "bbb", "cbb", "dbb"]], "Shared suffixes cancel most swaps; only a and d can trade."],
      ["two", [["ab", "cd"]], "Swapping gives 'cb' and 'ad': both new, so 2 names."],
      ["duplicates", [["ax", "bx"]], "Same suffix under both letters: no valid swap."],
    ],
  },
  {
    slug: "max-points-on-a-line",
    title: "Max Points on a Line",
    difficulty: "Hard",
    pattern: "Math & Geometry",
    fn: "maxPoints",
    params: [["points", "number[][]"]],
    returns: "number",
    hints: [
      "Fix one point. Every other point defines a direction from it; points on the same line through the anchor share a direction.",
      "For each anchor, count other points by reduced slope: (dy, dx) divided by their gcd with a fixed sign. The best line through the anchor has max count + 1 points.",
      "best = 1\nfor each anchor p:\n  slopes = empty map\n  for each other point q:\n    dx = q.x - p.x, dy = q.y - p.y\n    g = gcd(|dx|, |dy|); normalise (dx / g, dy / g) to one sign\n    slopes[(dx, dy)] += 1\n  best = max(best, max of slopes + 1)\nreturn best",
    ],
    reference: `function maxPoints(points) { const gcd = (a, b) => (b ? gcd(b, a % b) : a); let best = 1; for (let i = 0; i < points.length; i++) { const m = new Map(); for (let j = 0; j < points.length; j++) { if (i === j) continue; let dx = points[j][0] - points[i][0], dy = points[j][1] - points[i][1]; const g = gcd(Math.abs(dx), Math.abs(dy)); dx /= g; dy /= g; if (dx < 0 || (dx === 0 && dy < 0)) { dx = -dx; dy = -dy; } const k = dx + "/" + dy; const n = (m.get(k) || 0) + 1; m.set(k, n); if (n + 1 > best) best = n + 1; } } return best; }`,
    brute: `function maxPoints(points) { const n = points.length; if (n < 3) return n; let best = 2; for (let i = 0; i < n; i++) for (let j = i + 1; j < n; j++) { let c = 0; for (let k = 0; k < n; k++) { const [x1, y1] = points[i], [x2, y2] = points[j], [x3, y3] = points[k]; if ((y2 - y1) * (x3 - x1) === (y3 - y1) * (x2 - x1)) c++; } best = Math.max(best, c); } return best; }`,
    fuzz: gen(`const s = new Set(); const n = __r(rand, 1, 8); while (s.size < n) s.add(__r(rand, -3, 3) + "," + __r(rand, -3, 3)); return [[...s].map((p) => p.split(",").map(Number))];`),
    examples: [[[[1, 1], [2, 2], [3, 3]]], [[[1, 1], [3, 2], [5, 3], [4, 1], [2, 3], [1, 4]]]],
    edges: [
      ["single", [[[0, 0]]]],
      ["boundary", [[[0, 0], [0, 5], [0, -3], [1, 1]]], "A vertical line: dx = 0 must be handled."],
      ["negatives", [[[-1, -1], [1, 1], [2, 3], [-2, -2]]]],
    ],
  },
];

export const LADDER_HASHING_SEEDED: ProblemSpec[] = DEFS.map((d) => define(d).spec);
