import { define, type ProblemDef } from "../../dsa-extras/define";
import { gen, treeGen } from "../../dsa-extras/gen";
import type { ProblemSpec } from "../types";
import { design } from "./ladder-stack-seeded";

const T = "TreeNode | null";
const BST = (min: number, max: number) => treeGen(`return [__bstLevel(rand, __r(rand, ${min}, ${max}), 1, 30)];`);
const BST_PQ = treeGen(`const t = __bstLevel(rand, __r(rand, 2, 12), 1, 30); const v = __shuffle(rand, t.filter((x) => x !== null)); return [t, v[0], v[1]];`);
const TREE_DOC = "/**\n * Definition for a binary tree node.\n * function TreeNode(val, left, right) {\n *   this.val = (val === undefined ? 0 : val)\n *   this.left = (left === undefined ? null : left)\n *   this.right = (right === undefined ? null : right)\n * }\n */";
const ITER_DRIVER = `function runOps(ops) { const [[, level], ...calls] = ops; const obj = new BSTIterator(__treeFromLevelOrder(level)); return [null, ...calls.map(([op, ...args]) => { const out = obj[op](...args); return out === undefined ? null : out; })]; }`;
const ITER_DRIVER_DOC = `/**\n * Runs the operations and collects each result. Don't change this function.\n * The first operation is the constructor call; its argument is the tree in level order.\n * @param {Array<Array<string | number | Array<number | null>>>} ops\n * @return {Array<number | boolean | null>}\n */\nfunction runOps(ops) {\n  const [[, level], ...calls] = ops;\n  const obj = new BSTIterator(__treeFromLevelOrder(level));\n  return [null, ...calls.map(([op, ...args]) => {\n    const out = obj[op](...args);\n    return out === undefined ? null : out;\n  })];\n}`;

/** Judges for seeded LeetCode problems that the BST Ladder points at. LeetCode's own signatures. */
const DEFS: ProblemDef[] = [
  {
    slug: "search-in-a-binary-search-tree",
    title: "Search in a Binary Search Tree",
    difficulty: "Easy",
    pattern: "Trees",
    fn: "searchBST",
    params: [["root", T], ["val", "number"]],
    returns: T,
    argTypes: ["TreeNode", "value"],
    returnKind: "TreeNode",
    hints: [
      "In a BST everything smaller is on the left and everything larger on the right, so one comparison tells you which half to drop.",
      "Walk down from the root: go left when val is smaller, right when larger, and return the node when it matches (or null when you fall off).",
      "node = root\nwhile node and node.val != val:\n  node = node.left if val < node.val else node.right\nreturn node",
    ],
    reference: `function searchBST(root, val) { let n = root; while (n && n.val !== val) n = val < n.val ? n.left : n.right; return n; }`,
    brute: `function searchBST(root, val) { if (!root) return null; if (root.val === val) return root; return searchBST(root.left, val) || searchBST(root.right, val); }`,
    fuzz: treeGen(`const t = __bstLevel(rand, __r(rand, 1, 12), 1, 30); return [t, rand() < 0.85 ? __pick(rand, t.filter((x) => x !== null)) : __r(rand, 0, 32)];`),
    examples: [[[4, 2, 7, 1, 3], 2], [[4, 2, 7, 1, 3], 5]],
    edges: [
      ["single", [[1], 1]],
      ["no-answer", [[2, 1, 3], 4], "Not in the tree: return null (an empty tree)."],
      ["boundary", [[8, 3, 10, 1, 6], 8], "The root itself matches."],
    ],
  },
  {
    slug: "convert-sorted-array-to-binary-search-tree",
    title: "Convert Sorted Array to Binary Search Tree",
    difficulty: "Easy",
    pattern: "Trees",
    fn: "sortedArrayToBST",
    params: [["nums", "number[]"]],
    returns: T,
    returnKind: "TreeNode",
    compare: "balanced-same-inorder",
    hints: [
      "The middle element as root splits the rest into two halves of nearly equal size, which keeps the tree balanced.",
      "Recurse on index ranges: root = middle, left = build(left half), right = build(right half). Either middle works when the length is even; any height-balanced BST is accepted.",
      "build(lo, hi):\n  if lo > hi: return empty\n  mid = (lo + hi) // 2\n  node = new node(nums[mid])\n  node.left = build(lo, mid - 1)\n  node.right = build(mid + 1, hi)\n  return node\nreturn build(0, n - 1)",
    ],
    reference: `function sortedArrayToBST(nums) { const build = (lo, hi) => { if (lo > hi) return null; const m = (lo + hi) >> 1; return new TreeNode(nums[m], build(lo, m - 1), build(m + 1, hi)); }; return build(0, nums.length - 1); }`,
    brute: `function sortedArrayToBST(nums) { if (!nums.length) return null; const m = Math.ceil((nums.length - 1) / 2); return new TreeNode(nums[m], sortedArrayToBST(nums.slice(0, m)), sortedArrayToBST(nums.slice(m + 1))); }`,
    fuzz: gen(`return [__shuffle(rand, Array.from({ length: 31 }, (_, i) => i - 10)).slice(0, __r(rand, 1, 12)).sort((a, b) => a - b)];`),
    examples: [[[-10, -3, 0, 5, 9]], [[1, 3]]],
    edges: [
      ["single", [[0]]],
      ["negatives", [[-5, -4, -3]]],
      ["boundary", [[1, 2, 3, 4, 5, 6, 7]], "Seven values: a perfect tree."],
    ],
  },
  {
    slug: "minimum-absolute-difference-in-bst",
    title: "Minimum Absolute Difference in BST",
    difficulty: "Easy",
    pattern: "Trees",
    fn: "getMinimumDifference",
    params: [["root", T]],
    returns: "number",
    argTypes: ["TreeNode"],
    hints: [
      "An inorder walk of a BST visits values in sorted order, and the closest pair in a sorted list is always adjacent.",
      "Inorder traversal remembering the previous value; the answer is the smallest difference between neighbours.",
      "prev = none, best = infinity\ninorder(node):\n  if node is empty: return\n  inorder(node.left)\n  if prev is set: best = min(best, node.val - prev)\n  prev = node.val\n  inorder(node.right)\ninorder(root)\nreturn best",
    ],
    reference: `function getMinimumDifference(root) { let prev = null, best = Infinity; const go = (n) => { if (!n) return; go(n.left); if (prev !== null) best = Math.min(best, n.val - prev); prev = n.val; go(n.right); }; go(root); return best; }`,
    brute: `function getMinimumDifference(root) { const v = []; const go = (n) => { if (n) { v.push(n.val); go(n.left); go(n.right); } }; go(root); let best = Infinity; for (let i = 0; i < v.length; i++) for (let j = i + 1; j < v.length; j++) best = Math.min(best, Math.abs(v[i] - v[j])); return best; }`,
    fuzz: BST(2, 12),
    examples: [[[4, 2, 6, 1, 3]], [[1, 0, 48, null, null, 12, 49]]],
    edges: [
      ["two", [[1, null, 5]]],
      ["boundary", [[10, 5, 15, null, 9, 11]], "The closest pair is the root and a grandchild."],
      ["skewed", [[1, null, 3, null, 6]]],
    ],
  },
  {
    slug: "minimum-distance-between-bst-nodes",
    title: "Minimum Distance Between BST Nodes",
    difficulty: "Easy",
    pattern: "Trees",
    fn: "minDiffInBST",
    params: [["root", T]],
    returns: "number",
    argTypes: ["TreeNode"],
    hints: [
      "Inorder traversal of a BST is sorted, so only neighbours in that order can be the closest pair.",
      "Walk inorder iteratively with a stack, comparing each value with the previous one.",
      "stack = [], cur = root, prev = none, best = infinity\nwhile cur or stack not empty:\n  while cur: push cur; cur = cur.left\n  cur = pop\n  if prev is set: best = min(best, cur.val - prev)\n  prev = cur.val\n  cur = cur.right\nreturn best",
    ],
    reference: `function minDiffInBST(root) { const st = []; let cur = root, prev = null, best = Infinity; while (cur || st.length) { while (cur) { st.push(cur); cur = cur.left; } cur = st.pop(); if (prev !== null) best = Math.min(best, cur.val - prev); prev = cur.val; cur = cur.right; } return best; }`,
    brute: `function minDiffInBST(root) { const v = []; const go = (n) => { if (n) { v.push(n.val); go(n.left); go(n.right); } }; go(root); v.sort((a, b) => a - b); let best = Infinity; for (let i = 1; i < v.length; i++) best = Math.min(best, v[i] - v[i - 1]); return best; }`,
    fuzz: BST(2, 12),
    examples: [[[4, 2, 6, 1, 3]], [[1, 0, 48, null, null, 12, 49]]],
    edges: [
      ["two", [[5, 2]]],
      ["skewed", [[10, 7, null, 2]]],
      ["boundary", [[27, null, 34, null, 58, 50, null, 44]]],
    ],
  },
  {
    slug: "two-sum-iv-input-is-a-bst",
    title: "Two Sum IV - Input is a BST",
    difficulty: "Easy",
    pattern: "Trees",
    fn: "findTarget",
    params: [["root", T], ["k", "number"]],
    returns: "boolean",
    argTypes: ["TreeNode", "value"],
    hints: [
      "Two different nodes must add up to k. Classic Two Sum, but the numbers live in a tree.",
      "DFS with a set of values seen so far: if k - val is in the set, done. (Or take the sorted inorder list and use two pointers.)",
      "seen = empty set\ndfs(node):\n  if node is empty: return false\n  if k - node.val in seen: return true\n  add node.val to seen\n  return dfs(node.left) or dfs(node.right)\nreturn dfs(root)",
    ],
    reference: `function findTarget(root, k) { const seen = new Set(); const go = (n) => { if (!n) return false; if (seen.has(k - n.val)) return true; seen.add(n.val); return go(n.left) || go(n.right); }; return go(root); }`,
    brute: `function findTarget(root, k) { const v = []; const go = (n) => { if (n) { go(n.left); v.push(n.val); go(n.right); } }; go(root); let i = 0, j = v.length - 1; while (i < j) { const s = v[i] + v[j]; if (s === k) return true; if (s < k) i++; else j--; } return false; }`,
    fuzz: treeGen(`return [__bstLevel(rand, __r(rand, 1, 12), 1, 30), __r(rand, 2, 60)];`),
    examples: [[[5, 3, 6, 2, 4, null, 7], 9], [[5, 3, 6, 2, 4, null, 7], 28]],
    edges: [
      ["single", [[1], 2], "One node cannot pair with itself."],
      ["two", [[2, 1], 3]],
      ["no-answer", [[2, 1, 3], 6]],
    ],
  },
  {
    slug: "lowest-common-ancestor-of-a-binary-search-tree",
    title: "Lowest Common Ancestor of a Binary Search Tree",
    difficulty: "Medium",
    pattern: "Trees",
    fn: "lowestCommonAncestor",
    params: [["root", "TreeNode"], ["p", "TreeNode"], ["q", "TreeNode"]],
    returns: "TreeNode",
    argTypes: ["TreeNode", "TreeNodeRef", "TreeNodeRef"],
    returnKind: "TreeNodeVal",
    hints: [
      "In a BST, if both values are smaller than the node, the answer is on the left; if both are larger, on the right.",
      "Walk down from the root. The first node whose value lies between p and q (inclusive) is where their paths split: that is the LCA.",
      "node = root\nloop:\n  if p.val < node.val and q.val < node.val: node = node.left\n  else if p.val > node.val and q.val > node.val: node = node.right\n  else: return node",
    ],
    reference: `function lowestCommonAncestor(root, p, q) { let n = root; for (;;) { if (p.val < n.val && q.val < n.val) n = n.left; else if (p.val > n.val && q.val > n.val) n = n.right; else return n; } }`,
    brute: `function lowestCommonAncestor(root, p, q) { const path = (n, t, acc) => { if (!n) return false; acc.push(n); if (n === t || path(n.left, t, acc) || path(n.right, t, acc)) return true; acc.pop(); return false; }; const a = [], b = []; path(root, p, a); path(root, q, b); let i = 0; while (i < a.length && i < b.length && a[i] === b[i]) i++; return a[i - 1]; }`,
    fuzz: BST_PQ,
    examples: [[[6, 2, 8, 0, 4, 7, 9, null, null, 3, 5], 2, 8], [[6, 2, 8, 0, 4, 7, 9, null, null, 3, 5], 2, 4], [[2, 1], 2, 1]],
    edges: [
      ["skewed", [[1, null, 2, null, 3], 2, 3]],
      ["boundary", [[6, 2, 8, 0, 4], 0, 4], "The answer is p's parent, not the root."],
      ["order", [[6, 2, 8, 0, 4, 7, 9], 9, 7], "q is given before p in value order."],
    ],
  },
  {
    slug: "insert-into-a-binary-search-tree",
    title: "Insert into a Binary Search Tree",
    difficulty: "Medium",
    pattern: "Trees",
    fn: "insertIntoBST",
    params: [["root", T], ["val", "number"]],
    returns: T,
    argTypes: ["TreeNode", "value"],
    returnKind: "TreeNode",
    compare: "same-inorder",
    hints: [
      "val is not in the tree yet. Walk down as if searching for it; the empty spot you reach is a valid place for the new node. Any valid BST is accepted.",
      "Iterate: at each node go left if val is smaller, right if larger, and attach a new node at the first missing child. An empty tree becomes just the new node.",
      "if root is empty: return new node(val)\nnode = root\nloop:\n  if val < node.val:\n    if node.left is empty: node.left = new node(val); return root\n    node = node.left\n  else:\n    if node.right is empty: node.right = new node(val); return root\n    node = node.right",
    ],
    reference: `function insertIntoBST(root, val) { if (!root) return new TreeNode(val); let n = root; for (;;) { if (val < n.val) { if (!n.left) { n.left = new TreeNode(val); return root; } n = n.left; } else { if (!n.right) { n.right = new TreeNode(val); return root; } n = n.right; } } }`,
    brute: `function insertIntoBST(root, val) { const v = [val]; const go = (n) => { if (n) { v.push(n.val); go(n.left); go(n.right); } }; go(root); v.sort((a, b) => a - b); const build = (lo, hi) => { if (lo > hi) return null; const m = (lo + hi) >> 1; return new TreeNode(v[m], build(lo, m - 1), build(m + 1, hi)); }; return build(0, v.length - 1); }`,
    fuzz: treeGen(`const t = __bstLevel(rand, __r(rand, 0, 12), 1, 30); const have = new Set(t); let v = __r(rand, 0, 32); while (have.has(v)) v = __r(rand, 0, 32); return [t, v];`),
    examples: [[[4, 2, 7, 1, 3], 5], [[40, 20, 60, 10, 30, 50, 70], 25]],
    edges: [
      ["empty", [[], 5], "An empty tree becomes a single node."],
      ["extremes", [[4, 2, 7, 1, 3], 0], "Smaller than everything: goes to the far left."],
      ["skewed", [[1, null, 2, null, 3], 4]],
    ],
  },
  {
    slug: "delete-node-in-a-bst",
    title: "Delete Node in a BST",
    difficulty: "Medium",
    pattern: "Trees",
    fn: "deleteNode",
    params: [["root", T], ["key", "number"]],
    returns: T,
    argTypes: ["TreeNode", "value"],
    returnKind: "TreeNode",
    compare: "same-inorder",
    hints: [
      "Find the node first. A leaf just disappears and a node with one child is replaced by that child. Any valid BST is accepted.",
      "With two children, copy in the smallest value of the right subtree (the inorder successor), then delete that value from the right subtree.",
      "delete(node, key):\n  if node is empty: return empty\n  if key < node.val: node.left = delete(node.left, key)\n  else if key > node.val: node.right = delete(node.right, key)\n  else:\n    if node.left is empty: return node.right\n    if node.right is empty: return node.left\n    s = leftmost node of node.right\n    node.val = s.val\n    node.right = delete(node.right, s.val)\n  return node",
    ],
    reference: `function deleteNode(root, key) { if (!root) return null; if (key < root.val) root.left = deleteNode(root.left, key); else if (key > root.val) root.right = deleteNode(root.right, key); else { if (!root.left) return root.right; if (!root.right) return root.left; let s = root.right; while (s.left) s = s.left; root.val = s.val; root.right = deleteNode(root.right, s.val); } return root; }`,
    brute: `function deleteNode(root, key) { const v = []; const go = (n) => { if (n) { go(n.left); if (n.val !== key) v.push(n.val); go(n.right); } }; go(root); let r = null; const ins = (n, x) => { if (!n) return new TreeNode(x); if (x < n.val) n.left = ins(n.left, x); else n.right = ins(n.right, x); return n; }; for (const x of v.reverse()) r = ins(r, x); return r; }`,
    fuzz: treeGen(`const t = __bstLevel(rand, __r(rand, 0, 12), 1, 30); const vals = t.filter((x) => x !== null); return [t, vals.length && rand() < 0.75 ? __pick(rand, vals) : __r(rand, 0, 32)];`),
    examples: [[[5, 3, 6, 2, 4, null, 7], 3], [[5, 3, 6, 2, 4, null, 7], 0], [[], 0]],
    edges: [
      ["single", [[1], 1], "Deleting the only node leaves an empty tree."],
      ["boundary", [[5, 3, 6, 2, 4, null, 7], 5], "Delete the root, which has two children."],
      ["skewed", [[1, null, 2, null, 3], 2]],
    ],
  },
  {
    slug: "binary-search-tree-iterator",
    title: "Binary Search Tree Iterator",
    difficulty: "Medium",
    pattern: "Design (Coding)",
    fn: "runOps",
    params: [["ops", "Array<Array<string | number | Array<number | null>>>"]],
    returns: "Array<number | boolean | null>",
    starter: `${TREE_DOC}\nclass BSTIterator {\n  /** @param {TreeNode | null} root */\n  constructor(root) {\n    \n  }\n  next() {\n    \n  }\n  hasNext() {\n    \n  }\n}\n\n${ITER_DRIVER_DOC}`,
    hints: [
      "next() returns values in sorted order, which is an inorder traversal paused between calls.",
      "Keep a stack of the left spine. next() pops a node, then pushes the left spine of its right child. Each node is pushed once, so next() is O(1) on average and memory is O(height).",
      "constructor(root): stack = []; pushLeft(root)\npushLeft(node): while node: push node; node = node.left\nnext():\n  node = pop\n  pushLeft(node.right)\n  return node.val\nhasNext(): return stack not empty",
    ],
    reference: `class BSTIterator { constructor(root) { this.st = []; this.push(root); } push(n) { while (n) { this.st.push(n); n = n.left; } } next() { const n = this.st.pop(); this.push(n.right); return n.val; } hasNext() { return this.st.length > 0; } }\n${ITER_DRIVER}`,
    brute: `class BSTIterator { constructor(root) { this.v = []; const go = (n) => { if (n) { go(n.left); this.v.push(n.val); go(n.right); } }; go(root); this.i = 0; } next() { return this.v[this.i++]; } hasNext() { return this.i < this.v.length; } }\n${ITER_DRIVER}`,
    fuzz: treeGen(`const t = __bstLevel(rand, __r(rand, 1, 10), 1, 30); let left = t.filter((x) => x !== null).length; const ops = [["BSTIterator", t]]; const n = __r(rand, 1, 14); for (let i = 0; i < n; i++) { if (left > 0 && rand() < 0.6) { ops.push(["next"]); left--; } else ops.push(["hasNext"]); } return [ops];`),
    examples: [[[["BSTIterator", [7, 3, 15, null, null, 9, 20]], ["next"], ["next"], ["hasNext"], ["next"], ["hasNext"], ["next"], ["hasNext"], ["next"], ["hasNext"]]], [[["BSTIterator", [1]], ["hasNext"], ["next"], ["hasNext"]]]],
    edges: [
      ["skewed", [[["BSTIterator", [3, 2, null, 1]], ["next"], ["next"], ["next"], ["hasNext"]]], "A left chain: the stack starts full."],
      ["order", [[["BSTIterator", [1, null, 2, null, 3]], ["next"], ["hasNext"], ["next"], ["next"], ["hasNext"]]]],
      ["boundary", [[["BSTIterator", [5, 3, 8]], ["hasNext"], ["hasNext"], ["next"]]], "hasNext never advances."],
    ],
  },
  {
    slug: "recover-binary-search-tree",
    title: "Recover Binary Search Tree",
    difficulty: "Medium",
    pattern: "Trees",
    fn: "recoverTree",
    params: [["root", T]],
    returns: "void",
    argTypes: ["TreeNode"],
    returnKind: "arg0",
    hints: [
      "Exactly two values were swapped, so the inorder sequence is sorted except for one or two places where a value is bigger than the next.",
      "Walk inorder with a prev pointer. At the first drop, first = prev; at every drop, second = current. Swap the values of first and second at the end.",
      "first = second = prev = none\ninorder(node):\n  if node is empty: return\n  inorder(node.left)\n  if prev and prev.val > node.val:\n    if first is none: first = prev\n    second = node\n  prev = node\n  inorder(node.right)\ninorder(root)\nswap first.val and second.val",
    ],
    reference: `function recoverTree(root) { let first = null, second = null, prev = null; const go = (n) => { if (!n) return; go(n.left); if (prev && prev.val > n.val) { if (!first) first = prev; second = n; } prev = n; go(n.right); }; go(root); const t = first.val; first.val = second.val; second.val = t; }`,
    brute: `function recoverTree(root) { const nodes = []; const go = (n) => { if (n) { go(n.left); nodes.push(n); go(n.right); } }; go(root); const vals = nodes.map((n) => n.val).sort((a, b) => a - b); nodes.forEach((n, i) => { n.val = vals[i]; }); }`,
    fuzz: treeGen(`const t = __bstLevel(rand, __r(rand, 2, 12), 1, 30); const idx = []; t.forEach((v, i) => { if (v !== null) idx.push(i); }); const [a, b] = __shuffle(rand, idx).slice(0, 2); const s = t[a]; t[a] = t[b]; t[b] = s; return [t];`),
    examples: [[[1, 3, null, null, 2]], [[3, 1, 4, null, null, 2]]],
    edges: [
      ["two", [[1, 2]], "Two nodes swapped with each other."],
      ["boundary", [[2, 3, 1]], "The two swapped nodes are siblings."],
      ["skewed", [[3, null, 2, null, 1]]],
    ],
  },
  {
    slug: "unique-binary-search-trees",
    title: "Unique Binary Search Trees",
    difficulty: "Medium",
    pattern: "Trees",
    fn: "numTrees",
    params: [["n", "number"]],
    returns: "number",
    hints: [
      "Pick the root i. The values below it form the left subtree and the values above it the right, independently.",
      "Let g[k] be the number of BSTs on k values. g[k] = sum over the root position of g[left size] * g[right size], with g[0] = g[1] = 1 (the Catalan numbers).",
      "g = [1, 1, 0, ...]\nfor k in 2 .. n:\n  for root in 1 .. k:\n    g[k] = g[k] + g[root - 1] * g[k - root]\nreturn g[n]",
    ],
    reference: `function numTrees(n) { const g = [1, 1]; for (let k = 2; k <= n; k++) { g[k] = 0; for (let r = 1; r <= k; r++) g[k] += g[r - 1] * g[k - r]; } return g[n]; }`,
    brute: `function numTrees(n) { const f = (k) => { if (k <= 1) return 1; let s = 0; for (let r = 1; r <= k; r++) s += f(r - 1) * f(k - r); return s; }; return f(n); }`,
    fuzz: gen(`return [__r(rand, 1, 12)];`),
    examples: [[3], [1]],
    edges: [
      ["two", [2]],
      ["boundary", [4]],
      ["large", [15]],
    ],
  },
  {
    slug: "unique-binary-search-trees-ii",
    title: "Unique Binary Search Trees II",
    difficulty: "Medium",
    pattern: "Trees",
    fn: "generateTrees",
    params: [["n", "number"]],
    returns: "Array<TreeNode | null>",
    returnKind: "TreeNode[]",
    compare: "unordered-outer",
    hints: [
      "Every value can be the root; then every left subtree from the smaller values pairs with every right subtree from the larger ones. Any order of trees is accepted.",
      "Recurse on a value range [lo, hi]: an empty range gives [null]. For each root, combine every left tree with every right tree.",
      "build(lo, hi):\n  if lo > hi: return [empty]\n  out = []\n  for r in lo .. hi:\n    for L in build(lo, r - 1):\n      for R in build(r + 1, hi):\n        out.append(new node(r, L, R))\n  return out\nreturn build(1, n)",
    ],
    reference: `function generateTrees(n) { const build = (lo, hi) => { if (lo > hi) return [null]; const out = []; for (let r = lo; r <= hi; r++) for (const L of build(lo, r - 1)) for (const R of build(r + 1, hi)) out.push(new TreeNode(r, L, R)); return out; }; return build(1, n); }`,
    brute: `function generateTrees(n) { const seen = new Map(); const perm = (arr, used) => { if (arr.length === n) { let root = null; const ins = (node, v) => { if (!node) return new TreeNode(v); if (v < node.val) node.left = ins(node.left, v); else node.right = ins(node.right, v); return node; }; for (const v of arr) root = ins(root, v); const key = JSON.stringify(__treeToLevelOrder(root)); if (!seen.has(key)) seen.set(key, root); return; } for (let v = 1; v <= n; v++) if (!used[v]) { used[v] = true; arr.push(v); perm(arr, used); arr.pop(); used[v] = false; } }; perm([], []); return [...seen.values()]; }`,
    fuzz: gen(`return [__r(rand, 1, 5)];`),
    examples: [[3], [1]],
    edges: [
      ["two", [2]],
      ["boundary", [4], "14 trees."],
      ["large", [5], "42 trees."],
    ],
  },
  {
    slug: "trim-a-binary-search-tree",
    title: "Trim a Binary Search Tree",
    difficulty: "Medium",
    pattern: "Trees",
    fn: "trimBST",
    params: [["root", T], ["low", "number"], ["high", "number"]],
    returns: T,
    argTypes: ["TreeNode", "value", "value"],
    returnKind: "TreeNode",
    hints: [
      "If a node is below low, it and its whole left subtree are gone, but its right subtree may still have keepers. Symmetrically above high.",
      "Recurse: too small means return trim(right); too big means return trim(left); otherwise trim both children and keep the node.",
      "trim(node):\n  if node is empty: return empty\n  if node.val < low: return trim(node.right)\n  if node.val > high: return trim(node.left)\n  node.left = trim(node.left)\n  node.right = trim(node.right)\n  return node",
    ],
    reference: `function trimBST(root, low, high) { if (!root) return null; if (root.val < low) return trimBST(root.right, low, high); if (root.val > high) return trimBST(root.left, low, high); root.left = trimBST(root.left, low, high); root.right = trimBST(root.right, low, high); return root; }`,
    brute: `function trimBST(root, low, high) { const keep = []; const go = (n) => { if (n) { if (n.val >= low && n.val <= high) keep.push(n.val); go(n.left); go(n.right); } }; go(root); let r = null; const ins = (n, v) => { if (!n) return new TreeNode(v); if (v < n.val) n.left = ins(n.left, v); else n.right = ins(n.right, v); return n; }; for (const v of keep) r = ins(r, v); return r; }`,
    fuzz: treeGen(`const lo = __r(rand, 0, 25); return [__bstLevel(rand, __r(rand, 1, 12), 1, 30), lo, lo + __r(rand, 0, 12)];`),
    examples: [[[1, 0, 2], 1, 2], [[3, 0, 4, null, 2, null, null, 1], 1, 3]],
    edges: [
      ["no-answer", [[5, 3, 8], 10, 12], "Everything is out of range."],
      ["boundary", [[5, 3, 8], 3, 8], "The range covers every value: nothing changes."],
      ["single", [[4], 4, 4]],
    ],
  },
  {
    slug: "construct-binary-search-tree-from-preorder-traversal",
    title: "Construct Binary Search Tree from Preorder Traversal",
    difficulty: "Medium",
    pattern: "Trees",
    fn: "bstFromPreorder",
    params: [["preorder", "number[]"]],
    returns: T,
    returnKind: "TreeNode",
    hints: [
      "Inserting the values one by one works in O(n^2). Can you place each value with an upper bound instead?",
      "Recurse with a bound: build a node from the next value only if it is below the bound; its left subtree gets the node's value as bound, its right subtree inherits the parent's bound.",
      "i = 0\nbuild(bound):\n  if i == n or preorder[i] > bound: return empty\n  node = new node(preorder[i]); i += 1\n  node.left = build(node.val)\n  node.right = build(bound)\n  return node\nreturn build(infinity)",
    ],
    reference: `function bstFromPreorder(preorder) { let i = 0; const build = (bound) => { if (i === preorder.length || preorder[i] > bound) return null; const n = new TreeNode(preorder[i++]); n.left = build(n.val); n.right = build(bound); return n; }; return build(Infinity); }`,
    brute: `function bstFromPreorder(preorder) { let r = null; const ins = (n, v) => { if (!n) return new TreeNode(v); if (v < n.val) n.left = ins(n.left, v); else n.right = ins(n.right, v); return n; }; for (const v of preorder) r = ins(r, v); return r; }`,
    fuzz: treeGen(`const t = __bstLevel(rand, __r(rand, 1, 12), 1, 30); const pre = []; const walk = (n) => { if (n) { pre.push(n.val); walk(n.left); walk(n.right); } }; walk(__treeFromLevelOrder(t)); return [pre];`),
    examples: [[[8, 5, 1, 7, 10, 12]], [[1, 3]]],
    edges: [
      ["single", [[4]]],
      ["reverse-sorted", [[5, 4, 3, 2]], "Decreasing preorder: a left chain."],
      ["sorted", [[1, 2, 3, 4]], "Increasing preorder: a right chain."],
    ],
  },
  {
    slug: "convert-bst-to-greater-tree",
    title: "Convert BST to Greater Tree",
    difficulty: "Medium",
    pattern: "Trees",
    fn: "convertBST",
    params: [["root", T]],
    returns: T,
    argTypes: ["TreeNode"],
    returnKind: "TreeNode",
    hints: [
      "Each node becomes itself plus every larger value. Visiting nodes from largest to smallest lets you keep a running sum.",
      "Reverse inorder (right, node, left) with a running total; add the node's value to the total and write the total back.",
      "total = 0\nvisit(node):\n  if node is empty: return\n  visit(node.right)\n  total = total + node.val\n  node.val = total\n  visit(node.left)\nvisit(root)\nreturn root",
    ],
    reference: `function convertBST(root) { let total = 0; const go = (n) => { if (!n) return; go(n.right); total += n.val; n.val = total; go(n.left); }; go(root); return root; }`,
    brute: `function convertBST(root) { const vals = []; const collect = (n) => { if (n) { vals.push(n.val); collect(n.left); collect(n.right); } }; collect(root); const set = (n) => { if (!n) return null; return new TreeNode(vals.filter((v) => v >= n.val).reduce((a, b) => a + b, 0), set(n.left), set(n.right)); }; return set(root); }`,
    fuzz: treeGen(`return [__bstLevel(rand, __r(rand, 0, 12), 0, 30)];`),
    examples: [[[4, 1, 6, 0, 2, 5, 7, null, null, null, 3, null, null, null, 8]], [[0, null, 1]]],
    edges: [
      ["empty", [[]]],
      ["single", [[5]]],
      ["skewed", [[3, 2, null, 1]]],
    ],
  },
  design({
    slug: "my-calendar-i",
    title: "My Calendar I",
    difficulty: "Medium",
    pattern: "Binary Search Tree",
    cls: "MyCalendar",
    methods: ["book(startTime, endTime)"],
    hints: [
      "Two half-open intervals [s1, e1) and [s2, e2) overlap exactly when s1 < e2 and s2 < e1.",
      "Keep the booked intervals sorted by start. Binary search for the insert position and check only the neighbours on each side (a balanced BST or sorted map does this in O(log n)).",
      "book(s, e):\n  i = first position whose start >= s\n  if i > 0 and booked[i - 1].end > s: return false\n  if i < len(booked) and booked[i].start < e: return false\n  insert (s, e) at i\n  return true",
    ],
    reference: `class MyCalendar { constructor() { this.b = []; } book(startTime, endTime) { let lo = 0, hi = this.b.length; while (lo < hi) { const m = (lo + hi) >> 1; if (this.b[m][0] < startTime) lo = m + 1; else hi = m; } if (lo > 0 && this.b[lo - 1][1] > startTime) return false; if (lo < this.b.length && this.b[lo][0] < endTime) return false; this.b.splice(lo, 0, [startTime, endTime]); return true; } }`,
    brute: `class MyCalendar { constructor() { this.b = []; } book(s, e) { for (const [a, c] of this.b) if (s < c && a < e) return false; this.b.push([s, e]); return true; } }`,
    fuzz: gen(`const ops = [["MyCalendar"]]; const n = __r(rand, 1, 12); for (let i = 0; i < n; i++) { const s = __r(rand, 0, 30); ops.push(["book", s, s + __r(rand, 1, 6)]); } return [ops];`),
    examples: [[[["MyCalendar"], ["book", 10, 20], ["book", 15, 25], ["book", 20, 30]]], [[["MyCalendar"], ["book", 5, 10], ["book", 1, 5]]]],
    edges: [
      ["boundary", [[["MyCalendar"], ["book", 1, 3], ["book", 3, 5], ["book", 0, 1]]], "Touching end and start do not overlap."],
      ["duplicates", [[["MyCalendar"], ["book", 2, 4], ["book", 2, 4]]]],
      ["order", [[["MyCalendar"], ["book", 10, 20], ["book", 0, 5], ["book", 4, 11]]], "The third booking overlaps both neighbours."],
    ],
  }),
  {
    slug: "maximum-sum-bst-in-binary-tree",
    title: "Maximum Sum BST in Binary Tree",
    difficulty: "Hard",
    pattern: "Trees",
    fn: "maxSumBST",
    params: [["root", T]],
    returns: "number",
    argTypes: ["TreeNode"],
    hints: [
      "A subtree is a BST when both children are BSTs and the node is above the left maximum and below the right minimum. The empty BST counts, so the answer is at least 0.",
      "Post-order DFS returning (isBST, min, max, sum) for each subtree; when it is a BST, update the best sum.",
      "best = 0\ninfo(node):\n  if node is empty: return (true, +inf, -inf, 0)\n  L = info(node.left); R = info(node.right)\n  if L.ok and R.ok and L.max < node.val < R.min:\n    s = L.sum + R.sum + node.val\n    best = max(best, s)\n    return (true, min(L.min, node.val), max(R.max, node.val), s)\n  return (false, 0, 0, 0)\ninfo(root)\nreturn best",
    ],
    reference: `function maxSumBST(root) { let best = 0; const go = (n) => { if (!n) return [true, Infinity, -Infinity, 0]; const L = go(n.left), R = go(n.right); if (L[0] && R[0] && L[2] < n.val && n.val < R[1]) { const s = L[3] + R[3] + n.val; best = Math.max(best, s); return [true, Math.min(L[1], n.val), Math.max(R[2], n.val), s]; } return [false, 0, 0, 0]; }; go(root); return best; }`,
    brute: `function maxSumBST(root) { const vals = (n, out) => { if (n) { vals(n.left, out); out.push(n.val); vals(n.right, out); } return out; }; let best = 0; const all = (n) => { if (!n) return; const v = vals(n, []); let ok = true; for (let i = 1; i < v.length; i++) if (v[i] <= v[i - 1]) ok = false; if (ok) best = Math.max(best, v.reduce((a, b) => a + b, 0)); all(n.left); all(n.right); }; all(root); return best; }`,
    fuzz: treeGen(`return [rand() < 0.4 ? __bstLevel(rand, __r(rand, 1, 10), 1, 20) : __levelTree(rand, __r(rand, 1, 12), -5, 9)];`),
    examples: [[[1, 4, 3, 2, 4, 2, 5, null, null, null, null, null, null, 4, 6]], [[4, 3, null, 1, 2]], [[-4, -2, -5]]],
    edges: [
      ["single", [[5]]],
      ["negatives", [[-1, -2, -3]], "Every BST has a negative sum: the empty BST (0) wins."],
      ["duplicates", [[2, 2, 3]], "Equal values break the BST rule."],
    ],
  },
  {
    slug: "count-of-smaller-numbers-after-self",
    title: "Count of Smaller Numbers After Self",
    difficulty: "Hard",
    pattern: "Binary Search Tree",
    fn: "countSmaller",
    params: [["nums", "number[]"]],
    returns: "number[]",
    hints: [
      "For each value you need how many values to its right are strictly smaller. Scanning from the right, that is a rank query on everything seen so far.",
      "Scan from the right inserting into a sorted structure (a BST with subtree sizes, a Fenwick tree over ranks, or merge sort counting how many right-half items jump ahead).",
      "ranks = compress values to 1..m\nfenwick = empty tree of size m\nfor i from n - 1 down to 0:\n  ans[i] = fenwick.sum(rank[i] - 1)\n  fenwick.add(rank[i], 1)\nreturn ans",
    ],
    reference: `function countSmaller(nums) { const sorted = [...new Set(nums)].sort((a, b) => a - b), rank = new Map(sorted.map((v, i) => [v, i + 1])), bit = new Array(sorted.length + 1).fill(0), ans = new Array(nums.length); for (let i = nums.length - 1; i >= 0; i--) { let s = 0; for (let j = rank.get(nums[i]) - 1; j > 0; j -= j & -j) s += bit[j]; ans[i] = s; for (let j = rank.get(nums[i]); j < bit.length; j += j & -j) bit[j]++; } return ans; }`,
    brute: `function countSmaller(nums) { return nums.map((v, i) => nums.slice(i + 1).filter((x) => x < v).length); }`,
    fuzz: gen(`return [__arr(rand, __r(rand, 1, 12), -5, 9)];`),
    examples: [[[5, 2, 6, 1]], [[-1]], [[-1, -1]]],
    edges: [
      ["sorted", [[1, 2, 3, 4]], "Increasing: nothing smaller to the right."],
      ["reverse-sorted", [[4, 3, 2, 1]]],
      ["duplicates", [[2, 0, 2, 0]], "Only strictly smaller values count."],
    ],
  },
];

export const LADDER_BST_SEEDED: ProblemSpec[] = DEFS.map((d) => define(d).spec);
