import { define, type ProblemDef } from "../../dsa-extras/define";
import { gen } from "../../dsa-extras/gen";
import type { ProblemSpec } from "../types";
import { loadGenerator, mulberry32 } from "../vm-runner";

/** Group generator: k groups that each sum to the same target, shuffled (so "can partition" is true about half the time). */
const GROUPS = `function __groups(rand, k, lo, hi) { var t = __r(rand, lo, hi), out = []; for (var g = 0; g < k; g++) { var left = t; while (left > 0) { var p = __r(rand, 1, left); out.push(p); left -= p; } } return __shuffle(rand, out); }`;

/** A random solved grid with cells blanked one at a time while the solution stays unique. */
const SUDOKU = `
function __sudokuSolved(rand) {
  var digits = __shuffle(rand, [1, 2, 3, 4, 5, 6, 7, 8, 9]);
  function order() { var bands = __shuffle(rand, [0, 1, 2]), out = []; for (var b = 0; b < 3; b++) { var inner = __shuffle(rand, [0, 1, 2]); for (var i = 0; i < 3; i++) out.push(bands[b] * 3 + inner[i]); } return out; }
  var rows = order(), cols = order(), g = [];
  for (var r = 0; r < 9; r++) { var row = []; for (var c = 0; c < 9; c++) { var R = rows[r], C = cols[c]; row.push(digits[(R * 3 + Math.floor(R / 3) + C) % 9]); } g.push(row); }
  return g;
}
function __sudokuCount(g, limit) {
  var best = -1, bestMask = 0, bestCount = 10;
  for (var i = 0; i < 81; i++) {
    var r = Math.floor(i / 9), c = i % 9;
    if (g[r][c]) continue;
    var used = 0, br = r - r % 3, bc = c - c % 3;
    for (var k = 0; k < 9; k++) used |= (1 << g[r][k]) | (1 << g[k][c]) | (1 << g[br + Math.floor(k / 3)][bc + k % 3]);
    var free = ~used & 1022, cnt = 0;
    for (var d = 1; d <= 9; d++) if (free & (1 << d)) cnt++;
    if (cnt === 0) return 0;
    if (cnt < bestCount) { bestCount = cnt; best = i; bestMask = free; }
  }
  if (best < 0) return 1;
  var total = 0, r0 = Math.floor(best / 9), c0 = best % 9;
  for (var dd = 1; dd <= 9 && total < limit; dd++) if (bestMask & (1 << dd)) { g[r0][c0] = dd; total += __sudokuCount(g, limit - total); g[r0][c0] = 0; }
  return total;
}
function __sudokuPuzzle(rand, blanks, blankRow) {
  var g = __sudokuSolved(rand);
  if (blankRow) { for (var c = 0; c < 9; c++) g[4][c] = 0; }
  else {
    var cells = __shuffle(rand, Array.from({ length: 81 }, function (_, i) { return i; })), removed = 0;
    for (var t = 0; t < 81 && removed < blanks; t++) { var r = Math.floor(cells[t] / 9), cc = cells[t] % 9, keep = g[r][cc]; g[r][cc] = 0; if (__sudokuCount(g, 2) === 1) removed++; else g[r][cc] = keep; }
  }
  return g.map(function (row) { return row.map(function (v) { return v ? String(v) : "."; }); });
}`;
const sudoku = (seed: number, blanks: number, blankRow = false): unknown[] =>
  loadGenerator(gen(`${SUDOKU} return [__sudokuPuzzle(rand, ${blanks}, ${blankRow})];`))(mulberry32(seed)) as unknown[];

const LC_SUDOKU = [
  ["5", "3", ".", ".", "7", ".", ".", ".", "."],
  ["6", ".", ".", "1", "9", "5", ".", ".", "."],
  [".", "9", "8", ".", ".", ".", ".", "6", "."],
  ["8", ".", ".", ".", "6", ".", ".", ".", "3"],
  ["4", ".", ".", "8", ".", "3", ".", ".", "1"],
  ["7", ".", ".", ".", "2", ".", ".", ".", "6"],
  [".", "6", ".", ".", ".", ".", "2", "8", "."],
  [".", ".", ".", "4", "1", "9", ".", ".", "5"],
  [".", ".", ".", ".", "8", ".", ".", "7", "9"],
];
const WORD_BOARD = [["A", "B", "C", "E"], ["S", "F", "C", "S"], ["A", "D", "E", "E"]];

/** Judges for seeded LeetCode problems that the Recursion & Backtracking Ladder points at. LeetCode's own signatures. */
const DEFS: ProblemDef[] = [
  {
    slug: "fibonacci-number",
    title: "Fibonacci Number",
    difficulty: "Easy",
    pattern: "Recursion",
    fn: "fib",
    params: [["n", "number"]],
    returns: "number",
    hints: [
      "F(n) is defined in terms of F(n - 1) and F(n - 2). What are the two base cases?",
      "Recursion with F(0) = 0 and F(1) = 1 works; to avoid recomputing, keep just the last two values and walk up from 2 to n.",
      "if n < 2: return n\na = 0, b = 1\nrepeat n - 1 times:\n  a, b = b, a + b\nreturn b",
    ],
    reference: `function fib(n) { let a = 0, b = 1; for (let i = 0; i < n; i++) [a, b] = [b, a + b]; return a; }`,
    brute: `function fib(n) { return n < 2 ? n : fib(n - 1) + fib(n - 2); }`,
    fuzz: gen(`return [__r(rand, 0, 25)];`),
    examples: [[2], [4]],
    edges: [
      ["zeros", [0], "F(0) is 0, a base case."],
      ["single", [1]],
      ["extremes", [30], "Plain double recursion makes about 1.6 million calls here."],
    ],
  },
  {
    slug: "powx-n",
    title: "Pow(x, n)",
    difficulty: "Medium",
    pattern: "Recursion",
    fn: "myPow",
    params: [["x", "number"], ["n", "number"]],
    returns: "number",
    hints: [
      "Multiplying x by itself n times is O(n), and n can be about 2 billion. How does x^n relate to x^(n/2)?",
      "x^n = (x^(n/2))^2, times x when n is odd. For negative n, compute (1/x)^(-n), taking care that -n can exceed the 32-bit range.",
      "if n < 0: x = 1 / x, n = -n\nresult = 1\nwhile n > 0:\n  if n is odd: result = result * x\n  x = x * x\n  n = n div 2\nreturn result",
    ],
    reference: `function myPow(x, n) { let N = n, b = x; if (N < 0) { b = 1 / b; N = -N; } let r = 1; while (N > 0) { if (N % 2 === 1) r *= b; b *= b; N = Math.floor(N / 2); } return r; }`,
    brute: `function myPow(x, n) { return Math.pow(x, n); }`,
    fuzz: gen(`if (rand() < 0.5) return [__pick(rand, [2, -2, 0.5, -0.5, 0.25, 4, 1, -1]), __r(rand, -10, 10)]; return [__r(rand, -4, 4), __r(rand, 0, 12)];`),
    examples: [[2, 10], [2, -2]],
    edges: [
      ["extremes", [1, -2147483648], "n = -2^31: negating it overflows a 32-bit int, and a loop of n steps is far too slow."],
      ["zeros", [0, 5]],
      ["negatives", [-2, 3], "A negative base with an odd power stays negative."],
      ["boundary", [2, -2147483648], "Underflows to 0."],
    ],
  },
  {
    slug: "letter-case-permutation",
    title: "Letter Case Permutation",
    difficulty: "Medium",
    pattern: "Backtracking",
    fn: "letterCasePermutation",
    params: [["s", "string"]],
    returns: "string[]",
    compare: "unordered",
    hints: [
      "Digits have one choice, letters have two. Walk the string and branch only on letters.",
      "Recurse over positions with the string built so far: for a digit append it; for a letter recurse twice, once lower-case and once upper-case.",
      "go(i, cur):\n  if i == length: add cur to result; return\n  ch = s[i]\n  if ch is a digit: go(i + 1, cur + ch)\n  else:\n    go(i + 1, cur + lower(ch))\n    go(i + 1, cur + upper(ch))\ngo(0, \"\")",
    ],
    reference: `function letterCasePermutation(s) { const out = []; const go = (i, cur) => { if (i === s.length) { out.push(cur); return; } const c = s[i]; if (/[0-9]/.test(c)) go(i + 1, cur + c); else { go(i + 1, cur + c.toLowerCase()); go(i + 1, cur + c.toUpperCase()); } }; go(0, ""); return out; }`,
    brute: `function letterCasePermutation(s) { const idx = []; for (let i = 0; i < s.length; i++) if (/[a-z]/i.test(s[i])) idx.push(i); const out = []; for (let m = 0; m < 1 << idx.length; m++) { const a = s.toLowerCase().split(""); idx.forEach((p, b) => { if (m & (1 << b)) a[p] = a[p].toUpperCase(); }); out.push(a.join("")); } return out; }`,
    fuzz: gen(`return [__str(rand, __r(rand, 1, 6), "aB1c2D")];`),
    examples: [["a1b2"], ["3z4"]],
    edges: [
      ["single-char", ["1"], "No letters: the string itself is the only answer."],
      ["case-mix", ["Ab"], "Input case doesn't matter; both cases of each letter appear."],
      ["boundary", ["12345"]],
    ],
  },
  {
    slug: "subsets-ii",
    title: "Subsets II",
    difficulty: "Medium",
    pattern: "Backtracking",
    fn: "subsetsWithDup",
    params: [["nums", "number[]"]],
    returns: "number[][]",
    compare: "unordered",
    hints: [
      "Plain subset generation repeats subsets when values repeat. Sorting puts equal values together: how does that help skip repeats?",
      "Sort. At each level, loop over the remaining positions and skip a value equal to the previous one at the same level.",
      "sort nums\ngo(start, path):\n  add copy of path to result\n  for i from start to n - 1:\n    if i > start and nums[i] == nums[i - 1]: skip\n    push nums[i]; go(i + 1, path); pop\ngo(0, [])",
    ],
    reference: `function subsetsWithDup(nums) { const a = nums.slice().sort((x, y) => x - y), out = [], path = []; const go = (s) => { out.push(path.slice()); for (let i = s; i < a.length; i++) { if (i > s && a[i] === a[i - 1]) continue; path.push(a[i]); go(i + 1); path.pop(); } }; go(0); return out; }`,
    brute: `function subsetsWithDup(nums) { const a = nums.slice().sort((x, y) => x - y), seen = new Set(), out = []; for (let m = 0; m < 1 << a.length; m++) { const s = a.filter((_, i) => m & (1 << i)); const k = JSON.stringify(s); if (!seen.has(k)) { seen.add(k); out.push(s); } } return out; }`,
    fuzz: gen(`return [__arr(rand, __r(rand, 1, 7), -2, 2)];`),
    examples: [[[1, 2, 2]], [[0]]],
    edges: [
      ["all-equal", [[1, 1, 1]], "Only the sizes differ: [], [1], [1,1], [1,1,1]."],
      ["duplicates", [[4, 4, 4, 1, 4]]],
      ["negatives", [[-1, 1, -1]]],
    ],
  },
  {
    slug: "combinations",
    title: "Combinations",
    difficulty: "Medium",
    pattern: "Backtracking",
    fn: "combine",
    params: [["n", "number"], ["k", "number"]],
    returns: "number[][]",
    compare: "unordered",
    hints: [
      "Choose numbers in increasing order so each combination is built exactly once.",
      "Recurse with the next smallest number allowed; stop when the path has k numbers. Prune when too few numbers remain.",
      "go(start, path):\n  if size of path == k: add copy; return\n  for x from start to n:\n    if n - x + 1 < k - size of path: stop\n    push x; go(x + 1, path); pop\ngo(1, [])",
    ],
    reference: `function combine(n, k) { const out = [], p = []; const go = (s) => { if (p.length === k) { out.push(p.slice()); return; } for (let x = s; x <= n - (k - p.length) + 1; x++) { p.push(x); go(x + 1); p.pop(); } }; go(1); return out; }`,
    brute: `function combine(n, k) { const out = []; for (let m = 0; m < 1 << n; m++) { const s = []; for (let i = 0; i < n; i++) if (m & (1 << i)) s.push(i + 1); if (s.length === k) out.push(s); } return out; }`,
    fuzz: gen(`const n = __r(rand, 1, 8); return [n, __r(rand, 1, n)];`),
    examples: [[4, 2], [1, 1]],
    edges: [
      ["boundary", [5, 5], "k = n: just one combination."],
      ["single", [6, 1]],
      ["large", [10, 5], "252 combinations."],
    ],
  },
  {
    slug: "combination-sum",
    title: "Combination Sum",
    difficulty: "Medium",
    pattern: "Backtracking",
    fn: "combinationSum",
    params: [["candidates", "number[]"], ["target", "number"]],
    returns: "number[][]",
    compare: "unordered",
    hints: [
      "Each candidate can be used any number of times. How do you avoid producing [2,3] and [3,2] as different answers?",
      "Recurse with a start index: you may pick candidates[i] again (stay at i) or move on, never going back. Stop when the remaining target hits 0 or goes negative.",
      "go(start, remain, path):\n  if remain == 0: add copy; return\n  for i from start to n - 1:\n    if candidates[i] <= remain:\n      push candidates[i]\n      go(i, remain - candidates[i], path)\n      pop\ngo(0, target, [])",
    ],
    reference: `function combinationSum(candidates, target) { const out = [], p = []; const go = (s, r) => { if (r === 0) { out.push(p.slice()); return; } for (let i = s; i < candidates.length; i++) if (candidates[i] <= r) { p.push(candidates[i]); go(i, r - candidates[i]); p.pop(); } }; go(0, target); return out; }`,
    brute: `function combinationSum(candidates, target) { const c = candidates.slice().sort((a, b) => a - b); let layer = [[[], 0, 0]]; const out = []; while (layer.length) { const next = []; for (const [path, sum, s] of layer) { if (sum === target) { out.push(path); continue; } for (let i = s; i < c.length; i++) if (sum + c[i] <= target) next.push([path.concat(c[i]), sum + c[i], i]); } layer = next; } return out; }`,
    fuzz: gen(`const s = new Set(); const n = __r(rand, 1, 5); while (s.size < n) s.add(__r(rand, 2, 12)); return [[...s], __r(rand, 1, 20)];`),
    examples: [[[2, 3, 6, 7], 7], [[2, 3, 5], 8]],
    edges: [
      ["no-answer", [[2], 1]],
      ["reuse", [[3], 9], "The same candidate three times."],
      ["single", [[7], 7]],
    ],
  },
  {
    slug: "combination-sum-ii",
    title: "Combination Sum II",
    difficulty: "Medium",
    pattern: "Backtracking",
    fn: "combinationSum2",
    params: [["candidates", "number[]"], ["target", "number"]],
    returns: "number[][]",
    compare: "unordered",
    hints: [
      "Each position is used at most once, but values can repeat. Sorting makes equal values adjacent; how do you avoid repeated combinations?",
      "Sort. Recurse from start; at one level skip candidates[i] when it equals candidates[i - 1] (i > start). Stop early once a candidate exceeds the remaining target.",
      "sort candidates\ngo(start, remain, path):\n  if remain == 0: add copy; return\n  for i from start to n - 1:\n    if i > start and candidates[i] == candidates[i - 1]: skip\n    if candidates[i] > remain: stop\n    push; go(i + 1, remain - candidates[i], path); pop\ngo(0, target, [])",
    ],
    reference: `function combinationSum2(candidates, target) { const c = candidates.slice().sort((a, b) => a - b), out = [], p = []; const go = (s, r) => { if (r === 0) { out.push(p.slice()); return; } for (let i = s; i < c.length; i++) { if (i > s && c[i] === c[i - 1]) continue; if (c[i] > r) break; p.push(c[i]); go(i + 1, r - c[i]); p.pop(); } }; go(0, target); return out; }`,
    brute: `function combinationSum2(candidates, target) { const c = candidates.slice().sort((a, b) => a - b), seen = new Set(), out = []; for (let m = 0; m < 1 << c.length; m++) { let sum = 0; const s = []; for (let i = 0; i < c.length; i++) if (m & (1 << i)) { sum += c[i]; s.push(c[i]); } if (sum !== target) continue; const k = JSON.stringify(s); if (!seen.has(k)) { seen.add(k); out.push(s); } } return out; }`,
    fuzz: gen(`return [__arr(rand, __r(rand, 1, 10), 1, 8), __r(rand, 1, 15)];`),
    examples: [[[10, 1, 2, 7, 6, 1, 5], 8], [[2, 5, 2, 1, 2], 5]],
    edges: [
      ["no-answer", [[3, 5], 4]],
      ["duplicates", [[1, 1, 1, 1], 2], "Four 1s, but [1,1] appears once."],
      ["all-equal", [[2, 2, 2], 6]],
    ],
  },
  {
    slug: "combination-sum-iii",
    title: "Combination Sum III",
    difficulty: "Medium",
    pattern: "Backtracking",
    fn: "combinationSum3",
    params: [["k", "number"], ["n", "number"]],
    returns: "number[][]",
    compare: "unordered",
    hints: [
      "Only the digits 1..9 are allowed, each once. That's a tiny search space: pick digits in increasing order.",
      "Recurse with the next digit allowed, the remaining sum and how many digits are left. Prune when the digit exceeds the remaining sum.",
      "go(start, remain, path):\n  if size of path == k:\n    if remain == 0: add copy\n    return\n  for d from start to 9:\n    if d > remain: stop\n    push d; go(d + 1, remain - d, path); pop\ngo(1, n, [])",
    ],
    reference: `function combinationSum3(k, n) { const out = [], p = []; const go = (s, r) => { if (p.length === k) { if (r === 0) out.push(p.slice()); return; } for (let d = s; d <= 9 && d <= r; d++) { p.push(d); go(d + 1, r - d); p.pop(); } }; go(1, n); return out; }`,
    brute: `function combinationSum3(k, n) { const out = []; for (let m = 0; m < 512; m++) { const s = []; let sum = 0; for (let d = 1; d <= 9; d++) if (m & (1 << (d - 1))) { s.push(d); sum += d; } if (s.length === k && sum === n) out.push(s); } return out; }`,
    fuzz: gen(`return [__r(rand, 2, 5), __r(rand, 1, 30)];`),
    examples: [[3, 7], [3, 9]],
    edges: [
      ["no-answer", [4, 1]],
      ["boundary", [9, 45], "All nine digits."],
      ["extremes", [2, 17], "Only 8 + 9."],
    ],
  },
  {
    slug: "letter-combinations-of-a-phone-number",
    title: "Letter Combinations of a Phone Number",
    difficulty: "Medium",
    pattern: "Backtracking",
    fn: "letterCombinations",
    params: [["digits", "string"]],
    returns: "string[]",
    compare: "unordered",
    hints: [
      "Each digit maps to 3 or 4 letters. You need one letter per digit, in order: a tree with one level per digit.",
      "Recurse over digit positions, appending each letter of the current digit. An empty input has no combinations.",
      "if digits is empty: return []\ngo(i, cur):\n  if i == length: add cur; return\n  for each letter of keypad[digits[i]]:\n    go(i + 1, cur + letter)\ngo(0, \"\")",
    ],
    reference: `function letterCombinations(digits) { if (!digits) return []; const K = { 2: "abc", 3: "def", 4: "ghi", 5: "jkl", 6: "mno", 7: "pqrs", 8: "tuv", 9: "wxyz" }, out = []; const go = (i, cur) => { if (i === digits.length) { out.push(cur); return; } for (const ch of K[digits[i]]) go(i + 1, cur + ch); }; go(0, ""); return out; }`,
    brute: `function letterCombinations(digits) { if (!digits) return []; const K = ["", "", "abc", "def", "ghi", "jkl", "mno", "pqrs", "tuv", "wxyz"]; let acc = [""]; for (const d of digits) acc = acc.flatMap((p) => K[+d].split("").map((c) => p + c)); return acc; }`,
    fuzz: gen(`return [__str(rand, __r(rand, 0, 4), "23456789")];`),
    examples: [["23"], ["2"]],
    edges: [
      ["empty", [""], "No digits: an empty list, not [\"\"]."],
      ["boundary", ["79"], "Both keys have four letters."],
      ["duplicates", ["22"]],
    ],
  },
  {
    slug: "permutations",
    title: "Permutations",
    difficulty: "Medium",
    pattern: "Backtracking",
    fn: "permute",
    params: [["nums", "number[]"]],
    returns: "number[][]",
    compare: "unordered-outer",
    hints: [
      "Fill positions one at a time. Which values may go in the next position?",
      "Keep a used[] flag per index; at each level try every unused value, recurse, then unmark it (backtrack).",
      "go(path):\n  if size of path == n: add copy; return\n  for i from 0 to n - 1:\n    if not used[i]:\n      used[i] = true; push nums[i]\n      go(path)\n      pop; used[i] = false\ngo([])",
    ],
    reference: `function permute(nums) { const out = [], p = [], used = new Array(nums.length).fill(false); const go = () => { if (p.length === nums.length) { out.push(p.slice()); return; } for (let i = 0; i < nums.length; i++) if (!used[i]) { used[i] = true; p.push(nums[i]); go(); p.pop(); used[i] = false; } }; go(); return out; }`,
    brute: `function permute(nums) { let acc = [[]]; for (const x of nums) { const next = []; for (const p of acc) for (let i = 0; i <= p.length; i++) next.push([...p.slice(0, i), x, ...p.slice(i)]); acc = next; } return acc; }`,
    fuzz: gen(`return [__shuffle(rand, Array.from({ length: 11 }, (_, i) => i - 5)).slice(0, __r(rand, 1, 5))];`),
    examples: [[[1, 2, 3]], [[0, 1]]],
    edges: [
      ["single", [[1]]],
      ["two", [[5, 4]]],
      ["negatives", [[-1, 0, 2]]],
    ],
  },
  {
    slug: "permutations-ii",
    title: "Permutations II",
    difficulty: "Medium",
    pattern: "Backtracking",
    fn: "permuteUnique",
    params: [["nums", "number[]"]],
    returns: "number[][]",
    compare: "unordered-outer",
    hints: [
      "Equal values produce the same permutation twice. After sorting, when should you refuse to place a value?",
      "Sort, and at one level skip nums[i] if it equals nums[i - 1] and nums[i - 1] isn't currently used. That forces equal values to be placed in order.",
      "sort nums\ngo(path):\n  if size of path == n: add copy; return\n  for i from 0 to n - 1:\n    if used[i]: skip\n    if i > 0 and nums[i] == nums[i - 1] and not used[i - 1]: skip\n    mark i, push, go(path), pop, unmark i\ngo([])",
    ],
    reference: `function permuteUnique(nums) { const a = nums.slice().sort((x, y) => x - y), out = [], p = [], used = new Array(a.length).fill(false); const go = () => { if (p.length === a.length) { out.push(p.slice()); return; } for (let i = 0; i < a.length; i++) { if (used[i] || (i > 0 && a[i] === a[i - 1] && !used[i - 1])) continue; used[i] = true; p.push(a[i]); go(); p.pop(); used[i] = false; } }; go(); return out; }`,
    brute: `function permuteUnique(nums) { let acc = [[]]; for (const x of nums) { const next = []; for (const p of acc) for (let i = 0; i <= p.length; i++) next.push([...p.slice(0, i), x, ...p.slice(i)]); acc = next; } const seen = new Set(); return acc.filter((p) => { const k = JSON.stringify(p); if (seen.has(k)) return false; seen.add(k); return true; }); }`,
    fuzz: gen(`return [__arr(rand, __r(rand, 1, 6), 0, 3)];`),
    examples: [[[1, 1, 2]], [[1, 2, 3]]],
    edges: [
      ["all-equal", [[2, 2, 2]], "Only one distinct permutation."],
      ["duplicates", [[1, 1, 2, 2]]],
      ["single", [[0]]],
    ],
  },
  {
    slug: "beautiful-arrangement",
    title: "Beautiful Arrangement",
    difficulty: "Medium",
    pattern: "Backtracking",
    fn: "countArrangement",
    params: [["n", "number"]],
    returns: "number",
    hints: [
      "Trying all n! orders is too slow for n = 15. Can you reject a partial arrangement as soon as one position fails?",
      "Fill positions from n down to 1 (larger positions have fewer valid numbers). Place an unused number only if it divides the position or the position divides it.",
      "go(pos):\n  if pos == 0: return 1\n  total = 0\n  for x from 1 to n:\n    if not used[x] and (x mod pos == 0 or pos mod x == 0):\n      used[x] = true; total += go(pos - 1); used[x] = false\n  return total\nreturn go(n)",
    ],
    reference: `function countArrangement(n) { const used = new Array(n + 1).fill(false); const go = (pos) => { if (pos === 0) return 1; let t = 0; for (let x = 1; x <= n; x++) if (!used[x] && (x % pos === 0 || pos % x === 0)) { used[x] = true; t += go(pos - 1); used[x] = false; } return t; }; return go(n); }`,
    brute: `function countArrangement(n) { const dp = new Array(1 << n).fill(0); dp[0] = 1; for (let m = 0; m < 1 << n; m++) { if (!dp[m]) continue; let pos = 1; for (let b = m; b; b &= b - 1) pos++; for (let x = 1; x <= n; x++) if (!(m & (1 << (x - 1))) && (x % pos === 0 || pos % x === 0)) dp[m | (1 << (x - 1))] += dp[m]; } return dp[(1 << n) - 1]; }`,
    fuzz: gen(`return [__r(rand, 1, 12)];`),
    examples: [[2], [3]],
    edges: [
      ["min-size", [1]],
      ["extremes", [15], "The largest n: pruning is what keeps this fast."],
      ["boundary", [6]],
    ],
  },
  {
    slug: "the-k-th-lexicographical-string-of-all-happy-strings-of-length-n",
    title: "The k-th Lexicographical String of All Happy Strings of Length n",
    difficulty: "Medium",
    pattern: "Backtracking",
    fn: "getHappyString",
    params: [["n", "number"], ["k", "number"]],
    returns: "string",
    hints: [
      "Generating happy strings in order means trying 'a', 'b', 'c' at each position, skipping the previous letter.",
      "Backtrack in alphabetical order and count completed strings; return the kth. If fewer than k exist (there are 3 * 2^(n-1)), return \"\".",
      "count = 0\ngo(cur):\n  if length of cur == n:\n    count += 1\n    return cur if count == k else none\n  for ch in a, b, c:\n    if cur is empty or last of cur != ch:\n      r = go(cur + ch)\n      if r is not none: return r\n  return none\nreturn go(\"\") or \"\"",
    ],
    reference: `function getHappyString(n, k) { let c = 0; const go = (cur) => { if (cur.length === n) { c++; return c === k ? cur : null; } for (const ch of "abc") if (!cur || cur[cur.length - 1] !== ch) { const r = go(cur + ch); if (r !== null) return r; } return null; }; return go("") ?? ""; }`,
    brute: `function getHappyString(n, k) { let all = ["a", "b", "c"]; for (let i = 1; i < n; i++) all = all.flatMap((s) => "abc".split("").filter((c) => c !== s[s.length - 1]).map((c) => s + c)); all.sort(); return all[k - 1] ?? ""; }`,
    fuzz: gen(`return [__r(rand, 1, 10), __r(rand, 1, 100)];`),
    examples: [[1, 3], [3, 9]],
    edges: [
      ["no-answer", [1, 4], "Only 3 happy strings of length 1."],
      ["boundary", [3, 12], "The very last happy string of length 3."],
      ["extremes", [10, 100]],
    ],
  },
  {
    slug: "letter-tile-possibilities",
    title: "Letter Tile Possibilities",
    difficulty: "Medium",
    pattern: "Backtracking",
    fn: "numTilePossibilities",
    params: [["tiles", "string"]],
    returns: "number",
    hints: [
      "Equal tiles are interchangeable, so think in counts per letter rather than per tile.",
      "Recurse on the letter counts: for every letter with count > 0, use it (that's one new sequence), recurse, then put it back.",
      "count = letter counts of tiles\ngo():\n  total = 0\n  for each letter with count > 0:\n    count[letter] -= 1\n    total += 1 + go()\n    count[letter] += 1\n  return total\nreturn go()",
    ],
    reference: `function numTilePossibilities(tiles) { const cnt = new Array(26).fill(0); for (const c of tiles) cnt[c.charCodeAt(0) - 65]++; const go = () => { let t = 0; for (let i = 0; i < 26; i++) if (cnt[i]) { cnt[i]--; t += 1 + go(); cnt[i]++; } return t; }; return go(); }`,
    brute: `function numTilePossibilities(tiles) { const seen = new Set(), used = new Array(tiles.length).fill(false); const go = (cur) => { for (let i = 0; i < tiles.length; i++) if (!used[i]) { used[i] = true; seen.add(cur + tiles[i]); go(cur + tiles[i]); used[i] = false; } }; go(""); return seen.size; }`,
    fuzz: gen(`return [__str(rand, __r(rand, 1, 6), "ABC")];`),
    examples: [["AAB"], ["AAABBC"]],
    edges: [
      ["single-char", ["V"]],
      ["all-equal", ["AAAA"], "Only the length varies: 4 sequences."],
      ["boundary", ["ABCDEFG"], "Seven distinct tiles: 13699 sequences."],
    ],
  },
  {
    slug: "palindrome-partitioning",
    title: "Palindrome Partitioning",
    difficulty: "Medium",
    pattern: "Backtracking",
    fn: "partition",
    params: [["s", "string"]],
    returns: "string[][]",
    compare: "unordered-outer",
    hints: [
      "Pick the first piece: it must be a palindrome. What's left is the same problem on a shorter string.",
      "Recurse with a start index; for every end where s[start..end] is a palindrome, push it, recurse from end + 1, pop.",
      "go(start, path):\n  if start == n: add copy of path; return\n  for end from start to n - 1:\n    if s[start..end] is a palindrome:\n      push s[start..end]\n      go(end + 1, path)\n      pop\ngo(0, [])",
    ],
    reference: `function partition(s) { const out = [], p = []; const pal = (i, j) => { while (i < j) if (s[i++] !== s[j--]) return false; return true; }; const go = (st) => { if (st === s.length) { out.push(p.slice()); return; } for (let e = st; e < s.length; e++) if (pal(st, e)) { p.push(s.slice(st, e + 1)); go(e + 1); p.pop(); } }; go(0); return out; }`,
    brute: `function partition(s) { const out = [], n = s.length; for (let m = 0; m < 1 << (n - 1); m++) { const parts = []; let st = 0; for (let i = 0; i < n; i++) if (i === n - 1 || m & (1 << i)) { parts.push(s.slice(st, i + 1)); st = i + 1; } if (parts.every((x) => x === x.split("").reverse().join(""))) out.push(parts); } return out; }`,
    fuzz: gen(`return [__str(rand, __r(rand, 1, 8), "ab")];`),
    examples: [["aab"], ["a"]],
    edges: [
      ["all-equal", ["aaaa"], "Every split is a palindrome: 8 partitions."],
      ["boundary", ["abc"], "Only single letters work."],
      ["two", ["bb"]],
    ],
  },
  {
    slug: "restore-ip-addresses",
    title: "Restore IP Addresses",
    difficulty: "Medium",
    pattern: "Backtracking",
    fn: "restoreIpAddresses",
    params: [["s", "string"]],
    returns: "string[]",
    compare: "unordered",
    hints: [
      "An address is exactly four parts of 1 to 3 digits. Each part must be <= 255 and can't have a leading zero (except \"0\" itself).",
      "Recurse over parts: try lengths 1, 2, 3 for the next part, keep it only if valid, and accept when four parts use the whole string.",
      "go(start, parts):\n  if size of parts == 4:\n    if start == n: add parts joined by \".\"\n    return\n  for len from 1 to 3:\n    piece = s[start .. start + len - 1]\n    if piece fits and (len == 1 or piece[0] != '0') and value <= 255:\n      go(start + len, parts + [piece])\ngo(0, [])",
    ],
    reference: `function restoreIpAddresses(s) { const out = []; const go = (st, parts) => { if (parts.length === 4) { if (st === s.length) out.push(parts.join(".")); return; } for (let len = 1; len <= 3 && st + len <= s.length; len++) { const p = s.slice(st, st + len); if ((len > 1 && p[0] === "0") || +p > 255) continue; go(st + len, [...parts, p]); } }; go(0, []); return out; }`,
    brute: `function restoreIpAddresses(s) { const out = [], ok = (p) => p.length > 0 && p.length <= 3 && (p === "0" || p[0] !== "0") && +p <= 255; for (let a = 1; a < s.length; a++) for (let b = a + 1; b < s.length; b++) for (let c = b + 1; c < s.length; c++) { const ps = [s.slice(0, a), s.slice(a, b), s.slice(b, c), s.slice(c)]; if (ps.every(ok)) out.push(ps.join(".")); } return out; }`,
    fuzz: gen(`return [__str(rand, __r(rand, 4, 12), "01259")];`),
    examples: [["25525511135"], ["0000"]],
    edges: [
      ["no-answer", ["1111111111111"], "13 digits can't fit in four parts of at most 3."],
      ["zeros", ["010010"], "Leading zeros are never allowed."],
      ["min-size", ["1111"]],
    ],
  },
  {
    slug: "split-a-string-into-the-max-number-of-unique-substrings",
    title: "Split a String Into the Max Number of Unique Substrings",
    difficulty: "Medium",
    pattern: "Backtracking",
    fn: "maxUniqueSplit",
    params: [["s", "string"]],
    returns: "number",
    hints: [
      "Choose the first piece, then split the rest, while remembering which pieces are already taken.",
      "Backtrack with a Set of used pieces: for each prefix not in the set, add it, recurse on the rest, remove it. Track the best count.",
      "go(start, used):\n  if start == n: return 0\n  best = minus infinity\n  for end from start to n - 1:\n    piece = s[start..end]\n    if piece not in used:\n      add piece; best = max(best, 1 + go(end + 1, used)); remove piece\n  return best\nreturn go(0, empty set)",
    ],
    reference: `function maxUniqueSplit(s) { const used = new Set(); const go = (st) => { if (st === s.length) return 0; let best = -Infinity; for (let e = st + 1; e <= s.length; e++) { const p = s.slice(st, e); if (used.has(p)) continue; used.add(p); best = Math.max(best, 1 + go(e)); used.delete(p); } return best; }; return go(0); }`,
    brute: `function maxUniqueSplit(s) { const n = s.length; let best = 1; for (let m = 0; m < 1 << (n - 1); m++) { const parts = []; let st = 0; for (let i = 0; i < n; i++) if (i === n - 1 || m & (1 << i)) { parts.push(s.slice(st, i + 1)); st = i + 1; } if (new Set(parts).size === parts.length) best = Math.max(best, parts.length); } return best; }`,
    fuzz: gen(`return [__str(rand, __r(rand, 1, 12), "abc")];`),
    examples: [["ababccc"], ["aba"]],
    edges: [
      ["all-equal", ["aa"], "Can't split into \"a\" and \"a\": 1."],
      ["single-char", ["z"]],
      ["boundary", ["wwwzfvedwfvhsww"]],
    ],
  },
  {
    slug: "maximum-length-of-a-concatenated-string-with-unique-characters",
    title: "Maximum Length of a Concatenated String with Unique Characters",
    difficulty: "Medium",
    pattern: "Backtracking",
    fn: "maxLength",
    params: [["arr", "string[]"]],
    returns: "number",
    hints: [
      "Each string is either in or out. A string with a repeated letter can never be used. How do you check overlap fast?",
      "Turn each usable string into a 26-bit mask. Backtrack over the strings, taking one only if its mask doesn't overlap the current mask.",
      "masks = bitmask of each string with no repeated letters\ngo(i, cur):\n  if i == size of masks: return popcount(cur)\n  best = go(i + 1, cur)\n  if masks[i] and cur share no bit:\n    best = max(best, go(i + 1, cur or masks[i]))\n  return best\nreturn go(0, 0)",
    ],
    reference: `function maxLength(arr) { const ms = []; for (const w of arr) { let m = 0, ok = true; for (const c of w) { const b = 1 << (c.charCodeAt(0) - 97); if (m & b) { ok = false; break; } m |= b; } if (ok) ms.push(m); } const pc = (x) => { let c = 0; while (x) { x &= x - 1; c++; } return c; }; const go = (i, cur) => { if (i === ms.length) return pc(cur); let best = go(i + 1, cur); if (!(ms[i] & cur)) best = Math.max(best, go(i + 1, cur | ms[i])); return best; }; return go(0, 0); }`,
    brute: `function maxLength(arr) { let best = 0; for (let m = 0; m < 1 << arr.length; m++) { let s = ""; for (let i = 0; i < arr.length; i++) if (m & (1 << i)) s += arr[i]; if (new Set(s).size === s.length) best = Math.max(best, s.length); } return best; }`,
    fuzz: gen(`return [Array.from({ length: __r(rand, 1, 10) }, () => __str(rand, __r(rand, 1, 4), "abcdefgh"))];`),
    examples: [[["un", "iq", "ue"]], [["cha", "r", "act", "ers"]]],
    edges: [
      ["single", [["abcdefghijklmnopqrstuvwxyz"]]],
      ["duplicates", [["aa", "bb"]], "Each string repeats a letter itself, so nothing can be used: 0."],
      ["boundary", [["ab", "ba", "cd"]]],
    ],
  },
  {
    slug: "partition-to-k-equal-sum-subsets",
    title: "Partition to K Equal Sum Subsets",
    difficulty: "Medium",
    pattern: "Backtracking",
    fn: "canPartitionKSubsets",
    params: [["nums", "number[]"], ["k", "number"]],
    returns: "boolean",
    hints: [
      "The total must divide by k, and no number may exceed total / k. After that, it's filling k buckets.",
      "Sort descending and place each number into a bucket that still has room; backtrack on failure. Skip buckets with the same current sum to avoid repeating work.",
      "if total mod k != 0: return false\ntarget = total / k; sort nums descending\ngo(i):\n  if i == n: return true\n  for each bucket b:\n    if bucket[b] + nums[i] <= target and bucket[b] not tried at this level:\n      bucket[b] += nums[i]\n      if go(i + 1): return true\n      bucket[b] -= nums[i]\n  return false\nreturn go(0)",
    ],
    reference: `function canPartitionKSubsets(nums, k) { const total = nums.reduce((a, b) => a + b, 0); if (total % k) return false; const t = total / k, a = nums.slice().sort((x, y) => y - x); if (a[0] > t) return false; const b = new Array(k).fill(0); const go = (i) => { if (i === a.length) return true; const tried = new Set(); for (let j = 0; j < k; j++) { if (b[j] + a[i] > t || tried.has(b[j])) continue; tried.add(b[j]); b[j] += a[i]; if (go(i + 1)) return true; b[j] -= a[i]; } return false; }; return go(0); }`,
    brute: `function canPartitionKSubsets(nums, k) { const total = nums.reduce((a, b) => a + b, 0); if (total % k) return false; const t = total / k, n = nums.length, dp = new Array(1 << n).fill(-1); dp[0] = 0; for (let m = 0; m < 1 << n; m++) { if (dp[m] < 0) continue; for (let i = 0; i < n; i++) if (!(m & (1 << i)) && dp[m] + nums[i] <= t) dp[m | (1 << i)] = (dp[m] + nums[i]) % t; } return dp[(1 << n) - 1] === 0; }`,
    fuzz: gen(`${GROUPS} const k = __r(rand, 1, 4); const nums = rand() < 0.5 ? __groups(rand, k, 3, 9).slice(0, 12) : __arr(rand, __r(rand, 1, 10), 1, 8); return [nums, Math.min(k, nums.length)];`),
    examples: [[[4, 3, 2, 3, 5, 2, 1], 4], [[1, 2, 3, 4], 3]],
    edges: [
      ["single", [[5], 1]],
      ["no-answer", [[2, 2, 2, 2, 3, 4, 5], 4], "The total divides by 4, but no split works."],
      ["all-equal", [[3, 3, 3, 3], 4]],
    ],
  },
  {
    slug: "matchsticks-to-square",
    title: "Matchsticks to Square",
    difficulty: "Medium",
    pattern: "Backtracking",
    fn: "makesquare",
    params: [["matchsticks", "number[]"]],
    returns: "boolean",
    hints: [
      "This is partition into 4 equal-sum subsets: each side has length total / 4.",
      "Check total % 4 and the longest stick first. Sort descending and place each stick on a side that still has room, backtracking on failure.",
      "if total mod 4 != 0: return false\nside = total / 4; sort sticks descending\ngo(i):\n  if i == n: return true\n  for each of the 4 sides:\n    if sides[s] + sticks[i] <= side:\n      sides[s] += sticks[i]\n      if go(i + 1): return true\n      sides[s] -= sticks[i]\n    if sides[s] == 0: stop\n  return false",
    ],
    reference: `function makesquare(matchsticks) { const total = matchsticks.reduce((a, b) => a + b, 0); if (matchsticks.length < 4 || total % 4) return false; const t = total / 4, a = matchsticks.slice().sort((x, y) => y - x); if (a[0] > t) return false; const s = [0, 0, 0, 0]; const go = (i) => { if (i === a.length) return true; for (let j = 0; j < 4; j++) { if (s[j] + a[i] <= t) { s[j] += a[i]; if (go(i + 1)) return true; s[j] -= a[i]; } if (s[j] === 0) break; } return false; }; return go(0); }`,
    brute: `function makesquare(matchsticks) { const total = matchsticks.reduce((a, b) => a + b, 0); if (total % 4 || matchsticks.length < 4) return false; const t = total / 4, n = matchsticks.length, dp = new Array(1 << n).fill(-1); dp[0] = 0; for (let m = 0; m < 1 << n; m++) { if (dp[m] < 0) continue; for (let i = 0; i < n; i++) if (!(m & (1 << i)) && dp[m] + matchsticks[i] <= t) dp[m | (1 << i)] = (dp[m] + matchsticks[i]) % t; } return dp[(1 << n) - 1] === 0; }`,
    fuzz: gen(`${GROUPS} return [rand() < 0.5 ? __groups(rand, 4, 2, 8).slice(0, 12) : __arr(rand, __r(rand, 1, 10), 1, 6)];`),
    examples: [[[1, 1, 2, 2, 2]], [[3, 3, 3, 3, 4]]],
    edges: [
      ["min-size", [[1, 1, 1, 1]]],
      ["two", [[1, 1]], "Fewer than four sticks can't make four sides."],
      ["boundary", [[5, 5, 5, 5, 4, 4, 4, 4, 3, 3, 3, 3]], "Each side is 5 + 4 + 3."],
      ["all-equal", [[2, 2, 2, 2, 2, 2]], "Sides of 3 can't be built from 2s."],
    ],
  },
  {
    slug: "word-search",
    title: "Word Search",
    difficulty: "Medium",
    pattern: "Backtracking",
    fn: "exist",
    params: [["board", "character[][]"], ["word", "string"]],
    returns: "boolean",
    hints: [
      "Start from every cell that matches word[0]. From there, the next letter must be in a neighbouring cell you haven't used yet.",
      "DFS (r, c, i): fail if out of bounds or board[r][c] != word[i]; succeed when i is the last index. Mark the cell used while exploring, unmark on return.",
      "dfs(r, c, i):\n  if outside or board[r][c] != word[i]: return false\n  if i == length - 1: return true\n  mark (r, c) used\n  found = dfs on the 4 neighbours with i + 1\n  unmark (r, c)\n  return found\nreturn true if dfs(r, c, 0) for any cell",
    ],
    reference: `function exist(board, word) { const R = board.length, C = board[0].length; const dfs = (r, c, i) => { if (r < 0 || c < 0 || r >= R || c >= C || board[r][c] !== word[i]) return false; if (i === word.length - 1) return true; const t = board[r][c]; board[r][c] = "#"; const ok = dfs(r + 1, c, i + 1) || dfs(r - 1, c, i + 1) || dfs(r, c + 1, i + 1) || dfs(r, c - 1, i + 1); board[r][c] = t; return ok; }; for (let r = 0; r < R; r++) for (let c = 0; c < C; c++) if (dfs(r, c, 0)) return true; return false; }`,
    brute: `function exist(board, word) { const R = board.length, C = board[0].length; const stack = []; for (let r = 0; r < R; r++) for (let c = 0; c < C; c++) if (board[r][c] === word[0]) stack.push([r, c, 1, [r * C + c]]); while (stack.length) { const [r, c, i, path] = stack.pop(); if (i === word.length) return true; for (const [dr, dc] of [[1, 0], [-1, 0], [0, 1], [0, -1]]) { const nr = r + dr, nc = c + dc; if (nr < 0 || nc < 0 || nr >= R || nc >= C || board[nr][nc] !== word[i] || path.includes(nr * C + nc)) continue; stack.push([nr, nc, i + 1, path.concat(nr * C + nc)]); } } return false; }`,
    fuzz: gen(`const R = __r(rand, 1, 4), C = __r(rand, 1, 4); return [Array.from({ length: R }, () => __str(rand, C, "ab").split("")), __str(rand, __r(rand, 1, 6), "ab")];`),
    examples: [[WORD_BOARD, "ABCCED"], [WORD_BOARD, "ABCB"]],
    edges: [
      ["single", [[["a"]], "a"]],
      ["reuse", [[["a", "a"]], "aaa"], "A cell can't be used twice."],
      ["boundary", [[["a", "b"], ["c", "d"]], "abdc"], "The path turns corners."],
      ["no-answer", [[["a", "b"], ["c", "d"]], "abcd"]],
    ],
  },
  {
    slug: "path-with-maximum-gold",
    title: "Path with Maximum Gold",
    difficulty: "Medium",
    pattern: "Backtracking",
    fn: "getMaximumGold",
    params: [["grid", "number[][]"]],
    returns: "number",
    hints: [
      "There are at most 25 gold cells. Try starting from each one and explore every simple path.",
      "DFS from a gold cell: collect it, mark it empty, try the four neighbours, then restore it. Keep the best total.",
      "dfs(r, c):\n  if outside or grid[r][c] == 0: return 0\n  g = grid[r][c]; grid[r][c] = 0\n  best = max of dfs over the 4 neighbours\n  grid[r][c] = g\n  return g + best\nreturn max of dfs(r, c) over all cells",
    ],
    reference: `function getMaximumGold(grid) { const R = grid.length, C = grid[0].length; const dfs = (r, c) => { if (r < 0 || c < 0 || r >= R || c >= C || !grid[r][c]) return 0; const g = grid[r][c]; grid[r][c] = 0; const b = Math.max(dfs(r + 1, c), dfs(r - 1, c), dfs(r, c + 1), dfs(r, c - 1)); grid[r][c] = g; return g + b; }; let best = 0; for (let r = 0; r < R; r++) for (let c = 0; c < C; c++) best = Math.max(best, dfs(r, c)); return best; }`,
    brute: `function getMaximumGold(grid) { const R = grid.length, C = grid[0].length; let best = 0; const stack = []; for (let r = 0; r < R; r++) for (let c = 0; c < C; c++) if (grid[r][c]) stack.push([r, c, grid[r][c], [r * C + c]]); while (stack.length) { const [r, c, sum, path] = stack.pop(); best = Math.max(best, sum); for (const [dr, dc] of [[1, 0], [-1, 0], [0, 1], [0, -1]]) { const nr = r + dr, nc = c + dc; if (nr < 0 || nc < 0 || nr >= R || nc >= C || !grid[nr][nc] || path.includes(nr * C + nc)) continue; stack.push([nr, nc, sum + grid[nr][nc], path.concat(nr * C + nc)]); } } return best; }`,
    fuzz: gen(`const R = __r(rand, 1, 4), C = __r(rand, 1, 4); return [Array.from({ length: R }, () => Array.from({ length: C }, () => (rand() < 0.3 ? 0 : __r(rand, 1, 9))))];`),
    examples: [[[[0, 6, 0], [5, 8, 7], [0, 9, 0]]], [[[1, 0, 7], [2, 0, 6], [3, 4, 5], [0, 3, 0], [9, 0, 20]]]],
    edges: [
      ["zeros", [[[0, 0], [0, 0]]], "No gold at all: 0."],
      ["single", [[[5]]]],
      ["boundary", [[[1, 1, 1], [1, 1, 1], [1, 1, 1]]], "A snake path collects every cell."],
    ],
  },
  {
    slug: "n-queens",
    title: "N-Queens",
    difficulty: "Hard",
    pattern: "Backtracking",
    fn: "solveNQueens",
    params: [["n", "number"]],
    returns: "string[][]",
    compare: "unordered-outer",
    hints: [
      "Exactly one queen per row. Place them row by row; what makes a column choice illegal?",
      "Track used columns and both diagonals (r - c and r + c). In row r, try every free column, recurse to r + 1, then undo.",
      "go(r):\n  if r == n: add the board; return\n  for c from 0 to n - 1:\n    if c, r - c and r + c are all free:\n      place queen at (r, c), mark all three\n      go(r + 1)\n      remove queen, unmark\ngo(0)",
    ],
    reference: `function solveNQueens(n) { const out = [], cols = new Set(), d1 = new Set(), d2 = new Set(), pos = []; const go = (r) => { if (r === n) { out.push(pos.map((c) => ".".repeat(c) + "Q" + ".".repeat(n - c - 1))); return; } for (let c = 0; c < n; c++) { if (cols.has(c) || d1.has(r - c) || d2.has(r + c)) continue; cols.add(c); d1.add(r - c); d2.add(r + c); pos.push(c); go(r + 1); pos.pop(); cols.delete(c); d1.delete(r - c); d2.delete(r + c); } }; go(0); return out; }`,
    brute: `function solveNQueens(n) { const out = []; let acc = [[]]; for (let i = 0; i < n; i++) { const next = []; for (const p of acc) for (let c = 0; c < n; c++) if (!p.includes(c)) next.push(p.concat(c)); acc = next; } for (const p of acc) { let ok = true; for (let i = 0; i < n && ok; i++) for (let j = i + 1; j < n; j++) if (Math.abs(p[i] - p[j]) === j - i) { ok = false; break; } if (ok) out.push(p.map((c) => ".".repeat(c) + "Q" + ".".repeat(n - c - 1))); } return out; }`,
    fuzz: gen(`return [__r(rand, 1, 8)];`),
    examples: [[4], [1]],
    edges: [
      ["no-answer", [2], "No placement exists: an empty list."],
      ["boundary", [3]],
      ["large", [8], "92 boards."],
    ],
  },
  {
    slug: "n-queens-ii",
    title: "N-Queens II",
    difficulty: "Hard",
    pattern: "Backtracking",
    fn: "totalNQueens",
    params: [["n", "number"]],
    returns: "number",
    hints: [
      "Same search as N-Queens, but you only need to count complete placements.",
      "Row by row, with sets (or bitmasks) for used columns and the two diagonal directions; count when r reaches n.",
      "go(r):\n  if r == n: return 1\n  total = 0\n  for c from 0 to n - 1:\n    if c, r - c and r + c are all free:\n      mark them; total += go(r + 1); unmark\n  return total\nreturn go(0)",
    ],
    reference: `function totalNQueens(n) { const all = (1 << n) - 1; const go = (cols, d1, d2) => { if (cols === all) return 1; let t = 0, free = all & ~(cols | d1 | d2); while (free) { const b = free & -free; free -= b; t += go(cols | b, ((d1 | b) << 1) & all, (d2 | b) >> 1); } return t; }; return go(0, 0, 0); }`,
    brute: `function totalNQueens(n) { let count = 0; const p = []; const go = (r) => { if (r === n) { count++; return; } for (let c = 0; c < n; c++) { let ok = true; for (let i = 0; i < r; i++) if (p[i] === c || Math.abs(p[i] - c) === r - i) { ok = false; break; } if (ok) { p[r] = c; go(r + 1); } } }; go(0); return count; }`,
    fuzz: gen(`return [__r(rand, 1, 9)];`),
    examples: [[4], [1]],
    edges: [
      ["no-answer", [3], "No placement: 0."],
      ["boundary", [2]],
      ["large", [9], "352 placements."],
    ],
  },
  {
    slug: "sudoku-solver",
    title: "Sudoku Solver",
    difficulty: "Hard",
    pattern: "Backtracking",
    fn: "solveSudoku",
    params: [["board", "character[][]"]],
    returns: "void",
    returnKind: "arg0",
    hints: [
      "Fill one empty cell at a time with a digit that doesn't clash with its row, column or 3x3 box. When nothing fits, undo the last choice.",
      "Keep three sets of used digits (rows, columns, boxes) so each check is O(1). Recurse to the next empty cell; on failure clear the cell and try the next digit.",
      "solve(i):\n  move i to the next empty cell; if none left: return true\n  for d from 1 to 9:\n    if d is free in row, column and box of cell i:\n      place d and mark it\n      if solve(i + 1): return true\n      clear the cell and unmark d\n  return false\nsolve(0)",
    ],
    reference: `function solveSudoku(board) { const rows = Array.from({ length: 9 }, () => new Set()), cols = Array.from({ length: 9 }, () => new Set()), boxes = Array.from({ length: 9 }, () => new Set()), empty = []; for (let r = 0; r < 9; r++) for (let c = 0; c < 9; c++) { const v = board[r][c]; if (v === ".") empty.push([r, c]); else { rows[r].add(v); cols[c].add(v); boxes[3 * Math.floor(r / 3) + Math.floor(c / 3)].add(v); } } const go = (i) => { if (i === empty.length) return true; const [r, c] = empty[i], b = 3 * Math.floor(r / 3) + Math.floor(c / 3); for (let d = 1; d <= 9; d++) { const v = String(d); if (rows[r].has(v) || cols[c].has(v) || boxes[b].has(v)) continue; board[r][c] = v; rows[r].add(v); cols[c].add(v); boxes[b].add(v); if (go(i + 1)) return true; board[r][c] = "."; rows[r].delete(v); cols[c].delete(v); boxes[b].delete(v); } return false; }; go(0); }`,
    brute: `function solveSudoku(board) { const ok = (r, c, v) => { for (let k = 0; k < 9; k++) { if (board[r][k] === v || board[k][c] === v) return false; if (board[3 * Math.floor(r / 3) + Math.floor(k / 3)][3 * Math.floor(c / 3) + (k % 3)] === v) return false; } return true; }; const go = () => { let best = null, bestOpts = null; for (let r = 0; r < 9; r++) for (let c = 0; c < 9; c++) if (board[r][c] === ".") { const opts = []; for (let d = 1; d <= 9; d++) if (ok(r, c, String(d))) opts.push(String(d)); if (!best || opts.length < bestOpts.length) { best = [r, c]; bestOpts = opts; } } if (!best) return true; for (const v of bestOpts) { board[best[0]][best[1]] = v; if (go()) return true; } board[best[0]][best[1]] = "."; return false; }; go(); }`,
    fuzz: gen(`${SUDOKU} return [__sudokuPuzzle(rand, __r(rand, 30, 50), false)];`),
    fuzzHidden: 4,
    examples: [[LC_SUDOKU], sudoku(11, 40)],
    edges: [
      ["single", sudoku(12, 1), "Only one empty cell."],
      ["boundary", sudoku(13, 0, true), "A whole row is empty; each cell follows from its column."],
      ["extremes", sudoku(14, 56), "As many blanks as a unique solution allows."],
    ],
  },
  {
    slug: "permutation-sequence",
    title: "Permutation Sequence",
    difficulty: "Hard",
    pattern: "Recursion",
    fn: "getPermutation",
    params: [["n", "number"], ["k", "number"]],
    returns: "string",
    hints: [
      "Listing k permutations is too slow. How many permutations start with each possible first digit?",
      "(n - 1)! permutations share each first digit, so the first digit is the ((k - 1) div (n - 1)!)th remaining digit. Repeat with the remainder.",
      "digits = [1..n], k = k - 1, result = \"\"\nfor i from n down to 1:\n  f = (i - 1)!\n  idx = k div f\n  append digits[idx] to result and remove it\n  k = k mod f\nreturn result",
    ],
    reference: `function getPermutation(n, k) { const d = Array.from({ length: n }, (_, i) => i + 1), f = [1]; for (let i = 1; i <= n; i++) f[i] = f[i - 1] * i; let r = "", K = k - 1; for (let i = n; i >= 1; i--) { const idx = Math.floor(K / f[i - 1]); r += d.splice(idx, 1)[0]; K %= f[i - 1]; } return r; }`,
    brute: `function getPermutation(n, k) { const a = Array.from({ length: n }, (_, i) => i + 1); for (let s = 1; s < k; s++) { let i = n - 2; while (a[i] > a[i + 1]) i--; let j = n - 1; while (a[j] < a[i]) j--; [a[i], a[j]] = [a[j], a[i]]; a.splice(i + 1, n, ...a.slice(i + 1).reverse()); } return a.join(""); }`,
    fuzz: gen(`const n = __r(rand, 1, 8); let f = 1; for (let i = 2; i <= n; i++) f *= i; return [n, __r(rand, 1, f)];`),
    examples: [[3, 3], [4, 9]],
    edges: [
      ["min-size", [1, 1]],
      ["boundary", [3, 6], "k = n!: the last permutation, digits in reverse."],
      ["extremes", [9, 362880]],
    ],
  },
  {
    slug: "expression-add-operators",
    title: "Expression Add Operators",
    difficulty: "Hard",
    pattern: "Backtracking",
    fn: "addOperators",
    params: [["num", "string"], ["target", "number"]],
    returns: "string[]",
    compare: "unordered",
    hints: [
      "Between digits you may put +, -, *, or nothing (joining digits). Multiplication binds tighter: how do you undo the last term when you see a '*'?",
      "Recurse with the running value and the last term. For '*', value becomes value - last + last * cur and last becomes last * cur. Skip numbers with a leading zero.",
      "go(i, expr, value, last):\n  if i == n: if value == target: add expr; return\n  for j from i to n - 1:\n    if j > i and num[i] == '0': stop\n    cur = number num[i..j]\n    if i == 0: go(j + 1, cur, cur, cur)\n    else:\n      go(j + 1, expr + \"+\" + cur, value + cur, cur)\n      go(j + 1, expr + \"-\" + cur, value - cur, -cur)\n      go(j + 1, expr + \"*\" + cur, value - last + last * cur, last * cur)\ngo(0, \"\", 0, 0)",
    ],
    reference: `function addOperators(num, target) { const out = []; const go = (i, e, v, last) => { if (i === num.length) { if (v === target) out.push(e); return; } for (let j = i; j < num.length; j++) { if (j > i && num[i] === "0") break; const s = num.slice(i, j + 1), c = +s; if (i === 0) go(j + 1, s, c, c); else { go(j + 1, e + "+" + s, v + c, c); go(j + 1, e + "-" + s, v - c, -c); go(j + 1, e + "*" + s, v - last + last * c, last * c); } } }; go(0, "", 0, 0); return out; }`,
    brute: `function addOperators(num, target) { const n = num.length, out = [], ops = ["", "+", "-", "*"]; const total = Math.pow(4, n - 1); for (let m = 0; m < total; m++) { let e = num[0], x = m; for (let i = 1; i < n; i++) { e += ops[x % 4] + num[i]; x = Math.floor(x / 4); } const toks = e.split(/([+\\-*])/); if (toks.some((t, i) => i % 2 === 0 && t.length > 1 && t[0] === "0")) continue; let sum = 0, term = +toks[0], sign = 1; for (let i = 1; i < toks.length; i += 2) { const op = toks[i], v = +toks[i + 1]; if (op === "*") term *= v; else { sum += sign * term; sign = op === "+" ? 1 : -1; term = v; } } sum += sign * term; if (sum === target) out.push(e); } return out; }`,
    fuzz: gen(`return [__str(rand, __r(rand, 1, 6), "0123"), __r(rand, -10, 20)];`),
    examples: [["123", 6], ["232", 8]],
    edges: [
      ["zeros", ["105", 5], "\"05\" is not a valid number, but 1*0+5 and 10-5 are."],
      ["no-answer", ["3456237490", 9191]],
      ["boundary", ["00", 0], "Three ways, never \"00\"."],
    ],
  },
  {
    slug: "word-break-ii",
    title: "Word Break II",
    difficulty: "Hard",
    pattern: "Backtracking",
    fn: "wordBreak",
    params: [["s", "string"], ["wordDict", "string[]"]],
    returns: "string[]",
    compare: "unordered",
    hints: [
      "Pick a dictionary word that is a prefix of s, then break the rest the same way. The same suffix can be reached many times.",
      "Recurse on the start index and memoise the list of sentences for each suffix. Combine each matching word with every sentence of the remaining suffix.",
      "go(start):\n  if start == n: return [\"\"]\n  if start in memo: return memo[start]\n  result = []\n  for each word in dict that s starts with at start:\n    for each rest in go(start + length of word):\n      add word (plus \" \" + rest if rest is not empty) to result\n  memo[start] = result\n  return result\nreturn go(0)",
    ],
    reference: `function wordBreak(s, wordDict) { const memo = new Map(); const go = (st) => { if (st === s.length) return [""]; if (memo.has(st)) return memo.get(st); const res = []; for (const w of wordDict) if (s.startsWith(w, st)) for (const rest of go(st + w.length)) res.push(rest ? w + " " + rest : w); memo.set(st, res); return res; }; return go(0); }`,
    brute: `function wordBreak(s, wordDict) { const dict = new Set(wordDict), n = s.length, out = []; for (let m = 0; m < 1 << (n - 1); m++) { const parts = []; let st = 0; for (let i = 0; i < n; i++) if (i === n - 1 || m & (1 << i)) { parts.push(s.slice(st, i + 1)); st = i + 1; } if (parts.every((p) => dict.has(p))) out.push(parts.join(" ")); } return out; }`,
    fuzz: gen(`const words = new Set(); const k = __r(rand, 2, 4); while (words.size < k) words.add(__str(rand, __r(rand, 1, 3), "ab")); return [__str(rand, __r(rand, 1, 10), "ab"), [...words]];`),
    examples: [["catsanddog", ["cat", "cats", "and", "sand", "dog"]], ["pineapplepenapple", ["apple", "pen", "applepen", "pine", "pineapple"]]],
    edges: [
      ["no-answer", ["catsandog", ["cats", "dog", "sand", "and", "cat"]]],
      ["reuse", ["aaaa", ["a", "aa"]], "Words can be reused: 5 sentences."],
      ["single", ["a", ["a"]]],
    ],
  },
  {
    slug: "remove-invalid-parentheses",
    title: "Remove Invalid Parentheses",
    difficulty: "Hard",
    pattern: "Backtracking",
    fn: "removeInvalidParentheses",
    params: [["s", "string"]],
    returns: "string[]",
    compare: "unordered",
    hints: [
      "One scan tells you exactly how many '(' and how many ')' must go. Then you only need to choose which ones.",
      "Count the extra left and right parentheses. Backtrack over the string, optionally deleting a '(' or ')' while that budget lasts (skip equal neighbours to avoid duplicates), and keep strings that end up valid.",
      "count extra L and R by one scan\ngo(i, L, R, open, cur):\n  if i == n: if L == R == 0 and open == 0: add cur; return\n  ch = s[i]\n  if ch == '(' and L > 0: go(i + 1, L - 1, R, open, cur)\n  if ch == ')' and R > 0: go(i + 1, L, R - 1, open, cur)\n  if ch == '(': go(i + 1, L, R, open + 1, cur + ch)\n  else if ch == ')': if open > 0: go(i + 1, L, R, open - 1, cur + ch)\n  else: go(i + 1, L, R, open, cur + ch)\nreturn the distinct results",
    ],
    reference: `function removeInvalidParentheses(s) { let L = 0, R = 0; for (const c of s) { if (c === "(") L++; else if (c === ")") { if (L) L--; else R++; } } const out = new Set(); const go = (i, l, r, open, cur) => { if (i === s.length) { if (!l && !r && !open) out.add(cur); return; } const c = s[i]; if (c === "(" && l) go(i + 1, l - 1, r, open, cur); if (c === ")" && r) go(i + 1, l, r - 1, open, cur); if (c === "(") go(i + 1, l, r, open + 1, cur + c); else if (c === ")") { if (open) go(i + 1, l, r, open - 1, cur + c); } else go(i + 1, l, r, open, cur + c); }; go(0, L, R, 0, ""); return [...out]; }`,
    brute: `function removeInvalidParentheses(s) { const valid = (t) => { let b = 0; for (const c of t) { if (c === "(") b++; else if (c === ")" && --b < 0) return false; } return b === 0; }; let level = new Set([s]); while (level.size) { const ok = [...level].filter(valid); if (ok.length) return ok; const next = new Set(); for (const t of level) for (let i = 0; i < t.length; i++) if (t[i] === "(" || t[i] === ")") next.add(t.slice(0, i) + t.slice(i + 1)); level = next; } return [""]; }`,
    fuzz: gen(`return [__str(rand, __r(rand, 1, 10), "()a")];`),
    examples: [["()())()"], ["(a)())()"]],
    edges: [
      ["no-answer", [")("], "Everything has to go: the empty string."],
      ["single-char", ["x"]],
      ["boundary", ["(((k()(("], "Five '(' removed."],
    ],
  },
];

export const LADDER_RECURSION_SEEDED: ProblemSpec[] = DEFS.map((d) => define(d).spec);
