import { UNIQUE } from "../../dsa-extras/a2z-trees";
import { define, type ProblemDef } from "../../dsa-extras/define";
import { gen, treeGen } from "../../dsa-extras/gen";
import type { ProblemSpec } from "../types";
import { SOME_TREE } from "./ladder-trees-seeded";

const T = "TreeNode | null";
const TREE_DOC = "/**\n * Definition for a binary tree node.\n * function TreeNode(val, left, right) {\n *   this.val = (val === undefined ? 0 : val)\n *   this.left = (left === undefined ? null : left)\n *   this.right = (right === undefined ? null : right)\n * }\n */";
const ROUND_TRIP = `function roundTrip(root) { const data = new Codec().serialize(root); if (typeof data !== "string") throw new Error("serialize must return a string"); return new Codec().deserialize(data); }`;
const ROUND_TRIP_DOC = `/**\n * Serializes with one Codec and deserializes with a fresh one, like LeetCode's judge. Don't change this function.\n * @param {TreeNode | null} root\n * @return {TreeNode | null}\n */\nfunction roundTrip(root) {\n  const data = new Codec().serialize(root);\n  if (typeof data !== "string") throw new Error("serialize must return a string");\n  return new Codec().deserialize(data);\n}`;

/** More judges for seeded LeetCode problems that the Binary Trees Ladder points at. LeetCode's own signatures. */
const DEFS: ProblemDef[] = [
  {
    slug: "find-bottom-left-tree-value",
    title: "Find Bottom Left Tree Value",
    difficulty: "Medium",
    pattern: "Trees",
    fn: "findBottomLeftValue",
    params: [["root", T]],
    returns: "number",
    argTypes: ["TreeNode"],
    hints: [
      "You want the first node of the last level.",
      "BFS that enqueues the right child before the left: the very last node dequeued is the bottom-left one.",
      "queue = [root]\nwhile queue not empty:\n  node = dequeue\n  enqueue node.right if present\n  enqueue node.left if present\nreturn node.val",
    ],
    reference: `function findBottomLeftValue(root) { const q = [root]; let n = root; for (let i = 0; i < q.length; i++) { n = q[i]; if (n.right) q.push(n.right); if (n.left) q.push(n.left); } return n.val; }`,
    brute: `function findBottomLeftValue(root) { let best = -1, val = root.val; const go = (n, d) => { if (!n) return; if (d > best) { best = d; val = n.val; } go(n.left, d + 1); go(n.right, d + 1); }; go(root, 0); return val; }`,
    fuzz: SOME_TREE,
    examples: [[[2, 1, 3]], [[1, 2, 3, 4, null, 5, 6, null, null, 7]]],
    edges: [
      ["single", [[5]]],
      ["skewed", [[1, null, 2, null, 3]], "The deepest node is a right child."],
      ["boundary", [[1, 2, 3, null, null, null, 4]], "The last level has only one node, on the far right."],
    ],
  },
  {
    slug: "all-nodes-distance-k-in-binary-tree",
    title: "All Nodes Distance K in Binary Tree",
    difficulty: "Medium",
    pattern: "Trees",
    fn: "distanceK",
    params: [["root", "TreeNode"], ["target", "TreeNode"], ["k", "number"]],
    returns: "number[]",
    argTypes: ["TreeNode", "TreeNodeRef", "value"],
    compare: "unordered",
    hints: [
      "Distance can go up through parents as well as down. Once you can move to a parent, the tree is just an undirected graph.",
      "Record every node's parent with one DFS, then BFS from target over left, right and parent, k steps, never revisiting. Any order is accepted.",
      "parent = map from one DFS\nqueue = [target], seen = {target}\nrepeat k times:\n  next = []\n  for node in queue:\n    for nb in node.left, node.right, parent[node]:\n      if nb and nb not in seen: add to seen; next.append(nb)\n  queue = next\nreturn values in queue",
    ],
    reference: `function distanceK(root, target, k) { const par = new Map(); const go = (n, p) => { if (!n) return; par.set(n, p); go(n.left, n); go(n.right, n); }; go(root, null); let q = [target]; const seen = new Set(q); for (let s = 0; s < k; s++) { const next = []; for (const n of q) for (const nb of [n.left, n.right, par.get(n)]) if (nb && !seen.has(nb)) { seen.add(nb); next.push(nb); } q = next; } return q.map((n) => n.val); }`,
    brute: `function distanceK(root, target, k) { const path = (n, t) => { if (!n) return null; if (n === t) return [n]; const s = path(n.left, t) || path(n.right, t); return s ? [n].concat(s) : null; }; const tp = path(root, target), out = []; const all = []; const walk = (n) => { if (n) { all.push(n); walk(n.left); walk(n.right); } }; walk(root); for (const n of all) { const np = path(root, n); let c = 0; while (c < tp.length && c < np.length && tp[c] === np[c]) c++; if (tp.length - c + np.length - c === k) out.push(n.val); } return out; }`,
    fuzz: treeGen(`${UNIQUE} const t = __uniq(rand, __r(rand, 1, 12)); const v = t.filter((x) => x !== null); return [t, __pick(rand, v), __r(rand, 0, 4)];`),
    examples: [[[3, 5, 1, 6, 2, 0, 8, null, null, 7, 4], 5, 2], [[1], 1, 3]],
    edges: [
      ["zeros", [[1, 2, 3], 2, 0], "k = 0 is the target itself."],
      ["boundary", [[1, 2, 3, 4, 5], 1, 2], "The target is the root."],
      ["skewed", [[1, 2, null, 3, null, 4], 4, 2], "The answer is up the chain."],
    ],
  },
  {
    slug: "maximum-width-of-binary-tree",
    title: "Maximum Width of Binary Tree",
    difficulty: "Medium",
    pattern: "Trees",
    fn: "widthOfBinaryTree",
    params: [["root", T]],
    returns: "number",
    argTypes: ["TreeNode"],
    hints: [
      "Number the nodes like a heap: the root is 0, the children of i are 2i + 1 and 2i + 2. A level's width is last index - first index + 1, gaps included.",
      "BFS by level with these indexes. Subtract the level's first index from every index so the numbers stay small on deep trees.",
      "queue = [(root, 0)], best = 0\nwhile queue not empty:\n  first = index of queue[0]\n  best = max(best, index of last - first + 1)\n  next = []\n  for (node, i) in queue:\n    i = i - first\n    add (node.left, 2i + 1) and (node.right, 2i + 2) when present\n  queue = next\nreturn best",
    ],
    reference: `function widthOfBinaryTree(root) { let q = [[root, 0]], best = 0; while (q.length) { const first = q[0][1]; best = Math.max(best, q[q.length - 1][1] - first + 1); const next = []; for (const [n, i0] of q) { const i = i0 - first; if (n.left) next.push([n.left, 2 * i + 1]); if (n.right) next.push([n.right, 2 * i + 2]); } q = next; } return best; }`,
    brute: `function widthOfBinaryTree(root) { const lo = [], hi = []; const go = (n, d, i) => { if (!n) return; lo[d] = lo[d] === undefined ? i : Math.min(lo[d], i); hi[d] = hi[d] === undefined ? i : Math.max(hi[d], i); go(n.left, d + 1, 2 * i); go(n.right, d + 1, 2 * i + 1); }; go(root, 0, 1); return Math.max(...lo.map((v, d) => hi[d] - v + 1)); }`,
    fuzz: SOME_TREE,
    examples: [[[1, 3, 2, 5, 3, null, 9]], [[1, 3, 2, 5, null, null, 9, 6, null, 7]], [[1, 3, 2, 5]]],
    edges: [
      ["single", [[1]]],
      ["skewed", [[1, 2, null, 3]], "One node per level: width 1."],
      ["boundary", [[1, 2, 3, 4, null, null, 5]], "The gap between 4 and 5 counts."],
    ],
  },
  {
    slug: "count-complete-tree-nodes",
    title: "Count Complete Tree Nodes",
    difficulty: "Medium",
    pattern: "Trees",
    fn: "countNodes",
    params: [["root", T]],
    returns: "number",
    argTypes: ["TreeNode"],
    hints: [
      "Counting every node is O(n). In a complete tree, if the leftmost and rightmost depths match, the tree is perfect and has 2^h - 1 nodes.",
      "Otherwise recurse into both children; one of them is always perfect, so the work is O(log^2 n).",
      "count(node):\n  if node is empty: return 0\n  l = depth following left pointers\n  r = depth following right pointers\n  if l == r: return 2^l - 1\n  return 1 + count(node.left) + count(node.right)",
    ],
    reference: `function countNodes(root) { if (!root) return 0; let l = 0, r = 0; for (let n = root; n; n = n.left) l++; for (let n = root; n; n = n.right) r++; if (l === r) return 2 ** l - 1; return 1 + countNodes(root.left) + countNodes(root.right); }`,
    brute: `function countNodes(root) { let c = 0; const st = root ? [root] : []; while (st.length) { const n = st.pop(); c++; if (n.left) st.push(n.left); if (n.right) st.push(n.right); } return c; }`,
    fuzz: gen(`return [Array.from({ length: __r(rand, 0, 20) }, (_, i) => i + 1)];`),
    examples: [[[1, 2, 3, 4, 5, 6]], [[1]]],
    edges: [
      ["empty", [[]]],
      ["boundary", [[1, 2, 3, 4, 5, 6, 7]], "A perfect tree: no recursion needed."],
      ["two", [[1, 2]]],
    ],
  },
  {
    slug: "house-robber-iii",
    title: "House Robber III",
    difficulty: "Medium",
    pattern: "Trees",
    fn: "rob",
    params: [["root", T]],
    returns: "number",
    argTypes: ["TreeNode"],
    hints: [
      "You cannot rob a node and its parent together. For each node you want two numbers: the best with it robbed and the best with it skipped.",
      "Return the pair from a post-order DFS: robbed = val + skipped(left) + skipped(right); skipped = best(left) + best(right).",
      "go(node):\n  if node is empty: return (0, 0)\n  (lr, ls) = go(node.left)\n  (rr, rs) = go(node.right)\n  robbed = node.val + ls + rs\n  skipped = max(lr, ls) + max(rr, rs)\n  return (robbed, skipped)\nreturn max of go(root)",
    ],
    reference: `function rob(root) { const go = (n) => { if (!n) return [0, 0]; const [lr, ls] = go(n.left), [rr, rs] = go(n.right); return [n.val + ls + rs, Math.max(lr, ls) + Math.max(rr, rs)]; }; return Math.max(...go(root)); }`,
    brute: `function rob(root) { const best = (n) => { if (!n) return 0; let take = n.val; for (const c of [n.left, n.right]) if (c) take += best(c.left) + best(c.right); return Math.max(take, best(n.left) + best(n.right)); }; return best(root); }`,
    fuzz: treeGen(`return [__levelTree(rand, __r(rand, 1, 12), 0, 9)];`),
    examples: [[[3, 2, 3, null, 3, null, 1]], [[3, 4, 5, 1, 3, null, 1]]],
    edges: [
      ["single", [[4]]],
      ["skewed", [[4, 1, null, 2, null, 3]], "Rob 4 and 3, two apart."],
      ["all-equal", [[1, 1, 1, 1, 1, 1, 1]]],
    ],
  },
  {
    slug: "maximum-binary-tree",
    title: "Maximum Binary Tree",
    difficulty: "Medium",
    pattern: "Trees",
    fn: "constructMaximumBinaryTree",
    params: [["nums", "number[]"]],
    returns: T,
    returnKind: "TreeNode",
    hints: [
      "The maximum is the root; everything left of it builds the left subtree, everything right of it the right subtree.",
      "Recursion is O(n^2) on sorted input. A decreasing stack builds it in O(n): each new value adopts the last popped smaller node as its left child and becomes the right child of the stack top.",
      "stack = []\nfor x in nums:\n  node = new node(x), last = empty\n  while stack not empty and top.val < x: last = pop\n  node.left = last\n  if stack not empty: top.right = node\n  push node\nreturn stack[0]",
    ],
    reference: `function constructMaximumBinaryTree(nums) { const st = []; for (const x of nums) { const node = new TreeNode(x); let last = null; while (st.length && st[st.length - 1].val < x) last = st.pop(); node.left = last; if (st.length) st[st.length - 1].right = node; st.push(node); } return st[0]; }`,
    brute: `function constructMaximumBinaryTree(nums) { if (!nums.length) return null; const m = nums.indexOf(Math.max(...nums)); return new TreeNode(nums[m], constructMaximumBinaryTree(nums.slice(0, m)), constructMaximumBinaryTree(nums.slice(m + 1))); }`,
    fuzz: gen(`return [__shuffle(rand, Array.from({ length: 20 }, (_, i) => i)).slice(0, __r(rand, 1, 9))];`),
    examples: [[[3, 2, 1, 6, 0, 5]], [[3, 2, 1]]],
    edges: [
      ["single", [[1]]],
      ["sorted", [[1, 2, 3, 4]], "Increasing input: a left-leaning chain."],
      ["two", [[2, 7]]],
    ],
  },
  {
    slug: "amount-of-time-for-binary-tree-to-be-infected",
    title: "Amount of Time for Binary Tree to Be Infected",
    difficulty: "Medium",
    pattern: "Trees",
    fn: "amountOfTime",
    params: [["root", T], ["start", "number"]],
    returns: "number",
    argTypes: ["TreeNode", "value"],
    hints: [
      "Infection spreads to parents as well as children each minute. The answer is the farthest any node is from start.",
      "Treat the tree as an undirected graph (record parents), then BFS from the start node and count the levels.",
      "parent = map from one DFS; startNode = node with value start\nqueue = [startNode], seen = {startNode}, minutes = -1\nwhile queue not empty:\n  minutes += 1\n  next = unseen neighbours (left, right, parent) of every node in queue\n  mark them seen; queue = next\nreturn minutes",
    ],
    reference: `function amountOfTime(root, start) { const par = new Map(); let s = null; const go = (n, p) => { if (!n) return; par.set(n, p); if (n.val === start) s = n; go(n.left, n); go(n.right, n); }; go(root, null); let q = [s], t = -1; const seen = new Set(q); while (q.length) { t++; const next = []; for (const n of q) for (const nb of [n.left, n.right, par.get(n)]) if (nb && !seen.has(nb)) { seen.add(nb); next.push(nb); } q = next; } return t; }`,
    brute: `function amountOfTime(root, start) { const edges = [], vals = []; const go = (n) => { if (!n) return; vals.push(n.val); for (const c of [n.left, n.right]) if (c) { edges.push([n.val, c.val]); go(c); } }; go(root); let sick = new Set([start]), t = 0; while (sick.size < vals.length) { const next = new Set(sick); for (const [a, b] of edges) { if (sick.has(a)) next.add(b); if (sick.has(b)) next.add(a); } sick = next; t++; } return t; }`,
    fuzz: treeGen(`${UNIQUE} const t = __uniq(rand, __r(rand, 1, 12)); return [t, __pick(rand, t.filter((x) => x !== null))];`),
    examples: [[[1, 5, 3, null, 4, 10, 6, 9, 2], 3], [[1], 1]],
    edges: [
      ["two", [[1, 2], 2]],
      ["skewed", [[1, 2, null, 3, null, 4], 1]],
      ["boundary", [[1, 2, 3, 4, 5], 4], "Start at a leaf: the infection climbs first."],
    ],
  },
  {
    slug: "maximum-level-sum-of-a-binary-tree",
    title: "Maximum Level Sum of a Binary Tree",
    difficulty: "Medium",
    pattern: "Trees",
    fn: "maxLevelSum",
    params: [["root", T]],
    returns: "number",
    argTypes: ["TreeNode"],
    hints: [
      "Levels are numbered from 1. Sum each level and return the level with the largest sum (the smallest level on a tie).",
      "BFS by level keeping the best sum and its level; only replace on a strictly larger sum.",
      "queue = [root], level = 0, best = -infinity, ans = 1\nwhile queue not empty:\n  level += 1\n  s = sum of values in queue\n  if s > best: best = s, ans = level\n  queue = children of queue\nreturn ans",
    ],
    reference: `function maxLevelSum(root) { let q = [root], lvl = 0, best = -Infinity, ans = 1; while (q.length) { lvl++; const s = q.reduce((a, n) => a + n.val, 0); if (s > best) { best = s; ans = lvl; } q = q.flatMap((n) => [n.left, n.right].filter(Boolean)); } return ans; }`,
    brute: `function maxLevelSum(root) { const sums = []; const go = (n, d) => { if (!n) return; sums[d] = (sums[d] || 0) + n.val; go(n.left, d + 1); go(n.right, d + 1); }; go(root, 0); let b = 0; for (let i = 1; i < sums.length; i++) if (sums[i] > sums[b]) b = i; return b + 1; }`,
    fuzz: treeGen(`return [__levelTree(rand, __r(rand, 1, 12), -5, 9)];`),
    examples: [[[1, 7, 0, 7, -8, null, null]], [[989, null, 10250, 98693, -89388, null, null, null, -32127]]],
    edges: [
      ["single", [[-3]]],
      ["negatives", [[-1, -2, -3]]],
      ["all-equal", [[1, 0, 1]], "Levels 1 and 2 tie: the smaller level wins."],
    ],
  },
  {
    slug: "longest-zigzag-path-in-a-binary-tree",
    title: "Longest ZigZag Path in a Binary Tree",
    difficulty: "Medium",
    pattern: "Trees",
    fn: "longestZigZag",
    params: [["root", T]],
    returns: "number",
    argTypes: ["TreeNode"],
    hints: [
      "A zigzag alternates left and right. When you step left, the path continues only if the next step goes right.",
      "DFS passing two lengths: the zigzag arriving here by a left step and by a right step. Going left extends the 'arrived by right' length; going right extends the 'arrived by left' length.",
      "best = 0\ndfs(node, viaLeft, viaRight):\n  if node is empty: return\n  best = max(best, viaLeft, viaRight)\n  dfs(node.left, viaRight + 1, 0)\n  dfs(node.right, 0, viaLeft + 1)\ndfs(root, 0, 0)\nreturn best",
    ],
    reference: `function longestZigZag(root) { let best = 0; const go = (n, l, r) => { if (!n) return; best = Math.max(best, l, r); go(n.left, r + 1, 0); go(n.right, 0, l + 1); }; go(root, 0, 0); return best; }`,
    brute: `function longestZigZag(root) { let best = 0; const walk = (n, dir) => { let steps = 0; let cur = n; while (cur) { const nxt = dir === "L" ? cur.left : cur.right; if (!nxt) break; steps++; cur = nxt; dir = dir === "L" ? "R" : "L"; } return steps; }; const all = (n) => { if (!n) return; best = Math.max(best, walk(n, "L"), walk(n, "R")); all(n.left); all(n.right); }; all(root); return best; }`,
    fuzz: SOME_TREE,
    examples: [[[1, null, 1, 1, 1, null, null, 1, 1, null, 1, null, null, null, 1]], [[1, 1, 1, null, 1, null, null, 1, 1, null, 1]], [[1]]],
    edges: [
      ["two", [[1, 2]]],
      ["skewed", [[1, 2, null, 3]], "Two left steps in a row do not zigzag."],
      ["boundary", [[1, 2, null, null, 3, 4]], "Left, right, left: length 3."],
    ],
  },
  {
    slug: "check-completeness-of-a-binary-tree",
    title: "Check Completeness of a Binary Tree",
    difficulty: "Medium",
    pattern: "Trees",
    fn: "isCompleteTree",
    params: [["root", T]],
    returns: "boolean",
    argTypes: ["TreeNode"],
    hints: [
      "In a complete tree, a level-order walk never meets a real node after it has met a missing one.",
      "BFS that also enqueues missing children. Once you dequeue an empty slot, every later slot must be empty too.",
      "queue = [root], seenGap = false\nwhile queue not empty:\n  node = dequeue\n  if node is empty: seenGap = true\n  else:\n    if seenGap: return false\n    enqueue node.left, node.right (even if empty)\nreturn true",
    ],
    reference: `function isCompleteTree(root) { const q = [root]; let gap = false; for (let i = 0; i < q.length; i++) { const n = q[i]; if (!n) { gap = true; continue; } if (gap) return false; q.push(n.left, n.right); } return true; }`,
    brute: `function isCompleteTree(root) { let count = 0, maxIdx = 0; const go = (n, i) => { if (!n) return; count++; maxIdx = Math.max(maxIdx, i); go(n.left, 2 * i); go(n.right, 2 * i + 1); }; go(root, 1); return maxIdx === count; }`,
    fuzz: treeGen(`if (rand() < 0.4) return [Array.from({ length: __r(rand, 1, 12) }, (_, i) => i + 1)]; return [__levelTree(rand, __r(rand, 1, 10), 1, 9)];`),
    examples: [[[1, 2, 3, 4, 5, 6]], [[1, 2, 3, 4, 5, null, 7]]],
    edges: [
      ["single", [[1]]],
      ["boundary", [[1, null, 2]], "A right child with no left sibling."],
      ["large", [[1, 2, 3, 4, 5, 6, 7, 8]], "A new level started on the left: still complete."],
    ],
  },
  {
    slug: "distribute-coins-in-binary-tree",
    title: "Distribute Coins in Binary Tree",
    difficulty: "Medium",
    pattern: "Trees",
    fn: "distributeCoins",
    params: [["root", T]],
    returns: "number",
    argTypes: ["TreeNode"],
    hints: [
      "Look at one edge: the coins that must cross it equal |coins in the subtree below - nodes in that subtree|.",
      "Post-order DFS returning each subtree's excess (coins - nodes). Add |excess| of each child to the move count.",
      "moves = 0\nexcess(node):\n  if node is empty: return 0\n  l = excess(node.left); r = excess(node.right)\n  moves = moves + |l| + |r|\n  return node.val + l + r - 1\nexcess(root)\nreturn moves",
    ],
    reference: `function distributeCoins(root) { let moves = 0; const go = (n) => { if (!n) return 0; const l = go(n.left), r = go(n.right); moves += Math.abs(l) + Math.abs(r); return n.val + l + r - 1; }; go(root); return moves; }`,
    brute: `function distributeCoins(root) { const size = (n) => (n ? 1 + size(n.left) + size(n.right) : 0); const coins = (n) => (n ? n.val + coins(n.left) + coins(n.right) : 0); let m = 0; const all = (n) => { if (!n) return; if (n !== root) m += Math.abs(coins(n) - size(n)); all(n.left); all(n.right); }; all(root); return m; }`,
    fuzz: treeGen(`const t = __levelTree(rand, __r(rand, 1, 10), 0, 0); const idx = []; t.forEach((v, i) => { if (v !== null) idx.push(i); }); for (let c = 0; c < idx.length; c++) t[__pick(rand, idx)]++; return [t];`),
    examples: [[[3, 0, 0]], [[0, 3, 0]]],
    edges: [
      ["single", [[1]]],
      ["all-equal", [[1, 1, 1]], "Every node already has one coin."],
      ["skewed", [[0, 0, null, 3]]],
    ],
  },
  {
    slug: "smallest-string-starting-from-leaf",
    title: "Smallest String Starting From Leaf",
    difficulty: "Medium",
    pattern: "Trees",
    fn: "smallestFromLeaf",
    params: [["root", T]],
    returns: "string",
    argTypes: ["TreeNode"],
    hints: [
      "Values 0..25 are letters a..z, and each string is read from a leaf up to the root. Choosing the smaller child greedily fails, because a shorter string can win only at the very end.",
      "DFS building the root-to-node string; at a leaf reverse it and keep the smallest. Compare complete strings only.",
      "best = none\ndfs(node, path):\n  if node is empty: return\n  path = letter(node.val) + path\n  if node is a leaf: best = min(best, path)\n  dfs(node.left, path); dfs(node.right, path)\ndfs(root, \"\")\nreturn best",
    ],
    reference: `function smallestFromLeaf(root) { let best = null; const go = (n, s) => { if (!n) return; s = String.fromCharCode(97 + n.val) + s; if (!n.left && !n.right && (best === null || s < best)) best = s; go(n.left, s); go(n.right, s); }; go(root, ""); return best; }`,
    brute: `function smallestFromLeaf(root) { const all = []; const go = (n, p) => { if (!n) return; p = p.concat(n.val); if (!n.left && !n.right) all.push(p.slice().reverse().map((v) => "abcdefghijklmnopqrstuvwxyz"[v]).join("")); go(n.left, p); go(n.right, p); }; go(root, []); all.sort(); return all[0]; }`,
    fuzz: treeGen(`return [__levelTree(rand, __r(rand, 1, 10), 0, 3)];`),
    examples: [[[0, 1, 2, 3, 4, 3, 4]], [[25, 1, 3, 1, 3, 0, 2]], [[2, 2, 1, null, 1, 0, null, 0]]],
    edges: [
      ["single", [[0]]],
      ["two", [[1, 0]]],
      ["boundary", [[25, 1, null, 0, 0, 1, null, null, null, 0]], "The greedy smaller child leads to a larger string."],
    ],
  },
  {
    slug: "pseudo-palindromic-paths-in-a-binary-tree",
    title: "Pseudo-Palindromic Paths in a Binary Tree",
    difficulty: "Medium",
    pattern: "Trees",
    fn: "pseudoPalindromicPaths",
    params: [["root", T]],
    returns: "number",
    argTypes: ["TreeNode"],
    hints: [
      "Digits can be rearranged into a palindrome when at most one digit appears an odd number of times.",
      "Carry a bitmask of digit parities down the path (toggle bit val). At a leaf the path counts if mask has at most one bit set: mask & (mask - 1) == 0.",
      "count(node, mask):\n  if node is empty: return 0\n  mask = mask xor (1 << node.val)\n  if node is a leaf: return 1 if mask & (mask - 1) == 0 else 0\n  return count(node.left, mask) + count(node.right, mask)\nreturn count(root, 0)",
    ],
    reference: `function pseudoPalindromicPaths(root) { const go = (n, m) => { if (!n) return 0; m ^= 1 << n.val; if (!n.left && !n.right) return (m & (m - 1)) === 0 ? 1 : 0; return go(n.left, m) + go(n.right, m); }; return go(root, 0); }`,
    brute: `function pseudoPalindromicPaths(root) { let c = 0; const go = (n, p) => { if (!n) return; p = p.concat(n.val); if (!n.left && !n.right) { const cnt = {}; for (const v of p) cnt[v] = (cnt[v] || 0) + 1; if (Object.values(cnt).filter((x) => x % 2).length <= 1) c++; } go(n.left, p); go(n.right, p); }; go(root, []); return c; }`,
    fuzz: treeGen(`return [__levelTree(rand, __r(rand, 1, 12), 1, 4)];`),
    examples: [[[2, 3, 1, 3, 1, null, 1]], [[2, 1, 1, 1, 3, null, null, null, null, null, 1]], [[9]]],
    edges: [
      ["all-equal", [[1, 1, 1]]],
      ["two", [[1, 2]], "Two different digits cannot form a palindrome."],
      ["skewed", [[1, 2, null, 1, null, 2]]],
    ],
  },
  {
    slug: "maximum-difference-between-node-and-ancestor",
    title: "Maximum Difference Between Node and Ancestor",
    difficulty: "Medium",
    pattern: "Trees",
    fn: "maxAncestorDiff",
    params: [["root", T]],
    returns: "number",
    argTypes: ["TreeNode"],
    hints: [
      "For a node, the best ancestor partner is the smallest or the largest value on its root path.",
      "DFS carrying the min and max seen on the path; at each node compare against both, then update them for the children.",
      "go(node, lo, hi):\n  if node is empty: return hi - lo\n  lo = min(lo, node.val); hi = max(hi, node.val)\n  return max(go(node.left, lo, hi), go(node.right, lo, hi))\nreturn go(root, root.val, root.val)",
    ],
    reference: `function maxAncestorDiff(root) { const go = (n, lo, hi) => { if (!n) return hi - lo; lo = Math.min(lo, n.val); hi = Math.max(hi, n.val); return Math.max(go(n.left, lo, hi), go(n.right, lo, hi)); }; return go(root, root.val, root.val); }`,
    brute: `function maxAncestorDiff(root) { let best = 0; const desc = (n, v) => { if (!n) return; best = Math.max(best, Math.abs(n.val - v)); desc(n.left, v); desc(n.right, v); }; const all = (n) => { if (!n) return; desc(n.left, n.val); desc(n.right, n.val); all(n.left); all(n.right); }; all(root); return best; }`,
    fuzz: treeGen(`return [__levelTree(rand, __r(rand, 2, 12), 0, 20)];`),
    examples: [[[8, 3, 10, 1, 6, null, 14, null, null, 4, 7, 13]], [[1, null, 2, null, 0, 3]]],
    edges: [
      ["two", [[1, 2]]],
      ["all-equal", [[5, 5, 5]]],
      ["skewed", [[10, 2, null, 7, null, 0]], "The best pair is the root and the deepest node."],
    ],
  },
  {
    slug: "binary-tree-maximum-path-sum",
    title: "Binary Tree Maximum Path Sum",
    difficulty: "Hard",
    pattern: "Trees",
    fn: "maxPathSum",
    params: [["root", T]],
    returns: "number",
    argTypes: ["TreeNode"],
    hints: [
      "Every path has one highest node where it bends. Through that node the best path is val + best downward gain on the left + on the right, ignoring negative gains.",
      "Post-order DFS returning the best downward gain (val + max(0, left, right)) while updating a global best with val + max(0, left) + max(0, right).",
      "best = -infinity\ngain(node):\n  if node is empty: return 0\n  l = max(0, gain(node.left)); r = max(0, gain(node.right))\n  best = max(best, node.val + l + r)\n  return node.val + max(l, r)\ngain(root)\nreturn best",
    ],
    reference: `function maxPathSum(root) { let best = -Infinity; const gain = (n) => { if (!n) return 0; const l = Math.max(0, gain(n.left)), r = Math.max(0, gain(n.right)); best = Math.max(best, n.val + l + r); return n.val + Math.max(l, r); }; gain(root); return best; }`,
    brute: `function maxPathSum(root) { const path = (n, t) => { if (!n) return null; if (n === t) return [n]; const s = path(n.left, t) || path(n.right, t); return s ? [n].concat(s) : null; }; const all = []; const walk = (n) => { if (n) { all.push(n); walk(n.left); walk(n.right); } }; walk(root); let best = -Infinity; for (const a of all) for (const b of all) { const pa = path(root, a), pb = path(root, b); let c = 0; while (c < pa.length && c < pb.length && pa[c] === pb[c]) c++; let s = pa[c - 1].val; for (let i = c; i < pa.length; i++) s += pa[i].val; for (let i = c; i < pb.length; i++) s += pb[i].val; best = Math.max(best, s); } return best; }`,
    fuzz: treeGen(`return [__levelTree(rand, __r(rand, 1, 12), -10, 10)];`),
    examples: [[[1, 2, 3]], [[-10, 9, 20, null, null, 15, 7]]],
    edges: [
      ["single", [[-3]], "A single negative node is still a path."],
      ["negatives", [[-2, -1, -3]], "Every value is negative: take the largest one alone."],
      ["skewed", [[2, -1, null, 5]]],
    ],
  },
  {
    slug: "serialize-and-deserialize-binary-tree",
    title: "Serialize and Deserialize Binary Tree",
    difficulty: "Hard",
    pattern: "Trees",
    fn: "roundTrip",
    params: [["root", T]],
    returns: T,
    argTypes: ["TreeNode"],
    returnKind: "TreeNode",
    starter: `${TREE_DOC}\nclass Codec {\n  /** Encodes a tree to a single string. */\n  serialize(root) {\n    \n  }\n\n  /** Decodes your encoded data back to a tree. */\n  deserialize(data) {\n    \n  }\n}\n\n${ROUND_TRIP_DOC}`,
    hints: [
      "Any format works as long as deserialize(serialize(tree)) rebuilds the same tree. Mark empty children explicitly so the shape is not lost.",
      "Preorder with a '#' for every empty child, joined by commas. To decode, read tokens with a pointer: '#' is empty; otherwise make a node and decode its left then right.",
      "serialize(node):\n  if node is empty: return \"#\"\n  return node.val + \",\" + serialize(node.left) + \",\" + serialize(node.right)\ndeserialize(data):\n  tokens = data split on \",\", i = 0\n  build():\n    t = tokens[i]; i += 1\n    if t == \"#\": return empty\n    node = new node(t); node.left = build(); node.right = build()\n    return node\n  return build()",
    ],
    reference: `class Codec { serialize(root) { const out = []; const go = (n) => { if (!n) { out.push("#"); return; } out.push(n.val); go(n.left); go(n.right); }; go(root); return out.join(","); } deserialize(data) { const a = data.split(","); let i = 0; const go = () => { const v = a[i++]; if (v === "#") return null; const n = new TreeNode(Number(v)); n.left = go(); n.right = go(); return n; }; return go(); } }\n${ROUND_TRIP}`,
    brute: `class Codec { serialize(root) { return JSON.stringify(__treeToLevelOrder(root)); } deserialize(data) { return __treeFromLevelOrder(JSON.parse(data)); } }\n${ROUND_TRIP}`,
    fuzz: treeGen(`return [__levelTree(rand, __r(rand, 0, 12), -9, 9)];`),
    examples: [[[1, 2, 3, null, null, 4, 5]], [[]]],
    edges: [
      ["single", [[1]]],
      ["negatives", [[-1, -20, 300]], "Multi-digit and negative values."],
      ["skewed", [[1, null, 2, null, 3]]],
    ],
  },
  {
    slug: "vertical-order-traversal-of-a-binary-tree",
    title: "Vertical Order Traversal of a Binary Tree",
    difficulty: "Hard",
    pattern: "Trees",
    fn: "verticalTraversal",
    params: [["root", T]],
    returns: "number[][]",
    argTypes: ["TreeNode"],
    hints: [
      "Give every node a (column, row): left child is (col - 1, row + 1), right child (col + 1, row + 1). Columns go left to right; inside a column, top to bottom, and equal positions by value.",
      "Collect (col, row, val) for every node, sort by col, then row, then val, and group by column.",
      "items = []\ndfs(node, row, col): add (col, row, node.val); recurse into children\ndfs(root, 0, 0)\nsort items by (col, row, val)\ngroup consecutive items with the same col\nreturn the groups' values",
    ],
    reference: `function verticalTraversal(root) { const items = []; const go = (n, r, c) => { if (!n) return; items.push([c, r, n.val]); go(n.left, r + 1, c - 1); go(n.right, r + 1, c + 1); }; go(root, 0, 0); items.sort((a, b) => a[0] - b[0] || a[1] - b[1] || a[2] - b[2]); const out = []; let last = null; for (const [c, , v] of items) { if (c !== last) { out.push([]); last = c; } out[out.length - 1].push(v); } return out; }`,
    brute: `function verticalTraversal(root) { const cols = new Map(); const q = [[root, 0, 0]]; for (let i = 0; i < q.length; i++) { const [n, r, c] = q[i]; if (!cols.has(c)) cols.set(c, []); cols.get(c).push([r, n.val]); if (n.left) q.push([n.left, r + 1, c - 1]); if (n.right) q.push([n.right, r + 1, c + 1]); } return [...cols.keys()].sort((a, b) => a - b).map((c) => cols.get(c).sort((x, y) => x[0] - y[0] || x[1] - y[1]).map((p) => p[1])); }`,
    fuzz: SOME_TREE,
    examples: [[[3, 9, 20, null, null, 15, 7]], [[1, 2, 3, 4, 5, 6, 7]], [[1, 2, 3, 4, 6, 5, 7]]],
    edges: [
      ["single", [[1]]],
      ["duplicates", [[1, 2, 3, 4, 6, 5, 6]], "Same column and row: smaller value first."],
      ["skewed", [[1, 2, null, 3]]],
    ],
  },
  {
    slug: "binary-tree-cameras",
    title: "Binary Tree Cameras",
    difficulty: "Hard",
    pattern: "Trees",
    fn: "minCameraCover",
    params: [["root", T]],
    returns: "number",
    argTypes: ["TreeNode"],
    hints: [
      "A camera watches its parent, itself and its children. Putting cameras on leaves wastes them; put them on leaves' parents instead.",
      "Post-order with three states: 0 = not watched, 1 = has a camera, 2 = watched. If a child is unwatched, place a camera here; if a child has a camera, this node is watched; else this node is unwatched. Add one if the root ends unwatched.",
      "cams = 0\nstate(node):\n  if node is empty: return 2\n  l = state(node.left); r = state(node.right)\n  if l == 0 or r == 0: cams += 1; return 1\n  if l == 1 or r == 1: return 2\n  return 0\nif state(root) == 0: cams += 1\nreturn cams",
    ],
    reference: `function minCameraCover(root) { let cams = 0; const st = (n) => { if (!n) return 2; const l = st(n.left), r = st(n.right); if (l === 0 || r === 0) { cams++; return 1; } if (l === 1 || r === 1) return 2; return 0; }; if (st(root) === 0) cams++; return cams; }`,
    brute: `function minCameraCover(root) { const nodes = [], par = new Map(); const walk = (n, p) => { if (!n) return; par.set(n, p); nodes.push(n); walk(n.left, n); walk(n.right, n); }; walk(root, null); let best = Infinity; for (let m = 0; m < 1 << nodes.length; m++) { const on = new Set(nodes.filter((_, i) => m & (1 << i))); if (on.size >= best) continue; const ok = nodes.every((n) => on.has(n) || on.has(par.get(n)) || on.has(n.left) || on.has(n.right)); if (ok) best = on.size; } return best; }`,
    fuzz: treeGen(`return [__levelTree(rand, __r(rand, 1, 12), 0, 0)];`),
    examples: [[[0, 0, null, 0, 0]], [[0, 0, null, 0, null, 0, null, null, 0]]],
    edges: [
      ["single", [[0]], "One node needs its own camera."],
      ["skewed", [[0, 0, null, 0]]],
      ["boundary", [[0, 0, 0, 0, 0, 0, 0]], "Cameras on both middle nodes cover everything."],
    ],
  },
];

export const LADDER_TREES2_SEEDED: ProblemSpec[] = DEFS.map((d) => define(d).spec);
