import { define, type ProblemDef } from "../../dsa-extras/define";
import { gen } from "../../dsa-extras/gen";
import type { ProblemSpec } from "../types";

const POPCOUNT = `let c = 0; while (x) { x &= x - 1; c++; } return c;`;

/** Judges for seeded LeetCode problems that the Bit Manipulation & Math Ladder points at. LeetCode's own signatures. */
const DEFS: ProblemDef[] = [
  {
    slug: "power-of-two",
    title: "Power of Two",
    difficulty: "Easy",
    pattern: "Bit Manipulation",
    fn: "isPowerOfTwo",
    params: [["n", "number"]],
    returns: "boolean",
    hints: [
      "A power of two has exactly one set bit.",
      "n & (n - 1) clears the lowest set bit. For a positive power of two that leaves 0.",
      "return n > 0 and (n AND (n - 1)) == 0",
    ],
    reference: `function isPowerOfTwo(n) { return n > 0 && (n & (n - 1)) === 0; }`,
    brute: `function isPowerOfTwo(n) { if (n < 1) return false; while (n % 2 === 0) n /= 2; return n === 1; }`,
    fuzz: gen(`return [rand() < 0.5 ? 2 ** __r(rand, 0, 30) : __r(rand, -20, 5000)];`),
    examples: [[1], [16], [3]],
    edges: [
      ["zeros", [0], "0 has no set bits: not a power of two."],
      ["negatives", [-16], "Negative numbers are never powers of two."],
      ["extremes", [1073741824]],
    ],
  },
  {
    slug: "power-of-four",
    title: "Power of Four",
    difficulty: "Easy",
    pattern: "Bit Manipulation",
    fn: "isPowerOfFour",
    params: [["n", "number"]],
    returns: "boolean",
    hints: [
      "Every power of four is a power of two, but not the other way round. Where does the single set bit sit?",
      "Check it's a power of two, then check the bit is in an even position: n & 0x55555555 must be non-zero.",
      "return n > 0 and (n AND (n - 1)) == 0 and (n AND 0x55555555) != 0",
    ],
    reference: `function isPowerOfFour(n) { return n > 0 && (n & (n - 1)) === 0 && (n & 0x55555555) !== 0; }`,
    brute: `function isPowerOfFour(n) { if (n < 1) return false; while (n % 4 === 0) n /= 4; return n === 1; }`,
    fuzz: gen(`const r = rand(); return [r < 0.35 ? 4 ** __r(rand, 0, 15) : r < 0.6 ? 2 * 4 ** __r(rand, 0, 14) : __r(rand, -10, 5000)];`),
    examples: [[16], [5], [1]],
    edges: [
      ["zeros", [0]],
      ["boundary", [8], "A power of two, but not of four."],
      ["extremes", [1073741824], "4^15, the largest power of four in range."],
    ],
  },
  {
    slug: "hamming-distance",
    title: "Hamming Distance",
    difficulty: "Easy",
    pattern: "Bit Manipulation",
    fn: "hammingDistance",
    params: [["x", "number"], ["y", "number"]],
    returns: "number",
    hints: [
      "The bits where x and y differ are exactly the set bits of x ^ y.",
      "XOR them, then count set bits. n & (n - 1) drops one set bit per step.",
      "z = x XOR y, count = 0\nwhile z != 0:\n  z = z AND (z - 1)\n  count = count + 1\nreturn count",
    ],
    reference: `function hammingDistance(x, y) { x ^= y; ${POPCOUNT} }`,
    brute: `function hammingDistance(x, y) { let c = 0; for (let i = 0; i < 31; i++) if (((x >> i) & 1) !== ((y >> i) & 1)) c++; return c; }`,
    fuzz: gen(`return [__r(rand, 0, 2147483647), __r(rand, 0, 2147483647)];`),
    examples: [[1, 4], [3, 1]],
    edges: [
      ["zeros", [0, 0]],
      ["all-equal", [7, 7]],
      ["extremes", [0, 2147483647], "Every one of the 31 bits differs."],
    ],
  },
  {
    slug: "minimum-bit-flips-to-convert-number",
    title: "Minimum Bit Flips to Convert Number",
    difficulty: "Easy",
    pattern: "Bit Manipulation",
    fn: "minBitFlips",
    params: [["start", "number"], ["goal", "number"]],
    returns: "number",
    hints: [
      "Each flip fixes one bit where start and goal disagree.",
      "Count the set bits of start ^ goal.",
      "z = start XOR goal, count = 0\nwhile z != 0:\n  z = z AND (z - 1)\n  count = count + 1\nreturn count",
    ],
    reference: `function minBitFlips(start, goal) { let x = start ^ goal; ${POPCOUNT} }`,
    brute: `function minBitFlips(start, goal) { const a = start.toString(2).padStart(31, "0"), b = goal.toString(2).padStart(31, "0"); let c = 0; for (let i = 0; i < 31; i++) if (a[i] !== b[i]) c++; return c; }`,
    fuzz: gen(`return [__r(rand, 0, 1000000000), __r(rand, 0, 1000000000)];`),
    examples: [[10, 7], [3, 4]],
    edges: [
      ["zeros", [0, 0]],
      ["all-equal", [5, 5]],
      ["extremes", [0, 1000000000]],
    ],
  },
  {
    slug: "reverse-bits",
    title: "Reverse Bits",
    difficulty: "Easy",
    pattern: "Bit Manipulation",
    fn: "reverseBits",
    params: [["n", "number"]],
    returns: "number",
    hints: [
      "Read bits from the right end of n and push them onto the right end of the result, 32 times.",
      "Shift the result left, OR in n & 1, then shift n right (unsigned). In JavaScript finish with >>> 0 so the answer is unsigned.",
      "result = 0\nrepeat 32 times:\n  result = (result << 1) OR (n AND 1)\n  n = n unsigned-shift-right 1\nreturn result as unsigned",
    ],
    reference: `function reverseBits(n) { let r = 0; for (let i = 0; i < 32; i++) { r = (r << 1) | (n & 1); n >>>= 1; } return r >>> 0; }`,
    brute: `function reverseBits(n) { return parseInt(n.toString(2).padStart(32, "0").split("").reverse().join(""), 2); }`,
    fuzz: gen(`return [Math.floor(rand() * 4294967296)];`),
    examples: [[43261596], [4294967293]],
    edges: [
      ["zeros", [0]],
      ["boundary", [1], "The lowest bit becomes the highest: 2^31."],
      ["extremes", [4294967295], "All 32 bits set."],
    ],
  },
  {
    slug: "sort-integers-by-the-number-of-1-bits",
    title: "Sort Integers by The Number of 1 Bits",
    difficulty: "Easy",
    pattern: "Bit Manipulation",
    fn: "sortByBits",
    params: [["arr", "number[]"]],
    returns: "number[]",
    hints: [
      "Sort by a two-part key: the number of set bits first, then the value.",
      "Write a popcount helper and use it in the comparator; break ties with a - b.",
      "bits(x) = number of set bits in x\nsort arr by (bits(x), x)\nreturn arr",
    ],
    reference: `function sortByBits(arr) { const bits = (x) => { ${POPCOUNT} }; return arr.slice().sort((a, b) => bits(a) - bits(b) || a - b); }`,
    brute: `function sortByBits(arr) { const buckets = Array.from({ length: 32 }, () => []); for (const v of arr) buckets[v.toString(2).split("1").length - 1].push(v); return buckets.flatMap((b) => b.sort((x, y) => x - y)); }`,
    fuzz: gen(`return [__arr(rand, __r(rand, 1, 15), 0, 10000)];`),
    examples: [[[0, 1, 2, 3, 4, 5, 6, 7, 8]], [[1024, 512, 256, 128, 64, 32, 16, 8, 4, 2, 1]]],
    edges: [
      ["single", [[7]]],
      ["duplicates", [[3, 3, 1, 1]]],
      ["zeros", [[0, 0, 5]]],
    ],
  },
  {
    slug: "find-the-difference",
    title: "Find the Difference",
    difficulty: "Easy",
    pattern: "Bit Manipulation",
    fn: "findTheDifference",
    params: [["s", "string"], ["t", "string"]],
    returns: "character",
    hints: [
      "Every letter of s appears in t too. Pairs cancel under XOR.",
      "XOR the character codes of both strings together. What's left is the added letter.",
      "x = 0\nfor c in s + t:\n  x = x XOR code(c)\nreturn the character with code x",
    ],
    reference: `function findTheDifference(s, t) { let x = 0; for (const c of s + t) x ^= c.charCodeAt(0); return String.fromCharCode(x); }`,
    brute: `function findTheDifference(s, t) { const cnt = {}; for (const c of s) cnt[c] = (cnt[c] || 0) + 1; for (const c of t) { if (!cnt[c]) return c; cnt[c]--; } return ""; }`,
    fuzz: gen(`const s = __str(rand, __r(rand, 0, 12), "abcde"); const t = __shuffle(rand, (s + __str(rand, 1, "abcdez")).split("")).join(""); return [s, t];`),
    examples: [["abcd", "abcde"], ["", "y"]],
    edges: [
      ["duplicates", ["aa", "aaa"], "The extra letter already appears in s."],
      ["boundary", ["abc", "zabc"]],
      ["all-equal", ["bbbb", "bbbbb"]],
    ],
  },
  {
    slug: "xor-queries-of-a-subarray",
    title: "XOR Queries of a Subarray",
    difficulty: "Medium",
    pattern: "Bit Manipulation",
    fn: "xorQueries",
    params: [["arr", "number[]"], ["queries", "number[][]"]],
    returns: "number[]",
    hints: [
      "XOR undoes itself, so prefix XORs work like prefix sums.",
      "Build pre[i + 1] = pre[i] ^ arr[i]. The XOR of arr[l..r] is pre[r + 1] ^ pre[l].",
      "pre[0] = 0\nfor i in 0 .. n - 1: pre[i + 1] = pre[i] XOR arr[i]\nreturn [pre[r + 1] XOR pre[l] for each (l, r) in queries]",
    ],
    reference: `function xorQueries(arr, queries) { const pre = [0]; for (const v of arr) pre.push(pre[pre.length - 1] ^ v); return queries.map(([l, r]) => pre[r + 1] ^ pre[l]); }`,
    brute: `function xorQueries(arr, queries) { return queries.map(([l, r]) => { let x = 0; for (let i = l; i <= r; i++) x ^= arr[i]; return x; }); }`,
    fuzz: gen(`const n = __r(rand, 1, 10); const qs = Array.from({ length: __r(rand, 1, 6) }, () => { const l = __r(rand, 0, n - 1); return [l, __r(rand, l, n - 1)]; }); return [__arr(rand, n, 1, 100), qs];`),
    examples: [[[1, 3, 4, 8], [[0, 1], [1, 2], [0, 3], [3, 3]]], [[4, 8, 2, 10], [[2, 3], [1, 3], [0, 0], [0, 3]]]],
    edges: [
      ["single", [[5], [[0, 0]]]],
      ["all-equal", [[7, 7, 7], [[0, 1], [0, 2]]], "An even count of equal values cancels to 0."],
      ["boundary", [[1, 2, 3], [[2, 2], [0, 2]]]],
    ],
  },
  {
    slug: "single-number-ii",
    title: "Single Number II",
    difficulty: "Medium",
    pattern: "Bit Manipulation",
    fn: "singleNumber",
    params: [["nums", "number[]"]],
    returns: "number",
    hints: [
      "Look at one bit position: summed over the array, it's a multiple of 3 plus the single number's bit.",
      "Either count each of the 32 bits mod 3, or keep two masks (ones, twos) that track which bits have been seen once or twice.",
      "ones = 0, twos = 0\nfor x in nums:\n  ones = (ones XOR x) AND NOT twos\n  twos = (twos XOR x) AND NOT ones\nreturn ones",
    ],
    reference: `function singleNumber(nums) { let ones = 0, twos = 0; for (const x of nums) { ones = (ones ^ x) & ~twos; twos = (twos ^ x) & ~ones; } return ones; }`,
    brute: `function singleNumber(nums) { const cnt = new Map(); for (const x of nums) cnt.set(x, (cnt.get(x) || 0) + 1); for (const [v, c] of cnt) if (c === 1) return v; return null; }`,
    fuzz: gen(`const k = __r(rand, 0, 5); const set = new Set(); while (set.size < k + 1) set.add(__r(rand, -50, 50)); const [single, ...rest] = [...set]; const a = [single]; for (const v of rest) a.push(v, v, v); return [__shuffle(rand, a)];`),
    examples: [[[2, 2, 3, 2]], [[0, 1, 0, 1, 0, 1, 99]]],
    edges: [
      ["single", [[5]]],
      ["negatives", [[-2, -2, 1, 1, -3, 1, -3, -3, -4, -2]]],
      ["extremes", [[2147483647, 2147483647, 2147483647, -2147483648]], "The sign bit matters too."],
    ],
  },
  {
    slug: "single-number-iii",
    title: "Single Number III",
    difficulty: "Medium",
    pattern: "Bit Manipulation",
    fn: "singleNumber",
    params: [["nums", "number[]"]],
    returns: "number[]",
    compare: "unordered",
    hints: [
      "XOR of everything is a ^ b for the two singles. It's non-zero, so some bit differs between them.",
      "Pick the lowest set bit of a ^ b (x & -x). It splits the array into two groups, each with one single and only pairs otherwise. XOR each group.",
      "x = XOR of all nums\nbit = x AND -x\na = 0, b = 0\nfor v in nums:\n  if v AND bit: a = a XOR v\n  else: b = b XOR v\nreturn [a, b]",
    ],
    reference: `function singleNumber(nums) { let x = 0; for (const v of nums) x ^= v; const bit = x & -x; let a = 0, b = 0; for (const v of nums) { if (v & bit) a ^= v; else b ^= v; } return [a, b]; }`,
    brute: `function singleNumber(nums) { const cnt = new Map(); for (const x of nums) cnt.set(x, (cnt.get(x) || 0) + 1); return [...cnt].filter(([, c]) => c === 1).map(([v]) => v); }`,
    fuzz: gen(`const k = __r(rand, 2, 7); const set = new Set(); while (set.size < k) set.add(__r(rand, -50, 50)); const v = [...set]; const a = [v[0], v[1]]; for (const x of v.slice(2)) a.push(x, x); return [__shuffle(rand, a)];`),
    examples: [[[1, 2, 1, 3, 2, 5]], [[-1, 0]], [[0, 1]]],
    edges: [
      ["two", [[7, 9]]],
      ["negatives", [[-5, -5, -3, 7]]],
      ["extremes", [[2147483647, -2147483648, 4, 4]], "a ^ b is -1: the lowest set bit is still bit 0."],
    ],
  },
  {
    slug: "sum-of-two-integers",
    title: "Sum of Two Integers",
    difficulty: "Medium",
    pattern: "Bit Manipulation",
    fn: "getSum",
    params: [["a", "number"], ["b", "number"]],
    returns: "number",
    hints: [
      "Without + you can still add one bit column at a time: XOR gives the sum bit, AND gives the carry.",
      "Repeat: sum = a ^ b, carry = (a & b) << 1, until the carry is 0. Two's complement handles negatives for free.",
      "while b != 0:\n  carry = (a AND b) << 1\n  a = a XOR b\n  b = carry\nreturn a",
    ],
    reference: `function getSum(a, b) { while (b !== 0) { const c = (a & b) << 1; a ^= b; b = c; } return a; }`,
    brute: `function getSum(a, b) { return a + b; }`,
    fuzz: gen(`return [__r(rand, -1000, 1000), __r(rand, -1000, 1000)];`),
    examples: [[1, 2], [2, 3]],
    edges: [
      ["zeros", [0, 0]],
      ["negatives", [-5, -7]],
      ["boundary", [-1, 1], "The carry ripples through every bit before it disappears."],
    ],
  },
  {
    slug: "bitwise-and-of-numbers-range",
    title: "Bitwise AND of Numbers Range",
    difficulty: "Medium",
    pattern: "Bit Manipulation",
    fn: "rangeBitwiseAnd",
    params: [["left", "number"], ["right", "number"]],
    returns: "number",
    hints: [
      "Any bit below the highest bit where left and right differ flips somewhere in the range, so it ANDs to 0.",
      "The answer is the common binary prefix of left and right. Shift both right until they're equal, then shift back.",
      "shift = 0\nwhile left != right:\n  left = left >> 1\n  right = right >> 1\n  shift = shift + 1\nreturn left << shift",
    ],
    reference: `function rangeBitwiseAnd(left, right) { let s = 0; while (left !== right) { left >>= 1; right >>= 1; s++; } return left << s; }`,
    brute: `function rangeBitwiseAnd(left, right) { let r = left; for (let x = left + 1; x <= right && r; x++) r &= x; return r; }`,
    fuzz: gen(`if (rand() < 0.3) { const l = 2 ** __r(rand, 10, 30) + __r(rand, 0, 500); return [l, l + __r(rand, 0, 500)]; } const l = __r(rand, 0, 1000); return [l, l + __r(rand, 0, 300)];`),
    examples: [[5, 7], [0, 0], [1, 2147483647]],
    edges: [
      ["single", [12, 12], "left == right: the number itself."],
      ["extremes", [2147483646, 2147483647]],
      ["boundary", [1073741824, 1073742000], "A shared high bit survives."],
    ],
  },
  {
    slug: "minimum-flips-to-make-a-or-b-equal-to-c",
    title: "Minimum Flips to Make a OR b Equal to c",
    difficulty: "Medium",
    pattern: "Bit Manipulation",
    fn: "minFlips",
    params: [["a", "number"], ["b", "number"], ["c", "number"]],
    returns: "number",
    hints: [
      "Bits are independent. For each position, how many flips does it take to make (a | b) match c?",
      "If c's bit is 1, you need one flip only when both a and b are 0. If c's bit is 0, you must clear every 1 among a and b (0, 1 or 2 flips).",
      "flips = 0\nfor bit in 0 .. 30:\n  x = bit of a, y = bit of b, z = bit of c\n  if z == 1: flips = flips + (1 if x == 0 and y == 0 else 0)\n  else: flips = flips + x + y\nreturn flips",
    ],
    reference: `function minFlips(a, b, c) { let f = 0; for (let i = 0; i < 31; i++) { const x = (a >> i) & 1, y = (b >> i) & 1, z = (c >> i) & 1; f += z ? (x | y ? 0 : 1) : x + y; } return f; }`,
    brute: `function minFlips(a, b, c) { const pc = (v) => v.toString(2).split("1").length - 1; const wrong = (a | b) ^ c; return pc(wrong) + pc(a & b & wrong); }`,
    fuzz: gen(`const big = rand() < 0.5; const hi = big ? 1000000000 : 64; return [__r(rand, 1, hi), __r(rand, 1, hi), __r(rand, 1, hi)];`),
    examples: [[2, 6, 5], [4, 2, 7], [1, 2, 3]],
    edges: [
      ["all-equal", [5, 5, 5], "a | b is already c."],
      ["boundary", [8, 3, 5]],
      ["extremes", [1000000000, 1000000000, 1]],
    ],
  },
  {
    slug: "count-primes",
    title: "Count Primes",
    difficulty: "Medium",
    pattern: "Math",
    fn: "countPrimes",
    params: [["n", "number"]],
    returns: "number",
    hints: [
      "Testing each number separately is too slow for large n. Cross out composites instead.",
      "Sieve of Eratosthenes: for every p with p * p < n that is still marked prime, mark p * p, p * p + p, ... as composite. Count what's left below n.",
      "if n < 3: return 0\nprime = [true] * n, prime[0] = prime[1] = false\nfor p = 2 while p * p < n:\n  if prime[p]:\n    for m = p * p while m < n step p: prime[m] = false\nreturn count of true in prime",
    ],
    reference: `function countPrimes(n) { if (n < 3) return 0; const comp = new Uint8Array(n); let c = 0; for (let p = 2; p < n; p++) { if (comp[p]) continue; c++; for (let m = p * p; m < n; m += p) comp[m] = 1; } return c; }`,
    brute: `function countPrimes(n) { let c = 0; for (let x = 2; x < n; x++) { let ok = true; for (let d = 2; d * d <= x; d++) if (x % d === 0) { ok = false; break; } if (ok) c++; } return c; }`,
    fuzz: gen(`return [__r(rand, 3, 5000)];`),
    examples: [[10], [0], [1]],
    edges: [
      ["min-size", [2], "Primes strictly less than 2: none."],
      ["boundary", [3]],
      ["large", [50000]],
    ],
  },
  {
    slug: "maximum-xor-of-two-numbers-in-an-array",
    title: "Maximum XOR of Two Numbers in an Array",
    difficulty: "Medium",
    pattern: "Bit Manipulation",
    fn: "findMaximumXOR",
    params: [["nums", "number[]"]],
    returns: "number",
    hints: [
      "Build the answer greedily from the highest bit: can the answer have this bit set, given the bits chosen so far?",
      "For each bit from 30 down, collect the prefixes of all numbers. Try candidate = answer | bit; it's achievable if some prefix p has p ^ candidate also in the set (a ^ b = c means a ^ c = b). A binary trie works too.",
      "answer = 0, mask = 0\nfor bit from 30 down to 0:\n  mask = mask OR (1 << bit)\n  prefixes = {x AND mask for x in nums}\n  candidate = answer OR (1 << bit)\n  if any p in prefixes has (p XOR candidate) in prefixes:\n    answer = candidate\nreturn answer",
    ],
    reference: `function findMaximumXOR(nums) { let ans = 0, mask = 0; for (let b = 30; b >= 0; b--) { mask |= 1 << b; const set = new Set(nums.map((x) => x & mask)); const cand = ans | (1 << b); for (const p of set) if (set.has(p ^ cand)) { ans = cand; break; } } return ans; }`,
    brute: `function findMaximumXOR(nums) { let best = 0; for (let i = 0; i < nums.length; i++) for (let j = i + 1; j < nums.length; j++) best = Math.max(best, nums[i] ^ nums[j]); return best; }`,
    fuzz: gen(`return [__arr(rand, __r(rand, 2, 15), 0, rand() < 0.5 ? 100 : 2147483647)];`),
    examples: [[[3, 10, 5, 25, 2, 8]], [[14, 70, 53, 83, 49, 91, 36, 80, 92, 51, 66, 70]]],
    edges: [
      ["single", [[0]]],
      ["all-equal", [[7, 7, 7]]],
      ["extremes", [[0, 2147483647]]],
      ["large", [Array.from({ length: 700 }, (_, i) => (i * 7919) % 10007)]],
    ],
  },
];

export const LADDER_BITS_SEEDED: ProblemSpec[] = DEFS.map((d) => define(d).spec);
