import { define, type ProblemDef } from "../../dsa-extras/define";
import type { ProblemSpec } from "../types";
import { ggen } from "./ladder-graphs-seeded";

const DIRS = "[[1, 0], [-1, 0], [0, 1], [0, -1]]";
const GRID = "number[][]";
const ADJ = `const adj = Array.from({ length: n }, () => []);`;

/** Judges for the Graphs Ladder: cycles and bipartite, topological sort, weighted shortest paths, union-find and MST. */
const DEFS: ProblemDef[] = [
  {
    slug: "is-graph-bipartite",
    title: "Is Graph Bipartite?",
    difficulty: "Medium",
    pattern: "Graphs (BFS/DFS)",
    fn: "isBipartite",
    params: [["graph", GRID]],
    returns: "boolean",
    hints: [
      "Bipartite means you can colour every node with one of two colours so that every edge joins different colours. The graph may be disconnected.",
      "BFS from every uncoloured node: colour it 0, give each neighbour the opposite colour, and fail if a neighbour already has the same colour.",
      "color = array of n unset\nfor s in 0 .. n - 1:\n  if color[s] is set: continue\n  color[s] = 0; queue = [s]\n  while queue not empty:\n    u = pop front\n    for v in graph[u]:\n      if color[v] is unset: color[v] = 1 - color[u]; push v\n      else if color[v] == color[u]: return false\nreturn true",
    ],
    reference: `function isBipartite(graph) { const n = graph.length, color = new Array(n).fill(-1); for (let s = 0; s < n; s++) { if (color[s] >= 0) continue; color[s] = 0; const q = [s]; for (let i = 0; i < q.length; i++) { const u = q[i]; for (const v of graph[u]) { if (color[v] < 0) { color[v] = 1 - color[u]; q.push(v); } else if (color[v] === color[u]) return false; } } } return true; }`,
    brute: `function isBipartite(graph) { const n = graph.length; for (let mask = 0; mask < 1 << n; mask++) { let ok = true; for (let u = 0; u < n && ok; u++) for (const v of graph[u]) if (((mask >> u) & 1) === ((mask >> v) & 1)) { ok = false; break; } if (ok) return true; } return false; }`,
    fuzz: ggen(`const n = __r(rand, 1, 9), g = Array.from({ length: n }, () => []); for (const [a, b] of __edges(rand, n, __r(rand, 0, n + 1))) { g[a].push(b); g[b].push(a); } return [g.map((l) => l.sort((x, y) => x - y))];`),
    examples: [[[[1, 2, 3], [0, 2], [0, 1, 3], [0, 2]]], [[[1, 3], [0, 2], [1, 3], [0, 2]]]],
    edges: [
      ["single", [[[]]]],
      ["cycle", [[[1, 2], [0, 2], [0, 1]]], "An odd cycle can never be two-coloured."],
      ["boundary", [[[1], [0], [3, 4], [2, 4], [2, 3]]], "A good component and a triangle."],
    ],
  },
  {
    slug: "possible-bipartition",
    title: "Possible Bipartition",
    difficulty: "Medium",
    pattern: "Graphs (BFS/DFS)",
    fn: "possibleBipartition",
    params: [["n", "number"], ["dislikes", "number[][]"]],
    returns: "boolean",
    hints: [
      "People are nodes and each dislike is an edge between two people who must end up in different groups. That is a two-colouring question.",
      "Build the adjacency list (people are numbered from 1) and BFS-colour each component, failing on an edge whose ends share a colour.",
      "adj = adjacency list for 1 .. n from dislikes\ncolor = array of unset\nfor s in 1 .. n with color[s] unset:\n  color[s] = 0; queue = [s]\n  while queue not empty:\n    u = pop front\n    for v in adj[u]:\n      if color[v] is unset: color[v] = 1 - color[u]; push v\n      else if color[v] == color[u]: return false\nreturn true",
    ],
    reference: `function possibleBipartition(n, dislikes) { const adj = Array.from({ length: n + 1 }, () => []); for (const [a, b] of dislikes) { adj[a].push(b); adj[b].push(a); } const color = new Array(n + 1).fill(-1); for (let s = 1; s <= n; s++) { if (color[s] >= 0) continue; color[s] = 0; const q = [s]; for (let i = 0; i < q.length; i++) { const u = q[i]; for (const v of adj[u]) { if (color[v] < 0) { color[v] = 1 - color[u]; q.push(v); } else if (color[v] === color[u]) return false; } } } return true; }`,
    brute: `function possibleBipartition(n, dislikes) { for (let mask = 0; mask < 1 << n; mask++) if (dislikes.every(([a, b]) => ((mask >> (a - 1)) & 1) !== ((mask >> (b - 1)) & 1))) return true; return false; }`,
    fuzz: ggen(`const n = __r(rand, 1, 9); return [n, __edges(rand, n, __r(rand, 0, n + 1), 1)];`),
    examples: [[4, [[1, 2], [1, 3], [2, 4]]], [3, [[1, 2], [1, 3], [2, 3]]]],
    edges: [
      ["empty", [3, []]],
      ["single", [1, []]],
      ["cycle", [5, [[1, 2], [2, 3], [3, 4], [4, 5], [1, 5]]], "A 5-cycle is odd."],
    ],
  },
  {
    slug: "find-eventual-safe-states",
    title: "Find Eventual Safe States",
    difficulty: "Medium",
    pattern: "Graphs (BFS/DFS)",
    fn: "eventualSafeNodes",
    params: [["graph", GRID]],
    returns: "number[]",
    hints: [
      "A node is safe when every path from it ends at a terminal node, which means it can never reach a cycle.",
      "Reverse the edges and run Kahn's algorithm from the terminal nodes (out-degree 0): a node becomes safe once all of its out-edges lead to safe nodes. Return the safe nodes in increasing order.",
      "rev = reversed graph; out[u] = len(graph[u])\nqueue = nodes with out[u] == 0; safe = those nodes\nwhile queue not empty:\n  v = pop front\n  for u in rev[v]:\n    out[u] -= 1\n    if out[u] == 0: mark u safe; push u\nreturn safe nodes in increasing order",
    ],
    reference: `function eventualSafeNodes(graph) { const n = graph.length, rev = Array.from({ length: n }, () => []), out = graph.map((l) => l.length); graph.forEach((l, u) => l.forEach((v) => rev[v].push(u))); const q = [], safe = new Array(n).fill(false); for (let u = 0; u < n; u++) if (!out[u]) { q.push(u); safe[u] = true; } for (let i = 0; i < q.length; i++) for (const u of rev[q[i]]) if (--out[u] === 0) { safe[u] = true; q.push(u); } return safe.map((s, i) => (s ? i : -1)).filter((i) => i >= 0); }`,
    brute: `function eventualSafeNodes(graph) { const state = new Array(graph.length).fill(0); const dfs = (u) => { if (state[u]) return state[u] === 2; state[u] = 1; for (const v of graph[u]) if (!dfs(v)) return false; state[u] = 2; return true; }; return graph.map((_, i) => i).filter((i) => dfs(i)); }`,
    fuzz: ggen(`const n = __r(rand, 1, 8); return [Array.from({ length: n }, () => __shuffle(rand, Array.from({ length: n }, (_, i) => i)).slice(0, __r(rand, 0, 2)).sort((a, b) => a - b))];`),
    examples: [[[[1, 2], [2, 3], [5], [0], [5], [], []]], [[[1, 2, 3, 4], [1, 2], [3, 4], [0, 4], []]]],
    edges: [
      ["single", [[[]]]],
      ["cycle", [[[0]]], "A self-loop is never safe."],
      ["boundary", [[[1], [2], []]], "A chain into a terminal node: all safe."],
    ],
  },
  {
    slug: "course-schedule",
    title: "Course Schedule",
    difficulty: "Medium",
    pattern: "Graphs (BFS/DFS)",
    fn: "canFinish",
    params: [["numCourses", "number"], ["prerequisites", GRID]],
    returns: "boolean",
    hints: [
      "Courses are nodes and [a, b] is an edge b -> a. You can finish everything exactly when the graph has no cycle.",
      "Kahn's algorithm: count in-degrees, start from courses with none, and remove them one by one. If you remove all numCourses courses, there is no cycle.",
      "adj = edges b -> a; indeg[a] += 1 for each [a, b]\nqueue = courses with indeg 0; taken = 0\nwhile queue not empty:\n  u = pop front; taken += 1\n  for v in adj[u]:\n    indeg[v] -= 1\n    if indeg[v] == 0: push v\nreturn taken == numCourses",
    ],
    reference: `function canFinish(numCourses, prerequisites) { const n = numCourses; ${ADJ} const indeg = new Array(n).fill(0); for (const [a, b] of prerequisites) { adj[b].push(a); indeg[a]++; } const q = []; for (let i = 0; i < n; i++) if (!indeg[i]) q.push(i); for (let i = 0; i < q.length; i++) for (const v of adj[q[i]]) if (--indeg[v] === 0) q.push(v); return q.length === n; }`,
    brute: `function canFinish(numCourses, prerequisites) { const n = numCourses; ${ADJ} for (const [a, b] of prerequisites) adj[b].push(a); const state = new Array(n).fill(0); const cyc = (u) => { if (state[u] === 1) return true; if (state[u] === 2) return false; state[u] = 1; for (const v of adj[u]) if (cyc(v)) return true; state[u] = 2; return false; }; for (let i = 0; i < n; i++) if (cyc(i)) return false; return true; }`,
    fuzz: ggen(`const n = __r(rand, 1, 8), seen = {}, p = []; for (let i = 0; i < __r(rand, 0, n + 1); i++) { const a = __r(rand, 0, n - 1), b = __r(rand, 0, n - 1); if (a !== b && !seen[a + "," + b]) { seen[a + "," + b] = 1; p.push(rand() < 0.7 ? [Math.max(a, b), Math.min(a, b)] : [a, b]); } } return [n, p];`),
    examples: [[2, [[1, 0]]], [2, [[1, 0], [0, 1]]]],
    edges: [
      ["empty", [3, []]],
      ["cycle", [3, [[0, 1], [1, 2], [2, 0]]]],
      ["boundary", [4, [[1, 0], [2, 0], [3, 1], [3, 2]]], "A diamond shape is fine."],
    ],
  },
  {
    slug: "minimum-height-trees",
    title: "Minimum Height Trees",
    difficulty: "Medium",
    pattern: "Graphs (BFS/DFS)",
    fn: "findMinHeightTrees",
    params: [["n", "number"], ["edges", GRID]],
    returns: "number[]",
    compare: "unordered",
    hints: [
      "The best roots sit in the middle of the longest path, so there are at most two of them. Any order is accepted.",
      "Peel the tree like an onion: remove all current leaves (degree 1) at once, update degrees, and repeat until at most 2 nodes are left.",
      "if n == 1: return [0]\ndegree and adj from edges\nleaves = nodes with degree 1; left = n\nwhile left > 2:\n  left -= len(leaves)\n  next = []\n  for leaf in leaves:\n    for v in adj[leaf]:\n      degree[v] -= 1\n      if degree[v] == 1: next.append(v)\n  leaves = next\nreturn leaves",
    ],
    reference: `function findMinHeightTrees(n, edges) { if (n === 1) return [0]; ${ADJ} const deg = new Array(n).fill(0); for (const [a, b] of edges) { adj[a].push(b); adj[b].push(a); deg[a]++; deg[b]++; } let leaves = []; for (let i = 0; i < n; i++) if (deg[i] === 1) leaves.push(i); let left = n; while (left > 2) { left -= leaves.length; const next = []; for (const l of leaves) for (const v of adj[l]) if (--deg[v] === 1) next.push(v); leaves = next; } return leaves; }`,
    brute: `function findMinHeightTrees(n, edges) { ${ADJ} for (const [a, b] of edges) { adj[a].push(b); adj[b].push(a); } const h = (s) => { const d = new Array(n).fill(-1); d[s] = 0; const q = [s]; for (let i = 0; i < q.length; i++) for (const v of adj[q[i]]) if (d[v] < 0) { d[v] = d[q[i]] + 1; q.push(v); } return Math.max(...d); }; const hs = Array.from({ length: n }, (_, i) => h(i)), m = Math.min(...hs); return hs.map((x, i) => (x === m ? i : -1)).filter((i) => i >= 0); }`,
    fuzz: ggen(`const n = __r(rand, 1, 10); return [n, __shuffle(rand, __tree(rand, n))];`),
    examples: [[4, [[1, 0], [1, 2], [1, 3]]], [6, [[3, 0], [3, 1], [3, 2], [3, 4], [5, 4]]]],
    edges: [
      ["single", [1, []]],
      ["two", [2, [[0, 1]]], "Both nodes are centres."],
      ["boundary", [5, [[0, 1], [1, 2], [2, 3], [3, 4]]], "A path: the middle node."],
    ],
  },
  {
    slug: "parallel-courses-iii",
    title: "Parallel Courses III",
    difficulty: "Hard",
    pattern: "Advanced Graphs",
    fn: "minimumTime",
    params: [["n", "number"], ["relations", GRID], ["time", "number[]"]],
    returns: "number",
    hints: [
      "With unlimited parallel work, a course finishes at its own time plus the latest finish among its prerequisites. The answer is the latest finish overall.",
      "Topological order (Kahn) over the DAG: finish[v] = time[v] + max finish of its prerequisites. Relax each edge as you pop nodes.",
      "adj = edges prev -> next (courses numbered from 1); indeg counts\nfinish[v] = time[v - 1] for every course\nqueue = courses with indeg 0\nwhile queue not empty:\n  u = pop front\n  for v in adj[u]:\n    finish[v] = max(finish[v], finish[u] + time[v - 1])\n    indeg[v] -= 1\n    if indeg[v] == 0: push v\nreturn max of finish",
    ],
    reference: `function minimumTime(n, relations, time) { const adj = Array.from({ length: n + 1 }, () => []), indeg = new Array(n + 1).fill(0); for (const [a, b] of relations) { adj[a].push(b); indeg[b]++; } const fin = [0, ...time], q = []; for (let i = 1; i <= n; i++) if (!indeg[i]) q.push(i); for (let i = 0; i < q.length; i++) { const u = q[i]; for (const v of adj[u]) { fin[v] = Math.max(fin[v], fin[u] + time[v - 1]); if (--indeg[v] === 0) q.push(v); } } return Math.max(...fin); }`,
    brute: `function minimumTime(n, relations, time) { const pre = Array.from({ length: n + 1 }, () => []); for (const [a, b] of relations) pre[b].push(a); const memo = {}; const f = (v) => { if (memo[v] !== undefined) return memo[v]; let m = 0; for (const u of pre[v]) m = Math.max(m, f(u)); return (memo[v] = m + time[v - 1]); }; let best = 0; for (let v = 1; v <= n; v++) best = Math.max(best, f(v)); return best; }`,
    fuzz: ggen(`const n = __r(rand, 1, 9), order = __shuffle(rand, Array.from({ length: n }, (_, i) => i + 1)), seen = {}, rel = []; for (let i = 0; i < __r(rand, 0, 2 * n); i++) { const x = __r(rand, 0, n - 1), y = __r(rand, 0, n - 1); if (x < y && !seen[x + "," + y]) { seen[x + "," + y] = 1; rel.push([order[x], order[y]]); } } return [n, rel, __arr(rand, n, 1, 9)];`),
    examples: [[3, [[1, 3], [2, 3]], [3, 2, 5]], [5, [[1, 5], [2, 5], [3, 5], [3, 4], [4, 5]], [1, 2, 3, 4, 5]]],
    edges: [
      ["single", [1, [], [7]]],
      ["empty", [3, [], [4, 9, 2]], "No relations: the slowest course decides."],
      ["boundary", [4, [[1, 2], [2, 3], [3, 4]], [1, 1, 1, 1]], "A chain: times add up."],
    ],
  },
  {
    slug: "network-delay-time",
    title: "Network Delay Time",
    difficulty: "Medium",
    pattern: "Advanced Graphs",
    fn: "networkDelayTime",
    params: [["times", GRID], ["n", "number"], ["k", "number"]],
    returns: "number",
    hints: [
      "The signal reaches each node along its shortest path from k, so the answer is the largest shortest-path distance (or -1 if a node is unreachable).",
      "Dijkstra from k over the directed, non-negative weighted edges, then take the maximum distance.",
      "dist = infinity for 1 .. n; dist[k] = 0\nheap = [(0, k)]\nwhile heap not empty:\n  (d, u) = pop smallest\n  if d > dist[u]: continue\n  for (v, w) in adj[u]:\n    if d + w < dist[v]: dist[v] = d + w; push (dist[v], v)\nans = max of dist\nreturn -1 if ans is infinity else ans",
    ],
    reference: `function networkDelayTime(times, n, k) { const adj = Array.from({ length: n + 1 }, () => []); for (const [u, v, w] of times) adj[u].push([v, w]); const dist = new Array(n + 1).fill(Infinity), done = new Array(n + 1).fill(false); dist[k] = 0; for (let it = 0; it < n; it++) { let u = -1; for (let i = 1; i <= n; i++) if (!done[i] && (u < 0 || dist[i] < dist[u])) u = i; if (dist[u] === Infinity) break; done[u] = true; for (const [v, w] of adj[u]) if (dist[u] + w < dist[v]) dist[v] = dist[u] + w; } const ans = Math.max(...dist.slice(1)); return ans === Infinity ? -1 : ans; }`,
    brute: `function networkDelayTime(times, n, k) { const d = new Array(n + 1).fill(Infinity); d[k] = 0; for (let i = 0; i < n; i++) for (const [u, v, w] of times) if (d[u] + w < d[v]) d[v] = d[u] + w; const ans = Math.max(...d.slice(1)); return ans === Infinity ? -1 : ans; }`,
    fuzz: ggen(`const n = __r(rand, 1, 7), seen = {}, t = []; for (let i = 0; i < __r(rand, 0, 2 * n); i++) { const u = __r(rand, 1, n), v = __r(rand, 1, n); if (u !== v && !seen[u + "," + v]) { seen[u + "," + v] = 1; t.push([u, v, __r(rand, 0, 9)]); } } return [t, n, __r(rand, 1, n)];`),
    examples: [[[[2, 1, 1], [2, 3, 1], [3, 4, 1]], 4, 2], [[[1, 2, 1]], 2, 1], [[[1, 2, 1]], 2, 2]],
    edges: [
      ["single", [[], 1, 1]],
      ["boundary", [[[1, 2, 5], [1, 3, 1], [3, 2, 1]], 3, 1], "The indirect route is faster."],
      ["zeros", [[[1, 2, 0], [2, 3, 0]], 3, 1], "Zero-weight edges."],
    ],
  },
  {
    slug: "path-with-minimum-effort",
    title: "Path With Minimum Effort",
    difficulty: "Medium",
    pattern: "Advanced Graphs",
    fn: "minimumEffortPath",
    params: [["heights", GRID]],
    returns: "number",
    hints: [
      "A path's cost is its biggest single step, not the sum. You want the path from top-left to bottom-right whose biggest step is smallest.",
      "Dijkstra where a path's 'distance' is the max absolute height difference along it: relax a neighbour with max(effort so far, step).",
      "effort = grid of infinity; effort[0][0] = 0\nheap = [(0, 0, 0)]\nwhile heap not empty:\n  (e, r, c) = pop smallest\n  if (r, c) is the bottom-right: return e\n  if e > effort[r][c]: continue\n  for each neighbour (y, x):\n    ne = max(e, |heights[y][x] - heights[r][c]|)\n    if ne < effort[y][x]: effort[y][x] = ne; push (ne, y, x)",
    ],
    reference: `function minimumEffortPath(heights) { const R = heights.length, C = heights[0].length, eff = new Array(R * C).fill(Infinity), done = new Array(R * C).fill(false); eff[0] = 0; for (;;) { let u = -1; for (let i = 0; i < R * C; i++) if (!done[i] && (u < 0 || eff[i] < eff[u])) u = i; if (u === R * C - 1) return eff[u]; done[u] = true; const r = Math.floor(u / C), c = u % C; for (const [dr, dc] of ${DIRS}) { const y = r + dr, x = c + dc; if (y < 0 || x < 0 || y >= R || x >= C) continue; const ne = Math.max(eff[u], Math.abs(heights[y][x] - heights[r][c])); if (ne < eff[y * C + x]) eff[y * C + x] = ne; } } }`,
    brute: `function minimumEffortPath(heights) { const R = heights.length, C = heights[0].length; const can = (lim) => { const seen = new Set([0]), q = [[0, 0]]; for (let i = 0; i < q.length; i++) { const [r, c] = q[i]; if (r === R - 1 && c === C - 1) return true; for (const [dr, dc] of ${DIRS}) { const y = r + dr, x = c + dc; if (y >= 0 && x >= 0 && y < R && x < C && !seen.has(y * C + x) && Math.abs(heights[y][x] - heights[r][c]) <= lim) { seen.add(y * C + x); q.push([y, x]); } } } return false; }; let e = 0; while (!can(e)) e++; return e; }`,
    fuzz: ggen(`const r = __r(rand, 1, 5), c = __r(rand, 1, 5); return [Array.from({ length: r }, () => __arr(rand, c, 1, 12))];`),
    examples: [[[[1, 2, 2], [3, 8, 2], [5, 3, 5]]], [[[1, 2, 3], [3, 8, 4], [5, 3, 5]]], [[[1, 2, 1, 1, 1], [1, 2, 1, 2, 1], [1, 2, 1, 2, 1], [1, 2, 1, 2, 1], [1, 1, 1, 2, 1]]]],
    edges: [
      ["single", [[[5]]]],
      ["all-equal", [[[3, 3], [3, 3]]]],
      ["boundary", [[[1, 10], [2, 3]]], "Going around beats the direct jump."],
    ],
  },
  {
    slug: "cheapest-flights-within-k-stops",
    title: "Cheapest Flights Within K Stops",
    difficulty: "Medium",
    pattern: "Advanced Graphs",
    fn: "findCheapestPrice",
    params: [["n", "number"], ["flights", GRID], ["src", "number"], ["dst", "number"], ["k", "number"]],
    returns: "number",
    hints: [
      "At most k stops means at most k + 1 flights. Plain Dijkstra ignores that limit, so it can pick a cheap route with too many stops.",
      "Bellman-Ford for exactly k + 1 rounds: each round relaxes every flight using a copy of last round's prices, so a round adds at most one flight.",
      "price = infinity everywhere; price[src] = 0\nrepeat k + 1 times:\n  next = copy of price\n  for (u, v, w) in flights:\n    if price[u] + w < next[v]: next[v] = price[u] + w\n  price = next\nreturn -1 if price[dst] is infinity else price[dst]",
    ],
    reference: `function findCheapestPrice(n, flights, src, dst, k) { let p = new Array(n).fill(Infinity); p[src] = 0; for (let i = 0; i <= k; i++) { const next = p.slice(); for (const [u, v, w] of flights) if (p[u] + w < next[v]) next[v] = p[u] + w; p = next; } return p[dst] === Infinity ? -1 : p[dst]; }`,
    brute: `function findCheapestPrice(n, flights, src, dst, k) { ${ADJ} for (const [u, v, w] of flights) adj[u].push([v, w]); let best = Infinity; const go = (u, cost, legs, seen) => { if (u === dst) { best = Math.min(best, cost); return; } if (legs === k + 1) return; for (const [v, w] of adj[u]) if (!seen.has(v)) { seen.add(v); go(v, cost + w, legs + 1, seen); seen.delete(v); } }; go(src, 0, 0, new Set([src])); return best === Infinity ? -1 : best; }`,
    fuzz: ggen(`const n = __r(rand, 2, 6), seen = {}, f = []; for (let i = 0; i < __r(rand, 1, 2 * n); i++) { const u = __r(rand, 0, n - 1), v = __r(rand, 0, n - 1); if (u !== v && !seen[u + "," + v]) { seen[u + "," + v] = 1; f.push([u, v, __r(rand, 1, 20)]); } } const s = __r(rand, 0, n - 1); let d = __r(rand, 0, n - 1); while (d === s) d = __r(rand, 0, n - 1); return [n, f, s, d, __r(rand, 0, n - 1)];`),
    examples: [[4, [[0, 1, 100], [1, 2, 100], [2, 0, 100], [1, 3, 600], [2, 3, 200]], 0, 3, 1], [3, [[0, 1, 100], [1, 2, 100], [0, 2, 500]], 0, 2, 1], [3, [[0, 1, 100], [1, 2, 100], [0, 2, 500]], 0, 2, 0]],
    edges: [
      ["no-answer", [3, [[0, 1, 5]], 0, 2, 1]],
      ["boundary", [4, [[0, 1, 1], [1, 2, 1], [2, 3, 1], [0, 3, 10]], 0, 3, 1], "The cheap route needs too many stops."],
      ["two", [2, [[0, 1, 7]], 0, 1, 0]],
    ],
  },
  {
    slug: "number-of-ways-to-arrive-at-destination",
    title: "Number of Ways to Arrive at Destination",
    difficulty: "Medium",
    pattern: "Advanced Graphs",
    fn: "countPaths",
    params: [["n", "number"], ["roads", GRID]],
    returns: "number",
    hints: [
      "Count how many different shortest paths go from 0 to n - 1 (modulo 1e9 + 7).",
      "Dijkstra that also tracks ways[v]: a strictly shorter route resets ways[v] to ways[u]; an equally short one adds ways[u].",
      "dist = infinity; dist[0] = 0; ways[0] = 1\nheap = [(0, 0)]\nwhile heap not empty:\n  (d, u) = pop smallest\n  if d > dist[u]: continue\n  for (v, w) in adj[u]:\n    if d + w < dist[v]: dist[v] = d + w; ways[v] = ways[u]; push (dist[v], v)\n    else if d + w == dist[v]: ways[v] = (ways[v] + ways[u]) mod M\nreturn ways[n - 1]",
    ],
    reference: `function countPaths(n, roads) { const M = 1000000007; ${ADJ} for (const [u, v, w] of roads) { adj[u].push([v, w]); adj[v].push([u, w]); } const dist = new Array(n).fill(Infinity), ways = new Array(n).fill(0), done = new Array(n).fill(false); dist[0] = 0; ways[0] = 1; for (let it = 0; it < n; it++) { let u = -1; for (let i = 0; i < n; i++) if (!done[i] && (u < 0 || dist[i] < dist[u])) u = i; if (dist[u] === Infinity) break; done[u] = true; for (const [v, w] of adj[u]) { if (dist[u] + w < dist[v]) { dist[v] = dist[u] + w; ways[v] = ways[u]; } else if (dist[u] + w === dist[v]) ways[v] = (ways[v] + ways[u]) % M; } } return ways[n - 1]; }`,
    brute: `function countPaths(n, roads) { const d = Array.from({ length: n }, (_, i) => Array.from({ length: n }, (_, j) => (i === j ? 0 : Infinity))); for (const [u, v, w] of roads) { d[u][v] = Math.min(d[u][v], w); d[v][u] = Math.min(d[v][u], w); } for (let m = 0; m < n; m++) for (let i = 0; i < n; i++) for (let j = 0; j < n; j++) if (d[i][m] + d[m][j] < d[i][j]) d[i][j] = d[i][m] + d[m][j]; const order = Array.from({ length: n }, (_, i) => i).sort((a, b) => d[0][a] - d[0][b]), ways = new Array(n).fill(0); ways[0] = 1; for (const v of order) { if (v === 0) continue; for (const [a, b, w] of roads) { if (b === v && d[0][a] + w === d[0][v]) ways[v] += ways[a]; if (a === v && d[0][b] + w === d[0][v]) ways[v] += ways[b]; } ways[v] %= 1000000007; } return ways[n - 1]; }`,
    fuzz: ggen(`const n = __r(rand, 1, 7), es = __tree(rand, n).concat(__edges(rand, n, __r(rand, 0, n))), seen = {}, roads = []; for (const [a, b] of es) { const k = Math.min(a, b) + "," + Math.max(a, b); if (!seen[k]) { seen[k] = 1; roads.push([a, b, __r(rand, 1, 4)]); } } return [n, roads];`),
    examples: [[7, [[0, 6, 7], [0, 1, 2], [1, 2, 3], [1, 3, 3], [6, 3, 3], [3, 5, 1], [6, 5, 1], [2, 5, 1], [0, 4, 5], [4, 6, 2]]], [2, [[1, 0, 10]]]],
    edges: [
      ["single", [1, []], "Already at the destination: one way."],
      ["boundary", [4, [[0, 1, 1], [0, 2, 1], [1, 3, 1], [2, 3, 1]]], "Two equal shortest paths."],
      ["duplicates", [3, [[0, 1, 1], [1, 2, 1], [0, 2, 2]]], "A direct road ties with the two-step route."],
    ],
  },
  {
    slug: "find-the-city-with-the-smallest-number-of-neighbors-at-a-threshold-distance",
    title: "Find the City With the Smallest Number of Neighbors at a Threshold Distance",
    difficulty: "Medium",
    pattern: "Advanced Graphs",
    fn: "findTheCity",
    params: [["n", "number"], ["edges", GRID], ["distanceThreshold", "number"]],
    returns: "number",
    hints: [
      "You need shortest distances between every pair of cities, then count for each city how many others are within the threshold.",
      "Floyd-Warshall (n is small) fills the all-pairs table. Pick the city with the fewest reachable neighbours, breaking ties by the larger index.",
      "d = n x n table: 0 on the diagonal, edge weights, infinity elsewhere\nfor m in 0 .. n - 1:\n  for i, j: d[i][j] = min(d[i][j], d[i][m] + d[m][j])\nbest = -1; fewest = infinity\nfor i in 0 .. n - 1:\n  cnt = number of j != i with d[i][j] <= distanceThreshold\n  if cnt <= fewest: fewest = cnt; best = i\nreturn best",
    ],
    reference: `function findTheCity(n, edges, distanceThreshold) { const d = Array.from({ length: n }, (_, i) => Array.from({ length: n }, (_, j) => (i === j ? 0 : Infinity))); for (const [u, v, w] of edges) { d[u][v] = Math.min(d[u][v], w); d[v][u] = Math.min(d[v][u], w); } for (let m = 0; m < n; m++) for (let i = 0; i < n; i++) for (let j = 0; j < n; j++) if (d[i][m] + d[m][j] < d[i][j]) d[i][j] = d[i][m] + d[m][j]; let best = -1, few = Infinity; for (let i = 0; i < n; i++) { let c = 0; for (let j = 0; j < n; j++) if (j !== i && d[i][j] <= distanceThreshold) c++; if (c <= few) { few = c; best = i; } } return best; }`,
    brute: `function findTheCity(n, edges, distanceThreshold) { const counts = []; for (let s = 0; s < n; s++) { const d = new Array(n).fill(Infinity); d[s] = 0; for (let i = 0; i < n; i++) for (const [u, v, w] of edges) { if (d[u] + w < d[v]) d[v] = d[u] + w; if (d[v] + w < d[u]) d[u] = d[v] + w; } counts.push(d.filter((x, j) => j !== s && x <= distanceThreshold).length); } const m = Math.min(...counts); return counts.lastIndexOf(m); }`,
    fuzz: ggen(`const n = __r(rand, 2, 7); return [n, __edges(rand, n, __r(rand, 1, 2 * n)).map(([a, b]) => [a, b, __r(rand, 1, 9)]), __r(rand, 1, 15)];`),
    examples: [[4, [[0, 1, 3], [1, 2, 1], [1, 3, 4], [2, 3, 1]], 4], [5, [[0, 1, 2], [0, 4, 8], [1, 2, 3], [1, 4, 2], [2, 3, 1], [3, 4, 1]], 2]],
    edges: [
      ["two", [2, [[0, 1, 5]], 4], "Nobody is reachable: the larger index wins the tie."],
      ["boundary", [3, [[0, 1, 2], [1, 2, 2]], 2], "Exactly at the threshold counts."],
      ["extremes", [3, [[0, 1, 1], [1, 2, 1], [0, 2, 1]], 100]],
    ],
  },
  {
    slug: "swim-in-rising-water",
    title: "Swim in Rising Water",
    difficulty: "Hard",
    pattern: "Advanced Graphs",
    fn: "swimInWater",
    params: [["grid", GRID]],
    returns: "number",
    hints: [
      "At time t you can stand on any cell with height <= t. The answer is the smallest t at which a path from top-left to bottom-right exists: a minimax path.",
      "Dijkstra where the cost of a path is the highest cell on it (or binary search on t with a BFS).",
      "best = grid of infinity; best[0][0] = grid[0][0]\nheap = [(grid[0][0], 0, 0)]\nwhile heap not empty:\n  (t, r, c) = pop smallest\n  if (r, c) is the bottom-right: return t\n  for each neighbour (y, x):\n    nt = max(t, grid[y][x])\n    if nt < best[y][x]: best[y][x] = nt; push (nt, y, x)",
    ],
    reference: `function swimInWater(grid) { const n = grid.length, best = new Array(n * n).fill(Infinity), done = new Array(n * n).fill(false); best[0] = grid[0][0]; for (;;) { let u = -1; for (let i = 0; i < n * n; i++) if (!done[i] && (u < 0 || best[i] < best[u])) u = i; if (u === n * n - 1) return best[u]; done[u] = true; const r = Math.floor(u / n), c = u % n; for (const [dr, dc] of ${DIRS}) { const y = r + dr, x = c + dc; if (y < 0 || x < 0 || y >= n || x >= n) continue; const nt = Math.max(best[u], grid[y][x]); if (nt < best[y * n + x]) best[y * n + x] = nt; } } }`,
    brute: `function swimInWater(grid) { const n = grid.length; for (let t = 0; ; t++) { if (grid[0][0] > t) continue; const seen = new Set([0]), q = [[0, 0]]; for (let i = 0; i < q.length; i++) { const [r, c] = q[i]; if (r === n - 1 && c === n - 1) return t; for (const [dr, dc] of ${DIRS}) { const y = r + dr, x = c + dc; if (y >= 0 && x >= 0 && y < n && x < n && !seen.has(y * n + x) && grid[y][x] <= t) { seen.add(y * n + x); q.push([y, x]); } } } } }`,
    fuzz: ggen(`const n = __r(rand, 1, 5), v = __shuffle(rand, Array.from({ length: n * n }, (_, i) => i)); return [Array.from({ length: n }, (_, r) => v.slice(r * n, r * n + n))];`),
    examples: [[[[0, 2], [1, 3]]], [[[0, 1, 2, 3, 4], [24, 23, 22, 21, 5], [12, 13, 14, 15, 16], [11, 17, 18, 19, 20], [10, 9, 8, 7, 6]]]],
    edges: [
      ["single", [[[0]]]],
      ["boundary", [[[3, 2], [0, 1]]], "The start is the highest cell."],
      ["sorted", [[[0, 1, 2], [3, 4, 5], [6, 7, 8]]], "The end is the highest cell."],
    ],
  },
  {
    slug: "min-cost-to-connect-all-points",
    title: "Min Cost to Connect All Points",
    difficulty: "Medium",
    pattern: "Advanced Graphs",
    fn: "minCostConnectPoints",
    params: [["points", GRID]],
    returns: "number",
    hints: [
      "Every pair of points is a possible edge costing their Manhattan distance; you want a minimum spanning tree.",
      "Prim's algorithm on the dense graph in O(n^2): keep each outside point's cheapest link to the tree, add the cheapest point, and update the links.",
      "inTree = n false; cost = n infinity; cost[0] = 0; total = 0\nrepeat n times:\n  u = the point not in the tree with the smallest cost\n  inTree[u] = true; total += cost[u]\n  for each v not in the tree:\n    cost[v] = min(cost[v], |xu - xv| + |yu - yv|)\nreturn total",
    ],
    reference: `function minCostConnectPoints(points) { const n = points.length, inT = new Array(n).fill(false), cost = new Array(n).fill(Infinity); cost[0] = 0; let total = 0; for (let it = 0; it < n; it++) { let u = -1; for (let i = 0; i < n; i++) if (!inT[i] && (u < 0 || cost[i] < cost[u])) u = i; inT[u] = true; total += cost[u]; for (let v = 0; v < n; v++) if (!inT[v]) cost[v] = Math.min(cost[v], Math.abs(points[u][0] - points[v][0]) + Math.abs(points[u][1] - points[v][1])); } return total; }`,
    brute: `function minCostConnectPoints(points) { const n = points.length, es = []; for (let i = 0; i < n; i++) for (let j = i + 1; j < n; j++) es.push([Math.abs(points[i][0] - points[j][0]) + Math.abs(points[i][1] - points[j][1]), i, j]); es.sort((a, b) => a[0] - b[0]); const p = Array.from({ length: n }, (_, i) => i), f = (x) => (p[x] === x ? x : (p[x] = f(p[x]))); let total = 0; for (const [w, a, b] of es) if (f(a) !== f(b)) { p[f(a)] = f(b); total += w; } return total; }`,
    fuzz: ggen(`const pts = [], seen = {}; for (let i = 0; i < __r(rand, 1, 8); i++) { const x = __r(rand, -10, 10), y = __r(rand, -10, 10); if (!seen[x + "," + y]) { seen[x + "," + y] = 1; pts.push([x, y]); } } return [pts];`),
    examples: [[[[0, 0], [2, 2], [3, 10], [5, 2], [7, 0]]], [[[3, 12], [-2, 5], [-4, 1]]]],
    edges: [
      ["single", [[[0, 0]]]],
      ["two", [[[1, 1], [4, 5]]]],
      ["negatives", [[[-1, -1], [-3, -2], [0, -5]]]],
    ],
  },
  {
    slug: "redundant-connection",
    title: "Redundant Connection",
    difficulty: "Medium",
    pattern: "Graphs (BFS/DFS)",
    fn: "findRedundantConnection",
    params: [["edges", GRID]],
    returns: "number[]",
    hints: [
      "A tree plus one extra edge has exactly one cycle. Removing any edge of that cycle leaves a tree; return the one that appears last in the input.",
      "Union-find over the edges in order: the first edge whose two ends are already connected closes the cycle, and it is the last cycle edge in the input.",
      "parent[i] = i for 1 .. n\nfind(x): follow parent links to the root (compress the path)\nfor (a, b) in edges:\n  if find(a) == find(b): return [a, b]\n  parent[find(a)] = find(b)",
    ],
    reference: `function findRedundantConnection(edges) { const p = Array.from({ length: edges.length + 1 }, (_, i) => i), f = (x) => (p[x] === x ? x : (p[x] = f(p[x]))); for (const [a, b] of edges) { if (f(a) === f(b)) return [a, b]; p[f(a)] = f(b); } return []; }`,
    brute: `function findRedundantConnection(edges) { const n = edges.length; for (let skip = n - 1; skip >= 0; skip--) { const adj = Array.from({ length: n + 1 }, () => []); edges.forEach(([a, b], i) => { if (i !== skip) { adj[a].push(b); adj[b].push(a); } }); const seen = new Set([1]), st = [1]; while (st.length) for (const v of adj[st.pop()]) if (!seen.has(v)) { seen.add(v); st.push(v); } if (seen.size === n) return edges[skip]; } return []; }`,
    fuzz: ggen(`const n = __r(rand, 3, 9), t = __tree(rand, n, 1), have = new Set(t.map(([a, b]) => Math.min(a, b) + "," + Math.max(a, b))); for (;;) { const a = __r(rand, 1, n), b = __r(rand, 1, n); if (a !== b && !have.has(Math.min(a, b) + "," + Math.max(a, b))) { t.push([Math.min(a, b), Math.max(a, b)]); break; } } return [__shuffle(rand, t).map(([a, b]) => [Math.min(a, b), Math.max(a, b)])];`),
    examples: [[[[1, 2], [1, 3], [2, 3]]], [[[1, 2], [2, 3], [3, 4], [1, 4], [1, 5]]]],
    edges: [
      ["boundary", [[[1, 4], [3, 4], [1, 3], [1, 2], [4, 5]]], "The cycle closes in the middle of the list."],
      ["cycle", [[[1, 2], [2, 3], [3, 4], [4, 5], [1, 5]]], "Every edge is on the cycle: return the last one."],
      ["order", [[[2, 3], [1, 2], [1, 3]]]],
    ],
  },
  {
    slug: "number-of-operations-to-make-network-connected",
    title: "Number of Operations to Make Network Connected",
    difficulty: "Medium",
    pattern: "Advanced Graphs",
    fn: "makeConnected",
    params: [["n", "number"], ["connections", GRID]],
    returns: "number",
    hints: [
      "Connecting n computers needs at least n - 1 cables. If you have that many, each move of a spare cable joins two components.",
      "Return -1 when there are fewer than n - 1 cables; otherwise count components with union-find and return components - 1.",
      "if len(connections) < n - 1: return -1\nparent[i] = i\ncomponents = n\nfor (a, b) in connections:\n  if find(a) != find(b): union them; components -= 1\nreturn components - 1",
    ],
    reference: `function makeConnected(n, connections) { if (connections.length < n - 1) return -1; const p = Array.from({ length: n }, (_, i) => i), f = (x) => (p[x] === x ? x : (p[x] = f(p[x]))); let comp = n; for (const [a, b] of connections) if (f(a) !== f(b)) { p[f(a)] = f(b); comp--; } return comp - 1; }`,
    brute: `function makeConnected(n, connections) { if (connections.length < n - 1) return -1; ${ADJ} for (const [a, b] of connections) { adj[a].push(b); adj[b].push(a); } const seen = new Array(n).fill(false); let comp = 0; for (let s = 0; s < n; s++) { if (seen[s]) continue; comp++; const st = [s]; seen[s] = true; while (st.length) for (const v of adj[st.pop()]) if (!seen[v]) { seen[v] = true; st.push(v); } } return comp - 1; }`,
    fuzz: ggen(`const n = __r(rand, 1, 9); return [n, __edges(rand, n, __r(rand, 0, n + 2))];`),
    examples: [[4, [[0, 1], [0, 2], [1, 2]]], [6, [[0, 1], [0, 2], [0, 3], [1, 2], [1, 3]]], [6, [[0, 1], [0, 2], [0, 3], [1, 2]]]],
    edges: [
      ["single", [1, []]],
      ["no-answer", [3, [[0, 1]]], "Too few cables."],
      ["boundary", [3, [[0, 1], [1, 2]]], "Already connected."],
    ],
  },
  {
    slug: "accounts-merge",
    title: "Accounts Merge",
    difficulty: "Medium",
    pattern: "Graphs (BFS/DFS)",
    fn: "accountsMerge",
    params: [["accounts", "string[][]"]],
    returns: "string[][]",
    compare: "unordered-outer",
    hints: [
      "Two accounts belong to the same person when they share any email. Emails are the nodes; each account links its emails together.",
      "Union-find over emails (union every email with the first email of its account). Group emails by root, sort each group, and put the owner's name in front. Accounts may come back in any order.",
      "owner = map email -> name\nfor each account: union every email with the account's first email\ngroups = map root -> list of emails\nfor each email: append it to groups[find(email)]\nreturn [owner[g[0]]] + sorted(g) for each group g",
    ],
    reference: `function accountsMerge(accounts) { const p = new Map(), owner = new Map(); const f = (x) => { while (p.get(x) !== x) { p.set(x, p.get(p.get(x))); x = p.get(x); } return x; }; for (const [name, ...emails] of accounts) for (const e of emails) { if (!p.has(e)) p.set(e, e); owner.set(e, name); p.set(f(e), f(emails[0])); } const groups = new Map(); for (const e of p.keys()) { const r = f(e); if (!groups.has(r)) groups.set(r, []); groups.get(r).push(e); } return [...groups.values()].map((g) => [owner.get(g[0]), ...g.sort()]); }`,
    brute: `function accountsMerge(accounts) { let groups = accounts.map(([name, ...emails]) => ({ name, emails: new Set(emails) })); let merged = true; while (merged) { merged = false; outer: for (let i = 0; i < groups.length; i++) for (let j = i + 1; j < groups.length; j++) if ([...groups[j].emails].some((e) => groups[i].emails.has(e))) { for (const e of groups[j].emails) groups[i].emails.add(e); groups.splice(j, 1); merged = true; break outer; } } return groups.map((g) => [g.name, ...[...g.emails].sort()]); }`,
    fuzz: ggen(`const names = ["John", "Mary", "Alex"], pool = "abcdefgh".split("").map((c) => c + "@mail.com"), who = {}; for (const e of pool) who[e] = __pick(rand, names); const acc = []; for (let i = 0; i < __r(rand, 1, 6); i++) { const name = __pick(rand, names), mine = pool.filter((e) => who[e] === name); if (!mine.length) continue; acc.push([name, ...__shuffle(rand, mine.slice()).slice(0, __r(rand, 1, Math.min(3, mine.length)))]); } if (!acc.length) acc.push(["John", "z@mail.com"]); return [acc];`),
    examples: [[[["John", "johnsmith@mail.com", "john_newyork@mail.com"], ["John", "johnsmith@mail.com", "john00@mail.com"], ["Mary", "mary@mail.com"], ["John", "johnnybravo@mail.com"]]], [[["Gabe", "Gabe0@m.co", "Gabe3@m.co", "Gabe1@m.co"], ["Kevin", "Kevin3@m.co", "Kevin5@m.co", "Kevin0@m.co"]]]],
    edges: [
      ["single", [[["Ann", "b@x.com", "a@x.com"]]], "Emails must come back sorted."],
      ["duplicates", [[["Bob", "b@x.com"], ["Bob", "b@x.com"]]], "The same account twice."],
      ["boundary", [[["Sam", "a@x.com", "b@x.com"], ["Sam", "c@x.com"], ["Sam", "b@x.com", "c@x.com"]]], "The third account links the first two."],
    ],
  },
  {
    slug: "most-stones-removed-with-same-row-or-column",
    title: "Most Stones Removed with Same Row or Column",
    difficulty: "Medium",
    pattern: "Advanced Graphs",
    fn: "removeStones",
    params: [["stones", GRID]],
    returns: "number",
    hints: [
      "Stones sharing a row or column are connected. Inside one connected group you can always remove every stone but one.",
      "The answer is stones - components. Union-find on rows and columns: union row r with column c (offset the columns so they do not clash) for every stone.",
      "parent = empty map\nfor (r, c) in stones: union(r, c + 10001)\ncomponents = number of distinct roots among the rows and columns used\nreturn len(stones) - components",
    ],
    reference: `function removeStones(stones) { const p = new Map(); const f = (x) => { if (!p.has(x)) p.set(x, x); while (p.get(x) !== x) { p.set(x, p.get(p.get(x))); x = p.get(x); } return x; }; for (const [r, c] of stones) p.set(f(r), f(c + 10001)); const roots = new Set(); for (const k of p.keys()) roots.add(f(k)); return stones.length - roots.size; }`,
    brute: `function removeStones(stones) { const n = stones.length, seen = new Array(n).fill(false); let comp = 0; for (let s = 0; s < n; s++) { if (seen[s]) continue; comp++; seen[s] = true; const st = [s]; while (st.length) { const u = st.pop(); for (let v = 0; v < n; v++) if (!seen[v] && (stones[v][0] === stones[u][0] || stones[v][1] === stones[u][1])) { seen[v] = true; st.push(v); } } } return n - comp; }`,
    fuzz: ggen(`const pts = [], seen = {}; for (let i = 0; i < __r(rand, 1, 9); i++) { const x = __r(rand, 0, 5), y = __r(rand, 0, 5); if (!seen[x + "," + y]) { seen[x + "," + y] = 1; pts.push([x, y]); } } return [pts];`),
    examples: [[[[0, 0], [0, 1], [1, 0], [1, 2], [2, 1], [2, 2]]], [[[0, 0], [0, 2], [1, 1], [2, 0], [2, 2]]], [[[0, 0]]]],
    edges: [
      ["two", [[[0, 0], [1, 1]]], "No shared row or column."],
      ["boundary", [[[0, 0], [0, 5], [5, 5]]], "Linked through a corner stone."],
      ["all-equal", [[[3, 0], [3, 1], [3, 2], [3, 3]]], "One row."],
    ],
  },
  {
    slug: "making-a-large-island",
    title: "Making A Large Island",
    difficulty: "Hard",
    pattern: "Advanced Graphs",
    fn: "largestIsland",
    params: [["grid", GRID]],
    returns: "number",
    hints: [
      "Flipping one 0 joins the islands around it. Re-running a search for every 0 is O(n^4); precompute each island's size once.",
      "Label every island with an id and record its size. For each 0, add 1 plus the sizes of the distinct island ids among its 4 neighbours. If there is no 0, the answer is n * n.",
      "id = 2; size = map\nfor each land cell not yet labelled: size[id] = flood(cell, id); id += 1\nbest = max of size values, or 0 if none\nfor each cell with grid[r][c] == 0:\n  ids = distinct labels of the 4 neighbours\n  best = max(best, 1 + sum of size[i] for i in ids)\nreturn best",
    ],
    reference: `function largestIsland(grid) { const n = grid.length, size = {}; let id = 2; const flood = (r, c) => { if (r < 0 || c < 0 || r >= n || c >= n || grid[r][c] !== 1) return 0; grid[r][c] = id; let s = 1; for (const [dr, dc] of ${DIRS}) s += flood(r + dr, c + dc); return s; }; for (let r = 0; r < n; r++) for (let c = 0; c < n; c++) if (grid[r][c] === 1) { size[id] = flood(r, c); id++; } let best = Math.max(0, ...Object.values(size)); for (let r = 0; r < n; r++) for (let c = 0; c < n; c++) if (grid[r][c] === 0) { const ids = new Set(); for (const [dr, dc] of ${DIRS}) { const v = (grid[r + dr] || [])[c + dc]; if (v > 1) ids.add(v); } let s = 1; for (const i of ids) s += size[i]; best = Math.max(best, s); } return best; }`,
    brute: `function largestIsland(grid) { const n = grid.length; const biggest = (g) => { const seen = new Set(); let best = 0; for (let r = 0; r < n; r++) for (let c = 0; c < n; c++) { if (!g[r][c] || seen.has(r * n + c)) continue; let s = 0; const st = [[r, c]]; seen.add(r * n + c); while (st.length) { const [y, x] = st.pop(); s++; for (const [dy, dx] of ${DIRS}) { const ny = y + dy, nx = x + dx; if (ny >= 0 && nx >= 0 && ny < n && nx < n && g[ny][nx] && !seen.has(ny * n + nx)) { seen.add(ny * n + nx); st.push([ny, nx]); } } } best = Math.max(best, s); } return best; }; let best = biggest(grid); for (let r = 0; r < n; r++) for (let c = 0; c < n; c++) if (!grid[r][c]) { const g = grid.map((row) => row.slice()); g[r][c] = 1; best = Math.max(best, biggest(g)); } return best; }`,
    fuzz: ggen(`const n = __r(rand, 1, 6); return [__grid(rand, n, n, rand() * 0.8)];`),
    examples: [[[[1, 0], [0, 1]]], [[[1, 1], [1, 0]]], [[[1, 1], [1, 1]]]],
    edges: [
      ["zeros", [[[0, 0], [0, 0]]], "Flip any cell: an island of 1."],
      ["single", [[[0]]]],
      ["boundary", [[[1, 0, 1], [0, 0, 0], [1, 0, 1]]], "The centre touches no island; an edge cell joins two."],
    ],
  },
  {
    slug: "critical-connections-in-a-network",
    title: "Critical Connections in a Network",
    difficulty: "Hard",
    pattern: "Advanced Graphs",
    fn: "criticalConnections",
    params: [["n", "number"], ["connections", GRID]],
    returns: "number[][]",
    compare: "unordered",
    hints: [
      "A critical connection (bridge) is an edge on no cycle: removing it disconnects the graph. Any order of edges, and of the two ends of an edge, is accepted.",
      "Tarjan's DFS: give each node a discovery time and a low value (the earliest time reachable using at most one back edge). Edge u-v is a bridge when low[v] > disc[u].",
      "timer = 0; disc and low unset\ndfs(u, parent):\n  disc[u] = low[u] = timer; timer += 1\n  for v in adj[u]:\n    if v == parent: continue\n    if disc[v] is unset:\n      dfs(v, u)\n      low[u] = min(low[u], low[v])\n      if low[v] > disc[u]: record [u, v]\n    else: low[u] = min(low[u], disc[v])\ndfs(0, none)\nreturn the recorded edges",
    ],
    reference: `function criticalConnections(n, connections) { ${ADJ} for (const [a, b] of connections) { adj[a].push(b); adj[b].push(a); } const disc = new Array(n).fill(-1), low = new Array(n).fill(0), out = []; let t = 0; const dfs = (u, p) => { disc[u] = low[u] = t++; for (const v of adj[u]) { if (v === p) continue; if (disc[v] < 0) { dfs(v, u); low[u] = Math.min(low[u], low[v]); if (low[v] > disc[u]) out.push([u, v]); } else low[u] = Math.min(low[u], disc[v]); } }; dfs(0, -1); return out; }`,
    brute: `function criticalConnections(n, connections) { return connections.filter((_, skip) => { const adj = Array.from({ length: n }, () => []); connections.forEach(([a, b], i) => { if (i !== skip) { adj[a].push(b); adj[b].push(a); } }); const seen = new Set([0]), st = [0]; while (st.length) for (const v of adj[st.pop()]) if (!seen.has(v)) { seen.add(v); st.push(v); } return seen.size < n; }); }`,
    fuzz: ggen(`const n = __r(rand, 2, 9), t = __tree(rand, n), have = new Set(t.map(([a, b]) => Math.min(a, b) + "," + Math.max(a, b))); for (const [a, b] of __edges(rand, n, __r(rand, 0, 3))) { const k = Math.min(a, b) + "," + Math.max(a, b); if (!have.has(k)) { have.add(k); t.push([a, b]); } } return [n, __shuffle(rand, t)];`),
    examples: [[4, [[0, 1], [1, 2], [2, 0], [1, 3]]], [2, [[0, 1]]]],
    edges: [
      ["cycle", [3, [[0, 1], [1, 2], [2, 0]]], "Everything is on a cycle: no bridges."],
      ["boundary", [6, [[0, 1], [1, 2], [2, 0], [2, 3], [3, 4], [4, 5], [5, 3]]], "Two triangles joined by one bridge."],
      ["skewed", [4, [[0, 1], [1, 2], [2, 3]]], "A path: every edge is a bridge."],
    ],
  },
];

export const LADDER_GRAPHS2_SEEDED: ProblemSpec[] = DEFS.map((d) => define(d).spec);
