import { define, type ProblemDef } from "../../dsa-extras/define";
import { gen } from "../../dsa-extras/gen";
import type { ProblemSpec } from "../types";

const D1 = "1-D Dynamic Programming";
const D2 = "2-D Dynamic Programming";
const GRID = "number[][]";
const gridGen = (minR: number, maxR: number, minC: number, maxC: number, lo: number, hi: number) =>
  gen(`const r = __r(rand, ${minR}, ${maxR}), c = __r(rand, ${minC}, ${maxC}); return [Array.from({ length: r }, () => __arr(rand, c, ${lo}, ${hi}))];`);

/** Judges for the DP Ladder: 1-D, knapsack-style counting, stock states and grids. Brutes try every choice on small inputs. */
const DEFS: ProblemDef[] = [
  {
    slug: "min-cost-climbing-stairs",
    title: "Min Cost Climbing Stairs",
    difficulty: "Easy",
    pattern: D1,
    fn: "minCostClimbingStairs",
    params: [["cost", "number[]"]],
    returns: "number",
    hints: [
      "You may start on step 0 or 1 and climb 1 or 2 steps, paying the cost of each step you stand on. The top is one past the last step.",
      "Let best[i] be the cheapest way to stand past step i - 1: best[i] = min(best[i - 1] + cost[i - 1], best[i - 2] + cost[i - 2]). Two variables are enough.",
      "a = 0; b = 0   (cheapest to reach steps i - 2 and i - 1)\nfor i in 2 .. n:\n  c = min(b + cost[i - 1], a + cost[i - 2])\n  a = b; b = c\nreturn b",
    ],
    reference: `function minCostClimbingStairs(cost) { let a = 0, b = 0; for (let i = 2; i <= cost.length; i++) { const c = Math.min(b + cost[i - 1], a + cost[i - 2]); a = b; b = c; } return b; }`,
    brute: `function minCostClimbingStairs(cost) { const go = (i) => (i >= cost.length ? 0 : cost[i] + Math.min(go(i + 1), go(i + 2))); return Math.min(go(0), go(1)); }`,
    fuzz: gen(`return [__arr(rand, __r(rand, 2, 14), 0, 20)];`),
    examples: [[[10, 15, 20]], [[1, 100, 1, 1, 1, 100, 1, 1, 100, 1]]],
    edges: [
      ["two", [[5, 3]], "Start on the cheaper step and jump to the top."],
      ["zeros", [[0, 0, 0, 0]]],
      ["boundary", [[0, 1, 2, 2]]],
    ],
  },
  {
    slug: "n-th-tribonacci-number",
    title: "N-th Tribonacci Number",
    difficulty: "Easy",
    pattern: D1,
    fn: "tribonacci",
    params: [["n", "number"]],
    returns: "number",
    hints: [
      "T0 = 0, T1 = 1, T2 = 1 and each later term is the sum of the three before it.",
      "Plain recursion repeats work exponentially. Keep the last three values and slide them forward.",
      "if n == 0: return 0\na = 0; b = 1; c = 1\nrepeat n - 2 times:\n  a, b, c = b, c, a + b + c\nreturn c",
    ],
    reference: `function tribonacci(n) { if (n === 0) return 0; let a = 0, b = 1, c = 1; for (let i = 3; i <= n; i++) [a, b, c] = [b, c, a + b + c]; return c; }`,
    brute: `function tribonacci(n) { const memo = {}; const t = (k) => { if (k === 0) return 0; if (k <= 2) return 1; if (memo[k] !== undefined) return memo[k]; return (memo[k] = t(k - 1) + t(k - 2) + t(k - 3)); }; return t(n); }`,
    fuzz: gen(`return [__r(rand, 0, 37)];`),
    examples: [[4], [25]],
    edges: [
      ["zeros", [0]],
      ["single", [1]],
      ["large", [37], "The largest allowed n still fits in 32 bits."],
    ],
  },
  {
    slug: "house-robber-ii",
    title: "House Robber II",
    difficulty: "Medium",
    pattern: D1,
    fn: "rob",
    params: [["nums", "number[]"]],
    returns: "number",
    hints: [
      "The houses form a circle, so the first and last are neighbours. You can never rob both.",
      "Run the straight-line House Robber twice: once without the last house and once without the first, and take the better result. One house is a special case.",
      "line(a): take = 0; skip = 0; for x in a: take, skip = skip + x, max(take, skip); return max(take, skip)\nif n == 1: return nums[0]\nreturn max(line(nums[0 .. n - 2]), line(nums[1 .. n - 1]))",
    ],
    reference: `function rob(nums) { if (nums.length === 1) return nums[0]; const line = (a) => { let take = 0, skip = 0; for (const x of a) [take, skip] = [skip + x, Math.max(take, skip)]; return Math.max(take, skip); }; return Math.max(line(nums.slice(0, -1)), line(nums.slice(1))); }`,
    brute: `function rob(nums) { const n = nums.length; let best = 0; for (let m = 0; m < 1 << n; m++) { let ok = true, s = 0; for (let i = 0; i < n; i++) if ((m >> i) & 1) { s += nums[i]; if (n > 1 && (m >> ((i + 1) % n)) & 1 && (i + 1) % n !== i) ok = false; } if (ok) best = Math.max(best, s); } return best; }`,
    fuzz: gen(`return [__arr(rand, __r(rand, 1, 12), 0, 20)];`),
    examples: [[[2, 3, 2]], [[1, 2, 3, 1]], [[1, 2, 3]]],
    edges: [
      ["single", [[7]]],
      ["two", [[4, 9]]],
      ["boundary", [[200, 3, 140, 20, 10]], "First and last are both big, but they touch."],
    ],
  },
  {
    slug: "target-sum",
    title: "Target Sum",
    difficulty: "Medium",
    pattern: D1,
    fn: "findTargetSumWays",
    params: [["nums", "number[]"], ["target", "number"]],
    returns: "number",
    hints: [
      "Each number gets a + or a -. The plus group P and minus group M satisfy P - M = target and P + M = total.",
      "So P = (total + target) / 2: count subsets with that sum (0/1 knapsack counting). If that is not a whole number or is negative, the answer is 0. Zeros double the count, which the DP handles naturally.",
      "total = sum(nums)\nif |target| > total or (total + target) is odd: return 0\nwant = (total + target) / 2\nways = array of want + 1 zeros; ways[0] = 1\nfor x in nums:\n  for s from want down to x:\n    ways[s] += ways[s - x]\nreturn ways[want]",
    ],
    reference: `function findTargetSumWays(nums, target) { const total = nums.reduce((a, b) => a + b, 0); if (Math.abs(target) > total || (total + target) % 2) return 0; const want = (total + target) / 2, ways = new Array(want + 1).fill(0); ways[0] = 1; for (const x of nums) for (let s = want; s >= x; s--) ways[s] += ways[s - x]; return ways[want]; }`,
    brute: `function findTargetSumWays(nums, target) { const go = (i, s) => (i === nums.length ? (s === target ? 1 : 0) : go(i + 1, s + nums[i]) + go(i + 1, s - nums[i])); return go(0, 0); }`,
    fuzz: gen(`return [__arr(rand, __r(rand, 1, 12), 0, 6), __r(rand, -10, 10)];`),
    examples: [[[1, 1, 1, 1, 1], 3], [[1], 1]],
    edges: [
      ["zeros", [[0, 0, 1], 1], "Each zero can take either sign."],
      ["no-answer", [[2, 4], 1], "Parity makes it impossible."],
      ["negatives", [[1, 2, 3], -6]],
    ],
  },
  {
    slug: "coin-change-ii",
    title: "Coin Change II",
    difficulty: "Medium",
    pattern: D1,
    fn: "change",
    params: [["amount", "number"], ["coins", "number[]"]],
    returns: "number",
    hints: [
      "Count combinations, not orders: 1+2 and 2+1 are the same way. Coins can be reused.",
      "Unbounded knapsack counting with the coin loop on the outside, so each combination is built in one fixed coin order.",
      "ways = array of amount + 1 zeros; ways[0] = 1\nfor c in coins:\n  for s from c up to amount:\n    ways[s] += ways[s - c]\nreturn ways[amount]",
    ],
    reference: `function change(amount, coins) { const ways = new Array(amount + 1).fill(0); ways[0] = 1; for (const c of coins) for (let s = c; s <= amount; s++) ways[s] += ways[s - c]; return ways[amount]; }`,
    brute: `function change(amount, coins) { const go = (i, left) => { if (left === 0) return 1; if (i === coins.length) return 0; let w = 0; for (let k = 0; k * coins[i] <= left; k++) w += go(i + 1, left - k * coins[i]); return w; }; return go(0, amount); }`,
    fuzz: gen(`return [__r(rand, 0, 30), __shuffle(rand, Array.from({ length: 10 }, (_, i) => i + 1)).slice(0, __r(rand, 1, 4))];`),
    examples: [[5, [1, 2, 5]], [3, [2]], [10, [10]]],
    edges: [
      ["zeros", [0, [7]], "Amount 0: one way, use nothing."],
      ["no-answer", [7, [2, 4]]],
      ["boundary", [12, [1, 3, 4]]],
    ],
  },
  {
    slug: "perfect-squares",
    title: "Perfect Squares",
    difficulty: "Medium",
    pattern: D1,
    fn: "numSquares",
    params: [["n", "number"]],
    returns: "number",
    hints: [
      "The fewest perfect squares that add up to n. Greedy (take the biggest square) fails: 12 = 4 + 4 + 4, not 9 + 1 + 1 + 1.",
      "best[i] = 1 + min over squares s <= i of best[i - s], built from 0 upward.",
      "best = array with best[0] = 0, rest infinity\nfor i in 1 .. n:\n  for j = 1 while j * j <= i:\n    best[i] = min(best[i], best[i - j * j] + 1)\nreturn best[n]",
    ],
    reference: `function numSquares(n) { const best = [0]; for (let i = 1; i <= n; i++) { best[i] = Infinity; for (let j = 1; j * j <= i; j++) best[i] = Math.min(best[i], best[i - j * j] + 1); } return best[n]; }`,
    brute: `function numSquares(n) { const sq = (x) => Math.floor(Math.sqrt(x)) ** 2 === x; if (sq(n)) return 1; for (let a = 1; a * a <= n; a++) if (sq(n - a * a)) return 2; let m = n; while (m % 4 === 0) m /= 4; return m % 8 === 7 ? 4 : 3; }`,
    fuzz: gen(`return [__r(rand, 1, 200)];`),
    examples: [[12], [13]],
    edges: [
      ["single", [1]],
      ["boundary", [7], "Needs 4 squares: 4 + 1 + 1 + 1."],
      ["large", [9999]],
    ],
  },
  {
    slug: "combination-sum-iv",
    title: "Combination Sum IV",
    difficulty: "Medium",
    pattern: D1,
    fn: "combinationSum4",
    params: [["nums", "number[]"], ["target", "number"]],
    returns: "number",
    hints: [
      "Despite the name, different orders count as different ways here (1+2 and 2+1 are two).",
      "ways[t] = sum over nums x <= t of ways[t - x], with the target loop outside and the numbers loop inside.",
      "ways = array of target + 1 zeros; ways[0] = 1\nfor t in 1 .. target:\n  for x in nums:\n    if x <= t: ways[t] += ways[t - x]\nreturn ways[target]",
    ],
    reference: `function combinationSum4(nums, target) { const ways = new Array(target + 1).fill(0); ways[0] = 1; for (let t = 1; t <= target; t++) for (const x of nums) if (x <= t) ways[t] += ways[t - x]; return ways[target]; }`,
    brute: `function combinationSum4(nums, target) { const go = (left) => { if (left === 0) return 1; let w = 0; for (const x of nums) if (x <= left) w += go(left - x); return w; }; return go(target); }`,
    fuzz: gen(`return [__shuffle(rand, Array.from({ length: 8 }, (_, i) => i + 1)).slice(0, __r(rand, 1, 4)), __r(rand, 1, 16)];`),
    examples: [[[1, 2, 3], 4], [[9], 3]],
    edges: [
      ["single", [[1], 6], "Only one way: all ones."],
      ["no-answer", [[4, 6], 5]],
      ["order", [[1, 2], 5], "Every arrangement counts."],
    ],
  },
  {
    slug: "delete-and-earn",
    title: "Delete and Earn",
    difficulty: "Medium",
    pattern: D1,
    fn: "deleteAndEarn",
    params: [["nums", "number[]"]],
    returns: "number",
    hints: [
      "Taking value v earns v for every copy of it but forbids v - 1 and v + 1. Group equal values first.",
      "Make points[v] = v * count(v) and run House Robber over the values: adjacent values are adjacent houses.",
      "points[v] = v * (number of times v appears)\ntake = 0; skip = 0\nfor v in 0 .. max(nums):\n  take, skip = skip + points[v], max(take, skip)\nreturn max(take, skip)",
    ],
    reference: `function deleteAndEarn(nums) { const m = Math.max(...nums), pts = new Array(m + 1).fill(0); for (const x of nums) pts[x] += x; let take = 0, skip = 0; for (let v = 0; v <= m; v++) [take, skip] = [skip + pts[v], Math.max(take, skip)]; return Math.max(take, skip); }`,
    brute: `function deleteAndEarn(nums) { const vals = [...new Set(nums)].sort((a, b) => a - b); let best = 0; for (let mask = 0; mask < 1 << vals.length; mask++) { let ok = true, s = 0; for (let i = 0; i < vals.length; i++) if ((mask >> i) & 1) { if (i > 0 && (mask >> (i - 1)) & 1 && vals[i - 1] === vals[i] - 1) ok = false; s += vals[i] * nums.filter((x) => x === vals[i]).length; } if (ok) best = Math.max(best, s); } return best; }`,
    fuzz: gen(`return [__arr(rand, __r(rand, 1, 12), 1, 10)];`),
    examples: [[[3, 4, 2]], [[2, 2, 3, 3, 3, 4]]],
    edges: [
      ["single", [[5]]],
      ["all-equal", [[4, 4, 4]]],
      ["boundary", [[1, 1, 1, 2, 4, 5, 5, 5, 6]], "Two separate runs of values."],
    ],
  },
  {
    slug: "best-time-to-buy-and-sell-stock-with-cooldown",
    title: "Best Time to Buy and Sell Stock with Cooldown",
    difficulty: "Medium",
    pattern: D1,
    fn: "maxProfit",
    params: [["prices", "number[]"]],
    returns: "number",
    hints: [
      "After you sell, you must wait one day before buying again. Track what state you are in each day.",
      "Three states: holding a share, just sold (cooldown next day), and resting with no share. Update all three from yesterday's values.",
      "hold = -infinity; sold = 0; rest = 0\nfor p in prices:\n  prevSold = sold\n  sold = hold + p\n  hold = max(hold, rest - p)\n  rest = max(rest, prevSold)\nreturn max(sold, rest)",
    ],
    reference: `function maxProfit(prices) { let hold = -Infinity, sold = 0, rest = 0; for (const p of prices) { const ps = sold; sold = hold + p; hold = Math.max(hold, rest - p); rest = Math.max(rest, ps); } return Math.max(sold, rest); }`,
    brute: `function maxProfit(prices) { const go = (i, holding) => { if (i >= prices.length) return 0; const wait = go(i + 1, holding); return holding ? Math.max(wait, prices[i] + go(i + 2, false)) : Math.max(wait, go(i + 1, true) - prices[i]); }; return go(0, false); }`,
    fuzz: gen(`return [__arr(rand, __r(rand, 1, 12), 0, 15)];`),
    examples: [[[1, 2, 3, 0, 2]], [[1]]],
    edges: [
      ["reverse-sorted", [[5, 4, 3, 2, 1]], "Prices only fall: do nothing."],
      ["sorted", [[1, 2, 3, 4, 5]]],
      ["boundary", [[1, 4, 2, 7]], "The cooldown forbids buying right after a sale."],
    ],
  },
  {
    slug: "best-time-to-buy-and-sell-stock-with-transaction-fee",
    title: "Best Time to Buy and Sell Stock with Transaction Fee",
    difficulty: "Medium",
    pattern: D1,
    fn: "maxProfit",
    params: [["prices", "number[]"], ["fee", "number"]],
    returns: "number",
    hints: [
      "Unlimited trades, but each sale costs a fee, so tiny wiggles are no longer worth trading.",
      "Two states per day: cash (no share) and hold (one share). cash = max(cash, hold + price - fee); hold = max(hold, cash - price).",
      "cash = 0; hold = -prices[0]\nfor p in prices[1 ..]:\n  cash = max(cash, hold + p - fee)\n  hold = max(hold, cash - p)\nreturn cash",
    ],
    reference: `function maxProfit(prices, fee) { let cash = 0, hold = -prices[0]; for (let i = 1; i < prices.length; i++) { cash = Math.max(cash, hold + prices[i] - fee); hold = Math.max(hold, cash - prices[i]); } return cash; }`,
    brute: `function maxProfit(prices, fee) { const go = (i, holding) => { if (i === prices.length) return 0; const wait = go(i + 1, holding); return holding ? Math.max(wait, prices[i] - fee + go(i + 1, false)) : Math.max(wait, go(i + 1, true) - prices[i]); }; return go(0, false); }`,
    fuzz: gen(`return [__arr(rand, __r(rand, 1, 12), 1, 15), __r(rand, 0, 4)];`),
    examples: [[[1, 3, 2, 8, 4, 9], 2], [[1, 3, 7, 5, 10, 3], 3]],
    edges: [
      ["single", [[5], 1]],
      ["zeros", [[1, 2, 1, 2], 0], "No fee: take every rise."],
      ["boundary", [[1, 3, 1, 3], 2], "Each rise only pays the fee: profit 0."],
    ],
  },
  {
    slug: "partition-array-for-maximum-sum",
    title: "Partition Array for Maximum Sum",
    difficulty: "Medium",
    pattern: D1,
    fn: "maxSumAfterPartitioning",
    params: [["arr", "number[]"], ["k", "number"]],
    returns: "number",
    hints: [
      "Cut the array into pieces of length at most k; every value in a piece becomes the piece's maximum. Maximise the total.",
      "best[i] = the answer for the first i elements: try every last piece length L from 1 to k and take best[i - L] + L * max of that piece.",
      "best = array of n + 1 zeros\nfor i in 1 .. n:\n  m = 0\n  for L in 1 .. min(k, i):\n    m = max(m, arr[i - L])\n    best[i] = max(best[i], best[i - L] + m * L)\nreturn best[n]",
    ],
    reference: `function maxSumAfterPartitioning(arr, k) { const n = arr.length, best = new Array(n + 1).fill(0); for (let i = 1; i <= n; i++) { let m = 0; for (let L = 1; L <= Math.min(k, i); L++) { m = Math.max(m, arr[i - L]); best[i] = Math.max(best[i], best[i - L] + m * L); } } return best[n]; }`,
    brute: `function maxSumAfterPartitioning(arr, k) { const go = (i) => { if (i === arr.length) return 0; let best = 0, m = 0; for (let L = 1; L <= k && i + L <= arr.length; L++) { m = Math.max(m, arr[i + L - 1]); best = Math.max(best, m * L + go(i + L)); } return best; }; return go(0); }`,
    fuzz: gen(`return [__arr(rand, __r(rand, 1, 12), 0, 20), __r(rand, 1, 4)];`),
    examples: [[[1, 15, 7, 9, 2, 5, 10], 3], [[1, 4, 1, 5, 7, 3, 6, 1, 9, 9, 3], 4], [[1], 1]],
    edges: [
      ["boundary", [[3, 1, 2], 1], "k = 1: nothing changes."],
      ["large", [[2, 9, 4], 3], "One piece covers everything."],
      ["all-equal", [[5, 5, 5, 5], 2]],
    ],
  },
  {
    slug: "number-of-longest-increasing-subsequence",
    title: "Number of Longest Increasing Subsequence",
    difficulty: "Medium",
    pattern: D1,
    fn: "findNumberOfLIS",
    params: [["nums", "number[]"]],
    returns: "number",
    hints: [
      "Alongside the LIS length ending at each index, keep how many increasing subsequences reach that length there.",
      "For j < i with nums[j] < nums[i]: a longer length resets count[i] to count[j]; an equal length adds count[j]. Finally sum the counts of indices with the maximum length.",
      "len = n ones; cnt = n ones\nfor i in 0 .. n - 1:\n  for j in 0 .. i - 1 with nums[j] < nums[i]:\n    if len[j] + 1 > len[i]: len[i] = len[j] + 1; cnt[i] = cnt[j]\n    else if len[j] + 1 == len[i]: cnt[i] += cnt[j]\nbest = max(len)\nreturn sum of cnt[i] where len[i] == best",
    ],
    reference: `function findNumberOfLIS(nums) { const n = nums.length, len = new Array(n).fill(1), cnt = new Array(n).fill(1); for (let i = 0; i < n; i++) for (let j = 0; j < i; j++) if (nums[j] < nums[i]) { if (len[j] + 1 > len[i]) { len[i] = len[j] + 1; cnt[i] = cnt[j]; } else if (len[j] + 1 === len[i]) cnt[i] += cnt[j]; } const best = Math.max(...len); return cnt.reduce((s, c, i) => s + (len[i] === best ? c : 0), 0); }`,
    brute: `function findNumberOfLIS(nums) { const n = nums.length; let best = 0, count = 0; for (let m = 1; m < 1 << n; m++) { let last = -Infinity, ok = true, L = 0; for (let i = 0; i < n; i++) if ((m >> i) & 1) { if (nums[i] <= last) { ok = false; break; } last = nums[i]; L++; } if (!ok) continue; if (L > best) { best = L; count = 1; } else if (L === best) count++; } return count; }`,
    fuzz: gen(`return [__arr(rand, __r(rand, 1, 12), -5, 8)];`),
    examples: [[[1, 3, 5, 4, 7]], [[2, 2, 2, 2, 2]]],
    edges: [
      ["single", [[9]]],
      ["reverse-sorted", [[5, 4, 3, 2]], "Every single element is a longest subsequence."],
      ["duplicates", [[1, 2, 2, 3]], "Strictly increasing: two ways through the 2s."],
    ],
  },
  {
    slug: "longest-string-chain",
    title: "Longest String Chain",
    difficulty: "Medium",
    pattern: D1,
    fn: "longestStrChain",
    params: [["words", "string[]"]],
    returns: "number",
    hints: [
      "A word's predecessor is the word with exactly one letter removed. Chains only grow by one letter at a time, so process words from shortest to longest.",
      "Sort by length; for each word, try deleting each letter and look up the best chain ending at that shorter word in a map.",
      "sort words by length\nbest = empty map; ans = 0\nfor w in words:\n  best[w] = 1\n  for i in 0 .. len(w) - 1:\n    prev = w without letter i\n    if prev in best: best[w] = max(best[w], best[prev] + 1)\n  ans = max(ans, best[w])\nreturn ans",
    ],
    reference: `function longestStrChain(words) { const best = new Map(); let ans = 0; for (const w of [...words].sort((a, b) => a.length - b.length)) { let b = 1; for (let i = 0; i < w.length; i++) { const p = w.slice(0, i) + w.slice(i + 1); if (best.has(p)) b = Math.max(b, best.get(p) + 1); } best.set(w, b); ans = Math.max(ans, b); } return ans; }`,
    brute: `function longestStrChain(words) { const pred = (a, b) => { if (b.length !== a.length + 1) return false; for (let i = 0; i < b.length; i++) if (b.slice(0, i) + b.slice(i + 1) === a) return true; return false; }; const go = (w) => { let best = 1; for (const x of words) if (pred(w, x)) best = Math.max(best, 1 + go(x)); return best; }; return Math.max(...words.map(go)); }`,
    fuzz: gen(`const set = new Set(); for (let i = 0; i < __r(rand, 1, 9); i++) set.add(__str(rand, __r(rand, 1, 4), "abc")); return [__shuffle(rand, [...set])];`),
    examples: [[["a", "b", "ba", "bca", "bda", "bdca"]], [["xbc", "pcxbcf", "xb", "cxbc", "pcxbc"]], [["abcd", "dbqca"]]],
    edges: [
      ["single", [["z"]]],
      ["boundary", [["a", "ab", "ac", "abc"]], "Two routes to the same word."],
      ["order", [["ba", "ab", "a"]], "Insertion can happen anywhere in the word."],
    ],
  },
  {
    slug: "unique-paths-ii",
    title: "Unique Paths II",
    difficulty: "Medium",
    pattern: D2,
    fn: "uniquePathsWithObstacles",
    params: [["obstacleGrid", GRID]],
    returns: "number",
    hints: [
      "Moving only right or down, the ways into a cell are the ways into the cell above plus the cell to the left, unless the cell is an obstacle (0 ways).",
      "One row of DP is enough: ways[c] += ways[c - 1] for open cells, and ways[c] = 0 for obstacles.",
      "ways = array of cols zeros; ways[0] = 1\nfor each row:\n  for c in 0 .. cols - 1:\n    if row[c] == 1: ways[c] = 0\n    else if c > 0: ways[c] += ways[c - 1]\nreturn ways[cols - 1]",
    ],
    reference: `function uniquePathsWithObstacles(obstacleGrid) { const C = obstacleGrid[0].length, w = new Array(C).fill(0); w[0] = 1; for (const row of obstacleGrid) for (let c = 0; c < C; c++) { if (row[c]) w[c] = 0; else if (c > 0) w[c] += w[c - 1]; } return w[C - 1]; }`,
    brute: `function uniquePathsWithObstacles(g) { const R = g.length, C = g[0].length; const go = (r, c) => { if (r >= R || c >= C || g[r][c]) return 0; if (r === R - 1 && c === C - 1) return 1; return go(r + 1, c) + go(r, c + 1); }; return go(0, 0); }`,
    fuzz: gen(`const r = __r(rand, 1, 6), c = __r(rand, 1, 6); return [Array.from({ length: r }, () => Array.from({ length: c }, () => (rand() < 0.2 ? 1 : 0)))];`),
    examples: [[[[0, 0, 0], [0, 1, 0], [0, 0, 0]]], [[[0, 1], [0, 0]]]],
    edges: [
      ["single", [[[0]]]],
      ["no-answer", [[[1]]], "The start itself is blocked."],
      ["boundary", [[[0, 0], [1, 1], [0, 0]]], "A full row of obstacles."],
    ],
  },
  {
    slug: "minimum-path-sum",
    title: "Minimum Path Sum",
    difficulty: "Medium",
    pattern: D2,
    fn: "minPathSum",
    params: [["grid", GRID]],
    returns: "number",
    hints: [
      "Moving right or down, the cheapest way into a cell comes from the cheaper of its top and left neighbours.",
      "Fill a DP row by row: best[c] = grid[r][c] + min(best[c] from the row above, best[c - 1] in this row). The first row and column have only one way in.",
      "best = array of cols infinity; best[0] = 0\nfor each row r:\n  for c in 0 .. cols - 1:\n    left = best[c - 1] if c > 0 else infinity\n    best[c] = grid[r][c] + min(best[c], left)\nreturn best[cols - 1]",
    ],
    reference: `function minPathSum(grid) { const C = grid[0].length, b = new Array(C).fill(Infinity); b[0] = 0; for (const row of grid) for (let c = 0; c < C; c++) b[c] = row[c] + Math.min(b[c], c > 0 ? b[c - 1] : Infinity); return b[C - 1]; }`,
    brute: `function minPathSum(grid) { const R = grid.length, C = grid[0].length; const go = (r, c) => { if (r === R - 1 && c === C - 1) return grid[r][c]; let best = Infinity; if (r + 1 < R) best = Math.min(best, go(r + 1, c)); if (c + 1 < C) best = Math.min(best, go(r, c + 1)); return grid[r][c] + best; }; return go(0, 0); }`,
    fuzz: gridGen(1, 6, 1, 6, 0, 9),
    examples: [[[[1, 3, 1], [1, 5, 1], [4, 2, 1]]], [[[1, 2, 3], [4, 5, 6]]]],
    edges: [
      ["single", [[[7]]]],
      ["zeros", [[[0, 0], [0, 0]]]],
      ["boundary", [[[1], [2], [3]]], "A single column: one path."],
    ],
  },
  {
    slug: "triangle",
    title: "Triangle",
    difficulty: "Medium",
    pattern: D2,
    fn: "minimumTotal",
    params: [["triangle", GRID]],
    returns: "number",
    hints: [
      "From index i in a row you may step to index i or i + 1 in the next row. Find the cheapest top-to-bottom path.",
      "Work bottom-up: start with the last row and replace each value by itself plus the smaller of the two values below it. The top then holds the answer.",
      "best = copy of the last row\nfor r from second-to-last row up to 0:\n  for i in 0 .. r:\n    best[i] = triangle[r][i] + min(best[i], best[i + 1])\nreturn best[0]",
    ],
    reference: `function minimumTotal(triangle) { const b = triangle[triangle.length - 1].slice(); for (let r = triangle.length - 2; r >= 0; r--) for (let i = 0; i <= r; i++) b[i] = triangle[r][i] + Math.min(b[i], b[i + 1]); return b[0]; }`,
    brute: `function minimumTotal(triangle) { const go = (r, i) => (r === triangle.length ? 0 : triangle[r][i] + Math.min(go(r + 1, i), go(r + 1, i + 1))); return go(0, 0); }`,
    fuzz: gen(`const n = __r(rand, 1, 8); return [Array.from({ length: n }, (_, r) => __arr(rand, r + 1, -9, 9))];`),
    examples: [[[[2], [3, 4], [6, 5, 7], [4, 1, 8, 3]]], [[[-10]]]],
    edges: [
      ["two", [[[1], [2, 3]]]],
      ["negatives", [[[-1], [2, 3], [1, -1, -3]]]],
      ["boundary", [[[1], [9, 1], [9, 9, 1]]], "Hugging the right edge is cheapest."],
    ],
  },
  {
    slug: "minimum-falling-path-sum",
    title: "Minimum Falling Path Sum",
    difficulty: "Medium",
    pattern: D2,
    fn: "minFallingPathSum",
    params: [["matrix", GRID]],
    returns: "number",
    hints: [
      "Start anywhere in the first row; each step goes to the cell directly below or diagonally below-left or below-right.",
      "Row by row: best[c] = matrix[r][c] + min of the previous row's best at c - 1, c, c + 1 (where they exist). The answer is the smallest value in the last row.",
      "best = copy of row 0\nfor r in 1 .. n - 1:\n  next = []\n  for c in 0 .. n - 1:\n    next[c] = matrix[r][c] + min(best[c - 1], best[c], best[c + 1]) using only valid columns\n  best = next\nreturn min(best)",
    ],
    reference: `function minFallingPathSum(matrix) { const n = matrix.length; let b = matrix[0].slice(); for (let r = 1; r < n; r++) b = matrix[r].map((v, c) => v + Math.min(b[c], c > 0 ? b[c - 1] : Infinity, c < n - 1 ? b[c + 1] : Infinity)); return Math.min(...b); }`,
    brute: `function minFallingPathSum(matrix) { const n = matrix.length; const go = (r, c) => { if (c < 0 || c >= n) return Infinity; if (r === n - 1) return matrix[r][c]; return matrix[r][c] + Math.min(go(r + 1, c - 1), go(r + 1, c), go(r + 1, c + 1)); }; return Math.min(...matrix[0].map((_, c) => go(0, c))); }`,
    fuzz: gen(`const n = __r(rand, 1, 6); return [Array.from({ length: n }, () => __arr(rand, n, -9, 9))];`),
    examples: [[[[2, 1, 3], [6, 5, 4], [7, 8, 9]]], [[[-19, 57], [-40, -5]]]],
    edges: [
      ["single", [[[5]]]],
      ["negatives", [[[-1, -2], [-3, -4]]]],
      ["boundary", [[[1, 9, 9], [9, 9, 1], [9, 1, 9]]], "The diagonal moves matter."],
    ],
  },
  {
    slug: "maximal-square",
    title: "Maximal Square",
    difficulty: "Medium",
    pattern: D2,
    fn: "maximalSquare",
    params: [["matrix", "string[][]"]],
    returns: "number",
    hints: [
      "Let side[r][c] be the biggest all-'1' square whose bottom-right corner is (r, c). Return the area, side squared.",
      "side[r][c] = 1 + min(side above, side to the left, side above-left) when the cell is '1', else 0.",
      "side = (rows + 1) x (cols + 1) zeros; best = 0\nfor r in 1 .. rows:\n  for c in 1 .. cols:\n    if matrix[r - 1][c - 1] == '1':\n      side[r][c] = 1 + min(side[r - 1][c], side[r][c - 1], side[r - 1][c - 1])\n      best = max(best, side[r][c])\nreturn best * best",
    ],
    reference: `function maximalSquare(matrix) { const R = matrix.length, C = matrix[0].length, s = Array.from({ length: R + 1 }, () => new Array(C + 1).fill(0)); let best = 0; for (let r = 1; r <= R; r++) for (let c = 1; c <= C; c++) if (matrix[r - 1][c - 1] === "1") { s[r][c] = 1 + Math.min(s[r - 1][c], s[r][c - 1], s[r - 1][c - 1]); best = Math.max(best, s[r][c]); } return best * best; }`,
    brute: `function maximalSquare(matrix) { const R = matrix.length, C = matrix[0].length; let best = 0; for (let r = 0; r < R; r++) for (let c = 0; c < C; c++) for (let k = 1; r + k <= R && c + k <= C; k++) { let ok = true; for (let y = r; y < r + k && ok; y++) for (let x = c; x < c + k; x++) if (matrix[y][x] !== "1") { ok = false; break; } if (ok) best = Math.max(best, k); } return best * best; }`,
    fuzz: gen(`const r = __r(rand, 1, 6), c = __r(rand, 1, 6); return [Array.from({ length: r }, () => Array.from({ length: c }, () => (rand() < 0.7 ? "1" : "0")))];`),
    examples: [[[["1", "0", "1", "0", "0"], ["1", "0", "1", "1", "1"], ["1", "1", "1", "1", "1"], ["1", "0", "0", "1", "0"]]], [[["0", "1"], ["1", "0"]]], [[["0"]]]],
    edges: [
      ["single", [[["1"]]]],
      ["all-equal", [[["1", "1", "1"], ["1", "1", "1"], ["1", "1", "1"]]]],
      ["boundary", [[["1", "1", "1", "1"]]], "A strip only fits 1x1 squares."],
    ],
  },
  {
    slug: "count-square-submatrices-with-all-ones",
    title: "Count Square Submatrices with All Ones",
    difficulty: "Medium",
    pattern: D2,
    fn: "countSquares",
    params: [["matrix", GRID]],
    returns: "number",
    hints: [
      "A cell that is the corner of a k x k all-ones square is also the corner of the 1 x 1 .. (k-1) x (k-1) ones, so it contributes k squares.",
      "Same recurrence as Maximal Square: side = 1 + min(top, left, top-left) for 1 cells. Sum every side value.",
      "total = 0\nfor r in 0 .. rows - 1:\n  for c in 0 .. cols - 1:\n    if matrix[r][c] == 1 and r > 0 and c > 0:\n      matrix[r][c] = 1 + min(matrix[r - 1][c], matrix[r][c - 1], matrix[r - 1][c - 1])\n    total += matrix[r][c]\nreturn total",
    ],
    reference: `function countSquares(matrix) { let total = 0; for (let r = 0; r < matrix.length; r++) for (let c = 0; c < matrix[0].length; c++) { if (matrix[r][c] && r && c) matrix[r][c] = 1 + Math.min(matrix[r - 1][c], matrix[r][c - 1], matrix[r - 1][c - 1]); total += matrix[r][c]; } return total; }`,
    brute: `function countSquares(matrix) { const R = matrix.length, C = matrix[0].length; let n = 0; for (let r = 0; r < R; r++) for (let c = 0; c < C; c++) for (let k = 1; r + k <= R && c + k <= C; k++) { let ok = true; for (let y = r; y < r + k && ok; y++) for (let x = c; x < c + k; x++) if (!matrix[y][x]) { ok = false; break; } if (ok) n++; else break; } return n; }`,
    fuzz: gen(`const r = __r(rand, 1, 6), c = __r(rand, 1, 6); return [Array.from({ length: r }, () => Array.from({ length: c }, () => (rand() < 0.7 ? 1 : 0)))];`),
    examples: [[[[0, 1, 1, 1], [1, 1, 1, 1], [0, 1, 1, 1]]], [[[1, 0, 1], [1, 1, 0], [1, 1, 0]]]],
    edges: [
      ["single", [[[1]]]],
      ["zeros", [[[0, 0], [0, 0]]]],
      ["all-equal", [[[1, 1, 1], [1, 1, 1], [1, 1, 1]]], "9 + 4 + 1 squares."],
    ],
  },
  {
    slug: "cherry-pickup-ii",
    title: "Cherry Pickup II",
    difficulty: "Hard",
    pattern: D2,
    fn: "cherryPickup",
    params: [["grid", GRID]],
    returns: "number",
    hints: [
      "Both robots move down one row at a time, each stepping to column c - 1, c or c + 1. Move them together so the state is (row, column of robot 1, column of robot 2).",
      "dp over rows: for every pair of columns, take the best of the 9 combined moves from the previous row and add the cherries in this row (count once if both robots share a cell).",
      "dp[c1][c2] = -infinity except dp[0][cols - 1] = cherries in row 0 at both columns\nfor r in 1 .. rows - 1:\n  next = all -infinity\n  for c1, c2 and each of the 9 moves (d1, d2):\n    p1 = c1 - d1; p2 = c2 - d2\n    if p1, p2 are valid and dp[p1][p2] is reachable:\n      gain = grid[r][c1] + (grid[r][c2] if c2 != c1 else 0)\n      next[c1][c2] = max(next[c1][c2], dp[p1][p2] + gain)\n  dp = next\nreturn the max value in dp",
    ],
    reference: `function cherryPickup(grid) { const R = grid.length, C = grid[0].length, NEG = -Infinity; let dp = Array.from({ length: C }, () => new Array(C).fill(NEG)); dp[0][C - 1] = grid[0][0] + (C > 1 ? grid[0][C - 1] : 0); for (let r = 1; r < R; r++) { const nx = Array.from({ length: C }, () => new Array(C).fill(NEG)); for (let a = 0; a < C; a++) for (let b = 0; b < C; b++) for (let d1 = -1; d1 <= 1; d1++) for (let d2 = -1; d2 <= 1; d2++) { const pa = a - d1, pb = b - d2; if (pa < 0 || pb < 0 || pa >= C || pb >= C || dp[pa][pb] === NEG) continue; nx[a][b] = Math.max(nx[a][b], dp[pa][pb] + grid[r][a] + (a !== b ? grid[r][b] : 0)); } dp = nx; } return Math.max(...dp.flat()); }`,
    brute: `function cherryPickup(grid) { const R = grid.length, C = grid[0].length; const go = (r, a, b) => { if (a < 0 || b < 0 || a >= C || b >= C) return -Infinity; const here = grid[r][a] + (a !== b ? grid[r][b] : 0); if (r === R - 1) return here; let best = -Infinity; for (let d1 = -1; d1 <= 1; d1++) for (let d2 = -1; d2 <= 1; d2++) best = Math.max(best, go(r + 1, a + d1, b + d2)); return here + best; }; return go(0, 0, C - 1); }`,
    fuzz: gridGen(1, 5, 2, 5, 0, 9),
    examples: [[[[3, 1, 1], [2, 5, 1], [1, 5, 5], [2, 1, 1]]], [[[1, 0, 0, 0, 0, 0, 1], [2, 0, 0, 0, 0, 3, 0], [2, 0, 9, 0, 0, 0, 0], [0, 3, 0, 5, 4, 0, 0], [1, 0, 2, 3, 0, 0, 6]]]],
    edges: [
      ["two", [[[1, 2], [3, 4]]], "Two columns: the robots may swap sides."],
      ["zeros", [[[0, 0], [0, 0]]]],
      ["boundary", [[[0, 0, 0], [0, 9, 0], [0, 0, 0]]], "Both want the middle; it counts once."],
    ],
  },
];

export const LADDER_DP_SEEDED: ProblemSpec[] = DEFS.map((d) => define(d).spec);
