import { define, type ProblemDef } from "../../dsa-extras/define";
import { gen } from "../../dsa-extras/gen";
import type { ProblemSpec } from "../types";
import { HEAP } from "../../dsa-extras/ladder-heaps";
import { design } from "./ladder-stack-seeded";

/** Judges for seeded LeetCode problems that the Heaps Ladder points at. LeetCode's own signatures. */
const DEFS: ProblemDef[] = [
  design({
    slug: "kth-largest-element-in-a-stream",
    title: "Kth Largest Element in a Stream",
    difficulty: "Easy",
    pattern: "Heap / Priority Queue",
    cls: "KthLargest",
    ctor: "k, nums",
    methods: ["add(val)"],
    hints: [
      "You never need anything smaller than the k largest values seen so far.",
      "Keep a min-heap of at most k values. After each add, pop while it holds more than k; the top is the k-th largest.",
      "constructor(k, nums): heap = empty min-heap; add every x in nums\nadd(val):\n  push val\n  if heap size > k: pop\n  return heap top",
    ],
    reference: `${HEAP} class KthLargest { constructor(k, nums) { this.k = k; this.h = new MinHeap((a, b) => a - b); for (const x of nums) this.add(x); } add(val) { this.h.push(val); if (this.h.size > this.k) this.h.pop(); return this.h.peek(); } }`,
    brute: `class KthLargest { constructor(k, nums) { this.k = k; this.a = nums.slice(); } add(val) { this.a.push(val); const s = this.a.slice().sort((x, y) => y - x); return s[this.k - 1]; } }`,
    fuzz: gen(`const k = __r(rand, 1, 4); const ops = [["KthLargest", k, __arr(rand, __r(rand, k - 1, 6), -5, 9)]]; const n = __r(rand, 1, 10); for (let i = 0; i < n; i++) ops.push(["add", __r(rand, -5, 9)]); return [ops];`),
    examples: [[[["KthLargest", 3, [4, 5, 8, 2]], ["add", 3], ["add", 5], ["add", 10], ["add", 9], ["add", 4]]], [[["KthLargest", 1, []], ["add", -3], ["add", -2], ["add", -4]]]],
    edges: [
      ["empty", [[["KthLargest", 1, []], ["add", 5]]], "The stream starts empty."],
      ["duplicates", [[["KthLargest", 2, [5, 5]], ["add", 5], ["add", 1]]]],
      ["negatives", [[["KthLargest", 2, [-1, -3]], ["add", -2], ["add", -5]]]],
    ],
  }),
  {
    slug: "last-stone-weight",
    title: "Last Stone Weight",
    difficulty: "Easy",
    pattern: "Heap / Priority Queue",
    fn: "lastStoneWeight",
    params: [["stones", "number[]"]],
    returns: "number",
    hints: [
      "Every turn needs the two heaviest stones. Which structure hands you the largest value quickly, again and again?",
      "Use a max-heap. Pop two, push their difference if it is not zero, and repeat until at most one stone is left.",
      "heap = max-heap of stones\nwhile heap size > 1:\n  y = pop, x = pop\n  if y != x: push y - x\nreturn heap top, or 0 if empty",
    ],
    reference: `${HEAP} function lastStoneWeight(stones) { const h = new MinHeap((a, b) => b - a); for (const s of stones) h.push(s); while (h.size > 1) { const y = h.pop(), x = h.pop(); if (y !== x) h.push(y - x); } return h.size ? h.peek() : 0; }`,
    brute: `function lastStoneWeight(stones) { const a = stones.slice(); while (a.length > 1) { a.sort((x, y) => x - y); const y = a.pop(), x = a.pop(); if (y !== x) a.push(y - x); } return a.length ? a[0] : 0; }`,
    fuzz: gen(`return [__arr(rand, __r(rand, 1, 10), 1, 20)];`),
    examples: [[[2, 7, 4, 1, 8, 1]], [[1]]],
    edges: [
      ["two", [[3, 3]], "Equal stones destroy each other: nothing is left."],
      ["all-equal", [[4, 4, 4]]],
      ["extremes", [[1000, 1, 1]]],
    ],
  },
  {
    slug: "k-closest-points-to-origin",
    title: "K Closest Points to Origin",
    difficulty: "Medium",
    pattern: "Heap / Priority Queue",
    fn: "kClosest",
    params: [["points", "number[][]"], ["k", "number"]],
    returns: "number[][]",
    compare: "unordered-outer",
    hints: [
      "Comparing x*x + y*y is enough; the square root never changes the order.",
      "Keep a max-heap of size k keyed by distance. When it grows past k, drop the farthest point. What is left are the k closest.",
      "heap = max-heap by x*x + y*y\nfor p in points:\n  push p\n  if heap size > k: pop\nreturn every point in heap",
    ],
    reference: `${HEAP} function kClosest(points, k) { const d = (p) => p[0] * p[0] + p[1] * p[1]; const h = new MinHeap((a, b) => d(b) - d(a)); for (const p of points) { h.push(p); if (h.size > k) h.pop(); } return h.a; }`,
    brute: `function kClosest(points, k) { return points.slice().sort((a, b) => a[0] * a[0] + a[1] * a[1] - (b[0] * b[0] + b[1] * b[1])).slice(0, k); }`,
    fuzz: gen(`for (;;) { const n = __r(rand, 1, 8), pts = Array.from({ length: n }, () => [__r(rand, -6, 6), __r(rand, -6, 6)]), k = __r(rand, 1, n); const d = pts.map((p) => p[0] * p[0] + p[1] * p[1]).sort((a, b) => a - b); if (k === n || d[k - 1] !== d[k]) return [pts, k]; }`),
    examples: [[[[1, 3], [-2, 2]], 1], [[[3, 3], [5, -1], [-2, 4]], 2]],
    edges: [
      ["single", [[[0, 0]], 1]],
      ["boundary", [[[1, 1], [2, 2], [-1, 0]], 3], "k equals the number of points: return them all."],
      ["duplicates", [[[1, 1], [1, 1], [3, 3]], 2]],
    ],
  },
  {
    slug: "kth-largest-element-in-an-array",
    title: "Kth Largest Element in an Array",
    difficulty: "Medium",
    pattern: "Heap / Priority Queue",
    fn: "findKthLargest",
    params: [["nums", "number[]"], ["k", "number"]],
    returns: "number",
    hints: [
      "Sorting works in O(n log n). Can you avoid ordering the values you will never return?",
      "Keep a min-heap of the k largest values seen so far; its top is the answer. (Quickselect gets average O(n).)",
      "heap = empty min-heap\nfor x in nums:\n  push x\n  if heap size > k: pop\nreturn heap top",
    ],
    reference: `${HEAP} function findKthLargest(nums, k) { const h = new MinHeap((a, b) => a - b); for (const x of nums) { h.push(x); if (h.size > k) h.pop(); } return h.peek(); }`,
    brute: `function findKthLargest(nums, k) { return nums.slice().sort((a, b) => b - a)[k - 1]; }`,
    fuzz: gen(`const a = __arr(rand, __r(rand, 1, 12), -10, 10); return [a, __r(rand, 1, a.length)];`),
    examples: [[[3, 2, 1, 5, 6, 4], 2], [[3, 2, 3, 1, 2, 4, 5, 5, 6], 4]],
    edges: [
      ["single", [[1], 1]],
      ["duplicates", [[2, 2, 2], 2], "Duplicates count separately: the 2nd largest of [2,2,2] is 2."],
      ["negatives", [[-1, -5, -3], 3]],
    ],
  },
  {
    slug: "task-scheduler",
    title: "Task Scheduler",
    difficulty: "Medium",
    pattern: "Heap / Priority Queue",
    fn: "leastInterval",
    params: [["tasks", "string[]"], ["n", "number"]],
    returns: "number",
    hints: [
      "Only the counts matter, and the most frequent task decides how many idle gaps are forced.",
      "With max count m shared by c tasks, the frame (m - 1) * (n + 1) + c is a lower bound. If there are more tasks than that, no idling is needed. (A max-heap simulation also works.)",
      "count each task\nm = max count\nc = number of tasks with count m\nreturn max(len(tasks), (m - 1) * (n + 1) + c)",
    ],
    reference: `function leastInterval(tasks, n) { const cnt = {}; for (const t of tasks) cnt[t] = (cnt[t] || 0) + 1; const v = Object.values(cnt), m = Math.max(...v), c = v.filter((x) => x === m).length; return Math.max(tasks.length, (m - 1) * (n + 1) + c); }`,
    brute: `function leastInterval(tasks, n) { const left = {}, ready = {}; for (const t of tasks) { left[t] = (left[t] || 0) + 1; ready[t] = 0; } let done = 0, time = 0; while (done < tasks.length) { let pick = null; for (const t in left) if (left[t] > 0 && ready[t] <= time && (pick === null || left[t] > left[pick])) pick = t; if (pick !== null) { left[pick]--; ready[pick] = time + n + 1; done++; } time++; } return time; }`,
    fuzz: gen(`return [__str(rand, __r(rand, 1, 10), "AABBCDE").split(""), __r(rand, 0, 3)];`),
    examples: [[["A", "A", "A", "B", "B", "B"], 2], [["A", "C", "A", "B", "D", "B"], 1], [["A", "A", "A", "B", "B", "B"], 3]],
    edges: [
      ["single", [["A"], 5]],
      ["zeros", [["A", "A", "B"], 0], "With n = 0 nothing ever waits."],
      ["all-equal", [["A", "A", "A"], 2], "One task type: idle between every pair."],
    ],
  },
  design({
    slug: "design-twitter",
    title: "Design Twitter",
    difficulty: "Medium",
    pattern: "Heap / Priority Queue",
    cls: "Twitter",
    methods: ["postTweet(userId, tweetId)", "getNewsFeed(userId)", "follow(followerId, followeeId)", "unfollow(followerId, followeeId)"],
    hints: [
      "Stamp every tweet with a global counter. A feed is the 10 newest tweets among you and the people you follow.",
      "Each user's tweets are already in time order. Merge those lists newest-first with a max-heap holding one tweet per user, and stop after 10.",
      "postTweet: append (time, id) to tweets[user]; time += 1\ngetNewsFeed(u):\n  heap = newest tweet of u and of each followee\n  while heap not empty and feed has < 10:\n    pop newest, add to feed, push that user's previous tweet\nfollow / unfollow: add / remove in follows[u]",
    ],
    reference: `${HEAP} class Twitter { constructor() { this.t = 0; this.tweets = new Map(); this.follows = new Map(); } postTweet(userId, tweetId) { if (!this.tweets.has(userId)) this.tweets.set(userId, []); this.tweets.get(userId).push([this.t++, tweetId]); } getNewsFeed(userId) { const users = new Set([userId, ...(this.follows.get(userId) || [])]); const h = new MinHeap((a, b) => b[0] - a[0]); for (const u of users) { const list = this.tweets.get(u); if (list && list.length) h.push([list[list.length - 1][0], u, list.length - 1]); } const feed = []; while (h.size && feed.length < 10) { const [, u, i] = h.pop(); const list = this.tweets.get(u); feed.push(list[i][1]); if (i > 0) h.push([list[i - 1][0], u, i - 1]); } return feed; } follow(followerId, followeeId) { if (!this.follows.has(followerId)) this.follows.set(followerId, new Set()); this.follows.get(followerId).add(followeeId); } unfollow(followerId, followeeId) { const s = this.follows.get(followerId); if (s) s.delete(followeeId); } }`,
    brute: `class Twitter { constructor() { this.all = []; this.f = {}; } postTweet(userId, tweetId) { this.all.push([userId, tweetId]); } getNewsFeed(userId) { const out = []; for (let i = this.all.length - 1; i >= 0 && out.length < 10; i--) { const [u, id] = this.all[i]; if (u === userId || (this.f[userId] && this.f[userId][u])) out.push(id); } return out; } follow(a, b) { (this.f[a] = this.f[a] || {})[b] = true; } unfollow(a, b) { if (this.f[a]) delete this.f[a][b]; } }`,
    fuzz: gen(`const ops = [["Twitter"]]; let id = 1; const n = __r(rand, 1, 16); for (let i = 0; i < n; i++) { const r = rand(), u = __r(rand, 1, 3); let v = __r(rand, 1, 3); if (v === u) v = (u % 3) + 1; if (r < 0.45) ops.push(["postTweet", u, id++]); else if (r < 0.65) ops.push(["follow", u, v]); else if (r < 0.75) ops.push(["unfollow", u, v]); else ops.push(["getNewsFeed", u]); } return [ops];`),
    examples: [[[["Twitter"], ["postTweet", 1, 5], ["getNewsFeed", 1], ["follow", 1, 2], ["postTweet", 2, 6], ["getNewsFeed", 1], ["unfollow", 1, 2], ["getNewsFeed", 1]]], [[["Twitter"], ["postTweet", 1, 1], ["postTweet", 2, 2], ["getNewsFeed", 2]]]],
    edges: [
      ["empty", [[["Twitter"], ["getNewsFeed", 1]]], "No tweets yet: an empty feed."],
      ["large", [[["Twitter"], ...Array.from({ length: 12 }, (_, i) => ["postTweet", 1 + (i % 2), 100 + i]), ["follow", 1, 2], ["getNewsFeed", 1]]], "Only the 10 newest tweets make the feed."],
      ["no-answer", [[["Twitter"], ["unfollow", 1, 2], ["postTweet", 2, 7], ["getNewsFeed", 1]]], "Unfollowing someone you never followed does nothing."],
    ],
  }),
  {
    slug: "top-k-frequent-words",
    title: "Top K Frequent Words",
    difficulty: "Medium",
    pattern: "Heap / Priority Queue",
    fn: "topKFrequent",
    params: [["words", "string[]"], ["k", "number"]],
    returns: "string[]",
    hints: [
      "Count the words first. The order is: higher count first, and for equal counts the lexicographically smaller word first.",
      "Keep a heap of size k whose top is the worst word kept (lowest count, then the larger word). At the end pop everything and reverse.",
      "count each word\nheap = min-heap ordered by (count asc, word desc)\nfor each distinct word w:\n  push w\n  if heap size > k: pop\nresult = pop all, then reverse\nreturn result",
    ],
    reference: `${HEAP} function topKFrequent(words, k) { const c = new Map(); for (const w of words) c.set(w, (c.get(w) || 0) + 1); const h = new MinHeap((a, b) => c.get(a) - c.get(b) || (a < b ? 1 : a > b ? -1 : 0)); for (const w of c.keys()) { h.push(w); if (h.size > k) h.pop(); } const out = []; while (h.size) out.push(h.pop()); return out.reverse(); }`,
    brute: `function topKFrequent(words, k) { const c = {}; for (const w of words) c[w] = (c[w] || 0) + 1; return Object.keys(c).sort((a, b) => c[b] - c[a] || (a < b ? -1 : 1)).slice(0, k); }`,
    fuzz: gen(`const w = Array.from({ length: __r(rand, 1, 10) }, () => __pick(rand, ["a", "b", "ab", "ba", "c", "cat", "dog"])); return [w, __r(rand, 1, new Set(w).size)];`),
    examples: [[["i", "love", "leetcode", "i", "love", "coding"], 2], [["the", "day", "is", "sunny", "the", "the", "the", "sunny", "is", "is"], 4]],
    edges: [
      ["single", [["x"], 1]],
      ["all-equal", [["b", "a", "c"], 2], "Every count ties, so alphabetical order decides."],
      ["boundary", [["b", "a", "b", "c"], 3], "k is the number of distinct words."],
    ],
  },
  {
    slug: "reorganize-string",
    title: "Reorganize String",
    difficulty: "Medium",
    pattern: "Heap / Priority Queue",
    fn: "reorganizeString",
    params: [["s", "string"]],
    returns: "string",
    compare: "no-adjacent-repeat",
    hints: [
      "It is impossible exactly when one letter appears more than (n + 1) / 2 times. Any valid arrangement is accepted.",
      "Greedy with a max-heap by count: place the most frequent letter that differs from the last one placed, then push it back with one less.",
      "if max count > (n + 1) / 2: return \"\"\nheap = max-heap of (count, letter)\nout = \"\", held = none\nwhile heap not empty:\n  (c, ch) = pop; out += ch\n  if held has count > 0: push held\n  held = (c - 1, ch)\nreturn out",
    ],
    reference: `${HEAP} function reorganizeString(s) { const c = {}; for (const ch of s) c[ch] = (c[ch] || 0) + 1; if (Math.max(...Object.values(c)) > Math.ceil(s.length / 2)) return ""; const h = new MinHeap((a, b) => b[0] - a[0] || (a[1] < b[1] ? -1 : 1)); for (const ch in c) h.push([c[ch], ch]); let out = "", held = null; while (h.size) { const [n, ch] = h.pop(); out += ch; if (held && held[0] > 0) h.push(held); held = [n - 1, ch]; } return out; }`,
    brute: `function reorganizeString(s) { const c = {}; for (const ch of s) c[ch] = (c[ch] || 0) + 1; const keys = Object.keys(c).sort(); const go = (out, left) => { if (!left) return out; let mx = 0; for (const k of keys) mx = Math.max(mx, c[k]); if (mx > Math.ceil(left / 2)) return null; for (const k of keys) { if (!c[k] || out[out.length - 1] === k) continue; c[k]--; const r = go(out + k, left - 1); c[k]++; if (r !== null) return r; } return null; }; const r = go("", s.length); return r === null ? "" : r; }`,
    fuzz: gen(`return [__str(rand, __r(rand, 1, 10), __pick(rand, ["ab", "aab", "aaab", "abc", "aabc"]))];`),
    examples: [["aab"], ["aaab"]],
    edges: [
      ["single-char", ["a"]],
      ["no-answer", ["aaa"], "Three a's cannot be separated."],
      ["boundary", ["aaabb"], "The most frequent letter is exactly (n + 1) / 2."],
    ],
  },
  {
    slug: "ugly-number-ii",
    title: "Ugly Number II",
    difficulty: "Medium",
    pattern: "Heap / Priority Queue",
    fn: "nthUglyNumber",
    params: [["n", "number"]],
    returns: "number",
    hints: [
      "Every ugly number after 1 is a smaller ugly number times 2, 3 or 5.",
      "Pop the smallest from a min-heap, push it times 2, 3 and 5, and skip duplicates with a set. The n-th pop is the answer. (Three pointers do it in O(n).)",
      "heap = [1], seen = {1}\nrepeat n times:\n  x = pop\n  for f in 2, 3, 5:\n    if x * f not in seen: add to seen, push x * f\nreturn x",
    ],
    reference: `${HEAP} function nthUglyNumber(n) { const h = new MinHeap((a, b) => a - b), seen = new Set([1]); h.push(1); let x = 1; for (let i = 0; i < n; i++) { x = h.pop(); for (const f of [2, 3, 5]) if (!seen.has(x * f)) { seen.add(x * f); h.push(x * f); } } return x; }`,
    brute: `function nthUglyNumber(n) { let count = 0; for (let x = 1; ; x++) { let y = x; for (const f of [2, 3, 5]) while (y % f === 0) y /= f; if (y === 1 && ++count === n) return x; } }`,
    fuzz: gen(`return [__r(rand, 1, 200)];`),
    examples: [[10], [1]],
    edges: [
      ["boundary", [7], "7 is not ugly, so the 7th ugly number is 8."],
      ["min-size", [2]],
      ["large", [400]],
    ],
  },
  {
    slug: "find-k-pairs-with-smallest-sums",
    title: "Find K Pairs with Smallest Sums",
    difficulty: "Medium",
    pattern: "Heap / Priority Queue",
    fn: "kSmallestPairs",
    params: [["nums1", "number[]"], ["nums2", "number[]"], ["k", "number"]],
    returns: "number[][]",
    compare: "unordered-outer",
    hints: [
      "Picture a grid where cell (i, j) holds nums1[i] + nums2[j]. Rows and columns are sorted.",
      "Seed a min-heap with (i, 0) for every row. Pop the smallest k times; after popping (i, j), push (i, j + 1).",
      "heap = min-heap of (nums1[i] + nums2[0], i, 0) for each i\nout = []\nwhile heap not empty and len(out) < k:\n  (s, i, j) = pop\n  out.append([nums1[i], nums2[j]])\n  if j + 1 < len(nums2): push (nums1[i] + nums2[j + 1], i, j + 1)\nreturn out",
    ],
    reference: `${HEAP} function kSmallestPairs(nums1, nums2, k) { const h = new MinHeap((a, b) => a[0] - b[0]); for (let i = 0; i < nums1.length && i < k; i++) h.push([nums1[i] + nums2[0], i, 0]); const out = []; while (h.size && out.length < k) { const [, i, j] = h.pop(); out.push([nums1[i], nums2[j]]); if (j + 1 < nums2.length) h.push([nums1[i] + nums2[j + 1], i, j + 1]); } return out; }`,
    brute: `function kSmallestPairs(nums1, nums2, k) { const all = []; for (const a of nums1) for (const b of nums2) all.push([a, b]); return all.sort((x, y) => x[0] + x[1] - y[0] - y[1]).slice(0, k); }`,
    fuzz: gen(`for (;;) { const a = __sorted(rand, __r(rand, 1, 5), -5, 9), b = __sorted(rand, __r(rand, 1, 5), -5, 9), t = a.length * b.length, k = __r(rand, 1, t); const s = []; for (const x of a) for (const y of b) s.push(x + y); s.sort((x, y) => x - y); if (k === t || s[k - 1] !== s[k]) return [a, b, k]; }`),
    examples: [[[1, 7, 11], [2, 4, 6], 3], [[1, 1, 2], [1, 2, 3], 2]],
    edges: [
      ["single", [[1], [1], 1]],
      ["negatives", [[-3, -1], [-2, 4], 2]],
      ["boundary", [[1, 2], [3, 4], 4], "k is every possible pair."],
    ],
  },
  {
    slug: "furthest-building-you-can-reach",
    title: "Furthest Building You Can Reach",
    difficulty: "Medium",
    pattern: "Heap / Priority Queue",
    fn: "furthestBuilding",
    params: [["heights", "number[]"], ["bricks", "number"], ["ladders", "number"]],
    returns: "number",
    hints: [
      "Ladders are worth the most on the biggest climbs. Decide that lazily as you walk.",
      "Push every climb onto a min-heap. When the heap holds more climbs than ladders, the smallest climb must use bricks: pop it and spend. Stop when bricks go negative.",
      "heap = empty min-heap\nfor i in 0 .. n - 2:\n  d = heights[i + 1] - heights[i]\n  if d <= 0: continue\n  push d\n  if heap size > ladders: bricks = bricks - pop\n  if bricks < 0: return i\nreturn n - 1",
    ],
    reference: `${HEAP} function furthestBuilding(heights, bricks, ladders) { const h = new MinHeap((a, b) => a - b); for (let i = 0; i + 1 < heights.length; i++) { const d = heights[i + 1] - heights[i]; if (d <= 0) continue; h.push(d); if (h.size > ladders) bricks -= h.pop(); if (bricks < 0) return i; } return heights.length - 1; }`,
    brute: `function furthestBuilding(heights, bricks, ladders) { const ok = (t) => { const climbs = []; for (let i = 0; i < t; i++) if (heights[i + 1] > heights[i]) climbs.push(heights[i + 1] - heights[i]); climbs.sort((a, b) => b - a); return climbs.slice(ladders).reduce((s, x) => s + x, 0) <= bricks; }; let t = heights.length - 1; while (!ok(t)) t--; return t; }`,
    fuzz: gen(`return [__arr(rand, __r(rand, 1, 10), 1, 10), __r(rand, 0, 10), __r(rand, 0, 3)];`),
    examples: [[[4, 2, 7, 6, 9, 14, 12], 5, 1], [[4, 12, 2, 7, 3, 18, 20, 3, 19], 10, 2], [[14, 3, 19, 3], 17, 0]],
    edges: [
      ["single", [[5], 0, 0]],
      ["zeros", [[1, 5, 1, 2], 0, 0], "No bricks and no ladders: stuck at the first climb."],
      ["reverse-sorted", [[9, 7, 5, 3], 0, 0], "Only downhill: reach the end for free."],
    ],
  },
  {
    slug: "single-threaded-cpu",
    title: "Single-Threaded CPU",
    difficulty: "Medium",
    pattern: "Heap / Priority Queue",
    fn: "getOrder",
    params: [["tasks", "number[][]"]],
    returns: "number[]",
    hints: [
      "Sort task indexes by enqueue time and walk them with a pointer as the clock advances.",
      "Push every task that has arrived into a min-heap keyed by (processing time, index). If the heap is empty, jump the clock to the next arrival.",
      "order = indexes sorted by enqueue time\ntime = 0, p = 0, heap = empty, out = []\nwhile len(out) < n:\n  while p < n and enqueue[order[p]] <= time: push (proc, index); p += 1\n  if heap empty: time = enqueue[order[p]]; continue\n  (d, i) = pop; time = time + d; out.append(i)\nreturn out",
    ],
    reference: `${HEAP} function getOrder(tasks) { const order = tasks.map((_, i) => i).sort((a, b) => tasks[a][0] - tasks[b][0]); const h = new MinHeap((a, b) => a[0] - b[0] || a[1] - b[1]); const out = []; let time = 0, p = 0; while (out.length < tasks.length) { while (p < order.length && tasks[order[p]][0] <= time) { h.push([tasks[order[p]][1], order[p]]); p++; } if (!h.size) { time = tasks[order[p]][0]; continue; } const [d, i] = h.pop(); time += d; out.push(i); } return out; }`,
    brute: `function getOrder(tasks) { const done = tasks.map(() => false), out = []; let time = 0; while (out.length < tasks.length) { let pick = -1; for (let i = 0; i < tasks.length; i++) if (!done[i] && tasks[i][0] <= time && (pick < 0 || tasks[i][1] < tasks[pick][1])) pick = i; if (pick < 0) { time = Math.min(...tasks.filter((_, i) => !done[i]).map((t) => t[0])); continue; } done[pick] = true; time += tasks[pick][1]; out.push(pick); } return out; }`,
    fuzz: gen(`return [Array.from({ length: __r(rand, 1, 8) }, () => [__r(rand, 1, 10), __r(rand, 1, 5)])];`),
    examples: [[[[1, 2], [2, 4], [3, 2], [4, 1]]], [[[7, 10], [7, 12], [7, 5], [7, 4], [7, 2]]]],
    edges: [
      ["single", [[[1, 1]]]],
      ["all-equal", [[[1, 1], [1, 1], [1, 1]]], "Ties break by index."],
      ["boundary", [[[1, 1], [10, 2], [10, 1]]], "The CPU idles until time 10."],
    ],
  },
  design({
    slug: "seat-reservation-manager",
    title: "Seat Reservation Manager",
    difficulty: "Medium",
    pattern: "Heap / Priority Queue",
    cls: "SeatManager",
    ctor: "n",
    methods: ["reserve()", "unreserve(seatNumber)"],
    hints: [
      "reserve always wants the smallest free seat number.",
      "Hand out seats from a counter, and keep unreserved seats in a min-heap. reserve takes from the heap if it has anything, else from the counter.",
      "constructor(n): next = 1, heap = empty min-heap\nreserve():\n  if heap not empty: return pop\n  next = next + 1\n  return next - 1\nunreserve(seat): push seat",
    ],
    reference: `${HEAP} class SeatManager { constructor(n) { this.next = 1; this.h = new MinHeap((a, b) => a - b); } reserve() { return this.h.size ? this.h.pop() : this.next++; } unreserve(seatNumber) { this.h.push(seatNumber); } }`,
    brute: `class SeatManager { constructor(n) { this.taken = new Array(n + 1).fill(false); } reserve() { let i = 1; while (this.taken[i]) i++; this.taken[i] = true; return i; } unreserve(seatNumber) { this.taken[seatNumber] = false; } }`,
    fuzz: gen(`const n = __r(rand, 1, 5), ops = [["SeatManager", n]], taken = []; const m = __r(rand, 1, 14); for (let i = 0; i < m; i++) { if (taken.length < n && (taken.length === 0 || rand() < 0.6)) { let s = 1; while (taken.includes(s)) s++; taken.push(s); ops.push(["reserve"]); } else { const s = taken.splice(__r(rand, 0, taken.length - 1), 1)[0]; ops.push(["unreserve", s]); } } return [ops];`),
    examples: [[[["SeatManager", 5], ["reserve"], ["reserve"], ["unreserve", 2], ["reserve"], ["reserve"], ["reserve"], ["reserve"], ["unreserve", 5]]], [[["SeatManager", 2], ["reserve"], ["reserve"], ["unreserve", 1], ["reserve"]]]],
    edges: [
      ["single", [[["SeatManager", 1], ["reserve"]]]],
      ["order", [[["SeatManager", 4], ["reserve"], ["reserve"], ["reserve"], ["unreserve", 3], ["unreserve", 1], ["reserve"], ["reserve"]]], "Freed seats come back smallest first."],
      ["reuse", [[["SeatManager", 3], ["reserve"], ["unreserve", 1], ["reserve"], ["unreserve", 1], ["reserve"]]]],
    ],
  }),
  {
    slug: "process-tasks-using-servers",
    title: "Process Tasks Using Servers",
    difficulty: "Medium",
    pattern: "Heap / Priority Queue",
    fn: "assignTasks",
    params: [["servers", "number[]"], ["tasks", "number[]"]],
    returns: "number[]",
    hints: [
      "Two kinds of servers: free ones, wanted by (weight, index), and busy ones, wanted by the time they finish.",
      "Keep two heaps. For task j, move every busy server that is done by time max(j, now) to the free heap; if none are free, jump the clock to the earliest finish.",
      "free = heap of (weight, index), busy = heap of (finish, weight, index)\ntime = 0\nfor j in 0 .. m - 1:\n  time = max(time, j)\n  if free empty: time = max(time, busy top finish)\n  move busy servers with finish <= time to free\n  (w, i) = pop free; push (time + tasks[j], w, i) to busy\n  ans[j] = i\nreturn ans",
    ],
    reference: `${HEAP} function assignTasks(servers, tasks) { const free = new MinHeap((a, b) => a[0] - b[0] || a[1] - b[1]), busy = new MinHeap((a, b) => a[0] - b[0] || a[1] - b[1] || a[2] - b[2]); servers.forEach((w, i) => free.push([w, i])); const ans = []; let time = 0; for (let j = 0; j < tasks.length; j++) { time = Math.max(time, j); if (!free.size) time = Math.max(time, busy.peek()[0]); while (busy.size && busy.peek()[0] <= time) { const [, w, i] = busy.pop(); free.push([w, i]); } const [w, i] = free.pop(); busy.push([time + tasks[j], w, i]); ans.push(i); } return ans; }`,
    brute: `function assignTasks(servers, tasks) { const freeAt = servers.map(() => 0), ans = []; let t = 0; for (let j = 0; j < tasks.length; j++) { t = Math.max(t, j); let pick = -1; for (;;) { for (let i = 0; i < servers.length; i++) if (freeAt[i] <= t && (pick < 0 || servers[i] < servers[pick])) pick = i; if (pick >= 0) break; t = Math.min(...freeAt); } freeAt[pick] = t + tasks[j]; ans.push(pick); } return ans; }`,
    fuzz: gen(`return [__arr(rand, __r(rand, 1, 4), 1, 5), __arr(rand, __r(rand, 1, 8), 1, 6)];`),
    examples: [[[3, 3, 2], [1, 2, 3, 2, 1, 2]], [[5, 1, 4, 3, 2], [2, 1, 2, 4, 5, 2, 1]]],
    edges: [
      ["single", [[1], [1]]],
      ["all-equal", [[2, 2, 2], [3, 3, 3, 3]], "Equal weights: the smaller index wins."],
      ["boundary", [[1], [5, 1, 1]], "One server: later tasks queue until it frees up."],
    ],
  },
  {
    slug: "maximum-subsequence-score",
    title: "Maximum Subsequence Score",
    difficulty: "Medium",
    pattern: "Heap / Priority Queue",
    fn: "maxScore",
    params: [["nums1", "number[]"], ["nums2", "number[]"], ["k", "number"]],
    returns: "number",
    hints: [
      "Fix which index supplies the minimum of nums2. Then you want the k - 1 largest nums1 among indexes with nums2 at least that big.",
      "Sort pairs by nums2 descending. Walk them keeping a min-heap of the k largest nums1 and their sum; when the heap holds k, score = sum * current nums2.",
      "pairs = zip(nums1, nums2) sorted by nums2 descending\nheap = min-heap, sum = 0, best = 0\nfor (a, b) in pairs:\n  push a; sum = sum + a\n  if heap size > k: sum = sum - pop\n  if heap size == k: best = max(best, sum * b)\nreturn best",
    ],
    reference: `${HEAP} function maxScore(nums1, nums2, k) { const idx = nums1.map((_, i) => i).sort((a, b) => nums2[b] - nums2[a]); const h = new MinHeap((a, b) => a - b); let sum = 0, best = 0; for (const i of idx) { h.push(nums1[i]); sum += nums1[i]; if (h.size > k) sum -= h.pop(); if (h.size === k) best = Math.max(best, sum * nums2[i]); } return best; }`,
    brute: `function maxScore(nums1, nums2, k) { let best = 0; const n = nums1.length; for (let m = 0; m < 1 << n; m++) { let c = 0, s = 0, mn = Infinity; for (let i = 0; i < n; i++) if (m & (1 << i)) { c++; s += nums1[i]; mn = Math.min(mn, nums2[i]); } if (c === k) best = Math.max(best, s * mn); } return best; }`,
    fuzz: gen(`const n = __r(rand, 1, 8); return [__arr(rand, n, 0, 10), __arr(rand, n, 0, 10), __r(rand, 1, n)];`),
    examples: [[[1, 3, 3, 2], [2, 1, 3, 4], 3], [[4, 2, 3, 1, 1], [7, 5, 10, 9, 6], 1]],
    edges: [
      ["single", [[5], [3], 1]],
      ["zeros", [[0, 0], [0, 5], 1]],
      ["boundary", [[2, 1, 4], [3, 6, 1], 3], "k = n: every index is taken."],
    ],
  },
  {
    slug: "total-cost-to-hire-k-workers",
    title: "Total Cost to Hire K Workers",
    difficulty: "Medium",
    pattern: "Heap / Priority Queue",
    fn: "totalCost",
    params: [["costs", "number[]"], ["k", "number"], ["candidates", "number"]],
    returns: "number",
    hints: [
      "Each round looks only at the first and last `candidates` workers still waiting.",
      "Keep one min-heap for the front window and one for the back window, filled from two pointers that never cross. Take the cheaper top (front wins ties) and refill that side.",
      "lo = 0, hi = n - 1, front = heap, back = heap\nfill front from lo and back from hi, candidates each, while lo <= hi\nrepeat k times:\n  if back empty or (front not empty and front top <= back top): take front top, refill front from lo\n  else: take back top, refill back from hi\n  total = total + taken cost\nreturn total",
    ],
    reference: `${HEAP} function totalCost(costs, k, candidates) { const f = new MinHeap((a, b) => a - b), b = new MinHeap((a, b) => a - b); let lo = 0, hi = costs.length - 1, total = 0; for (let i = 0; i < candidates && lo <= hi; i++) f.push(costs[lo++]); for (let i = 0; i < candidates && lo <= hi; i++) b.push(costs[hi--]); for (let r = 0; r < k; r++) { if (!b.size || (f.size && f.peek() <= b.peek())) { total += f.pop(); if (lo <= hi) f.push(costs[lo++]); } else { total += b.pop(); if (lo <= hi) b.push(costs[hi--]); } } return total; }`,
    brute: `function totalCost(costs, k, candidates) { const a = costs.slice(); let total = 0; for (let r = 0; r < k; r++) { const pool = a.length <= 2 * candidates ? a.map((_, i) => i) : [...Array(candidates).keys(), ...Array.from({ length: candidates }, (_, i) => a.length - candidates + i)]; let best = pool[0]; for (const i of pool) if (a[i] < a[best] || (a[i] === a[best] && i < best)) best = i; total += a[best]; a.splice(best, 1); } return total; }`,
    fuzz: gen(`const n = __r(rand, 1, 10); return [__arr(rand, n, 1, 10), __r(rand, 1, n), __r(rand, 1, n)];`),
    examples: [[[17, 12, 10, 2, 7, 2, 11, 20, 8], 3, 4], [[1, 2, 4, 1], 3, 3]],
    edges: [
      ["single", [[5], 1, 1]],
      ["all-equal", [[3, 3, 3, 3], 2, 1]],
      ["boundary", [[1, 9, 9, 9, 1], 2, 1], "The two windows hold one worker each, at both ends."],
    ],
  },
  design({
    slug: "smallest-number-in-infinite-set",
    title: "Smallest Number in Infinite Set",
    difficulty: "Medium",
    pattern: "Heap / Priority Queue",
    cls: "SmallestInfiniteSet",
    methods: ["popSmallest()", "addBack(num)"],
    hints: [
      "Everything from some number `next` upward is still in the set. Only numbers below `next` that were added back need tracking.",
      "Keep `next` plus a min-heap (and a set, to skip duplicates) of added-back numbers smaller than `next`.",
      "next = 1, heap = empty, inHeap = empty set\npopSmallest():\n  if heap not empty: x = pop; remove x from inHeap; return x\n  next = next + 1\n  return next - 1\naddBack(num):\n  if num < next and num not in inHeap: push num; add to inHeap",
    ],
    reference: `${HEAP} class SmallestInfiniteSet { constructor() { this.next = 1; this.h = new MinHeap((a, b) => a - b); this.in = new Set(); } popSmallest() { if (this.h.size) { const x = this.h.pop(); this.in.delete(x); return x; } return this.next++; } addBack(num) { if (num < this.next && !this.in.has(num)) { this.in.add(num); this.h.push(num); } } }`,
    brute: `class SmallestInfiniteSet { constructor() { this.gone = {}; } popSmallest() { let i = 1; while (this.gone[i]) i++; this.gone[i] = true; return i; } addBack(num) { delete this.gone[num]; } }`,
    fuzz: gen(`const ops = [["SmallestInfiniteSet"]]; const n = __r(rand, 1, 14); for (let i = 0; i < n; i++) ops.push(rand() < 0.6 ? ["popSmallest"] : ["addBack", __r(rand, 1, 8)]); return [ops];`),
    examples: [[[["SmallestInfiniteSet"], ["addBack", 2], ["popSmallest"], ["popSmallest"], ["popSmallest"], ["addBack", 1], ["popSmallest"], ["popSmallest"], ["popSmallest"]]], [[["SmallestInfiniteSet"], ["popSmallest"], ["popSmallest"]]]],
    edges: [
      ["duplicates", [[["SmallestInfiniteSet"], ["popSmallest"], ["addBack", 1], ["addBack", 1], ["popSmallest"], ["popSmallest"]]], "Adding 1 back twice puts it in the set only once."],
      ["no-answer", [[["SmallestInfiniteSet"], ["addBack", 3], ["popSmallest"]]], "3 was never removed, so adding it back changes nothing."],
      ["order", [[["SmallestInfiniteSet"], ["popSmallest"], ["popSmallest"], ["popSmallest"], ["addBack", 3], ["addBack", 1], ["popSmallest"], ["popSmallest"], ["popSmallest"]]]],
    ],
  }),
  {
    slug: "find-the-kth-largest-integer-in-the-array",
    title: "Find the Kth Largest Integer in the Array",
    difficulty: "Medium",
    pattern: "Heap / Priority Queue",
    fn: "kthLargestNumber",
    params: [["nums", "string[]"], ["k", "number"]],
    returns: "string",
    hints: [
      "The numbers can be too long for a double. Without leading zeros, a longer string is a bigger number, and equal lengths compare as strings.",
      "Keep a min-heap of size k using that comparison; its top is the answer.",
      "smaller(a, b) = len(a) < len(b) or (len(a) == len(b) and a < b)\nheap = min-heap using smaller\nfor x in nums:\n  push x\n  if heap size > k: pop\nreturn heap top",
    ],
    reference: `${HEAP} function kthLargestNumber(nums, k) { const h = new MinHeap((a, b) => a.length - b.length || (a < b ? -1 : a > b ? 1 : 0)); for (const x of nums) { h.push(x); if (h.size > k) h.pop(); } return h.peek(); }`,
    brute: `function kthLargestNumber(nums, k) { return nums.slice().sort((a, b) => { const x = BigInt(a), y = BigInt(b); return x > y ? -1 : x < y ? 1 : 0; })[k - 1]; }`,
    fuzz: gen(`const nums = Array.from({ length: __r(rand, 1, 8) }, () => { const len = __r(rand, 1, 6); return len === 1 ? String(__r(rand, 0, 9)) : String(__r(rand, 1, 9)) + __str(rand, len - 1, "0123456789"); }); return [nums, __r(rand, 1, nums.length)];`),
    examples: [[["3", "6", "7", "10"], 4], [["2", "21", "12", "1"], 3], [["0", "0"], 2]],
    edges: [
      ["single", [["5"], 1]],
      ["extremes", [["99999999999999999999", "1"], 1], "Too big for a number type: compare as strings."],
      ["duplicates", [["7", "7", "3"], 2], "Equal values count separately."],
    ],
  },
  {
    slug: "longest-happy-string",
    title: "Longest Happy String",
    difficulty: "Medium",
    pattern: "Heap / Priority Queue",
    fn: "longestDiverseString",
    params: [["a", "number"], ["b", "number"], ["c", "number"]],
    returns: "string",
    compare: "no-triple-repeat",
    hints: [
      "Always try to place the letter with the most copies left, unless that would make three in a row. Any longest happy string is accepted.",
      "Use a max-heap by remaining count. If the top letter would make a triple, place the second one instead and push both back.",
      "heap = max-heap of (count, letter) for counts > 0\nout = \"\"\nwhile heap not empty:\n  (c1, x) = pop\n  if out ends with x x:\n    if heap empty: stop\n    (c2, y) = pop; out += y; push (c1, x); if c2 > 1: push (c2 - 1, y)\n  else: out += x; if c1 > 1: push (c1 - 1, x)\nreturn out",
    ],
    reference: `${HEAP} function longestDiverseString(a, b, c) { const h = new MinHeap((p, q) => q[0] - p[0] || (p[1] < q[1] ? -1 : 1)); for (const [n, ch] of [[a, "a"], [b, "b"], [c, "c"]]) if (n > 0) h.push([n, ch]); let out = ""; while (h.size) { const [n1, x] = h.pop(); if (out.length >= 2 && out[out.length - 1] === x && out[out.length - 2] === x) { if (!h.size) break; const [n2, y] = h.pop(); out += y; h.push([n1, x]); if (n2 > 1) h.push([n2 - 1, y]); } else { out += x; if (n1 > 1) h.push([n1 - 1, x]); } } return out; }`,
    brute: `function longestDiverseString(a, b, c) { const memo = new Map(); const go = (left, last, run) => { const key = left.join(",") + last + run; if (memo.has(key)) return memo.get(key); let best = ""; for (let i = 0; i < 3; i++) { if (!left[i] || (i === last && run === 2)) continue; left[i]--; const r = "abc"[i] + go(left, i, i === last ? run + 1 : 1); left[i]++; if (r.length > best.length) best = r; } memo.set(key, best); return best; }; return go([a, b, c], -1, 0); }`,
    fuzz: gen(`for (;;) { const a = __r(rand, 0, 6), b = __r(rand, 0, 6), c = __r(rand, 0, 6); if (a + b + c > 0) return [a, b, c]; }`),
    examples: [[1, 1, 7], [7, 1, 0]],
    edges: [
      ["single", [0, 0, 1]],
      ["all-equal", [2, 2, 2]],
      ["boundary", [0, 0, 5], "Only one letter: at most two in a row."],
    ],
  },
  design({
    slug: "find-median-from-data-stream",
    title: "Find Median from Data Stream",
    difficulty: "Hard",
    pattern: "Heap / Priority Queue",
    cls: "MedianFinder",
    methods: ["addNum(num)", "findMedian()"],
    hints: [
      "Split the numbers into a smaller half and a larger half. The median sits at the boundary.",
      "Keep a max-heap for the low half and a min-heap for the high half, balanced so low has the same size or one more. The median is low's top, or the average of both tops.",
      "addNum(x):\n  push x to low (max-heap)\n  move low top to high (min-heap)\n  if high size > low size: move high top to low\nfindMedian():\n  if low size > high size: return low top\n  return (low top + high top) / 2",
    ],
    reference: `${HEAP} class MedianFinder { constructor() { this.lo = new MinHeap((a, b) => b - a); this.hi = new MinHeap((a, b) => a - b); } addNum(num) { this.lo.push(num); this.hi.push(this.lo.pop()); if (this.hi.size > this.lo.size) this.lo.push(this.hi.pop()); } findMedian() { return this.lo.size > this.hi.size ? this.lo.peek() : (this.lo.peek() + this.hi.peek()) / 2; } }`,
    brute: `class MedianFinder { constructor() { this.a = []; } addNum(num) { let i = 0; while (i < this.a.length && this.a[i] < num) i++; this.a.splice(i, 0, num); } findMedian() { const n = this.a.length, m = n >> 1; return n % 2 ? this.a[m] : (this.a[m - 1] + this.a[m]) / 2; } }`,
    fuzz: gen(`const ops = [["MedianFinder"], ["addNum", __r(rand, -5, 9)]]; const n = __r(rand, 1, 14); for (let i = 0; i < n; i++) ops.push(rand() < 0.55 ? ["addNum", __r(rand, -5, 9)] : ["findMedian"]); return [ops];`),
    examples: [[[["MedianFinder"], ["addNum", 1], ["addNum", 2], ["findMedian"], ["addNum", 3], ["findMedian"]]], [[["MedianFinder"], ["addNum", 5], ["findMedian"]]]],
    edges: [
      ["duplicates", [[["MedianFinder"], ["addNum", 4], ["addNum", 4], ["addNum", 4], ["findMedian"]]]],
      ["negatives", [[["MedianFinder"], ["addNum", -1], ["addNum", -2], ["findMedian"], ["addNum", -3], ["findMedian"]]]],
      ["reverse-sorted", [[["MedianFinder"], ["addNum", 9], ["addNum", 7], ["addNum", 5], ["addNum", 3], ["findMedian"]]]],
    ],
  }),
  {
    slug: "meeting-rooms-iii",
    title: "Meeting Rooms III",
    difficulty: "Hard",
    pattern: "Heap / Priority Queue",
    fn: "mostBooked",
    params: [["n", "number"], ["meetings", "number[][]"]],
    returns: "number",
    hints: [
      "Process meetings by start time. A meeting takes the lowest-numbered free room; if none is free, it waits for the room that frees up first and keeps its length.",
      "Keep a min-heap of free room numbers and a min-heap of (end time, room) for busy rooms. Before each meeting, release every room whose end <= start.",
      "sort meetings by start\nfree = heap of 0 .. n - 1, busy = heap of (end, room)\nfor (s, e) in meetings:\n  release busy rooms with end <= s into free\n  if free not empty: r = pop free; push (e, r) to busy\n  else: (end, r) = pop busy; push (end + e - s, r) to busy\n  count[r] += 1\nreturn the room with the highest count (lowest index on ties)",
    ],
    reference: `${HEAP} function mostBooked(n, meetings) { const ms = meetings.slice().sort((a, b) => a[0] - b[0]); const free = new MinHeap((a, b) => a - b), busy = new MinHeap((a, b) => a[0] - b[0] || a[1] - b[1]); for (let i = 0; i < n; i++) free.push(i); const cnt = new Array(n).fill(0); for (const [s, e] of ms) { while (busy.size && busy.peek()[0] <= s) free.push(busy.pop()[1]); let r; if (free.size) { r = free.pop(); busy.push([e, r]); } else { const [end, room] = busy.pop(); r = room; busy.push([end + e - s, r]); } cnt[r]++; } let best = 0; for (let i = 1; i < n; i++) if (cnt[i] > cnt[best]) best = i; return best; }`,
    brute: `function mostBooked(n, meetings) { const ms = meetings.slice().sort((a, b) => a[0] - b[0]), end = new Array(n).fill(0), cnt = new Array(n).fill(0); for (const [s, e] of ms) { let r = -1; for (let i = 0; i < n; i++) if (end[i] <= s) { r = i; break; } if (r >= 0) end[r] = e; else { r = 0; for (let i = 1; i < n; i++) if (end[i] < end[r]) r = i; end[r] += e - s; } cnt[r]++; } return cnt.indexOf(Math.max(...cnt)); }`,
    fuzz: gen(`const starts = __shuffle(rand, Array.from({ length: 16 }, (_, i) => i)).slice(0, __r(rand, 1, 8)); return [__r(rand, 1, 3), starts.map((s) => [s, s + __r(rand, 1, 5)])];`),
    examples: [[2, [[0, 10], [1, 5], [2, 7], [3, 4]]], [3, [[1, 20], [2, 10], [3, 5], [4, 9], [6, 8]]]],
    edges: [
      ["single", [1, [[0, 1]]]],
      ["boundary", [2, [[0, 5], [1, 5]]], "Both rooms host one meeting: the lower number wins."],
      ["order", [2, [[4, 6], [0, 3], [2, 5]]], "Meetings arrive unsorted."],
    ],
  },
  {
    slug: "ipo",
    title: "IPO",
    difficulty: "Hard",
    pattern: "Heap / Priority Queue",
    fn: "findMaximizedCapital",
    params: [["k", "number"], ["w", "number"], ["profits", "number[]"], ["capital", "number[]"]],
    returns: "number",
    hints: [
      "Capital only grows, so once a project is affordable it stays affordable. Each round take the most profitable affordable project.",
      "Sort projects by capital. Each round, push every newly affordable project's profit into a max-heap, then pop the best. Stop early if the heap is empty.",
      "projects sorted by capital, p = 0, heap = max-heap\nrepeat k times:\n  while p < n and capital of project p <= w: push its profit; p += 1\n  if heap empty: stop\n  w = w + pop\nreturn w",
    ],
    reference: `${HEAP} function findMaximizedCapital(k, w, profits, capital) { const idx = profits.map((_, i) => i).sort((a, b) => capital[a] - capital[b]); const h = new MinHeap((a, b) => b - a); let p = 0; for (let r = 0; r < k; r++) { while (p < idx.length && capital[idx[p]] <= w) h.push(profits[idx[p++]]); if (!h.size) break; w += h.pop(); } return w; }`,
    brute: `function findMaximizedCapital(k, w, profits, capital) { const used = profits.map(() => false); for (let r = 0; r < k; r++) { let pick = -1; for (let i = 0; i < profits.length; i++) if (!used[i] && capital[i] <= w && (pick < 0 || profits[i] > profits[pick])) pick = i; if (pick < 0) break; used[pick] = true; w += profits[pick]; } return w; }`,
    fuzz: gen(`const n = __r(rand, 1, 8); return [__r(rand, 1, n + 1), __r(rand, 0, 5), __arr(rand, n, 0, 10), __arr(rand, n, 0, 10)];`),
    examples: [[2, 0, [1, 2, 3], [0, 1, 1]], [3, 0, [1, 2, 3], [0, 1, 2]]],
    edges: [
      ["no-answer", [2, 0, [5], [1]], "Nothing is affordable at the start."],
      ["single", [1, 3, [4], [3]]],
      ["boundary", [5, 1, [1, 1], [0, 1]], "k is larger than the number of projects."],
    ],
  },
  {
    slug: "the-skyline-problem",
    title: "The Skyline Problem",
    difficulty: "Hard",
    pattern: "Heap / Priority Queue",
    fn: "getSkyline",
    params: [["buildings", "number[][]"]],
    returns: "number[][]",
    hints: [
      "The outline only changes at a building's left or right edge. At each such x, the height is the tallest building covering x.",
      "Sweep the edges left to right. A max-heap of (height, right) holds active buildings; drop tops whose right <= x. Emit [x, height] when the max height changes.",
      "xs = sorted distinct lefts and rights\nheap = max-heap of (height, right), i = 0, out = []\nfor x in xs:\n  while i < n and left[i] <= x: push (height[i], right[i]); i += 1\n  while heap not empty and heap top right <= x: pop\n  h = heap top height, or 0\n  if out empty or out last height != h: out.append([x, h])\nreturn out",
    ],
    reference: `${HEAP} function getSkyline(buildings) { const xs = [...new Set(buildings.flatMap((b) => [b[0], b[1]]))].sort((a, b) => a - b); const h = new MinHeap((a, b) => b[0] - a[0]); const out = []; let i = 0; for (const x of xs) { while (i < buildings.length && buildings[i][0] <= x) { h.push([buildings[i][2], buildings[i][1]]); i++; } while (h.size && h.peek()[1] <= x) h.pop(); const ht = h.size ? h.peek()[0] : 0; if (!out.length || out[out.length - 1][1] !== ht) out.push([x, ht]); } return out; }`,
    brute: `function getSkyline(buildings) { const xs = [...new Set(buildings.flatMap((b) => [b[0], b[1]]))].sort((a, b) => a - b); const out = []; for (const x of xs) { let ht = 0; for (const [l, r, hh] of buildings) if (l <= x && x < r) ht = Math.max(ht, hh); if (!out.length || out[out.length - 1][1] !== ht) out.push([x, ht]); } return out; }`,
    fuzz: gen(`return [Array.from({ length: __r(rand, 1, 6) }, () => { const l = __r(rand, 0, 10); return [l, l + __r(rand, 1, 6), __r(rand, 1, 8)]; }).sort((a, b) => a[0] - b[0])];`),
    examples: [[[[2, 9, 10], [3, 7, 15], [5, 12, 12], [15, 20, 10], [19, 24, 8]]], [[[0, 2, 3], [2, 5, 3]]]],
    edges: [
      ["single", [[[1, 2, 1]]]],
      ["duplicates", [[[1, 5, 3], [1, 5, 3]]], "Two identical buildings draw one outline."],
      ["order", [[[1, 10, 5], [2, 3, 8]]], "A tall narrow building inside a wide one."],
    ],
  },
  {
    slug: "maximum-performance-of-a-team",
    title: "Maximum Performance of a Team",
    difficulty: "Hard",
    pattern: "Heap / Priority Queue",
    fn: "maxPerformance",
    params: [["n", "number"], ["speed", "number[]"], ["efficiency", "number[]"], ["k", "number"]],
    returns: "number",
    hints: [
      "Fix the engineer with the lowest efficiency on the team. Everyone else must be at least as efficient, and you want their k - 1 largest speeds.",
      "Sort by efficiency descending. Keep a min-heap of at most k speeds with their sum; at each engineer, performance = sum * their efficiency. Take the answer modulo 1e9+7 at the end.",
      "sort engineers by efficiency descending\nheap = min-heap, sum = 0, best = 0\nfor (s, e) in engineers:\n  push s; sum = sum + s\n  if heap size > k: sum = sum - pop\n  best = max(best, sum * e)\nreturn best mod 1000000007",
    ],
    reference: `${HEAP} function maxPerformance(n, speed, efficiency, k) { const idx = speed.map((_, i) => i).sort((a, b) => efficiency[b] - efficiency[a]); const h = new MinHeap((a, b) => a - b); let sum = 0, best = 0; for (const i of idx) { h.push(speed[i]); sum += speed[i]; if (h.size > k) sum -= h.pop(); best = Math.max(best, sum * efficiency[i]); } return best % 1000000007; }`,
    brute: `function maxPerformance(n, speed, efficiency, k) { let best = 0; for (let m = 1; m < 1 << n; m++) { let c = 0, s = 0, e = Infinity; for (let i = 0; i < n; i++) if (m & (1 << i)) { c++; s += speed[i]; e = Math.min(e, efficiency[i]); } if (c <= k) best = Math.max(best, s * e); } return best % 1000000007; }`,
    fuzz: gen(`const n = __r(rand, 1, 8); return [n, __arr(rand, n, 1, 10), __arr(rand, n, 1, 10), __r(rand, 1, n)];`),
    examples: [[6, [2, 10, 3, 1, 5, 8], [5, 4, 3, 9, 7, 2], 2], [6, [2, 10, 3, 1, 5, 8], [5, 4, 3, 9, 7, 2], 3], [6, [2, 10, 3, 1, 5, 8], [5, 4, 3, 9, 7, 2], 4]],
    edges: [
      ["single", [1, [7], [3], 1]],
      ["boundary", [3, [1, 1, 1], [9, 9, 9], 3], "Taking everyone is best when nobody lowers the efficiency."],
      ["extremes", [2, [100000, 1], [100000, 100000], 1]],
    ],
  },
  {
    slug: "smallest-range-covering-elements-from-k-lists",
    title: "Smallest Range Covering Elements from K Lists",
    difficulty: "Hard",
    pattern: "Heap / Priority Queue",
    fn: "smallestRange",
    params: [["nums", "number[][]"]],
    returns: "number[]",
    hints: [
      "A range covering one value from every list is [min, max] of one chosen element per list. To shrink it, the only useful move is to advance the list holding the minimum.",
      "Put the first element of each list in a min-heap and track the current max. Pop the min, record [min, max] if it is better, then push that list's next element. Stop when a list runs out.",
      "heap = (nums[i][0], i, 0) for each list, hi = max of those\nbest = none\nloop:\n  (lo, i, j) = pop\n  if best is none or hi - lo < best width: best = [lo, hi]\n  if j + 1 == len(nums[i]): return best\n  push (nums[i][j + 1], i, j + 1); hi = max(hi, nums[i][j + 1])",
    ],
    reference: `${HEAP} function smallestRange(nums) { const h = new MinHeap((a, b) => a[0] - b[0]); let hi = -Infinity; nums.forEach((l, i) => { h.push([l[0], i, 0]); hi = Math.max(hi, l[0]); }); let best = null; for (;;) { const [lo, i, j] = h.pop(); if (!best || hi - lo < best[1] - best[0]) best = [lo, hi]; if (j + 1 === nums[i].length) return best; const v = nums[i][j + 1]; h.push([v, i, j + 1]); hi = Math.max(hi, v); } }`,
    brute: `function smallestRange(nums) { const vals = [...new Set(nums.flat())].sort((a, b) => a - b); let best = null; for (const a of vals) for (const b of vals) { if (b < a) continue; if (!nums.every((l) => l.some((x) => x >= a && x <= b))) continue; if (!best || b - a < best[1] - best[0] || (b - a === best[1] - best[0] && a < best[0])) best = [a, b]; } return best; }`,
    fuzz: gen(`return [Array.from({ length: __r(rand, 1, 4) }, () => __sorted(rand, __r(rand, 1, 4), -5, 15))];`),
    examples: [[[[4, 10, 15, 24, 26], [0, 9, 12, 20], [5, 18, 22, 30]]], [[[1, 2, 3], [1, 2, 3], [1, 2, 3]]]],
    edges: [
      ["single", [[[5]]]],
      ["negatives", [[[-5, -1], [-3, 2]]]],
      ["duplicates", [[[1, 1, 4], [4, 4]]]],
    ],
  },
  {
    slug: "minimum-number-of-refueling-stops",
    title: "Minimum Number of Refueling Stops",
    difficulty: "Hard",
    pattern: "Heap / Priority Queue",
    fn: "minRefuelStops",
    params: [["target", "number"], ["startFuel", "number"], ["stations", "number[][]"]],
    returns: "number",
    hints: [
      "Drive as far as you can. When you run dry, you could have stopped at any station you already passed; pretend you did, at the one with the most fuel.",
      "Push each passed station's fuel into a max-heap. While the tank cannot reach the next point, pop the largest and count a stop; if the heap is empty, return -1.",
      "heap = max-heap, reach = startFuel, stops = 0\nfor (pos, fuel) in stations + [(target, 0)]:\n  while reach < pos:\n    if heap empty: return -1\n    reach = reach + pop; stops += 1\n  push fuel\nreturn stops",
    ],
    reference: `${HEAP} function minRefuelStops(target, startFuel, stations) { const h = new MinHeap((a, b) => b - a); let reach = startFuel, stops = 0; for (const [pos, fuel] of [...stations, [target, 0]]) { while (reach < pos) { if (!h.size) return -1; reach += h.pop(); stops++; } h.push(fuel); } return stops; }`,
    brute: `function minRefuelStops(target, startFuel, stations) { const n = stations.length, dp = new Array(n + 1).fill(-Infinity); dp[0] = startFuel; for (let i = 0; i < n; i++) for (let t = i; t >= 0; t--) if (dp[t] >= stations[i][0]) dp[t + 1] = Math.max(dp[t + 1], dp[t] + stations[i][1]); for (let t = 0; t <= n; t++) if (dp[t] >= target) return t; return -1; }`,
    fuzz: gen(`const target = __r(rand, 2, 30); const pos = __shuffle(rand, Array.from({ length: target - 1 }, (_, i) => i + 1)).slice(0, __r(rand, 0, Math.min(6, target - 1))).sort((a, b) => a - b); return [target, __r(rand, 1, 15), pos.map((p) => [p, __r(rand, 1, 10)])];`),
    examples: [[1, 1, []], [100, 1, [[10, 100]]], [100, 10, [[10, 60], [20, 30], [30, 30], [60, 40]]]],
    edges: [
      ["empty", [10, 10, []], "No stations, but the tank is exactly enough."],
      ["no-answer", [10, 1, [[5, 10]]], "The first station is out of reach."],
      ["boundary", [20, 10, [[10, 10]]], "Arrive at the station with an empty tank: that still counts."],
    ],
  },
  {
    slug: "minimize-deviation-in-array",
    title: "Minimize Deviation in Array",
    difficulty: "Hard",
    pattern: "Heap / Priority Queue",
    fn: "minimumDeviation",
    params: [["nums", "number[]"]],
    returns: "number",
    hints: [
      "Odd numbers can only double once; even numbers can only halve. Double every odd number first, so every value can only go down from there.",
      "Now the only useful move is to halve the current maximum while it is even. Keep a max-heap and the current minimum; record max - min after each step.",
      "for each x: if x is odd: x = 2x\nheap = max-heap of nums, lo = min(nums), best = infinity\nloop:\n  hi = pop\n  best = min(best, hi - lo)\n  if hi is odd: return best\n  lo = min(lo, hi / 2); push hi / 2",
    ],
    reference: `${HEAP} function minimumDeviation(nums) { const h = new MinHeap((a, b) => b - a); let lo = Infinity; for (const x of nums) { const v = x % 2 ? x * 2 : x; h.push(v); lo = Math.min(lo, v); } let best = Infinity; for (;;) { const hi = h.pop(); best = Math.min(best, hi - lo); if (hi % 2) return best; lo = Math.min(lo, hi / 2); h.push(hi / 2); } }`,
    brute: `function minimumDeviation(nums) { const opts = nums.map((x) => { const o = []; if (x % 2) o.push(x, 2 * x); else { let y = x; o.push(y); while (y % 2 === 0) { y /= 2; o.push(y); } } return o.sort((a, b) => a - b); }); let best = Infinity; for (const L of opts.flat()) { let hi = L, ok = true; for (const o of opts) { const v = o.find((y) => y >= L); if (v === undefined) { ok = false; break; } hi = Math.max(hi, v); } if (ok) best = Math.min(best, hi - L); } return best; }`,
    fuzz: gen(`return [__arr(rand, __r(rand, 2, 6), 1, 40)];`),
    examples: [[[1, 2, 3, 4]], [[4, 1, 5, 20, 3]], [[2, 10, 8]]],
    edges: [
      ["two", [[3, 5]]],
      ["all-equal", [[7, 7, 7]]],
      ["extremes", [[1, 1000000000]], "A huge even number halves many times."],
    ],
  },
  {
    slug: "trapping-rain-water-ii",
    title: "Trapping Rain Water II",
    difficulty: "Hard",
    pattern: "Heap / Priority Queue",
    fn: "trapRainWater",
    params: [["heightMap", "number[][]"]],
    returns: "number",
    hints: [
      "Water escapes through the lowest point of the wall around it. Start with the border as the wall and always work from its lowest cell inward.",
      "Push every border cell into a min-heap. Pop the lowest; for each unvisited neighbour, it holds max(0, wall - height) water, and enters the heap with height max(wall, its height).",
      "heap = min-heap of border cells (height, r, c); mark them visited\nwater = 0\nwhile heap not empty:\n  (h, r, c) = pop\n  for each unvisited neighbour (nr, nc):\n    mark visited\n    water = water + max(0, h - height[nr][nc])\n    push (max(h, height[nr][nc]), nr, nc)\nreturn water",
    ],
    reference: `${HEAP} function trapRainWater(heightMap) { const m = heightMap.length, n = heightMap[0].length, seen = heightMap.map((r) => r.map(() => false)); const h = new MinHeap((a, b) => a[0] - b[0]); for (let r = 0; r < m; r++) for (let c = 0; c < n; c++) if (r === 0 || c === 0 || r === m - 1 || c === n - 1) { seen[r][c] = true; h.push([heightMap[r][c], r, c]); } let water = 0; while (h.size) { const [ht, r, c] = h.pop(); for (const [dr, dc] of [[1, 0], [-1, 0], [0, 1], [0, -1]]) { const nr = r + dr, nc = c + dc; if (nr < 0 || nc < 0 || nr >= m || nc >= n || seen[nr][nc]) continue; seen[nr][nc] = true; water += Math.max(0, ht - heightMap[nr][nc]); h.push([Math.max(ht, heightMap[nr][nc]), nr, nc]); } } return water; }`,
    brute: `function trapRainWater(heightMap) { const m = heightMap.length, n = heightMap[0].length; const lvl = heightMap.map((row, r) => row.map((v, c) => (r === 0 || c === 0 || r === m - 1 || c === n - 1 ? v : Infinity))); let changed = true; while (changed) { changed = false; for (let r = 1; r < m - 1; r++) for (let c = 1; c < n - 1; c++) { const v = Math.max(heightMap[r][c], Math.min(lvl[r - 1][c], lvl[r + 1][c], lvl[r][c - 1], lvl[r][c + 1])); if (v < lvl[r][c]) { lvl[r][c] = v; changed = true; } } } let w = 0; for (let r = 0; r < m; r++) for (let c = 0; c < n; c++) w += lvl[r][c] - heightMap[r][c]; return w; }`,
    fuzz: gen(`const m = __r(rand, 1, 5), n = __r(rand, 1, 5); return [Array.from({ length: m }, () => __arr(rand, n, 0, 6))];`),
    examples: [[[[1, 4, 3, 1, 3, 2], [3, 2, 1, 3, 2, 4], [2, 3, 3, 2, 3, 1]]], [[[3, 3, 3, 3, 3], [3, 2, 2, 2, 3], [3, 2, 1, 2, 3], [3, 2, 2, 2, 3], [3, 3, 3, 3, 3]]]],
    edges: [
      ["single", [[[5]]]],
      ["min-size", [[[1, 2], [3, 4]]], "Every cell is on the border: nothing is trapped."],
      ["boundary", [[[3, 3, 3], [3, 0, 1], [3, 3, 3]]], "The wall has a low point at 1, so the pit only fills to 1."],
    ],
  },
];

export const LADDER_HEAPS_SEEDED: ProblemSpec[] = DEFS.map((d) => define(d).spec);
