import { define, type ProblemDef } from "../../dsa-extras/define";
import { gen } from "../../dsa-extras/gen";
import type { ProblemSpec } from "../types";

const D1 = "1-D Dynamic Programming";
const D2 = "2-D Dynamic Programming";

/** Judges for the DP Ladder: strings, stocks with a trade limit, and interval / partition DP. */
const DEFS: ProblemDef[] = [
  {
    slug: "longest-palindromic-subsequence",
    title: "Longest Palindromic Subsequence",
    difficulty: "Medium",
    pattern: D2,
    fn: "longestPalindromeSubseq",
    params: [["s", "string"]],
    returns: "number",
    hints: [
      "Look at the two ends of s[i..j]: equal ends can both be kept; otherwise drop one of them.",
      "Interval DP: L[i][j] = L[i + 1][j - 1] + 2 when s[i] == s[j], else max(L[i + 1][j], L[i][j - 1]). Fill by increasing length (or i from the right).",
      "L = n x n zeros; L[i][i] = 1\nfor i from n - 1 down to 0:\n  for j in i + 1 .. n - 1:\n    if s[i] == s[j]: L[i][j] = L[i + 1][j - 1] + 2\n    else: L[i][j] = max(L[i + 1][j], L[i][j - 1])\nreturn L[0][n - 1]",
    ],
    reference: `function longestPalindromeSubseq(s) { const n = s.length, L = Array.from({ length: n }, () => new Array(n).fill(0)); for (let i = n - 1; i >= 0; i--) { L[i][i] = 1; for (let j = i + 1; j < n; j++) L[i][j] = s[i] === s[j] ? (i + 1 <= j - 1 ? L[i + 1][j - 1] : 0) + 2 : Math.max(L[i + 1][j], L[i][j - 1]); } return L[0][n - 1]; }`,
    brute: `function longestPalindromeSubseq(s) { const n = s.length; let best = 0; for (let m = 1; m < 1 << n; m++) { let t = ""; for (let i = 0; i < n; i++) if ((m >> i) & 1) t += s[i]; if (t.length > best && t === t.split("").reverse().join("")) best = t.length; } return best; }`,
    fuzz: gen(`return [__str(rand, __r(rand, 1, 12), "abc")];`),
    examples: [["bbbab"], ["cbbd"]],
    edges: [
      ["single-char", ["a"]],
      ["all-equal", ["aaaa"]],
      ["boundary", ["abcde"], "No two letters match: 1."],
    ],
  },
  {
    slug: "delete-operation-for-two-strings",
    title: "Delete Operation for Two Strings",
    difficulty: "Medium",
    pattern: D2,
    fn: "minDistance",
    params: [["word1", "string"], ["word2", "string"]],
    returns: "number",
    hints: [
      "Whatever survives the deletions is a common subsequence, and you want to keep as much as possible.",
      "Find the longest common subsequence; the answer is len(word1) + len(word2) - 2 * LCS.",
      "L = (m + 1) x (n + 1) zeros\nfor i in 1 .. m:\n  for j in 1 .. n:\n    if word1[i - 1] == word2[j - 1]: L[i][j] = L[i - 1][j - 1] + 1\n    else: L[i][j] = max(L[i - 1][j], L[i][j - 1])\nreturn m + n - 2 * L[m][n]",
    ],
    reference: `function minDistance(word1, word2) { const m = word1.length, n = word2.length, L = Array.from({ length: m + 1 }, () => new Array(n + 1).fill(0)); for (let i = 1; i <= m; i++) for (let j = 1; j <= n; j++) L[i][j] = word1[i - 1] === word2[j - 1] ? L[i - 1][j - 1] + 1 : Math.max(L[i - 1][j], L[i][j - 1]); return m + n - 2 * L[m][n]; }`,
    brute: `function minDistance(word1, word2) { const go = (i, j) => { if (i === word1.length) return word2.length - j; if (j === word2.length) return word1.length - i; if (word1[i] === word2[j]) return go(i + 1, j + 1); return 1 + Math.min(go(i + 1, j), go(i, j + 1)); }; return go(0, 0); }`,
    fuzz: gen(`return [__str(rand, __r(rand, 1, 7), "abc"), __str(rand, __r(rand, 1, 7), "abc")];`),
    examples: [["sea", "eat"], ["leetcode", "etco"]],
    edges: [
      ["single-char", ["a", "b"]],
      ["duplicates", ["abc", "abc"], "Already equal: 0."],
      ["boundary", ["abc", "def"], "Nothing in common: delete everything."],
    ],
  },
  {
    slug: "minimum-insertion-steps-to-make-a-string-palindrome",
    title: "Minimum Insertion Steps to Make a String Palindrome",
    difficulty: "Hard",
    pattern: D2,
    fn: "minInsertions",
    params: [["s", "string"]],
    returns: "number",
    hints: [
      "Characters that already pair up into a palindrome need no help; every other character needs one inserted partner.",
      "The answer is n minus the longest palindromic subsequence. Or directly: f(i, j) = f(i + 1, j - 1) if the ends match, else 1 + min(f(i + 1, j), f(i, j - 1)).",
      "f = n x n zeros\nfor i from n - 1 down to 0:\n  for j in i + 1 .. n - 1:\n    if s[i] == s[j]: f[i][j] = f[i + 1][j - 1]\n    else: f[i][j] = 1 + min(f[i + 1][j], f[i][j - 1])\nreturn f[0][n - 1]",
    ],
    reference: `function minInsertions(s) { const n = s.length, f = Array.from({ length: n + 1 }, () => new Array(n + 1).fill(0)); for (let i = n - 1; i >= 0; i--) for (let j = i + 1; j < n; j++) f[i][j] = s[i] === s[j] ? f[i + 1][j - 1] : 1 + Math.min(f[i + 1][j], f[i][j - 1]); return f[0][n - 1]; }`,
    brute: `function minInsertions(s) { const go = (i, j) => { if (i >= j) return 0; if (s[i] === s[j]) return go(i + 1, j - 1); return 1 + Math.min(go(i + 1, j), go(i, j - 1)); }; return go(0, s.length - 1); }`,
    fuzz: gen(`return [__str(rand, __r(rand, 1, 11), "abc")];`),
    examples: [["zzazz"], ["mbadm"], ["leetcode"]],
    edges: [
      ["single-char", ["g"]],
      ["two", ["ab"]],
      ["reverse-sorted", ["dcba"], "All distinct: n - 1 insertions."],
    ],
  },
  {
    slug: "distinct-subsequences",
    title: "Distinct Subsequences",
    difficulty: "Hard",
    pattern: D2,
    fn: "numDistinct",
    params: [["s", "string"], ["t", "string"]],
    returns: "number",
    hints: [
      "Count how many ways you can pick positions in s that spell t. When s[i] == t[j] you may use it or skip it; otherwise you must skip it.",
      "ways[j] = number of ways to build t[0..j) from the prefix of s seen so far. For each character of s, update j from right to left so each s character is used once.",
      "ways = array of len(t) + 1 zeros; ways[0] = 1\nfor ch in s:\n  for j from len(t) down to 1:\n    if t[j - 1] == ch: ways[j] += ways[j - 1]\nreturn ways[len(t)]",
    ],
    reference: `function numDistinct(s, t) { const w = new Array(t.length + 1).fill(0); w[0] = 1; for (const ch of s) for (let j = t.length; j >= 1; j--) if (t[j - 1] === ch) w[j] += w[j - 1]; return w[t.length]; }`,
    brute: `function numDistinct(s, t) { const go = (i, j) => { if (j === t.length) return 1; if (s.length - i < t.length - j) return 0; return go(i + 1, j) + (s[i] === t[j] ? go(i + 1, j + 1) : 0); }; return go(0, 0); }`,
    fuzz: gen(`return [__str(rand, __r(rand, 1, 12), "ab"), __str(rand, __r(rand, 1, 4), "ab")];`),
    examples: [["rabbbit", "rabbit"], ["babgbag", "bag"]],
    edges: [
      ["no-answer", ["abc", "abcd"], "t is longer than s."],
      ["all-equal", ["aaaa", "aa"], "Choose 2 of 4 positions: 6."],
      ["single-char", ["a", "a"]],
    ],
  },
  {
    slug: "wildcard-matching",
    title: "Wildcard Matching",
    difficulty: "Hard",
    pattern: D2,
    fn: "isMatch",
    params: [["s", "string"], ["p", "string"]],
    returns: "boolean",
    hints: [
      "'?' matches one character and '*' matches any sequence, including the empty one. The whole string must match.",
      "dp[i][j]: does s[0..i) match p[0..j)? A '*' can match nothing (dp[i][j - 1]) or one more character (dp[i - 1][j]).",
      "dp = (m + 1) x (n + 1) false; dp[0][0] = true\nfor j in 1 .. n: dp[0][j] = dp[0][j - 1] and p[j - 1] == '*'\nfor i in 1 .. m:\n  for j in 1 .. n:\n    if p[j - 1] == '*': dp[i][j] = dp[i][j - 1] or dp[i - 1][j]\n    else: dp[i][j] = dp[i - 1][j - 1] and (p[j - 1] == '?' or p[j - 1] == s[i - 1])\nreturn dp[m][n]",
    ],
    reference: `function isMatch(s, p) { const m = s.length, n = p.length, dp = Array.from({ length: m + 1 }, () => new Array(n + 1).fill(false)); dp[0][0] = true; for (let j = 1; j <= n; j++) dp[0][j] = dp[0][j - 1] && p[j - 1] === "*"; for (let i = 1; i <= m; i++) for (let j = 1; j <= n; j++) dp[i][j] = p[j - 1] === "*" ? dp[i][j - 1] || dp[i - 1][j] : dp[i - 1][j - 1] && (p[j - 1] === "?" || p[j - 1] === s[i - 1]); return dp[m][n]; }`,
    brute: `function isMatch(s, p) { return new RegExp("^" + p.split("").map((c) => (c === "*" ? ".*" : c === "?" ? "." : c)).join("") + "$").test(s); }`,
    fuzz: gen(`const s = __str(rand, __r(rand, 0, 8), "ab"); let p = ""; for (let i = 0; i < __r(rand, 0, 6); i++) { const x = rand(); p += x < 0.25 ? "*" : x < 0.45 ? "?" : __pick(rand, ["a", "b"]); } return [s, p];`),
    examples: [["aa", "a"], ["aa", "*"], ["cb", "?a"]],
    edges: [
      ["empty", ["", "***"], "Stars can match nothing."],
      ["boundary", ["adceb", "*a*b"]],
      ["no-answer", ["acdcb", "a*c?b"]],
    ],
  },
  {
    slug: "regular-expression-matching",
    title: "Regular Expression Matching",
    difficulty: "Hard",
    pattern: D2,
    fn: "isMatch",
    params: [["s", "string"], ["p", "string"]],
    returns: "boolean",
    hints: [
      "'.' matches any one character and 'x*' means zero or more copies of x. The whole string must match.",
      "dp[i][j]: does s[0..i) match p[0..j)? For 'x*': use zero copies (dp[i][j - 2]) or, if x matches s[i - 1], one more copy (dp[i - 1][j]).",
      "dp = (m + 1) x (n + 1) false; dp[0][0] = true\nfor j in 2 .. n: dp[0][j] = p[j - 1] == '*' and dp[0][j - 2]\nmatch(i, j) = p[j - 1] == '.' or p[j - 1] == s[i - 1]\nfor i in 1 .. m:\n  for j in 1 .. n:\n    if p[j - 1] == '*':\n      dp[i][j] = dp[i][j - 2] or (match(i, j - 1) and dp[i - 1][j])\n    else: dp[i][j] = match(i, j) and dp[i - 1][j - 1]\nreturn dp[m][n]",
    ],
    reference: `function isMatch(s, p) { const m = s.length, n = p.length, dp = Array.from({ length: m + 1 }, () => new Array(n + 1).fill(false)); dp[0][0] = true; for (let j = 2; j <= n; j++) dp[0][j] = p[j - 1] === "*" && dp[0][j - 2]; const ok = (i, j) => p[j - 1] === "." || p[j - 1] === s[i - 1]; for (let i = 1; i <= m; i++) for (let j = 1; j <= n; j++) dp[i][j] = p[j - 1] === "*" ? dp[i][j - 2] || (ok(i, j - 1) && dp[i - 1][j]) : ok(i, j) && dp[i - 1][j - 1]; return dp[m][n]; }`,
    brute: `function isMatch(s, p) { return new RegExp("^(?:" + p + ")$").test(s); }`,
    fuzz: gen(`const s = __str(rand, __r(rand, 0, 8), "ab"); let p = ""; for (let i = 0; i < __r(rand, 1, 5); i++) { p += __pick(rand, ["a", "b", "."]); if (rand() < 0.4) p += "*"; } return [s, p];`),
    examples: [["aa", "a"], ["aa", "a*"], ["ab", ".*"]],
    edges: [
      ["empty", ["", "a*b*"], "Every starred part can be empty."],
      ["boundary", ["aab", "c*a*b"], "c* matches nothing."],
      ["no-answer", ["mississippi", "mis*is*p*."]],
    ],
  },
  {
    slug: "interleaving-string",
    title: "Interleaving String",
    difficulty: "Medium",
    pattern: D2,
    fn: "isInterleave",
    params: [["s1", "string"], ["s2", "string"], ["s3", "string"]],
    returns: "boolean",
    hints: [
      "s3 must use every character of s1 and s2 exactly once, keeping each string's order. Greedy choices fail when both strings offer the same next letter.",
      "dp[i][j]: can the first i letters of s1 and j letters of s2 form the first i + j letters of s3? Come from dp[i - 1][j] using s1[i - 1] or from dp[i][j - 1] using s2[j - 1].",
      "if len(s1) + len(s2) != len(s3): return false\ndp = (m + 1) x (n + 1) false; dp[0][0] = true\nfor i in 0 .. m:\n  for j in 0 .. n:\n    k = i + j - 1\n    if i > 0 and dp[i - 1][j] and s1[i - 1] == s3[k]: dp[i][j] = true\n    if j > 0 and dp[i][j - 1] and s2[j - 1] == s3[k]: dp[i][j] = true\nreturn dp[m][n]",
    ],
    reference: `function isInterleave(s1, s2, s3) { const m = s1.length, n = s2.length; if (m + n !== s3.length) return false; const dp = Array.from({ length: m + 1 }, () => new Array(n + 1).fill(false)); dp[0][0] = true; for (let i = 0; i <= m; i++) for (let j = 0; j <= n; j++) { const k = i + j - 1; if (i && dp[i - 1][j] && s1[i - 1] === s3[k]) dp[i][j] = true; if (j && dp[i][j - 1] && s2[j - 1] === s3[k]) dp[i][j] = true; } return dp[m][n]; }`,
    brute: `function isInterleave(s1, s2, s3) { if (s1.length + s2.length !== s3.length) return false; const go = (i, j) => { if (i + j === s3.length) return true; return (i < s1.length && s1[i] === s3[i + j] && go(i + 1, j)) || (j < s2.length && s2[j] === s3[i + j] && go(i, j + 1)); }; return go(0, 0); }`,
    fuzz: gen(`const a = __str(rand, __r(rand, 0, 6), "ab"), b = __str(rand, __r(rand, 0, 6), "ab"); let i = 0, j = 0, c = ""; while (i < a.length || j < b.length) c += (j >= b.length || (i < a.length && rand() < 0.5)) ? a[i++] : b[j++]; if (rand() < 0.4 && c.length) { const k = __r(rand, 0, c.length - 1); c = c.slice(0, k) + (c[k] === "a" ? "b" : "a") + c.slice(k + 1); } return [a, b, c];`),
    examples: [["aabcc", "dbbca", "aadbbcbcac"], ["aabcc", "dbbca", "aadbbbaccc"], ["", "", ""]],
    edges: [
      ["empty", ["", "abc", "abc"]],
      ["no-answer", ["a", "b", "abc"], "Lengths do not add up."],
      ["duplicates", ["aa", "ab", "aaba"], "Both strings offer an 'a' first."],
    ],
  },
  {
    slug: "best-time-to-buy-and-sell-stock-iii",
    title: "Best Time to Buy and Sell Stock III",
    difficulty: "Hard",
    pattern: D1,
    fn: "maxProfit",
    params: [["prices", "number[]"]],
    returns: "number",
    hints: [
      "At most two complete trades, and they cannot overlap.",
      "Track four running values: best after the first buy, first sell, second buy and second sell. Each day updates them in that order.",
      "buy1 = -infinity; sell1 = 0; buy2 = -infinity; sell2 = 0\nfor p in prices:\n  buy1 = max(buy1, -p)\n  sell1 = max(sell1, buy1 + p)\n  buy2 = max(buy2, sell1 - p)\n  sell2 = max(sell2, buy2 + p)\nreturn sell2",
    ],
    reference: `function maxProfit(prices) { let b1 = -Infinity, s1 = 0, b2 = -Infinity, s2 = 0; for (const p of prices) { b1 = Math.max(b1, -p); s1 = Math.max(s1, b1 + p); b2 = Math.max(b2, s1 - p); s2 = Math.max(s2, b2 + p); } return s2; }`,
    brute: `function maxProfit(prices) { const one = (a) => { let lo = Infinity, best = 0; for (const p of a) { lo = Math.min(lo, p); best = Math.max(best, p - lo); } return best; }; let best = 0; for (let k = 0; k <= prices.length; k++) best = Math.max(best, one(prices.slice(0, k)) + one(prices.slice(k))); return best; }`,
    fuzz: gen(`return [__arr(rand, __r(rand, 1, 12), 0, 15)];`),
    examples: [[[3, 3, 5, 0, 0, 3, 1, 4]], [[1, 2, 3, 4, 5]], [[7, 6, 4, 3, 1]]],
    edges: [
      ["single", [[1]]],
      ["boundary", [[1, 5, 2, 8, 3, 10]], "Three rises, but only two trades."],
      ["all-equal", [[4, 4, 4]]],
    ],
  },
  {
    slug: "best-time-to-buy-and-sell-stock-iv",
    title: "Best Time to Buy and Sell Stock IV",
    difficulty: "Hard",
    pattern: D1,
    fn: "maxProfit",
    params: [["k", "number"], ["prices", "number[]"]],
    returns: "number",
    hints: [
      "Generalise the two-trade version to k trades: keep a buy and a sell value for each trade number.",
      "buy[t] = max(buy[t], sell[t - 1] - p); sell[t] = max(sell[t], buy[t] + p), for t = 1..k each day. (If k >= n / 2, it is the same as unlimited trades.)",
      "buy = array of k + 1 values -infinity; sell = array of k + 1 zeros\nfor p in prices:\n  for t in 1 .. k:\n    buy[t] = max(buy[t], sell[t - 1] - p)\n    sell[t] = max(sell[t], buy[t] + p)\nreturn sell[k]",
    ],
    reference: `function maxProfit(k, prices) { const buy = new Array(k + 1).fill(-Infinity), sell = new Array(k + 1).fill(0); for (const p of prices) for (let t = 1; t <= k; t++) { buy[t] = Math.max(buy[t], sell[t - 1] - p); sell[t] = Math.max(sell[t], buy[t] + p); } return sell[k]; }`,
    brute: `function maxProfit(k, prices) { const go = (i, left, holding) => { if (i === prices.length || (left === 0 && !holding)) return 0; const wait = go(i + 1, left, holding); return holding ? Math.max(wait, prices[i] + go(i + 1, left, false)) : Math.max(wait, go(i + 1, left - 1, true) - prices[i]); }; return go(0, k, false); }`,
    fuzz: gen(`return [__r(rand, 1, 4), __arr(rand, __r(rand, 1, 11), 0, 15)];`),
    examples: [[2, [2, 4, 1]], [2, [3, 2, 6, 5, 0, 3]]],
    edges: [
      ["single", [1, [5]]],
      ["large", [100, [1, 3, 2, 5, 4, 8]], "More trades than rises: take every rise."],
      ["reverse-sorted", [3, [9, 7, 4, 1]]],
    ],
  },
  {
    slug: "burst-balloons",
    title: "Burst Balloons",
    difficulty: "Hard",
    pattern: D2,
    fn: "maxCoins",
    params: [["nums", "number[]"]],
    returns: "number",
    hints: [
      "Thinking about which balloon to burst first is messy because neighbours change. Think about which balloon in a range is burst last.",
      "Pad with 1 on both ends. best(l, r) over the open interval: try each k as the last one burst between l and r: nums[l] * nums[k] * nums[r] + best(l, k) + best(k, r).",
      "a = [1] + nums + [1]; n = len(a)\nbest = n x n zeros\nfor len in 2 .. n - 1:\n  for l in 0 .. n - 1 - len:\n    r = l + len\n    for k in l + 1 .. r - 1:\n      best[l][r] = max(best[l][r], best[l][k] + best[k][r] + a[l] * a[k] * a[r])\nreturn best[0][n - 1]",
    ],
    reference: `function maxCoins(nums) { const a = [1, ...nums, 1], n = a.length, b = Array.from({ length: n }, () => new Array(n).fill(0)); for (let len = 2; len < n; len++) for (let l = 0; l + len < n; l++) { const r = l + len; for (let k = l + 1; k < r; k++) b[l][r] = Math.max(b[l][r], b[l][k] + b[k][r] + a[l] * a[k] * a[r]); } return b[0][n - 1]; }`,
    brute: `function maxCoins(nums) { const go = (a) => { if (!a.length) return 0; let best = 0; for (let i = 0; i < a.length; i++) best = Math.max(best, (i > 0 ? a[i - 1] : 1) * a[i] * (i < a.length - 1 ? a[i + 1] : 1) + go(a.slice(0, i).concat(a.slice(i + 1)))); return best; }; return go(nums); }`,
    fuzz: gen(`return [__arr(rand, __r(rand, 1, 6), 0, 9)];`),
    examples: [[[3, 1, 5, 8]], [[1, 5]]],
    edges: [
      ["single", [[7]]],
      ["zeros", [[0, 0, 3]]],
      ["all-equal", [[2, 2, 2, 2]]],
    ],
  },
  {
    slug: "minimum-cost-to-cut-a-stick",
    title: "Minimum Cost to Cut a Stick",
    difficulty: "Hard",
    pattern: D2,
    fn: "minCost",
    params: [["n", "number"], ["cuts", "number[]"]],
    returns: "number",
    hints: [
      "Each cut costs the length of the piece being cut, so the order matters. A cut splits the problem into two independent pieces.",
      "Sort the cuts and add 0 and n as ends. cost(i, j) for the piece between cut points i and j = (c[j] - c[i]) + min over k between them of cost(i, k) + cost(k, j).",
      "c = [0] + sorted(cuts) + [n]; m = len(c)\nf = m x m zeros\nfor len in 2 .. m - 1:\n  for i in 0 .. m - 1 - len:\n    j = i + len; f[i][j] = infinity\n    for k in i + 1 .. j - 1:\n      f[i][j] = min(f[i][j], f[i][k] + f[k][j])\n    f[i][j] += c[j] - c[i]\nreturn f[0][m - 1]",
    ],
    reference: `function minCost(n, cuts) { const c = [0, ...[...cuts].sort((a, b) => a - b), n], m = c.length, f = Array.from({ length: m }, () => new Array(m).fill(0)); for (let len = 2; len < m; len++) for (let i = 0; i + len < m; i++) { const j = i + len; f[i][j] = Infinity; for (let k = i + 1; k < j; k++) f[i][j] = Math.min(f[i][j], f[i][k] + f[k][j]); f[i][j] += c[j] - c[i]; } return f[0][m - 1]; }`,
    brute: `function minCost(n, cuts) { const go = (lo, hi, list) => { const inside = list.filter((x) => x > lo && x < hi); if (!inside.length) return 0; let best = Infinity; for (const x of inside) best = Math.min(best, go(lo, x, inside) + go(x, hi, inside)); return best + hi - lo; }; return go(0, n, cuts); }`,
    fuzz: gen(`const n = __r(rand, 2, 20); return [n, __shuffle(rand, Array.from({ length: n - 1 }, (_, i) => i + 1)).slice(0, __r(rand, 1, Math.min(6, n - 1)))];`),
    examples: [[7, [1, 3, 4, 5]], [9, [5, 6, 1, 4, 2]]],
    edges: [
      ["single", [5, [2]], "One cut costs the whole length."],
      ["two", [2, [1]]],
      ["sorted", [10, [1, 2, 3, 4, 5, 6]]],
    ],
  },
  {
    slug: "palindrome-partitioning-ii",
    title: "Palindrome Partitioning II",
    difficulty: "Hard",
    pattern: D2,
    fn: "minCut",
    params: [["s", "string"]],
    returns: "number",
    hints: [
      "cuts[i] = fewest cuts for the prefix ending at i. The last piece is some palindrome s[j..i].",
      "Precompute which substrings are palindromes (pal[j][i] = s[j] == s[i] and pal[j + 1][i - 1]). Then cuts[i] = 0 if s[0..i] is a palindrome, else min over j of cuts[j - 1] + 1 where s[j..i] is a palindrome.",
      "pal = n x n false; cuts = array of n\nfor i in 0 .. n - 1:\n  cuts[i] = i\n  for j in 0 .. i:\n    if s[j] == s[i] and (i - j < 2 or pal[j + 1][i - 1]):\n      pal[j][i] = true\n      cuts[i] = 0 if j == 0 else min(cuts[i], cuts[j - 1] + 1)\nreturn cuts[n - 1]",
    ],
    reference: `function minCut(s) { const n = s.length, pal = Array.from({ length: n }, () => new Array(n).fill(false)), cuts = new Array(n).fill(0); for (let i = 0; i < n; i++) { cuts[i] = i; for (let j = 0; j <= i; j++) if (s[j] === s[i] && (i - j < 2 || pal[j + 1][i - 1])) { pal[j][i] = true; cuts[i] = j === 0 ? 0 : Math.min(cuts[i], cuts[j - 1] + 1); } } return cuts[n - 1]; }`,
    brute: `function minCut(s) { const isPal = (t) => t === t.split("").reverse().join(""); const go = (i) => { if (i === s.length) return -1; let best = Infinity; for (let j = i + 1; j <= s.length; j++) if (isPal(s.slice(i, j))) best = Math.min(best, 1 + go(j)); return best; }; return go(0); }`,
    fuzz: gen(`return [__str(rand, __r(rand, 1, 11), "ab")];`),
    examples: [["aab"], ["a"], ["ab"]],
    edges: [
      ["all-equal", ["aaaa"], "Already a palindrome: 0 cuts."],
      ["boundary", ["abcba"]],
      ["reverse-sorted", ["dcba"], "All distinct: n - 1 cuts."],
    ],
  },
  {
    slug: "last-stone-weight-ii",
    title: "Last Stone Weight II",
    difficulty: "Medium",
    pattern: D2,
    fn: "lastStoneWeightII",
    params: [["stones", "number[]"]],
    returns: "number",
    hints: [
      "Every smash subtracts one stone from another, so the final weight is a sum where each stone gets a + or a - sign. Make it as small as possible (and non-negative).",
      "Split the stones into two groups as evenly as possible: find the largest reachable subset sum not above total / 2 (0/1 knapsack); the answer is total - 2 * that sum.",
      "total = sum(stones); half = total // 2\ncan = array of half + 1 false; can[0] = true\nfor x in stones:\n  for s from half down to x:\n    if can[s - x]: can[s] = true\nbest = largest s with can[s]\nreturn total - 2 * best",
    ],
    reference: `function lastStoneWeightII(stones) { const total = stones.reduce((a, b) => a + b, 0), half = Math.floor(total / 2), can = new Array(half + 1).fill(false); can[0] = true; for (const x of stones) for (let s = half; s >= x; s--) if (can[s - x]) can[s] = true; let b = half; while (!can[b]) b--; return total - 2 * b; }`,
    brute: `function lastStoneWeightII(stones) { let best = Infinity; for (let m = 0; m < 1 << stones.length; m++) { let s = 0; stones.forEach((x, i) => { s += (m >> i) & 1 ? x : -x; }); if (s >= 0) best = Math.min(best, s); } return best; }`,
    fuzz: gen(`return [__arr(rand, __r(rand, 1, 12), 1, 20)];`),
    examples: [[[2, 7, 4, 1, 8, 1]], [[31, 26, 33, 21, 40]]],
    edges: [
      ["single", [[5]]],
      ["two", [[3, 3]]],
      ["boundary", [[1, 1, 4, 2, 2]], "A perfect split exists: 0."],
    ],
  },
];

export const LADDER_DP2_SEEDED: ProblemSpec[] = DEFS.map((d) => define(d).spec);
