import { define, type ProblemDef } from "../../dsa-extras/define";
import { gen } from "../../dsa-extras/gen";
import type { ProblemSpec } from "../types";
import { design } from "./ladder-stack-seeded";

const TR = "Tries";
const WORD = `const word = () => __str(rand, __r(rand, 1, 4), "abc");`;

/** Judges for seeded LeetCode problems that the Tries Ladder points at. */
const DEFS: ProblemDef[] = [
  design({
    slug: "implement-trie-prefix-tree",
    title: "Implement Trie (Prefix Tree)",
    difficulty: "Medium",
    pattern: TR,
    cls: "Trie",
    methods: ["insert(word)", "search(word)", "startsWith(prefix)"],
    hints: [
      "Each node holds up to 26 children and a flag saying whether a word ends there. Words that share a prefix share a path.",
      "insert walks down creating missing children and marks the last node; search walks down and checks the flag; startsWith only needs the walk to succeed.",
      "insert(w): node = root; for ch in w: node = node.child[ch] (create if missing); node.end = true\nwalk(s): node = root; for ch in s: if ch not in node.child: return none; node = node.child[ch]; return node\nsearch(w): n = walk(w); return n is not none and n.end\nstartsWith(p): return walk(p) is not none",
    ],
    reference: `class Trie { constructor() { this.root = {}; } insert(word) { let n = this.root; for (const ch of word) n = n[ch] || (n[ch] = {}); n.$ = true; } walk(s) { let n = this.root; for (const ch of s) { n = n[ch]; if (!n) return null; } return n; } search(word) { const n = this.walk(word); return !!(n && n.$); } startsWith(prefix) { return this.walk(prefix) !== null; } }`,
    brute: `class Trie { constructor() { this.w = []; } insert(word) { this.w.push(word); } search(word) { return this.w.includes(word); } startsWith(prefix) { return this.w.some((x) => x.startsWith(prefix)); } }`,
    fuzz: gen(`${WORD} const ops = [["Trie"]]; for (let i = 0; i < __r(rand, 1, 14); i++) { const r = rand(); ops.push(r < 0.4 ? ["insert", word()] : r < 0.7 ? ["search", word()] : ["startsWith", word()]); } return [ops];`),
    examples: [[[["Trie"], ["insert", "apple"], ["search", "apple"], ["search", "app"], ["startsWith", "app"], ["insert", "app"], ["search", "app"]]], [[["Trie"], ["search", "a"], ["startsWith", "a"]]]],
    edges: [
      ["duplicates", [[["Trie"], ["insert", "ab"], ["insert", "ab"], ["search", "ab"], ["search", "a"]]]],
      ["boundary", [[["Trie"], ["insert", "abc"], ["startsWith", "abc"], ["startsWith", "abcd"]]], "The whole word is also a prefix of itself."],
      ["single-char", [[["Trie"], ["insert", "a"], ["search", "a"], ["startsWith", "b"]]]],
    ],
  }),
  design({
    slug: "design-add-and-search-words-data-structure",
    title: "Design Add and Search Words Data Structure",
    difficulty: "Medium",
    pattern: TR,
    cls: "WordDictionary",
    methods: ["addWord(word)", "search(word)"],
    hints: [
      "A trie handles plain lookups. The '.' wildcard means 'any one letter', so at that position you must try every child.",
      "search is a DFS over (node, index): a letter follows one child, a '.' tries all children; succeed when the index reaches the end at a word-ending node.",
      "addWord(w): standard trie insert, mark the end\nsearch(w): return dfs(root, 0)\ndfs(node, i):\n  if i == len(w): return node.end\n  if w[i] == '.':\n    return any(dfs(child, i + 1) for each child of node)\n  if w[i] not in node.child: return false\n  return dfs(node.child[w[i]], i + 1)",
    ],
    reference: `class WordDictionary { constructor() { this.root = {}; } addWord(word) { let n = this.root; for (const ch of word) n = n[ch] || (n[ch] = {}); n.$ = true; } search(word) { const dfs = (n, i) => { if (i === word.length) return !!n.$; const ch = word[i]; if (ch === ".") { for (const k of Object.keys(n)) if (k !== "$" && dfs(n[k], i + 1)) return true; return false; } return !!n[ch] && dfs(n[ch], i + 1); }; return dfs(this.root, 0); } }`,
    brute: `class WordDictionary { constructor() { this.w = []; } addWord(word) { this.w.push(word); } search(word) { return this.w.some((x) => x.length === word.length && [...word].every((c, i) => c === "." || c === x[i])); } }`,
    fuzz: gen(`${WORD} const ops = [["WordDictionary"]]; for (let i = 0; i < __r(rand, 1, 14); i++) { if (rand() < 0.45) ops.push(["addWord", word()]); else ops.push(["search", word().split("").map((c) => (rand() < 0.3 ? "." : c)).join("")]); } return [ops];`),
    examples: [[[["WordDictionary"], ["addWord", "bad"], ["addWord", "dad"], ["addWord", "mad"], ["search", "pad"], ["search", "bad"], ["search", ".ad"], ["search", "b.."]]], [[["WordDictionary"], ["search", "."]]]],
    edges: [
      ["boundary", [[["WordDictionary"], ["addWord", "ab"], ["search", "a."], ["search", "a.."], ["search", ".."]]], "Dots must match exactly one letter each."],
      ["single-char", [[["WordDictionary"], ["addWord", "a"], ["search", "."], ["search", "a"]]]],
      ["no-answer", [[["WordDictionary"], ["addWord", "abc"], ["search", "ab"], ["search", "abcd"]]]],
    ],
  }),
  {
    slug: "replace-words",
    title: "Replace Words",
    difficulty: "Medium",
    pattern: TR,
    fn: "replaceWords",
    params: [["dictionary", "string[]"], ["sentence", "string"]],
    returns: "string",
    hints: [
      "Each word in the sentence is replaced by the shortest root that is a prefix of it, if any.",
      "Put the roots in a trie. For each word, walk the trie letter by letter and stop at the first node that ends a root.",
      "trie = all roots\nfor each word w in sentence.split(' '):\n  node = root; out = w\n  for i, ch in w:\n    if ch not in node.child: break\n    node = node.child[ch]\n    if node.end: out = w[0 .. i]; break\n  replace w by out\nreturn the words joined by spaces",
    ],
    reference: `function replaceWords(dictionary, sentence) { const root = {}; for (const w of dictionary) { let n = root; for (const ch of w) n = n[ch] || (n[ch] = {}); n.$ = true; } return sentence.split(" ").map((w) => { let n = root; for (let i = 0; i < w.length; i++) { n = n[w[i]]; if (!n) break; if (n.$) return w.slice(0, i + 1); } return w; }).join(" "); }`,
    brute: `function replaceWords(dictionary, sentence) { return sentence.split(" ").map((w) => { let best = w; for (const r of dictionary) if (w.startsWith(r) && r.length < best.length) best = r; return best; }).join(" "); }`,
    fuzz: gen(`const dict = [...new Set(Array.from({ length: __r(rand, 1, 4) }, () => __str(rand, __r(rand, 1, 3), "abc")))]; return [dict, Array.from({ length: __r(rand, 1, 6) }, () => __str(rand, __r(rand, 1, 5), "abc")).join(" ")];`),
    examples: [[["cat", "bat", "rat"], "the cattle was rattled by the battery"], [["a", "b", "c"], "aadsfasf absbs bbab cadsfafs"]],
    edges: [
      ["no-answer", [["xyz"], "hello world"]],
      ["boundary", [["a", "aa", "aaa"], "aaaa aa a"], "The shortest root wins."],
      ["single", [["ab"], "ab"], "A word equal to a root."],
    ],
  },
  {
    slug: "longest-word-in-dictionary",
    title: "Longest Word in Dictionary",
    difficulty: "Medium",
    pattern: TR,
    fn: "longestWord",
    params: [["words", "string[]"]],
    returns: "string",
    hints: [
      "A word counts only if every prefix of it (length 1, 2, ...) is also in the list. Return the longest such word, breaking ties by the smallest in alphabetical order.",
      "Sort the words; then a word is buildable when its prefix without the last letter was already marked buildable (or it has one letter). Track the best as you go.",
      "sort words\nok = set containing the empty string; best = ''\nfor w in words:\n  if w without its last letter is in ok:\n    add w to ok\n    if len(w) > len(best): best = w\nreturn best",
    ],
    reference: `function longestWord(words) { const ok = new Set([""]); let best = ""; for (const w of [...words].sort()) if (ok.has(w.slice(0, -1))) { ok.add(w); if (w.length > best.length) best = w; } return best; }`,
    brute: `function longestWord(words) { const set = new Set(words); let best = ""; for (const w of words) { let good = true; for (let k = 1; k < w.length; k++) if (!set.has(w.slice(0, k))) good = false; if (good && (w.length > best.length || (w.length === best.length && w < best))) best = w; } return best; }`,
    fuzz: gen(`return [[...new Set(Array.from({ length: __r(rand, 1, 10) }, () => __str(rand, __r(rand, 1, 4), "ab")))]];`),
    examples: [[["w", "wo", "wor", "worl", "world"]], [["a", "banana", "app", "appl", "ap", "apply", "apple"]]],
    edges: [
      ["single-char", [["z"]]],
      ["no-answer", [["ab", "abc"]], "No one-letter start: the answer is ''."],
      ["order", [["b", "a", "ba", "ab"]], "A tie goes to the alphabetically smaller word."],
    ],
  },
  {
    slug: "search-suggestions-system",
    title: "Search Suggestions System",
    difficulty: "Medium",
    pattern: TR,
    fn: "suggestedProducts",
    params: [["products", "string[]"], ["searchWord", "string"]],
    returns: "string[][]",
    hints: [
      "After each typed letter, return up to three products starting with the typed prefix, in alphabetical order.",
      "Sort the products once. For each prefix, binary search the first product >= prefix and take up to three that still start with it. (A trie storing the three best words per node also works.)",
      "sort products\nout = []\nfor i in 1 .. len(searchWord):\n  p = searchWord[0 .. i - 1]\n  k = first index with products[k] >= p\n  out.append(the products from k on that start with p, at most 3)\nreturn out",
    ],
    reference: `function suggestedProducts(products, searchWord) { const a = [...products].sort(), out = []; for (let i = 1; i <= searchWord.length; i++) { const p = searchWord.slice(0, i); let lo = 0, hi = a.length; while (lo < hi) { const m = (lo + hi) >> 1; if (a[m] < p) lo = m + 1; else hi = m; } const got = []; for (let k = lo; k < a.length && got.length < 3 && a[k].startsWith(p); k++) got.push(a[k]); out.push(got); } return out; }`,
    brute: `function suggestedProducts(products, searchWord) { const out = []; for (let i = 1; i <= searchWord.length; i++) out.push(products.filter((x) => x.startsWith(searchWord.slice(0, i))).sort().slice(0, 3)); return out; }`,
    fuzz: gen(`return [[...new Set(Array.from({ length: __r(rand, 1, 9) }, () => __str(rand, __r(rand, 1, 4), "abc")))], __str(rand, __r(rand, 1, 4), "abc")];`),
    examples: [[["mobile", "mouse", "moneypot", "monitor", "mousepad"], "mouse"], [["havana"], "tatiana"]],
    edges: [
      ["single", [["a"], "a"]],
      ["no-answer", [["abc"], "x"]],
      ["boundary", [["ab", "abc", "abd", "abe"], "ab"], "Only three suggestions even when four match."],
    ],
  },
  design({
    slug: "map-sum-pairs",
    title: "Map Sum Pairs",
    difficulty: "Medium",
    pattern: TR,
    cls: "MapSum",
    methods: ["insert(key, val)", "sum(prefix)"],
    hints: [
      "sum(prefix) adds the values of every key that starts with prefix. Inserting an existing key replaces its old value.",
      "Store in each trie node the total of all values below it. On insert, add the difference between the new and old value of the key along its path.",
      "vals = map key -> value\ninsert(key, val):\n  delta = val - vals.get(key, 0); vals[key] = val\n  node = root\n  for ch in key: node = node.child[ch] (create if missing); node.total += delta\nsum(prefix):\n  walk prefix; return node.total, or 0 if the walk fails",
    ],
    reference: `class MapSum { constructor() { this.root = { t: 0 }; this.vals = new Map(); } insert(key, val) { const d = val - (this.vals.get(key) || 0); this.vals.set(key, val); let n = this.root; for (const ch of key) { n = n[ch] || (n[ch] = { t: 0 }); n.t += d; } } sum(prefix) { let n = this.root; for (const ch of prefix) { n = n[ch]; if (!n) return 0; } return n.t; } }`,
    brute: `class MapSum { constructor() { this.m = new Map(); } insert(key, val) { this.m.set(key, val); } sum(prefix) { let s = 0; for (const [k, v] of this.m) if (k.startsWith(prefix)) s += v; return s; } }`,
    fuzz: gen(`${WORD} const ops = [["MapSum"]]; for (let i = 0; i < __r(rand, 1, 14); i++) ops.push(rand() < 0.5 ? ["insert", word(), __r(rand, 1, 20)] : ["sum", word()]); return [ops];`),
    examples: [[[["MapSum"], ["insert", "apple", 3], ["sum", "ap"], ["insert", "app", 2], ["sum", "ap"]]], [[["MapSum"], ["sum", "a"]]]],
    edges: [
      ["duplicates", [[["MapSum"], ["insert", "ab", 5], ["insert", "ab", 2], ["sum", "a"]]], "Re-inserting a key replaces its value."],
      ["boundary", [[["MapSum"], ["insert", "a", 1], ["insert", "ab", 2], ["sum", "ab"], ["sum", "abc"]]]],
      ["single-char", [[["MapSum"], ["insert", "x", 9], ["sum", "x"]]]],
    ],
  }),
  {
    slug: "extra-characters-in-a-string",
    title: "Extra Characters in a String",
    difficulty: "Medium",
    pattern: TR,
    fn: "minExtraChar",
    params: [["s", "string"], ["dictionary", "string[]"]],
    returns: "number",
    hints: [
      "Break s into dictionary words plus leftover characters, minimising the leftovers.",
      "best[i] = fewest extras in s[i..]. Either s[i] is extra (1 + best[i + 1]) or some dictionary word starts at i (best[j] where the word ends at j). A trie from i finds all such words in one walk.",
      "best[n] = 0\nfor i from n - 1 down to 0:\n  best[i] = 1 + best[i + 1]\n  node = root\n  for j in i .. n - 1:\n    if s[j] not in node.child: break\n    node = node.child[s[j]]\n    if node.end: best[i] = min(best[i], best[j + 1])\nreturn best[0]",
    ],
    reference: `function minExtraChar(s, dictionary) { const root = {}; for (const w of dictionary) { let n = root; for (const ch of w) n = n[ch] || (n[ch] = {}); n.$ = true; } const n = s.length, best = new Array(n + 1).fill(0); for (let i = n - 1; i >= 0; i--) { best[i] = 1 + best[i + 1]; let node = root; for (let j = i; j < n; j++) { node = node[s[j]]; if (!node) break; if (node.$) best[i] = Math.min(best[i], best[j + 1]); } } return best[0]; }`,
    brute: `function minExtraChar(s, dictionary) { const go = (i) => { if (i === s.length) return 0; let best = 1 + go(i + 1); for (const w of dictionary) if (s.startsWith(w, i)) best = Math.min(best, go(i + w.length)); return best; }; return go(0); }`,
    fuzz: gen(`return [__str(rand, __r(rand, 1, 12), "abc"), [...new Set(Array.from({ length: __r(rand, 1, 5) }, () => __str(rand, __r(rand, 1, 3), "abc")))]];`),
    examples: [["leetscode", ["leet", "code", "leetcode"]], ["sayhelloworld", ["hello", "world"]]],
    edges: [
      ["no-answer", ["abc", ["x"]], "Nothing matches: every character is extra."],
      ["boundary", ["aaa", ["aa", "a"]]],
      ["single-char", ["a", ["a"]]],
    ],
  },
  {
    slug: "word-search-ii",
    title: "Word Search II",
    difficulty: "Hard",
    pattern: TR,
    fn: "findWords",
    params: [["board", "string[][]"], ["words", "string[]"]],
    returns: "string[]",
    compare: "unordered",
    hints: [
      "Running Word Search once per word repeats work. Put all words in a trie and search the board once, following the trie as you walk. Any order of words is accepted.",
      "DFS from every cell carrying the current trie node; a cell may not be reused in one word. When a node ends a word, record it and clear the mark so it is reported once.",
      "trie = all words, word stored at its end node\nfor each cell (r, c): dfs(r, c, root)\ndfs(r, c, node):\n  ch = board[r][c]\n  if ch == '#' or ch not in node.child: return\n  node = node.child[ch]\n  if node.word: add node.word to found; node.word = none\n  board[r][c] = '#'\n  dfs each of the 4 neighbours inside the board with node\n  board[r][c] = ch\nreturn found",
    ],
    reference: `function findWords(board, words) { const root = {}; for (const w of words) { let n = root; for (const ch of w) n = n[ch] || (n[ch] = {}); n.$ = w; } const R = board.length, C = board[0].length, out = []; const dfs = (r, c, node) => { if (r < 0 || c < 0 || r >= R || c >= C) return; const ch = board[r][c]; if (ch === "#" || !node[ch]) return; node = node[ch]; if (node.$) { out.push(node.$); node.$ = null; } board[r][c] = "#"; dfs(r + 1, c, node); dfs(r - 1, c, node); dfs(r, c + 1, node); dfs(r, c - 1, node); board[r][c] = ch; }; for (let r = 0; r < R; r++) for (let c = 0; c < C; c++) dfs(r, c, root); return out; }`,
    brute: `function findWords(board, words) { const R = board.length, C = board[0].length; const exist = (w) => { const used = new Set(); const go = (r, c, i) => { if (i === w.length) return true; if (r < 0 || c < 0 || r >= R || c >= C || used.has(r * C + c) || board[r][c] !== w[i]) return false; used.add(r * C + c); const ok = go(r + 1, c, i + 1) || go(r - 1, c, i + 1) || go(r, c + 1, i + 1) || go(r, c - 1, i + 1); used.delete(r * C + c); return ok; }; for (let r = 0; r < R; r++) for (let c = 0; c < C; c++) if (go(r, c, 0)) return true; return false; }; return [...new Set(words)].filter(exist); }`,
    fuzz: gen(`const r = __r(rand, 1, 4), c = __r(rand, 1, 4); return [Array.from({ length: r }, () => __str(rand, c, "abc").split("")), [...new Set(Array.from({ length: __r(rand, 1, 6) }, () => __str(rand, __r(rand, 1, 4), "abc")))]];`),
    examples: [[[["o", "a", "a", "n"], ["e", "t", "a", "e"], ["i", "h", "k", "r"], ["i", "f", "l", "v"]], ["oath", "pea", "eat", "rain"]], [[["a", "b"], ["c", "d"]], ["abcb"]]],
    edges: [
      ["single", [[["a"]], ["a", "aa"]], "A cell cannot be reused within one word."],
      ["reuse", [[["a", "b"], ["a", "a"]], ["aaa", "aaab", "aba", "baa"]]],
      ["no-answer", [[["x", "y"]], ["z"]]],
    ],
  },
  {
    slug: "palindrome-pairs",
    title: "Palindrome Pairs",
    difficulty: "Hard",
    pattern: TR,
    fn: "palindromePairs",
    params: [["words", "string[]"]],
    returns: "number[][]",
    compare: "unordered-outer",
    hints: [
      "Checking every ordered pair is O(n^2 * L). Split each word into a prefix and a suffix: if one part is a palindrome, you need the reverse of the other part to be a word. Any order of pairs is accepted.",
      "Map each reversed word to its index. For word i and every split point k: if word[0..k) is a palindrome and reverse(word[k..]) is another word j, then [j, i] works; if word[k..] is a palindrome and reverse(word[0..k)) is word j, then [i, j] works. Skip k == len for the second case to avoid duplicates.",
      "rev = map reverse(word) -> index\nfor i, w in words:\n  for k in 0 .. len(w):\n    left = w[0 .. k); right = w[k ..]\n    if left is a palindrome and right in rev and rev[right] != i: add [rev[right], i]\n    if k < len(w) and right is a palindrome and left in rev and rev[left] != i: add [i, rev[left]]\nreturn pairs",
    ],
    reference: `function palindromePairs(words) { const rev = new Map(words.map((w, i) => [w.split("").reverse().join(""), i])), isPal = (s) => { for (let a = 0, b = s.length - 1; a < b; a++, b--) if (s[a] !== s[b]) return false; return true; }, out = []; words.forEach((w, i) => { for (let k = 0; k <= w.length; k++) { const L = w.slice(0, k), R = w.slice(k); if (isPal(L) && rev.has(R) && rev.get(R) !== i) out.push([rev.get(R), i]); if (k < w.length && isPal(R) && rev.has(L) && rev.get(L) !== i) out.push([i, rev.get(L)]); } }); return out; }`,
    brute: `function palindromePairs(words) { const out = []; for (let i = 0; i < words.length; i++) for (let j = 0; j < words.length; j++) if (i !== j) { const s = words[i] + words[j]; if (s === s.split("").reverse().join("")) out.push([i, j]); } return out; }`,
    fuzz: gen(`return [[...new Set(Array.from({ length: __r(rand, 1, 8) }, () => __str(rand, __r(rand, 0, 4), "ab")))]];`),
    examples: [[["abcd", "dcba", "lls", "s", "sssll"]], [["bat", "tab", "cat"]], [["a", ""]]],
    edges: [
      ["empty", [["", "aba", "ab"]], "The empty word pairs with every palindrome, both ways."],
      ["single", [["abc"]]],
      ["boundary", [["ab", "ba", "aba"]]],
    ],
  },
  design({
    slug: "stream-of-characters",
    title: "Stream of Characters",
    difficulty: "Hard",
    pattern: TR,
    cls: "StreamChecker",
    ctor: "words",
    methods: ["query(letter)"],
    hints: [
      "After each letter, ask whether some word is a suffix of everything typed so far. Checking every word every time is too slow.",
      "Build a trie of the reversed words. Keep the stream; on each query, walk the trie from the newest letter backwards and stop at the first word end (or a missing child).",
      "constructor(words): insert reverse(w) for every word into a trie\nstream = []\nquery(ch):\n  append ch to stream\n  node = root\n  for i from len(stream) - 1 down to 0:\n    if stream[i] not in node.child: return false\n    node = node.child[stream[i]]\n    if node.end: return true\n  return false",
    ],
    reference: `class StreamChecker { constructor(words) { this.root = {}; this.s = []; for (const w of words) { let n = this.root; for (let i = w.length - 1; i >= 0; i--) n = n[w[i]] || (n[w[i]] = {}); n.$ = true; } } query(letter) { this.s.push(letter); let n = this.root; for (let i = this.s.length - 1; i >= 0; i--) { n = n[this.s[i]]; if (!n) return false; if (n.$) return true; } return false; } }`,
    brute: `class StreamChecker { constructor(words) { this.w = words; this.s = ""; } query(letter) { this.s += letter; return this.w.some((x) => this.s.endsWith(x)); } }`,
    fuzz: gen(`const words = [...new Set(Array.from({ length: __r(rand, 1, 4) }, () => __str(rand, __r(rand, 1, 3), "abc")))], ops = [["StreamChecker", words]]; for (let i = 0; i < __r(rand, 1, 14); i++) ops.push(["query", __pick(rand, ["a", "b", "c"])]); return [ops];`),
    examples: [[[["StreamChecker", ["cd", "f", "kl"]], ["query", "a"], ["query", "b"], ["query", "c"], ["query", "d"], ["query", "e"], ["query", "f"], ["query", "g"], ["query", "h"], ["query", "i"], ["query", "j"], ["query", "k"], ["query", "l"]]], [[["StreamChecker", ["a"]], ["query", "a"], ["query", "b"]]]],
    edges: [
      ["boundary", [[["StreamChecker", ["ab", "b"]], ["query", "a"], ["query", "b"]]], "Two words end at the same letter."],
      ["duplicates", [[["StreamChecker", ["aa"]], ["query", "a"], ["query", "a"], ["query", "a"]]]],
      ["single-char", [[["StreamChecker", ["z"]], ["query", "y"], ["query", "z"]]]],
    ],
  }),
  {
    slug: "maximum-xor-with-an-element-from-array",
    title: "Maximum XOR With an Element From Array",
    difficulty: "Hard",
    pattern: TR,
    fn: "maximizeXor",
    params: [["nums", "number[]"], ["queries", "number[][]"]],
    returns: "number[]",
    hints: [
      "Each query [x, m] wants the largest x XOR num over nums with num <= m, or -1 if none qualifies.",
      "Answer offline: sort nums and the queries by m. Insert nums into a binary trie (high bit first) while they are <= m, then walk the trie greedily choosing the opposite bit of x whenever possible.",
      "sort nums; sort query indices by m\nk = 0\nfor each query (x, m, idx) in that order:\n  while k < n and nums[k] <= m: insert nums[k] bit by bit (bit 30 down to 0); k += 1\n  if k == 0: ans[idx] = -1; continue\n  node = root; best = 0\n  for b from 30 down to 0:\n    want = 1 - bit b of x\n    if node has child want: best |= 1 << b; node = child want\n    else: node = the other child\n  ans[idx] = best\nreturn ans",
    ],
    reference: `function maximizeXor(nums, queries) { const a = [...nums].sort((x, y) => x - y), order = queries.map((q, i) => i).sort((i, j) => queries[i][1] - queries[j][1]), root = [null, null], ans = new Array(queries.length); let k = 0; for (const qi of order) { const [x, m] = queries[qi]; while (k < a.length && a[k] <= m) { let n = root; for (let b = 30; b >= 0; b--) { const bit = (a[k] >> b) & 1; n = n[bit] || (n[bit] = [null, null]); } k++; } if (!k) { ans[qi] = -1; continue; } let n = root, best = 0; for (let b = 30; b >= 0; b--) { const want = 1 - ((x >> b) & 1); if (n[want]) { best |= 1 << b; n = n[want]; } else n = n[1 - want]; } ans[qi] = best; } return ans; }`,
    brute: `function maximizeXor(nums, queries) { return queries.map(([x, m]) => { let best = -1; for (const v of nums) if (v <= m) best = Math.max(best, x ^ v); return best; }); }`,
    fuzz: gen(`return [__arr(rand, __r(rand, 1, 10), 0, 60), Array.from({ length: __r(rand, 1, 6) }, () => [__r(rand, 0, 60), __r(rand, 0, 60)])];`),
    examples: [[[0, 1, 2, 3, 4], [[3, 1], [1, 3], [5, 6]]], [[5, 2, 4, 6, 6, 3], [[12, 4], [8, 1], [6, 3]]]],
    edges: [
      ["no-answer", [[5, 7], [[1, 2]]], "Every number is above m."],
      ["single", [[9], [[9, 9]]]],
      ["extremes", [[1000000000, 0], [[1000000000, 1000000000]]]],
    ],
  },
  {
    slug: "concatenated-words",
    title: "Concatenated Words",
    difficulty: "Hard",
    pattern: TR,
    fn: "findAllConcatenatedWordsInADict",
    params: [["words", "string[]"]],
    returns: "string[]",
    compare: "unordered",
    hints: [
      "A concatenated word is made of at least two shorter words from the list. Any order of answers is accepted.",
      "Process words from shortest to longest; a word is concatenated when Word Break succeeds using only the shorter words seen so far. Then add the word to the set.",
      "sort words by length; seen = empty set; out = []\nfor w in words (skip empty):\n  ok[0] = true\n  for i in 1 .. len(w):\n    ok[i] = any(ok[j] and w[j .. i) in seen for j in 0 .. i - 1)\n  if ok[len(w)]: out.append(w)\n  add w to seen\nreturn out",
    ],
    reference: `function findAllConcatenatedWordsInADict(words) { const seen = new Set(), out = []; for (const w of [...words].sort((a, b) => a.length - b.length)) { if (!w) continue; const ok = [true]; for (let i = 1; i <= w.length; i++) { ok[i] = false; for (let j = 0; j < i && !ok[i]; j++) if (ok[j] && seen.has(w.slice(j, i))) ok[i] = true; } if (ok[w.length]) out.push(w); seen.add(w); } return out; }`,
    brute: `function findAllConcatenatedWordsInADict(words) { const set = new Set(words.filter(Boolean)); const parts = (w) => { if (!w) return 0; let best = -1; for (let k = 1; k <= w.length; k++) if (set.has(w.slice(0, k))) { const rest = parts(w.slice(k)); if (rest >= 0) best = Math.max(best, rest + 1); } return best; }; return [...set].filter((w) => { set.delete(w); const p = parts(w); set.add(w); return p >= 2; }); }`,
    fuzz: gen(`const base = [...new Set(Array.from({ length: __r(rand, 1, 4) }, () => __str(rand, __r(rand, 1, 3), "ab")))], extra = Array.from({ length: __r(rand, 0, 4) }, () => Array.from({ length: __r(rand, 2, 3) }, () => __pick(rand, base)).join("")); return [[...new Set(base.concat(extra, rand() < 0.5 ? [__str(rand, __r(rand, 1, 5), "ab")] : []))]];`),
    examples: [[["cat", "cats", "catsdogcats", "dog", "dogcatsdog", "hippopotamuses", "rat", "ratcatdogcat"]], [["cat", "dog", "catdog"]]],
    edges: [
      ["single", [["a"]], "One word alone is never concatenated."],
      ["all-equal", [["a", "aa", "aaa"]]],
      ["no-answer", [["ab", "cd", "abc"]]],
    ],
  },
];

export const LADDER_TRIES_SEEDED: ProblemSpec[] = DEFS.map((d) => define(d).spec);
