/**
 * More SQL challenges, written for PrepOS. Every ordered challenge names its tie-break in the prompt, so the checker's row
 * comparison has exactly one right answer. Reference queries run on SQLite (sql.js).
 */
import type { DbChallenge } from "@/modules/dsa/domain/db-lab";

type C = Omit<DbChallenge, "mode">;
const sql = (c: C): DbChallenge => ({ ...c, mode: "sql" });

export const EXTRA_SQL_CHALLENGES: readonly DbChallenge[] = [
  /* ------------------------------------------------ basics ------------------------------------------------ */
  sql({ id: "sql-pune-students", dataset: "school", topic: "basics", title: "Pune students", difficulty: "Easy", prompt: "Which students live in Pune? Show name and grade_level, ordered by name.", hint: "WHERE city = 'Pune', then ORDER BY name.", solution: "SELECT name, grade_level FROM students WHERE city = 'Pune' ORDER BY name", ordered: true, concepts: ["WHERE", "ORDER BY"] }),
  sql({ id: "sql-oldest-students", dataset: "school", topic: "basics", title: "Three oldest students", difficulty: "Easy", prompt: "Show the 3 oldest students (earliest birth date first, ties by name): name and born.", hint: "Dates in YYYY-MM-DD sort correctly as text. ORDER BY then LIMIT 3.", solution: "SELECT name, born FROM students ORDER BY born, name LIMIT 3", ordered: true, concepts: ["ORDER BY", "LIMIT"] }),
  sql({ id: "sql-distinct-cities", dataset: "school", topic: "basics", title: "Where students come from", difficulty: "Easy", prompt: "List the distinct cities students come from, leaving out students with no city. Alphabetical.", hint: "DISTINCT removes repeats; a missing city is NULL, so filter with IS NOT NULL.", solution: "SELECT DISTINCT city FROM students WHERE city IS NOT NULL ORDER BY city", ordered: true, concepts: ["DISTINCT", "IS NOT NULL"] }),
  sql({ id: "sql-cheap-accessories", dataset: "shop", topic: "basics", title: "Cheap accessories", difficulty: "Easy", prompt: "Accessories that cost less than 100: name and price, most expensive first.", hint: "Two conditions joined with AND.", solution: "SELECT name, price FROM products WHERE category = 'Accessories' AND price < 100 ORDER BY price DESC, name", ordered: true, concepts: ["WHERE", "AND"] }),
  sql({ id: "sql-tech-history", dataset: "library", topic: "basics", title: "Tech and history", difficulty: "Easy", prompt: "Books in the tech or history genres: title and year, oldest first (ties by title).", hint: "IN ('tech', 'history') is shorter than two ORs.", solution: "SELECT title, year FROM books WHERE genre IN ('tech', 'history') ORDER BY year, title", ordered: true, concepts: ["IN", "ORDER BY"] }),
  sql({ id: "sql-big-withdrawals", dataset: "bank", topic: "basics", title: "Big withdrawals", difficulty: "Easy", prompt: "Withdrawals are negative amounts. Find withdrawals of 1,000 or more: id, amount and txn_date, the largest withdrawal first (ties by id).", hint: "A withdrawal of 1,000 or more means amount <= -1000. Sorting ascending puts the most negative first.", solution: "SELECT id, amount, txn_date FROM transactions WHERE amount <= -1000 ORDER BY amount, id", ordered: true, concepts: ["WHERE", "negative numbers"] }),
  sql({ id: "sql-mid-length-songs", dataset: "streaming", topic: "basics", title: "Three to five minutes", difficulty: "Easy", prompt: "Songs from 180 to 300 seconds long, inclusive: title and seconds, shortest first (ties by title).", hint: "BETWEEN includes both ends.", solution: "SELECT title, seconds FROM songs WHERE seconds BETWEEN 180 AND 300 ORDER BY seconds, title", ordered: true, concepts: ["BETWEEN"] }),
  sql({ id: "sql-recent-hires", dataset: "company", topic: "basics", title: "Recent hires", difficulty: "Easy", prompt: "Employees hired on or after 2021-01-01: name and hire_date, earliest first (ties by name).", hint: "ISO dates compare correctly as strings.", solution: "SELECT name, hire_date FROM employees WHERE hire_date >= '2021-01-01' ORDER BY hire_date, name", ordered: true, concepts: ["WHERE", "dates as text"] }),

  /* ---------------------------------------------- aggregation ---------------------------------------------- */
  sql({ id: "sql-students-per-grade", dataset: "school", topic: "aggregation", title: "Students per grade", difficulty: "Easy", prompt: "How many students are in each grade level? Show grade_level and students, by grade level.", hint: "GROUP BY grade_level with COUNT(*).", solution: "SELECT grade_level, COUNT(*) AS students FROM students GROUP BY grade_level ORDER BY grade_level", ordered: true, concepts: ["GROUP BY", "COUNT"] }),
  sql({ id: "sql-account-balance", dataset: "bank", topic: "aggregation", title: "Account balances", difficulty: "Easy", prompt: "The balance of an account is the sum of its transactions. Show account_id and balance for every account that has transactions, in account order.", hint: "SUM over amount, grouped by account_id.", solution: "SELECT account_id, SUM(amount) AS balance FROM transactions GROUP BY account_id ORDER BY account_id", ordered: true, concepts: ["SUM", "GROUP BY"] }),
  sql({ id: "sql-course-average", dataset: "school", topic: "aggregation", title: "Average score per course", difficulty: "Medium", prompt: "Average score per course, rounded to 1 decimal. Show course title and average, best course first (ties by title). Courses with no enrollments are left out.", hint: "AVG ignores NULL scores by itself. An inner join drops courses nobody took.", solution: "SELECT c.title, ROUND(AVG(e.score), 1) AS avg_score FROM courses c JOIN enrollments e ON e.course_id = c.id GROUP BY c.id, c.title ORDER BY avg_score DESC, c.title", ordered: true, concepts: ["AVG", "NULL in aggregates", "JOIN"] }),
  sql({ id: "sql-plays-per-genre", dataset: "streaming", topic: "aggregation", title: "Plays per genre", difficulty: "Medium", prompt: "Total plays per genre: genre and plays, most played first (ties alphabetical).", hint: "Join plays to songs, then group by genre.", solution: "SELECT s.genre, COUNT(*) AS plays FROM plays p JOIN songs s ON s.id = p.song_id GROUP BY s.genre ORDER BY plays DESC, s.genre", ordered: true, concepts: ["JOIN", "GROUP BY", "COUNT"] }),
  sql({ id: "sql-prolific-authors", dataset: "library", topic: "aggregation", title: "Prolific authors", difficulty: "Medium", prompt: "Authors with at least two books in the library: author and number of books, alphabetical.", hint: "HAVING filters groups after they are formed.", solution: "SELECT author, COUNT(*) AS books FROM books GROUP BY author HAVING COUNT(*) >= 2 ORDER BY author", ordered: true, concepts: ["HAVING"] }),
  sql({ id: "sql-salary-range", dataset: "company", topic: "aggregation", title: "Salary range per department", difficulty: "Medium", prompt: "For each department with at least 2 employees show its name, lowest, highest and average salary (average rounded to a whole number), alphabetical by department.", hint: "MIN, MAX and AVG in one GROUP BY, with HAVING COUNT(*) >= 2.", solution: "SELECT d.name, MIN(e.salary) AS lowest, MAX(e.salary) AS highest, ROUND(AVG(e.salary)) AS average FROM departments d JOIN employees e ON e.department_id = d.id GROUP BY d.id, d.name HAVING COUNT(*) >= 2 ORDER BY d.name", ordered: true, concepts: ["MIN", "MAX", "AVG", "HAVING"] }),
  sql({ id: "sql-spend-per-category", dataset: "bank", topic: "aggregation", title: "Spending per category", difficulty: "Medium", prompt: "Total withdrawals per category as a positive number: category and spent, largest first (ties by category). Ignore deposits and uncategorised transactions.", hint: "Filter amount < 0 and category IS NOT NULL, then negate the SUM.", solution: "SELECT category, -SUM(amount) AS spent FROM transactions WHERE amount < 0 AND category IS NOT NULL GROUP BY category ORDER BY spent DESC, category", ordered: true, concepts: ["SUM", "WHERE", "NULL"] }),
  sql({ id: "sql-average-order-value", dataset: "shop", topic: "aggregation", title: "Average order value", difficulty: "Hard", prompt: "What is the average total value of a delivered order, rounded to 2 decimals? An order's total is the sum of quantity x price over its lines.", hint: "Aggregate twice: first total per order in a subquery, then AVG of those totals.", solution: "SELECT ROUND(AVG(total), 2) AS avg_order_value FROM (SELECT o.id, SUM(oi.quantity * p.price) AS total FROM orders o JOIN order_items oi ON oi.order_id = o.id JOIN products p ON p.id = oi.product_id WHERE o.status = 'delivered' GROUP BY o.id)", ordered: false, concepts: ["nested aggregation", "derived table"] }),

  /* ------------------------------------------------- joins ------------------------------------------------- */
  sql({ id: "sql-course-teachers", dataset: "school", topic: "joins", title: "Courses and teachers", difficulty: "Easy", prompt: "Every course with its teacher's name (NULL when it has no teacher), ordered by course title.", hint: "LEFT JOIN keeps courses with no teacher.", solution: "SELECT c.title, t.name AS teacher FROM courses c LEFT JOIN teachers t ON t.id = c.teacher_id ORDER BY c.title", ordered: true, concepts: ["LEFT JOIN"] }),
  sql({ id: "sql-unplayed-songs", dataset: "streaming", topic: "joins", title: "Songs nobody played", difficulty: "Easy", prompt: "Which songs have never been played? Titles only.", hint: "LEFT JOIN plays and keep the rows where the play side is NULL.", solution: "SELECT s.title FROM songs s LEFT JOIN plays p ON p.song_id = s.id WHERE p.id IS NULL", ordered: false, concepts: ["anti-join", "LEFT JOIN"] }),
  sql({ id: "sql-no-account", dataset: "bank", topic: "joins", title: "Customers without an account", difficulty: "Easy", prompt: "Which customers have no account? Names only.", hint: "Anti-join: LEFT JOIN accounts and keep the unmatched rows.", solution: "SELECT c.name FROM customers c LEFT JOIN accounts a ON a.customer_id = c.id WHERE a.id IS NULL", ordered: false, concepts: ["anti-join"] }),
  sql({ id: "sql-no-enrollment", dataset: "school", topic: "joins", title: "Students taking nothing", difficulty: "Medium", prompt: "Which students are not enrolled in any course? Names only.", hint: "NOT EXISTS (or a LEFT JOIN with IS NULL).", solution: "SELECT s.name FROM students s WHERE NOT EXISTS (SELECT 1 FROM enrollments e WHERE e.student_id = s.id)", ordered: false, concepts: ["NOT EXISTS", "anti-join"] }),
  sql({ id: "sql-who-borrowed", dataset: "library", topic: "joins", title: "Who borrowed what", difficulty: "Medium", prompt: "For every loan show the member's name, the book's title and loaned_on, in loan id order.", hint: "loans joins to both members and books.", solution: "SELECT m.name AS member, b.title, l.loaned_on FROM loans l JOIN members m ON m.id = l.member_id JOIN books b ON b.id = l.book_id ORDER BY l.id", ordered: true, concepts: ["multi-table JOIN"] }),
  sql({ id: "sql-account-owners", dataset: "bank", topic: "joins", title: "Accounts and owners", difficulty: "Medium", prompt: "List each account with its owner's name and its type, ordered by owner name, then account id. Show owner, account_id, type.", hint: "accounts joins customers on customer_id.", solution: "SELECT c.name AS owner, a.id AS account_id, a.type FROM accounts a JOIN customers c ON c.id = a.customer_id ORDER BY c.name, a.id", ordered: true, concepts: ["JOIN"] }),
  sql({ id: "sql-customer-products", dataset: "shop", topic: "joins", title: "What each customer bought", difficulty: "Medium", prompt: "Which distinct products has each customer ordered, ignoring cancelled orders? Show customer and product, ordered by customer then product.", hint: "customers, orders, order_items, products: four tables. DISTINCT removes repeats.", solution: "SELECT DISTINCT c.name AS customer, p.name AS product FROM customers c JOIN orders o ON o.customer_id = c.id JOIN order_items oi ON oi.order_id = o.id JOIN products p ON p.id = oi.product_id WHERE o.status <> 'cancelled' ORDER BY c.name, p.name", ordered: true, concepts: ["4-table JOIN", "DISTINCT"] }),
  sql({ id: "sql-no-project", dataset: "company", topic: "joins", title: "Not on any project", difficulty: "Medium", prompt: "Employees who are not assigned to any project: names, alphabetical.", hint: "NOT EXISTS against assignments.", solution: "SELECT name FROM employees e WHERE NOT EXISTS (SELECT 1 FROM assignments a WHERE a.employee_id = e.id) ORDER BY name", ordered: true, concepts: ["NOT EXISTS"] }),
  sql({ id: "sql-teacher-reach", dataset: "school", topic: "joins", title: "Teacher reach", difficulty: "Hard", prompt: "For each teacher, how many different students are enrolled in their courses? Show teacher and students, most first (ties by teacher name).", hint: "A student can take two of one teacher's courses, so count DISTINCT student_id.", solution: "SELECT t.name AS teacher, COUNT(DISTINCT e.student_id) AS students FROM teachers t JOIN courses c ON c.teacher_id = t.id JOIN enrollments e ON e.course_id = c.id GROUP BY t.id, t.name ORDER BY students DESC, t.name", ordered: true, concepts: ["COUNT DISTINCT", "multi-table JOIN"] }),

  /* ---------------------------------------- subqueries and CTEs ---------------------------------------- */
  sql({ id: "sql-never-borrowed", dataset: "library", topic: "subqueries", title: "Never borrowed", difficulty: "Easy", prompt: "Books that have never been loaned: titles, alphabetical.", hint: "id NOT IN (SELECT book_id FROM loans). Loans never has a NULL book_id here, so NOT IN is safe.", solution: "SELECT title FROM books WHERE id NOT IN (SELECT book_id FROM loans) ORDER BY title", ordered: true, concepts: ["NOT IN", "subquery"] }),
  sql({ id: "sql-above-overall-average", dataset: "school", topic: "subqueries", title: "Above the overall average", difficulty: "Medium", prompt: "Enrollments scoring above the overall average score: student, course and score, highest first (ties by student, then course).", hint: "A scalar subquery in WHERE: score > (SELECT AVG(score) FROM enrollments).", solution: "SELECT s.name AS student, c.title AS course, e.score FROM enrollments e JOIN students s ON s.id = e.student_id JOIN courses c ON c.id = e.course_id WHERE e.score > (SELECT AVG(score) FROM enrollments) ORDER BY e.score DESC, s.name, c.title", ordered: true, concepts: ["scalar subquery"] }),
  sql({ id: "sql-accounts-big-withdrawal", dataset: "bank", topic: "subqueries", title: "Accounts with a big withdrawal", difficulty: "Medium", prompt: "Accounts that have ever had a withdrawal of 1,000 or more. Use EXISTS. Show the account id, ordered by id.", hint: "A correlated EXISTS: look for one matching transaction per account.", solution: "SELECT a.id FROM accounts a WHERE EXISTS (SELECT 1 FROM transactions t WHERE t.account_id = a.id AND t.amount <= -1000) ORDER BY a.id", ordered: true, concepts: ["EXISTS", "correlated subquery"] }),
  sql({ id: "sql-rich-departments", dataset: "company", topic: "subqueries", title: "Departments above the company average", difficulty: "Medium", prompt: "Departments whose average salary is above the company-wide average salary: names, alphabetical.", hint: "HAVING AVG(...) > (SELECT AVG(...) FROM employees).", solution: "SELECT d.name FROM departments d JOIN employees e ON e.department_id = d.id GROUP BY d.id, d.name HAVING AVG(e.salary) > (SELECT AVG(salary) FROM employees) ORDER BY d.name", ordered: true, concepts: ["HAVING", "scalar subquery"] }),
  sql({ id: "sql-pricey-for-category", dataset: "shop", topic: "subqueries", title: "Pricey for its category", difficulty: "Medium", prompt: "Products priced above their own category's average price: name, category and price, ordered by category then name.", hint: "A correlated subquery that averages price over the same category.", solution: "SELECT p.name, p.category, p.price FROM products p WHERE p.price > (SELECT AVG(price) FROM products WHERE category = p.category) ORDER BY p.category, p.name", ordered: true, concepts: ["correlated subquery"] }),
  sql({ id: "sql-heavy-listeners", dataset: "streaming", topic: "subqueries", title: "Heavy listeners", difficulty: "Medium", prompt: "Users who played more songs than the average listener (average over users with at least one play): name and plays, most first (ties by name).", hint: "Compute plays per user in a CTE, then compare to the average of that CTE.", solution: "WITH counts AS (SELECT user_id, COUNT(*) AS n FROM plays GROUP BY user_id) SELECT u.name, c.n AS plays FROM counts c JOIN users u ON u.id = c.user_id WHERE c.n > (SELECT AVG(n) FROM counts) ORDER BY c.n DESC, u.name", ordered: true, concepts: ["CTE", "scalar subquery"] }),
  sql({ id: "sql-big-depositors", dataset: "bank", topic: "subqueries", title: "Big depositors", difficulty: "Medium", prompt: "Using a CTE: customers whose total deposits (positive amounts across all their accounts) exceed 6,000. Show name and total, largest total first (ties by name).", hint: "WITH deposits AS (...), then join it to customers and filter.", solution: "WITH deposits AS (SELECT a.customer_id, SUM(t.amount) AS total FROM transactions t JOIN accounts a ON a.id = t.account_id WHERE t.amount > 0 GROUP BY a.customer_id) SELECT c.name, d.total FROM deposits d JOIN customers c ON c.id = d.customer_id WHERE d.total > 6000 ORDER BY d.total DESC, c.name", ordered: true, concepts: ["CTE", "JOIN", "SUM"] }),
  sql({ id: "sql-course-champions", dataset: "school", topic: "subqueries", title: "Course champions", difficulty: "Hard", prompt: "For each course that has scores, who scored highest? Show course, student and score, and show every student who ties for the top. Order by course, then student.", hint: "A correlated subquery for the course's MAX(score), compared in WHERE.", solution: "SELECT c.title AS course, s.name AS student, e.score FROM enrollments e JOIN courses c ON c.id = e.course_id JOIN students s ON s.id = e.student_id WHERE e.score = (SELECT MAX(e2.score) FROM enrollments e2 WHERE e2.course_id = e.course_id) ORDER BY c.title, s.name", ordered: true, concepts: ["correlated subquery", "MAX", "ties"] }),

  /* -------------------------------------------- window functions -------------------------------------------- */
  sql({ id: "sql-cumulative-loans", dataset: "library", topic: "windows", title: "Loans so far", difficulty: "Easy", prompt: "After each loan, how many loans have been made so far? Show id, loaned_on and loans_so_far, in order of loan date then id.", hint: "COUNT(*) OVER (ORDER BY loaned_on, id).", solution: "SELECT id, loaned_on, COUNT(*) OVER (ORDER BY loaned_on, id) AS loans_so_far FROM loans ORDER BY loaned_on, id", ordered: true, concepts: ["window function", "running count"] }),
  sql({ id: "sql-running-balance", dataset: "bank", topic: "windows", title: "Running balance", difficulty: "Medium", prompt: "The running balance of account 1 after each transaction: id, txn_date, amount and balance, in date then id order.", hint: "SUM(amount) OVER (ORDER BY txn_date, id).", solution: "SELECT id, txn_date, amount, SUM(amount) OVER (ORDER BY txn_date, id) AS balance FROM transactions WHERE account_id = 1 ORDER BY txn_date, id", ordered: true, concepts: ["window function", "running total"] }),
  sql({ id: "sql-latest-play", dataset: "streaming", topic: "windows", title: "Latest play per user", difficulty: "Medium", prompt: "Each user's most recent play: user, song title and played_on. If a user played twice on their last day, take the later play (higher id). Order by user. Users with no plays are left out.", hint: "ROW_NUMBER() OVER (PARTITION BY user_id ORDER BY played_on DESC, id DESC), keep row 1.", solution: "WITH ranked AS (SELECT p.user_id, p.song_id, p.played_on, ROW_NUMBER() OVER (PARTITION BY p.user_id ORDER BY p.played_on DESC, p.id DESC) AS rn FROM plays p) SELECT u.name AS user, s.title, r.played_on FROM ranked r JOIN users u ON u.id = r.user_id JOIN songs s ON s.id = r.song_id WHERE r.rn = 1 ORDER BY u.name", ordered: true, concepts: ["ROW_NUMBER", "PARTITION BY", "top-1 per group"] }),
  sql({ id: "sql-previous-loan", dataset: "library", topic: "windows", title: "Previous loan", difficulty: "Medium", prompt: "For every loan show the member, the loan date and that member's previous loan date (NULL for their first). Order by member name, loan date, then loan id.", hint: "LAG(loaned_on) OVER (PARTITION BY member_id ORDER BY loaned_on, id).", solution: "SELECT m.name AS member, l.loaned_on, LAG(l.loaned_on) OVER (PARTITION BY l.member_id ORDER BY l.loaned_on, l.id) AS previous FROM loans l JOIN members m ON m.id = l.member_id ORDER BY m.name, l.loaned_on, l.id", ordered: true, concepts: ["LAG", "PARTITION BY"] }),
  sql({ id: "sql-score-vs-course", dataset: "school", topic: "windows", title: "Score versus course average", difficulty: "Medium", prompt: "For every scored enrollment show student, course, score, the course's average score (1 decimal) and the difference from it (1 decimal). Order by course, then student.", hint: "AVG(score) OVER (PARTITION BY course_id) keeps every row, unlike GROUP BY.", solution: "SELECT s.name AS student, c.title AS course, e.score, ROUND(AVG(e.score) OVER (PARTITION BY e.course_id), 1) AS course_avg, ROUND(e.score - AVG(e.score) OVER (PARTITION BY e.course_id), 1) AS diff FROM enrollments e JOIN students s ON s.id = e.student_id JOIN courses c ON c.id = e.course_id WHERE e.score IS NOT NULL ORDER BY c.title, s.name", ordered: true, concepts: ["AVG OVER", "PARTITION BY"] }),
  sql({ id: "sql-salary-tiers", dataset: "company", topic: "windows", title: "Salary tiers", difficulty: "Medium", prompt: "Split employees into 3 salary tiers with NTILE (tier 1 = best paid; break salary ties by name). Show name, salary and tier, ordered by salary descending then name.", hint: "NTILE(3) OVER (ORDER BY salary DESC, name).", solution: "SELECT name, salary, NTILE(3) OVER (ORDER BY salary DESC, name) AS tier FROM employees ORDER BY salary DESC, name", ordered: true, concepts: ["NTILE"] }),
  sql({ id: "sql-algebra-scoreboard", dataset: "school", topic: "windows", title: "Algebra scoreboard", difficulty: "Medium", prompt: "A scoreboard for Algebra: student, score and DENSE_RANK (1 = best), skipping missing scores, ordered by rank then student.", hint: "Filter the course first, then DENSE_RANK() OVER (ORDER BY score DESC).", solution: "SELECT s.name AS student, e.score, DENSE_RANK() OVER (ORDER BY e.score DESC) AS position FROM enrollments e JOIN students s ON s.id = e.student_id JOIN courses c ON c.id = e.course_id WHERE c.title = 'Algebra' AND e.score IS NOT NULL ORDER BY position, s.name", ordered: true, concepts: ["DENSE_RANK"] }),
  sql({ id: "sql-rank-students", dataset: "school", topic: "windows", title: "Rank by average", difficulty: "Hard", prompt: "Rank students by their average score, highest first, skipping students with no scores. Show name, average (1 decimal) and rank, where equal averages share a rank (RANK, so the next rank is skipped). Order by rank then name.", hint: "Average per student in a CTE, then RANK() OVER (ORDER BY avg DESC). Round before ranking so equal rounded averages tie.", solution: "WITH avgs AS (SELECT student_id, ROUND(AVG(score), 1) AS avg_score FROM enrollments GROUP BY student_id HAVING COUNT(score) > 0) SELECT s.name, a.avg_score, RANK() OVER (ORDER BY a.avg_score DESC) AS rnk FROM avgs a JOIN students s ON s.id = a.student_id ORDER BY rnk, s.name", ordered: true, concepts: ["RANK", "CTE", "ties"] }),
  sql({ id: "sql-monthly-net-change", dataset: "bank", topic: "windows", title: "Month-over-month change", difficulty: "Hard", prompt: "Net money movement per month across the whole bank (the sum of all amounts), with the change from the previous month: month (YYYY-MM), net and change (NULL for the first month). In month order.", hint: "Aggregate by month in a CTE, then LAG(net) OVER (ORDER BY month).", solution: "WITH monthly AS (SELECT strftime('%Y-%m', txn_date) AS month, SUM(amount) AS net FROM transactions GROUP BY month) SELECT month, net, net - LAG(net) OVER (ORDER BY month) AS change FROM monthly ORDER BY month", ordered: true, concepts: ["LAG", "CTE", "strftime"] }),
  sql({ id: "sql-top-songs-per-genre", dataset: "streaming", topic: "windows", title: "Top two songs per genre", difficulty: "Hard", prompt: "The 2 most played songs in each genre (more plays first, title breaks ties): genre, title and plays, ordered by genre then rank.", hint: "Count plays per song, then ROW_NUMBER() OVER (PARTITION BY genre ORDER BY plays DESC, title) and keep rn <= 2.", solution: "WITH c AS (SELECT s.genre, s.title, COUNT(*) AS plays FROM plays p JOIN songs s ON s.id = p.song_id GROUP BY s.id, s.genre, s.title), r AS (SELECT genre, title, plays, ROW_NUMBER() OVER (PARTITION BY genre ORDER BY plays DESC, title) AS rn FROM c) SELECT genre, title, plays FROM r WHERE rn <= 2 ORDER BY genre, rn", ordered: true, concepts: ["ROW_NUMBER", "top-N per group", "CTE"] }),

  /* --------------------------------------------- dates and strings --------------------------------------------- */
  sql({ id: "sql-artist-initial", dataset: "streaming", topic: "dates-strings", title: "Song labels", difficulty: "Easy", prompt: "For each song show the title in UPPER case as title_upper, the artist's first letter as initial, and the title's length as title_length. Order by title.", hint: "UPPER(), SUBSTR(x, 1, 1) and LENGTH().", solution: "SELECT UPPER(title) AS title_upper, SUBSTR(artist, 1, 1) AS initial, LENGTH(title) AS title_length FROM songs ORDER BY title", ordered: true, concepts: ["UPPER", "SUBSTR", "LENGTH"] }),
  sql({ id: "sql-name-badge", dataset: "bank", topic: "dates-strings", title: "Name badge", difficulty: "Easy", prompt: "Build a badge text for each customer: NAME (CITY), both in upper case, for example MAYA (PUNE). Column badge, ordered by customer id.", hint: "SQLite joins strings with ||.", solution: "SELECT UPPER(name) || ' (' || UPPER(city) || ')' AS badge FROM customers ORDER BY id", ordered: true, concepts: ["string concatenation", "UPPER"] }),
  sql({ id: "sql-student-age", dataset: "school", topic: "dates-strings", title: "Student ages", difficulty: "Medium", prompt: "Each student's age in whole years on 2024-09-01: name and age, oldest first (ties by name).", hint: "(julianday('2024-09-01') - julianday(born)) / 365.25, cast to INTEGER to drop the fraction.", solution: "SELECT name, CAST((julianday('2024-09-01') - julianday(born)) / 365.25 AS INTEGER) AS age FROM students ORDER BY age DESC, name", ordered: true, concepts: ["julianday", "date arithmetic"] }),
  sql({ id: "sql-monthly-spend", dataset: "bank", topic: "dates-strings", title: "Monthly spending", difficulty: "Medium", prompt: "Total withdrawals per month as a positive number: month (YYYY-MM) and spent, in month order.", hint: "strftime('%Y-%m', txn_date), filter amount < 0, negate the SUM.", solution: "SELECT strftime('%Y-%m', txn_date) AS month, -SUM(amount) AS spent FROM transactions WHERE amount < 0 GROUP BY month ORDER BY month", ordered: true, concepts: ["strftime", "GROUP BY"] }),
  sql({ id: "sql-days-on-loan", dataset: "library", topic: "dates-strings", title: "Days on loan", difficulty: "Medium", prompt: "For returned loans, how many days was the book out? Show loan id and days, longest first (ties by id).", hint: "julianday(returned_on) - julianday(loaned_on), and skip loans with returned_on NULL.", solution: "SELECT id, CAST(julianday(returned_on) - julianday(loaned_on) AS INTEGER) AS days FROM loans WHERE returned_on IS NOT NULL ORDER BY days DESC, id", ordered: true, concepts: ["julianday", "NULL"] }),
  sql({ id: "sql-tenure", dataset: "company", topic: "dates-strings", title: "Tenure", difficulty: "Medium", prompt: "Whole years of tenure on 2024-01-01 for each employee: name and years, longest first (ties by name).", hint: "Same idea as an age: days between dates divided by 365.25, cast to INTEGER.", solution: "SELECT name, CAST((julianday('2024-01-01') - julianday(hire_date)) / 365.25 AS INTEGER) AS years FROM employees ORDER BY years DESC, name", ordered: true, concepts: ["julianday"] }),
  sql({ id: "sql-plays-weekday", dataset: "streaming", topic: "dates-strings", title: "Plays by weekday", difficulty: "Medium", prompt: "Plays per day of the week (0 = Sunday ... 6 = Saturday): weekday number and plays, in weekday order.", hint: "strftime('%w', played_on) gives the weekday number as text; cast it to INTEGER.", solution: "SELECT CAST(strftime('%w', played_on) AS INTEGER) AS weekday, COUNT(*) AS plays FROM plays GROUP BY weekday ORDER BY weekday", ordered: true, concepts: ["strftime", "GROUP BY"] }),

  /* ---------------------------------------------- NULLs and sets ---------------------------------------------- */
  sql({ id: "sql-uncategorised", dataset: "bank", topic: "nulls-sets", title: "Uncategorised", difficulty: "Easy", prompt: "Which transactions have no category? Show id and amount, ordered by id.", hint: "category IS NULL. = NULL never matches.", solution: "SELECT id, amount FROM transactions WHERE category IS NULL ORDER BY id", ordered: true, concepts: ["IS NULL"] }),
  sql({ id: "sql-missing-scores", dataset: "school", topic: "nulls-sets", title: "Missing scores", difficulty: "Easy", prompt: "Which students have at least one enrollment with a missing score? Names, alphabetical, each once.", hint: "Join enrollments, filter score IS NULL, DISTINCT.", solution: "SELECT DISTINCT s.name FROM students s JOIN enrollments e ON e.student_id = s.id WHERE e.score IS NULL ORDER BY s.name", ordered: true, concepts: ["IS NULL", "DISTINCT"] }),
  sql({ id: "sql-city-fallback", dataset: "school", topic: "nulls-sets", title: "City fallback", difficulty: "Easy", prompt: "Show each student's name and city, writing unknown where the city is missing. Ordered by name.", hint: "COALESCE(city, 'unknown').", solution: "SELECT name, COALESCE(city, 'unknown') AS city FROM students ORDER BY name", ordered: true, concepts: ["COALESCE"] }),
  sql({ id: "sql-still-out", dataset: "library", topic: "nulls-sets", title: "Still out", difficulty: "Medium", prompt: "Loans not yet returned: book title, member name and loaned_on, oldest loan first (ties by loan id).", hint: "returned_on IS NULL, joined to books and members.", solution: "SELECT b.title, m.name AS member, l.loaned_on FROM loans l JOIN books b ON b.id = l.book_id JOIN members m ON m.id = l.member_id WHERE l.returned_on IS NULL ORDER BY l.loaned_on, l.id", ordered: true, concepts: ["IS NULL", "JOIN"] }),
  sql({ id: "sql-everyone", dataset: "school", topic: "nulls-sets", title: "Everyone in one list", difficulty: "Medium", prompt: "One list of every teacher and every student: columns name and role (teacher or student), ordered by role then name.", hint: "UNION ALL with a constant column for the role.", solution: "SELECT name, 'teacher' AS role FROM teachers UNION ALL SELECT name, 'student' AS role FROM students ORDER BY role, name", ordered: true, concepts: ["UNION ALL"] }),
  sql({ id: "sql-premium-only-songs", dataset: "streaming", topic: "nulls-sets", title: "Premium-only songs", difficulty: "Hard", prompt: "Songs played by at least one premium user but never by a free user: titles, alphabetical. Use set logic (EXCEPT).", hint: "SELECT songs played by premium users EXCEPT SELECT songs played by free users.", solution: "SELECT s.title FROM plays p JOIN users u ON u.id = p.user_id JOIN songs s ON s.id = p.song_id WHERE u.plan = 'premium' EXCEPT SELECT s.title FROM plays p JOIN users u ON u.id = p.user_id JOIN songs s ON s.id = p.song_id WHERE u.plan = 'free' ORDER BY title", ordered: true, concepts: ["EXCEPT", "set difference"] }),

  /* ------------------------------------------- interview patterns ------------------------------------------- */
  sql({ id: "sql-late-loans", dataset: "library", topic: "patterns", title: "Late loans", difficulty: "Hard", prompt: "Loans kept more than 14 days, returned or not (treat a loan not yet returned as still out on 2024-04-01). Show loan id and days_out, longest first (ties by id).", hint: "COALESCE(returned_on, '2024-04-01') gives an end date for open loans.", solution: "SELECT id, CAST(julianday(COALESCE(returned_on, '2024-04-01')) - julianday(loaned_on) AS INTEGER) AS days_out FROM loans WHERE julianday(COALESCE(returned_on, '2024-04-01')) - julianday(loaned_on) > 14 ORDER BY days_out DESC, id", ordered: true, concepts: ["COALESCE", "date arithmetic"] }),
  sql({ id: "sql-term-pivot", dataset: "school", topic: "patterns", title: "Pivot by term", difficulty: "Hard", prompt: "For each student with at least one score show the average of their 2024F scores and of their 2024S scores in two columns, fall and spring (NULL when none), each rounded to 1 decimal. Order by name.", hint: "Conditional aggregation: AVG(CASE WHEN term = '2024F' THEN score END).", solution: "SELECT s.name, ROUND(AVG(CASE WHEN e.term = '2024F' THEN e.score END), 1) AS fall, ROUND(AVG(CASE WHEN e.term = '2024S' THEN e.score END), 1) AS spring FROM students s JOIN enrollments e ON e.student_id = s.id GROUP BY s.id, s.name HAVING COUNT(e.score) > 0 ORDER BY s.name", ordered: true, concepts: ["conditional aggregation", "pivot"] }),
  sql({ id: "sql-back-to-back-days", dataset: "streaming", topic: "patterns", title: "Back-to-back days", difficulty: "Hard", prompt: "Users who played on two consecutive days at least once: names, alphabetical.", hint: "Self-join plays where the second play is exactly one day after the first.", solution: "SELECT DISTINCT u.name FROM plays a JOIN plays b ON b.user_id = a.user_id AND julianday(b.played_on) = julianday(a.played_on) + 1 JOIN users u ON u.id = a.user_id ORDER BY u.name", ordered: true, concepts: ["self join", "consecutive days"] }),
  sql({ id: "sql-longest-streak", dataset: "streaming", topic: "patterns", title: "Longest listening streak", difficulty: "Hard", prompt: "The longest run of consecutive days with at least one play, per user (users with plays only): name and longest_streak, best first (ties by name).", hint: "Gaps and islands: number each user's distinct days, subtract the number from the date; days in one run share the same result.", solution: "WITH days AS (SELECT DISTINCT user_id, played_on AS d FROM plays), g AS (SELECT user_id, d, julianday(d) - ROW_NUMBER() OVER (PARTITION BY user_id ORDER BY d) AS grp FROM days), runs AS (SELECT user_id, COUNT(*) AS len FROM g GROUP BY user_id, grp) SELECT u.name, MAX(r.len) AS longest_streak FROM runs r JOIN users u ON u.id = r.user_id GROUP BY u.id, u.name ORDER BY longest_streak DESC, u.name", ordered: true, concepts: ["gaps and islands", "ROW_NUMBER", "CTE"] }),
];
