/**
 * More MongoDB-style challenges, written for PrepOS. They only use operators the in-browser engine supports
 * (modules/dsa/domain/mongo-query.ts), and every ordered one names its tie-break.
 */
import type { DbChallenge } from "@/modules/dsa/domain/db-lab";

type C = Omit<DbChallenge, "mode">;
const mongo = (c: C): DbChallenge => ({ ...c, mode: "mongo" });

export const EXTRA_MONGO_CHALLENGES: readonly DbChallenge[] = [
  /* --------------------------------------------- shop (existing data) --------------------------------------------- */
  mongo({ id: "mongo-young-users", dataset: "shop", topic: "find", title: "Younger than 30", difficulty: "Easy", prompt: "Users younger than 30: name and age (no _id), youngest first.", hint: "{ age: { $lt: 30 } }, a projection with _id: 0, and sort({ age: 1 }).", solution: "db.users.find({ age: { $lt: 30 } }, { name: 1, age: 1, _id: 0 }).sort({ age: 1 })", ordered: true, concepts: ["$lt", "projection", "sort"] }),
  mongo({ id: "mongo-not-us-in", dataset: "shop", topic: "find", title: "Outside the US and India", difficulty: "Easy", prompt: "Users whose country is neither US nor IN: names only (no _id), ordered by name.", hint: "$nin takes a list of values to exclude.", solution: "db.users.find({ country: { $nin: ['US', 'IN'] } }, { name: 1, _id: 0 }).sort({ name: 1 })", ordered: true, concepts: ["$nin"] }),
  mongo({ id: "mongo-low-stock", dataset: "shop", topic: "find", title: "Low stock", difficulty: "Easy", prompt: "Products with fewer than 50 units in stock: name and stock (no _id), fewest first.", hint: "{ stock: { $lt: 50 } } then sort ascending.", solution: "db.products.find({ stock: { $lt: 50 } }, { name: 1, stock: 1, _id: 0 }).sort({ stock: 1 })", ordered: true, concepts: ["$lt", "sort"] }),
  mongo({ id: "mongo-untagged", dataset: "shop", topic: "arrays", title: "Users with no tags", difficulty: "Easy", prompt: "Which users have an empty tags array? Names only (no _id).", hint: "$size matches arrays of an exact length.", solution: "db.users.find({ tags: { $size: 0 } }, { name: 1, _id: 0 })", ordered: false, concepts: ["$size"] }),
  mongo({ id: "mongo-vip-and-newsletter", dataset: "shop", topic: "arrays", title: "VIP and newsletter", difficulty: "Medium", prompt: "Users tagged both vip and newsletter: names only (no _id).", hint: "$all requires every listed value to be in the array.", solution: "db.users.find({ tags: { $all: ['vip', 'newsletter'] } }, { name: 1, _id: 0 })", ordered: false, concepts: ["$all"] }),
  mongo({ id: "mongo-items-per-order", dataset: "shop", topic: "aggregation", title: "Line items per order", difficulty: "Easy", prompt: "How many line items does each order have? Show _id and itemCount, ordered by _id.", hint: "$project a computed field with $size, then $sort.", solution: "db.orders.aggregate([{ $project: { itemCount: { $size: '$items' } } }, { $sort: { _id: 1 } }])", ordered: true, concepts: ["$project", "$size"] }),
  mongo({ id: "mongo-avg-price-category", dataset: "shop", topic: "aggregation", title: "Average price per category", difficulty: "Medium", prompt: "Average product price per category, rounded to 1 decimal, highest average first (ties by category).", hint: "$group by '$category' with $avg of '$price', then $project with $round, then $sort.", solution: "db.products.aggregate([{ $group: { _id: '$category', avgPrice: { $avg: '$price' } } }, { $project: { avgPrice: { $round: ['$avgPrice', 1] } } }, { $sort: { avgPrice: -1, _id: 1 } }])", ordered: true, concepts: ["$group", "$avg"] }),

  /* ------------------------------------------------- blog ------------------------------------------------- */
  mongo({ id: "mongo-published-posts", dataset: "blog", topic: "find", title: "Published posts", difficulty: "Easy", prompt: "Published posts: title and createdAt (no _id), oldest first.", hint: "{ published: true }, then sort by createdAt.", solution: "db.posts.find({ published: true }, { title: 1, createdAt: 1, _id: 0 }).sort({ createdAt: 1 })", ordered: true, concepts: ["find", "sort"] }),
  mongo({ id: "mongo-popular-posts", dataset: "blog", topic: "find", title: "Popular posts", difficulty: "Easy", prompt: "Posts with at least 800 views: title and views (no _id), most viewed first.", hint: "{ views: { $gte: 800 } }", solution: "db.posts.find({ views: { $gte: 800 } }, { title: 1, views: 1, _id: 0 }).sort({ views: -1 })", ordered: true, concepts: ["$gte", "sort"] }),
  mongo({ id: "mongo-tag-mongodb", dataset: "blog", topic: "arrays", title: "Tagged mongodb", difficulty: "Easy", prompt: "Titles of posts tagged mongodb (no _id), alphabetical.", hint: "Matching a value against an array field matches any element.", solution: "db.posts.find({ tags: 'mongodb' }, { title: 1, _id: 0 }).sort({ title: 1 })", ordered: true, concepts: ["array fields"] }),
  mongo({ id: "mongo-liked-comments", dataset: "blog", topic: "arrays", title: "A well-liked comment", difficulty: "Medium", prompt: "Posts that have at least one comment with 5 or more likes: titles only (no _id), alphabetical.", hint: "$elemMatch makes the conditions apply to the same array element.", solution: "db.posts.find({ comments: { $elemMatch: { likes: { $gte: 5 } } } }, { title: 1, _id: 0 }).sort({ title: 1 })", ordered: true, concepts: ["$elemMatch"] }),
  mongo({ id: "mongo-views-per-author", dataset: "blog", topic: "aggregation", title: "Views per author", difficulty: "Medium", prompt: "Total views per authorId, highest first (ties by authorId).", hint: "$group by '$authorId' with $sum of '$views'.", solution: "db.posts.aggregate([{ $group: { _id: '$authorId', views: { $sum: '$views' } } }, { $sort: { views: -1, _id: 1 } }])", ordered: true, concepts: ["$group", "$sum"] }),
  mongo({ id: "mongo-tag-counts", dataset: "blog", topic: "aggregation", title: "Most used tags", difficulty: "Medium", prompt: "The 5 tags used on the most posts: tag (_id) and count, most first, ties alphabetical.", hint: "$unwind the tags array, $group by tag, $sort, $limit 5.", solution: "db.posts.aggregate([{ $unwind: '$tags' }, { $group: { _id: '$tags', count: { $sum: 1 } } }, { $sort: { count: -1, _id: 1 } }, { $limit: 5 }])", ordered: true, concepts: ["$unwind", "$group", "$limit"] }),
  mongo({ id: "mongo-posts-with-author", dataset: "blog", topic: "lookup", title: "Posts with their author", difficulty: "Medium", prompt: "Each post's title with its author's name as author, ordered by post _id.", hint: "$lookup authors on authorId = _id, $unwind the result, then $project.", solution: "db.posts.aggregate([{ $lookup: { from: 'authors', localField: 'authorId', foreignField: '_id', as: 'a' } }, { $unwind: '$a' }, { $project: { title: 1, author: '$a.name' } }, { $sort: { _id: 1 } }])", ordered: true, concepts: ["$lookup", "$unwind", "$project"] }),
  mongo({ id: "mongo-top-commenters", dataset: "blog", topic: "patterns", title: "Top commenters", difficulty: "Hard", prompt: "The 3 users who left the most comments across all posts: user (_id) and comments, most first, ties alphabetical.", hint: "$unwind the embedded comments array, then $group by comments.user.", solution: "db.posts.aggregate([{ $unwind: '$comments' }, { $group: { _id: '$comments.user', comments: { $sum: 1 } } }, { $sort: { comments: -1, _id: 1 } }, { $limit: 3 }])", ordered: true, concepts: ["$unwind", "embedded documents", "$group"] }),

  /* ---------------------------------------------- product events ---------------------------------------------- */
  mongo({ id: "mongo-purchases", dataset: "events", topic: "find", title: "Purchases", difficulty: "Easy", prompt: "All purchase events: _id, userId and amount, in time order.", hint: "{ type: 'purchase' }, projection, sort by ts.", solution: "db.events.find({ type: 'purchase' }, { userId: 1, amount: 1 }).sort({ ts: 1 })", ordered: true, concepts: ["find", "projection"] }),
  mongo({ id: "mongo-blog-visits", dataset: "events", topic: "find", title: "Blog visits", difficulty: "Medium", prompt: "Events on pages under /blog/: _id, page and type, ordered by _id.", hint: "$regex with ^ anchors the match at the start.", solution: "db.events.find({ page: { $regex: '^/blog/' } }, { page: 1, type: 1 }).sort({ _id: 1 })", ordered: true, concepts: ["$regex"] }),
  mongo({ id: "mongo-events-per-type", dataset: "events", topic: "aggregation", title: "Events per type", difficulty: "Easy", prompt: "How many events of each type? Type (_id) and count, most common first, ties alphabetical.", hint: "$group by '$type' with { $sum: 1 }.", solution: "db.events.aggregate([{ $group: { _id: '$type', count: { $sum: 1 } } }, { $sort: { count: -1, _id: 1 } }])", ordered: true, concepts: ["$group", "$sum"] }),
  mongo({ id: "mongo-first-event", dataset: "events", topic: "patterns", title: "First page per user", difficulty: "Medium", prompt: "The first page each user visited, by time: userId (_id) and firstPage, ordered by user.", hint: "$sort by ts first, then $group by userId with $first of '$page'.", solution: "db.events.aggregate([{ $sort: { ts: 1 } }, { $group: { _id: '$userId', firstPage: { $first: '$page' } } }, { $sort: { _id: 1 } }])", ordered: true, concepts: ["$first", "sort before group"] }),
  mongo({ id: "mongo-silent-users", dataset: "events", topic: "lookup", title: "Users with no events", difficulty: "Medium", prompt: "Users who have no events at all: names only (no _id).", hint: "$lookup events into an array, then $match arrays of size 0.", solution: "db.users.aggregate([{ $lookup: { from: 'events', localField: '_id', foreignField: 'userId', as: 'ev' } }, { $match: { ev: { $size: 0 } } }, { $project: { name: 1, _id: 0 } }])", ordered: false, concepts: ["$lookup", "$size", "anti-join"] }),
  mongo({ id: "mongo-revenue-by-country", dataset: "events", topic: "lookup", title: "Revenue by country", difficulty: "Hard", prompt: "Purchase revenue per user country: country (_id) and revenue, highest first (ties by country).", hint: "$match purchases, $lookup users, $unwind, then $group by '$u.country'.", solution: "db.events.aggregate([{ $match: { type: 'purchase' } }, { $lookup: { from: 'users', localField: 'userId', foreignField: '_id', as: 'u' } }, { $unwind: '$u' }, { $group: { _id: '$u.country', revenue: { $sum: '$amount' } } }, { $sort: { revenue: -1, _id: 1 } }])", ordered: true, concepts: ["$lookup", "$unwind", "$group"] }),
  mongo({ id: "mongo-views-and-purchases", dataset: "events", topic: "patterns", title: "Views and purchases per user", difficulty: "Hard", prompt: "For each user count their view events and their purchase events: userId (_id), views and purchases, ordered by user.", hint: "Conditional counting: $sum of { $cond: [ { $eq: ['$type', 'view'] }, 1, 0 ] }.", solution: "db.events.aggregate([{ $group: { _id: '$userId', views: { $sum: { $cond: [{ $eq: ['$type', 'view'] }, 1, 0] } }, purchases: { $sum: { $cond: [{ $eq: ['$type', 'purchase'] }, 1, 0] } } } }, { $sort: { _id: 1 } }])", ordered: true, concepts: ["$cond", "conditional counting"] }),
];
