/**
 * Static interview prompts for the written mock rounds. Used as-is when no AI is configured, and as the
 * fallback when the AI's questions don't validate. Each prompt carries the points a strong answer covers,
 * which the grader (AI or you, in self-review) scores against.
 */

export interface BankPrompt {
  id: string;
  prompt: string;
  /** What a strong answer covers. */
  points: string[];
}

export interface SqlPrompt extends BankPrompt {
  schema: string;
  reference: string;
}

export const JS_CONCEPTS: BankPrompt[] = [
  { id: "js-event-loop", prompt: "Walk me through the event loop. Where do promises, setTimeout and queueMicrotask callbacks go, and in what order do they run?", points: ["Call stack runs to completion", "Microtask queue (promises, queueMicrotask) drains fully after each task", "Macrotasks (timers, I/O) one per loop turn", "Rendering happens between tasks in browsers", "Starving the loop with microtasks"] },
  { id: "js-closures", prompt: "What is a closure? Show a real use, and a bug closures commonly cause.", points: ["Function keeps access to its lexical scope after the outer function returns", "Use: data privacy, memoisation, factories, debounce", "Classic var-in-loop bug and the let fix", "Memory retention of captured variables"] },
  { id: "js-this", prompt: "How is `this` decided in JavaScript? Cover normal functions, methods, arrow functions, call/apply/bind and `new`.", points: ["Determined by call site for normal functions", "Method call binds the object", "Arrow functions capture lexical this", "call/apply/bind set it explicitly; bind is permanent", "new binds a fresh object", "Strict mode: undefined instead of globalThis"] },
  { id: "js-prototypes", prompt: "Explain prototypal inheritance. How do ES classes relate to prototypes?", points: ["Objects link to a prototype via [[Prototype]]", "Property lookup walks the chain", "Classes are syntax over constructor functions and prototypes", "Object.create, super, method sharing on the prototype"] },
  { id: "js-promises", prompt: "Compare Promise.all, allSettled, race and any. When would you use each, and how do errors behave?", points: ["all: fail-fast on first rejection", "allSettled: never rejects, gives every outcome", "race: first settled wins (timeouts)", "any: first fulfilled; AggregateError if all reject", "Unhandled rejections"] },
  { id: "js-debounce", prompt: "Implement debounce and explain how it differs from throttle. Where would you use each?", points: ["Debounce delays until calls stop for N ms", "Throttle runs at most once per N ms", "Clear and reset the timer; preserve this and args", "Leading/trailing options", "Search input vs scroll handler examples"] },
  { id: "js-equality", prompt: "Explain == vs === and type coercion. Give three surprising coercion results and how to avoid them.", points: ["=== no coercion; == coerces with rules", "null == undefined is true", "Objects compared by reference", "NaN !== NaN, Object.is", "Prefer === and explicit conversion"] },
  { id: "js-memory", prompt: "How does garbage collection work in V8, and what causes memory leaks in a long-running JS app?", points: ["Reachability from roots; mark-and-sweep", "Generational: young and old space", "Leaks: forgotten timers/listeners, global caches, closures, detached DOM", "WeakMap/WeakRef", "Heap snapshots to diagnose"] },
  { id: "js-modules", prompt: "Compare CommonJS and ES modules. What problems come up when mixing them?", points: ["require is sync and dynamic; import is static and async-capable", "Live bindings vs copied exports", "Tree shaking needs ESM", "Interop: default export, __esModule, top-level await", "package.json type and exports field"] },
  { id: "js-hoisting", prompt: "What is hoisting? Explain the temporal dead zone with let/const and how function declarations differ.", points: ["Declarations are processed before execution", "var hoisted and initialised to undefined", "let/const hoisted but in TDZ until declared", "Function declarations fully hoisted; expressions are not"] },
  { id: "js-immutability", prompt: "How do you keep data immutable in JS? Compare Object.freeze, spreading and structuredClone.", points: ["freeze is shallow", "Spread copies one level", "structuredClone deep copies (no functions)", "Why immutability helps React and debugging", "Cost of copying"] },
  { id: "js-generators", prompt: "What are generators and iterators, and how do async iterators help with streams of data?", points: ["Iterator protocol: next() returning {value, done}", "function* yields lazily", "for...of consumes iterables", "Async iterators with for await", "Pagination or stream processing example"] },
];

export const NODE_PROMPTS: BankPrompt[] = [
  { id: "node-event-loop", prompt: "How does Node's event loop differ from the browser's? Explain the phases and where process.nextTick and setImmediate fit.", points: ["libuv phases: timers, pending, poll, check, close", "nextTick queue runs before promise microtasks", "setImmediate runs in check phase", "Blocking the loop hurts every request"] },
  { id: "node-cpu", prompt: "A CPU-heavy endpoint is slowing down every request in your Node service. How do you find and fix it?", points: ["Profile (--prof, clinic, flame graphs)", "Move work to worker_threads or a queue", "Cluster or more instances", "Cache results", "Measure p99 latency before and after"] },
  { id: "node-streams", prompt: "Explain Node streams and backpressure. How would you upload a 5 GB file to S3 without running out of memory?", points: ["Readable, Writable, Transform, Duplex", "pipe/pipeline handle backpressure", "highWaterMark", "Multipart upload in chunks", "Error handling with pipeline"] },
  { id: "node-auth", prompt: "Design authentication for a REST API. Compare sessions and JWTs, and explain how you'd handle refresh tokens and logout.", points: ["Session cookie with server store vs stateless JWT", "Short-lived access token, rotating refresh token", "httpOnly, Secure, SameSite cookies", "Revocation list or token version", "bcrypt/argon2 for passwords"] },
  { id: "node-errors", prompt: "How do you handle errors in an Express or Nest app so nothing crashes the process and clients get useful responses?", points: ["Central error middleware or exception filter", "Async errors caught (express 5 or wrappers)", "Operational vs programmer errors", "unhandledRejection and graceful shutdown", "Consistent error shape and logging with request id"] },
  { id: "node-rate-limit", prompt: "Implement rate limiting for a public API running on several instances. Which algorithm and where is the state?", points: ["Token bucket or sliding window", "Shared store (Redis) or gateway-level limiting", "Per-user and per-IP keys", "429 with Retry-After", "Atomic operations to avoid races"] },
  { id: "node-db-pool", prompt: "What is connection pooling and what goes wrong with database connections in serverless Node?", points: ["Reusing TCP connections, pool size", "Serverless creates many instances, exhausting connections", "Cache the client across invocations", "Proxies like PgBouncer or Data API", "Timeouts and leaks"] },
  { id: "node-idempotency", prompt: "A payment endpoint is called twice because the client retried. How do you make it idempotent?", points: ["Idempotency key from the client", "Store request hash and response", "Unique constraint or transaction", "Return the stored result on replay", "Key expiry"] },
  { id: "node-caching", prompt: "Where would you add caching to a slow read-heavy API, and how do you keep the cache correct?", points: ["HTTP caching, CDN, app cache, DB cache", "Cache-aside pattern", "TTL and explicit invalidation", "Stampede protection", "What not to cache (per-user, sensitive)"] },
  { id: "node-graceful", prompt: "How do you deploy a Node service with zero downtime and shut down gracefully?", points: ["Handle SIGTERM", "Stop accepting, finish in-flight requests", "Close DB pools and queues", "Health/readiness checks", "Rolling or blue-green deploys"] },
  { id: "node-queue", prompt: "When do you move work to a background queue? Design sending 1 million emails reliably.", points: ["Decouple slow or retryable work", "Queue with workers (SQS, BullMQ, Kafka)", "Retries with backoff, dead-letter queue", "Idempotent consumers", "Rate limits of the provider"] },
  { id: "node-security", prompt: "List the main security risks for a Node web API and how you mitigate each.", points: ["Injection: parameterised queries, validation", "XSS and CSRF", "Secrets in env, not code", "Dependency vulnerabilities (npm audit)", "Rate limiting, helmet headers, least privilege"] },
  { id: "node-logging", prompt: "How would you make a Node service observable in production?", points: ["Structured logs (pino) with request ids", "Metrics: latency, error rate, saturation", "Distributed tracing (OpenTelemetry)", "Alerts on SLOs", "Avoid logging secrets"] },
  { id: "node-rest-graphql", prompt: "REST or GraphQL for a mobile app backend? Argue both sides and pick one.", points: ["Over/under-fetching", "Caching is easier with REST", "Schema and typing with GraphQL", "N+1 and DataLoader", "Team and tooling considerations"] },
];

export const LLD_PROMPTS: BankPrompt[] = [
  { id: "lld-parking", prompt: "Design a parking lot system: multiple floors, spot sizes, tickets, payments.", points: ["Classes: ParkingLot, Floor, Spot (by size), Vehicle, Ticket, Payment", "Spot allocation strategy", "Entry/exit flow and fee calculation", "Strategy pattern for pricing", "Concurrency when two cars take one spot"] },
  { id: "lld-elevator", prompt: "Design an elevator system for a building with several elevators.", points: ["Elevator, Controller, Request, Direction, State", "Scheduling algorithm (SCAN/LOOK, nearest car)", "State machine for doors and movement", "Handling internal and external requests", "Extensibility: VIP, maintenance mode"] },
  { id: "lld-splitwise", prompt: "Design Splitwise: groups, expenses split equally, exactly or by percentage, and settling up.", points: ["User, Group, Expense, Split types", "Balance sheet per pair", "Strategy for split types with validation", "Simplify debts", "Precision with money (integers)"] },
  { id: "lld-lru", prompt: "Design an in-memory LRU cache with get, put and a capacity, safe for concurrent use.", points: ["Hash map plus doubly linked list", "O(1) get and put", "Eviction on capacity", "Locking or segmenting for concurrency", "Generic key/value types, TTL extension"] },
  { id: "lld-rate-limiter", prompt: "Design a rate limiter library that supports several algorithms per client.", points: ["Interface RateLimiter with allow(key)", "Token bucket, fixed and sliding window implementations", "Strategy/factory to choose", "Storage abstraction (memory, Redis)", "Thread safety and clock injection for tests"] },
  { id: "lld-library", prompt: "Design a library management system: books, copies, members, loans, fines, reservations.", points: ["Book vs BookItem (copy)", "Member, Loan, Reservation, Fine", "Checkout/return rules and limits", "Observer to notify reservations", "Search by title/author"] },
  { id: "lld-vending", prompt: "Design a vending machine that accepts coins and notes, dispenses items and returns change.", points: ["State pattern: Idle, HasMoney, Dispensing, OutOfStock", "Inventory and Item", "Change-making algorithm", "Cancel and refund", "Admin restock"] },
  { id: "lld-bookmyshow", prompt: "Design a movie ticket booking system like BookMyShow.", points: ["Movie, Theatre, Screen, Show, Seat, Booking", "Seat locking with expiry during payment", "Concurrency: two users, one seat", "Payment and confirmation flow", "Search shows by city and movie"] },
  { id: "lld-logger", prompt: "Design a logging framework with levels, multiple outputs and formatting.", points: ["Logger, Level, Appender (console, file), Formatter", "Chain of responsibility or level filtering", "Singleton or DI for the logger", "Async buffered writes", "Configuration"] },
  { id: "lld-chess", prompt: "Design a two-player chess game.", points: ["Board, Cell, Piece hierarchy, Player, Move, Game", "Each piece validates its moves (polymorphism)", "Check, checkmate, stalemate detection", "Move history and undo (command pattern)", "Special moves: castling, en passant, promotion"] },
];

export const PROJECT_PROMPTS: BankPrompt[] = [
  { id: "proj-overview", prompt: "Give me a two-minute overview of the project you're proudest of: the problem, users, and your role.", points: ["Clear problem and who it's for", "Your specific contribution", "Scale or impact with numbers", "Tech stack and why"] },
  { id: "proj-architecture", prompt: "Draw (describe) the architecture of that project. Why this design and not a simpler one?", points: ["Components and data flow", "Key technology choices with reasons", "Alternatives considered", "What you'd simplify now"] },
  { id: "proj-hardest-bug", prompt: "What was the hardest bug or incident in that project, and how did you find and fix it?", points: ["Symptoms and impact", "Debugging method (logs, repro, bisect)", "Root cause", "Fix and prevention (tests, alerts)"] },
  { id: "proj-scale", prompt: "If traffic grew 100×, what would break first in your project and what would you change?", points: ["Identify the bottleneck honestly", "Database and caching changes", "Horizontal scaling and statelessness", "Cost awareness"] },
  { id: "proj-tradeoff", prompt: "Tell me about a trade-off you made under time pressure. Would you make it again?", points: ["The options and constraints", "Why you chose", "Consequences", "Reflection"] },
  { id: "proj-data", prompt: "Walk me through your data model. How did you choose the database and indexes?", points: ["Entities and relationships", "Access patterns drive the schema", "Indexes for the main queries", "Consistency and migrations"] },
  { id: "proj-testing", prompt: "How did you test the project and keep it working as it changed?", points: ["Unit vs integration vs end-to-end", "What you chose not to test and why", "CI pipeline", "A bug tests caught"] },
  { id: "proj-security", prompt: "What security concerns did the project have and how did you handle them?", points: ["Authentication and authorisation", "Input validation", "Secrets handling", "Data privacy"] },
  { id: "proj-redo", prompt: "If you rebuilt the project from scratch today, what would you do differently?", points: ["Concrete changes, not vague", "Why the original choice was made", "Lessons learned", "What you'd keep"] },
  { id: "proj-perf", prompt: "Describe a performance improvement you made. How did you measure it?", points: ["Baseline metric", "Profiling to find the cause", "The change", "Result with numbers"] },
];

export const BEHAVIORAL_PROMPTS: BankPrompt[] = [
  { id: "beh-conflict", prompt: "Tell me about a time you disagreed with a teammate or lead. What happened?", points: ["Situation and stakes", "How you raised it respectfully", "Data or reasoning used", "Outcome and relationship afterwards"] },
  { id: "beh-failure", prompt: "Tell me about a time you failed or missed a deadline.", points: ["Owns the failure without blaming", "What you did to recover", "Measurable result", "What you changed after"] },
  { id: "beh-ownership", prompt: "Describe a time you took ownership of something outside your job description.", points: ["Gap you noticed", "Initiative taken", "Obstacles", "Impact"] },
  { id: "beh-ambiguity", prompt: "Tell me about a project where the requirements were unclear. How did you move forward?", points: ["How you clarified", "Assumptions made explicit", "Iteration and feedback", "Result"] },
  { id: "beh-learn", prompt: "Tell me about a time you had to learn a new technology quickly.", points: ["Why it was needed", "Learning approach", "How fast you delivered", "Outcome"] },
  { id: "beh-feedback", prompt: "Tell me about critical feedback you received and what you did with it.", points: ["The feedback", "Initial reaction honestly", "Concrete change", "Evidence it worked"] },
  { id: "beh-priority", prompt: "Describe a time you had too many priorities. How did you decide what to drop?", points: ["Competing demands", "Prioritisation method", "Communication with stakeholders", "Result"] },
  { id: "beh-mentor", prompt: "Tell me about a time you helped a teammate grow or get unblocked.", points: ["Their challenge", "How you helped (teach, not do)", "Their outcome", "What you learned"] },
  { id: "beh-impact", prompt: "What is the most impactful thing you've built? How do you know it mattered?", points: ["Problem and users", "Your role", "Metrics", "Why it mattered to the business"] },
  { id: "beh-customer", prompt: "Tell me about a time you went out of your way for a user or customer.", points: ["The user's problem", "Action beyond the minimum", "Result", "Balance with other work"] },
  { id: "beh-why", prompt: "Why do you want to join this company, and why now?", points: ["Specific research on the company", "Link to your skills and goals", "Genuine motivation", "Concise"] },
  { id: "beh-pressure", prompt: "Tell me about a time you worked under significant pressure. How did you keep quality up?", points: ["Pressure source", "How you planned", "Trade-offs and communication", "Outcome"] },
];

const EMP = "Employee(id INT PK, name TEXT, salary INT, departmentId INT, managerId INT NULL)\nDepartment(id INT PK, name TEXT)";
const ORDERS = "Customer(id INT PK, name TEXT, city TEXT)\nOrders(id INT PK, customerId INT, amount DECIMAL, createdAt DATE)";

export const SQL_PROMPTS: SqlPrompt[] = [
  { id: "sql-second-salary", schema: EMP, prompt: "Return the second highest distinct salary, or NULL if there isn't one.", reference: "SELECT MAX(salary) AS second FROM Employee WHERE salary < (SELECT MAX(salary) FROM Employee);", points: ["Handles duplicates (distinct values)", "Returns NULL when missing", "Subquery or window function (DENSE_RANK)", "Explains why LIMIT/OFFSET alone can fail"] },
  { id: "sql-dept-top", schema: EMP, prompt: "For each department, list the employees with the highest salary (ties included).", reference: "SELECT d.name AS department, e.name, e.salary FROM Employee e JOIN Department d ON d.id = e.departmentId WHERE (e.departmentId, e.salary) IN (SELECT departmentId, MAX(salary) FROM Employee GROUP BY departmentId);", points: ["Correct join", "Ties included", "GROUP BY or window function", "Index on (departmentId, salary)"] },
  { id: "sql-manager", schema: EMP, prompt: "Find employees who earn more than their managers.", reference: "SELECT e.name FROM Employee e JOIN Employee m ON e.managerId = m.id WHERE e.salary > m.salary;", points: ["Self-join", "Employees without managers excluded correctly", "Clear aliases"] },
  { id: "sql-no-orders", schema: ORDERS, prompt: "List customers who have never placed an order.", reference: "SELECT c.name FROM Customer c LEFT JOIN Orders o ON o.customerId = c.id WHERE o.id IS NULL;", points: ["LEFT JOIN with IS NULL, or NOT EXISTS", "Avoids NOT IN with NULLs pitfall", "Index on Orders.customerId"] },
  { id: "sql-monthly", schema: ORDERS, prompt: "Show total order amount per month for 2025, including months with no orders as 0.", reference: "WITH months AS (SELECT generate_series('2025-01-01'::date, '2025-12-01', interval '1 month') AS m) SELECT to_char(m, 'YYYY-MM') AS month, COALESCE(SUM(o.amount), 0) AS total FROM months LEFT JOIN Orders o ON date_trunc('month', o.createdAt) = m GROUP BY m ORDER BY m;", points: ["Group by month", "Generates missing months", "COALESCE to 0", "Date range filter that can use an index"] },
  { id: "sql-top-customers", schema: ORDERS, prompt: "Find the top 3 customers by total spend in each city.", reference: "SELECT city, name, total FROM (SELECT c.city, c.name, SUM(o.amount) AS total, DENSE_RANK() OVER (PARTITION BY c.city ORDER BY SUM(o.amount) DESC) AS r FROM Customer c JOIN Orders o ON o.customerId = c.id GROUP BY c.id, c.city, c.name) t WHERE r <= 3;", points: ["Aggregate then rank", "PARTITION BY city", "RANK vs DENSE_RANK vs ROW_NUMBER choice explained", "Ties"] },
  { id: "sql-consecutive", schema: "Logins(userId INT, day DATE)", prompt: "Find users who logged in on at least 3 consecutive days.", reference: "SELECT DISTINCT userId FROM (SELECT userId, day - (ROW_NUMBER() OVER (PARTITION BY userId ORDER BY day))::int AS grp FROM (SELECT DISTINCT userId, day FROM Logins) d) t GROUP BY userId, grp HAVING COUNT(*) >= 3;", points: ["Deduplicate days", "Gaps-and-islands with ROW_NUMBER", "GROUP BY with HAVING", "Alternative with LAG/LEAD"] },
  { id: "sql-duplicates", schema: "Person(id INT PK, email TEXT)", prompt: "Delete duplicate emails, keeping the row with the smallest id.", reference: "DELETE FROM Person p USING Person q WHERE p.email = q.email AND p.id > q.id;", points: ["Keeps smallest id", "Self-join delete or window function", "Mentions adding a unique index afterwards", "Runs in a transaction"] },
];
