import { define, type ProblemDef } from "./define";
import { arrayGen, gen } from "./gen";

/** Striver A2Z rows that link a LeetCode problem PrepOS hadn't seeded. The statement is LeetCode's own. */
const DEFS: ProblemDef[] = [
  {
    slug: "perfect-number",
    title: "Perfect Number",
    difficulty: "Easy",
    pattern: "Math & Geometry",
    leetcodeId: 507,
    fn: "checkPerfectNumber",
    params: [["num", "number"]],
    returns: "boolean",
    hints: [
      "Divisors come in pairs: if i divides num, so does num / i. How far do you need to look?",
      "Loop i from 2 while i * i <= num, adding both i and num / i when i divides num (once if they're equal). Start the sum at 1 and remember 1 itself is not perfect.",
      "if num <= 1: return false\nsum = 1\ni = 2\nwhile i * i <= num:\n  if num % i == 0:\n    sum += i\n    if i != num / i: sum += num / i\n  i += 1\nreturn sum == num",
    ],
    reference: `function checkPerfectNumber(num) { if (num <= 1) return false; let s = 1; for (let i = 2; i * i <= num; i++) if (num % i === 0) { s += i; if (i !== num / i) s += num / i; } return s === num; }`,
    brute: `function checkPerfectNumber(num) { return [6, 28, 496, 8128, 33550336].includes(num); }`,
    fuzz: gen(`return [__pick(rand, [6, 28, 496, 8128, __r(rand, 1, 10000)])];`),
    examples: [[28], [7]],
    edges: [
      ["single", [1], "1 has no proper divisors other than itself, so it isn't perfect."],
      ["boundary", [6]],
      ["large", [33550336], "A large perfect number: a loop up to num would be too slow at the real limits."],
    ],
  },
  {
    slug: "largest-odd-number-in-string",
    title: "Largest Odd Number in String",
    difficulty: "Easy",
    pattern: "Arrays & Hashing",
    leetcodeId: 1903,
    fn: "largestOddNumber",
    params: [["num", "string"]],
    returns: "string",
    hints: [
      "A number is odd exactly when its last digit is odd. Which substring keeps the most digits and still ends on an odd one?",
      "The best answer is always a prefix of num: scan from the right for the last odd digit and return everything up to it, or an empty string if there isn't one.",
      "for i from n - 1 down to 0:\n  if digit num[i] is odd:\n    return num[0..i]\nreturn empty string",
    ],
    reference: `function largestOddNumber(num) { for (let i = num.length - 1; i >= 0; i--) if (Number(num[i]) % 2 === 1) return num.slice(0, i + 1); return ""; }`,
    brute: `function largestOddNumber(num) { for (let len = num.length; len > 0; len--) { const p = num.slice(0, len); if ("13579".includes(p[p.length - 1])) return p; } return ""; }`,
    fuzz: gen(`return [String(__r(rand, 1, 9)) + __str(rand, __r(rand, 0, 10), "0123456789")];`),
    examples: [["52"], ["35427"]],
    edges: [
      ["no-answer", ["4206"], "No odd digit at all: return the empty string."],
      ["single", ["7"]],
      ["boundary", ["10000001"], "Only the very last digit is odd: the whole string is the answer."],
    ],
  },
  {
    slug: "check-if-array-is-sorted-and-rotated",
    title: "Check if Array Is Sorted and Rotated",
    difficulty: "Easy",
    pattern: "Arrays & Hashing",
    leetcodeId: 1752,
    fn: "check",
    params: [["nums", "number[]"]],
    returns: "boolean",
    hints: [
      "Walk around the array as a circle. In a sorted array rotated some amount, how many times can a value be smaller than the one before it?",
      "Count positions i where nums[i] > nums[(i + 1) % n]. A sorted, rotated array has at most one such drop.",
      "drops = 0\nfor i from 0 to n - 1:\n  if nums[i] > nums[(i + 1) mod n]:\n    drops += 1\nreturn drops <= 1",
    ],
    reference: `function check(nums) { let d = 0; for (let i = 0; i < nums.length; i++) if (nums[i] > nums[(i + 1) % nums.length]) d++; return d <= 1; }`,
    brute: `function check(nums) { for (let r = 0; r < nums.length; r++) { const a = nums.slice(r).concat(nums.slice(0, r)); if (a.every((v, i) => i === 0 || a[i - 1] <= v)) return true; } return false; }`,
    fuzz: gen(`const a = __sorted(rand, __r(rand, 1, 8), 1, 6); const r = __r(rand, 0, a.length - 1); const rot = a.slice(r).concat(a.slice(0, r)); if (rand() < 0.4) __shuffle(rand, rot); return [rot];`),
    examples: [[[3, 4, 5, 1, 2]], [[2, 1, 3, 4]]],
    edges: [
      ["single", [[1]]],
      ["all-equal", [[2, 2, 2]], "Equal neighbours aren't drops."],
      ["sorted", [[1, 2, 3]], "Rotation by zero still counts as sorted and rotated."],
    ],
  },
  {
    slug: "rearrange-array-elements-by-sign",
    title: "Rearrange Array Elements by Sign",
    difficulty: "Medium",
    pattern: "Two Pointers",
    leetcodeId: 2149,
    fn: "rearrangeArray",
    params: [["nums", "number[]"]],
    returns: "number[]",
    hints: [
      "In the answer, positives sit at even indexes and negatives at odd indexes, each in their original order.",
      "Make a result array and two write indexes: 0 for the next positive, 1 for the next negative. Scan nums once and drop each value at its side's index, then advance that index by 2.",
      "res = array of size n\npos = 0, neg = 1\nfor each x in nums:\n  if x > 0:\n    res[pos] = x; pos += 2\n  else:\n    res[neg] = x; neg += 2\nreturn res",
    ],
    reference: `function rearrangeArray(nums) { const res = new Array(nums.length); let p = 0, q = 1; for (const x of nums) { if (x > 0) { res[p] = x; p += 2; } else { res[q] = x; q += 2; } } return res; }`,
    brute: `function rearrangeArray(nums) { const pos = nums.filter((x) => x > 0), neg = nums.filter((x) => x < 0); return pos.flatMap((x, i) => [x, neg[i]]); }`,
    fuzz: gen(`const h = __r(rand, 1, 6); const a = __arr(rand, h, 1, 20).concat(__arr(rand, h, -20, -1)); return [__shuffle(rand, a)];`),
    examples: [[[3, 1, -2, -5, 2, -4]], [[-1, 1]]],
    edges: [
      ["two", [[1, -1]]],
      ["order", [[-3, -2, -1, 4, 5, 6]], "All negatives come first: keep each sign's original order."],
      ["duplicates", [[2, 2, -2, -2]]],
    ],
  },
  {
    slug: "pascals-triangle-ii",
    title: "Pascal's Triangle II",
    difficulty: "Easy",
    pattern: "1-D Dynamic Programming",
    leetcodeId: 119,
    fn: "getRow",
    params: [["rowIndex", "number"]],
    returns: "number[]",
    hints: [
      "Each row is built from the row above. Can you update one array in place to get from one row to the next?",
      "Start with [1]. For each new row, append 1 and update positions from right to left: row[j] += row[j - 1]. Going right to left keeps the old values you still need.",
      "row = [1]\nrepeat rowIndex times:\n  append 1 to row\n  for j from length - 2 down to 1:\n    row[j] = row[j] + row[j - 1]\nreturn row",
    ],
    reference: `function getRow(rowIndex) { const row = [1]; for (let i = 0; i < rowIndex; i++) { row.push(1); for (let j = row.length - 2; j > 0; j--) row[j] += row[j - 1]; } return row; }`,
    brute: `function getRow(rowIndex) { let prev = [1]; for (let i = 1; i <= rowIndex; i++) { const cur = [1]; for (let j = 1; j < i; j++) cur.push(prev[j - 1] + prev[j]); cur.push(1); prev = cur; } return prev; }`,
    fuzz: gen(`return [__r(rand, 0, 33)];`),
    examples: [[3], [5]],
    edges: [
      ["zeros", [0], "Row 0 is just [1]."],
      ["single", [1]],
      ["extremes", [33], "The largest row still fits in a safe integer."],
    ],
  },
  {
    slug: "kth-missing-positive-number",
    title: "Kth Missing Positive Number",
    difficulty: "Easy",
    pattern: "Binary Search",
    leetcodeId: 1539,
    fn: "findKthPositive",
    params: [["arr", "number[]"], ["k", "number"]],
    returns: "number",
    hints: [
      "At index i of the sorted array, how many positive numbers are missing before arr[i]?",
      "Missing before index i is arr[i] - (i + 1), which never decreases. Binary search for the first index where it reaches k; the answer is that index plus k.",
      "lo = 0, hi = n\nwhile lo < hi:\n  mid = (lo + hi) / 2 rounded down\n  if arr[mid] - (mid + 1) < k: lo = mid + 1\n  else: hi = mid\nreturn lo + k",
    ],
    reference: `function findKthPositive(arr, k) { let lo = 0, hi = arr.length; while (lo < hi) { const m = (lo + hi) >> 1; if (arr[m] - m - 1 < k) lo = m + 1; else hi = m; } return lo + k; }`,
    brute: `function findKthPositive(arr, k) { const s = new Set(arr); let x = 0; while (k > 0) { x++; if (!s.has(x)) k--; } return x; }`,
    fuzz: gen(`const s = new Set(); const n = __r(rand, 1, 10); while (s.size < n) s.add(__r(rand, 1, 25)); return [[...s].sort(function (a, b) { return a - b; }), __r(rand, 1, 12)];`),
    examples: [[[2, 3, 4, 7, 11], 5], [[1, 2, 3, 4], 2]],
    edges: [
      ["boundary", [[5, 6, 7], 3], "Every missing number needed comes before the first element."],
      ["single", [[1], 1]],
      ["large", [[1, 2, 3], 1000], "The answer is far past the end of the array."],
    ],
  },
  {
    slug: "count-good-numbers",
    title: "Count Good Numbers",
    difficulty: "Medium",
    pattern: "Math & Geometry",
    leetcodeId: 1922,
    fn: "countGoodNumbers",
    params: [["n", "number"]],
    returns: "number",
    hints: [
      "Even indexes have 5 choices (0, 2, 4, 6, 8) and odd indexes have 4 (2, 3, 5, 7). The answer is a product of powers, but n can be 10^15.",
      "Compute 5^ceil(n/2) * 4^floor(n/2) mod 1e9+7 with fast exponentiation. Products exceed 2^53, so use BigInt (or split the multiplication) to stay exact.",
      "MOD = 1000000007\npower(b, e):\n  result = 1\n  while e > 0:\n    if e is odd: result = result * b mod MOD\n    b = b * b mod MOD\n    e = e / 2 rounded down\n  return result\nreturn power(5, ceil(n / 2)) * power(4, floor(n / 2)) mod MOD",
    ],
    reference: `function countGoodNumbers(n) { const M = 1000000007n; const pw = (b, e) => { let r = 1n; b %= M; while (e > 0n) { if (e & 1n) r = (r * b) % M; b = (b * b) % M; e >>= 1n; } return r; }; const N = BigInt(n); return Number((pw(5n, (N + 1n) / 2n) * pw(4n, N / 2n)) % M); }`,
    brute: `function countGoodNumbers(n) { const M = 1000000007n; function pw(b, e) { if (e === 0n) return 1n; const h = pw(b, e / 2n); const sq = (h * h) % M; return e % 2n === 0n ? sq : (sq * b) % M; } const N = BigInt(n); return Number((pw(20n, N / 2n) * (N % 2n === 1n ? 5n : 1n)) % M); }`,
    fuzz: gen(`return [__pick(rand, [__r(rand, 1, 60), __r(rand, 1, 1000000), __r(rand, 1, 1000000000000)])];`),
    examples: [[1], [4]],
    edges: [
      ["two", [2]],
      ["large", [1e15], "Too large for a loop and for plain number multiplication."],
      ["boundary", [50], "The exact answer already exceeds 2^53 before the modulo."],
    ],
  },
  {
    slug: "divide-two-integers",
    title: "Divide Two Integers",
    difficulty: "Medium",
    pattern: "Bit Manipulation",
    leetcodeId: 29,
    fn: "divide",
    params: [["dividend", "number"], ["divisor", "number"]],
    returns: "number",
    hints: [
      "Repeated subtraction is too slow for 2^31 / 1. Can you subtract the divisor doubled many times at once?",
      "Work with absolute values. Repeatedly find the largest divisor * 2^k that fits, subtract it and add 2^k to the quotient. Apply the sign at the end and clamp to [-2^31, 2^31 - 1].",
      "if dividend == -2^31 and divisor == -1: return 2^31 - 1\nnegative = signs differ\na = |dividend|, b = |divisor|, q = 0\nwhile a >= b:\n  chunk = b, times = 1\n  while chunk + chunk <= a: chunk += chunk; times += times\n  a -= chunk; q += times\nreturn -q if negative else q",
    ],
    reference: `function divide(dividend, divisor) { if (dividend === -2147483648 && divisor === -1) return 2147483647; const neg = (dividend < 0) !== (divisor < 0); let a = Math.abs(dividend), b = Math.abs(divisor), q = 0; while (a >= b) { let c = b, t = 1; while (c + c <= a) { c += c; t += t; } a -= c; q += t; } return neg ? -q : q; }`,
    brute: `function divide(dividend, divisor) { const q = Math.trunc(dividend / divisor); return Math.max(-2147483648, Math.min(2147483647, q)) || 0; }`,
    fuzz: gen(`const b = __pick(rand, [__r(rand, -20, -1), __r(rand, 1, 20), __r(rand, 1, 100000)]); return [__r(rand, -2147483648, 2147483647), b];`),
    examples: [[10, 3], [7, -3]],
    edges: [
      ["extremes", [-2147483648, -1], "The true answer 2^31 overflows: clamp to 2^31 - 1."],
      ["zeros", [0, 5]],
      ["boundary", [-2147483648, 1]],
      ["negatives", [-7, -2], "Both negative: the quotient is positive and rounds toward zero."],
    ],
  },
  {
    slug: "sum-of-subarray-ranges",
    title: "Sum of Subarray Ranges",
    difficulty: "Medium",
    pattern: "Stack & Monotonic Stack",
    leetcodeId: 2104,
    fn: "subArrayRanges",
    params: [["nums", "number[]"]],
    returns: "number",
    hints: [
      "The sum of (max - min) over all subarrays is (sum of maxes) - (sum of mins). Can you count how many subarrays each element is the maximum of?",
      "For each index, find how far it extends left and right as the maximum using a monotonic stack (strict on one side, non-strict on the other to avoid double counting). Its contribution is value * left * right. Do the same for minimums and subtract.",
      "contribution(better):\n  total = 0, stack = empty\n  for i from 0 to n (n acts as a sentinel):\n    while stack not empty and (i == n or better(nums[i], nums[top])):\n      j = pop; left = j - (new top or -1); right = i - j\n      total += nums[j] * left * right\n    push i\n  return total\nreturn contribution(greater) - contribution(smaller)",
    ],
    reference: `function subArrayRanges(nums) { const n = nums.length; const run = (better) => { let t = 0; const st = []; for (let i = 0; i <= n; i++) { while (st.length && (i === n || better(nums[i], nums[st[st.length - 1]]))) { const j = st.pop(); const l = j - (st.length ? st[st.length - 1] : -1); t += nums[j] * l * (i - j); } st.push(i); } return t; }; return run((a, b) => a > b) - run((a, b) => a < b); }`,
    brute: `function subArrayRanges(nums) { let s = 0; for (let i = 0; i < nums.length; i++) { let mx = nums[i], mn = nums[i]; for (let j = i; j < nums.length; j++) { mx = Math.max(mx, nums[j]); mn = Math.min(mn, nums[j]); s += mx - mn; } } return s; }`,
    fuzz: arrayGen(1, 14, -10, 10),
    examples: [[[1, 2, 3]], [[4, -2, -3, 4, 1]]],
    edges: [
      ["single", [[5]], "One subarray with range 0."],
      ["all-equal", [[3, 3, 3]], "Equal values must not be counted twice as max or min."],
      ["reverse-sorted", [[5, 4, 3, 2, 1]]],
    ],
  },
  {
    slug: "shortest-palindrome",
    title: "Shortest Palindrome",
    difficulty: "Hard",
    pattern: "Two Pointers",
    leetcodeId: 214,
    fn: "shortestPalindrome",
    params: [["s", "string"]],
    returns: "string",
    hints: [
      "You can only add characters in front. The part of s you keep untouched is its longest palindromic prefix.",
      "Find the longest palindromic prefix in linear time with the KMP failure function of s + '#' + reverse(s). Prepend the reverse of the remaining suffix.",
      "t = s + '#' + reverse(s)\nlps = KMP failure table of t\nkeep = lps[last index of t]\nreturn reverse(s[keep..]) + s",
    ],
    reference: `function shortestPalindrome(s) { const r = s.split("").reverse().join(""); const t = s + "#" + r; const lps = new Array(t.length).fill(0); for (let i = 1; i < t.length; i++) { let j = lps[i - 1]; while (j > 0 && t[i] !== t[j]) j = lps[j - 1]; if (t[i] === t[j]) j++; lps[i] = j; } const keep = lps[t.length - 1]; return s.slice(keep).split("").reverse().join("") + s; }`,
    brute: `function shortestPalindrome(s) { const pal = (x) => x === x.split("").reverse().join(""); for (let k = s.length; k >= 0; k--) if (pal(s.slice(0, k))) return s.slice(k).split("").reverse().join("") + s; return s; }`,
    fuzz: gen(`return [__str(rand, __r(rand, 0, 10), "abc")];`),
    examples: [["aacecaaa"], ["abcd"]],
    edges: [
      ["empty", [""]],
      ["single-char", ["a"]],
      ["all-equal", ["aaaa"], "Already a palindrome: add nothing."],
    ],
  },
  {
    slug: "longest-happy-prefix",
    title: "Longest Happy Prefix",
    difficulty: "Hard",
    pattern: "Two Pointers",
    leetcodeId: 1392,
    fn: "longestPrefix",
    params: [["s", "string"]],
    returns: "string",
    hints: [
      "You want the longest proper prefix that is also a suffix. That's exactly what the KMP prefix function stores.",
      "Build lps where lps[i] is the length of the longest proper prefix of s[0..i] that is also its suffix. The answer is s[0..lps[n - 1]].",
      "lps = array of n zeros\nj = 0\nfor i from 1 to n - 1:\n  while j > 0 and s[i] != s[j]: j = lps[j - 1]\n  if s[i] == s[j]: j += 1\n  lps[i] = j\nreturn s[0 .. lps[n - 1]]",
    ],
    reference: `function longestPrefix(s) { const lps = new Array(s.length).fill(0); let j = 0; for (let i = 1; i < s.length; i++) { while (j > 0 && s[i] !== s[j]) j = lps[j - 1]; if (s[i] === s[j]) j++; lps[i] = j; } return s.slice(0, lps[s.length - 1]); }`,
    brute: `function longestPrefix(s) { for (let k = s.length - 1; k > 0; k--) if (s.slice(0, k) === s.slice(s.length - k)) return s.slice(0, k); return ""; }`,
    fuzz: gen(`return [__str(rand, __r(rand, 1, 12), "ab")];`),
    examples: [["level"], ["ababab"]],
    edges: [
      ["single-char", ["a"], "A proper prefix can't be the whole string: the answer is empty."],
      ["no-answer", ["abc"]],
      ["all-equal", ["aaaa"]],
    ],
  },
];

export const A2Z_LEETCODE = DEFS.map(define);
