import { define, type ProblemDef } from "./define";
import { gen } from "./gen";

const POPCOUNT = `let c = 0; while (x) { x &= x - 1; c++; } return c;`;

const DEFS: ProblemDef[] = [
  {
    slug: "number-complement",
    title: "Number Complement",
    difficulty: "Easy",
    pattern: "Bit Manipulation",
    leetcodeId: 476,
    fn: "findComplement",
    params: [["num", "number"]],
    returns: "number",
    hints: [
      "Only the bits up to num's highest set bit flip; leading zeros stay zero.",
      "Build a mask of all 1s as wide as num (the smallest 2^k - 1 that is >= num) and return mask - num, which equals mask ^ num.",
      "mask = 1\nwhile mask <= num: mask = mask * 2\nreturn mask - 1 - num",
    ],
    reference: `function findComplement(num) { let m = 1; while (m <= num) m *= 2; return m - 1 - num; }`,
    brute: `function findComplement(num) { return parseInt(num.toString(2).split("").map((c) => (c === "1" ? "0" : "1")).join(""), 2); }`,
    fuzz: gen(`return [__r(rand, 1, rand() < 0.5 ? 1000 : 2147483647)];`),
    examples: [[5], [1]],
    edges: [
      ["boundary", [8], "A power of two: every lower bit turns on."],
      ["extremes", [2147483647], "All 31 bits set: the complement is 0."],
      ["large", [1000000000]],
    ],
  },
  {
    slug: "binary-number-with-alternating-bits",
    title: "Binary Number with Alternating Bits",
    difficulty: "Easy",
    pattern: "Bit Manipulation",
    leetcodeId: 693,
    fn: "hasAlternatingBits",
    params: [["n", "number"]],
    returns: "boolean",
    hints: [
      "If the bits alternate, n and n >> 1 differ in every position up to the top bit.",
      "x = n ^ (n >> 1) is then all 1s, and a number of all 1s satisfies x & (x + 1) == 0.",
      "x = n XOR (n >> 1)\nreturn (x AND (x + 1)) == 0",
    ],
    reference: `function hasAlternatingBits(n) { const x = n ^ (n >> 1); return (x & (x + 1)) === 0; }`,
    brute: `function hasAlternatingBits(n) { const s = n.toString(2); for (let i = 1; i < s.length; i++) if (s[i] === s[i - 1]) return false; return true; }`,
    fuzz: gen(`if (rand() < 0.5) { const len = __r(rand, 1, 31); let v = 0; for (let i = 0; i < len; i++) v = v * 2 + (i % 2 === 0 ? 1 : 0); return [v]; } return [__r(rand, 1, 1000000)];`),
    examples: [[5], [7], [11]],
    edges: [
      ["min-size", [1]],
      ["boundary", [2]],
      ["extremes", [1431655765], "0x55555555: 31 alternating bits."],
    ],
  },
  {
    slug: "xor-operation-in-an-array",
    title: "XOR Operation in an Array",
    difficulty: "Easy",
    pattern: "Bit Manipulation",
    leetcodeId: 1486,
    fn: "xorOperation",
    params: [["n", "number"], ["start", "number"]],
    returns: "number",
    hints: [
      "The array is start, start + 2, start + 4, ... You don't need to store it.",
      "Loop i from 0 to n - 1 and XOR start + 2 * i into the answer.",
      "x = 0\nfor i in 0 .. n - 1:\n  x = x XOR (start + 2 * i)\nreturn x",
    ],
    reference: `function xorOperation(n, start) { let x = 0; for (let i = 0; i < n; i++) x ^= start + 2 * i; return x; }`,
    brute: `function xorOperation(n, start) { return Array.from({ length: n }, (_, i) => start + 2 * i).reduce((a, b) => a ^ b, 0); }`,
    fuzz: gen(`return [__r(rand, 1, 1000), __r(rand, 0, 1000)];`),
    examples: [[5, 0], [4, 3]],
    edges: [
      ["min-size", [1, 7]],
      ["zeros", [3, 0]],
      ["large", [1000, 1000]],
    ],
  },
  {
    slug: "decode-xored-array",
    title: "Decode XORed Array",
    difficulty: "Easy",
    pattern: "Bit Manipulation",
    leetcodeId: 1720,
    fn: "decode",
    params: [["encoded", "number[]"], ["first", "number"]],
    returns: "number[]",
    hints: [
      "encoded[i] = arr[i] ^ arr[i + 1]. XOR both sides with arr[i].",
      "arr[i + 1] = encoded[i] ^ arr[i]. Start from first and walk forward.",
      "arr = [first]\nfor e in encoded:\n  append (last of arr) XOR e to arr\nreturn arr",
    ],
    reference: `function decode(encoded, first) { const a = [first]; for (const e of encoded) a.push(a[a.length - 1] ^ e); return a; }`,
    brute: `function decode(encoded, first) { const a = [first]; for (let i = 0; i < encoded.length; i++) { let x = first; for (let j = 0; j <= i; j++) x ^= encoded[j]; a.push(x); } return a; }`,
    fuzz: gen(`const arr = __arr(rand, __r(rand, 2, 12), 0, 100000); return [arr.slice(1).map((v, i) => v ^ arr[i]), arr[0]];`),
    examples: [[[1, 2, 3], 1], [[6, 2, 7, 3], 4]],
    edges: [
      ["zeros", [[0, 0], 0]],
      ["single", [[5], 3]],
      ["extremes", [[100000, 100000], 100000]],
    ],
  },
  {
    slug: "find-the-original-array-of-prefix-xor",
    title: "Find The Original Array of Prefix Xor",
    difficulty: "Medium",
    pattern: "Bit Manipulation",
    leetcodeId: 2433,
    fn: "findArray",
    params: [["pref", "number[]"]],
    returns: "number[]",
    hints: [
      "pref[i] = pref[i - 1] ^ arr[i]. Solve for arr[i].",
      "arr[0] = pref[0] and arr[i] = pref[i] ^ pref[i - 1].",
      "arr[0] = pref[0]\nfor i in 1 .. n - 1:\n  arr[i] = pref[i] XOR pref[i - 1]\nreturn arr",
    ],
    reference: `function findArray(pref) { return pref.map((v, i) => (i ? v ^ pref[i - 1] : v)); }`,
    brute: `function findArray(pref) { const a = []; let x = 0; for (const p of pref) { a.push(p ^ x); x ^= a[a.length - 1]; } return a; }`,
    fuzz: gen(`return [__arr(rand, __r(rand, 1, 12), 0, 1000000)];`),
    examples: [[[5, 2, 0, 3, 1]], [[13]]],
    edges: [
      ["zeros", [[0, 0, 0]]],
      ["all-equal", [[7, 7, 7]]],
      ["extremes", [[1000000, 0, 1000000]]],
    ],
  },
  {
    slug: "count-triplets-that-can-form-two-arrays-of-equal-xor",
    title: "Count Triplets That Can Form Two Arrays of Equal XOR",
    difficulty: "Medium",
    pattern: "Bit Manipulation",
    leetcodeId: 1442,
    fn: "countTriplets",
    params: [["arr", "number[]"]],
    returns: "number",
    hints: [
      "a == b means a ^ b == 0, i.e. the XOR of arr[i..k] is 0. Then every j in (i, k] works.",
      "For each pair i < k whose range XOR is 0 (use prefix XORs or a running XOR), add k - i.",
      "count = 0\nfor i in 0 .. n - 1:\n  x = arr[i]\n  for k in i + 1 .. n - 1:\n    x = x XOR arr[k]\n    if x == 0: count = count + (k - i)\nreturn count",
    ],
    reference: `function countTriplets(arr) { let c = 0; for (let i = 0; i < arr.length; i++) { let x = arr[i]; for (let k = i + 1; k < arr.length; k++) { x ^= arr[k]; if (x === 0) c += k - i; } } return c; }`,
    brute: `function countTriplets(arr) { const n = arr.length; let c = 0; for (let i = 0; i < n; i++) for (let j = i + 1; j < n; j++) for (let k = j; k < n; k++) { let a = 0, b = 0; for (let t = i; t < j; t++) a ^= arr[t]; for (let t = j; t <= k; t++) b ^= arr[t]; if (a === b) c++; } return c; }`,
    fuzz: gen(`return [__arr(rand, __r(rand, 1, 12), 1, 8)];`),
    examples: [[[2, 3, 1, 6, 7]], [[1, 1, 1, 1, 1]]],
    edges: [
      ["single", [[5]]],
      ["two", [[3, 3]]],
      ["boundary", [[1, 2, 3]], "1 ^ 2 ^ 3 = 0: both split points work."],
    ],
  },
  {
    slug: "total-hamming-distance",
    title: "Total Hamming Distance",
    difficulty: "Medium",
    pattern: "Bit Manipulation",
    leetcodeId: 477,
    fn: "totalHammingDistance",
    params: [["nums", "number[]"]],
    returns: "number",
    hints: [
      "Comparing all pairs is O(n^2). Count one bit position at a time instead.",
      "If c numbers have bit b set and n - c don't, that bit contributes c * (n - c) to the total.",
      "total = 0\nfor b in 0 .. 30:\n  c = count of x in nums with bit b set\n  total = total + c * (n - c)\nreturn total",
    ],
    reference: `function totalHammingDistance(nums) { let t = 0; for (let b = 0; b < 31; b++) { let c = 0; for (const x of nums) c += (x >> b) & 1; t += c * (nums.length - c); } return t; }`,
    brute: `function totalHammingDistance(nums) { const pc = (x) => { ${POPCOUNT} }; let t = 0; for (let i = 0; i < nums.length; i++) for (let j = i + 1; j < nums.length; j++) t += pc(nums[i] ^ nums[j]); return t; }`,
    fuzz: gen(`return [__arr(rand, __r(rand, 1, 15), 0, 1000000000)];`),
    examples: [[[4, 14, 2]], [[4, 14, 4]]],
    edges: [
      ["single", [[0]]],
      ["all-equal", [[9, 9, 9]]],
      ["large", [Array.from({ length: 600 }, (_, i) => (i * 7919) % 65536)]],
    ],
  },
  {
    slug: "maximum-product-of-word-lengths",
    title: "Maximum Product of Word Lengths",
    difficulty: "Medium",
    pattern: "Bit Manipulation",
    leetcodeId: 318,
    fn: "maxProduct",
    params: [["words", "string[]"]],
    returns: "number",
    hints: [
      "Two words share no letters when their sets of letters don't intersect. A 26-bit mask per word turns that into one AND.",
      "Build mask[i] with bit (c - 'a') set for each letter. For each pair with mask[i] & mask[j] == 0, take the product of lengths.",
      "for each word i: mask[i] = OR of (1 << letter) over its letters\nbest = 0\nfor i < j:\n  if mask[i] AND mask[j] == 0:\n    best = max(best, len(words[i]) * len(words[j]))\nreturn best",
    ],
    reference: `function maxProduct(words) { const m = words.map((w) => { let x = 0; for (const c of w) x |= 1 << (c.charCodeAt(0) - 97); return x; }); let best = 0; for (let i = 0; i < words.length; i++) for (let j = i + 1; j < words.length; j++) if (!(m[i] & m[j])) best = Math.max(best, words[i].length * words[j].length); return best; }`,
    brute: `function maxProduct(words) { let best = 0; for (let i = 0; i < words.length; i++) for (let j = i + 1; j < words.length; j++) { const s = new Set(words[i]); if (![...words[j]].some((c) => s.has(c))) best = Math.max(best, words[i].length * words[j].length); } return best; }`,
    fuzz: gen(`return [Array.from({ length: __r(rand, 2, 10) }, () => __str(rand, __r(rand, 1, 6), "abcdefgh"))];`),
    examples: [[["abcw", "baz", "foo", "bar", "xtfn", "abcdef"]], [["a", "ab", "abc", "d", "cd", "bcd", "abcd"]], [["a", "aa", "aaa", "aaaa"]]],
    edges: [
      ["two", [["ab", "cd"]]],
      ["duplicates", [["ab", "ab", "c"]]],
      ["no-answer", [["abc", "cab", "bca"]], "Every pair shares a letter: 0."],
    ],
  },
  {
    slug: "largest-combination-with-bitwise-and-greater-than-zero",
    title: "Largest Combination With Bitwise AND Greater Than Zero",
    difficulty: "Medium",
    pattern: "Bit Manipulation",
    leetcodeId: 2275,
    fn: "largestCombination",
    params: [["candidates", "number[]"]],
    returns: "number",
    hints: [
      "An AND is non-zero exactly when some single bit is set in every chosen number.",
      "For each bit position, count how many candidates have it. The best combination takes all of them for the most common bit.",
      "best = 0\nfor b in 0 .. 30:\n  best = max(best, count of x in candidates with bit b set)\nreturn best",
    ],
    reference: `function largestCombination(candidates) { let best = 0; for (let b = 0; b < 31; b++) { let c = 0; for (const x of candidates) c += (x >> b) & 1; best = Math.max(best, c); } return best; }`,
    brute: `function largestCombination(candidates) { const n = candidates.length; let best = 0; for (let m = 1; m < 1 << n; m++) { let and = -1, size = 0; for (let i = 0; i < n; i++) if (m & (1 << i)) { and &= candidates[i]; size++; } if (and > 0) best = Math.max(best, size); } return best; }`,
    fuzz: gen(`return [__arr(rand, __r(rand, 1, 12), 1, 100)];`),
    examples: [[[16, 17, 71, 62, 12, 24, 14]], [[8, 8]]],
    edges: [
      ["single", [[1]]],
      ["sorted", [[1, 2, 4, 8]], "No bit is shared: the best is one number."],
      ["extremes", [[10000000, 10000000, 1]]],
    ],
  },
  {
    slug: "minimize-xor",
    title: "Minimize XOR",
    difficulty: "Medium",
    pattern: "Bit Manipulation",
    leetcodeId: 2429,
    fn: "minimizeXor",
    params: [["num1", "number"], ["num2", "number"]],
    returns: "number",
    hints: [
      "x must have as many set bits as num2. To make x ^ num1 small, x should copy num1's set bits, highest first.",
      "Let c = popcount(num2). Take num1's set bits from the top while c > 0. If bits remain, fill num1's unset bits from the bottom.",
      "c = set bits in num2, x = 0\nfor b from 30 down to 0:\n  if c > 0 and bit b of num1 is 1: set bit b of x, c = c - 1\nfor b from 0 up to 30:\n  if c > 0 and bit b of x is 0: set bit b of x, c = c - 1\nreturn x",
    ],
    reference: `function minimizeXor(num1, num2) { let x = num2, c = 0; while (x) { x &= x - 1; c++; } let r = 0; for (let b = 30; b >= 0 && c; b--) if ((num1 >> b) & 1) { r |= 1 << b; c--; } for (let b = 0; b <= 30 && c; b++) if (!((r >> b) & 1)) { r |= 1 << b; c--; } return r; }`,
    brute: `function minimizeXor(num1, num2) { const pc = (v) => v.toString(2).split("1").length - 1; const c = pc(num2), width = Math.max(num1.toString(2).length, c) + 1; let best = -1; for (let x = 0; x < 2 ** width; x++) if (pc(x) === c && (best < 0 || (x ^ num1) < (best ^ num1))) best = x; return best; }`,
    fuzz: gen(`return [__r(rand, 1, 5000), __r(rand, 1, 5000)];`),
    examples: [[3, 5], [1, 12]],
    edges: [
      ["all-equal", [7, 7]],
      ["boundary", [8, 15], "num1 has fewer bits than needed: fill from the bottom."],
      ["large", [65535, 1], "Only one bit allowed: keep num1's highest."],
    ],
  },
  {
    slug: "bitwise-xor-of-all-pairings",
    title: "Bitwise XOR of All Pairings",
    difficulty: "Medium",
    pattern: "Bit Manipulation",
    leetcodeId: 2425,
    fn: "xorAllNums",
    params: [["nums1", "number[]"], ["nums2", "number[]"]],
    returns: "number",
    hints: [
      "Each nums1[i] appears in len(nums2) pairs. XORing a value an even number of times cancels it.",
      "If len(nums2) is odd, nums1's XOR survives; if len(nums1) is odd, nums2's XOR survives. Combine them.",
      "x = 0\nif len(nums2) is odd: x = x XOR (XOR of nums1)\nif len(nums1) is odd: x = x XOR (XOR of nums2)\nreturn x",
    ],
    reference: `function xorAllNums(nums1, nums2) { let x = 0; if (nums2.length % 2) for (const v of nums1) x ^= v; if (nums1.length % 2) for (const v of nums2) x ^= v; return x; }`,
    brute: `function xorAllNums(nums1, nums2) { let x = 0; for (const a of nums1) for (const b of nums2) x ^= a ^ b; return x; }`,
    fuzz: gen(`return [__arr(rand, __r(rand, 1, 10), 0, 1000), __arr(rand, __r(rand, 1, 10), 0, 1000)];`),
    examples: [[[2, 1, 3], [10, 2, 5, 0]], [[1, 2], [3, 4]]],
    edges: [
      ["single", [[5], [7]]],
      ["all-equal", [[4, 4], [4, 4, 4]]],
      ["boundary", [[1, 2, 3], [4]]],
    ],
  },
  {
    slug: "utf-8-validation",
    title: "UTF-8 Validation",
    difficulty: "Medium",
    pattern: "Bit Manipulation",
    leetcodeId: 393,
    fn: "validUtf8",
    params: [["data", "number[]"]],
    returns: "boolean",
    hints: [
      "The leading byte's high bits say how long the character is: 0xxxxxxx is 1 byte, 110xxxxx is 2, 1110xxxx is 3, 11110xxx is 4. Continuation bytes are 10xxxxxx.",
      "Walk the bytes keeping a count of continuation bytes still owed. A leading 10 with nothing owed, or a non-10 byte while something is owed, is invalid.",
      "need = 0\nfor b in data:\n  if need == 0:\n    if b >> 7 == 0: continue\n    else if b >> 5 == 6: need = 1\n    else if b >> 4 == 14: need = 2\n    else if b >> 3 == 30: need = 3\n    else: return false\n  else if b >> 6 == 2: need = need - 1\n  else: return false\nreturn need == 0",
    ],
    reference: `function validUtf8(data) { let need = 0; for (const b of data) { if (need === 0) { if (b >> 7 === 0) continue; if (b >> 5 === 6) need = 1; else if (b >> 4 === 14) need = 2; else if (b >> 3 === 30) need = 3; else return false; } else if (b >> 6 === 2) need--; else return false; } return need === 0; }`,
    brute: `function validUtf8(data) { const bits = data.map((b) => (b & 255).toString(2).padStart(8, "0")); let i = 0; while (i < bits.length) { const lead = bits[i]; const len = lead.startsWith("0") ? 1 : lead.startsWith("110") ? 2 : lead.startsWith("1110") ? 3 : lead.startsWith("11110") ? 4 : 0; if (!len || i + len > bits.length) return false; for (let j = 1; j < len; j++) if (!bits[i + j].startsWith("10")) return false; i += len; } return true; }`,
    fuzz: gen(`const out = []; const chars = __r(rand, 1, 5); for (let c = 0; c < chars; c++) { const len = __r(rand, 1, 4); out.push(len === 1 ? __r(rand, 0, 127) : len === 2 ? __r(rand, 192, 223) : len === 3 ? __r(rand, 224, 239) : __r(rand, 240, 247)); for (let j = 1; j < len; j++) out.push(__r(rand, 128, 191)); } if (rand() < 0.5) out[__r(rand, 0, out.length - 1)] = __r(rand, 0, 255); return [out];`),
    examples: [[[197, 130, 1]], [[235, 140, 4]]],
    edges: [
      ["single", [[145]], "A continuation byte with no leading byte."],
      ["extremes", [[255]], "11111111 is never a valid leading byte."],
      ["boundary", [[240, 162, 138, 147]], "A full 4-byte character."],
    ],
  },
  {
    slug: "maximum-xor-for-each-query",
    title: "Maximum XOR for Each Query",
    difficulty: "Medium",
    pattern: "Bit Manipulation",
    leetcodeId: 1829,
    fn: "getMaximumXor",
    params: [["nums", "number[]"], ["maximumBit", "number"]],
    returns: "number[]",
    hints: [
      "With x the XOR of the current array, the best k flips every bit of x within maximumBit bits.",
      "k = x ^ (2^maximumBit - 1). Keep a running XOR, answer, then XOR out the last element for the next query.",
      "x = XOR of nums, mask = 2^maximumBit - 1, out = []\nfor i from n - 1 down to 0:\n  append x XOR mask to out\n  x = x XOR nums[i]\nreturn out",
    ],
    reference: `function getMaximumXor(nums, maximumBit) { let x = 0; for (const v of nums) x ^= v; const mask = 2 ** maximumBit - 1, out = []; for (let i = nums.length - 1; i >= 0; i--) { out.push(x ^ mask); x ^= nums[i]; } return out; }`,
    brute: `function getMaximumXor(nums, maximumBit) { const out = []; for (let len = nums.length; len >= 1; len--) { let x = 0; for (let i = 0; i < len; i++) x ^= nums[i]; let best = 0, bk = 0; for (let k = 0; k < 2 ** maximumBit; k++) if ((x ^ k) > best) { best = x ^ k; bk = k; } out.push(bk); } return out; }`,
    fuzz: gen(`const mb = __r(rand, 1, 6); return [__sorted(rand, __r(rand, 1, 10), 0, 2 ** mb - 1), mb];`),
    examples: [[[0, 1, 1, 3], 2], [[2, 3, 4, 7], 3]],
    edges: [
      ["single", [[0], 1]],
      ["all-equal", [[5, 5], 3]],
      ["extremes", [[1048575], 20]],
    ],
  },
  {
    slug: "smallest-subarrays-with-maximum-bitwise-or",
    title: "Smallest Subarrays With Maximum Bitwise OR",
    difficulty: "Medium",
    pattern: "Bit Manipulation",
    leetcodeId: 2411,
    fn: "smallestSubarrays",
    params: [["nums", "number[]"]],
    returns: "number[]",
    hints: [
      "The best OR starting at i is the OR of the whole suffix. You need to reach, for every bit in it, the nearest index at or after i that has that bit.",
      "Scan from the right, keeping last[b] = the nearest index with bit b. For each i, the answer is max(last[b]) - i + 1 over known bits (at least 1).",
      "last[b] = -1 for every bit\nfor i from n - 1 down to 0:\n  for each bit b set in nums[i]: last[b] = i\n  far = i\n  for each bit b with last[b] != -1: far = max(far, last[b])\n  ans[i] = far - i + 1\nreturn ans",
    ],
    reference: `function smallestSubarrays(nums) { const last = new Array(31).fill(-1), ans = []; for (let i = nums.length - 1; i >= 0; i--) { for (let b = 0; b < 31; b++) if ((nums[i] >> b) & 1) last[b] = i; let far = i; for (let b = 0; b < 31; b++) if (last[b] > far) far = last[b]; ans[i] = far - i + 1; } return ans; }`,
    brute: `function smallestSubarrays(nums) { const n = nums.length; return nums.map((_, i) => { let full = 0; for (let j = i; j < n; j++) full |= nums[j]; let x = 0; for (let j = i; j < n; j++) { x |= nums[j]; if (x === full) return j - i + 1; } return 1; }); }`,
    fuzz: gen(`return [__arr(rand, __r(rand, 1, 12), 0, 64)];`),
    examples: [[[1, 0, 2, 1, 3]], [[1, 2]]],
    edges: [
      ["zeros", [[0, 0, 0]], "OR stays 0: one element is enough."],
      ["single", [[5]]],
      ["boundary", [[1, 2, 4, 8]], "Every bit lives in a different element."],
    ],
  },
  {
    slug: "shortest-subarray-with-or-at-least-k-ii",
    title: "Shortest Subarray With OR at Least K II",
    difficulty: "Medium",
    pattern: "Bit Manipulation",
    leetcodeId: 3097,
    fn: "minimumSubarrayLength",
    params: [["nums", "number[]"], ["k", "number"]],
    returns: "number",
    hints: [
      "OR only grows as a window widens, so a sliding window works, but you can't 'un-OR' a value directly.",
      "Keep a count of how many window elements have each bit. Removing nums[left] decrements its bits; a bit is in the OR while its count is positive.",
      "cnt[b] = 0 for every bit, left = 0, best = infinity\nfor right in 0 .. n - 1:\n  add the bits of nums[right] to cnt\n  while left <= right and OR(cnt) >= k:\n    best = min(best, right - left + 1)\n    remove the bits of nums[left] from cnt, left = left + 1\nreturn -1 if best is infinity else best",
    ],
    reference: `function minimumSubarrayLength(nums, k) { const cnt = new Array(31).fill(0); const or = () => { let v = 0; for (let b = 0; b < 31; b++) if (cnt[b]) v |= 1 << b; return v; }; let l = 0, best = Infinity; for (let r = 0; r < nums.length; r++) { for (let b = 0; b < 31; b++) if ((nums[r] >> b) & 1) cnt[b]++; while (l <= r && or() >= k) { best = Math.min(best, r - l + 1); for (let b = 0; b < 31; b++) if ((nums[l] >> b) & 1) cnt[b]--; l++; } } return best === Infinity ? -1 : best; }`,
    brute: `function minimumSubarrayLength(nums, k) { let best = -1; for (let i = 0; i < nums.length; i++) { let x = 0; for (let j = i; j < nums.length; j++) { x |= nums[j]; if (x >= k) { if (best < 0 || j - i + 1 < best) best = j - i + 1; break; } } } return best; }`,
    fuzz: gen(`return [__arr(rand, __r(rand, 1, 12), 0, 64), __r(rand, 1, 100)];`),
    examples: [[[1, 2, 3], 2], [[2, 1, 8], 10], [[1, 2], 0]],
    edges: [
      ["no-answer", [[1, 2], 8], "Even the whole array's OR is too small."],
      ["single", [[5], 5]],
      ["zeros", [[0, 0], 0], "k = 0: any single element is enough."],
    ],
  },
  {
    slug: "concatenation-of-consecutive-binary-numbers",
    title: "Concatenation of Consecutive Binary Numbers",
    difficulty: "Medium",
    pattern: "Bit Manipulation",
    leetcodeId: 1680,
    fn: "concatenatedBinary",
    params: [["n", "number"]],
    returns: "number",
    hints: [
      "Appending i's binary digits to x is x * 2^len(i) + i. Take the modulus after every step.",
      "The bit length grows by one exactly when i is a power of two (i & (i - 1) == 0).",
      "MOD = 1e9 + 7, x = 0, len = 0\nfor i in 1 .. n:\n  if i AND (i - 1) == 0: len = len + 1\n  x = (x * 2^len + i) mod MOD\nreturn x",
    ],
    reference: `function concatenatedBinary(n) { const MOD = 1000000007; let x = 0, len = 0; for (let i = 1; i <= n; i++) { if ((i & (i - 1)) === 0) len++; x = (x * 2 ** len + i) % MOD; } return x; }`,
    brute: `function concatenatedBinary(n) { const MOD = 1000000007; let x = 0; for (let i = 1; i <= n; i++) for (const c of i.toString(2)) x = (x * 2 + (c === "1" ? 1 : 0)) % MOD; return x; }`,
    fuzz: gen(`return [__r(rand, 1, 3000)];`),
    examples: [[1], [3], [12]],
    edges: [
      ["two", [2]],
      ["boundary", [4], "4 adds a new bit length: 11011100."],
      ["large", [100000]],
    ],
  },
  {
    slug: "minimum-one-bit-operations-to-make-integers-zero",
    title: "Minimum One Bit Operations to Make Integers Zero",
    difficulty: "Hard",
    pattern: "Bit Manipulation",
    leetcodeId: 1611,
    fn: "minimumOneBitOperations",
    params: [["n", "number"]],
    returns: "number",
    hints: [
      "Clearing just the top bit 2^k takes 2^(k+1) - 1 steps. The allowed moves are exactly the steps of a Gray code.",
      "f(n) = (2^(k+1) - 1) - f(n without its top bit), where 2^k is n's top bit. Equivalently the answer is the inverse Gray code: n ^ (n >> 1) ^ (n >> 2) ^ ...",
      "ans = 0\nwhile n > 0:\n  ans = ans XOR n\n  n = n >> 1\nreturn ans",
    ],
    reference: `function minimumOneBitOperations(n) { let r = 0; while (n) { r ^= n; n >>= 1; } return r; }`,
    brute: `function minimumOneBitOperations(n) { if (n === 0) return 0; let k = 0; while (2 ** (k + 1) <= n) k++; return 2 ** (k + 1) - 1 - minimumOneBitOperations(n - 2 ** k); }`,
    fuzz: gen(`return [__r(rand, 1, rand() < 0.5 ? 64 : 1000000000)];`),
    examples: [[3], [6]],
    edges: [
      ["zeros", [0]],
      ["min-size", [1]],
      ["extremes", [1000000000]],
    ],
  },
];

export const LADDER_BITS = DEFS.map(define);
