import { define, type ProblemDef } from "./define";
import { gen, treeGen } from "./gen";

const T = "TreeNode | null";
const INSERT = `const __ins = (n, v) => { if (!n) return new TreeNode(v); if (v <= n.val) n.left = __ins(n.left, v); else n.right = __ins(n.right, v); return n; };`;

const DEFS: ProblemDef[] = [
  {
    slug: "range-sum-of-bst",
    title: "Range Sum of BST",
    difficulty: "Easy",
    pattern: "Trees",
    leetcodeId: 938,
    fn: "rangeSumBST",
    params: [["root", T], ["low", "number"], ["high", "number"]],
    returns: "number",
    argTypes: ["TreeNode", "value", "value"],
    hints: [
      "Summing every node in range works, but the BST order tells you when a whole subtree is out of range.",
      "If a node is below low, only its right subtree can contribute; if above high, only its left. Otherwise count it and go both ways.",
      "sum(node):\n  if node is empty: return 0\n  if node.val < low: return sum(node.right)\n  if node.val > high: return sum(node.left)\n  return node.val + sum(node.left) + sum(node.right)\nreturn sum(root)",
    ],
    reference: `function rangeSumBST(root, low, high) { if (!root) return 0; if (root.val < low) return rangeSumBST(root.right, low, high); if (root.val > high) return rangeSumBST(root.left, low, high); return root.val + rangeSumBST(root.left, low, high) + rangeSumBST(root.right, low, high); }`,
    brute: `function rangeSumBST(root, low, high) { let s = 0; const go = (n) => { if (n) { if (n.val >= low && n.val <= high) s += n.val; go(n.left); go(n.right); } }; go(root); return s; }`,
    fuzz: treeGen(`const lo = __r(rand, 0, 25); return [__bstLevel(rand, __r(rand, 1, 12), 1, 30), lo, lo + __r(rand, 0, 12)];`),
    examples: [[[10, 5, 15, 3, 7, null, 18], 7, 15], [[10, 5, 15, 3, 7, 13, 18, 1, null, 6], 6, 10]],
    edges: [
      ["single", [[5], 5, 5]],
      ["no-answer", [[10, 5, 15], 20, 30]],
      ["boundary", [[10, 5, 15], 5, 15], "Both ends of the range are included."],
    ],
  },
  {
    slug: "increasing-order-search-tree",
    title: "Increasing Order Search Tree",
    difficulty: "Easy",
    pattern: "Trees",
    leetcodeId: 897,
    fn: "increasingBST",
    params: [["root", T]],
    returns: T,
    argTypes: ["TreeNode"],
    returnKind: "TreeNode",
    hints: [
      "The result is the inorder sequence laid out as a right-only chain.",
      "Inorder walk with a tail pointer starting at a dummy node: for each node, clear its left child, hang it on tail.right and move tail.",
      "dummy = new node(0); tail = dummy\ninorder(node):\n  if node is empty: return\n  inorder(node.left)\n  node.left = empty\n  tail.right = node\n  tail = node\n  inorder(node.right)\ninorder(root)\nreturn dummy.right",
    ],
    reference: `function increasingBST(root) { const dummy = new TreeNode(0); let tail = dummy; const go = (n) => { if (!n) return; go(n.left); n.left = null; tail.right = n; tail = n; go(n.right); }; go(root); return dummy.right; }`,
    brute: `function increasingBST(root) { const v = []; const go = (n) => { if (n) { go(n.left); v.push(n.val); go(n.right); } }; go(root); let r = null; for (let i = v.length - 1; i >= 0; i--) r = new TreeNode(v[i], null, r); return r; }`,
    fuzz: treeGen(`return [__bstLevel(rand, __r(rand, 1, 12), 0, 30)];`),
    examples: [[[5, 3, 6, 2, 4, null, 8, 1, null, null, null, 7, 9]], [[5, 1, 7]]],
    edges: [
      ["single", [[1]]],
      ["skewed", [[3, 2, null, 1]], "A left chain flips into a right chain."],
      ["sorted", [[1, null, 2, null, 3]], "Already a right chain: unchanged."],
    ],
  },
  {
    slug: "find-mode-in-binary-search-tree",
    title: "Find Mode in Binary Search Tree",
    difficulty: "Easy",
    pattern: "Trees",
    leetcodeId: 501,
    fn: "findMode",
    params: [["root", T]],
    returns: "number[]",
    argTypes: ["TreeNode"],
    compare: "unordered",
    hints: [
      "Here a BST allows duplicates (left <= node <= right), so equal values sit next to each other in inorder. Any order of modes is accepted.",
      "Inorder walk counting the current run of equal values. A longer run replaces the answer list; an equal-length run is appended. No extra map needed.",
      "prev = none, run = 0, best = 0, modes = []\ninorder(node):\n  if node is empty: return\n  inorder(node.left)\n  run = run + 1 if node.val == prev else 1\n  prev = node.val\n  if run > best: best = run; modes = [node.val]\n  else if run == best: modes.append(node.val)\n  inorder(node.right)\ninorder(root)\nreturn modes",
    ],
    reference: `function findMode(root) { let prev = null, run = 0, best = 0, modes = []; const go = (n) => { if (!n) return; go(n.left); run = n.val === prev ? run + 1 : 1; prev = n.val; if (run > best) { best = run; modes = [n.val]; } else if (run === best) modes.push(n.val); go(n.right); }; go(root); return modes; }`,
    brute: `function findMode(root) { const c = new Map(); const go = (n) => { if (n) { c.set(n.val, (c.get(n.val) || 0) + 1); go(n.left); go(n.right); } }; go(root); const m = Math.max(...c.values()); return [...c.keys()].filter((k) => c.get(k) === m); }`,
    fuzz: treeGen(`${INSERT} let r = null; for (const v of __arr(rand, __r(rand, 1, 12), 1, 6)) r = __ins(r, v); return [__treeToLevelOrder(r)];`),
    examples: [[[1, null, 2, 2]], [[0]]],
    edges: [
      ["all-equal", [[2, 2, null, 2]]],
      ["duplicates", [[2, 1, 3]], "Every value appears once: all are modes."],
      ["boundary", [[5, 3, 7, 3, null, 7]], "Two modes tie."],
    ],
  },
  {
    slug: "all-elements-in-two-binary-search-trees",
    title: "All Elements in Two Binary Search Trees",
    difficulty: "Medium",
    pattern: "Trees",
    leetcodeId: 1305,
    fn: "getAllElements",
    params: [["root1", T], ["root2", T]],
    returns: "number[]",
    argTypes: ["TreeNode", "TreeNode"],
    hints: [
      "Each tree's inorder is already sorted, so this is the merge step of merge sort.",
      "Collect both inorder lists (or walk both trees with two stacks at once) and merge them with two pointers.",
      "a = inorder(root1); b = inorder(root2)\ni = j = 0; out = []\nwhile i < len(a) or j < len(b):\n  if j == len(b) or (i < len(a) and a[i] <= b[j]):\n    out.append(a[i]); i += 1\n  else:\n    out.append(b[j]); j += 1\nreturn out",
    ],
    reference: `function getAllElements(root1, root2) { const ino = (n, out) => { if (n) { ino(n.left, out); out.push(n.val); ino(n.right, out); } return out; }; const a = ino(root1, []), b = ino(root2, []), out = []; let i = 0, j = 0; while (i < a.length || j < b.length) { if (j === b.length || (i < a.length && a[i] <= b[j])) out.push(a[i++]); else out.push(b[j++]); } return out; }`,
    brute: `function getAllElements(root1, root2) { const v = []; const go = (n) => { if (n) { v.push(n.val); go(n.left); go(n.right); } }; go(root1); go(root2); return v.sort((a, b) => a - b); }`,
    fuzz: treeGen(`return [__bstLevel(rand, __r(rand, 0, 10), -10, 20), __bstLevel(rand, __r(rand, 0, 10), -10, 20)];`),
    examples: [[[2, 1, 4], [1, 0, 3]], [[1, null, 8], [8, 1]]],
    edges: [
      ["empty", [[], [5, 1, 7]], "One tree is empty."],
      ["duplicates", [[2, 1, 3], [2, 1, 3]]],
      ["negatives", [[-3, -5, -1], [0, -4]]],
    ],
  },
  {
    slug: "balance-a-binary-search-tree",
    title: "Balance a Binary Search Tree",
    difficulty: "Medium",
    pattern: "Trees",
    leetcodeId: 1382,
    fn: "balanceBST",
    params: [["root", T]],
    returns: T,
    argTypes: ["TreeNode"],
    returnKind: "TreeNode",
    compare: "balanced-same-inorder",
    hints: [
      "Inorder gives the values sorted, and a sorted list turns into a balanced BST by always picking the middle as root. Any balanced answer is accepted.",
      "Two passes: collect the inorder values, then build recursively from index ranges using the middle element.",
      "vals = inorder(root)\nbuild(lo, hi):\n  if lo > hi: return empty\n  mid = (lo + hi) // 2\n  return new node(vals[mid], build(lo, mid - 1), build(mid + 1, hi))\nreturn build(0, len(vals) - 1)",
    ],
    reference: `function balanceBST(root) { const v = []; const go = (n) => { if (n) { go(n.left); v.push(n.val); go(n.right); } }; go(root); const build = (lo, hi) => { if (lo > hi) return null; const m = (lo + hi) >> 1; return new TreeNode(v[m], build(lo, m - 1), build(m + 1, hi)); }; return build(0, v.length - 1); }`,
    brute: `function balanceBST(root) { const v = []; const go = (n) => { if (n) { go(n.left); v.push(n.val); go(n.right); } }; go(root); const build = (a) => { if (!a.length) return null; const m = Math.ceil((a.length - 1) / 2); return new TreeNode(a[m], build(a.slice(0, m)), build(a.slice(m + 1))); }; return build(v); }`,
    fuzz: treeGen(`${INSERT} const vals = __shuffle(rand, Array.from({ length: 30 }, (_, i) => i + 1)).slice(0, __r(rand, 1, 12)); if (rand() < 0.5) vals.sort((a, b) => (rand() < 0.5 ? a - b : b - a)); let r = null; for (const v of vals) r = __ins(r, v); return [__treeToLevelOrder(r)];`),
    examples: [[[1, null, 2, null, 3, null, 4]], [[2, 1, 3]]],
    edges: [
      ["single", [[1]]],
      ["skewed", [[5, 4, null, 3, null, 2, null, 1]], "A left chain."],
      ["two", [[1, null, 2]], "Two nodes are already balanced."],
    ],
  },
  {
    slug: "contains-duplicate-iii",
    title: "Contains Duplicate III",
    difficulty: "Hard",
    pattern: "Sliding Window",
    leetcodeId: 220,
    fn: "containsNearbyAlmostDuplicate",
    params: [["nums", "number[]"], ["indexDiff", "number"], ["valueDiff", "number"]],
    returns: "boolean",
    hints: [
      "Keep a window of the last indexDiff values and ask: is any value within valueDiff of the new one? A sorted set (BST) answers with floor/ceiling.",
      "Without a sorted set, use buckets of width valueDiff + 1: two values in the same bucket are close enough, and otherwise only the two neighbouring buckets can hold a match. Evict the value that slides out of the window.",
      "w = valueDiff + 1; buckets = empty map\nfor i, x in nums:\n  b = floor(x / w)\n  if b in buckets: return true\n  if b - 1 in buckets and x - buckets[b - 1] <= valueDiff: return true\n  if b + 1 in buckets and buckets[b + 1] - x <= valueDiff: return true\n  buckets[b] = x\n  if i >= indexDiff: remove bucket of nums[i - indexDiff]\nreturn false",
    ],
    reference: `function containsNearbyAlmostDuplicate(nums, indexDiff, valueDiff) { const w = valueDiff + 1, m = new Map(); for (let i = 0; i < nums.length; i++) { const x = nums[i], b = Math.floor(x / w); if (m.has(b)) return true; if (m.has(b - 1) && x - m.get(b - 1) <= valueDiff) return true; if (m.has(b + 1) && m.get(b + 1) - x <= valueDiff) return true; m.set(b, x); if (i >= indexDiff) m.delete(Math.floor(nums[i - indexDiff] / w)); } return false; }`,
    brute: `function containsNearbyAlmostDuplicate(nums, indexDiff, valueDiff) { for (let i = 0; i < nums.length; i++) for (let j = i + 1; j <= i + indexDiff && j < nums.length; j++) if (Math.abs(nums[i] - nums[j]) <= valueDiff) return true; return false; }`,
    fuzz: gen(`return [__arr(rand, __r(rand, 2, 12), -20, 20), __r(rand, 1, 4), __r(rand, 0, 3)];`),
    examples: [[[1, 2, 3, 1], 3, 0], [[1, 5, 9, 1, 5, 9], 2, 3]],
    edges: [
      ["two", [[1, 1], 1, 0]],
      ["negatives", [[-3, 3], 2, 4], "Buckets must floor negative values correctly."],
      ["boundary", [[1, 4, 7, 1], 2, 2], "The equal pair is just outside the index window."],
    ],
  },
  {
    slug: "number-of-ways-to-reorder-array-to-get-same-bst",
    title: "Number of Ways to Reorder Array to Get Same BST",
    difficulty: "Hard",
    pattern: "Trees",
    leetcodeId: 1569,
    fn: "numOfWays",
    params: [["nums", "number[]"]],
    returns: "number",
    hints: [
      "The first value is always the root. After it, the left-subtree values and right-subtree values may interleave freely as long as each side keeps its own relative order.",
      "ways(a) = C(len(a) - 1, len(left)) * ways(left) * ways(right), where left and right keep their original order. Subtract 1 for the given order and work modulo 1e9 + 7 (Pascal's triangle for C).",
      "C = Pascal's triangle up to n, mod M\nways(a):\n  if len(a) <= 2: return 1\n  left = values in a smaller than a[0], in order\n  right = values in a larger than a[0], in order\n  return C[len(a) - 1][len(left)] * ways(left) * ways(right) mod M\nreturn (ways(nums) - 1) mod M",
    ],
    reference: `function numOfWays(nums) { const M = 1000000007n, n = nums.length, C = [[1n]]; for (let i = 1; i <= n; i++) { C[i] = [1n]; for (let j = 1; j <= i; j++) C[i][j] = ((C[i - 1][j - 1] || 0n) + (C[i - 1][j] || 0n)) % M; } const f = (a) => { if (a.length <= 2) return 1n; const L = a.filter((x) => x < a[0]), R = a.filter((x) => x > a[0]); return C[a.length - 1][L.length] * f(L) % M * f(R) % M; }; return Number((f(nums) - 1n + M) % M); }`,
    brute: `function numOfWays(nums) { const shape = (a) => { let r = null; const ins = (n, v) => { if (!n) return { v, l: null, r: null }; if (v < n.v) n.l = ins(n.l, v); else n.r = ins(n.r, v); return n; }; for (const v of a) r = ins(r, v); return JSON.stringify(r); }; const target = shape(nums); let count = 0; const used = [], cur = []; const perm = () => { if (cur.length === nums.length) { if (shape(cur) === target) count++; return; } for (let i = 0; i < nums.length; i++) if (!used[i]) { used[i] = true; cur.push(nums[i]); perm(); cur.pop(); used[i] = false; } }; perm(); return count - 1; }`,
    fuzz: gen(`const n = __r(rand, 1, 7); return [__shuffle(rand, Array.from({ length: n }, (_, i) => i + 1))];`),
    examples: [[[2, 1, 3]], [[3, 4, 5, 1, 2]], [[1, 2, 3]]],
    edges: [
      ["single", [[1]], "Only the given order: 0 other ways."],
      ["sorted", [[1, 2, 3, 4]], "A chain has exactly one insertion order."],
      ["boundary", [[4, 2, 6, 1, 3, 5, 7]], "A perfect tree: many interleavings."],
    ],
  },
];

export const LADDER_BST = DEFS.map(define);
