import { define, type ProblemDef } from "./define";
import { gen } from "./gen";

const DEFS: ProblemDef[] = [
  {
    slug: "array-partition",
    title: "Array Partition",
    difficulty: "Easy",
    pattern: "Greedy",
    leetcodeId: 561,
    fn: "arrayPairSum",
    params: [["nums", "number[]"]],
    returns: "number",
    hints: [
      "Each pair contributes its smaller value. Pairing a small number with a much bigger one wastes the big one.",
      "Sort and pair neighbours: the answer is the sum of the values at even indexes.",
      "sort nums\nsum = 0\nfor i in 0, 2, 4, ...: sum = sum + nums[i]\nreturn sum",
    ],
    reference: `function arrayPairSum(nums) { return nums.slice().sort((a, b) => a - b).reduce((s, v, i) => (i % 2 ? s : s + v), 0); }`,
    brute: `function arrayPairSum(nums) { const go = (left) => { if (!left.length) return 0; let best = -Infinity; for (let j = 1; j < left.length; j++) best = Math.max(best, Math.min(left[0], left[j]) + go(left.filter((_, k) => k !== 0 && k !== j))); return best; }; return go(nums); }`,
    fuzz: gen(`return [__arr(rand, 2 * __r(rand, 1, 4), -10, 10)];`),
    examples: [[[1, 4, 3, 2]], [[6, 2, 6, 5, 1, 2]]],
    edges: [
      ["two", [[7, 3]]],
      ["all-equal", [[5, 5, 5, 5]]],
      ["negatives", [[-1, -4, 2, 0]]],
    ],
  },
  {
    slug: "largest-perimeter-triangle",
    title: "Largest Perimeter Triangle",
    difficulty: "Easy",
    pattern: "Greedy",
    leetcodeId: 976,
    fn: "largestPerimeter",
    params: [["nums", "number[]"]],
    returns: "number",
    hints: [
      "Three sides a <= b <= c form a triangle exactly when a + b > c.",
      "Sort descending and check consecutive triples: for the largest c, the best partners are the next two largest values.",
      "sort nums descending\nfor i in 0 .. n - 3:\n  if nums[i + 1] + nums[i + 2] > nums[i]: return nums[i] + nums[i + 1] + nums[i + 2]\nreturn 0",
    ],
    reference: `function largestPerimeter(nums) { const a = nums.slice().sort((x, y) => y - x); for (let i = 0; i + 2 < a.length; i++) if (a[i + 1] + a[i + 2] > a[i]) return a[i] + a[i + 1] + a[i + 2]; return 0; }`,
    brute: `function largestPerimeter(nums) { let best = 0; const n = nums.length; for (let i = 0; i < n; i++) for (let j = i + 1; j < n; j++) for (let k = j + 1; k < n; k++) { const [a, b, c] = [nums[i], nums[j], nums[k]].sort((x, y) => x - y); if (a + b > c) best = Math.max(best, a + b + c); } return best; }`,
    fuzz: gen(`return [__arr(rand, __r(rand, 3, 10), 1, 20)];`),
    examples: [[[2, 1, 2]], [[1, 2, 1, 10]]],
    edges: [
      ["all-equal", [[3, 3, 3]]],
      ["no-answer", [[1, 2, 3]], "1 + 2 = 3 is degenerate, not a triangle."],
      ["boundary", [[3, 6, 2, 3]]],
    ],
  },
  {
    slug: "maximum-69-number",
    title: "Maximum 69 Number",
    difficulty: "Easy",
    pattern: "Greedy",
    leetcodeId: 1323,
    fn: "maximum69Number",
    params: [["num", "number"]],
    returns: "number",
    hints: [
      "Turning a 6 into a 9 helps more the further left it is.",
      "Change the leftmost 6 to a 9 (if there is one).",
      "s = digits of num\nreplace the first '6' in s with '9'\nreturn number(s)",
    ],
    reference: `function maximum69Number(num) { return Number(String(num).replace("6", "9")); }`,
    brute: `function maximum69Number(num) { const s = String(num); let best = num; for (let i = 0; i < s.length; i++) best = Math.max(best, Number(s.slice(0, i) + (s[i] === "6" ? "9" : "6") + s.slice(i + 1))); return best; }`,
    fuzz: gen(`return [Number(__str(rand, __r(rand, 1, 4), "69"))];`),
    examples: [[9669], [9996], [9999]],
    edges: [
      ["single", [6]],
      ["all-equal", [6666]],
      ["boundary", [996], "The only 6 is the last digit."],
    ],
  },
  {
    slug: "split-a-string-in-balanced-strings",
    title: "Split a String in Balanced Strings",
    difficulty: "Easy",
    pattern: "Greedy",
    leetcodeId: 1221,
    fn: "balancedStringSplit",
    params: [["s", "string"]],
    returns: "number",
    hints: [
      "Cut as soon as a piece is balanced: waiting can only merge pieces.",
      "Keep a counter (+1 for R, -1 for L). Every time it returns to 0, count a piece.",
      "bal = 0, pieces = 0\nfor c in s:\n  bal = bal + (1 if c == 'R' else -1)\n  if bal == 0: pieces = pieces + 1\nreturn pieces",
    ],
    reference: `function balancedStringSplit(s) { let b = 0, p = 0; for (const c of s) { b += c === "R" ? 1 : -1; if (b === 0) p++; } return p; }`,
    brute: `function balancedStringSplit(s) { const n = s.length, dp = new Array(n + 1).fill(-Infinity); dp[0] = 0; for (let j = 1; j <= n; j++) for (let i = 0; i < j; i++) { const t = s.slice(i, j); if (t.split("R").length - 1 === t.split("L").length - 1) dp[j] = Math.max(dp[j], dp[i] + 1); } return dp[n]; }`,
    fuzz: gen(`const k = __r(rand, 1, 8); return [__shuffle(rand, ("R".repeat(k) + "L".repeat(k)).split("")).join("")];`),
    examples: [["RLRRLLRLRL"], ["RLRRRLLRLL"], ["LLLLRRRR"]],
    edges: [
      ["two", ["RL"]],
      ["boundary", ["RRLL"], "Balanced only at the very end."],
      ["duplicates", ["LRLRLRLR"]],
    ],
  },
  {
    slug: "minimum-cost-to-move-chips-to-the-same-position",
    title: "Minimum Cost to Move Chips to The Same Position",
    difficulty: "Easy",
    pattern: "Greedy",
    leetcodeId: 1217,
    fn: "minCostToMoveChips",
    params: [["position", "number[]"]],
    returns: "number",
    hints: [
      "Moving by 2 is free, so every chip can reach any position of the same parity for nothing.",
      "Gather all chips on one even and one odd spot for free; then move the smaller group across at cost 1 each.",
      "odd = count of odd positions\neven = n - odd\nreturn min(odd, even)",
    ],
    reference: `function minCostToMoveChips(position) { const odd = position.filter((p) => p % 2).length; return Math.min(odd, position.length - odd); }`,
    brute: `function minCostToMoveChips(position) { let best = Infinity; for (const t of position) best = Math.min(best, position.reduce((s, p) => s + (Math.abs(p - t) % 2), 0)); return best; }`,
    fuzz: gen(`return [__arr(rand, __r(rand, 1, 10), 1, 30)];`),
    examples: [[[1, 2, 3]], [[2, 2, 2, 3, 3]], [[1, 1000000000]]],
    edges: [
      ["single", [[7]]],
      ["all-equal", [[4, 4, 4]]],
      ["boundary", [[2, 4, 6, 1]], "Only one odd chip has to pay."],
    ],
  },
  {
    slug: "patching-array",
    title: "Patching Array",
    difficulty: "Hard",
    pattern: "Greedy",
    leetcodeId: 330,
    fn: "minPatches",
    params: [["nums", "number[]"], ["n", "number"]],
    returns: "number",
    hints: [
      "Suppose every sum in [1, miss) can be formed. A number x <= miss extends that to [1, miss + x).",
      "Walk the sorted nums. If the next number is <= miss, use it; otherwise patch with miss itself (the largest number that keeps the range gap-free), doubling the range.",
      "miss = 1, i = 0, patches = 0\nwhile miss <= n:\n  if i < len(nums) and nums[i] <= miss:\n    miss = miss + nums[i], i = i + 1\n  else:\n    miss = miss + miss, patches = patches + 1\nreturn patches",
    ],
    reference: `function minPatches(nums, n) { let miss = 1, i = 0, p = 0; while (miss <= n) { if (i < nums.length && nums[i] <= miss) miss += nums[i++]; else { miss += miss; p++; } } return p; }`,
    brute: `function minPatches(nums, n) { const have = nums.slice(); let p = 0; for (;;) { const can = new Array(n + 1).fill(false); can[0] = true; for (const v of have) for (let s = n; s >= v; s--) if (can[s - v]) can[s] = true; let miss = 1; while (miss <= n && can[miss]) miss++; if (miss > n) return p; have.push(miss); p++; } }`,
    fuzz: gen(`return [__sorted(rand, __r(rand, 0, 6), 1, 20), __r(rand, 1, 80)];`),
    examples: [[[1, 3], 6], [[1, 5, 10], 20], [[1, 2, 2], 5]],
    edges: [
      ["empty", [[], 7], "Patch 1, 2, 4."],
      ["single", [[1], 1]],
      ["large", [[], 1000], "Patch 1, 2, 4, ..., 512: ten patches."],
    ],
  },
];

export const LADDER_GREEDY = DEFS.map(define);
