import { design } from "../dsa-testcases/specs/ladder-stack-seeded";
import { define, type ProblemDef } from "./define";
import { gen } from "./gen";

const TR = "Tries";
const WORDS = (n: number, len: number, alphabet: string) =>
  `[...new Set(Array.from({ length: __r(rand, 1, ${n}) }, () => __str(rand, __r(rand, 1, ${len}), "${alphabet}")))]`;

const DEFS: ProblemDef[] = [
  {
    slug: "counting-words-with-a-given-prefix",
    title: "Counting Words With a Given Prefix",
    difficulty: "Easy",
    pattern: TR,
    leetcodeId: 2185,
    fn: "prefixCount",
    params: [["words", "string[]"], ["pref", "string"]],
    returns: "number",
    hints: [
      "Count the words that start with pref.",
      "Compare the first len(pref) letters of each word with pref. (With many queries, a trie storing a count at every node answers each in O(len(pref)).)",
      "count = 0\nfor w in words:\n  if len(w) >= len(pref) and w[0 .. len(pref) - 1] == pref: count += 1\nreturn count",
    ],
    reference: `function prefixCount(words, pref) { return words.filter((w) => w.startsWith(pref)).length; }`,
    brute: `function prefixCount(words, pref) { const root = { c: 0 }; for (const w of words) { let n = root; for (const ch of w) { n = n[ch] || (n[ch] = { c: 0 }); n.c++; } } let n = root; for (const ch of pref) { n = n[ch]; if (!n) return 0; } return n.c; }`,
    fuzz: gen(`return [Array.from({ length: __r(rand, 1, 8) }, () => __str(rand, __r(rand, 1, 4), "ab")), __str(rand, __r(rand, 1, 3), "ab")];`),
    examples: [[["pay", "attention", "practice", "attend"], "at"], [["leetcode", "win", "loops", "success"], "code"]],
    edges: [
      ["duplicates", [["ab", "ab", "abc"], "ab"]],
      ["boundary", [["a"], "ab"], "The prefix is longer than the word."],
      ["single", [["x"], "x"]],
    ],
  },
  {
    slug: "count-prefix-and-suffix-pairs-i",
    title: "Count Prefix and Suffix Pairs I",
    difficulty: "Easy",
    pattern: TR,
    leetcodeId: 3042,
    fn: "countPrefixSuffixPairs",
    params: [["words", "string[]"]],
    returns: "number",
    hints: [
      "Count pairs i < j where words[i] is both a prefix and a suffix of words[j].",
      "Small inputs: check every pair with startsWith and endsWith. (The hard version stores pairs (word[k], word[len - 1 - k]) in a trie so both ends are checked in one walk.)",
      "count = 0\nfor i in 0 .. n - 1:\n  for j in i + 1 .. n - 1:\n    if words[j] starts with words[i] and ends with words[i]: count += 1\nreturn count",
    ],
    reference: `function countPrefixSuffixPairs(words) { let c = 0; for (let i = 0; i < words.length; i++) for (let j = i + 1; j < words.length; j++) if (words[j].startsWith(words[i]) && words[j].endsWith(words[i])) c++; return c; }`,
    brute: `function countPrefixSuffixPairs(words) { const root = { c: 0 }; let total = 0; for (const w of words) { let n = root; for (let k = 0; k < w.length; k++) { const key = w[k] + w[w.length - 1 - k]; n = n[key]; if (!n) break; total += n.c; } n = root; for (let k = 0; k < w.length; k++) { const key = w[k] + w[w.length - 1 - k]; n = n[key] || (n[key] = { c: 0 }); } n.c++; } return total; }`,
    fuzz: gen(`return [Array.from({ length: __r(rand, 1, 8) }, () => __str(rand, __r(rand, 1, 4), "ab"))];`),
    examples: [[["a", "aba", "ababa", "aa"]], [["pa", "papa", "ma", "mama"]], [["abab", "ab"]]],
    edges: [
      ["single", [["a"]]],
      ["all-equal", [["a", "a", "a"]], "Every pair counts: 3."],
      ["order", [["aba", "a"]], "Only i < j counts."],
    ],
  },
  {
    slug: "find-the-length-of-the-longest-common-prefix",
    title: "Find the Length of the Longest Common Prefix",
    difficulty: "Medium",
    pattern: TR,
    leetcodeId: 3043,
    fn: "longestCommonPrefix",
    params: [["arr1", "number[]"], ["arr2", "number[]"]],
    returns: "number",
    hints: [
      "Over all pairs (x from arr1, y from arr2), find the longest common prefix of their digits.",
      "Insert every number of arr1 into a trie of digits. Walk each number of arr2 down the trie; the depth reached is its best prefix length.",
      "trie = digits of every x in arr1\nbest = 0\nfor y in arr2:\n  node = root; depth = 0\n  for d in digits of y:\n    if d not in node.child: break\n    node = node.child[d]; depth += 1\n  best = max(best, depth)\nreturn best",
    ],
    reference: `function longestCommonPrefix(arr1, arr2) { const root = {}; for (const x of arr1) { let n = root; for (const d of String(x)) n = n[d] || (n[d] = {}); } let best = 0; for (const y of arr2) { let n = root, depth = 0; for (const d of String(y)) { n = n[d]; if (!n) break; depth++; } best = Math.max(best, depth); } return best; }`,
    brute: `function longestCommonPrefix(arr1, arr2) { let best = 0; for (const x of arr1) for (const y of arr2) { const a = String(x), b = String(y); let k = 0; while (k < a.length && k < b.length && a[k] === b[k]) k++; best = Math.max(best, k); } return best; }`,
    fuzz: gen(`const num = () => Number(String(__r(rand, 1, 9)) + __str(rand, __r(rand, 0, 4), "0123")); return [Array.from({ length: __r(rand, 1, 6) }, num), Array.from({ length: __r(rand, 1, 6) }, num)];`),
    examples: [[[1, 10, 100], [1000]], [[1, 2, 3], [4, 4, 4]]],
    edges: [
      ["single", [[5], [5]]],
      ["no-answer", [[12, 13], [21]]],
      ["extremes", [[100000000], [100000001]], "Long numbers sharing most digits."],
    ],
  },
  {
    slug: "short-encoding-of-words",
    title: "Short Encoding of Words",
    difficulty: "Medium",
    pattern: TR,
    leetcodeId: 820,
    fn: "minimumLengthEncoding",
    params: [["words", "string[]"]],
    returns: "number",
    hints: [
      "A word that is a suffix of another word can hide inside it: 'me' is free once 'time#' is written.",
      "Keep only words that are not a proper suffix of another word (a trie of reversed words: count the leaves). The answer is the sum of (length + 1) over the kept words.",
      "keep = set of words\nfor w in words:\n  for k in 1 .. len(w) - 1:\n    remove w[k ..] from keep\nreturn sum of len(w) + 1 for w in keep",
    ],
    reference: `function minimumLengthEncoding(words) { const keep = new Set(words); for (const w of words) for (let k = 1; k < w.length; k++) keep.delete(w.slice(k)); let s = 0; for (const w of keep) s += w.length + 1; return s; }`,
    brute: `function minimumLengthEncoding(words) { const u = [...new Set(words)]; return u.filter((w) => !u.some((x) => x !== w && x.endsWith(w))).reduce((s, w) => s + w.length + 1, 0); }`,
    fuzz: gen(`return [Array.from({ length: __r(rand, 1, 8) }, () => __str(rand, __r(rand, 1, 4), "ab"))];`),
    examples: [[["time", "me", "bell"]], [["t"]]],
    edges: [
      ["duplicates", [["ab", "ab"]], "Equal words are written once."],
      ["boundary", [["a", "ba", "cba"]], "A chain of suffixes collapses to one word."],
      ["no-answer", [["ab", "ba"]], "Neither hides in the other."],
    ],
  },
  design({
    slug: "implement-magic-dictionary",
    title: "Implement Magic Dictionary",
    difficulty: "Medium",
    pattern: TR,
    leetcodeId: 676,
    cls: "MagicDictionary",
    methods: ["buildDict(dictionary)", "search(searchWord)"],
    hints: [
      "search is true when changing exactly one letter of searchWord gives a dictionary word. Zero changes do not count.",
      "Store words by length (or in a trie and allow one mismatch while walking). For each candidate of the same length, count differing positions and accept exactly one.",
      "buildDict(d): words = d\nsearch(s):\n  for w in words with len(w) == len(s):\n    diff = number of positions where w and s differ\n    if diff == 1: return true\n  return false",
    ],
    reference: `class MagicDictionary { constructor() { this.root = {}; } buildDict(dictionary) { for (const w of dictionary) { let n = this.root; for (const ch of w) n = n[ch] || (n[ch] = {}); n.$ = true; } } search(searchWord) { const go = (n, i, used) => { if (i === searchWord.length) return used && !!n.$; for (const k of Object.keys(n)) { if (k === "$") continue; if (k === searchWord[i]) { if (go(n[k], i + 1, used)) return true; } else if (!used && go(n[k], i + 1, true)) return true; } return false; }; return go(this.root, 0, false); } }`,
    brute: `class MagicDictionary { constructor() { this.w = []; } buildDict(dictionary) { this.w = dictionary; } search(s) { return this.w.some((x) => x.length === s.length && [...x].filter((c, i) => c !== s[i]).length === 1); } }`,
    fuzz: gen(`const dict = ${WORDS(5, 3, "abc")}, ops = [["MagicDictionary"], ["buildDict", dict]]; for (let i = 0; i < __r(rand, 1, 10); i++) { const base = rand() < 0.6 ? __pick(rand, dict) : __str(rand, __r(rand, 1, 3), "abc"); const k = __r(rand, 0, base.length - 1), s = rand() < 0.7 ? base.slice(0, k) + __pick(rand, ["a", "b", "c"]) + base.slice(k + 1) : base; ops.push(["search", s]); } return [ops];`),
    examples: [[[["MagicDictionary"], ["buildDict", ["hello", "leetcode"]], ["search", "hello"], ["search", "hhllo"], ["search", "hell"], ["search", "leetcoded"]]], [[["MagicDictionary"], ["buildDict", ["a"]], ["search", "b"]]]],
    edges: [
      ["boundary", [[["MagicDictionary"], ["buildDict", ["hello", "hallo"]], ["search", "hello"]]], "Exact match fails, but 'hallo' is one change away."],
      ["single-char", [[["MagicDictionary"], ["buildDict", ["a"]], ["search", "a"]]], "Zero changes is not allowed."],
      ["no-answer", [[["MagicDictionary"], ["buildDict", ["abc"]], ["search", "xyz"], ["search", "ab"]]]],
    ],
  }),
  {
    slug: "sum-of-prefix-scores-of-strings",
    title: "Sum of Prefix Scores of Strings",
    difficulty: "Hard",
    pattern: TR,
    leetcodeId: 2416,
    fn: "sumPrefixScores",
    params: [["words", "string[]"]],
    returns: "number[]",
    hints: [
      "The score of a prefix is how many words start with it. Each word's answer is the sum of scores over all of its non-empty prefixes.",
      "Insert every word into a trie, incrementing a counter at each node passed. Then walk each word again and add up the counters along its path.",
      "for w in words:\n  node = root\n  for ch in w: node = node.child[ch] (create if missing); node.count += 1\nfor each word w:\n  node = root; total = 0\n  for ch in w: node = node.child[ch]; total += node.count\n  answer for w = total\nreturn answers",
    ],
    reference: `function sumPrefixScores(words) { const root = {}; for (const w of words) { let n = root; for (const ch of w) { n = n[ch] || (n[ch] = { $: 0 }); n.$++; } } return words.map((w) => { let n = root, t = 0; for (const ch of w) { n = n[ch]; t += n.$; } return t; }); }`,
    brute: `function sumPrefixScores(words) { return words.map((w) => { let t = 0; for (let k = 1; k <= w.length; k++) { const p = w.slice(0, k); t += words.filter((x) => x.startsWith(p)).length; } return t; }); }`,
    fuzz: gen(`return [Array.from({ length: __r(rand, 1, 8) }, () => __str(rand, __r(rand, 1, 5), "ab"))];`),
    examples: [[["abc", "ab", "bc", "b"]], [["abcd"]]],
    edges: [
      ["all-equal", [["a", "a"]]],
      ["single-char", [["a", "b", "c"]]],
      ["boundary", [["aaa", "aa", "a"]], "Nested prefixes."],
    ],
  },
  design({
    slug: "prefix-and-suffix-search",
    title: "Prefix and Suffix Search",
    difficulty: "Hard",
    pattern: TR,
    leetcodeId: 745,
    cls: "WordFilter",
    ctor: "words",
    methods: ["f(pref, suff)"],
    hints: [
      "f returns the largest index of a word with the given prefix and suffix, or -1.",
      "Precompute every (prefix, suffix) pair of every word into a map, letting later indices overwrite earlier ones; f is then one lookup. (Or insert 'suffix#word' strings into a trie.)",
      "constructor(words):\n  table = empty map\n  for idx, w in words:\n    for each prefix p of w (including empty) and each suffix s of w (including empty):\n      table[p + '#' + s] = idx\nf(pref, suff): return table.get(pref + '#' + suff, -1)",
    ],
    reference: `class WordFilter { constructor(words) { this.t = new Map(); words.forEach((w, idx) => { for (let a = 0; a <= w.length; a++) for (let b = 0; b <= w.length; b++) this.t.set(w.slice(0, a) + "#" + w.slice(b), idx); }); } f(pref, suff) { return this.t.has(pref + "#" + suff) ? this.t.get(pref + "#" + suff) : -1; } }`,
    brute: `class WordFilter { constructor(words) { this.w = words; } f(pref, suff) { for (let i = this.w.length - 1; i >= 0; i--) if (this.w[i].startsWith(pref) && this.w[i].endsWith(suff)) return i; return -1; } }`,
    fuzz: gen(`const words = Array.from({ length: __r(rand, 1, 5) }, () => __str(rand, __r(rand, 1, 4), "ab")), ops = [["WordFilter", words]]; for (let i = 0; i < __r(rand, 1, 8); i++) ops.push(["f", __str(rand, __r(rand, 1, 2), "ab"), __str(rand, __r(rand, 1, 2), "ab")]); return [ops];`),
    examples: [[[["WordFilter", ["apple"]], ["f", "a", "e"]]], [[["WordFilter", ["abc", "abd"]], ["f", "ab", "c"], ["f", "ab", "d"], ["f", "ab", "e"]]]],
    edges: [
      ["duplicates", [[["WordFilter", ["ab", "ab"]], ["f", "a", "b"]]], "Equal words: the larger index wins."],
      ["boundary", [[["WordFilter", ["aba"]], ["f", "aba", "aba"], ["f", "abab", "b"]]], "Prefix and suffix may be the whole word."],
      ["single-char", [[["WordFilter", ["a"]], ["f", "a", "a"], ["f", "b", "a"]]]],
    ],
  }),
];

export const LADDER_TRIES = DEFS.map(define);
