import { define, type ProblemDef } from "./define";
import { gen } from "./gen";

/** JavaScript has no built-in priority queue, so the reference solutions carry this small binary heap. */
export const HEAP = `class MinHeap { constructor(cmp) { this.a = []; this.cmp = cmp; } get size() { return this.a.length; } peek() { return this.a[0]; } push(v) { const a = this.a; a.push(v); let i = a.length - 1; while (i > 0) { const p = (i - 1) >> 1; if (this.cmp(a[i], a[p]) >= 0) break; [a[i], a[p]] = [a[p], a[i]]; i = p; } } pop() { const a = this.a, top = a[0], last = a.pop(); if (a.length) { a[0] = last; let i = 0; for (;;) { const l = 2 * i + 1, r = l + 1; let m = i; if (l < a.length && this.cmp(a[l], a[m]) < 0) m = l; if (r < a.length && this.cmp(a[r], a[m]) < 0) m = r; if (m === i) break; [a[i], a[m]] = [a[m], a[i]]; i = m; } } return top; } }`;

const DEFS: ProblemDef[] = [
  {
    slug: "relative-ranks",
    title: "Relative Ranks",
    difficulty: "Easy",
    pattern: "Heap / Priority Queue",
    leetcodeId: 506,
    fn: "findRelativeRanks",
    params: [["score", "number[]"]],
    returns: "string[]",
    hints: [
      "You need each athlete's place, so you need the scores in descending order but the answers in the original order.",
      "Push (score, index) into a max-heap and pop: the i-th pop is place i + 1. The top three get medals, the rest their place as a string.",
      "heap = max-heap of (score[i], i)\nnames = [\"Gold Medal\", \"Silver Medal\", \"Bronze Medal\"]\nfor place in 1 .. n:\n  (s, i) = pop\n  ans[i] = names[place - 1] if place <= 3 else str(place)\nreturn ans",
    ],
    reference: `${HEAP} function findRelativeRanks(score) { const h = new MinHeap((a, b) => b[0] - a[0]); score.forEach((s, i) => h.push([s, i])); const names = ["Gold Medal", "Silver Medal", "Bronze Medal"], ans = new Array(score.length); for (let p = 1; h.size; p++) { const [, i] = h.pop(); ans[i] = p <= 3 ? names[p - 1] : String(p); } return ans; }`,
    brute: `function findRelativeRanks(score) { return score.map((s) => { const p = 1 + score.filter((t) => t > s).length; return p === 1 ? "Gold Medal" : p === 2 ? "Silver Medal" : p === 3 ? "Bronze Medal" : String(p); }); }`,
    fuzz: gen(`return [__shuffle(rand, Array.from({ length: 30 }, (_, i) => i)).slice(0, __r(rand, 1, 9))];`),
    examples: [[[5, 4, 3, 2, 1]], [[10, 3, 8, 9, 4]]],
    edges: [
      ["single", [[7]]],
      ["two", [[1, 2]]],
      ["sorted", [[1, 2, 3, 4, 5]], "Ascending scores: the last athlete wins."],
    ],
  },
  {
    slug: "take-gifts-from-the-richest-pile",
    title: "Take Gifts From the Richest Pile",
    difficulty: "Easy",
    pattern: "Heap / Priority Queue",
    leetcodeId: 2558,
    fn: "pickGifts",
    params: [["gifts", "number[]"], ["k", "number"]],
    returns: "number",
    hints: [
      "Every second you need the current largest pile, and that pile then shrinks.",
      "Max-heap: pop the largest, push back floor(sqrt(x)), k times. Sum what remains.",
      "heap = max-heap of gifts\nrepeat k times:\n  x = pop\n  push floor(sqrt(x))\nreturn sum of heap",
    ],
    reference: `${HEAP} function pickGifts(gifts, k) { const h = new MinHeap((a, b) => b - a); for (const g of gifts) h.push(g); for (let i = 0; i < k; i++) h.push(Math.floor(Math.sqrt(h.pop()))); return h.a.reduce((s, x) => s + x, 0); }`,
    brute: `function pickGifts(gifts, k) { const a = gifts.slice(); for (let i = 0; i < k; i++) { let m = 0; for (let j = 1; j < a.length; j++) if (a[j] > a[m]) m = j; let r = 0; while ((r + 1) * (r + 1) <= a[m]) r++; a[m] = r; } return a.reduce((s, x) => s + x, 0); }`,
    fuzz: gen(`return [__arr(rand, __r(rand, 1, 8), 1, 100), __r(rand, 1, 8)];`),
    examples: [[[25, 64, 9, 4, 100], 4], [[1, 1, 1, 1], 4]],
    edges: [
      ["single", [[16], 3]],
      ["all-equal", [[9, 9, 9], 2]],
      ["extremes", [[1000000000], 1]],
    ],
  },
  {
    slug: "remove-stones-to-minimize-the-total",
    title: "Remove Stones to Minimize the Total",
    difficulty: "Medium",
    pattern: "Heap / Priority Queue",
    leetcodeId: 1962,
    fn: "minStoneSum",
    params: [["piles", "number[]"], ["k", "number"]],
    returns: "number",
    hints: [
      "Halving a big pile removes more stones than halving a small one, so always pick the current largest.",
      "Max-heap: k times, pop x and push x - floor(x / 2). Return the heap's sum.",
      "heap = max-heap of piles\nrepeat k times:\n  x = pop\n  push x - floor(x / 2)\nreturn sum of heap",
    ],
    reference: `${HEAP} function minStoneSum(piles, k) { const h = new MinHeap((a, b) => b - a); for (const p of piles) h.push(p); for (let i = 0; i < k; i++) { const x = h.pop(); h.push(x - Math.floor(x / 2)); } return h.a.reduce((s, x) => s + x, 0); }`,
    brute: `function minStoneSum(piles, k) { const a = piles.slice(); for (let i = 0; i < k; i++) { const m = a.indexOf(Math.max(...a)); a[m] -= Math.floor(a[m] / 2); } return a.reduce((s, x) => s + x, 0); }`,
    fuzz: gen(`return [__arr(rand, __r(rand, 1, 8), 1, 50), __r(rand, 1, 10)];`),
    examples: [[[5, 4, 9], 2], [[4, 3, 6, 7], 3]],
    edges: [
      ["single", [[1], 5], "A pile of 1 never shrinks."],
      ["all-equal", [[8, 8], 3]],
      ["large", [[10000, 9999, 1], 6]],
    ],
  },
  {
    slug: "maximal-score-after-applying-k-operations",
    title: "Maximal Score After Applying K Operations",
    difficulty: "Medium",
    pattern: "Heap / Priority Queue",
    leetcodeId: 2530,
    fn: "maxKelements",
    params: [["nums", "number[]"], ["k", "number"]],
    returns: "number",
    hints: [
      "Take the largest value every time; shrinking it to ceil(x / 3) can never make a smaller pick better.",
      "Max-heap: k times, pop x, add it to the score, push ceil(x / 3).",
      "heap = max-heap of nums, score = 0\nrepeat k times:\n  x = pop\n  score = score + x\n  push ceil(x / 3)\nreturn score",
    ],
    reference: `${HEAP} function maxKelements(nums, k) { const h = new MinHeap((a, b) => b - a); for (const x of nums) h.push(x); let s = 0; for (let i = 0; i < k; i++) { const x = h.pop(); s += x; h.push(Math.ceil(x / 3)); } return s; }`,
    brute: `function maxKelements(nums, k) { const a = nums.slice(); let s = 0; for (let i = 0; i < k; i++) { a.sort((x, y) => y - x); s += a[0]; a[0] = Math.floor((a[0] + 2) / 3); } return s; }`,
    fuzz: gen(`return [__arr(rand, __r(rand, 1, 8), 1, 60), __r(rand, 1, 10)];`),
    examples: [[[10, 10, 10, 10, 10], 5], [[1, 10, 3, 3, 3], 3]],
    edges: [
      ["single", [[7], 4]],
      ["boundary", [[1, 1], 5], "Once everything is 1, each pick adds 1."],
      ["extremes", [[1000000000, 1], 3]],
    ],
  },
  {
    slug: "kth-smallest-prime-fraction",
    title: "K-th Smallest Prime Fraction",
    difficulty: "Medium",
    pattern: "Heap / Priority Queue",
    leetcodeId: 786,
    fn: "kthSmallestPrimeFraction",
    params: [["arr", "number[]"], ["k", "number"]],
    returns: "number[]",
    hints: [
      "For a fixed denominator arr[j], the fractions arr[0]/arr[j], arr[1]/arr[j], ... increase. That is a set of sorted lists.",
      "Merge them with a min-heap: start with arr[0]/arr[j] for every j, pop k - 1 times, and after popping i/j push (i + 1)/j if i + 1 < j. Compare a/b < c/d as a*d < c*b.",
      "heap = min-heap of (0, j) for j in 1 .. n - 1, ordered by arr[i] / arr[j]\nrepeat k - 1 times:\n  (i, j) = pop\n  if i + 1 < j: push (i + 1, j)\n(i, j) = heap top\nreturn [arr[i], arr[j]]",
    ],
    reference: `${HEAP} function kthSmallestPrimeFraction(arr, k) { const h = new MinHeap((a, b) => arr[a[0]] * arr[b[1]] - arr[b[0]] * arr[a[1]]); for (let j = 1; j < arr.length; j++) h.push([0, j]); for (let r = 1; r < k; r++) { const [i, j] = h.pop(); if (i + 1 < j) h.push([i + 1, j]); } const [i, j] = h.peek(); return [arr[i], arr[j]]; }`,
    brute: `function kthSmallestPrimeFraction(arr, k) { const all = []; for (let i = 0; i < arr.length; i++) for (let j = i + 1; j < arr.length; j++) all.push([arr[i], arr[j]]); all.sort((a, b) => a[0] * b[1] - b[0] * a[1]); return all[k - 1]; }`,
    fuzz: gen(`const primes = [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37]; const arr = [1, ...__shuffle(rand, primes.slice()).slice(0, __r(rand, 1, 6)).sort((a, b) => a - b)]; const n = arr.length; return [arr, __r(rand, 1, (n * (n - 1)) / 2)];`),
    examples: [[[1, 2, 3, 5], 3], [[1, 7], 1]],
    edges: [
      ["boundary", [[1, 2, 3, 5], 6], "The largest fraction is the last one."],
      ["min-size", [[1, 3], 1]],
      ["sorted", [[1, 2, 3, 5, 7], 1], "The smallest fraction is 1 over the largest prime."],
    ],
  },
  {
    slug: "distant-barcodes",
    title: "Distant Barcodes",
    difficulty: "Medium",
    pattern: "Heap / Priority Queue",
    leetcodeId: 1054,
    fn: "rearrangeBarcodes",
    params: [["barcodes", "number[]"]],
    returns: "number[]",
    compare: "no-adjacent-repeat",
    hints: [
      "An answer always exists. Any arrangement with no two equal neighbours is accepted.",
      "Max-heap by count: place the most frequent code that differs from the last one placed, holding back the one you just used for one step.",
      "heap = max-heap of (count, code)\nout = [], held = none\nwhile heap not empty:\n  (c, x) = pop; out.append(x)\n  if held has count > 0: push held\n  held = (c - 1, x)\nreturn out",
    ],
    reference: `${HEAP} function rearrangeBarcodes(barcodes) { const c = new Map(); for (const b of barcodes) c.set(b, (c.get(b) || 0) + 1); const h = new MinHeap((a, b) => b[0] - a[0] || a[1] - b[1]); for (const [x, n] of c) h.push([n, x]); const out = []; let held = null; while (h.size) { const [n, x] = h.pop(); out.push(x); if (held && held[0] > 0) h.push(held); held = [n - 1, x]; } return out; }`,
    brute: `function rearrangeBarcodes(barcodes) { const c = new Map(); for (const b of barcodes) c.set(b, (c.get(b) || 0) + 1); const order = [...c.keys()].sort((a, b) => c.get(b) - c.get(a) || a - b); const flat = []; for (const x of order) for (let i = 0; i < c.get(x); i++) flat.push(x); const out = new Array(flat.length); let p = 0; for (let i = 0; i < out.length; i += 2) out[i] = flat[p++]; for (let i = 1; i < out.length; i += 2) out[i] = flat[p++]; return out; }`,
    fuzz: gen(`for (;;) { const a = __arr(rand, __r(rand, 1, 10), 1, 4); const c = {}; for (const x of a) c[x] = (c[x] || 0) + 1; if (Math.max(...Object.values(c)) <= Math.ceil(a.length / 2)) return [a]; }`),
    examples: [[[1, 1, 1, 2, 2, 2]], [[1, 1, 1, 1, 2, 2, 3, 3]]],
    edges: [
      ["single", [[5]]],
      ["boundary", [[2, 2, 2, 1, 1]], "The most frequent code fills every other slot."],
      ["two", [[4, 9]]],
    ],
  },
];

export const LADDER_HEAPS = DEFS.map(define);
