import type { Metadata } from "next";
import { ListChecks } from "lucide-react";
import { ComingInPhase } from "@/components/shared/empty-state";
import { PageHeader } from "@/components/shared/page-header";

export const metadata: Metadata = { title: "Quiz" };

export default function QuizPage() {
  return (
    <>
      <PageHeader title="Daily quiz" description="10 MCQs from what you studied today. Pass ≥ 60% to complete the day." />
      <ComingInPhase icon={ListChecks} title="Quiz engine" phase={5}>
        Unlocks after one problem and one subtopic. Generated by an LLM from your day, with a static bank as fallback.
      </ComingInPhase>
    </>
  );
}
