// Extra rows merged into the cheat sheets by scripts/generate-dsa-cheat-sheets.mjs:
// more patterns and decision rows for the existing topics, an interview workflow for every topic, and new topics.

export const row = (pattern, recognitionSignal, typicalProblems, typicalComplexity, firstQuestion, examples = []) => ({
  pattern,
  recognitionSignal,
  typicalProblems,
  typicalComplexity,
  firstQuestion,
  ...(examples.length ? { examples } : {}),
});
export const choice = (signal, thinkFirst) => ({ signal, thinkFirst });
const step = (action, mistake, practice) => ({ action, mistake, practice });
const flow = (...steps) => steps.map((s, i) => ({ step: i + 1, ...s }));

/** Examples (local problem slugs) for patterns that already exist, keyed by sheet id then pattern name. */
export const EXAMPLES = {
  arrays: {
    "Basic Traversal": ["maximum-subarray", "find-pivot-index"],
    "Linear Search": ["find-the-index-of-the-first-occurrence-in-a-string", "length-of-last-word"],
    "Index Traversal": ["can-place-flowers", "sign-of-the-product-of-an-array"],
    Simulation: ["rotate-array", "replace-elements-with-greatest-element-on-right-side"],
    "Two Pointers": ["two-sum-ii-input-array-is-sorted", "move-zeroes"],
    HashMap: ["two-sum", "majority-element"],
    Set: ["contains-duplicate", "longest-consecutive-sequence"],
    "Fixed Sliding Window": ["maximum-average-subarray-i", "maximum-number-of-vowels-in-a-substring-of-given-length"],
    "Variable Sliding Window": ["minimum-size-subarray-sum", "max-consecutive-ones-iii"],
    "Prefix Sum": ["range-sum-query-immutable", "find-pivot-index"],
    Kadane: ["maximum-subarray", "best-time-to-buy-and-sell-stock"],
    Sorting: ["largest-number", "h-index"],
    "Sorting + Two Pointers": ["3sum", "3sum-closest"],
    "In-place / Read-Write Pointer": ["remove-element", "remove-duplicates-from-sorted-array"],
    "Prefix + HashMap": ["subarray-sum-equals-k", "contiguous-array"],
    "Advanced Index Placement": ["first-missing-positive", "find-all-numbers-disappeared-in-an-array"],
  },
  "binary-search": { "Classic search": ["binary-search"], "Lower / upper bound": ["search-insert-position", "first-bad-version"], "Rotated array": ["search-in-rotated-sorted-array"], "Answer on a range": ["koko-eating-bananas"], "Matrix search": ["search-a-2d-matrix"], "Peak / boundary": ["find-peak-element"] },
  "two-pointers": { "Opposite ends": ["two-sum-ii-input-array-is-sorted"], "Same direction": ["remove-duplicates-from-sorted-array-ii"], "Fast and slow": ["linked-list-cycle"], "Three pointers after sort": ["3sum"], "Shrink a window from both sides": ["container-with-most-water"], Partition: ["sort-colors"] },
  "sliding-window": { "Fixed window": ["maximum-average-subarray-i"], "Variable longest": ["longest-substring-without-repeating-characters"], "Variable shortest": ["minimum-window-substring"], "Count of windows": ["count-number-of-nice-subarrays"], "Frequency window": ["permutation-in-string"], "Monotonic window": ["sliding-window-maximum"] },
  stack: { "Bracket matching": ["valid-parentheses"], "Min stack": ["min-stack"], "Next greater": ["daily-temperatures"], "Histogram area": ["largest-rectangle-in-histogram"], "Expression / calculator": ["basic-calculator-ii"] },
  "linked-list": { "Dummy head": ["remove-linked-list-elements"], Reverse: ["reverse-linked-list"], "Fast and slow": ["middle-of-the-linked-list"], "Merge sorted lists": ["merge-two-sorted-lists"], "Reorder / split": ["reorder-list"], "Design node": ["lru-cache"] },
  trees: { "DFS return value": ["maximum-depth-of-binary-tree"], "Level order": ["binary-tree-level-order-traversal"], "BST property": ["validate-binary-search-tree"], "Path through a node": ["binary-tree-maximum-path-sum"], "Build from traversals": ["construct-binary-tree-from-preorder-and-inorder-traversal"], "Parent and LCA": ["lowest-common-ancestor-of-a-binary-tree"] },
  graphs: { "Grid DFS / BFS": ["number-of-islands"], "Clone or copy": ["clone-graph"], "Shortest in an unweighted graph": ["word-ladder"], "Topological order": ["course-schedule-ii"], "Multi-source": ["rotting-oranges"] },
  "dp-1d": { "Climb / Fibonacci": ["climbing-stairs"], "House robber": ["house-robber"], "Coin change": ["coin-change"], "Decode / word break": ["decode-ways", "word-break"], LIS: ["longest-increasing-subsequence"], "Kadane as DP": ["maximum-product-subarray"] },
  "dp-2d": { "Grid paths": ["unique-paths"], "Two strings": ["longest-common-subsequence", "edit-distance"], Knapsack: ["ones-and-zeroes"], "Intervals / ranges": ["burst-balloons"], "Palindrome span": ["longest-palindromic-subsequence"] },
};

/** Additional patterns for the existing sheets. */
export const MORE_PATTERNS = {
  basics: [
    row("Brute force first", "Any problem where the optimal idea is not obvious yet.", "two sum by nested loops, all pairs", "O(n^2) as a baseline", "What is the slow but correct answer, and where does it repeat work?", ["two-sum"]),
    row("Digit loop", "The input is a single integer and you need its digits.", "reverse integer, palindrome number, happy number", "O(digits)", "Can n % 10 and Math.floor(n / 10) peel one digit per step?", ["reverse-integer", "palindrome-number"]),
    row("Constraint to complexity", "n is given in the constraints.", "n <= 1e5 means O(n log n); n <= 20 means 2^n", "read n first", "Which complexity class fits inside about 1e8 simple operations?"),
    row("Counting with a sieve", "Many primality or divisor questions up to n.", "count primes", "O(n log log n)", "Can I cross out multiples once instead of testing each number?", ["count-primes"]),
    row("Math shortcut", "A formula replaces a loop.", "trailing zeroes, power of two, sum 1..n", "O(1) or O(log n)", "Is there a known identity, like counting factors of 5?", ["factorial-trailing-zeroes", "power-of-two"]),
  ],
  sorting: [
    row("Quick select", "Need the kth element, not a fully sorted array.", "kth largest, k closest", "O(n) average", "Can I partition around a pivot and recurse into one side only?", ["kth-largest-element-in-an-array"]),
    row("Merge sort counting", "Count inversions or pairs while sorting.", "reverse pairs, count of smaller after self", "O(n log n)", "Can I count cross pairs during the merge step?", ["reverse-pairs", "count-of-smaller-numbers-after-self"]),
    row("Cyclic sort", "Values are 1..n (or 0..n) and indexes can hold them.", "missing number, find duplicates", "O(n), O(1) extra", "Can I swap each value into index value - 1?", ["find-all-duplicates-in-an-array", "missing-number"]),
    row("Sort by frequency", "Order elements by how often they appear.", "sort characters by frequency, top k words", "O(n log n) or bucket O(n)", "Count first, then sort the keys or bucket by count?", ["sort-characters-by-frequency"]),
    row("Relative / custom order", "A second array or a rank decides the order.", "relative sort array, custom sort string", "O(n log n)", "Can I map each value to its rank, then compare ranks?", ["relative-sort-array", "custom-sort-string"]),
  ],
  "binary-search": [
    row("First and last position", "Sorted input with duplicates; need a range.", "find first and last position", "O(log n)", "Run two bound searches: first >= target and first > target?", ["find-first-and-last-position-of-element-in-sorted-array"]),
    row("Square root / integer answer", "Find the largest integer x with f(x) <= target.", "sqrt(x), valid perfect square, arranging coins", "O(log n)", "What are lo and hi, and is f monotonic?", ["sqrtx", "valid-perfect-square"]),
    row("Single element by parity", "Pairs are adjacent except one element.", "single element in a sorted array", "O(log n)", "Does the pair start at an even index left of the single?", ["single-element-in-a-sorted-array"]),
    row("Two arrays partition", "Median or kth across two sorted arrays.", "median of two sorted arrays", "O(log min(m, n))", "Which cut makes every left value <= every right value?", ["median-of-two-sorted-arrays"]),
    row("Minimize the maximum", "Split or distribute so the worst part is as small as possible.", "split array largest sum, ship packages, bouquets", "O(n log range)", "Given a cap, can I greedily check feasibility in O(n)?", ["split-array-largest-sum", "capacity-to-ship-packages-within-d-days"]),
  ],
  "two-pointers": [
    row("Merge two sorted arrays", "Two sorted inputs combine into one.", "merge sorted array, interval intersections", "O(m + n)", "Fill from the back when merging in place?", ["merge-sorted-array", "interval-list-intersections"]),
    row("Reverse in place", "Reverse a string, an array, or words.", "reverse string, reverse words", "O(n)", "Swap ends until the pointers meet?", ["reverse-string", "reverse-words-in-a-string"]),
    row("Subsequence check", "Is one sequence inside another in order?", "is subsequence, merge strings alternately", "O(n + m)", "Advance the short pointer only on a match?", ["is-subsequence"]),
    row("Palindrome with one skip", "A palindrome check that tolerates one mismatch.", "valid palindrome II", "O(n)", "On the first mismatch, try skipping either side once?", ["valid-palindrome-ii"]),
    row("Greedy pairing after sort", "Pair the lightest with the heaviest.", "boats to save people, k-sum pairs", "O(n log n)", "If the heaviest cannot pair with the lightest, can it pair with anyone?", ["boats-to-save-people"]),
  ],
  "sliding-window": [
    row("At most K distinct", "Longest window with at most k kinds of values.", "fruit into baskets, at most k distinct", "O(n)", "Keep a count map; shrink while it has more than k keys?", ["fruit-into-baskets"]),
    row("Exactly K via two windows", "Count windows with exactly k of something.", "subarrays with k different integers, binary subarrays with sum", "O(n)", "exactly(k) = atMost(k) - atMost(k - 1)?", ["subarrays-with-k-different-integers", "binary-subarrays-with-sum"]),
    row("Window on the complement", "Remove a prefix and suffix; keep the middle.", "minimum operations to reduce x to zero, max points from cards", "O(n)", "Is it easier to find the longest middle window with sum total - x?", ["minimum-operations-to-reduce-x-to-zero", "maximum-points-you-can-obtain-from-cards"]),
    row("Product window", "Count subarrays with product below k.", "subarray product less than k", "O(n)", "Each right end adds right - left + 1 new subarrays?", ["subarray-product-less-than-k"]),
    row("Circular window", "The array wraps around.", "minimum swaps to group all 1s II", "O(n)", "Can I loop to 2n and use index % n?", ["minimum-swaps-to-group-all-1s-together-ii"]),
  ],
  stack: [
    row("Previous smaller / span", "For each day, how far back is the value smaller or equal?", "online stock span, sum of subarray minimums", "O(n) amortized", "Does each element pop the ones it dominates?", ["online-stock-span", "sum-of-subarray-minimums"]),
    row("Adjacent cancellation", "Neighbouring pairs remove each other.", "remove adjacent duplicates, asteroid collision, make the string great", "O(n)", "Does the new item cancel with the stack top?", ["asteroid-collision", "remove-all-adjacent-duplicates-in-string"]),
    row("Nested decode", "Brackets wrap repeated or nested content.", "decode string, score of parentheses", "O(n)", "Push the current state when you see an opener, pop on the closer?", ["decode-string", "score-of-parentheses"]),
    row("Greedy digit removal", "Make the smallest number by removing k digits.", "remove k digits, remove duplicate letters", "O(n)", "Pop while the top is larger and removals remain?", ["remove-k-digits", "remove-duplicate-letters"]),
    row("Queue with two stacks", "Implement FIFO using LIFO pieces.", "implement queue using stacks", "O(1) amortized", "Move items to the out stack only when it is empty?", ["implement-queue-using-stacks"]),
  ],
  "linked-list": [
    row("Kth from the end", "Remove or find a node counted from the tail.", "remove nth node from end", "O(n)", "Start the fast pointer n steps ahead?", ["remove-nth-node-from-end-of-list"]),
    row("Cycle start", "Find where the cycle begins, not just if it exists.", "linked list cycle II, find the duplicate number", "O(n), O(1) extra", "After meeting, reset one pointer to head and step both by one?", ["linked-list-cycle-ii", "find-the-duplicate-number"]),
    row("Add numbers as lists", "Digits are stored in list nodes.", "add two numbers, add two numbers II", "O(n)", "Carry forward, or reverse first if digits are most-significant first?", ["add-two-numbers", "add-two-numbers-ii"]),
    row("Reverse in groups", "Reverse every k nodes or a sublist.", "reverse nodes in k-group, reverse linked list II", "O(n)", "Can I reverse a segment and reconnect its two ends?", ["reverse-nodes-in-k-group", "reverse-linked-list-ii"]),
    row("Copy with extra pointers", "Nodes carry random or child pointers.", "copy list with random pointer, flatten multilevel list", "O(n)", "Map old to new nodes, or interleave copies in the list?", ["copy-list-with-random-pointer"]),
  ],
  bits: [
    row("XOR of a range", "Prefix XOR answers range queries.", "xor queries of a subarray", "O(n + q)", "Does prefix[r + 1] ^ prefix[l] give the range XOR?", ["xor-queries-of-a-subarray"]),
    row("Split by a set bit", "Two unique numbers among pairs.", "single number III", "O(n)", "Can the lowest set bit of a ^ b separate the two groups?", ["single-number-iii"]),
    row("Count bits per position", "Every number appears three times except one.", "single number II", "O(32n)", "Can I sum each bit position modulo 3?", ["single-number-ii"]),
    row("Hamming distance", "Count bit differences between numbers.", "hamming distance, minimum bit flips", "O(32)", "XOR them, then count the set bits?", ["hamming-distance", "minimum-bit-flips-to-convert-number"]),
    row("Common prefix of a range", "AND of every number in [m, n].", "bitwise AND of numbers range", "O(32)", "Shift both right until they are equal, then shift back?", ["bitwise-and-of-numbers-range"]),
  ],
  backtracking: [
    row("Duplicates in input", "The input has repeated values but the output must be unique.", "subsets II, permutations II, combination sum II", "O(2^n) or O(n!)", "Sort, then skip a value equal to the previous one at the same depth?", ["subsets-ii", "permutations-ii"]),
    row("Constraint placement", "Place items so no two attack or conflict.", "n-queens, sudoku solver", "exponential, pruned", "Which sets (columns, diagonals, boxes) tell me a placement is illegal?", ["n-queens", "sudoku-solver"]),
    row("String segmentation", "Split a string into valid parts.", "restore IP addresses, word break II", "exponential", "What makes one segment valid, and how many segments may remain?", ["restore-ip-addresses", "word-break-ii"]),
    row("Equal-sum buckets", "Split numbers into k groups with equal sums.", "partition to k equal sum subsets, matchsticks to square", "O(k * 2^n)", "Sort descending and skip identical empty buckets?", ["partition-to-k-equal-sum-subsets", "matchsticks-to-square"]),
    row("Expression building", "Insert operators or brackets to hit a target.", "expression add operators, generate parentheses", "exponential", "What must I carry (current value, last operand) to undo multiplication?", ["expression-add-operators", "generate-parentheses"]),
  ],
  heap: [
    row("Kth largest in a stream", "Values arrive one at a time; keep the kth largest.", "kth largest element in a stream", "O(log k) per add", "Keep a min-heap of size k; its top is the answer?", ["kth-largest-element-in-a-stream"]),
    row("Frequency top k", "Most frequent k items.", "top k frequent elements, top k frequent words", "O(n log k)", "Count first, then keep a heap of size k, or bucket by count?", ["top-k-frequent-elements", "top-k-frequent-words"]),
    row("Rearrange with gaps", "No two equal items may be adjacent.", "reorganize string, task scheduler", "O(n log k)", "Always place the most frequent remaining item that is allowed?", ["reorganize-string", "task-scheduler"]),
    row("Greedy with regret", "Spend a resource now, take it back later if needed.", "furthest building, refueling stops, IPO", "O(n log n)", "Push every choice, and pop the worst when you run out?", ["furthest-building-you-can-reach", "minimum-number-of-refueling-stops"]),
    row("Generate in order", "Produce the nth smallest of a generated sequence.", "ugly number II, k pairs with smallest sums", "O(n log n)", "Pop the smallest, push its successors, skip duplicates?", ["ugly-number-ii", "find-k-pairs-with-smallest-sums"]),
  ],
  greedy: [
    row("Sort and assign", "Match two lists with the cheapest or most valid pairing.", "assign cookies, two city scheduling, boats", "O(n log n)", "Sorted, does the smallest need go to the smallest supply?", ["assign-cookies", "two-city-scheduling"]),
    row("Balance counter", "Brackets or change must never go negative.", "valid parenthesis string, lemonade change", "O(n)", "Can a min and max count of open brackets bound the answer?", ["valid-parenthesis-string", "lemonade-change"]),
    row("Two-pass greedy", "Each element depends on both neighbours.", "candy, trapping rain water", "O(n)", "Pass left to right, then right to left, and take the max?", ["candy"]),
    row("Largest number / digits", "Build the best number by choosing digits.", "maximum swap, largest number", "O(n) or O(n log n)", "Which digit, moved where, raises the most significant place?", ["maximum-swap", "largest-number"]),
    row("Cover a range", "Pick the fewest intervals or taps to cover a line.", "video stitching, minimum taps", "O(n log n)", "From the current end, which option reaches farthest?", ["video-stitching", "minimum-number-of-taps-to-open-to-water-a-garden"]),
  ],
  trees: [
    row("Iterative traversal", "Recursion is not allowed or the tree is deep.", "inorder, preorder, postorder iteratively", "O(n)", "What does the explicit stack hold, and when do I visit?", ["binary-tree-inorder-traversal", "binary-tree-postorder-traversal"]),
    row("Root-to-leaf paths", "Every answer is a path from the root.", "path sum II, binary tree paths, sum root to leaf", "O(n * h)", "Carry the path down, record at a leaf, then backtrack?", ["path-sum-ii", "binary-tree-paths"]),
    row("Prefix sum on paths", "Count downward paths with a target sum.", "path sum III", "O(n)", "Can a map of prefix sums on the current path count matches?", ["path-sum-iii"]),
    row("Views and widths", "Right side view, vertical order, or max width.", "right side view, vertical order, maximum width", "O(n)", "Do I need a level, a column, or an index per node?", ["binary-tree-right-side-view", "maximum-width-of-binary-tree"]),
    row("Serialize / compare", "Encode a tree or detect equal subtrees.", "serialize and deserialize, find duplicate subtrees", "O(n)", "Which traversal with null markers rebuilds the tree uniquely?", ["serialize-and-deserialize-binary-tree", "find-duplicate-subtrees"]),
  ],
  tries: [
    row("Autocomplete", "Return suggestions for each typed prefix.", "search suggestions system", "O(total chars)", "Store the top suggestions at each node, or DFS from the prefix?", ["search-suggestions-system"]),
    row("Replace with roots", "Swap each word for its shortest dictionary prefix.", "replace words", "O(total chars)", "Stop at the first end mark while walking the word?", ["replace-words"]),
    row("Sum or value at prefix", "Aggregate values for every key with a prefix.", "map sum pairs", "O(key length)", "Update a running sum on every node of the path?", ["map-sum-pairs"]),
    row("Reverse trie for suffixes", "Queries ask about the last characters typed.", "stream of characters", "O(max word length) per query", "Insert words reversed and walk the stream backwards?", ["stream-of-characters"]),
    row("Trie plus DP", "Split a string into dictionary words.", "extra characters in a string, concatenated words", "O(n^2)", "From each start, walk the trie to find every word that begins there?", ["extra-characters-in-a-string", "concatenated-words"]),
  ],
  graphs: [
    row("Bipartite check", "Split nodes into two groups with no edge inside a group.", "is graph bipartite, possible bipartition", "O(V + E)", "Colour by BFS and fail when a neighbour has the same colour?", ["is-graph-bipartite", "possible-bipartition"]),
    row("Connected components", "Count groups or islands of connected nodes.", "number of provinces, count sub-islands", "O(V + E)", "Start a DFS from every unvisited node and count the starts?", ["number-of-provinces", "count-sub-islands"]),
    row("Border flood fill", "Cells connected to the edge are special.", "surrounded regions, number of enclaves, pacific atlantic", "O(mn)", "Flood from the border first, then everything left is enclosed?", ["surrounded-regions", "pacific-atlantic-water-flow"]),
    row("State BFS", "A move changes more than the position (keys, locks, words).", "open the lock, word ladder, snakes and ladders", "O(states)", "What exactly is one state, and how many can there be?", ["open-the-lock", "snakes-and-ladders"]),
    row("Safe nodes / reverse graph", "Nodes that never reach a cycle.", "find eventual safe states", "O(V + E)", "Reverse the edges and run Kahn's algorithm from terminal nodes?", ["find-eventual-safe-states"]),
  ],
  "advanced-graphs": [
    row("Floyd-Warshall", "All-pairs shortest paths with small V.", "city with the smallest number of neighbours", "O(V^3)", "Is V small enough (about 100) for three nested loops?", ["find-the-city-with-the-smallest-number-of-neighbors-at-a-threshold-distance"]),
    row("Eulerian path", "Use every edge exactly once.", "reconstruct itinerary", "O(E log E)", "Hierholzer: DFS, append on the way back, then reverse?", ["reconstruct-itinerary"]),
    row("Bridges and articulation", "Edges whose removal disconnects the graph.", "critical connections in a network", "O(V + E)", "Track discovery time and low-link with Tarjan's algorithm?", ["critical-connections-in-a-network"]),
    row("Shortest path counting", "Count the number of shortest routes.", "number of ways to arrive at destination", "O(E log V)", "In Dijkstra, add ways on ties and reset on improvement?", ["number-of-ways-to-arrive-at-destination"]),
    row("Minimax path", "Minimise the maximum edge or effort on a path.", "swim in rising water, path with minimum effort", "O(E log V)", "Dijkstra on max-so-far, or binary search plus BFS?", ["swim-in-rising-water", "path-with-minimum-effort"]),
  ],
  "dp-1d": [
    row("Partition subset sum", "Can the array split into equal sums?", "partition equal subset sum, target sum", "O(n * sum)", "Is this a 0/1 knapsack over reachable sums?", ["partition-equal-subset-sum", "target-sum"]),
    row("Stock with states", "Buy and sell with cooldown or fees.", "stock with cooldown, stock with fee", "O(n)", "What are the states (holding, sold, resting) and their transitions?", ["best-time-to-buy-and-sell-stock-with-cooldown", "best-time-to-buy-and-sell-stock-with-transaction-fee"]),
    row("Count the ways", "Number of ways to form a total or a string.", "combination sum IV, count good strings", "O(n * choices)", "Does order matter? If yes, loop the total outside the choices.", ["combination-sum-iv", "count-ways-to-build-good-strings"]),
    row("Palindromic expansion", "Longest or count of palindromic substrings.", "longest palindromic substring, palindromic substrings", "O(n^2)", "Expand around every centre, both odd and even?", ["longest-palindromic-substring", "palindromic-substrings"]),
    row("Skip ahead choice", "Take an item and jump past some next items.", "solving questions with brainpower, delete and earn", "O(n)", "Is dp[i] = max(skip, take + dp[next allowed])?", ["solving-questions-with-brainpower", "delete-and-earn"]),
  ],
  "dp-2d": [
    row("Square / rectangle in a grid", "Largest all-ones square or count of squares.", "maximal square, count square submatrices", "O(mn)", "Is dp[i][j] = 1 + min(top, left, diagonal)?", ["maximal-square", "count-square-submatrices-with-all-ones"]),
    row("Wildcard / regex", "Pattern matching with * and ? or .", "wildcard matching, regular expression matching", "O(mn)", "What does * match: zero characters or one more?", ["wildcard-matching", "regular-expression-matching"]),
    row("Game theory DP", "Two players play optimally.", "stone game, predict the winner", "O(n^2)", "Store the score difference for the player to move?", ["stone-game", "predict-the-winner"]),
    row("Path with obstacles / costs", "Grid paths with blocks or weights.", "unique paths II, minimum path sum, dungeon game", "O(mn)", "Which direction should the DP fill so dependencies are ready?", ["unique-paths-ii", "minimum-path-sum", "dungeon-game"]),
    row("Probability DP", "Chance of staying in bounds or hitting a total.", "knight probability, dice rolls with target", "O(k * states)", "Do I sum probabilities over moves, one step at a time?", ["knight-probability-in-chessboard", "number-of-dice-rolls-with-target-sum"]),
  ],
  intervals: [
    row("Calendar booking", "Accept a booking only if it does not overlap.", "my calendar I, my calendar II", "O(n) or O(log n) per booking", "Keep sorted bookings and check neighbours, or a sweep map?", ["my-calendar-i", "my-calendar-ii"]),
    row("Covered intervals", "Remove intervals that sit inside another.", "remove covered intervals", "O(n log n)", "Sort by start asc, end desc, then track the max end?", ["remove-covered-intervals"]),
    row("Difference array", "Many range increments, then read capacities.", "car pooling, count days without meetings", "O(n + range)", "Add at start, subtract at end, then prefix-sum?", ["car-pooling", "count-days-without-meetings"]),
    row("Queries against intervals", "For each query point, find the best interval.", "minimum interval to include each query", "O((n + q) log n)", "Sort queries and intervals, and use a heap of active ends?", ["minimum-interval-to-include-each-query"]),
    row("Arrows / points", "Fewest points that hit every interval.", "minimum number of arrows to burst balloons", "O(n log n)", "Sort by end and shoot at the first end?", ["minimum-number-of-arrows-to-burst-balloons"]),
  ],
  "segment-tree": [
    row("Union-find with ranks", "Many merges and same-group queries.", "smallest string with swaps, similar string groups", "near O(1) per op", "Path compression plus union by rank?", ["smallest-string-with-swaps", "similar-string-groups"]),
    row("Count smaller after self", "For each element, count later smaller values.", "count of smaller numbers after self, reverse pairs", "O(n log n)", "Fenwick tree over compressed values, scanning right to left?", ["count-of-smaller-numbers-after-self"]),
    row("Coordinate compression", "Values are huge but there are few distinct ones.", "count of range sum, falling squares", "O(n log n)", "Map each distinct value to a small index first?", ["count-of-range-sum", "falling-squares"]),
    row("Point update, range query", "Values change and range sums are asked often.", "range sum query mutable", "O(log n) each", "Is a Fenwick tree enough, or do I need min/max (segment tree)?", ["range-sum-query-mutable"]),
    row("Grid union-find", "Cells merge into regions.", "regions cut by slashes, making a large island", "O(mn α)", "How do I number each cell (r * cols + c) for the parent array?", ["regions-cut-by-slashes", "making-a-large-island"]),
  ],
  math: [
    row("Big number strings", "Numbers do not fit in 64 bits.", "multiply strings, add binary, add strings", "O(mn) or O(n)", "Do I simulate the schoolbook method digit by digit?", ["multiply-strings", "add-binary"]),
    row("Base conversion", "Convert between bases or column titles.", "excel sheet column title / number", "O(log n)", "Is it 1-indexed (subtract one before each division)?", ["excel-sheet-column-title", "excel-sheet-column-number"]),
    row("Geometry checks", "Overlap, squares, or lines from coordinates.", "rectangle overlap, valid square, max points on a line", "O(1) to O(n^2)", "Can I compare squared distances or slopes as reduced fractions?", ["rectangle-overlap", "valid-square", "max-points-on-a-line"]),
    row("Random with weights", "Pick an index with probability proportional to weight.", "random pick with weight", "O(log n) per pick", "Prefix sums plus a binary search on a random value?", ["random-pick-with-weight"]),
    row("Cycle by simulation", "A process repeats; find if it is bounded.", "robot bounded in circle, happy number", "O(1) or O(log n)", "After one round (or a few), does the state repeat?", ["robot-bounded-in-circle", "happy-number"]),
  ],
  design: [
    row("Circular buffer", "Fixed-capacity queue with wrap-around.", "design circular queue", "O(1) per op", "Track head and size, and use modulo for the tail?", ["design-circular-queue"]),
    row("Browser history", "Back and forward over a list with truncation.", "design browser history", "O(1) per op", "Keep an array and a cursor; visiting truncates the forward part?", ["design-browser-history"]),
    row("Averages over trips", "Aggregate times between paired events.", "design underground system", "O(1) per op", "One map for open check-ins, one for route totals?", ["design-underground-system"]),
    row("Frequency buckets", "O(1) inc/dec and max/min key.", "all O(1) data structure, LFU cache", "O(1) per op", "A doubly linked list of count buckets, each with a key set?", ["all-oone-data-structure", "lfu-cache"]),
    row("Rating by category", "Highest-rated item per group with updates.", "food rating system, number container system", "O(log n) per op", "A heap per group with lazy deletion of stale entries?", ["design-a-food-rating-system", "design-a-number-container-system"]),
  ],
};

/** Additional decision-tree rows for the existing sheets. */
export const MORE_TREE = {
  basics: [choice("n <= 20 in the constraints?", "Exponential search is fine"), choice("n up to 1e5?", "Aim for O(n log n) or better"), choice("Single integer input?", "Digit loop or math shortcut"), choice("No idea yet?", "Say the brute force, then remove repeated work")],
  sorting: [choice("Need only the kth element?", "Quick select or a heap"), choice("Count pairs out of order?", "Merge sort counting"), choice("Values are exactly 1..n?", "Cyclic sort"), choice("Order by count?", "Count, then bucket sort")],
  "binary-search": [choice("Duplicates and need a range?", "Two bound searches"), choice("Integer root or largest x with f(x) <= t?", "Binary search on the value"), choice("Minimise the largest part?", "Binary search on the cap plus a greedy check"), choice("Two sorted arrays and a median?", "Partition search on the smaller array")],
  "two-pointers": [choice("Merging two sorted arrays in place?", "Fill from the back"), choice("Reverse in place?", "Swap ends inward"), choice("One sequence inside another in order?", "Subsequence pointers"), choice("Pair heaviest with lightest?", "Sort, then greedy pointers")],
  "sliding-window": [choice("At most k kinds?", "Count map, shrink past k keys"), choice("Exactly k?", "atMost(k) - atMost(k - 1)"), choice("Remove from both ends?", "Window on the middle instead"), choice("Array wraps around?", "Loop to 2n with modulo")],
  stack: [choice("Neighbours cancel each other?", "Stack with cancellation"), choice("Nested brackets with repeats?", "Push state on open, pop on close"), choice("Smallest number after removing digits?", "Greedy monotonic stack"), choice("FIFO from LIFO pieces?", "Two stacks")],
  "linked-list": [choice("Counted from the tail?", "Fast pointer n steps ahead"), choice("Where does the cycle start?", "Floyd, then reset one pointer"), choice("Digits stored in nodes?", "Carry, or reverse first"), choice("Reverse every k nodes?", "Reverse a segment and reconnect")],
  bits: [choice("Range XOR queries?", "Prefix XOR"), choice("Two unique numbers among pairs?", "Split by the lowest set bit"), choice("Everything appears three times but one?", "Count each bit mod 3"), choice("How many bits differ?", "XOR, then popcount")],
  backtracking: [choice("Input has duplicates?", "Sort and skip equal siblings"), choice("Placements must not conflict?", "Sets for columns and diagonals"), choice("Split a string into valid parts?", "Choose the next cut and validate"), choice("Equal-sum groups?", "Sort descending and prune buckets")],
  heap: [choice("Values arrive in a stream?", "Size-k min-heap"), choice("Most frequent k?", "Count, then heap or buckets"), choice("No two equal items adjacent?", "Max-heap of counts"), choice("Spend now, undo later?", "Greedy with a regret heap")],
  greedy: [choice("Match two lists?", "Sort both, pair smallest needs first"), choice("Must never go negative?", "Balance counter"), choice("Depends on both neighbours?", "Two passes"), choice("Cover a line with fewest pieces?", "Farthest reach from the current end")],
  trees: [choice("No recursion allowed?", "Iterative traversal with a stack"), choice("Answer is a root-to-leaf path?", "Carry the path and backtrack"), choice("Count downward paths with a sum?", "Prefix sums on the path"), choice("Need a view or width?", "BFS with level or index")],
  tries: [choice("Suggestions per typed prefix?", "Top suggestions per node"), choice("Shortest dictionary prefix?", "Stop at the first end mark"), choice("Queries about the latest characters?", "Reversed trie"), choice("Split into dictionary words?", "Trie plus DP")],
  graphs: [choice("Two groups with no inner edge?", "Bipartite colouring"), choice("Count groups?", "Components by DFS or union-find"), choice("Cells touching the border?", "Flood from the border first"), choice("A move changes more than position?", "BFS over full states")],
  "advanced-graphs": [choice("All pairs and V about 100?", "Floyd-Warshall"), choice("Use every edge once?", "Hierholzer"), choice("Edge whose removal disconnects?", "Tarjan bridges"), choice("Minimise the worst edge?", "Dijkstra on max-so-far")],
  "dp-1d": [choice("Split into equal sums?", "0/1 knapsack over sums"), choice("Buy and sell with rules?", "State machine DP"), choice("Count ordered ways to a total?", "Total outside, choices inside"), choice("Take one, skip some?", "dp[i] = max(skip, take + dp[next])")],
  "dp-2d": [choice("Largest all-ones square?", "1 + min of three neighbours"), choice("Pattern with * or ?", "Match DP over both strings"), choice("Two players, optimal play?", "Score difference DP"), choice("Probability over moves?", "Step-by-step probability DP")],
  intervals: [choice("Accept bookings without overlap?", "Sorted bookings or a sweep map"), choice("Remove intervals inside others?", "Sort start asc, end desc"), choice("Many range increments?", "Difference array"), choice("Fewest points hitting all?", "Sort by end, shoot at the end")],
  "segment-tree": [choice("Merge groups and ask same-group?", "Union-find"), choice("Count later smaller values?", "Fenwick tree over ranks"), choice("Huge values, few distinct?", "Coordinate compression first"), choice("Point updates and range sums?", "Fenwick tree")],
  math: [choice("Numbers bigger than 64 bits?", "Digit-by-digit strings"), choice("Base or column titles?", "Base conversion, watch 1-indexing"), choice("Weighted random choice?", "Prefix sums plus binary search"), choice("A process repeats?", "Simulate one round and check the state")],
  design: [choice("Fixed-size queue?", "Circular buffer"), choice("Back and forward navigation?", "Array plus a cursor"), choice("O(1) max and min key by count?", "Linked list of count buckets"), choice("Best item per group with updates?", "Heap per group with lazy deletion")],
};

/** A five-step interview workflow per sheet: the action, the usual mistake, and problems to practise it on. */
export const WORKFLOW = {
  basics: flow(
    step("Read the constraints and the output format before writing code", "Jumping to code without knowing n or the value range", ["two-sum", "reverse-integer"]),
    step("Translate n into a complexity budget out loud", "Writing O(n^2) when n is 1e5", ["count-primes", "power-of-two"]),
    step("State the brute force in one sentence", "Staying silent while searching for the clever idea", ["two-sum", "palindrome-number"]),
    step("Remove repeated work to reach the target complexity", "Optimising code that is already within budget", ["happy-number", "factorial-trailing-zeroes"]),
    step("Dry-run an empty, a single, and a large input", "Only testing the sample input", ["reverse-integer", "palindrome-number"]),
  ),
  sorting: flow(
    step("Ask whether order unlocks a simpler scan", "Sorting by reflex and losing the original indexes", ["merge-sorted-array", "h-index"]),
    step("Pick the sort: comparison, counting, or partition", "Using a comparison sort on a tiny value range", ["sort-colors", "relative-sort-array"]),
    step("Write the comparator and its tie-break", "Comparators that are not consistent (a < b and b < a)", ["largest-number", "custom-sort-string"]),
    step("Finish with a single linear pass", "Nested loops after the sort", ["h-index", "merge-sorted-array"]),
    step("Test duplicates, negatives, and already-sorted input", "Forgetting stability when ties matter", ["sort-an-array", "sort-colors"]),
  ),
  arrays: flow(
    step("Read constraints + output before coding", "Jumping to code without understanding limits", ["two-sum", "maximum-subarray"]),
    step("Circle the trigger words: sorted, contiguous, in-place, frequency, k", "Choosing a pattern from the topic name only", ["two-sum-ii-input-array-is-sorted", "remove-duplicates-from-sorted-array"]),
    step("State the pattern aloud", "Saying only 'I'll use a loop'", ["longest-substring-without-repeating-characters", "group-anagrams"]),
    step("Give brute force first, then optimize", "Pretending the optimized idea is obvious", ["3sum", "container-with-most-water"]),
    step("Test one normal + one edge case", "Only testing the happy path", ["move-zeroes", "rotate-array"]),
  ),
  "binary-search": flow(
    step("Find the monotonic property before searching", "Binary searching an unsorted or non-monotonic space", ["binary-search", "find-peak-element"]),
    step("Choose the search space: an index or an answer value", "Searching indexes when the answer is a value range", ["koko-eating-bananas", "sqrtx"]),
    step("Fix the loop invariant: lo <= hi or lo < hi", "Mixing invariants and looping forever", ["search-insert-position", "first-bad-version"]),
    step("Write the feasibility check as its own function", "Inlining a buggy greedy check", ["capacity-to-ship-packages-within-d-days", "minimum-number-of-days-to-make-m-bouquets"]),
    step("Test one element, two elements, and the target at each end", "Off-by-one at the boundaries", ["find-first-and-last-position-of-element-in-sorted-array", "search-in-rotated-sorted-array"]),
  ),
  "two-pointers": flow(
    step("Check for order or a pair structure", "Using two pointers on unsorted data that needs a map", ["two-sum-ii-input-array-is-sorted", "valid-palindrome"]),
    step("Name each pointer's role (left/right or read/write)", "Moving both pointers without a rule", ["remove-duplicates-from-sorted-array-ii", "move-zeroes"]),
    step("Say which pointer moves on each comparison and why", "Moving the wrong side and missing the answer", ["container-with-most-water", "3sum"]),
    step("Skip duplicates where the output must be unique", "Returning repeated triplets", ["3sum", "4sum"]),
    step("Test empty, all-equal, and already-done inputs", "Pointers crossing without a stop condition", ["squares-of-a-sorted-array", "reverse-string"]),
  ),
  "sliding-window": flow(
    step("Confirm the answer is contiguous", "Using a window for subsequences", ["longest-substring-without-repeating-characters", "maximum-average-subarray-i"]),
    step("Decide fixed size or variable size", "Shrinking a fixed window or never shrinking a variable one", ["maximum-average-subarray-i", "minimum-size-subarray-sum"]),
    step("Define what 'valid' means for the window state", "Recomputing the window from scratch each step", ["longest-repeating-character-replacement", "permutation-in-string"]),
    step("Record the answer at the right moment (before or after shrinking)", "Recording the best while the window is invalid", ["minimum-window-substring", "max-consecutive-ones-iii"]),
    step("Test k = 1, k = n, and no valid window", "Forgetting the empty answer", ["sliding-window-maximum", "fruit-into-baskets"]),
  ),
  stack: flow(
    step("Ask what is waiting for a match or a bigger/smaller value", "Reaching for a stack when a counter is enough", ["valid-parentheses", "daily-temperatures"]),
    step("Decide what to push: values, indexes, or pairs", "Pushing values when you need distances", ["daily-temperatures", "largest-rectangle-in-histogram"]),
    step("State the monotonic order kept in the stack", "Popping with the wrong comparison (< versus <=)", ["next-greater-element-i", "online-stock-span"]),
    step("Handle what is left on the stack at the end", "Forgetting the elements that never got popped", ["largest-rectangle-in-histogram", "next-greater-element-ii"]),
    step("Test empty input, all increasing, and all decreasing", "Only testing a mixed sample", ["min-stack", "asteroid-collision"]),
  ),
  "linked-list": flow(
    step("Draw the list and the pointers before coding", "Rewiring in your head and losing a node", ["reverse-linked-list", "reorder-list"]),
    step("Add a dummy head when the head may change", "Special-casing the head in three places", ["remove-linked-list-elements", "merge-two-sorted-lists"]),
    step("Save next before you rewire", "Overwriting next and cutting the list", ["reverse-linked-list", "swap-nodes-in-pairs"]),
    step("Use fast/slow for middle, cycle, and kth-from-end", "Counting the length in a separate pass every time", ["middle-of-the-linked-list", "linked-list-cycle-ii"]),
    step("Test empty, one node, and two nodes", "Null pointer on the shortest lists", ["remove-nth-node-from-end-of-list", "palindrome-linked-list"]),
  ),
  bits: flow(
    step("Ask whether parity, uniqueness, or flags are the real question", "Using bits where a map is clearer", ["single-number", "missing-number"]),
    step("Write the bit identities you need (x & (x - 1), x ^ x = 0)", "Guessing operator precedence without brackets", ["number-of-1-bits", "power-of-two"]),
    step("Mind signed versus unsigned shifts", "Using >> when >>> was needed in JavaScript", ["reverse-bits", "number-of-1-bits"]),
    step("Combine with prefix XOR or masks when there are many queries", "Recomputing XOR per query", ["xor-queries-of-a-subarray", "counting-bits"]),
    step("Test 0, negative numbers, and the 32-bit edge", "Ignoring negative input", ["sum-of-two-integers", "hamming-distance"]),
  ),
  backtracking: flow(
    step("Name the choice at each level and the stop condition", "Recursing without a clear base case", ["subsets", "permutations"]),
    step("Draw the decision tree for a tiny input", "Missing or duplicating branches", ["combinations", "letter-combinations-of-a-phone-number"]),
    step("Choose, recurse, then undo", "Forgetting to restore state after the call", ["word-search", "n-queens"]),
    step("Prune early with sorting or running sums", "Exploring branches that already exceed the target", ["combination-sum", "combination-sum-ii"]),
    step("State the complexity (2^n, n!, k^n)", "Claiming polynomial time for an exponential search", ["subsets-ii", "palindrome-partitioning"]),
  ),
  heap: flow(
    step("Ask whether you need the best of k, not a full order", "Sorting everything for a top-k question", ["kth-largest-element-in-an-array", "k-closest-points-to-origin"]),
    step("Pick min-heap or max-heap and its size", "Keeping a max-heap of size k for the k largest", ["kth-largest-element-in-a-stream", "top-k-frequent-elements"]),
    step("Define the heap key (value, time, distance)", "Comparing the wrong field", ["k-closest-points-to-origin", "single-threaded-cpu"]),
    step("Plan deletions: pop, or lazy delete stale entries", "Searching the heap to delete an item", ["sliding-window-median", "find-median-from-data-stream"]),
    step("Test k = 1, k = n, and ties", "Unstable results on equal keys", ["top-k-frequent-words", "task-scheduler"]),
  ),
  greedy: flow(
    step("State the local choice you want to make", "Greedy without saying the rule", ["jump-game", "assign-cookies"]),
    step("Sort by the field that makes the choice safe", "Sorting by start when end is what matters", ["non-overlapping-intervals", "maximum-length-of-pair-chain"]),
    step("Argue why the choice never hurts (exchange argument)", "Assuming greedy works without a reason", ["gas-station", "two-city-scheduling"]),
    step("Try a counterexample before coding", "Missing the case where DP is needed", ["jump-game-ii", "candy"]),
    step("Test ties and the smallest inputs", "Failing when two options are equal", ["lemonade-change", "hand-of-straights"]),
  ),
  trees: flow(
    step("Decide what each subtree returns to its parent", "Using global variables for everything", ["maximum-depth-of-binary-tree", "balanced-binary-tree"]),
    step("Pick the traversal: pre, in, post, or level order", "Using BFS when the answer needs subtree results", ["binary-tree-level-order-traversal", "diameter-of-binary-tree"]),
    step("Separate the answer you return from the answer you record", "Returning both branches of a path upward", ["binary-tree-maximum-path-sum", "diameter-of-binary-tree"]),
    step("Use BST bounds when values are ordered", "Checking only a node and its children", ["validate-binary-search-tree", "kth-smallest-element-in-a-bst"]),
    step("Test null, a single node, and a skewed tree", "Stack overflow on a deep tree", ["invert-binary-tree", "same-tree"]),
  ),
  tries: flow(
    step("Ask whether many words share prefixes", "Building a trie when a set is enough", ["implement-trie-prefix-tree", "longest-word-in-dictionary"]),
    step("Define the node: children map or array, plus end mark", "Forgetting the end mark and matching prefixes as words", ["implement-trie-prefix-tree", "replace-words"]),
    step("Store extra data on nodes (counts, best word)", "Re-walking the trie for every query", ["search-suggestions-system", "map-sum-pairs"]),
    step("Walk the trie together with the input (board, stream)", "Searching each word separately", ["word-search-ii", "stream-of-characters"]),
    step("Test the empty string and words that are prefixes of others", "Deleting shared prefixes", ["design-add-and-search-words-data-structure", "palindrome-pairs"]),
  ),
  graphs: flow(
    step("Name the nodes and the edges", "Starting BFS before defining a node", ["number-of-islands", "course-schedule"]),
    step("Pick BFS for shortest steps, DFS for reachability", "Using DFS for an unweighted shortest path", ["rotting-oranges", "word-ladder"]),
    step("Mark visited when you enqueue, not when you pop", "Visiting the same node many times", ["shortest-path-in-binary-matrix", "01-matrix"]),
    step("Handle directed cycles and disconnected parts", "Running one DFS and missing components", ["course-schedule-ii", "number-of-provinces"]),
    step("Test an empty grid, one cell, and no path", "Returning 0 when the answer is -1", ["flood-fill", "nearest-exit-from-entrance-in-maze"]),
  ),
  "advanced-graphs": flow(
    step("Check the weights: none, 0/1, positive, or negative", "Running Dijkstra with negative edges", ["network-delay-time", "cheapest-flights-within-k-stops"]),
    step("Pick the algorithm that fits (Dijkstra, Bellman-Ford, union-find, MST)", "BFS on a weighted graph", ["min-cost-to-connect-all-points", "path-with-minimum-effort"]),
    step("Put extra constraints into the state (stops, keys)", "Ignoring the limit on stops", ["cheapest-flights-within-k-stops", "shortest-path-visiting-all-nodes"]),
    step("Skip stale heap entries", "Processing a node again with a worse distance", ["network-delay-time", "path-with-maximum-probability"]),
    step("Test unreachable nodes and a single node", "Returning Infinity instead of -1", ["number-of-operations-to-make-network-connected", "swim-in-rising-water"]),
  ),
  "dp-1d": flow(
    step("Define dp[i] in one sentence", "Writing loops before the state is clear", ["climbing-stairs", "house-robber"]),
    step("Write the recurrence and the base cases", "Wrong base case for i = 0 or 1", ["coin-change", "decode-ways"]),
    step("Start with memoised recursion if the order is unclear", "Filling a table in the wrong order", ["word-break", "partition-equal-subset-sum"]),
    step("Reduce memory to a few variables when possible", "Keeping a full array you never reread", ["climbing-stairs", "house-robber-ii"]),
    step("Test n = 0, n = 1, and an impossible target", "Returning 0 when the answer is -1", ["coin-change", "longest-increasing-subsequence"]),
  ),
  "dp-2d": flow(
    step("Define dp[i][j] and what i and j mean", "Mixing up prefix length and index", ["longest-common-subsequence", "unique-paths"]),
    step("List the choices at each cell (match, insert, delete, skip)", "Missing one transition", ["edit-distance", "interleaving-string"]),
    step("Pick the fill order so dependencies are ready", "Reading a cell before it is computed", ["burst-balloons", "longest-palindromic-subsequence"]),
    step("Compress to one row when only the previous row is needed", "Overwriting values still in use", ["unique-paths", "minimum-path-sum"]),
    step("Test empty strings and a 1 x 1 grid", "Index errors on empty input", ["distinct-subsequences", "maximal-square"]),
  ),
  intervals: flow(
    step("Sort by start (merge) or by end (choose most)", "Sorting by the wrong field", ["merge-intervals", "non-overlapping-intervals"]),
    step("Define overlap: touching ends count or not", "Off-by-one on [1,2] and [2,3]", ["merge-intervals", "meeting-rooms-iii"]),
    step("Keep one running interval or a heap of end times", "Comparing every pair", ["insert-interval", "car-pooling"]),
    step("Use a sweep line when many intervals overlap at once", "Simulating minute by minute", ["my-calendar-ii", "car-pooling"]),
    step("Test empty input, nested intervals, and identical intervals", "Dropping a fully covered interval incorrectly", ["remove-covered-intervals", "minimum-number-of-arrows-to-burst-balloons"]),
  ),
  "segment-tree": flow(
    step("Check whether prefix sums already solve it", "Building a segment tree for static data", ["range-sum-query-immutable", "range-sum-query-mutable"]),
    step("List the operations: point or range update, sum or min query", "Picking a Fenwick tree for range minimum", ["range-sum-query-mutable", "falling-squares"]),
    step("Compress coordinates when values are large", "Allocating a tree of size 1e9", ["count-of-smaller-numbers-after-self", "count-of-range-sum"]),
    step("For groups, use union-find with path compression", "Re-running DFS after every merge", ["smallest-string-with-swaps", "regions-cut-by-slashes"]),
    step("Test one element and updates at both ends", "Off-by-one in 1-indexed Fenwick trees", ["reverse-pairs", "longest-increasing-subsequence-ii"]),
  ),
  math: flow(
    step("Look for a formula or invariant before simulating", "Simulating a billion steps", ["factorial-trailing-zeroes", "angle-between-hands-of-a-clock"]),
    step("Check overflow and use modulo where asked", "Applying modulo only at the end", ["powx-n", "multiply-strings"]),
    step("Handle signs and zero explicitly", "Wrong answer for negative input", ["reverse-integer", "fraction-to-recurring-decimal"]),
    step("For geometry, compare squared distances or cross products", "Floating point equality checks", ["valid-square", "max-points-on-a-line"]),
    step("Test 0, 1, the maximum value, and negatives", "Only testing positive mid-range numbers", ["add-binary", "excel-sheet-column-title"]),
  ),
  design: flow(
    step("List every operation and its required complexity", "Choosing structures before knowing the operations", ["lru-cache", "min-stack"]),
    step("Pick one structure per operation, then combine", "Forcing one structure to do everything", ["lru-cache", "insert-delete-getrandom-o1"]),
    step("Keep the structures in sync on every update", "Updating the map but not the list", ["lru-cache", "lfu-cache"]),
    step("Walk through a sequence of calls on paper", "Testing only one method at a time", ["design-browser-history", "time-based-key-value-store"]),
    step("Test capacity 1, repeated keys, and empty reads", "Crashing on get before any put", ["design-circular-queue", "snapshot-array"]),
  ),
};

/** Topics that had no sheet before. */
export const NEW_SHEETS = [
  {
    id: "recursion",
    title: "Recursion",
    after: "sorting",
    description: "Trust the function on a smaller input. Every recursive answer is a base case plus one step that uses the smaller answer.",
    patterns: [
      row("Base case + smaller problem", "The answer for n is built from the answer for n - 1 or n / 2.", "fibonacci, factorial, power", "O(n) or O(log n)", "What is the smallest input I can answer directly?", ["fibonacci-number", "powx-n"]),
      row("Head versus tail recursion", "Work happens before or after the recursive call.", "print 1..n, print n..1, reverse a list", "O(n)", "Should I act before or after the call returns?", ["reverse-linked-list"]),
      row("Divide and conquer", "Split the input in halves and combine.", "merge sort, max subarray (D&C), power", "O(n log n)", "How do I combine the two half answers?", ["sort-an-array", "powx-n"]),
      row("Recursion on trees", "Each node asks its children, then combines.", "max depth, same tree, invert tree", "O(n)", "What does each child return to its parent?", ["maximum-depth-of-binary-tree", "invert-binary-tree"]),
      row("Take or skip", "Every element is either in or out of the answer.", "subsets, subsequences with sum k", "O(2^n)", "What are the two calls, and what changes between them?", ["subsets", "target-sum"]),
      row("Generate with constraints", "Build strings or lists that must stay valid.", "generate parentheses, letter combinations", "exponential", "Which constraint lets me stop a branch early?", ["generate-parentheses", "letter-combinations-of-a-phone-number"]),
      row("Memoised recursion", "The same arguments are computed many times.", "climbing stairs, decode ways, word break", "O(states)", "Which arguments define the state, and can I cache them?", ["climbing-stairs", "decode-ways"]),
      row("Recursion on strings", "Peel one character or a prefix each call.", "palindrome check, string reverse, atoi", "O(n)", "Do I pass an index instead of slicing the string?", ["valid-palindrome", "string-to-integer-atoi"]),
      row("Mutual / nested recursion", "Grammar-like input such as nested brackets.", "decode string, basic calculator", "O(n)", "Can each call parse one level and return where it stopped?", ["decode-string", "basic-calculator"]),
      row("Recursion to iteration", "Deep input risks a stack overflow.", "tree traversals, flood fill on a big grid", "O(n) with an explicit stack", "What would the explicit stack hold if I removed the recursion?", ["binary-tree-inorder-traversal", "flood-fill"]),
    ],
    decisionTree: [
      choice("Answer for n uses the answer for n - 1?", "Simple recursion"),
      choice("Split into halves?", "Divide and conquer"),
      choice("Each element in or out?", "Take or skip"),
      choice("Same arguments repeat?", "Memoise, then think DP"),
      choice("Output must stay valid while building?", "Generate with pruning"),
      choice("Nested brackets in the input?", "Recursive descent parser"),
      choice("Input deep enough to overflow?", "Explicit stack"),
      choice("Tree or graph input?", "Recurse on children"),
    ],
    workflow: flow(
      step("Write the function signature and what it promises", "Starting with the loop body instead of the contract", ["fibonacci-number", "maximum-depth-of-binary-tree"]),
      step("Write the base case first", "Missing a base case and recursing forever", ["powx-n", "climbing-stairs"]),
      step("Assume the smaller call works and use its result", "Tracing every level in your head", ["reverse-linked-list", "invert-binary-tree"]),
      step("Draw the recursion tree to find repeated work", "Exponential time from overlapping calls", ["climbing-stairs", "decode-ways"]),
      step("State time and stack depth", "Ignoring the O(n) stack space", ["subsets", "generate-parentheses"]),
    ),
  },
  {
    id: "hashing",
    title: "Hashing",
    after: "arrays",
    description: "Trade memory for time. A map answers 'have I seen this, and what did I learn about it' in O(1) on average.",
    patterns: [
      row("Complement lookup", "Need a pair that sums or matches a target.", "two sum, pairs with difference k", "O(n)", "For each value, which partner would finish the answer?", ["two-sum"]),
      row("Frequency count", "The answer depends on how often values appear.", "valid anagram, majority element, first unique char", "O(n)", "Count first, then read the counts?", ["valid-anagram", "majority-element"]),
      row("Grouping by key", "Items that share a signature belong together.", "group anagrams, group shifted strings", "O(n * k)", "What canonical key makes equal items collide?", ["group-anagrams"]),
      row("Seen set", "Only existence matters.", "contains duplicate, happy number, intersection", "O(n)", "Do I need counts, or is membership enough?", ["contains-duplicate", "happy-number"]),
      row("Last seen index", "Distance between equal values matters.", "contains duplicate II, longest substring without repeat", "O(n)", "Store the latest index of each value?", ["contains-duplicate-ii", "longest-substring-without-repeating-characters"]),
      row("Prefix sum + map", "Count subarrays with an exact sum or remainder.", "subarray sum equals k, subarray sums divisible by k", "O(n)", "How many earlier prefixes equal current - k?", ["subarray-sum-equals-k", "subarray-sums-divisible-by-k"]),
      row("Bijection maps", "Two sequences must map one-to-one.", "isomorphic strings, word pattern", "O(n)", "Do I need maps in both directions?", ["isomorphic-strings", "word-pattern"]),
      row("Consecutive sequence", "Find runs without sorting.", "longest consecutive sequence", "O(n)", "Start counting only from values whose predecessor is missing?", ["longest-consecutive-sequence"]),
      row("Count of counts", "Compare frequency shapes, not values.", "determine if two strings are close, unique occurrences", "O(n)", "Do I compare the multiset of counts?", ["determine-if-two-strings-are-close", "unique-number-of-occurrences"]),
      row("Rolling key / encoding", "Substrings or rows used as keys.", "repeated DNA sequences, equal row and column pairs", "O(n * k)", "Can I join the items into a string key, or hash a window?", ["repeated-dna-sequences", "equal-row-and-column-pairs"]),
    ],
    decisionTree: [
      choice("Need a partner value?", "Complement lookup"),
      choice("Depends on how often?", "Frequency map"),
      choice("Items share a signature?", "Group by canonical key"),
      choice("Only existence?", "Set"),
      choice("Distance between equal values?", "Last-seen index map"),
      choice("Subarrays with exact sum?", "Prefix sum + map"),
      choice("One-to-one mapping?", "Two maps"),
      choice("Runs of consecutive numbers?", "Set, start at run beginnings"),
    ],
    workflow: flow(
      step("Say what you would look up if lookups were free", "Using a map without knowing the key", ["two-sum", "subarray-sum-equals-k"]),
      step("Choose map (needs info) or set (needs existence)", "Storing counts you never read", ["contains-duplicate", "majority-element"]),
      step("Define the key precisely (sorted string, tuple, prefix)", "Keys that collide for different items", ["group-anagrams", "repeated-dna-sequences"]),
      step("Decide when to insert: before or after the check", "Matching an element with itself", ["two-sum", "contains-duplicate-ii"]),
      step("State average versus worst case and the memory cost", "Claiming O(1) worst case", ["longest-consecutive-sequence", "top-k-frequent-elements"]),
    ),
  },
  {
    id: "prefix-sum",
    title: "Prefix Sum",
    after: "sliding-window",
    description: "Pay O(n) once so every range question costs O(1). Pair it with a map to count subarrays.",
    patterns: [
      row("1-D prefix array", "Many range-sum queries on a static array.", "range sum query immutable", "O(n) build, O(1) query", "Does prefix[r + 1] - prefix[l] give the range?", ["range-sum-query-immutable"]),
      row("Pivot / balance point", "Left sum equals right sum.", "find pivot index", "O(n)", "Is right sum = total - left - nums[i]?", ["find-pivot-index"]),
      row("Prefix + hashmap count", "Count subarrays with sum exactly k.", "subarray sum equals k", "O(n)", "How many earlier prefixes equal current - k?", ["subarray-sum-equals-k"]),
      row("Prefix modulo", "Subarray sum divisible by k, or a multiple of k.", "continuous subarray sum, subarray sums divisible by k", "O(n)", "Do two prefixes with the same remainder bound a valid subarray?", ["continuous-subarray-sum", "subarray-sums-divisible-by-k"]),
      row("Balance as +1 / -1", "Equal numbers of two kinds.", "contiguous array", "O(n)", "If 0 becomes -1, is the target sum 0?", ["contiguous-array"]),
      row("Prefix and suffix products", "Each answer excludes one element.", "product of array except self", "O(n)", "Can a left pass and a right pass replace division?", ["product-of-array-except-self"]),
      row("2-D prefix sums", "Rectangle sums in a matrix.", "range sum query 2D immutable", "O(mn) build, O(1) query", "Do I add the two strips and subtract the overlap?", ["range-sum-query-2d-immutable"]),
      row("Difference array", "Many range updates, then one read.", "car pooling, corporate flight bookings", "O(n + updates)", "Add at l, subtract at r + 1, prefix-sum at the end?", ["car-pooling"]),
      row("Prefix XOR", "Range XOR queries.", "xor queries of a subarray", "O(n + q)", "Is xor(l..r) = px[r + 1] ^ px[l]?", ["xor-queries-of-a-subarray"]),
      row("Sum of distances", "Total absolute difference to every element.", "sum of absolute differences in a sorted array", "O(n)", "Split into left and right parts using prefix sums?", ["sum-of-absolute-differences-in-a-sorted-array"]),
    ],
    decisionTree: [
      choice("Many range sums, no updates?", "Prefix array"),
      choice("Count subarrays with sum k?", "Prefix + map"),
      choice("Divisible by k?", "Prefix remainder map"),
      choice("Equal 0s and 1s?", "Map 0 to -1, look for sum 0"),
      choice("Product except self?", "Prefix and suffix passes"),
      choice("Rectangle sums?", "2-D prefix"),
      choice("Many range updates?", "Difference array"),
      choice("Updates and queries mixed?", "Fenwick tree, not prefix sums"),
    ],
    workflow: flow(
      step("Spot repeated range work in the brute force", "Re-summing the same range for every query", ["range-sum-query-immutable", "find-pivot-index"]),
      step("Decide inclusive or exclusive prefix indexing", "Off-by-one with prefix[0]", ["range-sum-query-immutable", "range-sum-query-2d-immutable"]),
      step("For counting, seed the map with prefix 0 seen once", "Missing subarrays that start at index 0", ["subarray-sum-equals-k", "contiguous-array"]),
      step("Normalise negative remainders", "JavaScript % returning negative values", ["subarray-sums-divisible-by-k", "continuous-subarray-sum"]),
      step("Test all zeros, negatives, and k = 0", "Assuming all numbers are positive", ["subarray-sum-equals-k", "product-of-array-except-self"]),
    ),
  },
  {
    id: "strings",
    title: "Strings",
    after: "prefix-sum",
    description: "Most string questions are array questions over characters. Count, compare, or slide a window, and avoid building new strings in a loop.",
    patterns: [
      row("Character count", "Anagram, permutation, or ransom checks.", "valid anagram, ransom note, find the difference", "O(n)", "Is a 26-slot array enough, or do I need a map?", ["valid-anagram", "ransom-note"]),
      row("Two-pointer palindrome", "Check or build palindromes.", "valid palindrome, valid palindrome II", "O(n)", "Skip non-alphanumerics and compare lowercase?", ["valid-palindrome", "valid-palindrome-ii"]),
      row("Expand around centre", "Longest or count of palindromic substrings.", "longest palindromic substring, palindromic substrings", "O(n^2)", "Do I expand from each index and each gap?", ["longest-palindromic-substring", "palindromic-substrings"]),
      row("Window over characters", "Longest/shortest substring with a property.", "longest substring without repeating, minimum window", "O(n)", "What counts must the window keep?", ["longest-substring-without-repeating-characters", "minimum-window-substring"]),
      row("Common prefix", "Compare many strings from the start.", "longest common prefix", "O(total chars)", "Compare column by column, or sort and compare first and last?", ["longest-common-prefix"]),
      row("Parsing", "Convert text to numbers or tokens.", "string to integer, roman to integer, compare versions", "O(n)", "What are the states: sign, digits, overflow, stop?", ["string-to-integer-atoi", "roman-to-integer", "compare-version-numbers"]),
      row("Build with an array", "Many appends or edits.", "string compression, reverse words, zigzag", "O(n)", "Push to an array and join once?", ["string-compression", "reverse-words-in-a-string", "zigzag-conversion"]),
      row("Stack over characters", "Remove pairs or decode nested text.", "removing stars, decode string, make the string great", "O(n)", "Does each new character cancel with the top?", ["removing-stars-from-a-string", "decode-string"]),
      row("Canonical form", "Group or compare by a normalised key.", "group anagrams, unique email addresses", "O(n * k)", "What normalisation makes equal items identical?", ["group-anagrams", "unique-email-addresses"]),
      row("Rotation / repetition", "Is one string a rotation or repeat of another?", "rotate string, repeated substring", "O(n)", "Is b a substring of a + a?", ["rotate-string"]),
    ],
    decisionTree: [
      choice("Same letters, different order?", "Character count"),
      choice("Reads the same both ways?", "Two pointers or expand around centre"),
      choice("Best substring with a property?", "Sliding window"),
      choice("Text to number?", "Parse with explicit states"),
      choice("Many appends in a loop?", "Array then join"),
      choice("Pairs cancel or nesting?", "Stack"),
      choice("Group by sameness?", "Canonical key"),
      choice("Rotation check?", "Search in a + a"),
    ],
    workflow: flow(
      step("Ask about the character set (ASCII, lowercase, Unicode)", "Assuming 26 letters when input has digits and spaces", ["valid-palindrome", "valid-anagram"]),
      step("Treat the string as an array of characters", "Slicing substrings inside loops (hidden O(n^2))", ["longest-common-prefix", "reverse-words-in-a-string"]),
      step("Pick the pattern: count, window, two pointers, or stack", "Brute-forcing every substring", ["longest-substring-without-repeating-characters", "minimum-window-substring"]),
      step("Build output with an array and join once", "String concatenation in a hot loop", ["string-compression", "zigzag-conversion"]),
      step("Test empty, one character, all same, and spaces", "Failing on leading or trailing spaces", ["length-of-last-word", "string-to-integer-atoi"]),
    ),
  },
  {
    id: "string-algorithms",
    title: "String Algorithms (KMP, Z, Hashing)",
    after: "strings",
    description: "When naive substring search is too slow, precompute what you already matched so you never re-scan it.",
    patterns: [
      row("Naive search baseline", "Find a pattern in a text, small inputs.", "find the index of the first occurrence", "O(nm)", "Is n * m small enough to just compare at each start?", ["find-the-index-of-the-first-occurrence-in-a-string"]),
      row("KMP prefix function", "Pattern search without re-scanning matched text.", "strStr, shortest palindrome, repeated substring", "O(n + m)", "What is the longest proper prefix that is also a suffix?", ["find-the-index-of-the-first-occurrence-in-a-string"]),
      row("Z-algorithm", "Match lengths of every suffix against the prefix.", "pattern search via p + '$' + t", "O(n + m)", "Can I reuse the rightmost Z-box I have seen?"),
      row("Rolling hash (Rabin-Karp)", "Compare many fixed-length substrings.", "repeated DNA sequences, longest duplicate substring", "O(n) average", "Can I update the hash in O(1) when the window slides?", ["repeated-dna-sequences"]),
      row("Rotation via doubling", "Rotation and cyclic checks.", "rotate string", "O(n)", "Search b inside a + a?", ["rotate-string"]),
      row("Manacher", "All palindromic radii in linear time.", "longest palindromic substring", "O(n)", "Can a mirror around the current centre seed each radius?", ["longest-palindromic-substring"]),
      row("Trie / Aho-Corasick", "Search many patterns at once.", "stream of characters, word search II", "O(total length)", "Can a trie with failure links scan the text once?", ["stream-of-characters", "word-search-ii"]),
      row("Binary search + hashing", "Longest substring with a property (repeat, common).", "longest duplicate substring, longest common substring", "O(n log n)", "If length L works, does every shorter length also work?"),
    ],
    decisionTree: [
      choice("Single pattern, small inputs?", "Naive search"),
      choice("Single pattern, large inputs?", "KMP or Z"),
      choice("Many fixed-length windows?", "Rolling hash"),
      choice("Rotation question?", "Search in a + a"),
      choice("All palindromes, linear time?", "Manacher"),
      choice("Many patterns at once?", "Trie / Aho-Corasick"),
      choice("Longest length that works?", "Binary search plus hashing"),
    ],
    workflow: flow(
      step("Give the naive O(nm) solution and its limits", "Jumping straight to KMP without a baseline", ["find-the-index-of-the-first-occurrence-in-a-string", "rotate-string"]),
      step("Name which repeated work KMP or hashing removes", "Using an algorithm you cannot explain", ["find-the-index-of-the-first-occurrence-in-a-string", "repeated-dna-sequences"]),
      step("Build the helper array (lps or Z) on a small example", "Off-by-one in the failure function", ["find-the-index-of-the-first-occurrence-in-a-string", "longest-palindromic-substring"]),
      step("For hashing, pick base and modulus and handle collisions", "Trusting a hash match without checking", ["repeated-dna-sequences", "longest-palindromic-substring"]),
      step("Test an empty pattern, a pattern longer than the text, and all-same characters", "Worst case aaaa...b inputs", ["find-the-index-of-the-first-occurrence-in-a-string", "rotate-string"]),
    ),
  },
  {
    id: "queue",
    title: "Queue & Deque",
    after: "stack",
    description: "First in, first out. Use a queue for order of arrival and BFS, and a deque when both ends matter.",
    patterns: [
      row("Plain queue", "Process items in arrival order.", "number of recent calls, BFS", "O(1) per op", "Do items leave in the order they arrived?", ["number-of-recent-calls"]),
      row("BFS layers", "Shortest steps in an unweighted graph or tree levels.", "level order, rotting oranges", "O(V + E)", "Do I process the queue one level at a time?", ["binary-tree-level-order-traversal", "rotting-oranges"]),
      row("Monotonic deque", "Max or min of every window.", "sliding window maximum", "O(n)", "Pop smaller values from the back, expired indexes from the front?", ["sliding-window-maximum"]),
      row("Circular queue", "Fixed-size buffer with wrap-around.", "design circular queue", "O(1) per op", "Is tail = (head + size) % capacity?", ["design-circular-queue"]),
      row("Queue from stacks", "Implement FIFO with LIFO.", "implement queue using stacks", "O(1) amortized", "Refill the out stack only when empty?", ["implement-queue-using-stacks"]),
      row("Stack from queues", "Implement LIFO with FIFO.", "implement stack using queues", "O(n) push or pop", "Rotate the queue after each push?", ["implement-stack-using-queues"]),
      row("Round-robin simulation", "Turns rotate between players.", "dota2 senate, time needed to buy tickets", "O(n)", "Does the winner of a round re-enter at the back?", ["dota2-senate"]),
      row("Front-middle-back", "Insertions at both ends and the middle.", "design front middle back queue", "O(1) per op", "Two deques kept balanced?", ["design-front-middle-back-queue"]),
      row("0-1 BFS deque", "Edge weights are 0 or 1.", "minimum obstacle removal", "O(V + E)", "Push 0-weight moves to the front, 1-weight to the back?", ["minimum-obstacle-removal-to-reach-corner"]),
      row("Time window queue", "Count events inside the last t seconds.", "number of recent calls, hit counter", "O(1) amortized", "Pop from the front while the oldest is too old?", ["number-of-recent-calls"]),
    ],
    decisionTree: [
      choice("Arrival order matters?", "Queue"),
      choice("Fewest steps, unweighted?", "BFS"),
      choice("Max/min of every window?", "Monotonic deque"),
      choice("Fixed-size buffer?", "Circular queue"),
      choice("Players take turns?", "Round-robin queue"),
      choice("Weights only 0 or 1?", "0-1 BFS"),
      choice("Events in the last t seconds?", "Time window queue"),
      choice("Need both ends?", "Deque"),
    ],
    workflow: flow(
      step("Decide whether order of arrival or both ends matter", "Using shift() on a big array (O(n) each)", ["number-of-recent-calls", "sliding-window-maximum"]),
      step("Pick the structure: queue, deque, or circular buffer", "Rebuilding arrays on every pop", ["design-circular-queue", "design-front-middle-back-queue"]),
      step("For BFS, enqueue with the distance or process by level", "Losing track of which level a node is on", ["binary-tree-level-order-traversal", "rotting-oranges"]),
      step("For deques, state the invariant (decreasing values, valid indexes)", "Leaving expired indexes at the front", ["sliding-window-maximum", "minimum-obstacle-removal-to-reach-corner"]),
      step("Test empty queue operations and capacity edges", "Crashing on pop from empty", ["design-circular-queue", "implement-queue-using-stacks"]),
    ),
  },
  {
    id: "bst",
    title: "Binary Search Trees",
    after: "trees",
    description: "Left < node < right. Use the ordering to skip half the tree, and inorder traversal to read it sorted.",
    patterns: [
      row("Search by comparison", "Find, insert, or locate a value.", "search in a BST, insert into a BST", "O(h)", "Go left or right by comparing with the node?", ["search-in-a-binary-search-tree", "insert-into-a-binary-search-tree"]),
      row("Validate with bounds", "Check the BST property for the whole subtree.", "validate binary search tree", "O(n)", "Do I pass (low, high) bounds down?", ["validate-binary-search-tree"]),
      row("Inorder is sorted", "Kth smallest, min difference, or recover swapped nodes.", "kth smallest, minimum absolute difference, recover BST", "O(n)", "Does an inorder walk give me the sorted order?", ["kth-smallest-element-in-a-bst", "minimum-absolute-difference-in-bst", "recover-binary-search-tree"]),
      row("Delete with successor", "Remove a node with two children.", "delete node in a BST", "O(h)", "Replace with the inorder successor, then delete it?", ["delete-node-in-a-bst"]),
      row("LCA using order", "Common ancestor in a BST.", "lowest common ancestor of a BST", "O(h)", "Split point where p and q go different ways?", ["lowest-common-ancestor-of-a-binary-search-tree"]),
      row("Build balanced", "Create a BST from sorted data.", "convert sorted array to BST", "O(n)", "Pick the middle as root and recurse?", ["convert-sorted-array-to-binary-search-tree"]),
      row("Build from preorder", "Reconstruct a BST from its preorder.", "construct BST from preorder", "O(n)", "Use an upper bound to know when a subtree ends?", ["construct-binary-search-tree-from-preorder-traversal"]),
      row("Iterator with a stack", "next() and hasNext() in O(1) amortized.", "BST iterator", "O(h) memory", "Push the left spine, pop, then push the right child's left spine?", ["binary-search-tree-iterator"]),
      row("Trim / range", "Keep only values within [low, high].", "trim a BST, range sum of BST", "O(n)", "If the node is too small, is the answer in its right subtree?", ["trim-a-binary-search-tree"]),
      row("Two sum on BST", "Find a pair with a target sum.", "two sum IV", "O(n)", "Inorder to an array plus two pointers, or a set during DFS?", ["two-sum-iv-input-is-a-bst"]),
    ],
    decisionTree: [
      choice("Find or insert a value?", "Compare and go one way"),
      choice("Is it a valid BST?", "Pass bounds down"),
      choice("Kth or sorted order?", "Inorder traversal"),
      choice("Delete a node with two children?", "Inorder successor"),
      choice("Common ancestor?", "Split point by value"),
      choice("Sorted array to tree?", "Middle as root"),
      choice("next() in sorted order?", "Stack of the left spine"),
      choice("Keep a value range?", "Trim by bounds"),
    ],
    workflow: flow(
      step("Confirm it is a BST and whether duplicates exist", "Treating a plain binary tree as a BST", ["validate-binary-search-tree", "search-in-a-binary-search-tree"]),
      step("Use the ordering to visit one side only", "Visiting the whole tree for a lookup", ["lowest-common-ancestor-of-a-binary-search-tree", "insert-into-a-binary-search-tree"]),
      step("Reach for inorder when order matters", "Sorting values after a random traversal", ["kth-smallest-element-in-a-bst", "minimum-absolute-difference-in-bst"]),
      step("Handle the three delete cases: leaf, one child, two children", "Losing the subtree on delete", ["delete-node-in-a-bst", "trim-a-binary-search-tree"]),
      step("State O(h) and the skewed worst case O(n)", "Claiming O(log n) for every BST", ["binary-search-tree-iterator", "convert-sorted-array-to-binary-search-tree"]),
    ),
  },
  {
    id: "matrix",
    title: "Matrix / 2-D Grid",
    after: "graphs",
    description: "A grid is an array of rows. Get the indexing right, then traverse by layers, directions, or as a graph.",
    patterns: [
      row("Row/column scan", "Check every row, column, or box.", "valid sudoku, equal row and column pairs", "O(mn)", "Which sets or maps track rows, columns, and boxes?", ["valid-sudoku", "equal-row-and-column-pairs"]),
      row("Spiral traversal", "Visit in layers from the outside in.", "spiral matrix, spiral matrix II", "O(mn)", "Shrink top, right, bottom, left after each side?", ["spiral-matrix", "spiral-matrix-ii"]),
      row("Rotate / transpose", "Rotate 90 degrees in place.", "rotate image", "O(n^2)", "Transpose, then reverse each row?", ["rotate-image"]),
      row("In-place markers", "Mark cells without extra memory.", "set matrix zeroes, game of life", "O(mn), O(1) extra", "Can the first row/column or extra bits store the marks?", ["set-matrix-zeroes", "game-of-life"]),
      row("Sorted matrix search", "Rows and columns are sorted.", "search a 2D matrix, search a 2D matrix II", "O(log mn) or O(m + n)", "Start from the top-right corner and step left or down?", ["search-a-2d-matrix", "search-a-2d-matrix-ii"]),
      row("Grid as a graph", "Islands, regions, or shortest paths.", "number of islands, rotting oranges, 01 matrix", "O(mn)", "Do I use a directions array and a visited grid?", ["number-of-islands", "01-matrix"]),
      row("Grid DP", "Paths or squares built from neighbours.", "unique paths, maximal square, minimum path sum", "O(mn)", "Which neighbours does each cell depend on?", ["unique-paths", "maximal-square"]),
      row("Diagonals", "Work along diagonals or anti-diagonals.", "matrix diagonal sum, diagonal traverse", "O(mn)", "Is r - c or r + c constant on the diagonal?", ["matrix-diagonal-sum"]),
      row("Shift / flatten", "Treat the grid as one long array.", "shift 2D grid, search a 2D matrix", "O(mn)", "Is index i at row i / cols, column i % cols?", ["shift-2d-grid", "search-a-2d-matrix"]),
      row("2-D prefix sums", "Many rectangle sum queries.", "range sum query 2D", "O(mn) build", "Sum = big - top - left + overlap?", ["range-sum-query-2d-immutable"]),
    ],
    decisionTree: [
      choice("Check rows, columns, and boxes?", "Sets per row, column, box"),
      choice("Visit in layers?", "Spiral with four bounds"),
      choice("Rotate in place?", "Transpose and reverse"),
      choice("Mark without extra memory?", "Use first row/column or bits"),
      choice("Sorted rows and columns?", "Staircase from a corner"),
      choice("Connected regions or steps?", "BFS/DFS on the grid"),
      choice("Paths or squares from neighbours?", "Grid DP"),
      choice("Many rectangle sums?", "2-D prefix sums"),
    ],
    workflow: flow(
      step("Write rows = m, cols = n, and the index conventions", "Swapping rows and columns in the loops", ["spiral-matrix", "rotate-image"]),
      step("Define a directions array once", "Copy-pasting four neighbour checks", ["number-of-islands", "game-of-life"]),
      step("Check bounds before reading a neighbour", "Index out of range at the edges", ["01-matrix", "set-matrix-zeroes"]),
      step("Decide in-place versus a copy", "Overwriting values that are still needed", ["game-of-life", "set-matrix-zeroes"]),
      step("Test 1 x 1, 1 x n, and non-square grids", "Assuming the matrix is square", ["spiral-matrix", "search-a-2d-matrix"]),
    ),
  },
];
